
import { Era, TimelineNodeStub } from './types';

export const ERAS: Era[] = [
  {
    id: 'prelude',
    title: 'Prelude: The Thaw',
    yearRange: 'c. 12,000 BCE - 4000 BCE',
    introQuote: "Before cities rose, the ice had to fall.",
    description: "The world wasn't always ready for civilization. For thousands of years, humanity lived on the edge of glaciers, surviving wild climate swings. This era marks the dramatic end of the last Ice Age—a chaotic time of floods, rising seas, and a sudden, brutal freeze called the Younger Dryas. It is the final deep breath before history begins.",
    details: {
      concept: "The End of the Ice Age",
      explanation: "We often think history starts with pyramids, but the stage had to be set first. As the Earth warmed, huge ice sheets melted. Then, disaster struck: the Younger Dryas cold snap. Only after this chaos stabilized could humans settle down and build the first cities.",
      keyThemes: ['Climate Chaos', 'Megafauna Extinction', 'Survival & Adaptation', 'The First Stone Temples']
    }
  },
  {
  id: 'foundations',
  title: 'Early Cities & Bronze Age',
  yearRange: '4000 BCE - 1000 BCE',
  introQuote:
    "Civilization doesn’t start when humans get smart. It starts when we try to live together in giant, complicated groups.",
  description:
    "For most of human history, people lived in small bands or villages. They hunted, gathered, farmed, raised kids, gossiped, and told stories around the fire. Their brains were the same as ours — same emotions, same ability to love, hate, plan, and fear the future. What changes in this era isn’t the human brain. It’s the size of the experiments we run with it.\n\n" +
    "Between about 4000 and 3000 BCE, in a few lucky river valleys, people push farming way beyond the village level. In Mesopotamia, along the Tigris and Euphrates, cities like Uruk explode in size. In the Nile Valley, Egyptian towns knit together into a single kingdom under a pharaoh. In the Indus Valley, carefully planned cities like Mohenjo-Daro rise out of baked brick. In northern China, the ancestors of the Shang kings build walled settlements and start casting beautiful bronze ritual vessels.\n\n" +
    "This is the Bronze Age: a time when people discover that if you melt copper and mix in a little tin, you get bronze — a metal that keeps a sharp edge and doesn’t bend easily. Bronze tools cut more wood, dig better irrigation ditches, and carve more stone. Bronze weapons give armies a deadly advantage. But bronze has a weakness: tin is rare. That means long-distance trade, risky journeys, and politics built on fragile supply chains.\n\n" +
    "At the same time, record-keeping becomes too heavy for memory alone. Governments, temples, and merchants invent writing — first as simple number marks on clay, then as full writing systems like cuneiform and Egyptian hieroglyphs. Laws, myths, receipts, and royal propaganda can now survive long after the people who wrote them are dust. This is the moment when we move from prehistory (no writing) into history (we have written sources, even if they’re biased).\n\n" +
    "Zooming out even further: our era sits after a wild climate event called the Younger Dryas. Just as the last Ice Age was ending, Earth suddenly snapped back to colder conditions for about 1,200 years and then warmed again quickly. Some scientists think debris from a comet helped trigger this; many others argue that normal Earth systems (ice sheets, ocean currents, volcanoes) are enough to explain it. The debate is still going. What matters for our story is that by around 4000 BCE the climate has calmed down, farming has spread widely, and humans have had thousands of years to practice living in bigger communities.\n\n" +
    "The Bronze Age isn’t peaceful. Kings and queens claim they rule by the will of the gods. Slavery exists. Wars are common. Massive building projects like pyramids and city walls require enormous amounts of labor — sometimes taxed, sometimes forced. But there is also art, music, literature, and everyday kindness woven into all that power and fear.\n\n" +
    "Near the end of this era, around 1200–1100 BCE, the whole eastern Mediterranean world shakes. Palaces burn. Trade routes vanish. Some written languages disappear for centuries. Egyptian inscriptions talk about groups they call the “Sea Peoples” attacking by ship. At the same time, droughts, internal rebellions, and shifting military technology slam many Bronze Age kingdoms all at once. Historians call this cluster of disasters the Late Bronze Age Collapse. It doesn’t wipe out civilization, but it ends this first global experiment in city-states held together by bronze and long-distance trade.\n\n" +
    "Meanwhile, other parts of the world are running their own experiments. In China, the Shang kings use oracle bones and early Chinese characters to ask their ancestors questions. In Mesoamerica, the Olmec build giant stone heads and ritual centers. In Africa, early Bantu-speaking farmers begin migrations that will reshape the languages of half a continent. And modern tools like laser-scanning (LiDAR) are now revealing that dense, planned pre-Columbian cities existed under the forests of the Maya lowlands and the Amazon — proving that big, complex societies were more widespread than older textbooks claimed.\n\n" +
    "In short: this era is the dawn of large-scale civilization. Cities, writing, law codes, kings, queens, slavery, organized religion, international trade, and full-on civilizational collapse all show up here. Everything that comes later — from classical Greece to modern nation-states — stands on top of what people figured out (and messed up) in this Bronze Age world.",
  details: {
    concept: "What is the 'Bronze Age'?",
    explanation:
      "The Bronze Age is named after a metal recipe.\n\n" +
      "1. First came stone tools: sharp, easy to make, but brittle.\n" +
      "2. Then came pure copper: softer than stone, but you can melt and reuse it.\n" +
      "3. Finally, people discovered that if you melt copper and stir in a little tin, you get bronze: hard, sharp, and shiny.\n\n" +
      "Making bronze isn’t simple. You need miners to dig out copper and tin, smelters who know how to control high heat, and craftspeople who can cast tools and weapons in molds. You also need trade routes, because copper and tin are rarely found in the same place. That means caravans and ships carrying heavy ingots across deserts and seas, guarded by soldiers and taxed by rulers.\n\n" +
      "Because bronze is so useful, whoever controls the metal often controls the power. Bronze-armed chariot elites dominate battlefields. Temple and palace workshops turn bronze into status objects and sacred treasures. When the supply of tin or the safety of trade routes breaks down — because of climate stress, earthquakes, migrations, internal rebellions, or foreign invasions — the whole political and economic system wobbles.\n\n" +
      "By around 1200–1100 BCE, many of these bronze-based palace states in the eastern Mediterranean and Near East collapse or shrink. Egyptian texts blame mysterious 'Sea Peoples' for some of the attacks, but modern historians see a perfect storm: droughts, crop failures, elite infighting, refugees on the move, new styles of warfare, and plain bad luck. Afterward, iron slowly replaces bronze for tools and weapons, and new powers rise on the ruins of the old.\n\n" +
      "So when we say 'Bronze Age,' we don’t just mean a metal. We mean a whole system: farming surpluses, cities, kings, long-distance trade, specialized workers, written records, powerful armies — and the risk that all of this can fall apart.",
    keyThemes: [
      'From villages to the first true cities',
      'Bronze technology and long-distance trade',
      'The invention of writing and record-keeping',
      'God-kings, temples, and early states',
      'Empires, law codes, and social classes',
      'Collapse of the Bronze Age and the Sea Peoples',
    ],
  },
  },
  { 
    id: 'classical', 
    title: 'Classical Antiquity', 
    yearRange: '1000 BCE - 500 CE',
    introQuote: "The glory that was Greece, and the grandeur that was Rome.",
    description: "The era of superstars. Greece gives us democracy and philosophy, Rome builds a superpower, and China builds the Great Wall.",
    details: {
      concept: "The Age of Empires",
      explanation: "This era is defined by organization. It wasn't just about one city anymore; it was about conquering the whole known world. The Persians, Greeks, Romans, and Han Chinese built massive road systems, laws, and armies.\n\nIt's also when the 'Axial Age' happened—a specific time when Buddha, Confucius, Socrates, and Jewish prophets were all thinking about ethics and how to be a good person at roughly the same time.",
      keyThemes: ["Democracy vs. Empire", "The Silk Road Opens", "Philosophy & Science", "The Rise of Christianity & Buddhism"]
    }
  },
  {
    id: 'early_medieval',
    title: 'New Empires & Golden Ages',
    yearRange: '500 CE - 1000 CE',
    introQuote: "When old empires fall, new powers rise from the ashes.",
    description: "Rome has fallen in the West, but the world doesn't stop. In the East, the Byzantine Empire continues for another thousand years. In Arabia, a new religion—Islam—explodes outward, creating a vast caliphate stretching from Spain to Central Asia. The Islamic Golden Age begins: scholars in Baghdad translate ancient Greek texts, invent algebra, and advance medicine and astronomy far beyond anything Europe can manage.\n\nIn China, the Tang Dynasty presides over a golden age of poetry, art, and technological innovation. Gunpowder is invented. The Grand Canal connects north and south. In Japan, Buddhism shapes a new culture. In West Africa, the Ghana Empire controls the gold and salt trade.\n\nMeanwhile, in Europe, the old Roman infrastructure crumbles. Kings, knights, and castles emerge. It's a localized, dangerous world for peasants. But in the north, Vikings build incredible longships and raid—then trade and explore—reaching as far as Baghdad and even North America, 500 years before Columbus.\n\nThis era proves that 'Dark Ages' is a Eurocentric myth. While Europe struggled, much of the world flourished.",
    details: {
      concept: "Golden Ages Beyond Europe",
      explanation: "After Rome's collapse, Europe fragmented into small kingdoms, but this was an era of brilliance elsewhere. The Islamic Caliphates became centers of learning, preserving Greek philosophy and pioneering new sciences. Tang China reached cultural and technological heights. The label 'Dark Ages' only applies if you ignore most of the world.",
      keyThemes: ["Islamic Golden Age", "Tang Dynasty Innovation", "Byzantine Continuation", "Viking Exploration", "Feudal Europe Emerges"]
    }
  },
  {
    id: 'high_medieval',
    title: 'The Connected World',
    yearRange: '1000 CE - 1450 CE',
    introQuote: "The world gets smaller. Trade routes stretch from London to Beijing.",
    description: "This is the era when the world truly connects. In China, the Song Dynasty invents paper money, gunpowder weapons, and the compass. In West Africa, Mansa Musa's pilgrimage to Mecca is so lavish it crashes economies. In Cambodia, Angkor Wat rises as the largest religious monument in the world. In Mesoamerica, the Aztecs and Inca build sophisticated empires.\n\nThen come the Mongols. Genghis Khan and his successors conquer the largest land empire in history, stretching from Korea to Hungary. The Mongol Peace (Pax Mongolica) makes the Silk Road safer than ever before. Marco Polo travels from Venice to China. Ideas, technologies, and diseases flow across continents.\n\nIn Europe, Gothic cathedrals soar toward heaven. The first universities open in Bologna, Oxford, and Paris. The Crusades connect (and traumatize) the Christian and Islamic worlds. Magna Carta limits royal power in England.\n\nBut connectivity has a dark side. The Black Death travels along trade routes, killing a third of Eurasia's population. It's a reminder that when the world connects, everything—good and bad—spreads faster.",
    details: {
      concept: "The Mongol Peace & Global Exchange",
      explanation: "The Mongol Empire connected East and West like never before, creating safe passage along the Silk Road. This allowed unprecedented exchange of goods, ideas, and technologies—but also enabled the Black Death to spread across continents. The world was becoming one system, for better and worse.",
      keyThemes: ["The Mongol Empire", "Song Dynasty Innovation", "The Black Death", "Crusades & Conflict", "Mali & Great Zimbabwe"]
    }
  },
  {
    id: 'contact',
    title: 'Age of Contact',
    yearRange: '1450 CE - 1600 CE',
    introQuote: "The world's continents meet for the first time. Nothing will ever be the same.",
    description: "This is the era when separate worlds collide. Columbus reaches the Americas in 1492. Vasco da Gama sails around Africa to India. Magellan's expedition circumnavigates the globe. For the first time in history, all of Earth's inhabited continents are connected by ships and trade routes.\n\nThe consequences are world-changing. European diseases devastate the Americas, killing up to 90% of indigenous populations. The Columbian Exchange moves crops, animals, and people (including millions of enslaved Africans) across oceans. Silver from Peruvian mines flows to China, linking global economies.\n\nMeanwhile, three Islamic 'Gunpowder Empires' reach their zenith: the Ottomans (who conquer Constantinople and besiege Vienna), the Safavids in Persia, and the Mughals in India. These empires are rich, sophisticated, and militarily powerful—rivaling or surpassing European states.\n\nIn Europe, the printing press revolutionizes communication. Martin Luther challenges the Catholic Church, sparking the Protestant Reformation and decades of religious wars. The Renaissance flourishes in Italy with artists like Da Vinci and Michelangelo.\n\nThis era is about contact, connection, and catastrophe—all happening at once.",
    details: {
      concept: "The Columbian Exchange & Gunpowder Empires",
      explanation: "When Columbus reached the Americas, he didn't just 'discover' a new world—he connected two biological and cultural systems that had been separate for 12,000 years. The exchange of crops, animals, diseases, and people reshaped the entire planet. Meanwhile, the Ottoman, Safavid, and Mughal empires represented a different model of power: Islamic, sophisticated, and militarily advanced.",
      keyThemes: ["European Exploration", "Columbian Exchange", "Gunpowder Empires", "The Printing Press", "Protestant Reformation"]
    }
  },
  {
    id: 'renaissance',
    title: 'Renaissance & Scientific Revolution',
    yearRange: '1600 CE - 1700 CE',
    introQuote: "Mankind stops accepting ancient wisdom and starts testing it.",
    description: "This is the paradigm shift. For centuries, Europeans accepted ancient authorities—Aristotle for science, the Bible for truth, the Church for morality. Now, they start questioning everything.\n\nGalileo points his telescope at the sky and sees moons orbiting Jupiter, proving Earth isn't the center of the universe. Kepler discovers that planets move in ellipses, not perfect circles. Descartes declares 'I think, therefore I am,' making human reason the foundation of knowledge. By century's end, Isaac Newton publishes his *Principia Mathematica*, explaining gravity and motion with pure mathematics. The Scientific Method is born: observe, hypothesize, test, repeat.\n\nThis revolution isn't just in science. Shakespeare explores the human condition like never before. Artists master perspective, anatomy, and realism. Thinkers begin to see the world as a machine that can be understood through reason and experimentation.\n\nThe old world—where kings ruled by divine right, the Church controlled knowledge, and tradition was unquestionable—begins to crack. The modern world is being born.\n\nMeanwhile, the Thirty Years' War devastates Europe, the English Civil War executes a king, and the Tokugawa Shogunate unifies Japan, closing it to the outside world for two centuries.",
    details: {
      concept: "The Birth of Modern Science",
      explanation: "The Scientific Revolution wasn't just about discovering new facts—it was about creating a new way of thinking. Instead of accepting what ancient books said, scientists insisted on evidence, experimentation, and mathematics. This mindset would eventually be applied to politics, economics, and society itself.",
      keyThemes: ["The Scientific Method", "Galileo & Newton", "Baroque Art", "Shakespeare", "The Thirty Years' War"]
    }
  },
  {
    id: 'enlightenment',
    title: 'Age of Reason',
    yearRange: '1700 CE - 1789 CE',
    introQuote: "If reason can explain the stars, why can't it design a government?",
    description: "The Scientific Revolution proved that reason and evidence can unlock nature's secrets. Now, Enlightenment thinkers ask: what if we apply that same method to society?\n\nPhilosophers like John Locke argue that governments should be based on consent, not divine right. Voltaire mocks religious superstition and champions free speech. Rousseau imagines a 'social contract' where people govern themselves. Benjamin Franklin experiments with electricity and helps draft a constitution. Adam Smith explains how markets work. Diderot compiles all human knowledge into the *Encyclopédie*.\n\nMeanwhile, absolute monarchs like Louis XIV, Peter the Great, and Frederick the Great build powerful centralized states. They use Enlightenment ideas to modernize their armies and bureaucracies—but not to give up their thrones.\n\nThe contradiction is unstable. If humans have natural rights, why should kings rule by birth? If evidence matters, why trust ancient traditions? By 1776, American colonists declare independence using Enlightenment logic. In 1789, the French Revolution explodes, putting Reason on trial. The old order is dying.\n\nReason is the revolutionary force of this era—and once unleashed, it can't be put back in the box.",
    details: {
      concept: "Reason Applied to Politics",
      explanation: "The Enlightenment took the Scientific Method—observation, logic, evidence—and applied it to human society. If the universe follows natural laws, maybe government should too. This wasn't just philosophy; it was the intellectual foundation for modern democracy, human rights, and revolutions that toppled monarchies.",
      keyThemes: ["Enlightenment Philosophy", "Absolute Monarchy vs. Liberty", "American Revolution", "French Revolution Begins", "Rise of Reason"]
    }
  },
  { 
    id: 'industry', 
    title: 'Industry & Revolution', 
    yearRange: '1789 CE - 1914 CE',
    introQuote: "Steam and steel changed the rhythm of life forever.",
    description: "The world gets loud. Machines replace hand-tools, trains replace horses, and empires scramble to own everything.",
    details: {
      concept: "The Industrial Revolution",
      explanation: "For 10,000 years, the fastest a human could travel was on a horse. Suddenly, we had Steam Engines! \n\nFactories popped up, cities became crowded and smoky, and mass production made things cheap. European countries used this new technology to take over almost all of Africa and Asia (Imperialism), leading to massive wealth for some and tragedy for others.",
      keyThemes: ["Steam Power & Factories", "The Abolition of Slavery", "Imperialism", "Invention of Photography & Electricity"]
    }
  },
  { 
    id: 'global_conflict', 
    title: 'The World Wars', 
    yearRange: '1914 CE - 1945 CE',
    introQuote: "The war to end all wars... until the next one.",
    description: "Technology turns violent. The entire world fights twice, leading to tragedies like the Holocaust and the atomic bomb.",
    details: {
      concept: "Total War",
      explanation: "New technology (tanks, planes, machine guns) made war deadlier than ever. WWI destroyed the old empires. WWII was a fight against fascism (Hitler & Mussolini).\n\nIt was a dark time, but it also forced rapid invention—radar, penicillin, jet engines, and nuclear energy were all developed to win these wars.",
      keyThemes: ["Trench Warfare", "The Great Depression", "The Holocaust", "The Atomic Bomb"]
    }
  },
  { 
    id: 'modern', 
    title: 'Atomic & Digital Age', 
    yearRange: '1945 CE - Present',
    introQuote: "We went to the moon, and then we went online.",
    description: "The Cold War scares everyone, but computers connect everyone. We map the human genome and face a changing climate.",
    details: {
      concept: "Information Age",
      explanation: "After WWII, the USA and USSR faced off in a 'Cold War'—building thousands of nukes but never firing them. Instead, they raced to space.\n\nThen came the microchip. Computers shrunk from room-sized to pocket-sized. The Internet connected 8 billion people, changing how we learn, talk, and work faster than any era before.",
      keyThemes: ["The Cold War", "Civil Rights Movement", "Space Exploration", "The Internet & AI"]
    }
  },
];

export const INITIAL_NODES: TimelineNodeStub[] = [
  // --- PRELUDE (~10,500 BCE) ---
  { id: 'younger_dryas_reset', title: 'Younger Dryas: The Great Freeze', year: 'c. 10,800 BCE', eraId: 'prelude', region: 'Global', tags: ['Science', 'Climate', 'Myth'] },

  // --- EARLY CITIES & BRONZE AGE (4000 BCE - 1000 BCE) ---
  { id: 'neolithic_revolution', title: 'The Agricultural Revolution', year: 'c. 10,000 BCE', eraId: 'foundations', region: 'Fertile Crescent', tags: ['Science'] },
  { id: 'animal_domestication', title: 'Domestication of Animals', year: 'c. 8000 BCE', eraId: 'foundations', region: 'Middle East', tags: ['Science'] },
  { id: 'bronze_age_begins', title: 'Bronze Age Begins', year: 'c. 3300 BCE', eraId: 'foundations', region: 'Middle East', tags: ['Science'] },
  { id: 'wheel', title: 'Invention of the Wheel', year: 'c. 3500 BCE', eraId: 'foundations', region: 'Mesopotamia', tags: ['Science'] },
  { id: 'sumer_writing', title: 'Invention of Cuneiform', year: 'c. 3400 BCE', eraId: 'foundations', region: 'Mesopotamia', tags: ['Science', 'Literature'] },
  { id: 'uruk', title: 'Uruk Grows into First Big City', year: 'c. 3200 BCE', eraId: 'foundations', region: 'Mesopotamia', tags: ['Politics', 'Science'] },
  { id: 'hieroglyphs', title: 'Egyptian Hieroglyphs Standardized', year: 'c. 3200 BCE', eraId: 'foundations', region: 'Egypt', tags: ['Literature', 'Art'] },
  { id: 'narmer', title: 'Unification of Upper & Lower Egypt', year: 'c. 3100 BCE', eraId: 'foundations', region: 'Egypt', tags: ['Politics', 'Military'] },
  { id: 'otzi', title: 'Ötzi the Iceman Lives', year: 'c. 3300 BCE', eraId: 'foundations', region: 'Europe', tags: ['Science'] },
  { id: 'imhotep', title: 'Imhotep & The Step Pyramid', year: 'c. 2630 BCE', eraId: 'foundations', region: 'Egypt', tags: ['Art', 'Science'] },
  { id: 'pyramids', title: 'Great Pyramid of Giza', year: 'c. 2580 BCE', eraId: 'foundations', region: 'Egypt', tags: ['Art', 'Politics', 'Science'] },
  { id: 'ur_standard', title: 'The Standard of Ur', year: 'c. 2600 BCE', eraId: 'foundations', region: 'Mesopotamia', tags: ['Art', 'Military'] },
  { id: 'indus_script', title: 'Indus Valley Script Appears', year: 'c. 2600 BCE', eraId: 'foundations', region: 'India/Pakistan', tags: ['Literature', 'Science'] },
  { id: 'indus_cities', title: 'Rise of Mohenjo-Daro', year: 'c. 2500 BCE', eraId: 'foundations', region: 'India/Pakistan', tags: ['Science', 'Politics'] },
  { id: 'stonehenge', title: 'Construction of Stonehenge', year: 'c. 2500 BCE', eraId: 'foundations', region: 'England', tags: ['Religion', 'Science'] },
  { id: 'kerma', title: 'Kingdom of Kerma in Nubia', year: 'c. 2500 BCE', eraId: 'foundations', region: 'Nubia (Sudan)', tags: ['Politics', 'Military'] },
  { id: 'sargon', title: 'Sargon of Akkad: First Empire', year: 'c. 2334 BCE', eraId: 'foundations', region: 'Mesopotamia', tags: ['Military', 'Politics'] },
  { id: 'gilgamesh', title: 'Epic of Gilgamesh Written', year: 'c. 2100 BCE', eraId: 'foundations', region: 'Mesopotamia', tags: ['Literature'] },
  { id: 'bronze_spreads', title: 'Bronze Tools Spread Across Eurasia', year: 'c. 2000 BCE', eraId: 'foundations', region: 'Europe/Asia', tags: ['Science', 'Military'] },
  { id: 'bronze_age_trade', title: 'Bronze Age Global Trade Networks', year: 'c. 2000 BCE', eraId: 'foundations', region: 'Eurasia', tags: ['Exploration', 'Politics'] },
  { id: 'minoans', title: 'Minoan Civilization on Crete', year: 'c. 2000 BCE', eraId: 'foundations', region: 'Crete (Greece)', tags: ['Art', 'Politics', 'Science'] },
  { id: 'hammurabi', title: 'Code of Hammurabi', year: 'c. 1750 BCE', eraId: 'foundations', region: 'Babylon', tags: ['Politics', 'Literature'] },
  { id: 'abraham', title: 'Abraham & Origins of Monotheism', year: 'c. 1800 BCE', eraId: 'foundations', region: 'Canaan', tags: ['Religion'] },
  { id: 'assyrian_trade', title: 'Old Assyrian Trade Colonies', year: 'c. 1900 BCE', eraId: 'foundations', region: 'Anatolia/Mesopotamia', tags: ['Politics', 'Science'] },
  { id: 'shang', title: 'Shang Dynasty & Bronze Age', year: 'c. 1600 BCE', eraId: 'foundations', region: 'China', tags: ['Art', 'Military'] },
  { id: 'hittites', title: 'Hittite Empire in Anatolia', year: 'c. 1600 BCE', eraId: 'foundations', region: 'Anatolia', tags: ['Military', 'Politics'] },
  { id: 'mycenaeans', title: 'Mycenaean Greece & Warrior Kings', year: 'c. 1600 BCE', eraId: 'foundations', region: 'Greece', tags: ['Military', 'Politics'] },
  { id: 'bantu_migration', title: 'Early Bantu Migrations Begin', year: 'c. 1500 BCE', eraId: 'foundations', region: 'Africa', tags: ['Exploration', 'Politics'] },
  { id: 'hatshepsut', title: 'Reign of Pharaoh Hatshepsut', year: 'c. 1478 BCE', eraId: 'foundations', region: 'Egypt', tags: ['Politics'] },
  { id: 'akhenaten', title: "Akhenaten's Religious Revolution", year: 'c. 1353 BCE', eraId: 'foundations', region: 'Egypt', tags: ['Religion', 'Politics'] },
  { id: 'tut', title: "Tutankhamun's Restoration", year: 'c. 1332 BCE', eraId: 'foundations', region: 'Egypt', tags: ['Politics', 'Religion'] },
  { id: 'uluburun', title: 'Uluburun Shipwreck: Bronze Age Super-Cargo', year: 'c. 1300 BCE', eraId: 'foundations', region: 'Mediterranean', tags: ['Exploration', 'Science'] },
  { id: 'kadesh', title: 'Battle of Kadesh (First Peace Treaty)', year: '1274 BCE', eraId: 'foundations', region: 'Syria', tags: ['Military', 'Politics'] },
  { id: 'trojan_war', title: 'The Trojan War (Myth & Memory)', year: 'c. 1200 BCE', eraId: 'foundations', region: 'Turkey/Greece', tags: ['Military', 'Literature'] },
  { id: 'olmec', title: 'Olmec Civilization Rises', year: 'c. 1200 BCE', eraId: 'foundations', region: 'Mesoamerica', tags: ['Art', 'Religion'] },
  { id: 'oracle_bones', title: 'Shang Oracle Bones & Chinese Writing', year: 'c. 1200 BCE', eraId: 'foundations', region: 'China', tags: ['Religion', 'Literature'] },
  { id: 'sea_peoples', title: 'Collapse of Bronze Age / Sea Peoples', year: 'c. 1177 BCE', eraId: 'foundations', region: 'Mediterranean', tags: ['Military', 'Politics'] },
  { id: 'iron_age_begins', title: 'Iron Age Begins in the Near East', year: 'c. 1100 BCE', eraId: 'foundations', region: 'Anatolia/Levant', tags: ['Science', 'Military'] },
  { id: 'phoenicians', title: 'Phoenician Alphabet Developed', year: 'c. 1050 BCE', eraId: 'foundations', region: 'Lebanon', tags: ['Literature', 'Science'] },
  { id: 'zoroastrianism', title: 'Teachings of Zoroaster (Zarathustra)', year: 'c. 1000 BCE', eraId: 'foundations', region: 'Persia', tags: ['Religion'] },

  // --- CLASSICAL ANTIQUITY (1000 BCE - 500 CE) ---
  { id: 'david', title: 'Reign of King David', year: 'c. 1000 BCE', eraId: 'classical', region: 'Israel', tags: ['Politics', 'Religion'] },
  { id: 'olympics', title: 'First Olympic Games in Greece', year: '776 BCE', eraId: 'classical', region: 'Greece', tags: ['Art', 'Religion'] },
  { id: 'chavin', title: 'Chavín Culture', year: 'c. 900 BCE', eraId: 'classical', region: 'Peru', tags: ['Art', 'Religion'] },
  { id: 'parthian_empire', title: 'Rise of the Parthian Empire', year: '247 BCE', eraId: 'classical', region: 'Persia', tags: ['Politics', 'Military'] },
  { id: 'homer', title: 'Homer Composes Iliad & Odyssey', year: 'c. 750 BCE', eraId: 'classical', region: 'Greece', tags: ['Literature'] },
  { id: 'rome_founded', title: 'Founding of Rome', year: 'c. 753 BCE', eraId: 'classical', region: 'Italy', tags: ['Politics'] },
  { id: 'nineveh', title: 'Library of Ashurbanipal', year: 'c. 660 BCE', eraId: 'classical', region: 'Assyria', tags: ['Literature', 'Science'] },
  { id: 'babylon_gardens', title: 'Nebuchadnezzar II & Hanging Gardens', year: 'c. 600 BCE', eraId: 'classical', region: 'Babylon', tags: ['Art', 'Science'] },
  { id: 'roman_republic', title: 'Roman Republic Established', year: '509 BCE', eraId: 'classical', region: 'Rome', tags: ['Politics'] },
  { id: 'cyrus', title: 'Cyrus the Great & Persian Empire', year: '550 BCE', eraId: 'classical', region: 'Persia', tags: ['Politics', 'Military'] },
  { id: 'buddha', title: 'Life of Siddhartha Gautama', year: 'c. 480 BCE', eraId: 'classical', region: 'India/Nepal', tags: ['Religion', 'Philosophy'] },
  { id: 'confucius', title: 'Confucius Teaches Ethics', year: 'c. 479 BCE', eraId: 'classical', region: 'China', tags: ['Philosophy'] },
  { id: 'marathon', title: 'Battle of Marathon', year: '490 BCE', eraId: 'classical', region: 'Greece', tags: ['Military'] },
  { id: 'pericles', title: 'Golden Age of Athens (Pericles)', year: 'c. 450 BCE', eraId: 'classical', region: 'Greece', tags: ['Philosophy', 'Politics', 'Art'] },
  { id: 'peloponnesian_war', title: 'Peloponnesian War Begins', year: '431 BCE', eraId: 'classical', region: 'Greece', tags: ['Military', 'Politics'] },
  { id: 'socrates', title: 'Trial of Socrates', year: '399 BCE', eraId: 'classical', region: 'Greece', tags: ['Philosophy'] },
  { id: 'plato_academy', title: 'Plato Founds the Academy', year: 'c. 387 BCE', eraId: 'classical', region: 'Greece', tags: ['Philosophy'] },
  { id: 'aristotle_lyceum', title: 'Aristotle Teaches at the Lyceum', year: 'c. 335 BCE', eraId: 'classical', region: 'Greece', tags: ['Philosophy', 'Science'] },
  { id: 'alexander', title: 'Alexander the Great\'s Conquests', year: '334 BCE', eraId: 'classical', region: 'Macedonia/Persia', tags: ['Military', 'Exploration'] },
  { id: 'alexandria_lib', title: 'Library of Alexandria Founded', year: 'c. 283 BCE', eraId: 'classical', region: 'Egypt', tags: ['Science', 'Literature'] },
  { id: 'hellenistic_science', title: 'Hellenistic Science Flourishes', year: 'c. 250 BCE', eraId: 'classical', region: 'Egypt/Greece', tags: ['Science'] },
  { id: 'mauryan_empire', title: 'Chandragupta Founds Mauryan Empire', year: 'c. 321 BCE', eraId: 'classical', region: 'India', tags: ['Politics', 'Military'] },
  { id: 'ashoka', title: 'Ashoka\'s Edicts', year: 'c. 268 BCE', eraId: 'classical', region: 'India', tags: ['Politics', 'Religion'] },
  { id: 'qin_shi_huang', title: 'Qin Shi Huang Unifies China', year: '221 BCE', eraId: 'classical', region: 'China', tags: ['Politics', 'Military'] },
  { id: 'terracotta', title: 'Terracotta Army Buried', year: '210 BCE', eraId: 'classical', region: 'China', tags: ['Art'] },
  { id: 'hannibal', title: 'Hannibal Crosses the Alps', year: '218 BCE', eraId: 'classical', region: 'Europe', tags: ['Military'] },
  { id: 'silk_road', title: 'Han Dynasty Opens Silk Road', year: 'c. 130 BCE', eraId: 'classical', region: 'China/Central Asia', tags: ['Exploration', 'Politics'] },
  { id: 'caesar', title: 'Julius Caesar Assassinated', year: '44 BCE', eraId: 'classical', region: 'Rome', tags: ['Politics', 'Military'] },
  { id: 'cleopatra', title: 'Death of Cleopatra', year: '30 BCE', eraId: 'classical', region: 'Egypt', tags: ['Politics'] },
  { id: 'augustus', title: 'Augustus & Pax Romana', year: '27 BCE', eraId: 'classical', region: 'Rome', tags: ['Politics'] },
  { id: 'jesus', title: 'Ministry of Jesus', year: 'c. 30 CE', eraId: 'classical', region: 'Judea', tags: ['Religion'] },
  { id: 'jewish_wars', title: 'Jewish Wars Against Rome', year: '66 CE', eraId: 'classical', region: 'Judea', tags: ['Military', 'Politics'] },
  { id: 'boudica', title: 'Boudica\'s Revolt', year: '60 CE', eraId: 'classical', region: 'Britain', tags: ['Military', 'Politics'] },
  { id: 'pompeii', title: 'Destruction of Pompeii', year: '79 CE', eraId: 'classical', region: 'Italy', tags: ['Science'] },
  { id: 'paper', title: 'Cai Lun Invents Paper', year: '105 CE', eraId: 'classical', region: 'China', tags: ['Science', 'Literature'] },
  { id: 'hadrian', title: 'Hadrian\'s Wall Built', year: '122 CE', eraId: 'classical', region: 'Britain', tags: ['Military', 'Politics'] },
  { id: 'roman_engineering', title: 'Roman Engineering & Concrete', year: 'c. 100 CE', eraId: 'classical', region: 'Rome', tags: ['Science'] },
  { id: 'early_christianity', title: 'Christianity Spreads Underground', year: 'c. 150 CE', eraId: 'classical', region: 'Roman Empire', tags: ['Religion'] },
  { id: 'sassanian_empire', title: 'Sassanian Empire Founded', year: '224 CE', eraId: 'classical', region: 'Persia', tags: ['Politics', 'Military'] },
  { id: 'teotihuacan', title: 'Teotihuacan City Flourishes', year: 'c. 250 CE', eraId: 'classical', region: 'Mesoamerica', tags: ['Art', 'Religion'] },
  { id: 'mayan_classic', title: 'Mayan Classic Period Peak', year: 'c. 250 CE', eraId: 'classical', region: 'Mesoamerica', tags: ['Science', 'Art'] },
  { id: 'diocletian_split', title: 'Diocletian Splits Roman Empire', year: '285 CE', eraId: 'classical', region: 'Rome', tags: ['Politics'] },
  { id: 'constantine', title: 'Constantine Legalizes Christianity', year: '313 CE', eraId: 'classical', region: 'Rome', tags: ['Religion', 'Politics'] },
  { id: 'nicene_council', title: 'Council of Nicaea', year: '325 CE', eraId: 'classical', region: 'Rome', tags: ['Religion', 'Politics'] },
  { id: 'gupta', title: 'Gupta Golden Age (Zero Invented)', year: 'c. 320 CE', eraId: 'classical', region: 'India', tags: ['Science', 'Art'] },
  { id: 'fall_rome', title: 'Fall of Western Rome', year: '476 CE', eraId: 'classical', region: 'Rome', tags: ['Politics', 'Military'] },

  // --- NEW EMPIRES & GOLDEN AGES (500 CE - 1000 CE) ---
  { id: 'arthur', title: 'Legends of King Arthur', year: 'c. 500 CE', eraId: 'early_medieval', region: 'Britain', tags: ['Literature'] },
  { id: 'clovis', title: 'Clovis Unites the Franks', year: '509 CE', eraId: 'early_medieval', region: 'France', tags: ['Politics'] },
  { id: 'justinian', title: 'Justinian Code & Hagia Sophia', year: '537 CE', eraId: 'early_medieval', region: 'Byzantium', tags: ['Art', 'Politics'] },
  { id: 'plague_justinian', title: 'Plague of Justinian', year: '541 CE', eraId: 'early_medieval', region: 'Europe/Asia', tags: ['Science'] },
  { id: 'sui_canal', title: 'Grand Canal of China Built', year: '605 CE', eraId: 'early_medieval', region: 'China', tags: ['Science', 'Politics'] },
  { id: 'islam_origins', title: 'Muhammad & Origins of Islam', year: '610 CE', eraId: 'early_medieval', region: 'Arabia', tags: ['Religion'] },
  { id: 'umayyad_caliphate', title: 'Umayyad Caliphate Expands', year: '661 CE', eraId: 'early_medieval', region: 'Middle East', tags: ['Politics', 'Military'] },
  { id: 'tang_dynasty', title: 'Tang Dynasty Golden Age', year: '618 CE', eraId: 'early_medieval', region: 'China', tags: ['Art', 'Politics'] },
  { id: 'nara_period', title: 'Nara Period & Tōdai-ji Temple', year: '710 CE', eraId: 'early_medieval', region: 'Japan', tags: ['Art', 'Religion'] },
  { id: 'wu_zetian', title: 'Empress Wu Zetian', year: '690 CE', eraId: 'early_medieval', region: 'China', tags: ['Politics'] },
  { id: 'tours', title: 'Battle of Tours', year: '732 CE', eraId: 'early_medieval', region: 'France', tags: ['Military'] },
  { id: 'iconoclasm', title: 'Byzantine Iconoclasm Crisis', year: '726 CE', eraId: 'early_medieval', region: 'Byzantium', tags: ['Religion', 'Politics'] },
  { id: 'battle_talas', title: 'Battle of Talas', year: '751 CE', eraId: 'early_medieval', region: 'Central Asia', tags: ['Military', 'Science'] },
  { id: 'an_lushan', title: 'An Lushan Rebellion', year: '755 CE', eraId: 'early_medieval', region: 'China', tags: ['Military', 'Politics'] },
  { id: 'house_wisdom', title: 'House of Wisdom Founded', year: 'c. 750 CE', eraId: 'early_medieval', region: 'Baghdad', tags: ['Science', 'Philosophy'] },
  { id: 'lindisfarne', title: 'Vikings Raid Lindisfarne', year: '793 CE', eraId: 'early_medieval', region: 'England', tags: ['Military', 'Exploration'] },
  { id: 'charlemagne', title: 'Charlemagne Crowned Emperor', year: '800 CE', eraId: 'early_medieval', region: 'Europe', tags: ['Politics', 'Religion'] },
  { id: 'carolingian_renaissance', title: 'Carolingian Renaissance', year: 'c. 800 CE', eraId: 'early_medieval', region: 'Europe', tags: ['Art', 'Literature'] },
  { id: 'khmer', title: 'Jayavarman II Founds Khmer Empire', year: '802 CE', eraId: 'early_medieval', region: 'Cambodia', tags: ['Politics'] },
  { id: 'gunpowder', title: 'Invention of Gunpowder', year: 'c. 850 CE', eraId: 'early_medieval', region: 'China', tags: ['Science', 'Military'] },
  { id: 'viking_trade', title: 'Viking Trade Networks', year: 'c. 850 CE', eraId: 'early_medieval', region: 'Northern Europe', tags: ['Exploration', 'Politics'] },
  { id: 'alfred', title: 'Alfred the Great Defends Wessex', year: '878 CE', eraId: 'early_medieval', region: 'England', tags: ['Military', 'Politics'] },
  { id: 'feudalism_system', title: 'Feudalism Emerges in Europe', year: 'c. 900 CE', eraId: 'early_medieval', region: 'Europe', tags: ['Politics'] },
  { id: 'ghana', title: 'Ghana Empire (Gold & Salt)', year: 'c. 900 CE', eraId: 'early_medieval', region: 'West Africa', tags: ['Politics'] },
  { id: 'maya_collapse', title: 'Classic Maya Cities Decline', year: 'c. 900 CE', eraId: 'early_medieval', region: 'Mesoamerica', tags: ['Politics', 'Science'] },
  { id: 'polynesian_settlement', title: 'Polynesians Reach New Zealand', year: 'c. 900 CE', eraId: 'early_medieval', region: 'Pacific', tags: ['Exploration'] },
  { id: 'erik_red', title: 'Erik the Red Settles Greenland', year: '985 CE', eraId: 'early_medieval', region: 'North Atlantic', tags: ['Exploration'] },

  // --- THE CONNECTED WORLD (1000 CE - 1450 CE) ---
  { id: 'leif', title: 'Leif Erikson Reaches Vinland', year: 'c. 1000 CE', eraId: 'high_medieval', region: 'North America', tags: ['Exploration'] },
  { id: 'agricultural_revolution_medieval', title: 'Medieval Agricultural Revolution', year: 'c. 1000 CE', eraId: 'high_medieval', region: 'Europe', tags: ['Science'] },
  { id: 'song_dynasty', title: 'Song Dynasty & Paper Money', year: '960 CE', eraId: 'high_medieval', region: 'China', tags: ['Politics', 'Science'] },
  { id: 'tale_genji', title: 'The Tale of Genji Written', year: 'c. 1008 CE', eraId: 'high_medieval', region: 'Japan', tags: ['Literature', 'Art'] },
  { id: 'schism', title: 'The Great Schism', year: '1054 CE', eraId: 'high_medieval', region: 'Europe', tags: ['Religion'] },
  { id: 'hastings', title: 'Battle of Hastings', year: '1066 CE', eraId: 'high_medieval', region: 'England', tags: ['Military', 'Politics'] },
  { id: 'university', title: 'University of Bologna Founded', year: '1088 CE', eraId: 'high_medieval', region: 'Italy', tags: ['Science', 'Philosophy'] },
  { id: 'reconquista', title: 'The Reconquista Intensifies', year: 'c. 1085 CE', eraId: 'high_medieval', region: 'Spain', tags: ['Military', 'Religion'] },
  { id: 'crusades', title: 'The First Crusade', year: '1096 CE', eraId: 'high_medieval', region: 'Middle East', tags: ['Religion', 'Military'] },
  { id: 'angkor_wat', title: 'Construction of Angkor Wat', year: 'c. 1113 CE', eraId: 'high_medieval', region: 'Cambodia', tags: ['Art', 'Religion'] },
  { id: 'kamakura', title: 'Kamakura Shogunate in Japan', year: '1185 CE', eraId: 'high_medieval', region: 'Japan', tags: ['Politics', 'Military'] },
  { id: 'hildegard', title: 'Hildegard of Bingen', year: 'c. 1150 CE', eraId: 'high_medieval', region: 'Germany', tags: ['Religion', 'Science'] },
  { id: 'gothic_engineering', title: 'Gothic Cathedrals & Engineering', year: 'c. 1150 CE', eraId: 'high_medieval', region: 'Europe', tags: ['Science', 'Art'] },
  { id: 'hanseatic_league', title: 'Hanseatic League Forms', year: 'c. 1200 CE', eraId: 'high_medieval', region: 'Northern Europe', tags: ['Politics'] },
  { id: 'saladin', title: 'Saladin Recaptures Jerusalem', year: '1187 CE', eraId: 'high_medieval', region: 'Middle East', tags: ['Military', 'Politics'] },
  { id: 'delhi_sultanate', title: 'Delhi Sultanate Founded', year: '1206 CE', eraId: 'high_medieval', region: 'India', tags: ['Politics', 'Religion'] },
  { id: 'genghis', title: 'Genghis Khan Unites Mongols', year: '1206 CE', eraId: 'high_medieval', region: 'Mongolia', tags: ['Military', 'Politics'] },
  { id: 'magna_carta', title: 'Magna Carta Signed', year: '1215 CE', eraId: 'high_medieval', region: 'England', tags: ['Politics'] },
  { id: 'baghdad_sack', title: 'Mongol Siege of Baghdad', year: '1258 CE', eraId: 'high_medieval', region: 'Iraq', tags: ['Military'] },
  { id: 'marco_polo', title: 'Travels of Marco Polo', year: '1271 CE', eraId: 'high_medieval', region: 'Asia', tags: ['Exploration'] },
  { id: 'aquinas', title: 'Thomas Aquinas: Summa Theologica', year: '1274 CE', eraId: 'high_medieval', region: 'Italy', tags: ['Philosophy', 'Religion'] },
  { id: 'william_wallace', title: 'William Wallace & Scottish Wars', year: '1297 CE', eraId: 'high_medieval', region: 'Scotland', tags: ['Military'] },
  { id: 'mali_empire', title: 'Mansa Musa\'s Pilgrimage', year: '1324 CE', eraId: 'high_medieval', region: 'West Africa', tags: ['Politics', 'Religion'] },
  { id: 'tenochtitlan', title: 'Founding of Tenochtitlan', year: '1325 CE', eraId: 'high_medieval', region: 'Mexico', tags: ['Politics'] },
  { id: 'great_zimbabwe', title: 'Great Zimbabwe Flourishes', year: 'c. 1300 CE', eraId: 'high_medieval', region: 'Southern Africa', tags: ['Politics', 'Art'] },
  { id: 'swahili_cities', title: 'Swahili Coast City-States Trade', year: 'c. 1300 CE', eraId: 'high_medieval', region: 'East Africa', tags: ['Politics', 'Exploration'] },
  { id: 'hundred_years', title: 'Hundred Years\' War Begins', year: '1337 CE', eraId: 'high_medieval', region: 'France/England', tags: ['Military'] },
  { id: 'black_death', title: 'The Black Death Peaked', year: '1347 CE', eraId: 'high_medieval', region: 'Europe/Asia', tags: ['Science'] },
  { id: 'black_death_aftermath', title: 'After the Plague: Social Revolution', year: 'c. 1360 CE', eraId: 'high_medieval', region: 'Europe', tags: ['Politics'] },
  { id: 'chucer', title: 'Chaucer: Canterbury Tales', year: 'c. 1387 CE', eraId: 'high_medieval', region: 'England', tags: ['Literature'] },
  { id: 'zheng_he', title: 'Voyages of Zheng He', year: '1405 CE', eraId: 'high_medieval', region: 'China', tags: ['Exploration', 'Politics'] },
  { id: 'forbidden_city', title: 'Forbidden City Completed', year: '1420 CE', eraId: 'high_medieval', region: 'China', tags: ['Art', 'Politics'] },
  { id: 'joan_arc', title: 'Joan of Arc Executed', year: '1431 CE', eraId: 'high_medieval', region: 'France', tags: ['Religion', 'Military'] },
  { id: 'inca_pachacuti', title: 'Pachacuti Expands Inca Empire', year: '1438 CE', eraId: 'high_medieval', region: 'Peru', tags: ['Politics', 'Military'] },
  { id: 'aztec_empire', title: 'Aztec Triple Alliance Forms', year: '1428 CE', eraId: 'high_medieval', region: 'Mexico', tags: ['Politics', 'Military'] },

  // --- AGE OF CONTACT (1450 CE - 1600 CE) ---
  { id: 'gutenberg', title: 'Gutenberg Printing Press', year: 'c. 1440 CE', eraId: 'contact', region: 'Germany', tags: ['Science', 'Literature'] },
  { id: 'constantinople', title: 'Fall of Constantinople', year: '1453 CE', eraId: 'contact', region: 'Turkey', tags: ['Military', 'Politics'] },
  { id: 'wars_roses', title: 'Wars of the Roses', year: '1455 CE', eraId: 'contact', region: 'England', tags: ['Military', 'Politics'] },
  { id: 'benin_bronzes', title: 'Benin Bronzes Cast in West Africa', year: 'c. 1500 CE', eraId: 'contact', region: 'West Africa', tags: ['Art'] },
  { id: 'columbus', title: 'Columbus Reaches Americas', year: '1492 CE', eraId: 'contact', region: 'Americas', tags: ['Exploration'] },
  { id: 'columbian_exchange', title: 'The Columbian Exchange Impact', year: 'c. 1500 CE', eraId: 'contact', region: 'Global', tags: ['Science', 'Politics'] },
  { id: 'da_vinci', title: 'Da Vinci Paints Last Supper', year: '1498 CE', eraId: 'contact', region: 'Italy', tags: ['Art', 'Science'] },
  { id: 'songhai_empire', title: 'Songhai Empire Flourishes', year: 'c. 1500 CE', eraId: 'contact', region: 'West Africa', tags: ['Politics'] },
  { id: 'kingdom_kongo', title: 'Kingdom of Kongo Meets Portuguese', year: 'c. 1500 CE', eraId: 'contact', region: 'Central Africa', tags: ['Politics'] },
  { id: 'safavid', title: 'Rise of Safavid Empire', year: '1501 CE', eraId: 'contact', region: 'Persia', tags: ['Politics', 'Religion'] },
  { id: 'michelangelo', title: 'Michelangelo Paints Sistine Chapel', year: '1512 CE', eraId: 'contact', region: 'Italy', tags: ['Art'] },
  { id: 'machiavelli', title: 'Machiavelli writes The Prince', year: '1513 CE', eraId: 'contact', region: 'Italy', tags: ['Politics', 'Literature'] },
  { id: 'luther', title: 'Martin Luther\'s 95 Theses', year: '1517 CE', eraId: 'contact', region: 'Germany', tags: ['Religion', 'Politics'] },
  { id: 'magellan', title: 'Magellan Circumnavigates Globe', year: '1519 CE', eraId: 'contact', region: 'Global', tags: ['Exploration'] },
  { id: 'cortes', title: 'Cortes Conquers Aztecs', year: '1521 CE', eraId: 'contact', region: 'Mexico', tags: ['Military', 'Politics'] },
  { id: 'atlantic_slave_trade', title: 'Atlantic Slave Trade Begins', year: 'c. 1520 CE', eraId: 'contact', region: 'Atlantic', tags: ['Politics'] },
  { id: 'pizarro', title: 'Pizarro Conquers the Inca', year: '1532 CE', eraId: 'contact', region: 'Peru', tags: ['Military', 'Politics'] },
  { id: 'china_stops_exploring', title: 'China Ends Ocean Voyages', year: '1433 CE', eraId: 'contact', region: 'China', tags: ['Politics'] },
  { id: 'suleiman', title: 'Suleiman the Magnificent', year: '1520 CE', eraId: 'contact', region: 'Ottoman Empire', tags: ['Politics', 'Military'] },
  { id: 'price_revolution', title: 'The Price Revolution', year: 'c. 1550 CE', eraId: 'contact', region: 'Europe', tags: ['Politics'] },
  { id: 'henry_viii', title: 'Henry VIII Act of Supremacy', year: '1534 CE', eraId: 'contact', region: 'England', tags: ['Religion', 'Politics'] },
  { id: 'copernicus', title: 'Copernicus: Heliocentrism', year: '1543 CE', eraId: 'contact', region: 'Poland', tags: ['Science'] },
  { id: 'ivan_terrible', title: 'Ivan the Terrible Crowned Tsar', year: '1547 CE', eraId: 'contact', region: 'Russia', tags: ['Politics'] },
  { id: 'akbar', title: 'Akbar the Great Rules Mughal India', year: '1556 CE', eraId: 'contact', region: 'India', tags: ['Politics', 'Religion'] },
  { id: 'elizabeth', title: 'Elizabeth I Coronation', year: '1558 CE', eraId: 'contact', region: 'England', tags: ['Politics'] },
  { id: 'manila_galleons', title: 'Manila Galleon Trade Begins', year: '1565 CE', eraId: 'contact', region: 'Pacific', tags: ['Exploration', 'Politics'] },
  { id: 'armada', title: 'Defeat of Spanish Armada', year: '1588 CE', eraId: 'contact', region: 'England/Spain', tags: ['Military'] },
  { id: 'shakespeare', title: 'Shakespeare\'s Globe Theatre', year: '1599 CE', eraId: 'contact', region: 'England', tags: ['Literature', 'Art'] },

  // --- RENAISSANCE & SCIENTIFIC REVOLUTION (1600 CE - 1700 CE) ---
  { id: 'edo_period', title: 'Tokugawa Shogunate Begins', year: '1603 CE', eraId: 'renaissance', region: 'Japan', tags: ['Politics'] },
  { id: 'jamestown', title: 'Jamestown Colony Founded', year: '1607 CE', eraId: 'renaissance', region: 'North America', tags: ['Politics'] },
  { id: 'galileo', title: 'Galileo\'s Telescope', year: '1609 CE', eraId: 'renaissance', region: 'Italy', tags: ['Science'] },
  { id: 'thirty_years', title: 'Thirty Years\' War Begins', year: '1618 CE', eraId: 'renaissance', region: 'Europe', tags: ['Military', 'Religion'] },
  { id: 'mayflower', title: 'Mayflower Compact', year: '1620 CE', eraId: 'renaissance', region: 'North America', tags: ['Politics'] },
  { id: 'dutch_golden_age', title: 'Dutch Golden Age', year: 'c. 1620 CE', eraId: 'renaissance', region: 'Netherlands', tags: ['Politics', 'Art'] },
  { id: 'harvey', title: 'Harvey Discovers Blood Circulation', year: '1628 CE', eraId: 'renaissance', region: 'England', tags: ['Science'] },
  { id: 'tulip_mania', title: 'Tulip Mania: First Financial Bubble', year: '1637 CE', eraId: 'renaissance', region: 'Netherlands', tags: ['Politics'] },
  { id: 'taj_mahal', title: 'Construction of Taj Mahal', year: '1632 CE', eraId: 'renaissance', region: 'India', tags: ['Art', 'Religion'] },
  { id: 'descartes', title: 'Descartes: "I think, therefore I am"', year: '1637 CE', eraId: 'renaissance', region: 'France', tags: ['Philosophy'] },
  { id: 'louis_xiv', title: 'Louis XIV "Sun King" Reign', year: '1643 CE', eraId: 'renaissance', region: 'France', tags: ['Politics'] },
  { id: 'qing', title: 'Qing Dynasty Established', year: '1644 CE', eraId: 'renaissance', region: 'China', tags: ['Politics'] },
  { id: 'english_civil_war', title: 'English Civil War', year: '1642 CE', eraId: 'renaissance', region: 'England', tags: ['Military', 'Politics'] },
  { id: 'london_fire', title: 'Great Fire of London', year: '1666 CE', eraId: 'renaissance', region: 'England', tags: ['Science'] },
  { id: 'newton', title: 'Newton\'s Principia Mathematica', year: '1687 CE', eraId: 'renaissance', region: 'England', tags: ['Science'] },
  { id: 'locke', title: 'John Locke: Two Treatises of Government', year: '1689 CE', eraId: 'renaissance', region: 'England', tags: ['Philosophy', 'Politics'] },
  { id: 'glorious_rev', title: 'The Glorious Revolution', year: '1688 CE', eraId: 'renaissance', region: 'England', tags: ['Politics'] },
  { id: 'salem', title: 'Salem Witch Trials', year: '1692 CE', eraId: 'renaissance', region: 'USA', tags: ['Religion'] },
  { id: 'peter_great', title: 'Peter the Great Westernizes Russia', year: '1696 CE', eraId: 'renaissance', region: 'Russia', tags: ['Politics'] },

  // --- AGE OF REASON (1700 CE - 1789 CE) ---
  { id: 'steam_newcomen', title: 'Newcomen Steam Engine', year: '1712 CE', eraId: 'enlightenment', region: 'England', tags: ['Science'] },
  { id: 'bach', title: 'Bach Brandenburg Concertos', year: '1721 CE', eraId: 'enlightenment', region: 'Germany', tags: ['Art'] },
  { id: 'coffeehouses_salons', title: 'Coffeehouses & Salons Spread Ideas', year: 'c. 1720 CE', eraId: 'enlightenment', region: 'Europe', tags: ['Philosophy', 'Politics'] },
  { id: 'agricultural_revolution_enlightenment', title: 'Agricultural Revolution in Britain', year: 'c. 1750 CE', eraId: 'enlightenment', region: 'Britain', tags: ['Science'] },
  { id: 'middle_passage', title: 'The Middle Passage at Its Peak', year: 'c. 1750 CE', eraId: 'enlightenment', region: 'Atlantic', tags: ['Politics'] },
  { id: 'encyclopedie', title: 'Diderot\'s Encyclopédie Published', year: '1751 CE', eraId: 'enlightenment', region: 'France', tags: ['Literature', 'Science'] },
  { id: 'franklin', title: 'Benjamin Franklin\'s Kite Experiment', year: '1752 CE', eraId: 'enlightenment', region: 'USA', tags: ['Science'] },
  { id: 'seven_years', title: 'Seven Years\' War', year: '1756 CE', eraId: 'enlightenment', region: 'Global', tags: ['Military'] },
  { id: 'lisbon_earthquake', title: 'Lisbon Earthquake Shakes Faith', year: '1755 CE', eraId: 'enlightenment', region: 'Portugal', tags: ['Science', 'Philosophy'] },
  { id: 'voltaire', title: 'Voltaire Writes Candide', year: '1759 CE', eraId: 'enlightenment', region: 'France', tags: ['Literature', 'Philosophy'] },
  { id: 'catherine', title: 'Catherine the Great', year: '1762 CE', eraId: 'enlightenment', region: 'Russia', tags: ['Politics'] },
  { id: 'watt_steam', title: 'James Watt Improves Steam Engine', year: '1769 CE', eraId: 'enlightenment', region: 'Scotland', tags: ['Science'] },
  { id: 'cook', title: 'Captain Cook Reaches Australia', year: '1770 CE', eraId: 'enlightenment', region: 'Oceania', tags: ['Exploration'] },
  { id: 'boston_tea', title: 'Boston Tea Party', year: '1773 CE', eraId: 'enlightenment', region: 'USA', tags: ['Politics'] },
  { id: 'declaration', title: 'US Declaration of Independence', year: '1776 CE', eraId: 'enlightenment', region: 'USA', tags: ['Politics'] },
  { id: 'wealth_nations', title: 'Adam Smith: Wealth of Nations', year: '1776 CE', eraId: 'enlightenment', region: 'Scotland', tags: ['Literature', 'Politics'] },
  { id: 'mozart', title: 'Mozart Composes in Vienna', year: 'c. 1781 CE', eraId: 'enlightenment', region: 'Austria', tags: ['Art'] },
  { id: 'yorktown', title: 'Battle of Yorktown (American Victory)', year: '1781 CE', eraId: 'enlightenment', region: 'USA', tags: ['Military', 'Politics'] },
  { id: 'constitution', title: 'US Constitution Signed', year: '1787 CE', eraId: 'enlightenment', region: 'USA', tags: ['Politics'] },
  { id: 'first_fleet', title: 'First Fleet Arrives in Sydney', year: '1788 CE', eraId: 'enlightenment', region: 'Australia', tags: ['Exploration', 'Politics'] },

  // --- INDUSTRY & REVOLUTION (1789 CE - 1914 CE) ---
  { id: 'french_rev', title: 'Storming of the Bastille', year: '1789 CE', eraId: 'industry', region: 'France', tags: ['Politics'] },
  { id: 'why_industrial_revolution', title: 'Why the Industrial Revolution Began in Britain', year: 'c. 1780 CE', eraId: 'industry', region: 'Britain', tags: ['Science', 'Politics'] },
  { id: 'haiti_rev', title: 'Haitian Revolution', year: '1791 CE', eraId: 'industry', region: 'Haiti', tags: ['Politics', 'Military'] },
  { id: 'wollstonecraft', title: 'Rights of Woman Published', year: '1792 CE', eraId: 'industry', region: 'England', tags: ['Philosophy', 'Politics'] },
  { id: 'smallpox_vaccine', title: 'Jenner invents Smallpox Vaccine', year: '1796 CE', eraId: 'industry', region: 'England', tags: ['Science'] },
  { id: 'rosetta', title: 'Discovery of Rosetta Stone', year: '1799 CE', eraId: 'industry', region: 'Egypt', tags: ['Science', 'Literature'] },
  { id: 'napoleon_crown', title: 'Napoleon Crowned Emperor', year: '1804 CE', eraId: 'industry', region: 'France', tags: ['Politics', 'Military'] },
  { id: 'slave_trade_ban_uk', title: 'Britain Abolishes Slave Trade', year: '1807 CE', eraId: 'industry', region: 'UK', tags: ['Politics'] },
  { id: 'lewis_clark', title: 'Lewis & Clark Expedition', year: '1804 CE', eraId: 'industry', region: 'USA', tags: ['Exploration'] },
  { id: 'beethoven', title: 'Beethoven\'s 5th Symphony', year: '1808 CE', eraId: 'industry', region: 'Germany', tags: ['Art'] },
  { id: 'bolivar', title: 'Simon Bolivar\'s Admirable Campaign', year: '1813 CE', eraId: 'industry', region: 'South America', tags: ['Politics', 'Military'] },
  { id: 'waterloo', title: 'Battle of Waterloo', year: '1815 CE', eraId: 'industry', region: 'Belgium', tags: ['Military'] },
  { id: 'shaka_zulu', title: 'Shaka Zulu Forms Empire', year: '1816 CE', eraId: 'industry', region: 'South Africa', tags: ['Military'] },
  { id: 'monroe', title: 'Monroe Doctrine', year: '1823 CE', eraId: 'industry', region: 'USA', tags: ['Politics'] },
  { id: 'braille', title: 'Louis Braille Invents Writing System', year: '1824 CE', eraId: 'industry', region: 'France', tags: ['Science', 'Literature'] },
  { id: 'trail_tears', title: 'The Trail of Tears', year: '1831 CE', eraId: 'industry', region: 'USA', tags: ['Politics'] },
  { id: 'photography', title: 'Daguerreotype Photography', year: '1839 CE', eraId: 'industry', region: 'France', tags: ['Science', 'Art'] },
  { id: 'opium_war', title: 'First Opium War', year: '1839 CE', eraId: 'industry', region: 'China', tags: ['Military', 'Politics'] },
  { id: 'telegraph', title: 'First Telegraph Message', year: '1844 CE', eraId: 'industry', region: 'USA', tags: ['Science'] },
  { id: 'potato_famine', title: 'Irish Potato Famine', year: '1845 CE', eraId: 'industry', region: 'Ireland', tags: ['Politics', 'Science'] },
  { id: 'marx', title: 'The Communist Manifesto', year: '1848 CE', eraId: 'industry', region: 'Germany', tags: ['Philosophy', 'Politics'] },
  { id: 'nationalism_rises', title: 'Rise of Nationalism in Europe', year: 'c. 1848 CE', eraId: 'industry', region: 'Europe', tags: ['Politics'] },
  { id: 'seneca_falls', title: 'Seneca Falls Women\'s Rights Convention', year: '1848 CE', eraId: 'industry', region: 'USA', tags: ['Politics'] },
  { id: 'working_conditions', title: 'Factory Working Conditions Crisis', year: 'c. 1850 CE', eraId: 'industry', region: 'Britain', tags: ['Politics'] },
  { id: 'perry_japan', title: 'Commodore Perry Opens Japan', year: '1853 CE', eraId: 'industry', region: 'Japan', tags: ['Politics'] },
  { id: 'crimean_war', title: 'Crimean War (Florence Nightingale)', year: '1853 CE', eraId: 'industry', region: 'Russia/Turkey', tags: ['Military', 'Science'] },
  { id: 'taiping', title: 'Taiping Rebellion in China', year: '1850 CE', eraId: 'industry', region: 'China', tags: ['Military', 'Politics'] },
  { id: 'indian_rebellion', title: 'Indian Rebellion Against British Rule', year: '1857 CE', eraId: 'industry', region: 'India', tags: ['Military', 'Politics'] },
  { id: 'darwin', title: 'On the Origin of Species', year: '1859 CE', eraId: 'industry', region: 'England', tags: ['Science'] },
  { id: 'civil_war', title: 'US Civil War Begins', year: '1861 CE', eraId: 'industry', region: 'USA', tags: ['Military', 'Politics'] },
  { id: 'emancipation', title: 'Emancipation Proclamation', year: '1863 CE', eraId: 'industry', region: 'USA', tags: ['Politics'] },
  { id: 'slavery_abolished_us', title: 'Slavery Abolished in USA (13th Amendment)', year: '1865 CE', eraId: 'industry', region: 'USA', tags: ['Politics'] },
  { id: 'pasteur', title: 'Pasteurization Invented', year: '1864 CE', eraId: 'industry', region: 'France', tags: ['Science'] },
  { id: 'meiji', title: 'Meiji Restoration', year: '1868 CE', eraId: 'industry', region: 'Japan', tags: ['Politics'] },
  { id: 'suez', title: 'Suez Canal Opens', year: '1869 CE', eraId: 'industry', region: 'Egypt', tags: ['Science', 'Politics'] },
  { id: 'second_industrial_revolution', title: 'Second Industrial Revolution: Steel & Electricity', year: 'c. 1870 CE', eraId: 'industry', region: 'Global', tags: ['Science'] },
  { id: 'social_darwinism', title: 'Social Darwinism Justifies Imperialism', year: 'c. 1870 CE', eraId: 'industry', region: 'Europe', tags: ['Philosophy', 'Politics'] },
  { id: 'germany_unite', title: 'Unification of Germany', year: '1871 CE', eraId: 'industry', region: 'Germany', tags: ['Politics'] },
  { id: 'telephone', title: 'Bell Invents Telephone', year: '1876 CE', eraId: 'industry', region: 'USA', tags: ['Science'] },
  { id: 'lightbulb', title: 'Edison Invents Light Bulb', year: '1879 CE', eraId: 'industry', region: 'USA', tags: ['Science'] },
  { id: 'zulu_wars', title: 'Anglo-Zulu War', year: '1879 CE', eraId: 'industry', region: 'South Africa', tags: ['Military', 'Politics'] },
  { id: 'scramble_africa', title: 'Scramble for Africa', year: '1881 CE', eraId: 'industry', region: 'Africa', tags: ['Politics', 'Military'] },
  { id: 'berlin_conf', title: 'Berlin Conference', year: '1884 CE', eraId: 'industry', region: 'Europe', tags: ['Politics'] },
  { id: 'benz', title: 'Benz Patent-Motorwagen', year: '1886 CE', eraId: 'industry', region: 'Germany', tags: ['Science'] },
  { id: 'van_gogh', title: 'Van Gogh: Starry Night', year: '1889 CE', eraId: 'industry', region: 'France', tags: ['Art'] },
  { id: 'xray', title: 'Discovery of X-Rays', year: '1895 CE', eraId: 'industry', region: 'Germany', tags: ['Science'] },
  { id: 'radio', title: 'Marconi Sends Radio Signal', year: '1901 CE', eraId: 'industry', region: 'Italy/UK', tags: ['Science'] },
  { id: 'flight', title: 'Wright Brothers First Flight', year: '1903 CE', eraId: 'industry', region: 'USA', tags: ['Science'] },
  { id: 'curie', title: 'Marie Curie Wins Nobel', year: '1903 CE', eraId: 'industry', region: 'France', tags: ['Science'] },
  { id: 'einstein_sr', title: 'Einstein\'s Special Relativity', year: '1905 CE', eraId: 'industry', region: 'Switzerland', tags: ['Science'] },
  { id: 'ford_t', title: 'Ford Model T Introduced', year: '1908 CE', eraId: 'industry', region: 'USA', tags: ['Science'] },
  { id: 'titanic', title: 'Sinking of the Titanic', year: '1912 CE', eraId: 'industry', region: 'Atlantic', tags: ['Science'] },
  { id: 'boxer_rebellion', title: 'Boxer Rebellion in China', year: '1899 CE', eraId: 'industry', region: 'China', tags: ['Military', 'Politics'] },
  { id: 'mexican_revolution', title: 'Mexican Revolution Begins', year: '1910 CE', eraId: 'industry', region: 'Mexico', tags: ['Politics', 'Military'] },

  // --- THE WORLD WARS (1914 CE - 1945 CE) ---
  { id: 'archduke', title: 'Assassination of Archduke Ferdinand', year: '1914 CE', eraId: 'global_conflict', region: 'Bosnia', tags: ['Politics', 'Military'] },
  { id: 'ww1', title: 'World War I Begins', year: '1914 CE', eraId: 'global_conflict', region: 'Global', tags: ['Military'] },
  { id: 'somme', title: 'Battle of the Somme', year: '1916 CE', eraId: 'global_conflict', region: 'France', tags: ['Military'] },
  { id: 'russian_rev', title: 'Russian Revolution', year: '1917 CE', eraId: 'global_conflict', region: 'Russia', tags: ['Politics'] },
  { id: 'spanish_flu', title: 'Spanish Flu Pandemic', year: '1918 CE', eraId: 'global_conflict', region: 'Global', tags: ['Science'] },
  { id: 'versailles', title: 'Treaty of Versailles', year: '1919 CE', eraId: 'global_conflict', region: 'France', tags: ['Politics'] },
  { id: 'ottoman_collapse', title: 'Collapse of the Ottoman Empire', year: '1922 CE', eraId: 'global_conflict', region: 'Turkey/Middle East', tags: ['Politics'] },
  { id: 'league_of_nations', title: 'League of Nations Founded', year: '1920 CE', eraId: 'global_conflict', region: 'Switzerland', tags: ['Politics'] },
  { id: 'suffrage', title: 'Women\'s Suffrage (19th Amendment)', year: '1920 CE', eraId: 'global_conflict', region: 'USA', tags: ['Politics'] },
  { id: 'roaring_twenties', title: 'The Roaring Twenties Culture', year: 'c. 1925 CE', eraId: 'global_conflict', region: 'USA/Europe', tags: ['Art'] },
  { id: 'mussolini', title: 'Mussolini\'s Fascists Take Power', year: '1922 CE', eraId: 'global_conflict', region: 'Italy', tags: ['Politics'] },
  { id: 'weimar_hyperinflation', title: 'Weimar Germany Hyperinflation Crisis', year: '1923 CE', eraId: 'global_conflict', region: 'Germany', tags: ['Politics'] },
  { id: 'insulin', title: 'Discovery of Insulin', year: '1921 CE', eraId: 'global_conflict', region: 'Canada', tags: ['Science'] },
  { id: 'tut_tomb', title: 'Discovery of Tutankhamun\'s Tomb', year: '1922 CE', eraId: 'global_conflict', region: 'Egypt', tags: ['Exploration'] },
  { id: 'penicillin', title: 'Fleming Discovers Penicillin', year: '1928 CE', eraId: 'global_conflict', region: 'UK', tags: ['Science'] },
  { id: 'stock_crash', title: 'Wall Street Crash', year: '1929 CE', eraId: 'global_conflict', region: 'USA', tags: ['Politics'] },
  { id: 'gandhi_salt', title: 'Gandhi\'s Salt March', year: '1930 CE', eraId: 'global_conflict', region: 'India', tags: ['Politics'] },
  { id: 'japanese_imperialism', title: 'Japan Invades Manchuria', year: '1931 CE', eraId: 'global_conflict', region: 'China/Japan', tags: ['Military', 'Politics'] },
  { id: 'hitler_rise', title: 'Hitler Becomes Chancellor', year: '1933 CE', eraId: 'global_conflict', region: 'Germany', tags: ['Politics'] },
  { id: 'nanking', title: 'Rape of Nanking', year: '1937 CE', eraId: 'global_conflict', region: 'China', tags: ['Military'] },
  { id: 'kristallnacht', title: 'Kristallnacht Pogrom', year: '1938 CE', eraId: 'global_conflict', region: 'Germany', tags: ['Politics', 'Military'] },
  { id: 'ww2_start', title: 'Invasion of Poland (WWII)', year: '1939 CE', eraId: 'global_conflict', region: 'Europe', tags: ['Military'] },
  { id: 'penicillin_mass', title: 'Mass Production of Penicillin', year: '1940 CE', eraId: 'global_conflict', region: 'UK/USA', tags: ['Science'] },
  { id: 'battle_britain', title: 'Battle of Britain', year: '1940 CE', eraId: 'global_conflict', region: 'UK', tags: ['Military'] },
  { id: 'pearl_harbor', title: 'Attack on Pearl Harbor', year: '1941 CE', eraId: 'global_conflict', region: 'USA/Pacific', tags: ['Military'] },
  { id: 'midway', title: 'Battle of Midway', year: '1942 CE', eraId: 'global_conflict', region: 'Pacific', tags: ['Military'] },
  { id: 'stalingrad', title: 'Battle of Stalingrad', year: '1942 CE', eraId: 'global_conflict', region: 'Russia', tags: ['Military'] },
  { id: 'turing', title: 'Alan Turing Cracks Enigma', year: '1942 CE', eraId: 'global_conflict', region: 'UK', tags: ['Science', 'Military'] },
  { id: 'resistance_movements', title: 'Resistance Movements Across Occupied Europe', year: 'c. 1943 CE', eraId: 'global_conflict', region: 'Europe', tags: ['Military', 'Politics'] },
  { id: 'd_day', title: 'D-Day Landings', year: '1944 CE', eraId: 'global_conflict', region: 'France', tags: ['Military'] },
  { id: 'bretton_woods', title: 'Bretton Woods: Designing Global Economy', year: '1944 CE', eraId: 'global_conflict', region: 'USA', tags: ['Politics'] },
  { id: 'yalta_conference', title: 'Yalta Conference: Dividing Post-War World', year: '1945 CE', eraId: 'global_conflict', region: 'Crimea', tags: ['Politics'] },
  { id: 'holocaust_lib', title: 'Liberation of Auschwitz', year: '1945 CE', eraId: 'global_conflict', region: 'Poland', tags: ['Military', 'Politics'] },
  { id: 'hiroshima', title: 'Atomic Bombing of Hiroshima', year: '1945 CE', eraId: 'global_conflict', region: 'Japan', tags: ['Military', 'Science'] },
  { id: 'nagasaki', title: 'Atomic Bombing of Nagasaki', year: '1945 CE', eraId: 'global_conflict', region: 'Japan', tags: ['Military', 'Science'] },
  { id: 'nuremberg', title: 'Nuremberg War Crimes Trials', year: '1945 CE', eraId: 'global_conflict', region: 'Germany', tags: ['Politics'] },
  { id: 'un_founded', title: 'Founding of the UN', year: '1945 CE', eraId: 'global_conflict', region: 'USA', tags: ['Politics'] },

  // --- ATOMIC & DIGITAL AGE (1945 CE - Present) ---
  { id: 'eniac', title: 'ENIAC (First Electronic Computer)', year: '1946 CE', eraId: 'modern', region: 'USA', tags: ['Science'] },
  { id: 'india_indep', title: 'Indian Independence & Partition', year: '1947 CE', eraId: 'modern', region: 'India/Pakistan', tags: ['Politics'] },
  { id: 'israel', title: 'Establishment of Israel', year: '1948 CE', eraId: 'modern', region: 'Middle East', tags: ['Politics'] },
  { id: 'mao', title: 'Mao Declares People\'s Republic', year: '1949 CE', eraId: 'modern', region: 'China', tags: ['Politics'] },
  { id: 'korean_war', title: 'Korean War Begins', year: '1950 CE', eraId: 'modern', region: 'Korea', tags: ['Military', 'Politics'] },
  { id: 'dna', title: 'Watson & Crick Discover DNA Structure', year: '1953 CE', eraId: 'modern', region: 'UK', tags: ['Science'] },
  { id: 'rosa_parks', title: 'Rosa Parks Bus Boycott', year: '1955 CE', eraId: 'modern', region: 'USA', tags: ['Politics'] },
  { id: 'ghana_independence', title: 'Ghana Gains Independence', year: '1957 CE', eraId: 'modern', region: 'West Africa', tags: ['Politics'] },
  { id: 'sputnik', title: 'Sputnik Launched', year: '1957 CE', eraId: 'modern', region: 'USSR', tags: ['Science', 'Exploration'] },
  { id: 'cuban_missile', title: 'Cuban Missile Crisis', year: '1962 CE', eraId: 'modern', region: 'Cuba', tags: ['Politics', 'Military'] },
  { id: 'mlk_dream', title: 'I Have A Dream Speech', year: '1963 CE', eraId: 'modern', region: 'USA', tags: ['Politics'] },
  { id: 'civil_rights', title: 'Civil Rights Act', year: '1964 CE', eraId: 'modern', region: 'USA', tags: ['Politics'] },
  { id: 'vietnam_war', title: 'US Involvement in Vietnam Peaks', year: '1968 CE', eraId: 'modern', region: 'Vietnam', tags: ['Military', 'Politics'] },
  { id: 'cultural_rev', title: 'Cultural Revolution', year: '1966 CE', eraId: 'modern', region: 'China', tags: ['Politics'] },
  { id: 'green_revolution', title: 'The Green Revolution in Agriculture', year: 'c. 1965 CE', eraId: 'modern', region: 'Global', tags: ['Science'] },
  { id: 'six_day_war', title: 'Six-Day War', year: '1967 CE', eraId: 'modern', region: 'Middle East', tags: ['Military', 'Politics'] },
  { id: 'moon', title: 'Apollo 11 Moon Landing', year: '1969 CE', eraId: 'modern', region: 'Space', tags: ['Science', 'Exploration'] },
  { id: 'internet_arpanet', title: 'ARPANET (Precursor to Internet)', year: '1969 CE', eraId: 'modern', region: 'USA', tags: ['Science'] },
  { id: 'earth_day', title: 'First Earth Day & Modern Environmentalism', year: '1970 CE', eraId: 'modern', region: 'USA', tags: ['Science', 'Politics'] },
  { id: 'woodstock', title: 'Woodstock Festival', year: '1969 CE', eraId: 'modern', region: 'USA', tags: ['Art'] },
  { id: 'star_wars', title: 'Star Wars Released', year: '1977 CE', eraId: 'modern', region: 'USA', tags: ['Art'] },
  { id: 'iran_rev', title: 'Iranian Revolution', year: '1979 CE', eraId: 'modern', region: 'Iran', tags: ['Politics'] },
  { id: 'solidarity_poland', title: 'Solidarity Movement in Poland', year: '1980 CE', eraId: 'modern', region: 'Poland', tags: ['Politics'] },
  { id: 'hiv_aids', title: 'HIV/AIDS Crisis Emerges', year: '1981 CE', eraId: 'modern', region: 'Global', tags: ['Science'] },
  { id: 'chernobyl', title: 'Chernobyl Nuclear Disaster', year: '1986 CE', eraId: 'modern', region: 'USSR', tags: ['Science'] },
  { id: 'berlin_wall', title: 'Fall of the Berlin Wall', year: '1989 CE', eraId: 'modern', region: 'Germany', tags: ['Politics'] },
  { id: 'tiananmen_square', title: 'Tiananmen Square Protests', year: '1989 CE', eraId: 'modern', region: 'China', tags: ['Politics'] },
  { id: 'mandela', title: 'Nelson Mandela Released', year: '1990 CE', eraId: 'modern', region: 'South Africa', tags: ['Politics'] },
  { id: 'apartheid_ends', title: 'End of Apartheid in South Africa', year: '1994 CE', eraId: 'modern', region: 'South Africa', tags: ['Politics'] },
  { id: 'www', title: 'World Wide Web Publicly Available', year: '1991 CE', eraId: 'modern', region: 'Global', tags: ['Science'] },
  { id: 'ussr_fall', title: 'Dissolution of the Soviet Union', year: '1991 CE', eraId: 'modern', region: 'Russia', tags: ['Politics'] },
  { id: 'eu_founded', title: 'European Union Formed (Maastricht)', year: '1993 CE', eraId: 'modern', region: 'Europe', tags: ['Politics'] },
  { id: 'rwanda', title: 'Rwandan Genocide', year: '1994 CE', eraId: 'modern', region: 'Rwanda', tags: ['Politics', 'Military'] },
  { id: 'yugoslav_wars', title: 'Yugoslav Wars', year: '1991 CE', eraId: 'modern', region: 'Balkans', tags: ['Military', 'Politics'] },
  { id: 'globalization', title: 'Globalization Accelerates', year: 'c. 1995 CE', eraId: 'modern', region: 'Global', tags: ['Politics'] },
  { id: 'dolly', title: 'Dolly the Sheep Cloned', year: '1996 CE', eraId: 'modern', region: 'UK', tags: ['Science'] },
  { id: 'iss', title: 'ISS First Module Launched', year: '1998 CE', eraId: 'modern', region: 'Space', tags: ['Science'] },
  { id: 'sept_11', title: '9/11 Terrorist Attacks', year: '2001 CE', eraId: 'modern', region: 'USA', tags: ['Military', 'Politics'] },
  { id: 'genome', title: 'Human Genome Sequenced', year: '2003 CE', eraId: 'modern', region: 'Global', tags: ['Science'] },
  { id: 'facebook', title: 'Facebook Launched', year: '2004 CE', eraId: 'modern', region: 'USA', tags: ['Science'] },
  { id: 'iphone', title: 'iPhone Released', year: '2007 CE', eraId: 'modern', region: 'Global', tags: ['Science'] },
  { id: 'digital_divide', title: 'The Digital Divide Grows', year: 'c. 2007 CE', eraId: 'modern', region: 'Global', tags: ['Politics', 'Science'] },
  { id: 'global_financial_crisis', title: 'Global Financial Crisis', year: '2008 CE', eraId: 'modern', region: 'Global', tags: ['Politics'] },
  { id: 'obama', title: 'Barack Obama Elected', year: '2008 CE', eraId: 'modern', region: 'USA', tags: ['Politics'] },
  { id: 'arab_spring', title: 'Arab Spring Begins', year: '2010 CE', eraId: 'modern', region: 'Middle East', tags: ['Politics'] },
  { id: 'crispr', title: 'CRISPR Gene Editing', year: '2012 CE', eraId: 'modern', region: 'USA/Europe', tags: ['Science'] },
  { id: 'paris_agreement', title: 'Paris Climate Agreement', year: '2015 CE', eraId: 'modern', region: 'Global', tags: ['Politics', 'Science'] },
  { id: 'covid', title: 'COVID-19 Pandemic', year: '2019 CE', eraId: 'modern', region: 'Global', tags: ['Science'] },
  { id: 'maya_lidar', title: 'LiDAR Reveals Hidden Maya Cities', year: '2018 CE', eraId: 'modern', region: 'Mesoamerica', tags: ['Science', 'Exploration'] },
  { id: 'amazon_lidar', title: 'LiDAR Uncovers Ancient Amazon Cities', year: '2024 CE', eraId: 'modern', region: 'Amazon', tags: ['Science', 'Exploration'] },
  { id: 'ai_boom', title: 'Generative AI Boom', year: '2022 CE', eraId: 'modern', region: 'Global', tags: ['Science'] },
];
