import mediaManifest from './media/generated/chronos-media.json';
import { MediaLocatorSchema, type Claim, type Journey, type KnowledgeCard, type Lesson, type MediaAsset, type Source, type UnderstandingPrompt } from '../src/domains/contracts';

const mediaLocator = (id: string) => {
  const entry = mediaManifest.assets.find((asset) => asset.id === id);
  if (!entry) throw new Error(`Missing generated media locator for ${id}`);
  return MediaLocatorSchema.parse(entry.locator);
};

export const sources: Source[] = [
  { id: 'source.met.uruk', title: 'Uruk: First City of the Ancient World', url: 'https://www.metmuseum.org/toah/hd/uruk/hd_uruk.htm', publisher: 'The Metropolitan Museum of Art', accessedOn: '2026-07-13', licenseOrUse: 'Institutional educational reference; runtime reuse not asserted', reviewStatus: 'review-required' },
  { id: 'source.britannica.uruk', title: 'Uruk', url: 'https://www.britannica.com/place/Uruk', publisher: 'Encyclopaedia Britannica', accessedOn: '2026-07-13', licenseOrUse: 'Editorial reference; runtime reuse not asserted', reviewStatus: 'review-required' },
  { id: 'source.unesco.ahwar', title: 'The Ahwar of Southern Iraq', url: 'https://whc.unesco.org/en/list/1481/', publisher: 'UNESCO World Heritage Centre', accessedOn: '2026-07-14', licenseOrUse: 'Property description available under CC-BY-SA IGO 3.0', reviewStatus: 'reviewed' },
  { id: 'source.unesco.ahwar-maps', title: 'The Ahwar of Southern Iraq: Maps and Geographical Data', url: 'https://whc.unesco.org/en/list/1481/maps/', publisher: 'UNESCO World Heritage Centre', accessedOn: '2026-07-14', licenseOrUse: 'Official World Heritage coordinates and public State Party nomination-map reference', reviewStatus: 'reviewed' },
  { id: 'source.ur.southern-mesopotamia', title: 'Southern Mesopotamia, Figure 28.1', url: 'https://people.bu.edu/chamley/HSFref/Ur2012CompanionArchANE.pdf', publisher: 'Jason Ur, in A Companion to the Archaeology of the Ancient Near East (Blackwell)', accessedOn: '2026-07-14', licenseOrUse: 'Copyrighted scholarly publication; used as a non-distributed geographic reference only', reviewStatus: 'reviewed' },
  { id: 'source.archatlas.uruk-ur', title: 'Uruk and Ur', url: 'https://www.archatlas.org/atlas/visualisations/sitesfromsatellites/urukur/', publisher: 'ArchAtlas / Andrew Sherratt', accessedOn: '2026-07-14', licenseOrUse: 'Cited scholarly web reference; NASA imagery credited by the publisher', reviewStatus: 'reviewed' },
  { id: 'source.met.writing-origins', title: 'The Origins of Writing', url: 'https://www.metmuseum.org/essays/the-origins-of-writing', publisher: 'The Metropolitan Museum of Art', accessedOn: '2026-07-16', licenseOrUse: 'Institutional scholarly reference; article text not redistributed', reviewStatus: 'reviewed' },
  { id: 'source.met.proto-cuneiform-tablet', title: 'Proto-Cuneiform Tablet with Seal Impressions, 1988.433.1', url: 'https://www.metmuseum.org/art/collection/search/329081', publisher: 'The Metropolitan Museum of Art', accessedOn: '2026-07-16', licenseOrUse: 'Object image explicitly marked Public Domain under The Met Open Access policy; derivatives and redistribution permitted', reviewStatus: 'reviewed' },
  { id: 'source.cdli.uruk-iv-tablet', title: 'W 20498 (P003801)', url: 'https://cdli.earth/P003801', publisher: 'Cuneiform Digital Library Initiative', accessedOn: '2026-07-16', licenseOrUse: 'Specialist corpus record used as research reference; artifact photograph not redistributed', reviewStatus: 'reviewed' },
  { id: 'source.cdli.writing-epistemology', title: 'The Origins of Writing as a Problem of Historical Epistemology', url: 'https://cdli.earth/articles/cdlj/2006-1', publisher: 'Cuneiform Digital Library Initiative', accessedOn: '2026-07-16', licenseOrUse: 'Open scholarly reference; article text not redistributed', reviewStatus: 'reviewed' },
  { id: 'source.antiquity.seals-signs', title: 'Seals and Signs: Tracing the Origins of Writing in Ancient South-west Asia', url: 'https://www.cambridge.org/core/journals/antiquity/article/seals-and-signs-tracing-the-origins-of-writing-in-ancient-southwest-asia/B3C2D400F3F80A7A0162D9035C9C2804', publisher: 'Antiquity / Cambridge University Press', accessedOn: '2026-07-16', licenseOrUse: 'CC BY-NC-ND scholarly reference; no article media redistributed', reviewStatus: 'reviewed' },
  { id: 'source.isac.visible-language', title: 'Visible Language: Inventions of Writing in the Ancient Middle East and Beyond', url: 'https://isac.uchicago.edu/programs-events/member-events/visible-language-inventions-writing-ancient-middle-east-and-beyond', publisher: 'Institute for the Study of Ancient Cultures, University of Chicago', accessedOn: '2026-07-16', licenseOrUse: 'Institutional reference; runtime reuse not asserted', reviewStatus: 'reviewed' },
];

export const claims: Claim[] = [
  { id: 'claim.uruk.administration', statement: 'Proto-cuneiform tablets and seals provide evidence for organized accounting and administration at Uruk.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.met.uruk'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.uruk.city-life', statement: 'City-scale life created opportunities for specialization while also requiring coordinated labor and creating unequal burdens.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.met.uruk', 'source.britannica.uruk'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.uruk.wetland-landscape', statement: 'Uruk, Ur, and Eridu developed on the shifting alluvial and wetland landscape of southern Mesopotamia; exact ancient river channels, marsh limits, and shoreline positions remain approximate.', kind: 'reconstruction', certainty: 'moderate', sourceIds: ['source.unesco.ahwar', 'source.ur.southern-mesopotamia', 'source.archatlas.uruk-ur'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.writing.administrative-evidence', statement: 'Surviving proto-cuneiform tablets from Uruk and nearby contexts preserve numerical and commodity signs used in administration and accounting.', kind: 'observation', certainty: 'high', sourceIds: ['source.met.proto-cuneiform-tablet', 'source.cdli.uruk-iv-tablet'], reviewStatus: 'reviewed' },
  { id: 'claim.writing.precursors', statement: 'Tokens, seals, numerical tablets, and other earlier practices formed part of the administrative environment from which proto-cuneiform emerged, but a simple one-to-one path from every token or seal motif to a later sign is not demonstrated.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.antiquity.seals-signs'], reviewStatus: 'reviewed' },
  { id: 'claim.writing.change-over-time', statement: 'Proto-cuneiform signs and writing practices changed over time; later cuneiform used impressed wedge-shaped signs and more fully represented spoken languages.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.met.writing-origins', 'source.cdli.writing-epistemology'], reviewStatus: 'reviewed' },
  { id: 'claim.writing.limits', statement: 'Most surviving proto-cuneiform texts concern restricted administrative fields, so they do not preserve the full range of speech, thought, or experience in these communities.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.cdli.writing-epistemology'], reviewStatus: 'reviewed' },
  { id: 'claim.writing.independent-traditions', statement: 'Mesopotamian proto-cuneiform was one early writing tradition; writing also developed independently in Egypt, China, and Mesoamerica.', kind: 'observation', certainty: 'high', sourceIds: ['source.isac.visible-language'], reviewStatus: 'reviewed' },
];

export const media: MediaAsset[] = [
  { id: 'media.writing.proto-cuneiform-tablet', locator: mediaLocator('media.writing.proto-cuneiform-tablet'), alt: 'Small clay proto-cuneiform administrative tablet with incised signs, numerical impressions, and a partial cylinder-seal scene', depictionMode: 'evidence', depictionLabel: 'Surviving proto-cuneiform tablet — The Met, 1988.433.1, Public Domain', sourceIds: ['source.met.proto-cuneiform-tablet'], visualBriefRef: 'docs/research/early-writing-systems.md#media-and-card-provenance', reviewStatus: 'approved' },
  { id: 'media.uruk.reconstruction', locator: mediaLocator('media.uruk.reconstruction'), alt: 'Aerial evidence-based reconstruction of ancient Uruk with a monumental precinct at its center', depictionMode: 'evidence-based-reconstruction', depictionLabel: 'Evidence-based reconstruction — provenance and historical review required', sourceIds: ['source.met.uruk'], visualBriefRef: 'docs/architecture/uruk-vertical-slice.md#evidence-and-reconstruction-treatment', reviewStatus: 'provenance-review-required' },
  { id: 'media.uruk.site', locator: mediaLocator('media.uruk.site'), alt: 'Archaeological remains at the site of Uruk in the modern landscape', depictionMode: 'evidence', depictionLabel: 'Archaeological site photograph — provenance review required', sourceIds: ['source.met.uruk'], visualBriefRef: 'docs/architecture/uruk-vertical-slice.md#evidence-and-reconstruction-treatment', reviewStatus: 'provenance-review-required' },
  { id: 'media.uruk.clay-envelope', locator: mediaLocator('media.uruk.clay-envelope'), alt: 'Clay accounting envelope and tablet with impressed marks', depictionMode: 'evidence', depictionLabel: 'Surviving clay record — object identification and provenance review required', sourceIds: ['source.met.uruk'], visualBriefRef: 'docs/architecture/uruk-vertical-slice.md#evidence-and-reconstruction-treatment', reviewStatus: 'provenance-review-required' },
  { id: 'media.uruk.southern-mesopotamia-map', locator: mediaLocator('media.uruk.southern-mesopotamia-map'), alt: 'Illustrated map of the southern Mesopotamian plain showing the relative positions of Uruk, Ur, and Eridu, the Tigris and Euphrates river system, the Zagros highlands, and an approximate ancient Gulf and wetland margin', depictionMode: 'map', depictionLabel: 'Illustrative historical map — coordinate-verified cities with approximate ancient waterways and wetland margin', sourceIds: ['source.unesco.ahwar-maps', 'source.ur.southern-mesopotamia', 'source.archatlas.uruk-ur'], visualBriefRef: 'docs/research/uruk-southern-mesopotamia-map.md', reviewStatus: 'provenance-review-required' },
];

export const prompts: UnderstandingPrompt[] = [
  { id: 'prompt.uruk.administration-evidence', lessonId: 'lesson.uruk.first-city', kind: 'supported-selection', question: 'Which evidence best supports organized administration at Uruk?', explanation: 'Administrative tablets and seals are surviving evidence of accounting; a reconstruction is an interpretation, not direct evidence.', required: true, options: [{ id: 'option.uruk.reconstruction', label: 'A reconstruction painting of the city' }, { id: 'option.uruk.tablets', label: 'Administrative tablets and cylinder seals' }, { id: 'option.uruk.later-story', label: 'A later story about Uruk’s walls' }] },
  { id: 'prompt.uruk.opportunity-and-cost', lessonId: 'lesson.uruk.first-city', kind: 'concise-explanation', question: 'Name one opportunity and one cost or challenge of life in Uruk, using lesson evidence.', explanation: 'A sincere answer connects an opportunity such as specialization with a challenge such as coordinated labor, inequality, crowding, or resource pressure.', required: true, minimumResponseLength: 20 },
  { id: 'prompt.writing.administration-evidence', lessonId: 'lesson.writing.early-systems', kind: 'supported-selection', question: 'Which surviving evidence best supports the use of early writing for administration or accounting?', explanation: 'A proto-cuneiform tablet that records numbers and commodities is direct surviving evidence. A modern reconstruction or a much later literary story is not.', required: true, options: [{ id: 'option.writing.tablet', label: 'A proto-cuneiform tablet recording quantities and goods' }, { id: 'option.writing.reconstruction', label: 'A modern painting of a scribe at work' }, { id: 'option.writing.later-story', label: 'A literary story copied many centuries later' }] },
  { id: 'prompt.writing.possibility-and-limit', lessonId: 'lesson.writing.early-systems', kind: 'concise-explanation', question: 'Explain one thing writing made possible and one limitation of what the surviving tablets can tell historians.', explanation: 'A sincere answer might connect durable records, comparison, allocation, or transmission with the limits of an administrative sample that leaves many voices and experiences unrecorded.', required: true, minimumResponseLength: 30 },
];

const stubSection = (id: string) => ({ id, heading: 'Coming later', purpose: 'Journey context only', modules: [{ id: id.replace('section', 'module'), type: 'prose' as const, body: 'Editorial stub; not a published lesson.', claimIds: [], sourceIds: [] }] });

export const lessons: Lesson[] = [
  { id: 'lesson.farming.settlements', legacyAliases: [], status: 'draft', title: 'Farming and Settlements', masthead: 'Before 3500 BCE', place: 'Southwest Asia', chronology: { startYear: -9000, endYear: -3500, display: 'Before 3500 BCE', approximate: true }, significance: 'Neighboring stub.', sectionIdsRequired: ['section.stub.farming'], sections: [stubSection('section.stub.farming')], claimIds: ['claim.uruk.city-life'], sourceIds: ['source.met.uruk'], mediaIds: [], promptIds: [] },
  {
    status: 'published', place: 'Southern Mesopotamia', heroMediaId: 'media.uruk.reconstruction', heroLabel: 'Evidence-based reconstruction', heroCaption: 'Interpretation informed by evidence—not a surviving view of Uruk.',
    id: 'lesson.uruk.first-city', legacyAliases: ['uruk'], title: 'Uruk: Life in an Early City', masthead: 'c. 3200 BCE', chronology: { startYear: -3500, endYear: -3000, display: 'approximately 3500–3000 BCE', approximate: true }, significance: 'Uruk’s emergence as a major city around 3200 BCE shows how city-scale coordination changed human life.',
    sectionIdsRequired: ['section.uruk.masthead', 'section.uruk.opening-city-question', 'section.uruk.water-food-and-labor', 'section.uruk.the-built-city', 'section.uruk.tablets-and-administration', 'section.uruk.evidence-and-reconstruction', 'section.uruk.check-and-complete'],
    sections: [
      { id: 'section.uruk.masthead', heading: 'Uruk around 3200 BCE', purpose: 'Begin with place and scale', modules: [{ id: 'module.uruk.city-glance', type: 'knowledge', eyebrow: 'City at a glance', title: 'Thousands of lives, one shared place', body: 'Uruk grew into a major southern Mesopotamian city where food, work, worship, and record-keeping had to be coordinated at a new scale.', items: [{ label: 'Place', detail: 'Southern Mesopotamia' }, { label: 'Chronology', detail: 'c. 3200 BCE' }, { label: 'Big idea', detail: 'Coordination changed city life' }], claimIds: ['claim.uruk.city-life'], sourceIds: ['source.met.uruk'] }, {
        id: 'module.uruk.southern-mesopotamia-map', type: 'historical-map', eyebrow: 'Place & landscape', title: 'A city shaped by water',
        body: 'Uruk stood on the southern Mesopotamian plain, where rivers, channels, wetlands, and dry ground shifted over generations. Its position connected fields and settlements while demanding constant coordination around water.',
        mediaId: 'media.uruk.southern-mesopotamia-map', periodLabel: 'c. 3200 BCE', focusPlace: 'Uruk', modernContext: 'Near modern Warka, Iraq',
        accessibleSummary: 'Uruk lies northwest of Ur and Eridu on the southern Mesopotamian plain. The Euphrates system runs along the western side, the Tigris system lies farther east toward the Zagros highlands, and a shifting wetland and Gulf zone lies to the southeast.',
        compactLabel: 'Illustrative map · ancient waterways approximate',
        coordinateNote: 'Uruk, Ur, and Eridu are placed using official UNESCO World Heritage coordinates.',
        uncertaintyNote: 'City locations follow UNESCO World Heritage coordinates. Ancient river channels, marshes, and the Gulf shoreline shifted over time and are shown approximately.',
        depictionStatus: 'illustrative-reconstruction', claimIds: ['claim.uruk.wetland-landscape'], sourceIds: ['source.unesco.ahwar', 'source.unesco.ahwar-maps', 'source.ur.southern-mesopotamia', 'source.archatlas.uruk-ur'],
      }] },
      { id: 'section.uruk.opening-city-question', heading: 'What makes a city?', purpose: 'Opening city question', modules: [{ id: 'module.uruk.city-question', type: 'prose', body: 'What changes when thousands of people live and work together—and how can historians recognize those changes in the traces people leave behind?', claimIds: [], sourceIds: [] }, { id: 'module.uruk.scene', type: 'scene', title: 'Explore the scene', body: 'Use this reconstruction as a question-making tool. Each feature is an interpretation informed by evidence, not a surviving view.', mediaId: 'media.uruk.reconstruction', hotspots: [{ label: 'Monumental precinct', detail: 'Large shared buildings point to coordinated construction and ritual life.' }, { label: 'Dense neighborhoods', detail: 'Mudbrick homes placed many households close together.' }, { label: 'Water routes', detail: 'Canals and waterways connected fields, food, and movement.' }], claimIds: ['claim.uruk.city-life'], sourceIds: ['source.met.uruk'] }] },
      { id: 'section.uruk.water-food-and-labor', heading: 'Water, food, and labor', purpose: 'How the city kept moving', modules: [{ id: 'module.uruk.city-systems', type: 'knowledge', eyebrow: 'Inline knowledge', title: 'A city is a system', body: 'Irrigation and surplus supported specialized work, while coordination could distribute benefits and burdens unevenly.', items: [{ label: 'Water', detail: 'Canals carried water toward fields and settlements.' }, { label: 'Food', detail: 'Surplus grain could support people doing other work.' }, { label: 'Labor', detail: 'Large projects required planning and many hands.' }], claimIds: ['claim.uruk.city-life'], sourceIds: ['source.met.uruk', 'source.britannica.uruk'] }] },
      { id: 'section.uruk.the-built-city', heading: 'The built city', purpose: 'Read architecture as a clue', modules: [{ id: 'module.uruk.built-city', type: 'knowledge', eyebrow: 'Look closer', title: 'Buildings preserve choices', body: 'Mudbrick buildings and monumental precincts reveal large-scale construction, while much of everyday city life remains incomplete in the record.', items: [{ label: 'Monumental', detail: 'Shared precincts demanded materials, planning, and labor.' }, { label: 'Everyday', detail: 'Homes and lanes held ordinary lives that left fewer traces.' }, { label: 'Uncertain', detail: 'A plan of walls cannot tell us exactly how every space felt or functioned.' }], claimIds: [], sourceIds: ['source.met.uruk'] }] },
      { id: 'section.uruk.tablets-and-administration', heading: 'Tablets and administration', purpose: 'Museum evidence', modules: [{ id: 'module.uruk.tablet-evidence', type: 'evidence', title: 'Records pressed into clay', artifactLabel: 'Surviving evidence', body: 'Clay records and seals help historians trace accounting and administration. The object survives; what a specific mark meant still requires expert interpretation. Uruk connects earlier farming communities to a world where records and ideas could travel beyond one person’s memory.', mediaId: 'media.uruk.clay-envelope', claimIds: ['claim.uruk.administration'], sourceIds: ['source.met.uruk'] }] },
      { id: 'section.uruk.evidence-and-reconstruction', heading: 'Evidence and reconstruction', purpose: 'Separate what survives from what is inferred', modules: [{ id: 'module.uruk.site-evidence', type: 'evidence', title: 'The city beneath the landscape', artifactLabel: 'Archaeological context', body: 'The surviving site is direct archaeological context. The cinematic city above is a reconstruction that assembles evidence into a possible view; it is not a photograph of the past.', mediaId: 'media.uruk.site', claimIds: ['claim.uruk.administration'], sourceIds: ['source.met.uruk'] }] },
      { id: 'section.uruk.check-and-complete', heading: 'World Check', purpose: 'Use evidence to explain', modules: [{ id: 'module.uruk.prompt-admin', type: 'prompt', promptId: 'prompt.uruk.administration-evidence', claimIds: [], sourceIds: [] }, { id: 'module.uruk.prompt-cost', type: 'prompt', promptId: 'prompt.uruk.opportunity-and-cost', claimIds: [], sourceIds: [] }] },
    ],
    claimIds: ['claim.uruk.administration', 'claim.uruk.city-life', 'claim.uruk.wetland-landscape'], sourceIds: ['source.met.uruk', 'source.britannica.uruk', 'source.unesco.ahwar', 'source.unesco.ahwar-maps', 'source.ur.southern-mesopotamia', 'source.archatlas.uruk-ur'], mediaIds: ['media.uruk.reconstruction', 'media.uruk.site', 'media.uruk.clay-envelope', 'media.uruk.southern-mesopotamia-map'], promptIds: ['prompt.uruk.administration-evidence', 'prompt.uruk.opportunity-and-cost'],
  },
  {
    id: 'lesson.writing.early-systems', legacyAliases: ['sumer_writing'], status: 'published', title: 'From Marks to Proto-Cuneiform', masthead: 'c. 3200–2800 BCE', place: 'Southern Mesopotamia', chronology: { startYear: -3200, endYear: -2800, display: 'c. 3200–2800 BCE', approximate: true },
    significance: 'Following Uruk’s administrative tablets, this lesson asks how durable marks became a powerful—but still limited—system for recording information.', heroMediaId: 'media.writing.proto-cuneiform-tablet', heroLabel: 'Surviving evidence', heroCaption: 'This object survives; its reading and administrative context are scholarly interpretations.',
    sectionIdsRequired: ['section.writing.opening-question', 'section.writing.coordination-problem', 'section.writing.before-tablets', 'section.writing.tablets-as-evidence', 'section.writing.signs-change', 'section.writing.power-and-access', 'section.writing.limits', 'section.writing.world-check'],
    sections: [
      { id: 'section.writing.opening-question', heading: 'Can a mark remember?', purpose: 'Opening question', modules: [{ id: 'module.writing.opening', type: 'prose', body: 'Uruk introduced clay records used in administration. Now look more closely: when a mark outlasts the person who made it, what can a community do that memory alone cannot?', claimIds: ['claim.writing.administrative-evidence'], sourceIds: ['source.met.proto-cuneiform-tablet'] }] },
      { id: 'section.writing.coordination-problem', heading: 'More people, more to remember', purpose: 'The coordination problem', modules: [{ id: 'module.writing.coordination', type: 'knowledge', eyebrow: 'A record can travel', title: 'Information beyond one memory', body: 'Large communities moved grain, animals, textiles, labor, and rations through institutions. Durable records could help people count, compare, allocate, and check information.', items: [{ label: 'Count', detail: 'How much came in or went out?' }, { label: 'Identify', detail: 'Which good, person, or institution was involved?' }, { label: 'Carry', detail: 'Could the record be checked later or elsewhere?' }], claimIds: ['claim.writing.administrative-evidence'], sourceIds: ['source.met.writing-origins'] }] },
      { id: 'section.writing.before-tablets', heading: 'Before the tablet', purpose: 'Earlier administrative practices', modules: [{ id: 'module.writing.precursors', type: 'prose', body: 'Tokens, seals, clay envelopes, numerical marks, and other devices were used before and alongside the earliest tablets. They belong to the same world of accounting, but scholars cannot trace every later sign to one earlier object or declare a single instant when writing was invented.', claimIds: ['claim.writing.precursors'], sourceIds: ['source.antiquity.seals-signs'] }] },
      { id: 'section.writing.tablets-as-evidence', heading: 'A tablet that survives', purpose: 'Read the object carefully', modules: [{ id: 'module.writing.tablet-evidence', type: 'evidence', title: 'Numbers, commodities, and a seal', artifactLabel: 'Surviving evidence', body: 'This small clay tablet, probably from Uruk, dates to about 3100–2900 BCE. The Met interprets it as an administrative account, probably involving barley distribution. The marks and seal impression survive; the exact transaction remains uncertain because early texts omit much that later writing would express.', mediaId: 'media.writing.proto-cuneiform-tablet', claimIds: ['claim.writing.administrative-evidence'], sourceIds: ['source.met.proto-cuneiform-tablet'] }] },
      { id: 'section.writing.signs-change', heading: 'Signs do not stand still', purpose: 'From proto-cuneiform toward cuneiform', modules: [{ id: 'module.writing.change', type: 'knowledge', eyebrow: 'Change over time', title: 'A practice, not a finished invention', body: 'Early signs were often drawn or impressed to organize restricted kinds of information. Over centuries, sign shapes and uses changed; later cuneiform used wedge-shaped impressions and could represent spoken languages much more fully.', items: [{ label: 'Early', detail: 'Numerals and signs organized goods and quantities.' }, { label: 'Changing', detail: 'Tools, sign shapes, and conventions shifted.' }, { label: 'Later', detail: 'Cuneiform represented several languages and many kinds of text.' }], claimIds: ['claim.writing.change-over-time'], sourceIds: ['source.met.writing-origins', 'source.cdli.writing-epistemology'] }] },
      { id: 'section.writing.power-and-access', heading: 'Records make power visible', purpose: 'Possibility and control', modules: [{ id: 'module.writing.power', type: 'prose', body: 'Writing made information more durable and comparable. That could support allocation, obligations, planning, and institutional memory. Yet learning and controlling a specialized record system may also have concentrated access among administrators and trained writers; the tablets do not show that everyone could read or decide what was recorded.', claimIds: ['claim.writing.administrative-evidence', 'claim.writing.limits'], sourceIds: ['source.met.writing-origins', 'source.cdli.writing-epistemology'] }] },
      { id: 'section.writing.limits', heading: 'What the archive leaves out', purpose: 'Evidence, interpretation, and uncertainty', modules: [{ id: 'module.writing.limits', type: 'knowledge', eyebrow: 'Historical caution', title: 'Survival is not the whole society', body: 'Administrative tablets are abundant because clay can survive and institutions kept records. That does not mean administration was writing’s only use, or that the surviving archive captures every person’s experience.', items: [{ label: 'Evidence', detail: 'Clay objects and their marks survive.' }, { label: 'Interpretation', detail: 'Scholars compare signs, numbers, contexts, and later texts.' }, { label: 'Uncertainty', detail: 'Many signs and transactions remain difficult to identify.' }, { label: 'Wider world', detail: 'Other writing traditions developed independently.' }], claimIds: ['claim.writing.limits', 'claim.writing.independent-traditions'], sourceIds: ['source.cdli.writing-epistemology', 'source.isac.visible-language'] }] },
      { id: 'section.writing.world-check', heading: 'World Check', purpose: 'Use evidence and name a limit', modules: [{ id: 'module.writing.prompt-evidence', type: 'prompt', promptId: 'prompt.writing.administration-evidence', claimIds: [], sourceIds: [] }, { id: 'module.writing.prompt-limit', type: 'prompt', promptId: 'prompt.writing.possibility-and-limit', claimIds: [], sourceIds: [] }] },
    ],
    claimIds: ['claim.writing.administrative-evidence', 'claim.writing.precursors', 'claim.writing.change-over-time', 'claim.writing.limits', 'claim.writing.independent-traditions'], sourceIds: ['source.met.writing-origins', 'source.met.proto-cuneiform-tablet', 'source.cdli.uruk-iv-tablet', 'source.cdli.writing-epistemology', 'source.antiquity.seals-signs', 'source.isac.visible-language'], mediaIds: ['media.writing.proto-cuneiform-tablet'], promptIds: ['prompt.writing.administration-evidence', 'prompt.writing.possibility-and-limit'],
  },
];

export const journeys: Journey[] = [{ id: 'journey.world-history', title: 'World History', kind: 'world-history', chapters: [{ id: 'chapter.world-history.foundations', title: 'Foundations', position: 0, entries: [{ id: 'entry.world-history.farming', lessonId: 'lesson.farming.settlements', position: 0, required: true, framing: 'From settled farming' }, { id: 'entry.world-history.uruk', lessonId: 'lesson.uruk.first-city', position: 1, required: true, framing: 'How city life changed human coordination' }, { id: 'entry.world-history.writing', lessonId: 'lesson.writing.early-systems', position: 2, required: true, framing: 'Toward recorded administration' }] }] }];

export const cards: KnowledgeCard[] = [
  { id: 'card.place.uruk', title: 'Uruk', category: 'place', cardClass: 'foundation', date: { startYear: -3500, endYear: -3000, display: 'c. 3200 BCE', approximate: true }, place: 'Southern Mesopotamia', significance: 'A major early city where evidence reveals new scales of building, work, and administration.', revealTitle: 'A place worth remembering', revealBody: 'You earned Uruk by using evidence to explain how early city life changed human coordination.', depictionLabel: 'Evidence-based reconstruction', facts: ['Major city by about 3200 BCE', 'Located in southern Mesopotamia', 'Administrative tablets preserve accounting evidence'], lessonIds: ['lesson.uruk.first-city'], sourceIds: ['source.met.uruk', 'source.britannica.uruk'], mediaId: 'media.uruk.reconstruction', unlockLessonId: 'lesson.uruk.first-city' },
  { id: 'card.artifact.proto-cuneiform-tablet', title: 'Proto-Cuneiform Tablet', category: 'artifact', cardClass: 'witness', date: { startYear: -3100, endYear: -2900, display: 'c. 3100–2900 BCE', approximate: true }, place: 'Southern Mesopotamia', significance: 'A surviving administrative object that shows numbers, signs, and sealing working together before later cuneiform was fully developed.', revealTitle: 'A record that outlived its makers', revealBody: 'You earned this Witness card by distinguishing the tablet itself from scholarly readings of what its marks recorded.', depictionLabel: 'Artifact-focused · surviving evidence', facts: ['Made from clay and small enough to hold', 'Uses proto-cuneiform signs and numerical impressions', 'Probably records an administrative distribution', 'Its exact transaction remains uncertain'], lessonIds: ['lesson.writing.early-systems'], sourceIds: ['source.met.proto-cuneiform-tablet', 'source.cdli.writing-epistemology'], mediaId: 'media.writing.proto-cuneiform-tablet', unlockLessonId: 'lesson.writing.early-systems' },
];

export const chronosContent = { sources, claims, media, prompts, lessons, journeys, cards };
