import type { Claim, Journey, KnowledgeCard, Lesson, MediaAsset, Source, UnderstandingPrompt } from '../src/domains/contracts';
export const sources:Source[]=[
 {id:'source.met.uruk',title:'Uruk: First City of the Ancient World',url:'https://www.metmuseum.org/toah/hd/uruk/hd_uruk.htm',publisher:'The Metropolitan Museum of Art',accessedOn:'2026-07-13',reviewStatus:'review-required'},
 {id:'source.britannica.uruk',title:'Uruk',url:'https://www.britannica.com/place/Uruk',publisher:'Encyclopaedia Britannica',accessedOn:'2026-07-13',reviewStatus:'review-required'}];
export const claims:Claim[]=[
 {id:'claim.uruk.administration',statement:'Proto-cuneiform tablets and seals provide evidence for organized accounting and administration at Uruk.',kind:'interpretation',certainty:'high',sourceIds:['source.met.uruk'],reviewStatus:'editorial-review-required'},
 {id:'claim.uruk.city-life',statement:'City-scale life created opportunities for specialization while also requiring coordinated labor and creating unequal burdens.',kind:'interpretation',certainty:'moderate',sourceIds:['source.met.uruk','source.britannica.uruk'],reviewStatus:'editorial-review-required'}];
export const media:MediaAsset[]=[{id:'media.uruk.candidate',path:'/images/places/uruk.jpg',alt:'Candidate reconstruction of ancient Uruk requiring provenance review',depictionMode:'evidence-based-reconstruction',depictionLabel:'Evidence-based reconstruction — provenance and historical review required',sourceIds:['source.met.uruk'],visualBriefRef:'docs/architecture/uruk-vertical-slice.md#evidence-and-reconstruction-treatment',reviewStatus:'provenance-review-required'}];
export const prompts:UnderstandingPrompt[]=[
 {id:'prompt.uruk.administration-evidence',lessonId:'lesson.uruk.first-city',kind:'supported-selection',question:'Which evidence best supports organized administration at Uruk?',explanation:'Administrative tablets and seals are surviving evidence of accounting; a reconstruction is an interpretation, not direct evidence.',required:true},
 {id:'prompt.uruk.opportunity-and-cost',lessonId:'lesson.uruk.first-city',kind:'concise-explanation',question:'Name one opportunity and one cost or challenge of life in Uruk, using lesson evidence.',explanation:'A sincere answer connects an opportunity such as specialization with a challenge such as coordinated labor, inequality, crowding, or resource pressure.',required:true,minimumResponseLength:20}];
const section=(id:string,heading:string,body:string, claimIds:string[]=[]):any=>({id:`section.uruk.${id}`,heading,purpose:heading,modules:[{id:`module.uruk.${id}`,type:'prose',body,claimIds,sourceIds:claimIds.length?['source.met.uruk']:[]}]});
export const lessons:Lesson[]=[
 {id:'lesson.farming.settlements',legacyAliases:[],title:'Farming and Settlements',masthead:'Before 3500 BCE',chronology:{startYear:-9000,endYear:-3500,display:'Before 3500 BCE',approximate:true},significance:'Neighboring stub.',sectionIdsRequired:['section.stub.farming'],sections:[{id:'section.stub.farming',heading:'Coming later',purpose:'Journey context only',modules:[{id:'module.stub.farming',type:'prose',body:'Editorial stub; not a published lesson.',claimIds:[],sourceIds:[]}]}],claimIds:['claim.uruk.city-life'],sourceIds:['source.met.uruk'],mediaIds:[],promptIds:[]},
 {id:'lesson.uruk.first-city',legacyAliases:['uruk'],title:'Uruk: Life in an Early City',masthead:'c. 3200 BCE',chronology:{startYear:-3500,endYear:-3000,display:'approximately 3500–3000 BCE',approximate:true},significance:'Uruk’s emergence as a major city around 3200 BCE shows how city-scale coordination changed human life.',sectionIdsRequired:['section.uruk.masthead','section.uruk.opening-city-question','section.uruk.water-food-and-labor','section.uruk.the-built-city','section.uruk.tablets-and-administration','section.uruk.evidence-and-reconstruction','section.uruk.connections','section.uruk.check-and-complete'],sections:[section('masthead','Uruk around 3200 BCE','Uruk grew into a major southern Mesopotamian city. Copy requires final historical review.'),section('opening-city-question','What makes a city?','What changes when thousands of people live and work together?'),section('water-food-and-labor','Water, food, and labor','Irrigation and surplus supported specialized work while coordination could distribute benefits and burdens unevenly.',['claim.uruk.city-life']),section('the-built-city','The built city','Mudbrick buildings and monumental precincts reveal large-scale construction, while much everyday life remains incomplete in the record.'),section('tablets-and-administration','Tablets and administration','Proto-cuneiform tablets and seals help historians trace accounting and administration.',['claim.uruk.administration']),{id:'section.uruk.evidence-and-reconstruction',heading:'Evidence and reconstruction',purpose:'Distinguish surviving evidence from interpretation',modules:[{id:'module.uruk.evidence',type:'evidence',body:'The image is a candidate reconstruction, not direct evidence. Details require provenance and historical review.',mediaId:'media.uruk.candidate',claimIds:['claim.uruk.administration'],sourceIds:['source.met.uruk']}]},section('connections','Connections','Uruk connects earlier farming communities to later developments in cities and writing.'),{id:'section.uruk.check-and-complete',heading:'Check and complete',purpose:'Sincere attempt and explicit completion',modules:[{id:'module.uruk.prompt-admin',type:'prompt',promptId:'prompt.uruk.administration-evidence',claimIds:[],sourceIds:[]},{id:'module.uruk.prompt-cost',type:'prompt',promptId:'prompt.uruk.opportunity-and-cost',claimIds:[],sourceIds:[]}]}],claimIds:['claim.uruk.administration','claim.uruk.city-life'],sourceIds:['source.met.uruk','source.britannica.uruk'],mediaIds:['media.uruk.candidate'],promptIds:['prompt.uruk.administration-evidence','prompt.uruk.opportunity-and-cost']},
 {id:'lesson.writing.early-systems',legacyAliases:['sumer_writing'],title:'Early Writing Systems',masthead:'After c. 3200 BCE',chronology:{startYear:-3200,endYear:-2800,display:'c. 3200–2800 BCE',approximate:true},significance:'Neighboring stub.',sectionIdsRequired:['section.stub.writing'],sections:[{id:'section.stub.writing',heading:'Coming later',purpose:'Journey context only',modules:[{id:'module.stub.writing',type:'prose',body:'Editorial stub; not a published lesson.',claimIds:[],sourceIds:[]}]}],claimIds:['claim.uruk.administration'],sourceIds:['source.met.uruk'],mediaIds:[],promptIds:[]}];
export const journeys:Journey[]=[{id:'journey.world-history',title:'World History',kind:'world-history',chapters:[{id:'chapter.world-history.foundations',title:'Foundations',position:0,entries:[{id:'entry.world-history.farming',lessonId:'lesson.farming.settlements',position:0,required:true,framing:'From settled farming'},{id:'entry.world-history.uruk',lessonId:'lesson.uruk.first-city',position:1,required:true,framing:'How city life changed human coordination'},{id:'entry.world-history.writing',lessonId:'lesson.writing.early-systems',position:2,required:true,framing:'Toward recorded administration'}]}]}];
export const cards:KnowledgeCard[]=[{id:'card.place.uruk',title:'Uruk',category:'place',cardClass:'foundation',date:{startYear:-3500,endYear:-3000,display:'approximately 3500–3000 BCE',approximate:true},significance:'A major early city where evidence reveals new scales of building, work, and administration.',facts:['Major city by about 3200 BCE','Located in southern Mesopotamia','Administrative tablets preserve accounting evidence'],lessonIds:['lesson.uruk.first-city'],sourceIds:['source.met.uruk','source.britannica.uruk'],mediaId:'media.uruk.candidate',unlockLessonId:'lesson.uruk.first-city'}];
export const urukContent={sources,claims,media,prompts,lessons,journeys,cards};
