import urukMediaManifest from './media/generated/uruk-media.json';
import { MediaLocatorSchema, type Claim, type Journey, type KnowledgeCard, type Lesson, type MediaAsset, type Source, type UnderstandingPrompt } from '../src/domains/contracts';

const mediaLocator = (id: string) => {
  const entry = urukMediaManifest.assets.find((asset) => asset.id === id);
  if (!entry) throw new Error(`Missing generated media locator for ${id}`);
  return MediaLocatorSchema.parse(entry.locator);
};

export const sources: Source[] = [
  { id: 'source.met.uruk', title: 'Uruk: First City of the Ancient World', url: 'https://www.metmuseum.org/toah/hd/uruk/hd_uruk.htm', publisher: 'The Metropolitan Museum of Art', accessedOn: '2026-07-13', licenseOrUse: 'Institutional educational reference; runtime reuse not asserted', reviewStatus: 'review-required' },
  { id: 'source.britannica.uruk', title: 'Uruk', url: 'https://www.britannica.com/place/Uruk', publisher: 'Encyclopaedia Britannica', accessedOn: '2026-07-13', licenseOrUse: 'Editorial reference; runtime reuse not asserted', reviewStatus: 'review-required' },
  { id: 'source.unesco.ahwar', title: 'The Ahwar of Southern Iraq', url: 'https://whc.unesco.org/en/list/1481/', publisher: 'UNESCO World Heritage Centre', accessedOn: '2026-07-14', licenseOrUse: 'Property description available under CC-BY-SA IGO 3.0', reviewStatus: 'reviewed' },
  { id: 'source.unesco.ahwar-maps', title: 'The Ahwar of Southern Iraq: Maps and Geographical Data', url: 'https://whc.unesco.org/en/list/1481/maps/', publisher: 'UNESCO World Heritage Centre', accessedOn: '2026-07-14', licenseOrUse: 'Official World Heritage coordinates and public State Party nomination-map reference', reviewStatus: 'reviewed' },
  { id: 'source.ur.southern-mesopotamia', title: 'Southern Mesopotamia, Figure 28.1', url: 'https://people.bu.edu/chamley/HSFref/Ur2012CompanionArchANE.pdf', publisher: 'Jason Ur, in A Companion to the Archaeology of the Ancient Near East (Blackwell)', accessedOn: '2026-07-14', licenseOrUse: 'Copyrighted scholarly publication; used as a non-distributed geographic reference only', reviewStatus: 'reviewed' },
  { id: 'source.archatlas.uruk-ur', title: 'Uruk and Ur', url: 'https://www.archatlas.org/atlas/visualisations/sitesfromsatellites/urukur/', publisher: 'ArchAtlas / Andrew Sherratt', accessedOn: '2026-07-14', licenseOrUse: 'Cited scholarly web reference; NASA imagery credited by the publisher', reviewStatus: 'reviewed' },
  { id: 'source.chronos.generated-uruk-media', title: 'Chronos-generated Uruk media, 2026-07-15', url: 'https://github.com/dev-vibe/chronos-learning/tree/codex/ash-56-media-storage/assets/generated', publisher: 'Chronos', accessedOn: '2026-07-15', licenseOrUse: 'Chronos-original generated artwork; complete generation lineage and boundaries recorded in docs/research/uruk-media-provenance-20260715.md', reviewStatus: 'reviewed' },
  { id: 'source.commons.louvre-susa-envelope', title: 'Accountancy clay envelope, Louvre Sb 1932', url: 'https://commons.wikimedia.org/wiki/File:Accountancy_clay_envelope_Louvre_Sb1932.jpg', publisher: 'Wikimedia Commons / Louvre Museum', accessedOn: '2026-07-15', licenseOrUse: 'Photograph by Marie-Lan Nguyen, CC BY 2.5; used as a non-distributed factual reference only', reviewStatus: 'reviewed' },
];

export const claims: Claim[] = [
  { id: 'claim.uruk.administration', statement: 'Proto-cuneiform tablets and seals provide evidence for organized accounting and administration at Uruk.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.met.uruk'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.uruk.city-life', statement: 'City-scale life created opportunities for specialization while also requiring coordinated labor and creating unequal burdens.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.met.uruk', 'source.britannica.uruk'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.uruk.wetland-landscape', statement: 'Uruk, Ur, and Eridu developed on the shifting alluvial and wetland landscape of southern Mesopotamia; exact ancient river channels, marsh limits, and shoreline positions remain approximate.', kind: 'reconstruction', certainty: 'moderate', sourceIds: ['source.unesco.ahwar', 'source.ur.southern-mesopotamia', 'source.archatlas.uruk-ur'], reviewStatus: 'editorial-review-required' },
];

export const media: MediaAsset[] = [
  { id: 'media.uruk.reconstruction', locator: mediaLocator('media.uruk.reconstruction'), alt: 'Aerial evidence-based reconstruction of ancient Uruk with a monumental precinct at its center', depictionMode: 'evidence-based-reconstruction', depictionLabel: 'Evidence-based reconstruction — generated from documented historical research', sourceIds: ['source.met.uruk', 'source.chronos.generated-uruk-media'], visualBriefRef: 'docs/research/uruk-media-provenance-20260715.md', reviewStatus: 'approved' },
  { id: 'media.uruk.site', locator: mediaLocator('media.uruk.site'), alt: 'Illustrative view of the archaeological landscape at Uruk in the modern era', depictionMode: 'evidence-based-reconstruction', depictionLabel: 'Illustrative archaeological context — generated from documented research; not a documentary photograph', sourceIds: ['source.unesco.ahwar', 'source.chronos.generated-uruk-media'], visualBriefRef: 'docs/research/uruk-media-provenance-20260715.md', reviewStatus: 'approved' },
  { id: 'media.uruk.clay-envelope', locator: mediaLocator('media.uruk.clay-envelope'), alt: 'Illustrative reconstruction of a Late Uruk clay accounting envelope with simple counting tokens', depictionMode: 'evidence-based-reconstruction', depictionLabel: 'Illustrative reconstruction informed by surviving accounting envelopes — not a photograph of a specific object', sourceIds: ['source.commons.louvre-susa-envelope', 'source.chronos.generated-uruk-media'], visualBriefRef: 'docs/research/uruk-media-provenance-20260715.md', reviewStatus: 'approved' },
  { id: 'media.uruk.southern-mesopotamia-map', locator: mediaLocator('media.uruk.southern-mesopotamia-map'), alt: 'Illustrated map of the southern Mesopotamian plain showing the relative positions of Uruk, Ur, and Eridu, the Tigris and Euphrates river system, the Zagros highlands, and an approximate ancient Gulf and wetland margin', depictionMode: 'map', depictionLabel: 'Illustrative historical map — coordinate-verified cities with approximate ancient waterways and wetland margin', sourceIds: ['source.unesco.ahwar-maps', 'source.ur.southern-mesopotamia', 'source.archatlas.uruk-ur', 'source.chronos.generated-uruk-media'], visualBriefRef: 'docs/research/uruk-southern-mesopotamia-map.md', reviewStatus: 'approved' },
];

export const prompts: UnderstandingPrompt[] = [
  { id: 'prompt.uruk.administration-evidence', lessonId: 'lesson.uruk.first-city', kind: 'supported-selection', question: 'Which evidence best supports organized administration at Uruk?', explanation: 'Administrative tablets and seals are surviving evidence of accounting; a reconstruction is an interpretation, not direct evidence.', required: true },
  { id: 'prompt.uruk.opportunity-and-cost', lessonId: 'lesson.uruk.first-city', kind: 'concise-explanation', question: 'Name one opportunity and one cost or challenge of life in Uruk, using lesson evidence.', explanation: 'A sincere answer connects an opportunity such as specialization with a challenge such as coordinated labor, inequality, crowding, or resource pressure.', required: true, minimumResponseLength: 20 },
];

const stubSection = (id: string) => ({ id, heading: 'Coming later', purpose: 'Journey context only', modules: [{ id: id.replace('section', 'module'), type: 'prose' as const, body: 'Editorial stub; not a published lesson.', claimIds: [], sourceIds: [] }] });

export const lessons: Lesson[] = [
  { id: 'lesson.farming.settlements', legacyAliases: [], title: 'Farming and Settlements', masthead: 'Before 3500 BCE', chronology: { startYear: -9000, endYear: -3500, display: 'Before 3500 BCE', approximate: true }, significance: 'Neighboring stub.', sectionIdsRequired: ['section.stub.farming'], sections: [stubSection('section.stub.farming')], claimIds: ['claim.uruk.city-life'], sourceIds: ['source.met.uruk'], mediaIds: [], promptIds: [] },
  {
    id: 'lesson.uruk.first-city', legacyAliases: ['uruk'], title: 'Uruk: Life in an Early City', masthead: 'c. 3200 BCE', chronology: { startYear: -3500, endYear: -3000, display: 'approximately 3500–3000 BCE', approximate: true }, significance: 'Uruk’s emergence as a major city around 3200 BCE shows how city-scale coordination changed human life.',
    sectionIdsRequired: ['section.uruk.masthead', 'section.uruk.opening-city-question', 'section.uruk.water-food-and-labor', 'section.uruk.the-built-city', 'section.uruk.tablets-and-administration', 'section.uruk.evidence-and-reconstruction', 'section.uruk.connections', 'section.uruk.check-and-complete'],
    sections: [
      { id: 'section.uruk.masthead', heading: 'Uruk around 3200 BCE', purpose: 'Begin with place and scale', modules: [{ id: 'module.uruk.city-glance', type: 'knowledge', eyebrow: 'City at a glance', title: 'Thousands of lives, one shared place', body: 'Uruk grew into a major southern Mesopotamian city where food, work, worship, and record-keeping had to be coordinated at a new scale.', items: [{ label: 'Place', detail: 'Southern Mesopotamia' }, { label: 'Chronology', detail: 'c. 3200 BCE' }, { label: 'Big idea', detail: 'Coordination changed city life' }], claimIds: ['claim.uruk.city-life'], sourceIds: ['source.met.uruk'] }, {
        id: 'module.uruk.southern-mesopotamia-map', type: 'historical-map', eyebrow: 'Place & landscape', title: 'A city shaped by water',
        body: 'Uruk stood on the southern Mesopotamian plain, where rivers, channels, wetlands, and dry ground shifted over generations. Its position connected fields and settlements while demanding constant coordination around water.',
        mediaId: 'media.uruk.southern-mesopotamia-map', periodLabel: 'c. 3200 BCE', focusPlace: 'Uruk', modernContext: 'Near modern Warka, Iraq',
        accessibleSummary: 'Uruk lies northwest of Ur and Eridu on the southern Mesopotamian plain. The Euphrates system runs along the western side, the Tigris system lies farther east toward the Zagros highlands, and a shifting wetland and Gulf zone lies to the southeast.',
        uncertaintyNote: 'City locations follow UNESCO World Heritage coordinates. Ancient river channels, marshes, and the Gulf shoreline shifted over time and are shown approximately.',
        depictionStatus: 'illustrative-reconstruction', claimIds: ['claim.uruk.wetland-landscape'], sourceIds: ['source.unesco.ahwar', 'source.unesco.ahwar-maps', 'source.ur.southern-mesopotamia', 'source.archatlas.uruk-ur'],
      }] },
      { id: 'section.uruk.opening-city-question', heading: 'What makes a city?', purpose: 'Opening city question', modules: [{ id: 'module.uruk.city-question', type: 'prose', body: 'What changes when thousands of people live and work together—and how can historians recognize those changes in the traces people leave behind?', claimIds: [], sourceIds: [] }, { id: 'module.uruk.scene', type: 'scene', title: 'Explore the scene', body: 'Use this reconstruction as a question-making tool. Each feature is an interpretation informed by evidence, not a surviving view.', mediaId: 'media.uruk.reconstruction', hotspots: [{ label: 'Monumental precinct', detail: 'Large shared buildings point to coordinated construction and ritual life.' }, { label: 'Dense neighborhoods', detail: 'Mudbrick homes placed many households close together.' }, { label: 'Water routes', detail: 'Canals and waterways connected fields, food, and movement.' }], claimIds: ['claim.uruk.city-life'], sourceIds: ['source.met.uruk'] }] },
      { id: 'section.uruk.water-food-and-labor', heading: 'Water, food, and labor', purpose: 'How the city kept moving', modules: [{ id: 'module.uruk.city-systems', type: 'knowledge', eyebrow: 'Inline knowledge', title: 'A city is a system', body: 'Irrigation and surplus supported specialized work, while coordination could distribute benefits and burdens unevenly.', items: [{ label: 'Water', detail: 'Canals carried water toward fields and settlements.' }, { label: 'Food', detail: 'Surplus grain could support people doing other work.' }, { label: 'Labor', detail: 'Large projects required planning and many hands.' }], claimIds: ['claim.uruk.city-life'], sourceIds: ['source.met.uruk', 'source.britannica.uruk'] }] },
      { id: 'section.uruk.the-built-city', heading: 'The built city', purpose: 'Read architecture as a clue', modules: [{ id: 'module.uruk.built-city', type: 'knowledge', eyebrow: 'Look closer', title: 'Buildings preserve choices', body: 'Mudbrick buildings and monumental precincts reveal large-scale construction, while much of everyday city life remains incomplete in the record.', items: [{ label: 'Monumental', detail: 'Shared precincts demanded materials, planning, and labor.' }, { label: 'Everyday', detail: 'Homes and lanes held ordinary lives that left fewer traces.' }, { label: 'Uncertain', detail: 'A plan of walls cannot tell us exactly how every space felt or functioned.' }], claimIds: [], sourceIds: ['source.met.uruk'] }] },
      { id: 'section.uruk.tablets-and-administration', heading: 'Tablets and administration', purpose: 'Museum evidence', modules: [{ id: 'module.uruk.tablet-evidence', type: 'evidence', title: 'Records pressed into clay', artifactLabel: 'Illustrative reconstruction informed by surviving evidence', body: 'Surviving clay envelopes, tokens, seals, and tablets help historians trace accounting and administration. This illustration is not a photograph of a specific object; what a specific mark meant still requires expert interpretation.', mediaId: 'media.uruk.clay-envelope', claimIds: ['claim.uruk.administration'], sourceIds: ['source.met.uruk', 'source.commons.louvre-susa-envelope'] }] },
      { id: 'section.uruk.evidence-and-reconstruction', heading: 'Evidence and reconstruction', purpose: 'Separate what survives from what is inferred', modules: [{ id: 'module.uruk.site-evidence', type: 'evidence', title: 'The city beneath the landscape', artifactLabel: 'Illustrative archaeological context', body: 'This illustration helps distinguish the archaeological landscape from the reconstructed city above. It is not a documentary photograph; the surviving site and its evidence remain the basis for historical interpretation.', mediaId: 'media.uruk.site', claimIds: ['claim.uruk.administration'], sourceIds: ['source.met.uruk', 'source.unesco.ahwar'] }] },
      { id: 'section.uruk.connections', heading: 'Connections', purpose: 'Follow the idea forward', modules: [{ id: 'module.uruk.connection-writing', type: 'connection', eyebrow: 'This lesson opens', title: 'Early Writing Systems', body: 'Uruk connects earlier farming communities to a world where records and ideas could travel beyond one person’s memory.', lessonIds: ['lesson.writing.early-systems'], claimIds: ['claim.uruk.administration'], sourceIds: ['source.met.uruk'] }] },
      { id: 'section.uruk.check-and-complete', heading: 'World Check', purpose: 'Use evidence to explain', modules: [{ id: 'module.uruk.prompt-admin', type: 'prompt', promptId: 'prompt.uruk.administration-evidence', claimIds: [], sourceIds: [] }, { id: 'module.uruk.prompt-cost', type: 'prompt', promptId: 'prompt.uruk.opportunity-and-cost', claimIds: [], sourceIds: [] }] },
    ],
    claimIds: ['claim.uruk.administration', 'claim.uruk.city-life', 'claim.uruk.wetland-landscape'], sourceIds: ['source.met.uruk', 'source.britannica.uruk', 'source.unesco.ahwar', 'source.unesco.ahwar-maps', 'source.ur.southern-mesopotamia', 'source.archatlas.uruk-ur'], mediaIds: ['media.uruk.reconstruction', 'media.uruk.site', 'media.uruk.clay-envelope', 'media.uruk.southern-mesopotamia-map'], promptIds: ['prompt.uruk.administration-evidence', 'prompt.uruk.opportunity-and-cost'],
  },
  { id: 'lesson.writing.early-systems', legacyAliases: ['sumer_writing'], title: 'Early Writing Systems', masthead: 'After c. 3200 BCE', chronology: { startYear: -3200, endYear: -2800, display: 'c. 3200–2800 BCE', approximate: true }, significance: 'Neighboring stub.', sectionIdsRequired: ['section.stub.writing'], sections: [stubSection('section.stub.writing')], claimIds: ['claim.uruk.administration'], sourceIds: ['source.met.uruk'], mediaIds: [], promptIds: [] },
];

export const journeys: Journey[] = [{ id: 'journey.world-history', title: 'World History', kind: 'world-history', chapters: [{ id: 'chapter.world-history.foundations', title: 'Foundations', position: 0, entries: [{ id: 'entry.world-history.farming', lessonId: 'lesson.farming.settlements', position: 0, required: true, framing: 'From settled farming' }, { id: 'entry.world-history.uruk', lessonId: 'lesson.uruk.first-city', position: 1, required: true, framing: 'How city life changed human coordination' }, { id: 'entry.world-history.writing', lessonId: 'lesson.writing.early-systems', position: 2, required: true, framing: 'Toward recorded administration' }] }] }];

export const cards: KnowledgeCard[] = [{ id: 'card.place.uruk', title: 'Uruk', category: 'place', cardClass: 'foundation', date: { startYear: -3500, endYear: -3000, display: 'c. 3200 BCE', approximate: true }, significance: 'A major early city where evidence reveals new scales of building, work, and administration.', facts: ['Major city by about 3200 BCE', 'Located in southern Mesopotamia', 'Administrative tablets preserve accounting evidence'], lessonIds: ['lesson.uruk.first-city'], sourceIds: ['source.met.uruk', 'source.britannica.uruk'], mediaId: 'media.uruk.reconstruction', unlockLessonId: 'lesson.uruk.first-city' }];

export const urukContent = { sources, claims, media, prompts, lessons, journeys, cards };
