import type { Claim, Lesson, Source, UnderstandingPrompt } from '../../src/domains/contracts';
import type { AuthoredContentModule } from '../assemble';
import { akkadLocatorVisual, akkadMedia, akkadMediaSources, akkadSealExampleVisual, akkadSteleVisual } from './akkad-media';

const lessonId = 'lesson.mesopotamia.akkadian-empire';

export const akkadSources: Source[] = [
  ...akkadMediaSources,
  { id: 'source.akkad.met-period', title: 'The Akkadian Period (ca. 2350–2150 B.C.)', url: 'https://www.metmuseum.org/toah/hd/akka/hd_akka.htm', publisher: 'The Metropolitan Museum of Art', accessedOn: '2026-09-22', licenseOrUse: 'Research citation for rounded period and southern Mesopotamian setting; the essay’s absolute first-empire language is not adopted. No image redistribution.', reviewStatus: 'reviewed' },
  { id: 'source.akkad.sargon-inscription', title: 'RIME 2.01.01.01 composite, P461926', url: 'https://cdli.earth/artifacts/461926', publisher: 'Cuneiform Digital Library Initiative / RIME', accessedOn: '2026-09-22', licenseOrUse: 'Research citation and short attributed paraphrase; Akkadian version lines 12–31 and 79–85 close-reviewed. Scholarly composite without an original findspot or image on the record.', reviewStatus: 'reviewed' },
  { id: 'source.akkad.leilan', title: 'Acropolis Northwest — Akkadian Palace', url: 'https://leilan.yale.edu/about-project/excavations/acropolis-northwest-akkadian-palace', publisher: 'Yale Tell Leilan Project', accessedOn: '2026-09-22', licenseOrUse: 'Research citation; Akkadian conquest, schoolroom, palace and post-Akkadian sections close-reviewed. Page states no reprint without permission; no image copied.', reviewStatus: 'reviewed' },
  { id: 'source.akkad.urkesh', title: 'Tar’am-Agade, Daughter of Naram-Sin, at Urkesh', url: 'https://urkesh.org/attach/Buccellati%202002%20Taram%20Agade%20Daughter%20of%20Naram%20Sin.pdf', publisher: 'Giorgio Buccellati and Marilyn Kelly-Buccellati, excavators of Urkesh (2002)', accessedOn: '2026-09-22', licenseOrUse: 'Research citation; pp. 1–4 excavation, sealings, Tar’am-Agade and alternative roles close-reviewed. No image redistribution established.', reviewStatus: 'reviewed' },
  { id: 'source.akkad.louvre-stele', title: 'Victory Stele of Naram-Sin, SB 4', url: 'https://collections.louvre.fr/en/ark:/53355/cl010123450', publisher: 'Musée du Louvre, Département des Antiquités orientales', accessedOn: '2026-09-22', licenseOrUse: 'Research citation; object description, inscriptions and provenance close-reviewed. Image use requires separate rights review.', reviewStatus: 'reviewed' },
  { id: 'source.akkad.weiss', title: 'The Genesis and Collapse of the Akkadian Empire: The Accidental Refraction of Historical Law', url: 'https://leilan.yale.edu/sites/default/files/publications/article-specific/weiss_and_courty_1993_genesis_collapse_akkadian_empire_in_liverani_ed_akkad_the_first_world_empire.pdf', publisher: 'Harvey Weiss and Marie-Agnès Courty, in Liverani (ed.), Akkad: The First World Empire (1993), pp. 131–155', accessedOn: '2026-09-22', licenseOrUse: 'Research citation for the Tell Leilan abandonment/aridity explanation; source argument reviewed alongside a recent countercase. No figure reuse.', reviewStatus: 'reviewed' },
  { id: 'source.akkad.isotopes', title: 'Much ado about nothing: assessing the impact of the 4.2 kya event', url: 'https://doi.org/10.15184/aqy.2021.117', publisher: 'Arkadiusz Sołtysiak et al., Antiquity 95 (2021)', accessedOn: '2026-09-22', licenseOrUse: 'Open research citation; archaeological background, isotope results and conclusions close-reviewed. Figures require attribution and separate placement review.', reviewStatus: 'reviewed' },
  { id: 'source.akkad.capital-review', title: 'Where Was the City of Akkade?', url: 'https://kokushikan.repo.nii.ac.jp/records/15919', publisher: 'Kawakami, Al-Rāfidān 44 (2023)', accessedOn: '2026-09-22', licenseOrUse: 'Research citation for unsettled capital-location proposals; no map reproduction.', reviewStatus: 'reviewed' },
  { id: 'source.akkad.sargon-retinue', title: 'RIME 2.01.01.11 composite, P461937', url: 'https://cdli.earth/artifacts/461937', publisher: 'Cuneiform Digital Library Initiative / RIME', accessedOn: '2026-09-23', licenseOrUse: 'Research citation and short attributed quotation; Sumerian version col. v lines 9–13 and 34–37 and Akkadian version col. vi lines 11–16 and 41–44 close-reviewed. Scholarly composite without an original findspot or image on the record.', reviewStatus: 'reviewed' },
  { id: 'source.akkad.possehl-meluhha', title: 'The Middle Asian Interaction Sphere', url: 'https://www.penn.museum/sites/expedition/the-middle-asian-interaction-sphere/', publisher: 'Gregory L. Possehl, Expedition magazine (2007), Penn Museum', accessedOn: '2026-09-23', licenseOrUse: 'Research citation for the identification of Dilmun, Magan and Meluhha; opening section on the Gulf trading lands close-reviewed. No image reuse.', reviewStatus: 'reviewed' },
  { id: 'source.akkad.smarthistory-stele', title: 'Victory Stele of Naram-Sin', url: 'https://smarthistory.org/victory-stele-of-naram-sin/', publisher: 'Dr. Beth Harris and Dr. Steven Zucker, Smarthistory', accessedOn: '2026-09-23', licenseOrUse: 'Research citation for the horned helmet as a sign of divinity, the depicted enemies and the stele’s removal by Shutruk-Nahhunte; transcript close-reviewed. No image or video reuse.', reviewStatus: 'reviewed' },
  { id: 'source.akkad.curse-etcsl', title: 'The cursing of Agade (ETCSL t.2.1.5), English translation', url: 'https://etcsl.orinst.ox.ac.uk/section2/tr215.htm', publisher: 'Electronic Text Corpus of Sumerian Literature, University of Oxford', accessedOn: '2026-09-23', licenseOrUse: 'Research citation and brief paraphrase of a later literary composition; lines 100–175 (temple attack and Gutians) and 272–281 (grass on the towpaths, closing praise) close-reviewed. Later tradition, not a record of events.', reviewStatus: 'reviewed' },
  { id: 'source.akkad.curse-cdli', title: 'CDLI Literary 000375 (Curse of Agade) composite, P469679', url: 'https://cdli.earth/artifacts/469679', publisher: 'Cuneiform Digital Library Initiative, after J. S. Cooper, The Curse of Agade (1983)', accessedOn: '2026-09-23', licenseOrUse: 'Research citation for the Old Babylonian date (c. 1900–1600 BCE) and multi-site witnesses of the poem; record metadata close-reviewed.', reviewStatus: 'reviewed' },
];

export const akkadClaims: Claim[] = [
  { id: 'claim.akkad.period', statement: 'About 2350–2150 BCE is a rounded teaching frame for the Akkadian period, not an exact interval for every site.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.akkad.met-period'], reviewStatus: 'reviewed' },
  { id: 'claim.akkad.capital-location', statement: 'Agade is named in ancient records but its exact archaeological location has not been securely identified.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.akkad.capital-review', 'source.akkad.sargon-inscription'], reviewStatus: 'reviewed' },
  { id: 'claim.akkad.conquest-claims', statement: 'Sargon’s royal inscription claims victories over Uruk, Ur and Umma and says citizens of Agade held governorships.', kind: 'observation', certainty: 'high', sourceIds: ['source.akkad.sargon-inscription'], reviewStatus: 'reviewed' },
  { id: 'claim.akkad.winning-and-governing', statement: 'A military victory and continued government are different; governing places across distance required officials, supplies and relationships with local people.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.akkad.sargon-inscription', 'source.akkad.leilan', 'source.akkad.urkesh'], reviewStatus: 'reviewed' },
  { id: 'claim.akkad.leilan-administration', statement: 'Tell Leilan preserves an Akkadian-period fortified administrative building, grain-processing spaces, sealings and tablets.', kind: 'observation', certainty: 'high', sourceIds: ['source.akkad.leilan'], reviewStatus: 'reviewed' },
  { id: 'claim.akkad.leilan-work', statement: 'Grain processing and record keeping at Leilan show labor and supplies behind distant rule without revealing every worker’s experience.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.akkad.leilan'], reviewStatus: 'reviewed' },
  { id: 'claim.akkad.taram-sealings', statement: 'Seal impressions found in the Urkesh palace name Tar’am-Agade as Naram-Sin’s daughter.', kind: 'observation', certainty: 'high', sourceIds: ['source.akkad.urkesh'], reviewStatus: 'reviewed' },
  { id: 'claim.akkad.seal-example', statement: 'The Met displays an Akkadian-period cylinder seal with a modern impression of its design; it is not a Tar’am-Agade sealing or a find from Urkesh.', kind: 'observation', certainty: 'high', sourceIds: ['source.akkad.met-seal-example'], reviewStatus: 'reviewed' },
  { id: 'claim.akkad.urkesh-relationship', statement: 'Tar’am-Agade’s sealings establish a royal-family connection at Urkesh but do not alone settle whether Akkad directly governed the city.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.akkad.urkesh'], reviewStatus: 'reviewed' },
  { id: 'claim.akkad.stele-image', statement: 'Naram-Sin’s surviving victory stele depicts the king above and larger than his soldiers and the people they defeat.', kind: 'observation', certainty: 'high', sourceIds: ['source.akkad.louvre-stele'], reviewStatus: 'reviewed' },
  { id: 'claim.akkad.stele-afterlife', statement: 'The stele is associated with Sippar, was later taken to Susa and given a second inscription there; much of its Akkadian inscription is lost.', kind: 'observation', certainty: 'high', sourceIds: ['source.akkad.louvre-stele'], reviewStatus: 'reviewed' },
  { id: 'claim.akkad.uneven-change', statement: 'Late-third-millennium settlement changes differed across northern Mesopotamian sites, including abandonment at Leilan and continued occupation elsewhere.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.akkad.leilan', 'source.akkad.isotopes'], reviewStatus: 'reviewed' },
  { id: 'claim.akkad.drought-limits', statement: 'Aridity may have harmed some northern places, but the evidence does not establish one sudden drought that ended Akkadian rule everywhere.', kind: 'interpretation', certainty: 'contested', sourceIds: ['source.akkad.weiss', 'source.akkad.isotopes'], reviewStatus: 'reviewed' },
  { id: 'claim.akkad.agade-quay', statement: 'A Sargon inscription says boats of Meluhha, Magan and Dilmun were tied up at the quay of Agade.', kind: 'observation', certainty: 'high', sourceIds: ['source.akkad.sargon-retinue'], reviewStatus: 'reviewed' },
  { id: 'claim.akkad.trade-places', statement: 'Scholars identify Meluhha with the Indus civilization, Magan with present-day Oman and nearby areas, and Dilmun with Bahrain and the nearby Arabian shore.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.akkad.possehl-meluhha'], reviewStatus: 'reviewed' },
  { id: 'claim.akkad.sea-to-sea', statement: 'Sargon’s inscription says the god Enlil gave him the land from the Upper Sea to the Lower Sea.', kind: 'observation', certainty: 'high', sourceIds: ['source.akkad.sargon-inscription'], reviewStatus: 'reviewed' },
  { id: 'claim.akkad.bread-boast', statement: 'A Sargon inscription says 5,400 men ate bread before him daily.', kind: 'observation', certainty: 'high', sourceIds: ['source.akkad.sargon-retinue'], reviewStatus: 'reviewed' },
  { id: 'claim.akkad.leilan-walls', statement: 'The Akkadian administrative building at Tell Leilan had walls up to 6.6 meters thick; its grain-processing rooms held ovens mostly 1 to 3 meters across, and plant residue from the work covered every floor.', kind: 'observation', certainty: 'high', sourceIds: ['source.akkad.leilan'], reviewStatus: 'reviewed' },
  { id: 'claim.akkad.leilan-official', statement: 'The Akkadian conquest displaced Leilan’s local elite, and sealings show an Akkadian šabra official directing agricultural and construction projects.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.akkad.leilan'], reviewStatus: 'reviewed' },
  { id: 'claim.akkad.barley-ration', statement: 'Akkadian administrative texts set two sila of barley, roughly two liters, as a laborer’s standard daily ration.', kind: 'observation', certainty: 'high', sourceIds: ['source.akkad.leilan'], reviewStatus: 'reviewed' },
  { id: 'claim.akkad.leilan-schoolroom', statement: 'A schoolroom at Leilan held round tablets with a few practice signs in Old Akkadian script, perhaps used to train local officials.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.akkad.leilan'], reviewStatus: 'reviewed' },
  { id: 'claim.akkad.leilan-unfinished', statement: 'The last Akkadian building project at Leilan was abandoned before completion, with basalt boulders left several meters from a partly built wall; by no later than about 2140 BCE Tell Leilan lay in ruins.', kind: 'observation', certainty: 'high', sourceIds: ['source.akkad.leilan'], reviewStatus: 'reviewed' },
  { id: 'claim.akkad.urkesh-find', statement: 'In August 1999, on what was planned as the last day of work in that area of the Urkesh royal palace, excavators began finding the inscribed sealings; Tar’am-Agade’s small seal, about 3 cm high, had been rolled on clay closing a door in the palace of Urkesh’s Hurrian rulers.', kind: 'observation', certainty: 'high', sourceIds: ['source.akkad.urkesh'], reviewStatus: 'reviewed' },
  { id: 'claim.akkad.taram-name', statement: 'The name Tar’am-Agade means “She loves Akkad”; the excavators read it as a political statement.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.akkad.urkesh'], reviewStatus: 'reviewed' },
  { id: 'claim.akkad.stele-details', statement: 'The limestone stele is about 2 meters tall; its inscription names victories over the Lullubi, and it shows Akkadian soldiers on a wooded mountain with Naram-Sin in a horned helmet.', kind: 'observation', certainty: 'high', sourceIds: ['source.akkad.louvre-stele', 'source.akkad.smarthistory-stele'], reviewStatus: 'reviewed' },
  { id: 'claim.akkad.horned-helmet', statement: 'In Akkadian art, a horned helmet was a sign of divinity.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.akkad.smarthistory-stele'], reviewStatus: 'reviewed' },
  { id: 'claim.akkad.stele-booty', statement: 'In the twelfth century BCE the Elamite king Shutruk-Nahhunte took the stele from Sippar to Susa as war booty and had an inscription carved on its mountain saying so; excavators found it at Susa in 1898.', kind: 'observation', certainty: 'high', sourceIds: ['source.akkad.louvre-stele', 'source.akkad.smarthistory-stele'], reviewStatus: 'reviewed' },
  { id: 'claim.akkad.curse-of-agade', statement: 'The Curse of Agade, a Sumerian poem known from Old Babylonian copies made centuries after Naram-Sin, blames Agade’s ruin on his attack on Enlil’s temple and describes grass growing on the city’s canal towpaths.', kind: 'later-tradition', certainty: 'high', sourceIds: ['source.akkad.curse-etcsl', 'source.akkad.curse-cdli'], reviewStatus: 'reviewed' },
];

export const akkadPrompts: UnderstandingPrompt[] = [
  {
    id: 'prompt.akkad.local-arrangements', lessonId, kind: 'supported-selection', required: true,
    question: 'At Leilan, archaeologists found a fortified administrative building with grain-processing rooms and tablets. At Urkesh, they found seal impressions naming a daughter of an Akkadian ruler. What is the strongest conclusion?',
    hint: 'Ask what the finds show at each place before deciding whether the two cities were governed in the same way.',
    explanation: 'Leilan has an Akkadian administrative building, with its ovens, tablets and an official’s sealings. The Urkesh sealings show a royal-family tie inside a local palace, but her exact role and the city’s political arrangement remain uncertain. Distant power could work through different local relationships.',
    options: [
      { id: 'option.akkad.different-ties', label: 'Both places had Akkadian connections, but the evidence points to different or uncertain arrangements.', feedback: 'Yes. The Leilan building and the Urkesh sealings show different kinds of connection; they cannot be flattened into one identical province.' },
      { id: 'option.akkad.identical-provinces', label: 'Both cities had identical Akkadian offices because a royal name appears in each place.', feedback: 'A royal name or family tie does not establish every office and practice in a city. Leilan has stronger evidence for an administrative installation.' },
      { id: 'option.akkad.no-connection', label: 'Neither city had a meaningful Akkadian connection.', feedback: 'The Leilan complex and the Urkesh sealings are material evidence of connections; the question is what kind of relationship each supports.' },
    ],
  },
  {
    id: 'prompt.akkad.holding-power', lessonId, kind: 'concise-explanation', required: true, minimumResponseLength: 20,
    question: 'Sargon’s inscription says he defeated several cities. Why would a victory alone not tell us how Akkadian rulers kept power? Use one example from Leilan or Urkesh.',
    hint: 'Think about what people would have to keep doing after soldiers left a city.',
    explanation: 'For example: Sargon could claim a victory, but continued rule needed people to grow, carry and bake grain, keep records and carry out orders. Leilan preserves the ovens, sealings and tablets of that work in an Akkadian administrative building. Urkesh shows a different tie, a princess whose seal closed doors in a local palace, although her exact role is uncertain. A victory claim alone cannot tell us how each city was governed.',
  },
];

const sections: Lesson['sections'] = [
  {
    id: 'section.akkad.place-and-question', heading: 'Akkad in Mesopotamia', purpose: 'Locate the lesson and make the distinction between conquering and governing concrete.',
    modules: [
      { id: 'module.akkad.opening-question', type: 'prose', claimIds: ['claim.akkad.agade-quay', 'claim.akkad.trade-places', 'claim.akkad.capital-location'], sourceIds: ['source.akkad.sargon-retinue', 'source.akkad.possehl-meluhha', 'source.akkad.capital-review'], body: 'Sargon, king of Agade, wanted everyone to know how far his reach went. One of his inscriptions boasts that boats from Meluhha, Magan and Dilmun, lands that scholars identify with the Indus cities, Oman and Bahrain, were tied up at the quay of Agade, his capital.\n\nArchaeologists would love to stand on that quay. Nobody knows where it is. Agade, the city that gave the Akkadian kings their name, has never been securely found.' },
      akkadLocatorVisual,
      { id: 'module.akkad.opening-context', type: 'prose', claimIds: ['claim.akkad.period', 'claim.akkad.capital-location', 'claim.akkad.winning-and-governing'], sourceIds: ['source.akkad.met-period', 'source.akkad.capital-review', 'source.akkad.sargon-inscription', 'source.akkad.leilan'], body: 'Agade stood somewhere in Mesopotamia, the land around the Tigris and Euphrates rivers in present-day Iraq. Between about 2350 and 2150 BCE, Sargon and later kings such as Naram-Sin claimed power over cities that had long ruled themselves.\n\nWhen one center claims power over many other communities, historians call it an empire. Claiming it was the easy part. A battle could be won in a day, but keeping a distant city in line after the army went home took officials, food and working relationships with local people. At Kerma you saw that contact between places did not automatically mean one ruled the other. Here the question is what ruling took.' },
    ],
  },
  {
    id: 'section.akkad.conquest-claims', heading: 'Sargon’s conquest claims', purpose: 'Attribute a royal account and distinguish a reported victory from durable control.',
    modules: [
      { id: 'module.akkad.sargon-claims', type: 'prose', claimIds: ['claim.akkad.conquest-claims', 'claim.akkad.sea-to-sea', 'claim.akkad.bread-boast', 'claim.akkad.winning-and-governing'], sourceIds: ['source.akkad.sargon-inscription', 'source.akkad.sargon-retinue'], body: 'Sargon’s own words survive in royal inscriptions that modern scholars have pieced together from several ancient copies, so there is no single stone with its original setting. What the words say is loud: Sargon defeated Uruk, Ur and Umma, old cities with their own gods and kings. The god Enlil, the inscription says, gave him the land from the Upper Sea to the Lower Sea. And citizens of Agade held the governorships. A governor ran a place on the ruler’s behalf.\n\nAnother inscription adds a boast about food: 5,400 men ate bread before him every day. The number is a boast, but it points at a real problem. Bread for 5,400 people meant grain grown, carried, ground and baked by someone, every day.\n\nThese inscriptions are the king’s side of the story. They tell us what Sargon wanted remembered, not what happened in a city once the soldiers left. For that, we need evidence from the cities themselves.' },
    ],
  },
  {
    id: 'section.akkad.leilan-administration', heading: 'Governing at Tell Leilan', purpose: 'Show administrative buildings, grain and records as continued work behind distant rule.',
    modules: [
      { id: 'module.akkad.leilan', type: 'prose', claimIds: ['claim.akkad.leilan-administration', 'claim.akkad.leilan-official', 'claim.akkad.leilan-walls', 'claim.akkad.barley-ration', 'claim.akkad.leilan-schoolroom', 'claim.akkad.leilan-work'], sourceIds: ['source.akkad.leilan'], body: 'Far to the north of Uruk, on the plains of present-day Syria, excavators at Tell Leilan found what Akkadian rule looked like on the ground. After the conquest, the local ruling families were pushed aside. Clay sealings show an Akkadian official, called a šabra, now directing farm work and building projects. The center of it all was a fortified administrative building with walls as much as 6.6 meters thick.\n\nMuch of the work inside was about grain. Room after room held ovens, many of them 1 to 3 meters across, used so heavily that a fine layer of plant residue from the grain covered every floor. Akkadian administrative texts set a laborer’s standard daily ration at two sila of barley, about two liters. Multiply that by every worker and you see why rulers needed a building like this. Across the street, a schoolroom held tablets with a few practice signs, perhaps, the excavators suggest, for training local officials to keep the new records.\n\nNone of these finds names the farmers who grew the barley or says whether they worked willingly.' },
      { id: 'module.akkad.leilan-work', type: 'knowledge', eyebrow: 'Who did the work', title: 'Who did the work', body: 'Holding Leilan was daily work, done by many hands.', claimIds: ['claim.akkad.leilan-work', 'claim.akkad.leilan-walls', 'claim.akkad.leilan-official'], sourceIds: ['source.akkad.leilan'], items: [
        { label: 'Grow and bring grain', detail: 'Farmers raised the barley, and someone carried it in.' },
        { label: 'Process and bake', detail: 'Rooms of large ovens turned it into food, day after day.' },
        { label: 'Record and seal', detail: 'Scribes kept tablets; officials sealed clay to track goods and orders.' },
      ] },
    ],
  },
  {
    id: 'section.akkad.urkesh-ties', heading: 'A royal connection at Urkesh', purpose: 'Use a named woman and local sealings to compare forms of imperial presence.',
    modules: [
      { id: 'module.akkad.urkesh', type: 'prose', claimIds: ['claim.akkad.urkesh-find', 'claim.akkad.taram-sealings', 'claim.akkad.taram-name'], sourceIds: ['source.akkad.urkesh'], body: 'In August 1999, on what was meant to be the last day of digging in one part of the royal palace at Urkesh, excavators unexpectedly began finding inscribed lumps of clay. They kept digging. The impressions named Tar’am-Agade, daughter of Naram-Sin, king of Akkad. Her name means “She loves Akkad,” and the excavators point out that it reads like a political message.\n\nUrkesh, close to Leilan on the map, was the city of its own Hurrian rulers. Tar’am-Agade’s impressions came from a small cylinder seal, about 3 centimeters high, rolled across clay that closed a door in their palace. So her seal was used in Urkesh itself, not just mentioned somewhere else.' },
      akkadSealExampleVisual,
      { id: 'module.akkad.urkesh-limits', type: 'prose', claimIds: ['claim.akkad.taram-sealings', 'claim.akkad.urkesh-relationship'], sourceIds: ['source.akkad.urkesh'], body: 'Why was an Akkadian princess sealing doors in a Hurrian palace? The excavators think she was queen of Urkesh, married to its local ruler: an alliance made by marriage rather than by a governor. They also weigh another possibility: she served as a priestess beside an Akkadian administrator. Either way, her seal shows a royal family tie at work inside the palace. It does not show that Urkesh was run the way Leilan was.\n\nShe is one of the few people in this story besides a king whom we can name, and even she reaches us through palace life. Most people in Urkesh left no names.' },
    ],
  },
  {
    id: 'section.akkad.naram-sin-stele', heading: 'Naram-Sin’s victory stele', purpose: 'Read a surviving royal artwork as purposeful self-presentation, then name its limits.',
    modules: [
      { id: 'module.akkad.stele-intro', type: 'prose', claimIds: ['claim.akkad.stele-image', 'claim.akkad.stele-details', 'claim.akkad.horned-helmet'], sourceIds: ['source.akkad.louvre-stele', 'source.akkad.smarthistory-stele'], body: 'Tar’am-Agade’s father told his own story in stone. Naram-Sin’s victory stele, a carved slab about 2 meters tall, celebrates a win over the Lullubi, a mountain people. His soldiers climb a wooded mountain. Their enemies fall, flee or lie beneath the king. Above them all stands Naram-Sin, larger than anyone else, wearing a horned helmet, which in Akkadian art was a sign of the gods.' },
      akkadSteleVisual,
      { id: 'module.akkad.stele-limits', type: 'prose', claimIds: ['claim.akkad.stele-image', 'claim.akkad.stele-afterlife', 'claim.akkad.stele-booty'], sourceIds: ['source.akkad.louvre-stele', 'source.akkad.smarthistory-stele'], body: 'The stele is a message, not a battle report. It shows how Naram-Sin wanted his power seen, not how any city was governed afterward, and the defeated Lullubi appear only as the king’s enemies; no account of their own survives.\n\nThe stone’s later life makes the point sharper. It first stood at Sippar, in Mesopotamia. About a thousand years later, in the 1100s BCE, an Elamite king named Shutruk-Nahhunte carried it off to Susa as war booty and had his own inscription carved on the mountain. One conqueror’s monument became another conqueror’s trophy. French excavators found it at Susa in 1898. Much of Naram-Sin’s original inscription is lost.' },
    ],
  },
  {
    id: 'section.akkad.regional-change', heading: 'Changes in different regions', purpose: 'Resolve the question without a uniform collapse or monocausal drought story.',
    modules: [
      { id: 'module.akkad.regional-change', type: 'prose', claimIds: ['claim.akkad.leilan-unfinished', 'claim.akkad.uneven-change', 'claim.akkad.drought-limits', 'claim.akkad.curse-of-agade', 'claim.akkad.winning-and-governing', 'claim.akkad.capital-location'], sourceIds: ['source.akkad.leilan', 'source.akkad.weiss', 'source.akkad.isotopes', 'source.akkad.curse-etcsl', 'source.akkad.curse-cdli', 'source.akkad.capital-review'], body: 'Akkadian power did not last. At Tell Leilan, the last Akkadian building project, a large structure on basalt foundations, was never finished. Excavators found basalt boulders lying a few meters from a half-built wall, where the builders had left them. By about 2140 BCE, Leilan lay in ruins.\n\nWhy did places like Leilan empty out? Some researchers link its abandonment and other northern changes to a drier climate that hurt rain-fed farming. Others point to sites where people kept living and eating much as before during the same broad period. Drier conditions may have mattered in some places, but the evidence does not show one sudden drought ending Akkadian rule everywhere. Political ties could break, too.\n\nPeople in Mesopotamia wanted an explanation as well. Centuries later, scribes copied a poem now called the Curse of Agade. In it, Naram-Sin attacks the temple of the god Enlil, and the angry gods send invaders and curse his city until grass grows long on its canal towpaths. The poem is later tradition. It tells us how Akkad’s fall was remembered, not what caused it.\n\nHolding power had taken far more than Sargon’s boasts: officials and seals, ovens and barley, royal family ties and messages carved in stone, all depending on people far from the king. Those ties were strong in some places, thin in others, and they came apart in different ways. Agade itself, the city whose name runs through all of it, is still waiting to be found.' },
    ],
  },
  {
    id: 'section.akkad.understanding', heading: 'Explain Akkadian rule', purpose: 'Use local evidence and explain what ruling at distance required.',
    modules: [
      { id: 'module.akkad.local-check', type: 'prompt', promptId: 'prompt.akkad.local-arrangements', claimIds: ['claim.akkad.leilan-administration', 'claim.akkad.urkesh-relationship'], sourceIds: ['source.akkad.leilan', 'source.akkad.urkesh'] },
      { id: 'module.akkad.holding-check', type: 'prompt', promptId: 'prompt.akkad.holding-power', claimIds: ['claim.akkad.conquest-claims', 'claim.akkad.winning-and-governing'], sourceIds: ['source.akkad.sargon-inscription', 'source.akkad.leilan', 'source.akkad.urkesh'] },
    ],
  },
];

export const akkadLesson: Lesson = {
  id: lessonId, legacyAliases: [], status: 'published',
  title: 'Akkad and the Problem of Empire', masthead: 'c. 2350–2150 BCE', place: 'Mesopotamia · present-day Iraq and neighboring regions',
  chronology: { startYear: -2350, endYear: -2150, display: 'c. 2350–2150 BCE', approximate: true },
  significance: 'Akkadian rulers claimed far-reaching victories, but keeping power across different cities depended on officials, supplies and local relationships.',
  learningOutcome: 'You explored why winning cities and governing them are different, and how local evidence can test a ruler’s claim.',
  orientationMapModuleId: 'module.akkad.locator',
  sectionIdsRequired: sections.map((section) => section.id), sections,
  claimIds: akkadClaims.map((claim) => claim.id), sourceIds: akkadSources.map((source) => source.id), mediaIds: akkadMedia.map((media) => media.id), promptIds: akkadPrompts.map((prompt) => prompt.id),
};

export const akkadContent: AuthoredContentModule = { sources: akkadSources, claims: akkadClaims, media: akkadMedia, lessons: [akkadLesson], prompts: akkadPrompts };
