import type { Claim, Lesson, Source, UnderstandingPrompt } from '../../src/domains/contracts';
import type { AuthoredContentModule } from '../assemble';

export const caralAndeanUrbanismSources: Source[] = [
  {
    id: 'source.caral.unesco-1269',
    title: 'Sacred City of Caral-Supe',
    url: 'https://whc.unesco.org/en/list/1269/',
    publisher: 'UNESCO World Heritage Centre',
    accessedOn: '2026-08-19',
    licenseOrUse: 'Official heritage synthesis cited for research; description is CC BY-SA IGO 3.0, maps and site photographs are not redistributed from this page',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.caral.unesco-maps',
    title: 'Sacred City of Caral-Supe maps',
    url: 'https://whc.unesco.org/en/list/1269/maps/',
    publisher: 'UNESCO World Heritage Centre',
    accessedOn: '2026-08-19',
    licenseOrUse: 'Official coordinate and inscribed-property record; maps are reference-only unless separately cleared',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.caral.unesco-nomination',
    title: 'Sacred City of Caral-Supe nomination file',
    url: 'https://whc.unesco.org/uploads/nominations/1269.pdf',
    publisher: 'UNESCO World Heritage Centre / Republic of Peru',
    accessedOn: '2026-08-19',
    licenseOrUse: 'State Party nomination cited for architecture and economy; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.caral.shady-haas-creamer-2001',
    title: 'Dating Caral, a Preceramic Site in the Supe Valley on the Central Coast of Peru',
    url: 'https://doi.org/10.1126/science.1059519',
    publisher: 'Science',
    accessedOn: '2026-08-19',
    licenseOrUse: 'Peer-reviewed radiocarbon and settlement paper cited for research; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.caral.haas-creamer-ruiz-2004',
    title: 'Dating the Late Archaic occupation of the Norte Chico region in Peru',
    url: 'https://doi.org/10.1038/nature03146',
    publisher: 'Nature',
    accessedOn: '2026-08-19',
    licenseOrUse: 'Peer-reviewed regional chronology cited for research; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.caral.sandweiss-2009',
    title: 'Environmental change and economic development in coastal Peru between 5,800 and 3,600 years ago',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC2635784/',
    publisher: 'Proceedings of the National Academy of Sciences',
    accessedOn: '2026-08-19',
    licenseOrUse: 'Open-access scholarly synthesis cited for research; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.caral.haas-creamer-2005-power',
    title: 'Power and the Emergence of Complex Polities in the Peruvian Preceramic',
    url: 'https://doi.org/10.1525/ap3a.2005.14.037',
    publisher: 'Archeological Papers of the American Anthropological Association',
    accessedOn: '2026-08-19',
    licenseOrUse: 'Peer-reviewed political interpretation cited for research; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.caral.creamer-haas-2014-peer-polity',
    title: 'Peer-polity interaction in the Norte Chico, Peru, 3000–1800 BC',
    url: 'https://doi.org/10.4324/9781315798288-28',
    publisher: 'Routledge',
    accessedOn: '2026-08-19',
    licenseOrUse: 'Specialist chapter cited for the peer-center interpretation; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.caral.zona-caral',
    title: 'Zona Arqueológica Caral',
    url: 'https://zonacaral.gob.pe/en/',
    publisher: 'Zona Arqueológica Caral / Ministerio de Cultura del Perú',
    accessedOn: '2026-08-19',
    licenseOrUse: 'Official excavation-project synthesis cited for research; site media are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.caral.commons-plaza',
    title: 'Plaza Circular del Templo Mayor',
    url: 'https://commons.wikimedia.org/wiki/File:PeruCaral19.jpg',
    publisher: 'Wikimedia Commons / Håkan Svensson',
    accessedOn: '2026-08-19',
    licenseOrUse: 'CC BY 2.5 photograph of surviving architecture; candidate runtime evidence image',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.caral.shady-2006-pucp',
    title: 'La civilización Caral: sistema social y manejo del territorio y sus recursos',
    url: 'https://doi.org/10.18800/boletindearqueologiapucp.200601.004',
    publisher: 'Boletín de Arqueología PUCP',
    accessedOn: '2026-08-19',
    licenseOrUse: 'Open-access excavator synthesis cited for the knotted-fiber offering; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
];

export const caralAndeanUrbanismClaims: Claim[] = [
  {
    id: 'claim.caral.late-archaic-range',
    statement: 'A major preceramic monumental complex developed on Peru’s north-central coast between about 3000 and 1800 BCE.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.caral.haas-creamer-ruiz-2004', 'source.caral.unesco-1269'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.caral-dates',
    statement: 'Radiocarbon dates from plant fibers in Caral’s construction place monumental architecture around 2627 to 1977 BCE.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.caral.shady-haas-creamer-2001'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.inland-setting',
    statement: 'Caral occupies a dry desert terrace above the green Supe Valley about 23 km inland from the Pacific.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.caral.shady-haas-creamer-2001', 'source.caral.unesco-1269', 'source.caral.sandweiss-2009'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.regional-sites',
    statement: 'Caral is one of multiple large preceramic settlements in the Supe Valley and neighboring valleys.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.caral.shady-haas-creamer-2001', 'source.caral.haas-creamer-ruiz-2004', 'source.caral.unesco-1269'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.monumental-architecture',
    statement: 'Caral’s central zone includes six large platform mounds, sunken circular plazas, and residential architecture over about 65 hectares.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.caral.shady-haas-creamer-2001', 'source.caral.unesco-nomination'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.plaza-observation',
    statement: 'A sunken circular plaza at the foot of a platform mound is a surviving public gathering space connected to the building by a stairway.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.caral.commons-plaza', 'source.caral.unesco-nomination'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.preceramic',
    statement: 'These early monumental sites were built and used without pottery.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.caral.shady-haas-creamer-2001', 'source.caral.haas-creamer-ruiz-2004', 'source.caral.sandweiss-2009'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.cotton-fish-exchange',
    statement: 'Inland irrigation produced cotton and gourds used in fishing technology, while marine fish and shellfish reached inland sites.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.caral.sandweiss-2009', 'source.caral.unesco-nomination', 'source.caral.zona-caral'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.no-checklist',
    statement: 'Pottery, metal tools, wheeled transport, and writing like Egypt’s or Uruk’s were not required for this urban complexity.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.caral.shady-haas-creamer-2001', 'source.caral.sandweiss-2009', 'source.caral.unesco-1269'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.shicra',
    statement: 'Workers packed stones in woven fiber bags to build platform-mound cores; those fibers provided the dated samples.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.caral.shady-haas-creamer-2001', 'source.caral.unesco-nomination'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.labor-and-hierarchy',
    statement: 'Monumental building required organized labor, and residential remains show unequal living spaces.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.caral.unesco-nomination', 'source.caral.shady-haas-creamer-2001'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.not-one-recipe',
    statement: 'Caral-Supe urbanism developed in the Andes independently of Egypt and Mesopotamia.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.caral.unesco-1269', 'source.caral.shady-haas-creamer-2001'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.oldest-qualified',
    statement: 'Calling Caral the oldest city in the Americas is a promotional shortcut; it is among the earliest known urban centers, and nearby sites were also early.',
    kind: 'interpretation',
    certainty: 'contested',
    sourceIds: ['source.caral.unesco-1269', 'source.caral.shady-haas-creamer-2001', 'source.caral.haas-creamer-ruiz-2004'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.polity-disagreement',
    statement: 'Whether Caral was the capital of a consolidated state or one of several peer centers is debated.',
    kind: 'interpretation',
    certainty: 'contested',
    sourceIds: ['source.caral.unesco-1269', 'source.caral.creamer-haas-2014-peer-polity'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.quipu-contested',
    statement: 'A knotted fiber object was found as an offering in a public building; identifying it as an early quipu remains unconfirmed.',
    kind: 'interpretation',
    certainty: 'contested',
    sourceIds: ['source.caral.shady-2006-pucp', 'source.caral.unesco-1269'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.warfare-absence',
    statement: 'Researchers have not reported clear fortifications or battlefield remains for this Preceramic cluster; that absence does not prove a uniquely peaceful society.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.caral.haas-creamer-2005-power'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.evidence-bias',
    statement: 'Most surviving evidence is architecture, plants, marine remains, and ceremonial deposits, so it reveals public building more clearly than ordinary lives.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.caral.unesco-nomination', 'source.caral.sandweiss-2009'],
    reviewStatus: 'reviewed',
  },
];

export const caralAndeanUrbanismPrompts: UnderstandingPrompt[] = [
  {
    id: 'prompt.caral.supported-model',
    lessonId: 'lesson.caral.andean-urbanism',
    kind: 'supported-selection',
    question: 'Which conclusion is best supported by Caral’s monuments and the cotton–fish evidence?',
    explanation: 'The inland mounds, plazas, irrigation, cotton, and marine food remains support a bounded model: people organized large public building projects and linked valley farms with coastal fishing without pottery. They do not prove that Caral copied Egypt, that writing is required for a city, or that the region was a proven peaceful empire.',
    required: true,
    options: [
      { id: 'option.caral.exchange-and-labor', label: 'Inland farming and coastal fishing were connected, and people organized large public building projects without pottery.' },
      { id: 'option.caral.copied-egypt', label: 'Caral’s mounds prove that Andean builders copied Egypt’s pyramids.' },
      { id: 'option.caral.no-writing-no-city', label: 'Because no writing system like cuneiform survives, Caral cannot have been an urban center.' },
      { id: 'option.caral.peaceful-empire', label: 'The missing fortifications prove that one peaceful empire ruled the whole Andes from Caral.' },
    ],
  },
  {
    id: 'prompt.caral.evidence-and-limit',
    lessonId: 'lesson.caral.andean-urbanism',
    kind: 'concise-explanation',
    question: 'Choose the sunken plaza, the cotton–fish exchange, or the missing pottery. How does that evidence help explain urban life at Caral, and what can it not prove by itself?',
    explanation: 'A strong answer makes one supported connection—public gathering space, coastal–inland interdependence, or complexity without a pottery checklist—then names a limit such as exact ceremonies, who held political power, everyday household life, or whether Caral was the only first city.',
    required: true,
    minimumResponseLength: 30,
  },
];

export const caralAndeanUrbanismLesson: Lesson = {
  id: 'lesson.caral.andean-urbanism',
  legacyAliases: ['caral_norte_chico'],
  status: 'draft',
  title: 'Caral and Early Andean Urbanism',
  masthead: 'c. 3000–1800 BCE',
  place: 'Supe Valley, north-central coast of Peru',
  chronology: {
    startYear: -3000,
    endYear: -1800,
    display: 'c. 3000–1800 BCE',
    approximate: true,
  },
  significance: 'People built urban centers in the Andes with irrigation, coastal–inland exchange, and monumental public architecture—without pottery, metal, or writing.',
  sectionIdsRequired: [
    'section.caral.another-way',
    'section.caral.coast-and-valley',
    'section.caral.plaza',
    'section.caral.how-built',
    'section.caral.what-it-can-prove',
    'section.caral.world-check',
  ],
  sections: [
    {
      id: 'section.caral.another-way',
      heading: 'Another way to build a city',
      purpose: 'Break the Uruk/Egypt checklist and pose the preceramic urban problem',
      modules: [
        {
          id: 'module.caral.opening',
          type: 'prose',
          body: 'If you already have a picture of an early city, it may look like Uruk: crowded houses, clay tablets, and officials counting goods. Or like Egypt: a long river, kings, and carved claims of rule. Walk onto a dry terrace above Peru’s Supe Valley around 2600 BCE and that picture breaks.\n\nHuge platform mounds rise from the desert. Sunken circular plazas sit at their feet. People lived, gathered, farmed, and traded here. But excavators did not find pottery. They did not find metal tools or a writing system like cuneiform or hieroglyphs. If a city needed those things, Caral should not exist. It does.\n\nThis lesson asks how people built urban life here—and what the surviving mounds and remains can actually prove.',
          claimIds: ['claim.caral.no-checklist', 'claim.caral.late-archaic-range', 'claim.caral.preceramic'],
          sourceIds: ['source.caral.shady-haas-creamer-2001', 'source.caral.unesco-1269', 'source.caral.sandweiss-2009'],
        },
      ],
    },
    {
      id: 'section.caral.coast-and-valley',
      heading: 'Coast and valley together',
      purpose: 'Establish inland Caral, coastal fishing, and cotton–fish interdependence without geographic inevitability',
      modules: [
        {
          id: 'module.caral.geography',
          type: 'prose',
          body: 'Caral is not on the beach. It sits about 23 kilometers inland, on a dry terrace looking down on a green river valley. The Pacific Ocean is west. The Andes rise east. Most of the year, this coastal desert is extremely dry. River water, moved through irrigation, made farming possible.\n\nDown at the river mouth, coastal communities such as Áspero fished the rich Pacific waters. Inland, people grew cotton, gourds, squash, beans, and other plants. Cotton could become nets. Gourds could become floats and containers. Dried fish and shellfish could travel inland. The two zones needed each other.\n\nA connected landscape is not the same thing as a kingdom. The valley and coast made exchange possible. People still had to organize the work that turned fish, fiber, and water into lasting public buildings.',
          claimIds: ['claim.caral.inland-setting', 'claim.caral.cotton-fish-exchange', 'claim.caral.regional-sites'],
          sourceIds: ['source.caral.shady-haas-creamer-2001', 'source.caral.sandweiss-2009', 'source.caral.unesco-nomination', 'source.caral.zona-caral'],
        },
        {
          id: 'module.caral.two-zones',
          type: 'knowledge',
          eyebrow: 'Two zones, one system',
          title: 'Coast and valley were not the same place',
          body: 'Hold these three relationships in view. None of them is a political border drawn with modern precision.',
          items: [
            { label: 'The coast', detail: 'Fishing communities at the river mouth, including Áspero, harvested anchovy, other fish, and shellfish.' },
            { label: 'The inland valley', detail: 'Caral and other centers sat on desert terraces above irrigated fields of cotton, gourds, and food plants.' },
            { label: 'The exchange', detail: 'Fiber and containers could move toward the sea; marine protein could move inland. Each side made the other more productive.' },
          ],
          claimIds: ['claim.caral.inland-setting', 'claim.caral.cotton-fish-exchange'],
          sourceIds: ['source.caral.sandweiss-2009', 'source.caral.unesco-nomination', 'source.caral.zona-caral'],
        },
      ],
    },
    {
      id: 'section.caral.plaza',
      heading: 'A sunken plaza and a platform mound',
      purpose: 'Observe surviving public architecture before interpreting political meaning',
      modules: [
        {
          id: 'module.caral.plaza-first-look',
          type: 'prose',
          body: 'Look for a circular hollow at the foot of a stepped mound. That hollow is a sunken circular plaza. A stairway climbs from the plaza onto the platform mound above, a building later visitors often call a pyramid. The plaza is architecture you can still see. The exact ceremonies held there are not.\n\nAround the site, six large platform mounds dominate a central zone of about 65 hectares. Some residential buildings sit near the monuments. Others sit farther out and are simpler. That difference is evidence of unequal living, not a roll call of named rulers.',
          claimIds: ['claim.caral.plaza-observation', 'claim.caral.monumental-architecture', 'claim.caral.labor-and-hierarchy'],
          sourceIds: ['source.caral.commons-plaza', 'source.caral.unesco-nomination', 'source.caral.shady-haas-creamer-2001'],
        },
        {
          id: 'module.caral.plaza-observe',
          type: 'knowledge',
          eyebrow: 'Observation before interpretation',
          title: 'Four details worth holding onto',
          body: 'An observation names what survives. An interpretation explains why it may matter.',
          items: [
            { label: 'A lowered circle', detail: 'The plaza is cut down into the ground, so a crowd could gather below the mound rather than on a flat empty yard.' },
            { label: 'A stairway', detail: 'The plaza is connected to the platform above, not standing as a separate leftover hole.' },
            { label: 'Stepped mass', detail: 'The mound is a huge stack of terraces. It is a public building, not a natural sand dune.' },
            { label: 'Unequal houses', detail: 'Better-built residences cluster nearer the monuments; simpler dwellings lie farther out.' },
          ],
          claimIds: ['claim.caral.plaza-observation', 'claim.caral.monumental-architecture', 'claim.caral.labor-and-hierarchy'],
          sourceIds: ['source.caral.commons-plaza', 'source.caral.unesco-nomination'],
        },
      ],
    },
    {
      id: 'section.caral.how-built',
      heading: 'How the monuments were built',
      purpose: 'Turn monumentality into dated human labor and reject the primitive-without-pottery story',
      modules: [
        {
          id: 'module.caral.shicra-work',
          type: 'prose',
          body: 'The mounds were not poured like modern concrete. Workers packed stones into woven fiber bags, called shicra, and stacked them inside retaining walls. Those plant fibers survived in the dry climate. Radiocarbon dates from them place Caral’s monumental construction around 2627 to 1977 BCE.\n\nBuilding on this scale required planning, many workers, food, and people who directed work. Music may have been part of public gatherings: excavators found bird-bone flutes in a sunken circular gathering space. The instruments survive. The songs do not.\n\nNo pottery does not mean no skill. People used gourds, baskets, fiber, and stone. They solved different problems with different tools.',
          claimIds: ['claim.caral.shicra', 'claim.caral.caral-dates', 'claim.caral.preceramic', 'claim.caral.labor-and-hierarchy'],
          sourceIds: ['source.caral.shady-haas-creamer-2001', 'source.caral.unesco-nomination', 'source.caral.sandweiss-2009'],
        },
        {
          id: 'module.caral.work-not-magic',
          type: 'knowledge',
          eyebrow: 'A city in practice',
          title: 'Public buildings depended on repeated work',
          body: 'The mounds are visible from far away. They became durable through the work of many people whose names are gone.',
          items: [
            { label: 'Farmers and irrigators', detail: 'Moved river water onto desert land and grew cotton, gourds, and food plants.' },
            { label: 'Fishers and net makers', detail: 'Turned fiber into nets and sent marine protein inland.' },
            { label: 'Quarry and bag crews', detail: 'Filled shicra bags, hauled stone, and stacked cores inside retaining walls.' },
            { label: 'Organizers', detail: 'Directed labor, food, and ceremony. Their exact titles and powers remain uncertain.' },
          ],
          claimIds: ['claim.caral.labor-and-hierarchy', 'claim.caral.cotton-fish-exchange', 'claim.caral.shicra', 'claim.caral.evidence-bias'],
          sourceIds: ['source.caral.unesco-nomination', 'source.caral.sandweiss-2009', 'source.caral.shady-haas-creamer-2001'],
        },
      ],
    },
    {
      id: 'section.caral.what-it-can-prove',
      heading: 'What this case can prove',
      purpose: 'Qualify oldest-city, state, quipu, and peace stories while keeping the independent urban model',
      modules: [
        {
          id: 'module.caral.limits',
          type: 'prose',
          body: 'Caral is one of several large preceramic centers in the Supe Valley and neighboring valleys. Together they show that urban complexity in the Andes began early and independently of Egypt or Mesopotamia. That is the claim this lesson needs.\n\nSome descriptions call Caral the oldest city in the Americas and the capital of a fully formed state. Those phrases go beyond what one site can prove. Nearby sites were also early. Archaeologists disagree about whether Caral ruled the others or whether several centers competed as peers.\n\nA knotted fiber object was found as an offering in a public building. The excavation team presents it as an early quipu, a cord record later famous in the Andes. Other specialists have not confirmed that identification. The object is real. The reading is not settled.\n\nResearchers have not found clear fortifications or battlefield debris from this period. That is important. It is not the same as proving that life was peaceful or that nobody was coerced. Absence of those remains is a limit of the evidence, not a complete social portrait.\n\nMost surviving evidence is architecture, plants, fish remains, and ceremonial deposits. Farmers, net makers, quarry workers, and children are in the story even when their names are not.',
          claimIds: ['claim.caral.not-one-recipe', 'claim.caral.oldest-qualified', 'claim.caral.polity-disagreement', 'claim.caral.quipu-contested', 'claim.caral.warfare-absence', 'claim.caral.evidence-bias'],
          sourceIds: ['source.caral.unesco-1269', 'source.caral.haas-creamer-ruiz-2004', 'source.caral.creamer-haas-2014-peer-polity', 'source.caral.shady-2006-pucp', 'source.caral.haas-creamer-2005-power'],
        },
        {
          id: 'module.caral.can-cannot',
          type: 'knowledge',
          eyebrow: 'Evidence boundary',
          title: 'What Caral can—and cannot—do',
          body: 'A site can be powerful without answering every question.',
          items: [
            { label: 'It can show', detail: 'That people built large public architecture and linked inland farms with coastal fishing without pottery, metal, or writing.' },
            { label: 'It can support', detail: 'A claim that urban life in the Andes developed on its own path, not as a copy of Egypt or Mesopotamia.' },
            { label: 'It cannot prove alone', detail: 'That Caral was the one first city, the capital of a settled territorial state, or a uniquely peaceful society.' },
            { label: 'It cannot recover', detail: 'The thoughts of ordinary builders, the meaning of every ceremony, or a readable administration from one knotted offering.' },
          ],
          claimIds: ['claim.caral.no-checklist', 'claim.caral.not-one-recipe', 'claim.caral.oldest-qualified', 'claim.caral.quipu-contested', 'claim.caral.warfare-absence'],
          sourceIds: ['source.caral.unesco-1269', 'source.caral.creamer-haas-2014-peer-polity', 'source.caral.shady-2006-pucp', 'source.caral.haas-creamer-2005-power'],
        },
      ],
    },
    {
      id: 'section.caral.world-check',
      heading: 'World Check',
      purpose: 'Require one supported urban model and one explicit evidence limit',
      modules: [
        {
          id: 'module.caral.prompt-model',
          type: 'prompt',
          promptId: 'prompt.caral.supported-model',
          claimIds: [],
          sourceIds: [],
        },
        {
          id: 'module.caral.prompt-limit',
          type: 'prompt',
          promptId: 'prompt.caral.evidence-and-limit',
          claimIds: [],
          sourceIds: [],
        },
      ],
    },
  ],
  claimIds: caralAndeanUrbanismClaims.map((claim) => claim.id),
  sourceIds: caralAndeanUrbanismSources.map((source) => source.id),
  mediaIds: [],
  promptIds: caralAndeanUrbanismPrompts.map((prompt) => prompt.id),
};

export const caralAndeanUrbanismContent: AuthoredContentModule = {
  sources: caralAndeanUrbanismSources,
  claims: caralAndeanUrbanismClaims,
  prompts: caralAndeanUrbanismPrompts,
  lessons: [caralAndeanUrbanismLesson],
};
