import type { Claim, KnowledgeCard, Lesson, MediaAsset, Source, UnderstandingPrompt } from '../../src/domains/contracts';
import type { AuthoredContentModule } from '../assemble';
import { mediaLocator } from '../shared/media-locator';

export const caralAndeanUrbanismSources: Source[] = [
  {
    id: 'source.caral.unesco-1269',
    title: 'Sacred City of Caral-Supe',
    url: 'https://whc.unesco.org/en/list/1269/',
    publisher: 'UNESCO World Heritage Centre',
    accessedOn: '2026-08-19',
    licenseOrUse: 'Official heritage synthesis cited for research; description is CC BY-SA IGO 3.0, maps and site photographs are not redistributed from this page',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.caral.unesco-maps',
    title: 'Sacred City of Caral-Supe maps',
    url: 'https://whc.unesco.org/en/list/1269/maps/',
    publisher: 'UNESCO World Heritage Centre',
    accessedOn: '2026-08-19',
    licenseOrUse: 'Official coordinate and inscribed-property record; maps are reference-only unless separately cleared',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.caral.unesco-nomination',
    title: 'Sacred City of Caral-Supe nomination file',
    url: 'https://whc.unesco.org/uploads/nominations/1269.pdf',
    publisher: 'UNESCO World Heritage Centre / Republic of Peru',
    accessedOn: '2026-08-19',
    licenseOrUse: 'State Party nomination cited for architecture and economy; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.caral.shady-haas-creamer-2001',
    title: 'Dating Caral, a Preceramic Site in the Supe Valley on the Central Coast of Peru',
    url: 'https://doi.org/10.1126/science.1059519',
    publisher: 'Science',
    accessedOn: '2026-08-19',
    licenseOrUse: 'Peer-reviewed radiocarbon and settlement paper cited for research; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.caral.haas-creamer-ruiz-2004',
    title: 'Dating the Late Archaic occupation of the Norte Chico region in Peru',
    url: 'https://doi.org/10.1038/nature03146',
    publisher: 'Nature',
    accessedOn: '2026-08-19',
    licenseOrUse: 'Peer-reviewed regional chronology cited for research; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.caral.sandweiss-2009',
    title: 'Environmental change and economic development in coastal Peru between 5,800 and 3,600 years ago',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC2635784/',
    publisher: 'Proceedings of the National Academy of Sciences',
    accessedOn: '2026-08-19',
    licenseOrUse: 'Open-access scholarly synthesis cited for research; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.caral.haas-creamer-2005-power',
    title: 'Power and the Emergence of Complex Polities in the Peruvian Preceramic',
    url: 'https://doi.org/10.1525/ap3a.2005.14.037',
    publisher: 'Archeological Papers of the American Anthropological Association',
    accessedOn: '2026-08-19',
    licenseOrUse: 'Peer-reviewed political interpretation cited for research; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.caral.creamer-haas-2014-peer-polity',
    title: 'Peer-polity interaction in the Norte Chico, Peru, 3000–1800 BC',
    url: 'https://doi.org/10.4324/9781315798288-28',
    publisher: 'Routledge',
    accessedOn: '2026-08-19',
    licenseOrUse: 'Specialist chapter cited for the peer-center interpretation; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.caral.zona-caral',
    title: 'Zona Arqueológica Caral',
    url: 'https://zonacaral.gob.pe/en/',
    publisher: 'Zona Arqueológica Caral / Ministerio de Cultura del Perú',
    accessedOn: '2026-08-19',
    licenseOrUse: 'Official excavation-project synthesis cited for research; site media are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.caral.commons-plaza',
    title: 'Plaza Circular del Templo Mayor',
    url: 'https://commons.wikimedia.org/wiki/File:PeruCaral19.jpg',
    publisher: 'Wikimedia Commons / Håkan Svensson',
    accessedOn: '2026-08-19',
    licenseOrUse: 'CC BY 2.5 photograph of surviving architecture; runtime evidence image with attribution',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.caral.commons-almacenes-shicras',
    title: 'Almacenes con Shicras',
    url: 'https://commons.wikimedia.org/wiki/File:Almacenes_con_Shicras.jpg',
    publisher: 'Wikimedia Commons / Gisela Xiomara Garcia Almonacid',
    accessedOn: '2026-08-19',
    licenseOrUse: 'CC BY-SA 4.0 photograph of excavated shicra bags in a retaining-wall core; runtime evidence image with attribution, and reconstruction reference',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.caral.commons-vista-frontal',
    title: 'Vista frontal de la imponente Pirámide Mayor de la Ciudad Sagrada de Caral',
    url: 'https://commons.wikimedia.org/wiki/File:Vista_frontal_de_la_imponente_Pirámide_Mayor_de_la_Ciudad_Sagrada_de_Caral.jpg',
    publisher: 'Wikimedia Commons / JOSE MORALES CIENCIA POLITICA UNMSM',
    accessedOn: '2026-08-20',
    licenseOrUse: 'CC BY-SA 4.0 photograph used as an independent architectural identification check for the plaza–stair–pyramid axis; not the runtime hero',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.caral.commons-peru-physical-map',
    title: 'Physical map of Peru',
    url: 'https://commons.wikimedia.org/wiki/File:Peru_physical_map.svg',
    publisher: 'Wikimedia Commons / Urutseg',
    accessedOn: '2026-08-19',
    licenseOrUse: 'CC0 1.0 public-domain dedication; SRTM-derived topographic raster used as geographic composition reference',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.caral.scientific-reports-aspero-2023',
    title: 'Analysis of starch grains trapped in human dental calculus in Áspero, Peru during the Initial Formative Period (3000–1800 BCE)',
    url: 'https://doi.org/10.1038/s41598-023-41015-6',
    publisher: 'Scientific Reports',
    accessedOn: '2026-08-19',
    licenseOrUse: 'Open-access CC BY 4.0 scholarly article cited for Áspero coordinates and coastal setting; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.caral.shady-2006-pucp',
    title: 'La civilización Caral: sistema social y manejo del territorio y sus recursos',
    url: 'https://doi.org/10.18800/boletindearqueologiapucp.200601.004',
    publisher: 'Boletín de Arqueología PUCP',
    accessedOn: '2026-08-19',
    licenseOrUse: 'Open-access CC BY 4.0 excavator synthesis cited for the knotted-fiber offering, fisher–farmer exchange goods, stone hauling, building burial cycles, and unequal diets; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
];

export const caralAndeanUrbanismClaims: Claim[] = [
  {
    id: 'claim.caral.late-archaic-range',
    statement: 'A major preceramic monumental complex developed on Peru’s north-central coast between about 3000 and 1800 BCE.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.caral.haas-creamer-ruiz-2004', 'source.caral.unesco-1269'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.caral-dates',
    statement: 'Radiocarbon dates from plant fibers in Caral’s construction place monumental architecture around 2627 to 1977 BCE.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.caral.shady-haas-creamer-2001'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.dating-published-2001',
    statement: 'Ruth Shady Solís, Jonathan Haas, and Winifred Creamer published Caral’s radiocarbon dates in Science in 2001.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.caral.shady-haas-creamer-2001'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.eighteen-supe-sites',
    statement: 'Caral is one of 18 large preceramic sites in the Supe Valley.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.caral.shady-haas-creamer-2001'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.first-pyramid-same-era',
    statement: 'Caral’s monumental building had begun by about 2627 BCE, roughly when Egypt’s first pyramid was built for King Djoser at Saqqara, around 2630 BCE on the chronology the nomination file cites; the two developed independently.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.caral.shady-haas-creamer-2001', 'source.caral.unesco-nomination'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.fisher-farmer-exchange',
    statement: 'According to the excavators, coastal fishers supplied dried anchovies and shellfish while valley farmers supplied cotton, gourds, squash, beans, sweet potatoes, and other plants; Áspero faced one of the richest anchovy fisheries, and a cotton fishing net at least 8 by 4 meters was found at the early fishing village of Bandurria.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.caral.shady-2006-pucp', 'source.caral.unesco-nomination'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.greater-pyramid-plaza',
    statement: 'The Greater Pyramid is Caral’s largest building, about 150 by 170 meters at the base and 19 to 30 meters high; its sunken circular plaza has an inner diameter of about 21.5 meters, inner walls estimated at about 3 meters high, and a stairway leading toward the mound.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.caral.unesco-nomination'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.unequal-tables',
    statement: 'The excavators report that large fish, anchovies, shellfish, and deer meat frequently reached the tables of Caral’s authorities and officials.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.caral.shady-2006-pucp'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.human-hauling',
    statement: 'No pack animals were used; stone was moved from quarries with ropes and plant-fiber bags made for the purpose, and shicra were woven reed bags.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.caral.shady-2006-pucp', 'source.caral.unesco-nomination'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.burial-and-rebuilding',
    statement: 'Caral’s public buildings were rebuilt in repeated cycles: older rooms were buried, often with shicra bags full of stones, and new rooms were built on top.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.caral.unesco-nomination', 'source.caral.shady-2006-pucp'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.bone-flutes',
    statement: 'A set of 32 small bone flutes, decorated with incisions and red and black paint, was found in the sunken circular plaza of the Amphitheater Temple, the largest sunken circular plaza in Caral.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.caral.unesco-nomination'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.quipu-twelfth-step',
    statement: 'The knotted fiber object was part of an offering placed on the twelfth step of the central stairway of the Gallery Pyramid, with objects the excavators link to the sea and to music.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.caral.unesco-nomination'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.inland-setting',
    statement: 'Caral occupies a dry desert terrace above the green Supe Valley about 23 km inland from the Pacific.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.caral.shady-haas-creamer-2001', 'source.caral.unesco-1269', 'source.caral.sandweiss-2009', 'source.caral.scientific-reports-aspero-2023'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.regional-sites',
    statement: 'Caral is one of multiple large preceramic settlements in the Supe Valley and neighboring valleys.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.caral.shady-haas-creamer-2001', 'source.caral.haas-creamer-ruiz-2004', 'source.caral.unesco-1269'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.monumental-architecture',
    statement: 'Caral’s central zone includes six large platform mounds, sunken circular plazas, and residential architecture over about 65 hectares.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.caral.shady-haas-creamer-2001', 'source.caral.unesco-nomination'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.plaza-observation',
    statement: 'A sunken circular plaza at the foot of a platform mound is a surviving public gathering space connected to the building by a stairway.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.caral.commons-plaza', 'source.caral.unesco-nomination'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.preceramic',
    statement: 'These early monumental sites were built and used without pottery.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.caral.shady-haas-creamer-2001', 'source.caral.haas-creamer-ruiz-2004', 'source.caral.sandweiss-2009'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.cotton-fish-exchange',
    statement: 'Inland irrigation produced cotton and gourds used in fishing technology, while marine fish and shellfish reached inland sites.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.caral.sandweiss-2009', 'source.caral.unesco-nomination', 'source.caral.zona-caral'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.no-checklist',
    statement: 'Pottery, metal tools, wheeled transport, and writing like Egypt’s or Uruk’s were not required for this urban complexity.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.caral.shady-haas-creamer-2001', 'source.caral.sandweiss-2009', 'source.caral.unesco-1269'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.shicra',
    statement: 'Workers packed stones in woven fiber bags to build platform-mound cores; those fibers provided the dated samples.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.caral.shady-haas-creamer-2001', 'source.caral.unesco-nomination'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.labor-and-hierarchy',
    statement: 'Monumental building required organized labor, and residential remains show unequal living spaces.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.caral.unesco-nomination', 'source.caral.shady-haas-creamer-2001'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.not-one-recipe',
    statement: 'Caral-Supe urbanism developed in the Andes independently of Egypt and Mesopotamia.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.caral.unesco-1269', 'source.caral.shady-haas-creamer-2001'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.oldest-qualified',
    statement: 'Calling Caral the oldest city in the Americas is a promotional shortcut; it is among the earliest known urban centers, and nearby sites were also early.',
    kind: 'interpretation',
    certainty: 'contested',
    sourceIds: ['source.caral.unesco-1269', 'source.caral.shady-haas-creamer-2001', 'source.caral.haas-creamer-ruiz-2004'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.polity-disagreement',
    statement: 'Whether Caral was the capital of a consolidated state or one of several peer centers is debated.',
    kind: 'interpretation',
    certainty: 'contested',
    sourceIds: ['source.caral.unesco-1269', 'source.caral.creamer-haas-2014-peer-polity'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.quipu-contested',
    statement: 'A knotted fiber object was found as an offering in a public building; identifying it as an early quipu remains unconfirmed.',
    kind: 'interpretation',
    certainty: 'contested',
    sourceIds: ['source.caral.shady-2006-pucp', 'source.caral.unesco-1269'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.warfare-absence',
    statement: 'Researchers have not reported clear fortifications or battlefield remains for this Preceramic cluster; that absence does not prove a uniquely peaceful society.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.caral.haas-creamer-2005-power'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.caral.evidence-bias',
    statement: 'Most surviving evidence is architecture, plants, marine remains, and ceremonial deposits, so it reveals public building more clearly than ordinary lives.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.caral.unesco-nomination', 'source.caral.sandweiss-2009'],
    reviewStatus: 'reviewed',
  },
];

export const caralAndeanUrbanismMedia: MediaAsset[] = [
  {
    id: 'media.caral.supe-valley-map',
    locator: mediaLocator('media.caral.supe-valley-map'),
    alt: 'West-facing illustrated map of Peru’s north-central coast with the Pacific Ocean on the left, Áspero at the Supe River mouth, inland Caral on a pale desert terrace above the green Supe Valley, and the Andes to the east',
    depictionMode: 'map',
    depictionLabel: 'Evidence-based historical map · shorelines, river width, and terrace edges are approximate',
    rightsLabel: 'Chronos original raster map edit · geographic reference by Urutseg, CC0 1.0, from SRTM topography',
    sourceIds: ['source.caral.commons-peru-physical-map', 'source.caral.unesco-maps', 'source.caral.shady-haas-creamer-2001', 'source.caral.scientific-reports-aspero-2023'],
    visualBriefRef: 'docs/research/caral-supe-valley-map.md#generated-artwork-lineage',
    reviewStatus: 'approved',
  },
  {
    id: 'media.caral.site-hero',
    locator: mediaLocator('media.caral.site-hero'),
    alt: 'High-angle illustration of conserved Caral: a sunken circular plaza in the foreground, a central stairway, and the stepped Pirámide Mayor with room-like stone enclosures, dry terrace, and a green valley behind',
    depictionMode: 'evidence',
    depictionLabel: 'Illustrated from surviving ruins · not a photograph, not a reconstructed city',
    rightsLabel: 'Chronos original illustration',
    sourceIds: ['source.caral.unesco-nomination', 'source.caral.commons-vista-frontal'],
    visualBriefRef: 'docs/research/caral-andean-urbanism.md#image-lifecycle',
    reviewStatus: 'approved',
  },
  {
    id: 'media.caral.sunken-plaza',
    locator: mediaLocator('media.caral.sunken-plaza'),
    alt: 'Sunken circular plaza at the foot of a stepped platform mound at Caral, with a stone stairway climbing from the plaza floor onto the mound and dry hills behind',
    depictionMode: 'evidence',
    depictionLabel: 'Surviving evidence · conserved ruins, not a ceremony in progress',
    rightsLabel: 'Photograph by Håkan Svensson (Xauxa), CC BY 2.5',
    sourceIds: ['source.caral.commons-plaza', 'source.caral.unesco-nomination'],
    visualBriefRef: 'docs/research/caral-andean-urbanism.md#image-lifecycle',
    reviewStatus: 'approved',
  },
  {
    id: 'media.caral.shicra-reconstruction',
    locator: mediaLocator('media.caral.shicra-reconstruction'),
    alt: 'Evidence-led reconstruction of workers filling coarse fiber bags with rounded river stones and stacking those bags as core fill inside a stone retaining wall',
    depictionMode: 'evidence-based-reconstruction',
    depictionLabel: 'Evidence-led reconstruction · the exact crew and moment are illustrative',
    rightsLabel: 'Chronos original reconstruction · bag morphology from Gisela Xiomara Garcia Almonacid, CC BY-SA 4.0',
    sourceIds: ['source.caral.commons-almacenes-shicras', 'source.caral.shady-haas-creamer-2001', 'source.caral.unesco-nomination'],
    visualBriefRef: 'docs/research/caral-andean-urbanism.md#image-lifecycle',
    reviewStatus: 'approved',
  },
];

export const caralAndeanUrbanismPrompts: UnderstandingPrompt[] = [
  {
    id: 'prompt.caral.supported-model',
    lessonId: 'lesson.caral.andean-urbanism',
    kind: 'supported-selection',
    question: 'Which conclusion is best supported by Caral’s monuments and the cotton–fish evidence?',
    explanation: 'The inland mounds, plazas, irrigation, cotton, and marine food remains support a bounded model: people organized large public building projects and linked valley farms with coastal fishing without pottery. They do not prove that Caral copied Egypt, that writing is required for a city, or that the region was a proven peaceful empire.',
    required: true,
    options: [
      { id: 'option.caral.exchange-and-labor', label: 'Inland farming and coastal fishing were connected, and people organized large public building projects without pottery.' },
      { id: 'option.caral.copied-egypt', label: 'Caral’s mounds prove that Andean builders copied Egypt’s pyramids.' },
      { id: 'option.caral.no-writing-no-city', label: 'Because no writing system like cuneiform survives, Caral cannot have been an urban center.' },
      { id: 'option.caral.peaceful-empire', label: 'The missing fortifications prove that one peaceful empire ruled the whole Andes from Caral.' },
    ],
  },
  {
    id: 'prompt.caral.evidence-and-limit',
    lessonId: 'lesson.caral.andean-urbanism',
    kind: 'concise-explanation',
    question: 'Choose the sunken plaza, the cotton–fish exchange, or the missing pottery. How does that evidence help explain urban life at Caral, and what can it not prove by itself?',
    explanation: 'A strong answer makes one supported connection—public gathering space, coastal–inland interdependence, or complexity without a pottery checklist—then names a limit such as exact ceremonies, who held political power, everyday household life, or whether Caral was the only first city.',
    required: true,
    minimumResponseLength: 30,
  },
];

export const caralAndeanUrbanismLesson: Lesson = {
  id: 'lesson.caral.andean-urbanism',
  legacyAliases: ['caral_norte_chico'],
  status: 'published',
  title: 'Caral and Early Andean Urbanism',
  masthead: 'c. 3000–1800 BCE',
  place: 'Supe Valley, north-central coast of Peru',
  chronology: {
    startYear: -3000,
    endYear: -1800,
    display: 'c. 3000–1800 BCE',
    approximate: true,
  },
  significance: 'People built urban centers in the Andes with irrigation, coastal–inland exchange, and monumental public architecture—without pottery, metal, or writing.',
  heroMediaId: 'media.caral.site-hero',
  heroLabel: 'Illustrated ruins',
  heroCaption: 'Illustrated from the conserved sunken circular plaza and stepped Pirámide Mayor. This is not a photograph or a reconstructed city of 2600 BCE.',
  sectionIdsRequired: [
    'section.caral.another-way',
    'section.caral.coast-and-valley',
    'section.caral.plaza',
    'section.caral.how-built',
    'section.caral.what-it-can-prove',
    'section.caral.world-check',
  ],
  sections: [
    {
      id: 'section.caral.another-way',
      heading: 'Another way to build a city',
      purpose: 'Break the Uruk/Egypt checklist and pose the preceramic urban problem',
      modules: [
        {
          id: 'module.caral.opening',
          type: 'prose',
          body: 'The great mounds of Caral, on a dry terrace above Peru’s Supe Valley, are built around bags of stones. Workers wove the bags from reeds, packed them with stones, and stacked them inside stone walls to form each mound’s core. In the desert air, the fiber never rotted. In 2001, the archaeologists Ruth Shady Solís, Jonathan Haas, and Winifred Creamer published radiocarbon dates from it: people were raising monumental buildings here by about 2627 BCE. That is roughly when Egypt’s first pyramid was built at Saqqara, half a world away.\n\nThe strangest thing about Caral is what is missing. If you know Uruk or Egypt, you may picture an early city with clay tablets and officials counting goods, or with kings and carved claims of rule. Caral has six huge platform mounds and sunken circular plazas, but excavators found no pottery, no metal tools, and no writing system like cuneiform or hieroglyphs. If a city needed those things, Caral should not exist. It does.\n\nSo how did people build a city without them, and what can the mounds actually prove? Much of the answer is made of fiber: cotton nets, stone-filled bags, and one knotted cord.',
          claimIds: ['claim.caral.shicra', 'claim.caral.caral-dates', 'claim.caral.dating-published-2001', 'claim.caral.first-pyramid-same-era', 'claim.caral.monumental-architecture', 'claim.caral.no-checklist', 'claim.caral.preceramic'],
          sourceIds: ['source.caral.shady-haas-creamer-2001', 'source.caral.unesco-nomination', 'source.caral.unesco-1269', 'source.caral.sandweiss-2009'],
        },
      ],
    },
    {
      id: 'section.caral.coast-and-valley',
      heading: 'Coast and valley together',
      purpose: 'Establish inland Caral, coastal fishing, and cotton–fish interdependence without geographic inevitability',
      modules: [
        {
          id: 'module.caral.geography',
          type: 'prose',
          body: 'Caral is not on the beach. It sits about 23 kilometers inland, on a pale desert terrace above a green strip of river valley, with the Pacific Ocean to the west and the Andes to the east. Rain almost never falls here, so farming depended on channels that led river water into the fields.\n\nNow follow the fiber. In those fields, people grew cotton and gourds alongside squash, beans, sweet potatoes, and other food plants. Cotton became fishing nets, some at least 8 meters long, and hollow gourds could keep them afloat. At the river mouth, the fishing town of Áspero looked out on one of the richest anchovy fisheries in the world. Fishers sent dried anchovies and shellfish up the valley, where their remains turn up at inland sites, and farmers sent back cotton, gourds, and food. Each zone had something the other needed.\n\nBetween about 3000 and 1800 BCE, Caral was one of 18 large sites in the Supe Valley alone, with more in the neighboring valleys. A connected landscape is not a kingdom, though. People still had to organize the work that turned water, fiber, and fish into lasting public buildings.',
          claimIds: ['claim.caral.inland-setting', 'claim.caral.cotton-fish-exchange', 'claim.caral.fisher-farmer-exchange', 'claim.caral.late-archaic-range', 'claim.caral.eighteen-supe-sites', 'claim.caral.regional-sites'],
          sourceIds: ['source.caral.shady-haas-creamer-2001', 'source.caral.haas-creamer-ruiz-2004', 'source.caral.sandweiss-2009', 'source.caral.shady-2006-pucp', 'source.caral.unesco-nomination', 'source.caral.zona-caral'],
        },
        {
          id: 'module.caral.two-zones',
          type: 'knowledge',
          eyebrow: 'Two zones, one system',
          title: 'Coast and valley were not the same place',
          body: 'Two different places, joined by a river. Neither one was a country with borders.',
          items: [
            { label: 'The coast', detail: 'At the river mouth, fishing towns such as Áspero hauled in anchovies, other fish, and shellfish.' },
            { label: 'The inland valley', detail: 'Caral and other centers sat on desert terraces above irrigated fields of cotton, gourds, and food plants.' },
            { label: 'The exchange', detail: 'Cotton for nets and gourds for floats and containers could move toward the sea; fish and shellfish could move inland. Each side made the other more productive.' },
          ],
          claimIds: ['claim.caral.inland-setting', 'claim.caral.cotton-fish-exchange'],
          sourceIds: ['source.caral.sandweiss-2009', 'source.caral.unesco-nomination', 'source.caral.zona-caral'],
        },
        {
          id: 'module.caral.supe-map',
          type: 'historical-map',
          eyebrow: 'Hold the two zones',
          title: 'Coast at the mouth, city inland',
          body: 'Use the map to keep west and east in view: the Pacific and Áspero at the river mouth, then inland Caral on a dry terrace above the green Supe Valley, with the Andes farther east. The map shows a connected landscape. It does not draw a kingdom.',
          mediaId: 'media.caral.supe-valley-map',
          periodLabel: 'c. 3000–1800 BCE',
          focusPlace: 'Supe Valley, north-central coast of Peru',
          modernContext: 'Pacific coast of present-day Peru; ancient shoreline and river channels changed',
          accessibleSummary: 'A west-to-east map places the Pacific Ocean on the left. Áspero sits at the Supe River mouth. Caral sits inland on a pale desert terrace above a narrow green valley. The Andes rise on the right. No political borders or capital territory are shown.',
          compactLabel: 'Coast and inland valley · no political borders',
          coordinateNote: 'Caral is anchored by UNESCO World Heritage coordinates. Áspero is anchored by published WGS84 coordinates from a 2023 open-access study of the coastal site.',
          uncertaintyNote: 'Shorelines, river width, terrace edges, and the exact ancient course of the Supe River are approximate. The map preserves relative west–east placement rather than reconstructing one surveyed year.',
          depictionStatus: 'evidence-based-reconstruction',
          introLayout: 'dense',
          claimIds: ['claim.caral.inland-setting', 'claim.caral.cotton-fish-exchange', 'claim.caral.regional-sites'],
          sourceIds: ['source.caral.commons-peru-physical-map', 'source.caral.unesco-maps', 'source.caral.shady-haas-creamer-2001', 'source.caral.scientific-reports-aspero-2023'],
        },
      ],
    },
    {
      id: 'section.caral.plaza',
      heading: 'A sunken plaza and a platform mound',
      purpose: 'Observe surviving public architecture before interpreting political meaning',
      modules: [
        {
          id: 'module.caral.plaza-first-look',
          type: 'prose',
          body: 'Caral’s largest platform mound, the kind of stepped building visitors often call a pyramid, is known as the Greater Pyramid. Its base is about 150 by 170 meters, and on its tallest side it rises about 30 meters. At its foot lies a sunken circular plaza: a round floor about 21.5 meters across, set down inside a stone wall that the excavators estimate stood about 3 meters high. A stairway leads up out of the plaza toward the mound. The plaza survives, but no written account describes the gatherings held in it.\n\nIt is one of six large platform mounds spread across a central zone of about 65 hectares, roughly the area of 90 soccer fields. Not everyone lived alike. Houses near the monuments are larger and better built than those farther out, and the excavators report that big fish, shellfish, and deer meat often reached the tables of leaders and officials. That is evidence that some people lived better than others. It is not a list of rulers’ names.',
          claimIds: ['claim.caral.greater-pyramid-plaza', 'claim.caral.plaza-observation', 'claim.caral.monumental-architecture', 'claim.caral.labor-and-hierarchy', 'claim.caral.unequal-tables'],
          sourceIds: ['source.caral.unesco-nomination', 'source.caral.commons-plaza', 'source.caral.shady-haas-creamer-2001', 'source.caral.shady-2006-pucp'],
        },
        {
          id: 'module.caral.plaza-evidence',
          type: 'evidence',
          title: 'The plaza you can still see',
          artifactLabel: 'Surviving evidence · conserved ruins',
          body: 'The circular hollow, its enclosing wall, and the stairway all survive. Find the lowered floor, follow the stairway up onto the mound, and notice the dry hills around the site. Then ask what the space was built for.',
          mediaId: 'media.caral.sunken-plaza',
          claimIds: ['claim.caral.plaza-observation', 'claim.caral.monumental-architecture'],
          sourceIds: ['source.caral.commons-plaza', 'source.caral.unesco-nomination'],
        },
        {
          id: 'module.caral.plaza-observe',
          type: 'knowledge',
          eyebrow: 'What you can see',
          title: 'Four details worth holding onto',
          body: 'Start with what is actually there. Each of these survives at the site today.',
          items: [
            { label: 'A lowered circle', detail: 'The plaza is cut down into the ground, so a crowd could gather below the mound rather than on a flat empty yard.' },
            { label: 'A stairway', detail: 'The plaza is connected to the platform above, not standing as a separate leftover hole.' },
            { label: 'Stepped mass', detail: 'The mound is a huge stack of terraces. It is a public building, not a natural sand dune.' },
            { label: 'Unequal houses', detail: 'Better-built residences cluster nearer the monuments; simpler dwellings lie farther out.' },
          ],
          claimIds: ['claim.caral.plaza-observation', 'claim.caral.monumental-architecture', 'claim.caral.labor-and-hierarchy'],
          sourceIds: ['source.caral.commons-plaza', 'source.caral.unesco-nomination'],
        },
      ],
    },
    {
      id: 'section.caral.how-built',
      heading: 'How the monuments were built',
      purpose: 'Turn monumentality into dated human labor and reject the primitive-without-pottery story',
      modules: [
        {
          id: 'module.caral.shicra-work',
          type: 'prose',
          body: 'Go back to the bags from the start of this lesson. Each one is a shicra, a bag woven from reeds and packed with stones. With no pack animals to help, people hauled stone from the quarries using ropes and fiber bags made for the job, then stacked the filled bags inside retaining walls to build the solid cores of the platform mounds.\n\nThe mounds also grew by burying their own past. Again and again, builders filled old rooms with shicra bags and stones and built new rooms on top, so each mound holds older versions of itself inside. The bags later became the evidence: their fibers survived in the dry climate, and radiocarbon dates from them place Caral’s monumental construction around 2627 to 1977 BCE.\n\nWork on this scale needed planning, food for many workers, and people to direct it. It may also have had music: in the largest sunken plaza in the city, excavators found 32 small bone flutes decorated with cut lines and red and black paint. The instruments survive. The songs do not.\n\nNo pottery did not mean no skill. People here built what they needed from gourds, baskets, fiber, and stone.',
          claimIds: ['claim.caral.shicra', 'claim.caral.human-hauling', 'claim.caral.burial-and-rebuilding', 'claim.caral.caral-dates', 'claim.caral.preceramic', 'claim.caral.labor-and-hierarchy', 'claim.caral.bone-flutes'],
          sourceIds: ['source.caral.shady-haas-creamer-2001', 'source.caral.unesco-nomination', 'source.caral.shady-2006-pucp', 'source.caral.sandweiss-2009'],
        },
        {
          id: 'module.caral.shicra-field-guide',
          type: 'scene',
          title: 'Follow a bag of stones into the wall',
          body: 'Evidence-led reconstruction: the exact crew and moment are illustrative. Open the field guide to see how fiber bags became the dated core of a platform mound.',
          mediaId: 'media.caral.shicra-reconstruction',
          hotspots: [
            { label: 'Woven bags', detail: 'Workers packed rounded river stones into coarse plant-fiber bags called shicra. Those fibers survived in the dry climate and later provided radiocarbon dates.' },
            { label: 'Stacked cores', detail: 'Filled bags were stacked inside stone retaining walls. The photograph of excavated bags supports this fill method; the people shown here are reconstructed.' },
            { label: 'Organized labor', detail: 'Building on this scale required many workers, food, and people who directed work. Their exact titles and powers remain uncertain.' },
          ],
          claimIds: ['claim.caral.shicra', 'claim.caral.caral-dates', 'claim.caral.labor-and-hierarchy'],
          sourceIds: ['source.caral.commons-almacenes-shicras', 'source.caral.shady-haas-creamer-2001', 'source.caral.unesco-nomination'],
        },
        {
          id: 'module.caral.work-not-magic',
          type: 'knowledge',
          eyebrow: 'Who did the work',
          title: 'Public buildings depended on repeated work',
          body: 'Each mound was the work of many people. Their names are gone, but the kinds of work they did can still be traced.',
          items: [
            { label: 'Farmers and irrigators', detail: 'Moved river water onto desert land and grew cotton, gourds, and food plants.' },
            { label: 'Fishers and net makers', detail: 'Turned fiber into nets and sent marine protein inland.' },
            { label: 'Quarry and bag crews', detail: 'Filled shicra bags, hauled stone, and stacked cores inside retaining walls.' },
            { label: 'Organizers', detail: 'Directed labor, food, and ceremony. Their exact titles and powers remain uncertain.' },
          ],
          claimIds: ['claim.caral.labor-and-hierarchy', 'claim.caral.cotton-fish-exchange', 'claim.caral.shicra', 'claim.caral.evidence-bias'],
          sourceIds: ['source.caral.unesco-nomination', 'source.caral.sandweiss-2009', 'source.caral.shady-haas-creamer-2001'],
        },
      ],
    },
    {
      id: 'section.caral.what-it-can-prove',
      heading: 'What this case can prove',
      purpose: 'Qualify oldest-city, state, quipu, and peace stories while keeping the independent urban model',
      modules: [
        {
          id: 'module.caral.limits',
          type: 'prose',
          body: 'Caral is often called the oldest city in the Americas and the capital of a fully formed state. The evidence supports something smaller and still remarkable. Caral was one of many early centers in the region, and some of its neighbors were also early. Archaeologists still disagree about whether Caral ruled them or competed with them as an equal. Either way, urban life in the Andes took shape on its own path, independently of Egypt and Mesopotamia.\n\nThen there is the knotted cord. On the twelfth step of the central stairway of another mound, the Gallery Pyramid, excavators found an offering: a fiber object tied with knots, left with other things linked to the sea and to music. The excavation team reads it as the oldest known quipu, a kind of knotted-cord record that became famous much later in the Andes. Other specialists have not confirmed that identification. The cord is real. What it meant is still open.\n\nNo one has found clear fortifications or battlefield remains from this period, either. That does not prove that life was peaceful or that nobody was forced to work; pressure and violence can leave little behind.\n\nMost of what survives is architecture, plants, fish remains, and offerings, so the buildings speak more clearly than the people who made them. Every bag inside the mounds was filled by someone, and every net was made by someone. The fiber kept its date for more than 4,500 years. It did not keep a single name.',
          claimIds: ['claim.caral.oldest-qualified', 'claim.caral.regional-sites', 'claim.caral.polity-disagreement', 'claim.caral.not-one-recipe', 'claim.caral.quipu-contested', 'claim.caral.quipu-twelfth-step', 'claim.caral.warfare-absence', 'claim.caral.evidence-bias', 'claim.caral.shicra', 'claim.caral.caral-dates', 'claim.caral.cotton-fish-exchange'],
          sourceIds: ['source.caral.unesco-1269', 'source.caral.shady-haas-creamer-2001', 'source.caral.haas-creamer-ruiz-2004', 'source.caral.creamer-haas-2014-peer-polity', 'source.caral.shady-2006-pucp', 'source.caral.haas-creamer-2005-power', 'source.caral.unesco-nomination', 'source.caral.sandweiss-2009'],
        },
        {
          id: 'module.caral.can-cannot',
          type: 'knowledge',
          eyebrow: 'What we can know',
          title: 'What Caral can—and cannot—do',
          body: 'A site can be powerful without answering every question.',
          items: [
            { label: 'It can show', detail: 'That people built large public architecture and linked inland farms with coastal fishing without pottery, metal, or writing.' },
            { label: 'It can support', detail: 'A claim that urban life in the Andes developed on its own path, not as a copy of Egypt or Mesopotamia.' },
            { label: 'It cannot prove alone', detail: 'That Caral was the one first city, the capital of a settled territorial state, or a uniquely peaceful society.' },
            { label: 'It cannot recover', detail: 'The thoughts of ordinary builders, the meaning of every ceremony, or a readable administration from one knotted offering.' },
          ],
          claimIds: ['claim.caral.no-checklist', 'claim.caral.not-one-recipe', 'claim.caral.oldest-qualified', 'claim.caral.quipu-contested', 'claim.caral.warfare-absence'],
          sourceIds: ['source.caral.unesco-1269', 'source.caral.creamer-haas-2014-peer-polity', 'source.caral.shady-2006-pucp', 'source.caral.haas-creamer-2005-power'],
        },
      ],
    },
    {
      id: 'section.caral.world-check',
      heading: 'World Check',
      purpose: 'Require one supported urban model and one explicit evidence limit',
      modules: [
        {
          id: 'module.caral.prompt-model',
          type: 'prompt',
          promptId: 'prompt.caral.supported-model',
          claimIds: [],
          sourceIds: [],
        },
        {
          id: 'module.caral.prompt-limit',
          type: 'prompt',
          promptId: 'prompt.caral.evidence-and-limit',
          claimIds: [],
          sourceIds: [],
        },
      ],
    },
  ],
  claimIds: caralAndeanUrbanismClaims.map((claim) => claim.id),
  sourceIds: caralAndeanUrbanismSources.map((source) => source.id),
  mediaIds: caralAndeanUrbanismMedia.map((media) => media.id),
  promptIds: caralAndeanUrbanismPrompts.map((prompt) => prompt.id),
};

export const caralAndeanUrbanismCards: KnowledgeCard[] = [
  {
    id: 'card.place.caral',
    title: 'Caral',
    category: 'place',
    cardClass: 'foundation',
    date: {
      startYear: -3000,
      endYear: -1800,
      display: 'c. 3000–1800 BCE',
      approximate: true,
    },
    place: 'Supe Valley, north-central coast of Peru',
    significance: 'An inland monumental center that shows urban life can grow from irrigation, coastal–inland exchange, and public architecture without pottery, metal, or writing.',
    revealTitle: 'A city without the usual checklist',
    revealBody: 'You earned this Place card by reading Caral from its mounds, its sunken plaza, and its nets and fish, without crowning it the first city, a peaceful empire, or the home of a decoded quipu.',
    depictionLabel: 'Place-focused · surviving sunken plaza',
    facts: [
      'Sits about 23 kilometers inland on a dry desert terrace above the green Supe Valley',
      'Central zone of about 65 hectares with platform mounds and sunken circular plazas',
      'Built without pottery, metal tools, or a writing system like Egypt’s or Uruk’s',
      'One of several early monumental centers in neighboring valleys, not a proven unique first city',
    ],
    lessonIds: ['lesson.caral.andean-urbanism'],
    sourceIds: ['source.caral.commons-plaza', 'source.caral.shady-haas-creamer-2001', 'source.caral.unesco-1269', 'source.caral.sandweiss-2009'],
    mediaId: 'media.caral.sunken-plaza',
    unlockLessonId: 'lesson.caral.andean-urbanism',
  },
];

export const caralAndeanUrbanismContent: AuthoredContentModule = {
  sources: caralAndeanUrbanismSources,
  claims: caralAndeanUrbanismClaims,
  media: caralAndeanUrbanismMedia,
  prompts: caralAndeanUrbanismPrompts,
  lessons: [caralAndeanUrbanismLesson],
  cards: caralAndeanUrbanismCards,
};
