import type { Claim, KnowledgeCard, Lesson, MediaAsset, Source, UnderstandingPrompt } from '../../src/domains/contracts';
import type { AuthoredContentModule } from '../assemble';
import { mediaLocator } from '../shared/media-locator';

export const earlyWritingSources: Source[] = [
  {
    id: 'source.met.writing-origins',
    title: 'The Origins of Writing',
    url: 'https://www.metmuseum.org/essays/the-origins-of-writing',
    publisher: 'The Metropolitan Museum of Art',
    accessedOn: '2026-07-19',
    licenseOrUse: 'Institutional scholarly reference; article text not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.met.proto-cuneiform-tablet',
    title: 'Proto-Cuneiform Tablet with Seal Impressions, 1988.433.1',
    url: 'https://www.metmuseum.org/art/collection/search/329081',
    publisher: 'The Metropolitan Museum of Art',
    accessedOn: '2026-07-19',
    licenseOrUse: 'Object image explicitly marked Public Domain under The Met Open Access policy; derivatives and redistribution permitted',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.cdli.uruk-iv-tablet',
    title: 'W 20498 (P003801)',
    url: 'https://cdli.earth/P003801',
    publisher: 'Cuneiform Digital Library Initiative',
    accessedOn: '2026-07-19',
    licenseOrUse: 'Specialist corpus record used as research reference; artifact photograph not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.cdli.writing-epistemology',
    title: 'The Origins of Writing as a Problem of Historical Epistemology',
    url: 'https://cdli.earth/articles/cdlj/2006-1',
    publisher: 'Cuneiform Digital Library Initiative',
    accessedOn: '2026-07-19',
    licenseOrUse: 'Open scholarly reference; article text not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.antiquity.seals-signs',
    title: 'Seals and Signs: Tracing the Origins of Writing in Ancient South-west Asia',
    url: 'https://www.cambridge.org/core/journals/antiquity/article/seals-and-signs-tracing-the-origins-of-writing-in-ancient-southwest-asia/B3C2D400F3F80A7A0162D9035C9C2804',
    publisher: 'Antiquity / Cambridge University Press',
    accessedOn: '2026-07-19',
    licenseOrUse: 'CC BY-NC-ND 4.0 scholarly reference; no article media or derivative text redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.isac.visible-language',
    title: 'Visible Language: Inventions of Writing in the Ancient Middle East and Beyond',
    url: 'https://isac.uchicago.edu/research/publications/oimp/oimp-32-visible-language-inventions-writing-ancient-middle-east-and',
    publisher: 'Institute for the Study of Ancient Cultures, University of Chicago',
    accessedOn: '2026-07-19',
    licenseOrUse: 'Institutional edited-volume reference; runtime redistribution not asserted',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.cdli.englund-account-books',
    title: 'Proto-Cuneiform Account-Books and Journals',
    url: 'https://cdli.earth/files-up/publications/englund2004a.pdf',
    publisher: 'Robert K. Englund, in Creating Economic Order (CDL Press, 2004), via Cuneiform Digital Library Initiative',
    accessedOn: '2026-09-24',
    licenseOrUse: 'Specialist scholarly chapter cited as a fact source; text and figures not redistributed',
    reviewStatus: 'reviewed',
  },
];

export const earlyWritingClaims: Claim[] = [
  {
    id: 'claim.writing.coordination-problem',
    statement: 'Late-fourth-millennium institutions used durable administrative devices to organize selected information about goods, quantities, people, and activities.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.met.writing-origins', 'source.antiquity.seals-signs', 'source.cdli.writing-epistemology'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.writing.administrative-evidence',
    statement: 'Surviving late-fourth-millennium tablets preserve numerical and commodity signs used for administration and accounting.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.met.proto-cuneiform-tablet', 'source.cdli.uruk-iv-tablet', 'source.antiquity.seals-signs'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.writing.precursors',
    statement: 'Tokens, sealings, clay envelopes, numerical tablets, and other marks were used before and alongside proto-cuneiform in administrative settings across South-west Asia.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.antiquity.seals-signs', 'source.cdli.writing-epistemology'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.writing.precursor-paths',
    statement: 'Some proto-cuneiform signs may draw on older visual or administrative practices, but most one-to-one paths from a particular token or seal motif to a later sign are not demonstrable.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.antiquity.seals-signs'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.writing.tablet-object',
    statement: 'The Met tablet 1988.433.1 is a small clay object dated about 3100–2900 BCE, probably from Uruk, with incised signs, numerical impressions, and a cylinder-seal impression.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.met.proto-cuneiform-tablet'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.writing.tablet-reading',
    statement: 'The Met interprets tablet 1988.433.1 as a probable grain distribution, but the exact transaction remains uncertain.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.met.proto-cuneiform-tablet'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.writing.restricted-information',
    statement: 'Most surviving proto-cuneiform texts organize restricted administrative information rather than fully encoding the syntax and range of spoken language.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.cdli.writing-epistemology', 'source.antiquity.seals-signs', 'source.isac.visible-language'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.writing.change-over-time',
    statement: 'Over centuries, writing tools, sign forms, conventions, phonetic coding, languages, and text types changed into later cuneiform traditions.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.met.writing-origins', 'source.cdli.writing-epistemology', 'source.isac.visible-language'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.writing.power-access',
    statement: 'Because proto-cuneiform record-making was a specialized institutional practice, control of it may have concentrated access to durable information and decisions; the tablets do not directly identify every reader, writer, or decision-maker.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.cdli.writing-epistemology', 'source.isac.visible-language', 'source.met.writing-origins'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.writing.limits',
    statement: 'The surviving administrative corpus is not a complete record of speech, writing practices, or lived experience in early Mesopotamian communities.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.cdli.writing-epistemology', 'source.antiquity.seals-signs'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.writing.independent-traditions',
    statement: 'Mesopotamian proto-cuneiform was one early writing tradition; writing also developed independently in Egypt, China, and Mesoamerica.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.isac.visible-language'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.writing.tablet-making',
    statement: 'Met tablet 1988.433.1 measures about 5.4 × 6 × 4.1 cm; its signs were drawn in the clay with a pointed implement, circular impressions stand for numbers, and The Met acquired it by purchase in 1988.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.met.proto-cuneiform-tablet'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.writing.tablet-seal-scene',
    statement: 'A cylinder seal was incompletely rolled over both faces and the edges of Met tablet 1988.433.1 before it was inscribed; the impression shows a male figure guiding two dogs on a leash and hunting or herding boars in a reed marsh, and the seal itself apparently has not survived.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.met.proto-cuneiform-tablet'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.writing.temple-grain-no-verbs',
    statement: 'The Met reads tablet 1988.433.1 as most likely documenting grain distributed by a large temple, noting that the absence of verbs in early texts makes them difficult to interpret with certainty.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.met.proto-cuneiform-tablet'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.writing.among-oldest',
    statement: 'Proto-cuneiform is probably the oldest known writing system and the only early one documented by an abundance of original texts.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.cdli.writing-epistemology'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.writing.seal-uses',
    statement: 'Before and alongside proto-cuneiform, seals were pressed on lumps of clay securing containers and doors, rolled over clay balls (bullae) that could carry numerical impressions and enclose tokens, and used on blank or numerical tablets; seals also expressed authority and property.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.antiquity.seals-signs', 'source.cdli.writing-epistemology'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.writing.no-discontinuity',
    statement: 'Damerow argues that tokens, standardized containers and seals developed into proto-cuneiform with virtually no discontinuity.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.cdli.writing-epistemology'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.writing.netted-vessel',
    statement: 'Kelley, Cartolano and Ferrara propose that proto-cuneiform sign ZATU190, a vessel enclosed in a net, echoes a common seal motif, while warning that simple comparisons of shape lack a sound method; the same loops on one Susa seal have been read as strings of dried fruit or as a belt loom.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.antiquity.seals-signs'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.writing.number-values',
    statement: 'In proto-cuneiform, the value of a number sign depended on what was counted: the small circular sign N14 could stand for ten pots of butter oil, a grain measure of about 150 liters of barley, or a field of about 6 hectares.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.cdli.englund-account-books'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.writing.school-lists',
    statement: 'Apart from administrative texts, the surviving proto-cuneiform texts are mainly lexical lists, apparently written as school exercises.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.cdli.writing-epistemology', 'source.cdli.englund-account-books'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.writing.one-off-signs',
    statement: 'The proto-cuneiform corpus of about 6,000 texts and fragments contains more than 1,500 non-numerical signs, more than 500 of them attested only once.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.cdli.writing-epistemology'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.writing.wedges-and-sounds',
    statement: 'Cuneiform, meaning wedge-shaped, was written by pressing a stylus with a wedge-shaped tip into clay; by the Fara period, some 500 years after proto-cuneiform, partial phonetic writing of names and other words had changed the system and its range of use.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.met.proto-cuneiform-tablet', 'source.met.writing-origins', 'source.cdli.writing-epistemology'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.writing.dependent-laborers',
    statement: 'Englund reads the sign combinations qualifying persons named in some proto-cuneiform accounts (MSVO 1, 212–214) as designations of dependent laborers, probably captives taken in violent actions against neighbors.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.cdli.englund-account-books'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.writing.uruk-rubbish',
    statement: 'About 5,000 proto-cuneiform tablets were excavated at Uruk by the German Archaeological Institute between 1928 and 1976, and the earliest known come from the Eanna temple precinct; virtually all came from secondary contexts in rubbish heaps, which makes precise dating difficult.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.isac.visible-language'],
    reviewStatus: 'reviewed',
  },
];

export const earlyWritingMedia: MediaAsset[] = [
  {
    id: 'media.writing.proto-cuneiform-tablet',
    locator: mediaLocator('media.writing.proto-cuneiform-tablet'),
    alt: 'Small clay tablet with incised signs, round numerical impressions, and part of a rolled cylinder-seal image',
    depictionMode: 'evidence',
    depictionLabel: 'Surviving proto-cuneiform tablet — The Met, 1988.433.1, Public Domain',
    rightsLabel: 'Public Domain · The Met Open Access',
    sourceIds: ['source.met.proto-cuneiform-tablet'],
    visualBriefRef: 'docs/research/early-writing-systems.md#media-and-knowledge-card-plan',
    reviewStatus: 'approved',
  },
];

export const earlyWritingPrompts: UnderstandingPrompt[] = [
  {
    id: 'prompt.writing.administration-evidence',
    lessonId: 'lesson.writing.early-systems',
    kind: 'supported-selection',
    question: 'Which surviving evidence best supports the use of proto-cuneiform for administration?',
    explanation: 'A tablet with numbers and signs for goods is direct surviving evidence of record-making. Calling it one exact transaction is a scholarly reading. A modern reconstruction or a much later story is not direct evidence for this early practice.',
    required: true,
    options: [
      { id: 'option.writing.tablet', label: 'A proto-cuneiform tablet combining numbers and signs for goods' },
      { id: 'option.writing.reconstruction', label: 'A modern painting of a scribe at work' },
      { id: 'option.writing.later-story', label: 'A literary story copied many centuries later' },
    ],
  },
  {
    id: 'prompt.writing.possibility-and-limit',
    lessonId: 'lesson.writing.early-systems',
    kind: 'concise-explanation',
    question: 'Explain one thing durable records made possible and one limit of what surviving proto-cuneiform tablets can tell historians.',
    explanation: 'A strong answer links records to a real job, such as counting grain, sharing it out, or checking one account against another long after the moment had passed. Then it names a limit: the Met tablet has no verbs, so it never says who gave or received the grain; many signs are still not understood; and the workers whose rations were counted left no words of their own.',
    required: true,
    minimumResponseLength: 30,
  },
];

export const earlyWritingLesson: Lesson = {
  id: 'lesson.writing.early-systems',
  legacyAliases: ['sumer_writing'],
  status: 'published',
  title: 'From Marks to Proto-Cuneiform',
  masthead: 'c. 3200–2800 BCE',
  place: 'Southern Mesopotamia',
  chronology: {
    startYear: -3200,
    endYear: -2800,
    display: 'c. 3200–2800 BCE',
    approximate: true,
  },
  significance: 'After Uruk’s clay records, ask how people made important information last — and why these tablets were not yet like later written sentences.',
  heroMediaId: 'media.writing.proto-cuneiform-tablet',
  heroLabel: 'Surviving evidence',
  heroCaption: 'The clay, signs, numbers, and seal impression survive. Their probable meaning is a scholarly interpretation.',
  sectionIdsRequired: [
    'section.writing.opening-question',
    'section.writing.coordination-problem',
    'section.writing.before-tablets',
    'section.writing.tablets-as-evidence',
    'section.writing.limits',
    'section.writing.signs-change',
    'section.writing.power-and-access',
    'section.writing.world-check',
  ],
  sections: [
    {
      id: 'section.writing.opening-question',
      heading: 'A clay record of grain',
      purpose: 'Open with the problem of making selected information last',
      modules: [
        {
          id: 'module.writing.opening',
          type: 'prose',
          body: 'About 5,000 years ago, probably in the city of Uruk, someone took a lump of clay about 6 centimeters across and rolled a small cylinder-shaped seal over it. The seal left a tiny scene on both faces and around the edges: a man guiding two dogs on a leash, hunting or herding boars in a reed marsh. Only then did someone draw signs into the clay with a pointed tool and press in round marks that stood for numbers.\n\nThe clay has outlasted everything around it. The seal itself seems not to have survived. The grain the tablet most likely counted, handed out by a large temple, was eaten long ago. Today the tablet sits in the Metropolitan Museum of Art in New York.\n\nIn Uruk you saw a city where grain, animals, cloth and work had to be shared out among many people. This lump of clay was one of the tools for doing it, and it belongs to what is probably the oldest writing system on Earth. It was made for a practical job: keeping track of who got what, after the people in the room had gone home.',
          claimIds: ['claim.writing.tablet-making', 'claim.writing.tablet-seal-scene', 'claim.writing.temple-grain-no-verbs', 'claim.writing.coordination-problem', 'claim.writing.among-oldest'],
          sourceIds: ['source.met.proto-cuneiform-tablet', 'source.met.writing-origins', 'source.antiquity.seals-signs', 'source.cdli.writing-epistemology'],
        },
      ],
    },
    {
      id: 'section.writing.coordination-problem',
      heading: 'When memory is not enough',
      purpose: 'Explain the coordination problem without treating writing as inevitable progress',
      modules: [
        {
          id: 'module.writing.coordination',
          type: 'knowledge',
          eyebrow: 'Administration',
          title: 'Count, identify, and check',
          body: 'A large temple handing out grain faced the same questions again and again: how much came in, how much went out, who received it and whether it all added up. People still talked, gave orders and remembered, and records did not replace any of that. What a mark on clay added was a fixed version of a few details that someone else could pick up later and check.',
          items: [
            { label: 'Count', detail: 'How many animals, jars or measures of grain were involved.' },
            { label: 'Identify', detail: 'Which person, office, place or task the amount belonged to.' },
            { label: 'Check', detail: 'Whether this record matched another one, long after the moment it described had passed.' },
          ],
          claimIds: ['claim.writing.coordination-problem', 'claim.writing.administrative-evidence'],
          sourceIds: ['source.met.writing-origins', 'source.cdli.writing-epistemology'],
        },
      ],
    },
    {
      id: 'section.writing.before-tablets',
      heading: 'Record-keeping before writing',
      purpose: 'Introduce earlier administrative practices and the limits of a simple origin story',
      modules: [
        {
          id: 'module.writing.precursors',
          type: 'knowledge',
          eyebrow: 'Earlier practices',
          title: 'Tokens, seals, and numerical tablets',
          body: 'The seal on the Met tablet was the old part. Across South-west Asia, people were pressing seals into clay before anyone drew signs, and a seal stood for authority or ownership. Writing grew out of this world of clay, counting and sealing with, in one scholar’s words, “virtually no discontinuity.” It did not climb one neat ladder.',
          items: [
            { label: 'Sealings', detail: 'Lumps of clay pressed over jars and doors kept them closed, and the seal image marked the person or office behind them.' },
            { label: 'Tokens and clay balls', detail: 'Small clay shapes stood for counted goods. Some were sealed inside hollow clay balls whose surfaces could carry seal images and number marks.' },
            { label: 'Numerical tablets', detail: 'Flat tablets carried pressed-in numbers and seal images before the full set of proto-cuneiform signs appeared.' },
            { label: 'Uncertain paths', detail: 'A 2025 study noticed that a jar hanging in a net, a common picture on seals, looks much like one early sign. The authors warn that shape alone proves little: the same loops on one seal have been read as strings of dried fruit and as part of a loom.' },
          ],
          claimIds: ['claim.writing.precursors', 'claim.writing.precursor-paths', 'claim.writing.seal-uses', 'claim.writing.no-discontinuity', 'claim.writing.netted-vessel'],
          sourceIds: ['source.antiquity.seals-signs', 'source.cdli.writing-epistemology'],
        },
      ],
    },
    {
      id: 'section.writing.tablets-as-evidence',
      heading: 'The tablet up close',
      purpose: 'Separate close observation from a probable scholarly reading',
      modules: [
        {
          id: 'module.writing.tablet-evidence',
          type: 'evidence',
          title: 'Numbers, signs, and a seal',
          artifactLabel: 'Surviving evidence',
          body: 'Start with what you can see. The upper part of the tablet is divided into boxes. Inside them are signs drawn with a pointed tool, and along the top edge are round holes pressed in for numbers. Lower down, part of the rolled seal scene shows through. The tablet is about 6 centimeters wide and 4 thick: a chunky lump, not a flat page.\n\nThen the harder part. The tablet dates to about 3100–2900 BCE. The Met bought it in 1988, and with no record of where it was dug up, “probably from Uruk” is as close as anyone can get. The Met reads it as grain handed out by a large temple, but the tablet has no verbs. It never says who gave, who received or why. The marks survive; the exact transaction does not.',
          mediaId: 'media.writing.proto-cuneiform-tablet',
          claimIds: ['claim.writing.tablet-object', 'claim.writing.tablet-making', 'claim.writing.tablet-reading', 'claim.writing.temple-grain-no-verbs', 'claim.writing.administrative-evidence'],
          sourceIds: ['source.met.proto-cuneiform-tablet'],
        },
      ],
    },
    {
      id: 'section.writing.limits',
      heading: 'A record is not yet a sentence',
      purpose: 'Distinguish proto-cuneiform’s restricted information from later language-rich writing',
      modules: [
        {
          id: 'module.writing.restricted-information',
          type: 'knowledge',
          eyebrow: 'Proto-cuneiform',
          title: 'Quantities, categories, layout, and limits',
          body: 'Missing verbs are not an accident of this one tablet. Most early tablets are accounts, and they are laid out like accounts: amounts, goods and names placed in boxes, not words in the order anyone would say them. The rest are mostly word lists that trainees seem to have copied as exercises. Hardly any of them reads like speech written down.',
          items: [
            { label: 'Quantities', detail: 'A number’s value depended on what was being counted. The same small round sign could mean ten pots of butter oil, about 150 liters of barley, or a field of about 6 hectares.' },
            { label: 'Categories', detail: 'Other signs named goods, people, offices, institutions, places or activities.' },
            { label: 'Layout', detail: 'Entries and totals were arranged by their position on the clay, not in the order of a spoken sentence.' },
            { label: 'Limits', detail: 'Many signs are still not understood. The people who made the tablets knew the context and left it out; we do not have it.' },
          ],
          claimIds: ['claim.writing.restricted-information', 'claim.writing.number-values', 'claim.writing.school-lists'],
          sourceIds: ['source.cdli.writing-epistemology', 'source.antiquity.seals-signs', 'source.isac.visible-language', 'source.cdli.englund-account-books'],
        },
      ],
    },
    {
      id: 'section.writing.signs-change',
      heading: 'Signs, tools, and uses change',
      purpose: 'Show development toward later cuneiform without inventing a clean finish line',
      modules: [
        {
          id: 'module.writing.change',
          type: 'knowledge',
          eyebrow: 'Over time',
          title: 'Early, changing, and later uses',
          body: 'The early system was still being made up as people went along. Specialists have counted more than 1,500 different signs in the surviving early texts, and more than 500 of them turn up only once. Over the next few centuries the signs, the tools and the jobs writing could do all changed, unevenly and without a single finishing day.',
          items: [
            { label: 'Early', detail: 'Signs drawn with a pointed tool, plus pressed-in numbers, tracked goods and work for institutions.' },
            { label: 'Changing', detail: 'Scribes began pressing a stylus with a wedge-shaped tip into the clay, which is where cuneiform, “wedge-shaped,” gets its name. Some signs came to stand for sounds, so names could be spelled out.' },
            { label: 'Later', detail: 'About 500 years after the first tablets, cuneiform was turning into a system that could follow spoken language. It went on to write several languages, with letters, stories, law, learning and more.' },
          ],
          claimIds: ['claim.writing.change-over-time', 'claim.writing.one-off-signs', 'claim.writing.wedges-and-sounds'],
          sourceIds: ['source.met.writing-origins', 'source.met.proto-cuneiform-tablet', 'source.cdli.writing-epistemology', 'source.isac.visible-language'],
        },
      ],
    },
    {
      id: 'section.writing.power-and-access',
      heading: 'What records show — and leave out',
      purpose: 'Connect durable information with institutional power, archive bias, and wider writing traditions',
      modules: [
        {
          id: 'module.writing.power',
          type: 'prose',
          body: 'A tablet let an office do things memory alone could not. It could share out grain, track who owed work, compare this month’s account with last month’s, and hold on to a decision after the people who made it had moved on. Reading and writing these signs took training, so the people who kept the tablets may also have controlled who could check or challenge them. That is a reasonable reading of the evidence; the tablets themselves do not name every writer or reader.\n\nThey say even less about the people at the other end of the account. In some early accounts, workers are listed by name with signs that one leading specialist reads as “dependent laborers,” probably captives taken in fighting with neighbors. Their names survive. What they thought about their rations does not.\n\nMost of the tablets we have were thrown away. About 5,000 early tablets were dug up at Uruk between 1928 and 1976, and virtually all of them came from ancient rubbish heaps, which is one reason they are so hard to date precisely. They were made for an office, not for us. Mesopotamia was also not the only place where people invented writing: as far as scholars can tell, Egypt, China and Mesoamerica each developed their own. This was one beginning, not the beginning.\n\nThe man with his two dogs is still walking across the Met tablet. The grain is gone, and so is everyone who ate it. The clay kept what the office needed, and almost nothing else.',
          claimIds: ['claim.writing.coordination-problem', 'claim.writing.power-access', 'claim.writing.school-lists', 'claim.writing.dependent-laborers', 'claim.writing.limits', 'claim.writing.uruk-rubbish', 'claim.writing.independent-traditions', 'claim.writing.tablet-seal-scene'],
          sourceIds: ['source.cdli.writing-epistemology', 'source.isac.visible-language', 'source.met.writing-origins', 'source.cdli.englund-account-books', 'source.antiquity.seals-signs', 'source.met.proto-cuneiform-tablet'],
        },
      ],
    },
    {
      id: 'section.writing.world-check',
      heading: 'World Check',
      purpose: 'Use surviving evidence and name what it cannot establish',
      modules: [
        {
          id: 'module.writing.prompt-evidence',
          type: 'prompt',
          promptId: 'prompt.writing.administration-evidence',
          claimIds: [],
          sourceIds: [],
        },
        {
          id: 'module.writing.prompt-limit',
          type: 'prompt',
          promptId: 'prompt.writing.possibility-and-limit',
          claimIds: [],
          sourceIds: [],
        },
      ],
    },
  ],
  claimIds: earlyWritingClaims.map((claim) => claim.id),
  sourceIds: earlyWritingSources.map((source) => source.id),
  mediaIds: ['media.writing.proto-cuneiform-tablet'],
  promptIds: [
    'prompt.writing.administration-evidence',
    'prompt.writing.possibility-and-limit',
  ],
};

export const earlyWritingCards: KnowledgeCard[] = [
  {
    id: 'card.artifact.proto-cuneiform-tablet',
    title: 'Proto-Cuneiform Tablet',
    category: 'artifact',
    cardClass: 'witness',
    date: {
      startYear: -3100,
      endYear: -2900,
      display: 'c. 3100–2900 BCE',
      approximate: true,
    },
    place: 'Southern Mesopotamia, probably Uruk',
    significance: 'A surviving administrative object that preserves numbers, signs, and sealing while reminding us that an object and its probable reading are not the same thing.',
    revealTitle: 'A record that outlived its makers',
    revealBody: 'You earned this Artifact card by using a surviving tablet as evidence while keeping its probable reading separate from what is visible.',
    depictionLabel: 'Artifact-focused · surviving evidence',
    facts: [
      'A small clay tablet dated about 3100–2900 BCE',
      'Probably from Uruk in southern Mesopotamia',
      'Carries signs drawn with a pointed tool, round number marks, and a rolled seal showing a man guiding two dogs among boars in a reed marsh',
      'Probably records a grain distribution, but the exact transaction remains uncertain',
    ],
    lessonIds: ['lesson.writing.early-systems'],
    sourceIds: [
      'source.met.proto-cuneiform-tablet',
      'source.cdli.writing-epistemology',
    ],
    mediaId: 'media.writing.proto-cuneiform-tablet',
    unlockLessonId: 'lesson.writing.early-systems',
  },
];

export const earlyWritingSystemsContent: AuthoredContentModule = {
  sources: earlyWritingSources,
  claims: earlyWritingClaims,
  media: earlyWritingMedia,
  prompts: earlyWritingPrompts,
  lessons: [earlyWritingLesson],
  cards: earlyWritingCards,
};
