import type { Claim, KnowledgeCard, Lesson, MediaAsset, Source, UnderstandingPrompt } from '../../src/domains/contracts';
import type { AuthoredContentModule } from '../assemble';
import { mediaLocator } from '../shared/media-locator';

export const egyptNileStateSources: Source[] = [
  {
    id: 'source.egypt.wengrow-state-formation',
    title: 'The Egyptian Predynastic and State Formation',
    url: 'https://discovery.ucl.ac.uk/id/eprint/1496035/',
    publisher: 'UCL Discovery / Journal of Archaeological Research',
    accessedOn: '2026-08-16',
    licenseOrUse: 'CC BY 4.0 peer-reviewed synthesis cited for research; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.regulski-writing',
    title: 'The Origins and Early Development of Writing in Egypt',
    url: 'https://academic.oup.com/edited-volume/43506/chapter/364131674',
    publisher: 'Oxford Academic',
    accessedOn: '2026-08-16',
    licenseOrUse: 'Specialist handbook chapter cited for research; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.stevenson-palettes',
    title: 'Palettes',
    url: 'https://escholarship.org/content/qt7dh0x2n0/qt7dh0x2n0.pdf',
    publisher: 'UCLA Encyclopedia of Egyptology',
    accessedOn: '2026-08-16',
    licenseOrUse: 'Open-access specialist encyclopedia article cited for research; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.ministry-narmer-palette',
    title: 'Narmer Palette',
    url: 'https://egymonuments.gov.eg/collections/narmer-palette-1/',
    publisher: 'Egyptian Ministry of Tourism and Antiquities',
    accessedOn: '2026-08-16',
    licenseOrUse: 'Official object record cited for facts; ministry image is not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.commons-narmer-palette',
    title: 'Both sides of the Narmer Palette',
    url: 'https://commons.wikimedia.org/wiki/File:Narmer_Palette.jpg',
    publisher: 'Wikimedia Commons',
    accessedOn: '2026-08-16',
    licenseOrUse: 'Public Domain Mark faithful reproduction; candidate runtime evidence image',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.ucl-narmer',
    title: 'Narmer',
    url: 'https://www.ucl.ac.uk/museums-static/digitalegypt/chronology/narmer.html',
    publisher: 'UCL Digital Egypt for Universities',
    accessedOn: '2026-08-16',
    licenseOrUse: 'University museum chronology cited for research; media are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.british-museum-early-egypt',
    title: 'Early Egypt',
    url: 'https://www.britishmuseum.org/collection/galleries/early-egypt',
    publisher: 'British Museum',
    accessedOn: '2026-08-16',
    licenseOrUse: 'Museum synthesis cited for research; gallery media are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.cambridge-nile',
    title: 'The Nile: Mobility and Management',
    url: 'https://doi.org/10.1017/9781108919913',
    publisher: 'Cambridge University Press',
    accessedOn: '2026-08-16',
    licenseOrUse: 'Scholarly environmental synthesis cited for research; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.met-educator',
    title: 'The Art of Ancient Egypt: A Resource for Educators',
    url: 'https://www.metmuseum.org/-/media/files/learn/for-educators/publications-for-educators/the-art-of-ancient-egypt.pdf',
    publisher: 'The Metropolitan Museum of Art',
    accessedOn: '2026-08-16',
    licenseOrUse: 'Museum educator reference cited for research; PDF media are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.hierakonpolis-expedition',
    title: 'Firsts of the First City',
    url: 'https://www.hierakonpolis-online.org/index.php/about-hierakonpolis/firsts-of-the-first-city',
    publisher: 'Hierakonpolis Expedition',
    accessedOn: '2026-08-16',
    licenseOrUse: 'Active excavation-project synthesis cited for research; images are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.unesco-memphis',
    title: 'Memphis and its Necropolis',
    url: 'https://whc.unesco.org/en/list/86/',
    publisher: 'UNESCO World Heritage Centre',
    accessedOn: '2026-08-16',
    licenseOrUse: 'Official heritage and geographic reference; description is CC BY-SA IGO 3.0, maps are reference-only',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.commons-ancient-map',
    title: 'Ancient Egypt main map',
    url: 'https://commons.wikimedia.org/wiki/File:Ancient_Egypt_main_map.png',
    publisher: 'Wikimedia Commons / Jeff Dahl',
    accessedOn: '2026-08-19',
    licenseOrUse: 'CC BY-SA 3.0 raster map used as the geographic composition reference; attribution and share-alike preserved',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.pleiades-abydos',
    title: 'Abydos/Ebot',
    url: 'https://pleiades.stoa.org/places/756512',
    publisher: 'Pleiades, Ancient World Mapping Center / ISAW',
    accessedOn: '2026-08-19',
    licenseOrUse: 'CC BY 3.0 scholarly place record and representative coordinate used for geographic cross-checking',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.ucl-tour-nile',
    title: 'Tour of the Nile',
    url: 'https://www.ucl.ac.uk/3dpetriemuseum/stories/excavation-and-rediscovery/tour-of-the-nile/Tour_of_the_Nile.html',
    publisher: 'UCL Petrie Museum',
    accessedOn: '2026-08-19',
    licenseOrUse: 'University museum reference used to cross-check north-to-south site order; image is not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.met-predynastic-boats',
    title: 'Decorated ware jar depicting two boats',
    url: 'https://www.metmuseum.org/art/collection/search/558187',
    publisher: 'The Metropolitan Museum of Art',
    accessedOn: '2026-08-19',
    licenseOrUse: 'CC0 Open Access image, accession 99.3.2; used as a Predynastic boat and pottery reference for the reconstruction',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.hierakonpolis-tomb-boat',
    title: 'Hierakonpolis Tomb 100 boat',
    url: 'https://commons.wikimedia.org/wiki/File:Hierakonpolis_Tomb_100_Boat.jpg',
    publisher: 'Wikimedia Commons / Frederick William Green and James Edward Quibell',
    accessedOn: '2026-08-19',
    licenseOrUse: 'Public Domain Mark and PD-US-expired; c. 3500–3200 BCE boat image used as a period reference for the reconstruction',
    reviewStatus: 'reviewed',
  },
];

export const egyptNileStateClaims: Claim[] = [
  {
    id: 'claim.egypt.nile-corridor',
    statement: 'The Nile joined a narrow valley, a broad delta, wetlands, and desert-edge settlements into a long corridor for food, movement, and exchange.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.egypt.cambridge-nile', 'source.egypt.british-museum-early-egypt'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.no-river-determinism',
    statement: 'The Nile made connection possible, but a river did not automatically create one state.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.egypt.wengrow-state-formation', 'source.egypt.cambridge-nile'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.long-state-formation',
    statement: 'Egyptian state formation was a long, uneven process of competition, alliance, display, production, and administration, not one invention day.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.egypt.wengrow-state-formation', 'source.egypt.met-educator'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.unified-around-3100',
    statement: 'By about 3100 BCE, evidence supports rule over a politically unified Egypt, although the exact sequence remains debated.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.egypt.british-museum-early-egypt', 'source.egypt.met-educator', 'source.egypt.wengrow-state-formation'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.narmer-attested',
    statement: 'Narmer is known from contemporary inscriptions at multiple sites as well as the famous palette.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.egypt.ucl-narmer', 'source.egypt.ministry-narmer-palette'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.menes-uncertain',
    statement: 'Whether Narmer was the later remembered founder Menes is uncertain.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.egypt.ucl-narmer'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.palette-observations',
    statement: 'The Narmer Palette shows the ruler’s name, different crowns, ordered attendants, defeated people, animal imagery, and scenes of royal violence.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.egypt.ministry-narmer-palette', 'source.egypt.stevenson-palettes', 'source.egypt.commons-narmer-palette'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.palette-royal-claim',
    statement: 'The palette presents force, order, and elite ceremony as parts of legitimate kingship.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.egypt.stevenson-palettes', 'source.egypt.ministry-narmer-palette'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.palette-cannot-prove-unification',
    statement: 'The Narmer Palette cannot by itself prove that one pictured battle unified all Egypt exactly as shown.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.egypt.stevenson-palettes', 'source.egypt.wengrow-state-formation'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.ceremonial-elite-medium',
    statement: 'Late ceremonial palettes were rare, elaborate media tied to emerging kingship and restricted elite contexts.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.egypt.stevenson-palettes'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.early-writing',
    statement: 'By about 3250 BCE, short Egyptian inscriptions on labels and containers recorded names, places, quantities, or goods.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.egypt.regulski-writing', 'source.egypt.british-museum-early-egypt'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.writing-and-rule',
    statement: 'Early writing helped direct goods and administration while also displaying elite ownership and authority.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.egypt.regulski-writing'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.memphis-region',
    statement: 'The Memphis region became a strategic administrative center near the meeting of valley and delta.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.egypt.unesco-memphis', 'source.egypt.met-educator', 'source.egypt.regulski-writing'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.evidence-bias',
    statement: 'Most surviving early records come from elite cemeteries and ceremonies, so they reveal rulers more clearly than farmers, boat crews, craftspeople, and storehouse workers.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.egypt.regulski-writing', 'source.egypt.wengrow-state-formation'],
    reviewStatus: 'reviewed',
  },
];

export const egyptNileStateMedia: MediaAsset[] = [
  {
    id: 'media.egypt.nile-corridor-map',
    locator: mediaLocator('media.egypt.nile-corridor-map'),
    alt: 'North-up illustrated map of the Nile corridor with the Mediterranean and Nile Delta at top, Memphis near the Delta entrance, Abydos farther south, and Nekhen or Hierakonpolis farthest south; Upper Egypt is south and Lower Egypt north',
    depictionMode: 'map',
    depictionLabel: 'Evidence-based historical map · river branches, wetlands, and settlement extents are approximate',
    rightsLabel: 'Chronos original raster map edit · geographic reference by Jeff Dahl, CC BY-SA 3.0',
    sourceIds: ['source.egypt.commons-ancient-map', 'source.egypt.unesco-memphis', 'source.egypt.pleiades-abydos', 'source.egypt.hierakonpolis-expedition', 'source.egypt.ucl-tour-nile'],
    visualBriefRef: 'docs/research/the-nile-and-an-early-egyptian-state-map.md#generated-artwork-lineage',
    reviewStatus: 'approved',
  },
  {
    id: 'media.egypt.narmer-palette',
    locator: mediaLocator('media.egypt.narmer-palette'),
    alt: 'Both faces of the gray-green Narmer Palette shown side by side, including Narmer in the White Crown raising a mace on one face and Narmer in the Red Crown leading a procession on the other',
    depictionMode: 'evidence',
    depictionLabel: 'Surviving evidence · both faces shown together without cropping',
    rightsLabel: 'Public Domain Mark · faithful reproduction of a public-domain two-dimensional work',
    sourceIds: ['source.egypt.commons-narmer-palette', 'source.egypt.ministry-narmer-palette', 'source.egypt.stevenson-palettes'],
    visualBriefRef: 'docs/research/the-nile-and-an-early-egyptian-state.md#image-lifecycle',
    reviewStatus: 'approved',
  },
  {
    id: 'media.egypt.nile-landing-reconstruction',
    locator: mediaLocator('media.egypt.nile-landing-reconstruction'),
    alt: 'Evidence-led reconstruction of workers unloading jars, baskets, and bundles from a Nile boat while others check closures and cords and carry goods into low mudbrick storehouses',
    depictionMode: 'evidence-based-reconstruction',
    depictionLabel: 'Evidence-led reconstruction · the exact people, landing, and moment are illustrative',
    rightsLabel: 'Chronos original reconstruction · boat references from The Met, CC0, and Green and Quibell, Public Domain',
    sourceIds: ['source.egypt.regulski-writing', 'source.egypt.wengrow-state-formation', 'source.egypt.cambridge-nile', 'source.egypt.hierakonpolis-expedition', 'source.egypt.met-predynastic-boats', 'source.egypt.hierakonpolis-tomb-boat'],
    visualBriefRef: 'docs/research/the-nile-and-an-early-egyptian-state.md#image-lifecycle',
    reviewStatus: 'approved',
  },
];

export const egyptNileStatePrompts: UnderstandingPrompt[] = [
  {
    id: 'prompt.egypt.palette-supported-claim',
    lessonId: 'lesson.egypt.nile-state',
    kind: 'supported-selection',
    question: 'Which conclusion is best supported by the Narmer Palette itself?',
    explanation: 'The visible crowns, attendants, defeated figures, scale, and ritual order support a bounded claim about how Narmer’s rule was presented. They do not prove one exact conquest story or tell us what every community thought.',
    required: true,
    options: [
      { id: 'option.egypt.palette-kingship-claim', label: 'Narmer’s image connected kingship with force, order, and rule over different regions.' },
      { id: 'option.egypt.palette-one-battle', label: 'One battle shown on the Palette certainly unified every part of Egypt.' },
      { id: 'option.egypt.palette-everyone-agreed', label: 'Every community accepted Narmer’s rule without resistance.' },
      { id: 'option.egypt.palette-daily-tool', label: 'Farmers used this large carved Palette as an everyday grinding board.' },
    ],
  },
  {
    id: 'prompt.egypt.evidence-and-limit',
    lessonId: 'lesson.egypt.nile-state',
    kind: 'concise-explanation',
    question: 'Choose the Nile corridor, the Narmer Palette, or the early labels. How does that evidence help explain state formation, and what can it not prove by itself?',
    explanation: 'A strong answer makes one supported connection—movement, royal ideology, or administration—then names a limit such as exact motives, one conquest sequence, every worker’s experience, or the first moment a state existed.',
    required: true,
    minimumResponseLength: 30,
  },
];

export const egyptNileStateLesson: Lesson = {
  id: 'lesson.egypt.nile-state',
  legacyAliases: ['hieroglyphs', 'narmer'],
  status: 'published',
  title: 'The Nile and an Early Egyptian State',
  masthead: 'c. 3200–2700 BCE',
  place: 'Nile Valley and Delta, northeastern Africa',
  chronology: {
    startYear: -3200,
    endYear: -2700,
    display: 'c. 3200–2700 BCE',
    approximate: true,
  },
  significance: 'The Nile connected communities, but generations of political competition, labor, administration, writing, and royal claims made an early territorial state.',
  heroMediaId: 'media.egypt.nile-landing-reconstruction',
  heroLabel: 'Evidence-led reconstruction',
  heroCaption: 'A reconstructed Nile landing and storehouse workflow based on archaeological evidence — not a photograph of one known place or moment.',
  sectionIdsRequired: [
    'section.egypt.river-corridor',
    'section.egypt.before-one-king',
    'section.egypt.read-palette',
    'section.egypt.palette-limits',
    'section.egypt.administration',
    'section.egypt.world-check',
  ],
  sections: [
    {
      id: 'section.egypt.river-corridor',
      heading: 'The Nile corridor',
      purpose: 'Establish the Nile’s spatial opportunities while rejecting geographic inevitability',
      modules: [
        {
          id: 'module.egypt.opening-river',
          type: 'prose',
          body: 'Stand beside the Nile near the end of the fourth millennium BCE. Away from the water, desert reaches toward the horizon. Along the river, a narrow green corridor holds fields, settlements, boats, animals, workshops, and landing places. Farther north, the river spreads into a broad, wet delta before reaching the Mediterranean.\n\nThe current flows north, downriver. That is why Upper Egypt is in the south, upriver at higher elevation, while Lower Egypt is in the north. The names can feel upside down on a modern map. To people traveling by boat, the river’s direction made sense.\n\nThis geography created connections. Boats could move people, jars, grain, stone, wood, cattle, messages, and officials over long distances. Floodwater renewed fields, although the river and its channels also shifted. But a connected landscape is not the same thing as a kingdom. The Nile made movement possible. People still had to build—often unequally—the relationships and institutions that turned movement into rule.',
          claimIds: ['claim.egypt.nile-corridor', 'claim.egypt.no-river-determinism'],
          sourceIds: ['source.egypt.cambridge-nile', 'source.egypt.british-museum-early-egypt', 'source.egypt.wengrow-state-formation'],
        },
        {
          id: 'module.egypt.upper-lower',
          type: 'knowledge',
          eyebrow: 'Read the river',
          title: 'Upper is upriver; Lower is downriver',
          body: 'Three relationships keep the geography clear. None of them is a political border drawn with modern precision.',
          items: [
            { label: 'Upper Egypt', detail: 'The long southern valley, upriver and at higher elevation.' },
            { label: 'Lower Egypt', detail: 'The northern delta, downriver where channels fan toward the Mediterranean.' },
            { label: 'The corridor', detail: 'River travel connected many communities without erasing their local histories or automatically placing them under one ruler.' },
          ],
          claimIds: ['claim.egypt.nile-corridor', 'claim.egypt.no-river-determinism'],
          sourceIds: ['source.egypt.cambridge-nile', 'source.egypt.met-educator'],
        },
        {
          id: 'module.egypt.nile-map',
          type: 'historical-map',
          eyebrow: 'Follow the corridor',
          title: 'Three places along one river',
          body: 'Use the map to hold the north–south relationship in view: Nekhen in the southern valley, Abydos farther north, and the Memphis region near the meeting of valley and delta. These positions help explain movement and administration; they do not draw a timeless political border.',
          mediaId: 'media.egypt.nile-corridor-map',
          periodLabel: 'c. 3200–2700 BCE',
          focusPlace: 'Nile Valley and Delta',
          modernContext: 'Northeastern Africa; ancient channels and wetlands changed',
          accessibleSummary: 'A north-oriented map follows the Nile from Upper Egypt in the south through Nekhen and Abydos to the Memphis region and the Nile Delta in Lower Egypt. The river reaches the Mediterranean Sea in the north. No political borders or conquest arrows are shown.',
          compactLabel: 'Broad river relationships · no political borders',
          coordinateNote: 'Memphis is anchored by UNESCO World Heritage coordinates, Abydos by Pleiades, and Nekhen by a broad site position cross-checked against archaeological reference maps.',
          uncertaintyNote: 'River branches, wetlands, shorelines, and settlement extents changed over time; the map preserves broad relative locations rather than reconstructing one exact ancient year.',
          depictionStatus: 'evidence-based-reconstruction',
          introLayout: 'dense',
          claimIds: ['claim.egypt.nile-corridor', 'claim.egypt.no-river-determinism', 'claim.egypt.memphis-region'],
          sourceIds: ['source.egypt.commons-ancient-map', 'source.egypt.pleiades-abydos', 'source.egypt.ucl-tour-nile', 'source.egypt.unesco-memphis', 'source.egypt.hierakonpolis-expedition'],
        },
      ],
    },
    {
      id: 'section.egypt.before-one-king',
      heading: 'Before one king',
      purpose: 'Replace a neat two-kingdom conquest story with a long process of political experimentation',
      modules: [
        {
          id: 'module.egypt.long-process',
          type: 'prose',
          body: 'It is tempting to imagine two complete kingdoms—Upper Egypt and Lower Egypt—waiting on opposite sides of a border until one final battle joined them. Archaeology does not give us that tidy picture.\n\nAcross centuries, communities and regional centers changed in different ways. Places such as Nekhen, also called Hierakonpolis, and Abydos became important in the south. Elites competed through production, exchange, ritual, burial, display, alliances, and violence. Southern material culture spread north, while Delta communities had their own economies, settlements, and connections beyond the Nile. Power grew, shifted, and had to be made real in everyday practices.\n\nBy about 3100 BCE, rulers could claim authority over a politically unified Egypt. That does not mean the state appeared in a day. It means many earlier changes had reached a point where one kingship could organize and represent a territory hundreds of kilometers long—and where later rulers still had to keep that organization working.',
          claimIds: ['claim.egypt.long-state-formation', 'claim.egypt.unified-around-3100'],
          sourceIds: ['source.egypt.wengrow-state-formation', 'source.egypt.met-educator', 'source.egypt.british-museum-early-egypt'],
        },
        {
          id: 'module.egypt.state-formation-process',
          type: 'knowledge',
          eyebrow: 'Not one switch',
          title: 'Several processes became one political system',
          body: 'No single item below created the state. Together, and over time, they changed what powerful institutions could do.',
          items: [
            { label: 'Production and exchange', detail: 'Food, craft goods, stone, animals, and imported materials moved through growing networks.' },
            { label: 'Competition and alliance', detail: 'Regional elites used relationships, ritual, display, and force to expand or defend authority.' },
            { label: 'Administration', detail: 'Labels, sealings, officials, storehouses, and repeated procedures helped institutions direct goods and work.' },
            { label: 'Royal ideology', detail: 'Ceremonies and images presented one ruler as the maker of order and the controller of enemies.' },
          ],
          claimIds: ['claim.egypt.long-state-formation', 'claim.egypt.writing-and-rule', 'claim.egypt.palette-royal-claim'],
          sourceIds: ['source.egypt.wengrow-state-formation', 'source.egypt.regulski-writing', 'source.egypt.stevenson-palettes'],
        },
      ],
    },
    {
      id: 'section.egypt.read-palette',
      heading: 'Read the Narmer Palette',
      purpose: 'Observe both faces of one surviving royal object before interpreting its political message',
      modules: [
        {
          id: 'module.egypt.palette-first-look',
          type: 'prose',
          body: 'A green-gray stone object about 64 centimeters tall survives from around 3100 BCE. It was found in a temple deposit at Nekhen and is now held by the Egyptian Museum in Cairo. Its shape recalls smaller palettes used for grinding pigment, but this one is unusually large, deeply carved, and ceremonial.',
          claimIds: ['claim.egypt.palette-observations', 'claim.egypt.ceremonial-elite-medium', 'claim.egypt.narmer-attested'],
          sourceIds: ['source.egypt.ministry-narmer-palette', 'source.egypt.stevenson-palettes', 'source.egypt.ucl-narmer'],
        },
        {
          id: 'module.egypt.palette-evidence',
          type: 'evidence',
          title: 'Both faces, held together',
          artifactLabel: 'Surviving evidence · both faces',
          body: 'Both faces are shown together and uncropped. Before reading the court’s claim, trace the crowns, attendants, captives, animals, signs, and changes in scale. The carved lines, surface damage, and overall arrangement survive; an exact sequence of events does not.',
          mediaId: 'media.egypt.narmer-palette',
          claimIds: ['claim.egypt.palette-observations', 'claim.egypt.ceremonial-elite-medium'],
          sourceIds: ['source.egypt.commons-narmer-palette', 'source.egypt.ministry-narmer-palette', 'source.egypt.stevenson-palettes'],
        },
        {
          id: 'module.egypt.palette-observations',
          type: 'prose',
          body: 'Before deciding what it means, look. Near the top of both faces, a catfish and chisel write the ruler’s name: Narmer. On one face, the ruler wears the tall White Crown associated with Upper Egypt and raises a mace over a kneeling person. A falcon, captives, attendants, and signs fill the ordered scene.\n\nOn the other face, the ruler wears the Red Crown associated with Lower Egypt and walks in a procession toward defeated bodies. Two long-necked fantastic animals curve around a central hollow. At the bottom, a bull breaks into a fortified enclosure. The ruler is much larger than most other people. These are observations. What they prove comes next.',
          claimIds: ['claim.egypt.palette-observations', 'claim.egypt.narmer-attested', 'claim.egypt.early-writing'],
          sourceIds: ['source.egypt.ministry-narmer-palette', 'source.egypt.stevenson-palettes', 'source.egypt.ucl-narmer', 'source.egypt.regulski-writing'],
        },
        {
          id: 'module.egypt.palette-observe',
          type: 'knowledge',
          eyebrow: 'Observation before interpretation',
          title: 'Four details worth holding onto',
          body: 'An observation names what is visible. An interpretation explains why it may matter.',
          items: [
            { label: 'Two crowns', detail: 'Narmer appears with a different regional crown on each face.' },
            { label: 'Unequal scale', detail: 'The ruler is shown larger than attendants, captives, and defeated people.' },
            { label: 'Ordered violence', detail: 'Processions, standards, rows, and registers organize scenes of domination.' },
            { label: 'Early writing', detail: 'Short signs identify the ruler and some people or places; they do not form a long narrative caption.' },
          ],
          claimIds: ['claim.egypt.palette-observations', 'claim.egypt.early-writing'],
          sourceIds: ['source.egypt.ministry-narmer-palette', 'source.egypt.stevenson-palettes', 'source.egypt.regulski-writing'],
        },
      ],
    },
    {
      id: 'section.egypt.palette-limits',
      heading: 'What the Palette can prove',
      purpose: 'Use the Palette for a bounded interpretation and make its limits explicit',
      modules: [
        {
          id: 'module.egypt.palette-interpretation',
          type: 'prose',
          body: 'The Palette is real evidence from Narmer’s time. It is also an argument. It presents a ruler who controls force, ritual, attendants, regions, and defeated enemies. The crowns make rule over different parts of Egypt part of that message. The careful order of the carving turns violence into a claim about legitimate kingship.\n\nFor a long time, scholars often read the scenes as a direct record of one battle in which Narmer conquered Lower Egypt and unified the country. Today, literal readings are treated more cautiously. Similar royal images can compress repeated conflicts, rituals, ideals, and imagined enemies into one powerful scene. The Palette may refer to events. It does not tell us which parts are a specific event, which are symbols, or how people outside the court experienced the change.\n\nNarmer is attested in contemporary inscriptions at several sites. A much later tradition names Menes as Egypt’s founder. Whether those names refer to the same person remains uncertain. Evidence gets stronger when we preserve that boundary instead of filling it with a heroic biography.',
          claimIds: ['claim.egypt.palette-royal-claim', 'claim.egypt.palette-cannot-prove-unification', 'claim.egypt.narmer-attested', 'claim.egypt.menes-uncertain'],
          sourceIds: ['source.egypt.stevenson-palettes', 'source.egypt.wengrow-state-formation', 'source.egypt.ucl-narmer'],
        },
        {
          id: 'module.egypt.palette-can-cannot',
          type: 'knowledge',
          eyebrow: 'Evidence boundary',
          title: 'What the Palette can—and cannot—do',
          body: 'A source can be powerful without answering every question.',
          items: [
            { label: 'It can show', detail: 'How Narmer’s court connected kingship with crowns, hierarchy, violence, ceremony, and order.' },
            { label: 'It can support', detail: 'A claim that rule over different regions mattered to early royal identity.' },
            { label: 'It cannot prove alone', detail: 'That one battle created the state exactly as pictured, or that every community accepted one ruler in the same way.' },
            { label: 'It cannot recover', detail: 'The thoughts of captives, farmers, craft workers, boat crews, or most people who appear faintly—or not at all—in elite art.' },
          ],
          claimIds: ['claim.egypt.palette-royal-claim', 'claim.egypt.palette-cannot-prove-unification', 'claim.egypt.evidence-bias'],
          sourceIds: ['source.egypt.stevenson-palettes', 'source.egypt.regulski-writing', 'source.egypt.wengrow-state-formation'],
        },
      ],
    },
    {
      id: 'section.egypt.administration',
      heading: 'How administration worked',
      purpose: 'Connect movement, goods, writing, workers, and repeated procedures to durable administration',
      modules: [
        {
          id: 'module.egypt.labels-and-goods',
          type: 'prose',
          body: 'A dramatic image could proclaim authority. Keeping authority working across the Nile corridor required quieter practices repeated every day. Boats arrived with jars, grain, linen, animals, stone, timber, and other goods. Someone unloaded them. Someone checked containers and seals. Someone decided where goods went, who received rations, and what labor was expected.\n\nAt Abydos, tiny ivory and bone labels from about 3250 BCE preserve some of Egypt’s earliest writing. Their signs are brief. They may identify names, places, quantities, goods, or institutions. Some were made in repeated groups and cut apart, evidence of organized production rather than one person doodling. Writing did not begin as long stories for a wide reading public. It helped small groups direct material flows and display elite control.\n\nNear the meeting of valley and delta, the Memphis region became an important administrative center. Later tradition says the first king founded the city, but the exact founder and ancient river setting remain uncertain. The strategic relationship is clearer: from this area, movement between the narrow valley and branching delta could be watched and organized.',
          claimIds: ['claim.egypt.early-writing', 'claim.egypt.writing-and-rule', 'claim.egypt.memphis-region'],
          sourceIds: ['source.egypt.regulski-writing', 'source.egypt.unesco-memphis', 'source.egypt.met-educator'],
        },
        {
          id: 'module.egypt.state-in-practice',
          type: 'knowledge',
          eyebrow: 'A state in practice',
          title: 'Power depended on repeated human work',
          body: 'The ruler was visible on stone. The state became durable through the work of many people, most of whose names are gone.',
          items: [
            { label: 'Boat crews and carriers', detail: 'Moved food, stone, people, and messages along river routes and between landings.' },
            { label: 'Farmers and herders', detail: 'Produced much of the food and livestock that institutions collected, stored, and redistributed.' },
            { label: 'Craft and storehouse workers', detail: 'Made containers, seals, labels, tools, cloth, and prestige goods; checked and protected supplies.' },
            { label: 'Officials and writers', detail: 'Turned selected people, places, goods, and obligations into records that institutions could reuse.' },
          ],
          claimIds: ['claim.egypt.writing-and-rule', 'claim.egypt.evidence-bias', 'claim.egypt.nile-corridor'],
          sourceIds: ['source.egypt.regulski-writing', 'source.egypt.wengrow-state-formation', 'source.egypt.cambridge-nile', 'source.egypt.hierakonpolis-expedition'],
        },
        {
          id: 'module.egypt.nile-landing-field-guide',
          type: 'scene',
          title: 'Follow the goods from boat to storehouse',
          body: 'Evidence-led reconstruction: the exact people, landing, and moment are illustrative. Open the field guide to trace the repeated work that could turn river movement into institutional control.',
          mediaId: 'media.egypt.nile-landing-reconstruction',
          hotspots: [
            { label: 'River transport', detail: 'Boat crews and carriers moved containers, food, materials, people, and messages along the Nile corridor.' },
            { label: 'Checks, seals, and cords', detail: 'Workers could inspect closures, seals, tags, and containers. The scene shows the physical workflow without claiming exact marks or one documented landing.' },
            { label: 'Storage and redistribution', detail: 'Mudbrick storehouses made collection visible, but keeping goods useful required repeated decisions about access, protection, rations, and destinations.' },
          ],
          claimIds: ['claim.egypt.writing-and-rule', 'claim.egypt.evidence-bias', 'claim.egypt.nile-corridor'],
          sourceIds: ['source.egypt.regulski-writing', 'source.egypt.met-predynastic-boats', 'source.egypt.hierakonpolis-tomb-boat', 'source.egypt.hierakonpolis-expedition'],
        },
      ],
    },
    {
      id: 'section.egypt.world-check',
      heading: 'World Check',
      purpose: 'Require one bounded claim from evidence and one explicit limit',
      modules: [
        {
          id: 'module.egypt.prompt-palette',
          type: 'prompt',
          promptId: 'prompt.egypt.palette-supported-claim',
          claimIds: [],
          sourceIds: [],
        },
        {
          id: 'module.egypt.prompt-limit',
          type: 'prompt',
          promptId: 'prompt.egypt.evidence-and-limit',
          claimIds: [],
          sourceIds: [],
        },
      ],
    },
  ],
  claimIds: egyptNileStateClaims.map((claim) => claim.id),
  sourceIds: egyptNileStateSources.map((source) => source.id),
  mediaIds: egyptNileStateMedia.map((media) => media.id),
  promptIds: egyptNileStatePrompts.map((prompt) => prompt.id),
};

export const egyptNileStateCards: KnowledgeCard[] = [
  {
    id: 'card.artifact.narmer-palette',
    title: 'Narmer Palette',
    category: 'artifact',
    cardClass: 'witness',
    date: {
      startYear: -3100,
      endYear: -3000,
      display: 'c. 3100 BCE',
      approximate: true,
    },
    place: 'Nekhen (Hierakonpolis), Upper Egypt',
    significance: 'A carved royal claim that reveals how early kingship wanted to be seen without recording the whole path to power.',
    revealTitle: 'A royal claim, read with limits',
    revealBody: 'You earned this Artifact card by using both faces of the Palette as evidence while refusing to treat one court image as a complete conquest record.',
    depictionLabel: 'Artifact-focused · surviving evidence',
    facts: [
      'A ceremonial gray-green stone palette about 64 centimeters tall',
      'Found in a temple deposit at Nekhen and now held by the Egyptian Museum in Cairo',
      'Shows Narmer with different regional crowns, attendants, captives, fantastic animals, and royal violence',
      'Can support claims about royal ideology but cannot prove one battle unified all Egypt exactly as shown',
    ],
    lessonIds: ['lesson.egypt.nile-state'],
    sourceIds: ['source.egypt.commons-narmer-palette', 'source.egypt.ministry-narmer-palette', 'source.egypt.stevenson-palettes'],
    mediaId: 'media.egypt.narmer-palette',
    unlockLessonId: 'lesson.egypt.nile-state',
  },
];

export const egyptNileStateContent: AuthoredContentModule = {
  sources: egyptNileStateSources,
  claims: egyptNileStateClaims,
  media: egyptNileStateMedia,
  prompts: egyptNileStatePrompts,
  lessons: [egyptNileStateLesson],
  cards: egyptNileStateCards,
};
