import type { Claim, Lesson, Source, UnderstandingPrompt } from '../../src/domains/contracts';
import type { AuthoredContentModule } from '../assemble';

export const egyptNileStateSources: Source[] = [
  {
    id: 'source.egypt.wengrow-state-formation',
    title: 'The Egyptian Predynastic and State Formation',
    url: 'https://discovery.ucl.ac.uk/id/eprint/1496035/',
    publisher: 'UCL Discovery / Journal of Archaeological Research',
    accessedOn: '2026-08-16',
    licenseOrUse: 'CC BY 4.0 peer-reviewed synthesis cited for research; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.regulski-writing',
    title: 'The Origins and Early Development of Writing in Egypt',
    url: 'https://academic.oup.com/edited-volume/43506/chapter/364131674',
    publisher: 'Oxford Academic',
    accessedOn: '2026-08-16',
    licenseOrUse: 'Specialist handbook chapter cited for research; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.stevenson-palettes',
    title: 'Palettes',
    url: 'https://escholarship.org/content/qt7dh0x2n0/qt7dh0x2n0.pdf',
    publisher: 'UCLA Encyclopedia of Egyptology',
    accessedOn: '2026-08-16',
    licenseOrUse: 'Open-access specialist encyclopedia article cited for research; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.ministry-narmer-palette',
    title: 'Narmer Palette',
    url: 'https://egymonuments.gov.eg/collections/narmer-palette-1/',
    publisher: 'Egyptian Ministry of Tourism and Antiquities',
    accessedOn: '2026-08-16',
    licenseOrUse: 'Official object record cited for facts; ministry image is not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.commons-narmer-palette',
    title: 'Both sides of the Narmer Palette',
    url: 'https://commons.wikimedia.org/wiki/File:Narmer_Palette.jpg',
    publisher: 'Wikimedia Commons',
    accessedOn: '2026-08-16',
    licenseOrUse: 'Public Domain Mark faithful reproduction; candidate runtime evidence image',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.ucl-narmer',
    title: 'Narmer',
    url: 'https://www.ucl.ac.uk/museums-static/digitalegypt/chronology/narmer.html',
    publisher: 'UCL Digital Egypt for Universities',
    accessedOn: '2026-08-16',
    licenseOrUse: 'University museum chronology cited for research; media are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.british-museum-early-egypt',
    title: 'Early Egypt',
    url: 'https://www.britishmuseum.org/collection/galleries/early-egypt',
    publisher: 'British Museum',
    accessedOn: '2026-08-16',
    licenseOrUse: 'Museum synthesis cited for research; gallery media are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.cambridge-nile',
    title: 'The Nile: Mobility and Management',
    url: 'https://doi.org/10.1017/9781108919913',
    publisher: 'Cambridge University Press',
    accessedOn: '2026-08-16',
    licenseOrUse: 'Scholarly environmental synthesis cited for research; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.met-educator',
    title: 'The Art of Ancient Egypt: A Resource for Educators',
    url: 'https://www.metmuseum.org/-/media/files/learn/for-educators/publications-for-educators/the-art-of-ancient-egypt.pdf',
    publisher: 'The Metropolitan Museum of Art',
    accessedOn: '2026-08-16',
    licenseOrUse: 'Museum educator reference cited for research; PDF media are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.hierakonpolis-expedition',
    title: 'Firsts of the First City',
    url: 'https://www.hierakonpolis-online.org/index.php/about-hierakonpolis/firsts-of-the-first-city',
    publisher: 'Hierakonpolis Expedition',
    accessedOn: '2026-08-16',
    licenseOrUse: 'Active excavation-project synthesis cited for research; images are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.unesco-memphis',
    title: 'Memphis and its Necropolis',
    url: 'https://whc.unesco.org/en/list/86/',
    publisher: 'UNESCO World Heritage Centre',
    accessedOn: '2026-08-16',
    licenseOrUse: 'Official heritage and geographic reference; description is CC BY-SA IGO 3.0, maps are reference-only',
    reviewStatus: 'reviewed',
  },
];

export const egyptNileStateClaims: Claim[] = [
  {
    id: 'claim.egypt.nile-corridor',
    statement: 'The Nile joined a narrow valley, a broad delta, wetlands, and desert-edge settlements into a long corridor for food, movement, and exchange.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.egypt.cambridge-nile', 'source.egypt.british-museum-early-egypt'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.no-river-determinism',
    statement: 'The Nile made connection possible, but a river did not automatically create one state.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.egypt.wengrow-state-formation', 'source.egypt.cambridge-nile'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.long-state-formation',
    statement: 'Egyptian state formation was a long, uneven process of competition, alliance, display, production, and administration, not one invention day.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.egypt.wengrow-state-formation', 'source.egypt.met-educator'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.unified-around-3100',
    statement: 'By about 3100 BCE, evidence supports rule over a politically unified Egypt, although the exact sequence remains debated.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.egypt.british-museum-early-egypt', 'source.egypt.met-educator', 'source.egypt.wengrow-state-formation'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.narmer-attested',
    statement: 'Narmer is known from contemporary inscriptions at multiple sites as well as the famous palette.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.egypt.ucl-narmer', 'source.egypt.ministry-narmer-palette'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.menes-uncertain',
    statement: 'Whether Narmer was the later remembered founder Menes is uncertain.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.egypt.ucl-narmer'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.palette-observations',
    statement: 'The Narmer Palette shows the ruler’s name, different crowns, ordered attendants, defeated people, animal imagery, and scenes of royal violence.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.egypt.ministry-narmer-palette', 'source.egypt.stevenson-palettes', 'source.egypt.commons-narmer-palette'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.palette-royal-claim',
    statement: 'The palette presents force, order, and elite ceremony as parts of legitimate kingship.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.egypt.stevenson-palettes', 'source.egypt.ministry-narmer-palette'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.palette-not-camera',
    statement: 'The Narmer Palette cannot by itself prove that one pictured battle unified all Egypt exactly as shown.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.egypt.stevenson-palettes', 'source.egypt.wengrow-state-formation'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.ceremonial-elite-medium',
    statement: 'Late ceremonial palettes were rare, elaborate media tied to emerging kingship and restricted elite contexts.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.egypt.stevenson-palettes'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.early-writing',
    statement: 'By about 3250 BCE, short Egyptian inscriptions on labels and containers recorded names, places, quantities, or goods.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.egypt.regulski-writing', 'source.egypt.british-museum-early-egypt'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.writing-and-rule',
    statement: 'Early writing helped direct goods and administration while also displaying elite ownership and authority.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.egypt.regulski-writing'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.memphis-region',
    statement: 'The Memphis region became a strategic administrative center near the meeting of valley and delta.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.egypt.unesco-memphis', 'source.egypt.met-educator', 'source.egypt.regulski-writing'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.evidence-bias',
    statement: 'Most surviving early records come from elite cemeteries and ceremonies, so they reveal rulers more clearly than farmers, boat crews, craftspeople, and storehouse workers.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.egypt.regulski-writing', 'source.egypt.wengrow-state-formation'],
    reviewStatus: 'reviewed',
  },
];

export const egyptNileStatePrompts: UnderstandingPrompt[] = [
  {
    id: 'prompt.egypt.palette-supported-claim',
    lessonId: 'lesson.egypt.nile-state',
    kind: 'supported-selection',
    question: 'Which conclusion is best supported by the Narmer Palette itself?',
    explanation: 'The visible crowns, attendants, defeated figures, scale, and ritual order support a bounded claim about how Narmer’s rule was presented. They do not prove one exact conquest story or tell us what every community thought.',
    required: true,
    options: [
      { id: 'option.egypt.palette-kingship-claim', label: 'Narmer’s image connected kingship with force, order, and rule over different regions.' },
      { id: 'option.egypt.palette-one-battle', label: 'One battle shown on the Palette certainly unified every part of Egypt.' },
      { id: 'option.egypt.palette-everyone-agreed', label: 'Every community accepted Narmer’s rule without resistance.' },
      { id: 'option.egypt.palette-daily-tool', label: 'Farmers used this large carved Palette as an everyday grinding board.' },
    ],
  },
  {
    id: 'prompt.egypt.evidence-and-limit',
    lessonId: 'lesson.egypt.nile-state',
    kind: 'concise-explanation',
    question: 'Choose the Nile corridor, the Narmer Palette, or the early labels. How does that evidence help explain state formation, and what can it not prove by itself?',
    explanation: 'A strong answer makes one supported connection—movement, royal ideology, or administration—then names a limit such as exact motives, one conquest sequence, every worker’s experience, or the first moment a state existed.',
    required: true,
    minimumResponseLength: 30,
  },
];

export const egyptNileStateLesson: Lesson = {
  id: 'lesson.egypt.nile-state',
  legacyAliases: ['hieroglyphs', 'narmer'],
  status: 'draft',
  title: 'The Nile and an Early Egyptian State',
  masthead: 'c. 3200–2700 BCE',
  place: 'Nile Valley and Delta, northeastern Africa',
  chronology: {
    startYear: -3200,
    endYear: -2700,
    display: 'c. 3200–2700 BCE',
    approximate: true,
  },
  significance: 'The Nile connected communities, but generations of political competition, labor, administration, writing, and royal claims made an early territorial state.',
  sectionIdsRequired: [
    'section.egypt.river-corridor',
    'section.egypt.before-one-king',
    'section.egypt.read-palette',
    'section.egypt.claim-not-camera',
    'section.egypt.making-rule-travel',
    'section.egypt.world-check',
  ],
  sections: [
    {
      id: 'section.egypt.river-corridor',
      heading: 'A kingdom shaped like a river?',
      purpose: 'Establish the Nile’s spatial opportunities while rejecting geographic inevitability',
      modules: [
        {
          id: 'module.egypt.opening-river',
          type: 'prose',
          body: 'Stand beside the Nile near the end of the fourth millennium BCE. Away from the water, desert reaches toward the horizon. Along the river, a narrow green corridor holds fields, settlements, boats, animals, workshops, and landing places. Farther north, the river spreads into a broad, wet delta before reaching the Mediterranean.\n\nThe current flows north, downriver. That is why Upper Egypt is in the south, upriver at higher elevation, while Lower Egypt is in the north. The names can feel upside down on a modern map. To people traveling by boat, the river’s direction made sense.\n\nThis geography created connections. Boats could move people, jars, grain, stone, wood, cattle, messages, and officials over long distances. Floodwater renewed fields, although the river and its channels also shifted. But a connected landscape is not the same thing as a kingdom. The Nile made movement possible. People still had to build—often unequally—the relationships and institutions that turned movement into rule.',
          claimIds: ['claim.egypt.nile-corridor', 'claim.egypt.no-river-determinism'],
          sourceIds: ['source.egypt.cambridge-nile', 'source.egypt.british-museum-early-egypt', 'source.egypt.wengrow-state-formation'],
        },
        {
          id: 'module.egypt.upper-lower',
          type: 'knowledge',
          eyebrow: 'Read the river',
          title: 'Upper is upriver; Lower is downriver',
          body: 'Three relationships keep the geography clear. None of them is a political border drawn with modern precision.',
          items: [
            { label: 'Upper Egypt', detail: 'The long southern valley, upriver and at higher elevation.' },
            { label: 'Lower Egypt', detail: 'The northern delta, downriver where channels fan toward the Mediterranean.' },
            { label: 'The corridor', detail: 'River travel connected many communities without erasing their local histories or automatically placing them under one ruler.' },
          ],
          claimIds: ['claim.egypt.nile-corridor', 'claim.egypt.no-river-determinism'],
          sourceIds: ['source.egypt.cambridge-nile', 'source.egypt.met-educator'],
        },
      ],
    },
    {
      id: 'section.egypt.before-one-king',
      heading: 'Before one king',
      purpose: 'Replace a neat two-kingdom conquest story with a long process of political experimentation',
      modules: [
        {
          id: 'module.egypt.long-process',
          type: 'prose',
          body: 'It is tempting to imagine two complete kingdoms—Upper Egypt and Lower Egypt—waiting on opposite sides of a border until one final battle joined them. Archaeology does not give us that tidy picture.\n\nAcross centuries, communities and regional centers changed in different ways. Places such as Nekhen, also called Hierakonpolis, and Abydos became important in the south. Elites competed through production, exchange, ritual, burial, display, alliances, and violence. Southern material culture spread north, while Delta communities had their own economies, settlements, and connections beyond the Nile. Power grew, shifted, and had to be made real in everyday practices.\n\nBy about 3100 BCE, rulers could claim authority over a politically unified Egypt. That does not mean the state appeared in a day. It means many earlier changes had reached a point where one kingship could organize and represent a territory hundreds of kilometers long—and where later rulers still had to keep that organization working.',
          claimIds: ['claim.egypt.long-state-formation', 'claim.egypt.unified-around-3100'],
          sourceIds: ['source.egypt.wengrow-state-formation', 'source.egypt.met-educator', 'source.egypt.british-museum-early-egypt'],
        },
        {
          id: 'module.egypt.state-formation-process',
          type: 'knowledge',
          eyebrow: 'Not one switch',
          title: 'Several processes became one political system',
          body: 'No single item below created the state. Together, and over time, they changed what powerful institutions could do.',
          items: [
            { label: 'Production and exchange', detail: 'Food, craft goods, stone, animals, and imported materials moved through growing networks.' },
            { label: 'Competition and alliance', detail: 'Regional elites used relationships, ritual, display, and force to expand or defend authority.' },
            { label: 'Administration', detail: 'Labels, sealings, officials, storehouses, and repeated procedures helped institutions direct goods and work.' },
            { label: 'Royal ideology', detail: 'Ceremonies and images presented one ruler as the maker of order and the controller of enemies.' },
          ],
          claimIds: ['claim.egypt.long-state-formation', 'claim.egypt.writing-and-rule', 'claim.egypt.palette-royal-claim'],
          sourceIds: ['source.egypt.wengrow-state-formation', 'source.egypt.regulski-writing', 'source.egypt.stevenson-palettes'],
        },
      ],
    },
    {
      id: 'section.egypt.read-palette',
      heading: 'Read the Narmer Palette',
      purpose: 'Observe both faces of one surviving royal object before interpreting its political message',
      modules: [
        {
          id: 'module.egypt.palette-first-look',
          type: 'prose',
          body: 'A green-gray stone object about 64 centimeters tall survives from around 3100 BCE. It was found in a temple deposit at Nekhen and is now held by the Egyptian Museum in Cairo. Its shape recalls smaller palettes used for grinding pigment, but this one is unusually large, deeply carved, and ceremonial.\n\nBefore deciding what it means, look. Near the top of both faces, a catfish and chisel write the ruler’s name: Narmer. On one face, the ruler wears the tall White Crown associated with Upper Egypt and raises a mace over a kneeling person. A falcon, captives, attendants, and signs fill the ordered scene.\n\nOn the other face, the ruler wears the Red Crown associated with Lower Egypt and walks in a procession toward defeated bodies. Two long-necked fantastic animals curve around a central hollow. At the bottom, a bull breaks into a fortified enclosure. The ruler is much larger than most other people. These are observations. What they prove comes next.',
          claimIds: ['claim.egypt.palette-observations', 'claim.egypt.ceremonial-elite-medium', 'claim.egypt.narmer-attested'],
          sourceIds: ['source.egypt.ministry-narmer-palette', 'source.egypt.stevenson-palettes', 'source.egypt.ucl-narmer'],
        },
        {
          id: 'module.egypt.palette-observe',
          type: 'knowledge',
          eyebrow: 'Observation before interpretation',
          title: 'Four details worth holding onto',
          body: 'An observation names what is visible. An interpretation explains why it may matter.',
          items: [
            { label: 'Two crowns', detail: 'Narmer appears with a different regional crown on each face.' },
            { label: 'Unequal scale', detail: 'The ruler is shown larger than attendants, captives, and defeated people.' },
            { label: 'Ordered violence', detail: 'Processions, standards, rows, and registers organize scenes of domination.' },
            { label: 'Early writing', detail: 'Short signs identify the ruler and some people or places; they do not form a long narrative caption.' },
          ],
          claimIds: ['claim.egypt.palette-observations', 'claim.egypt.early-writing'],
          sourceIds: ['source.egypt.ministry-narmer-palette', 'source.egypt.stevenson-palettes', 'source.egypt.regulski-writing'],
        },
      ],
    },
    {
      id: 'section.egypt.claim-not-camera',
      heading: 'A ruler’s claim is not a camera',
      purpose: 'Use the Palette for a bounded interpretation and make its limits explicit',
      modules: [
        {
          id: 'module.egypt.palette-interpretation',
          type: 'prose',
          body: 'The Palette is real evidence from Narmer’s time. It is also an argument. It presents a ruler who controls force, ritual, attendants, regions, and defeated enemies. The crowns make rule over different parts of Egypt part of that message. The careful order of the carving turns violence into a claim about legitimate kingship.\n\nFor a long time, scholars often read the scenes as a direct record of one battle in which Narmer conquered Lower Egypt and unified the country. Today, literal readings are treated more cautiously. Similar royal images can compress repeated conflicts, rituals, ideals, and imagined enemies into one powerful scene. The Palette may refer to events. It does not tell us which parts are a specific event, which are symbols, or how people outside the court experienced the change.\n\nNarmer is attested in contemporary inscriptions at several sites. A much later tradition names Menes as Egypt’s founder. Whether those names refer to the same person remains uncertain. Evidence gets stronger when we preserve that boundary instead of filling it with a heroic biography.',
          claimIds: ['claim.egypt.palette-royal-claim', 'claim.egypt.palette-not-camera', 'claim.egypt.narmer-attested', 'claim.egypt.menes-uncertain'],
          sourceIds: ['source.egypt.stevenson-palettes', 'source.egypt.wengrow-state-formation', 'source.egypt.ucl-narmer'],
        },
        {
          id: 'module.egypt.palette-can-cannot',
          type: 'knowledge',
          eyebrow: 'Evidence boundary',
          title: 'What the Palette can—and cannot—do',
          body: 'A source can be powerful without answering every question.',
          items: [
            { label: 'It can show', detail: 'How Narmer’s court connected kingship with crowns, hierarchy, violence, ceremony, and order.' },
            { label: 'It can support', detail: 'A claim that rule over different regions mattered to early royal identity.' },
            { label: 'It cannot prove alone', detail: 'That one battle created the state exactly as pictured, or that every community accepted one ruler in the same way.' },
            { label: 'It cannot recover', detail: 'The thoughts of captives, farmers, craft workers, boat crews, or most people who appear faintly—or not at all—in elite art.' },
          ],
          claimIds: ['claim.egypt.palette-royal-claim', 'claim.egypt.palette-not-camera', 'claim.egypt.evidence-bias'],
          sourceIds: ['source.egypt.stevenson-palettes', 'source.egypt.regulski-writing', 'source.egypt.wengrow-state-formation'],
        },
      ],
    },
    {
      id: 'section.egypt.making-rule-travel',
      heading: 'Making rule travel',
      purpose: 'Connect movement, goods, writing, workers, and repeated procedures to durable administration',
      modules: [
        {
          id: 'module.egypt.labels-and-goods',
          type: 'prose',
          body: 'A dramatic image could proclaim authority. Keeping authority working across the Nile corridor required quieter practices repeated every day. Boats arrived with jars, grain, linen, animals, stone, timber, and other goods. Someone unloaded them. Someone checked containers and seals. Someone decided where goods went, who received rations, and what labor was expected.\n\nAt Abydos, tiny ivory and bone labels from about 3250 BCE preserve some of Egypt’s earliest writing. Their signs are brief. They may identify names, places, quantities, goods, or institutions. Some were made in repeated groups and cut apart, evidence of organized production rather than one person doodling. Writing did not begin as long stories for a wide reading public. It helped small groups direct material flows and display elite control.\n\nNear the meeting of valley and delta, the Memphis region became an important administrative center. Later tradition says the first king founded the city, but the exact founder and ancient river setting remain uncertain. The strategic relationship is clearer: from this area, movement between the narrow valley and branching delta could be watched and organized.',
          claimIds: ['claim.egypt.early-writing', 'claim.egypt.writing-and-rule', 'claim.egypt.memphis-region'],
          sourceIds: ['source.egypt.regulski-writing', 'source.egypt.unesco-memphis', 'source.egypt.met-educator'],
        },
        {
          id: 'module.egypt.state-in-practice',
          type: 'knowledge',
          eyebrow: 'A state in practice',
          title: 'Power depended on repeated human work',
          body: 'The ruler was visible on stone. The state became durable through the work of many people, most of whose names are gone.',
          items: [
            { label: 'Boat crews and carriers', detail: 'Moved food, stone, people, and messages along river routes and between landings.' },
            { label: 'Farmers and herders', detail: 'Produced much of the food and livestock that institutions collected, stored, and redistributed.' },
            { label: 'Craft and storehouse workers', detail: 'Made containers, seals, labels, tools, cloth, and prestige goods; checked and protected supplies.' },
            { label: 'Officials and writers', detail: 'Turned selected people, places, goods, and obligations into records that institutions could reuse.' },
          ],
          claimIds: ['claim.egypt.writing-and-rule', 'claim.egypt.evidence-bias', 'claim.egypt.nile-corridor'],
          sourceIds: ['source.egypt.regulski-writing', 'source.egypt.wengrow-state-formation', 'source.egypt.cambridge-nile', 'source.egypt.hierakonpolis-expedition'],
        },
      ],
    },
    {
      id: 'section.egypt.world-check',
      heading: 'World Check',
      purpose: 'Require one bounded claim from evidence and one explicit limit',
      modules: [
        {
          id: 'module.egypt.prompt-palette',
          type: 'prompt',
          promptId: 'prompt.egypt.palette-supported-claim',
          claimIds: [],
          sourceIds: [],
        },
        {
          id: 'module.egypt.prompt-limit',
          type: 'prompt',
          promptId: 'prompt.egypt.evidence-and-limit',
          claimIds: [],
          sourceIds: [],
        },
      ],
    },
  ],
  claimIds: egyptNileStateClaims.map((claim) => claim.id),
  sourceIds: egyptNileStateSources.map((source) => source.id),
  mediaIds: [],
  promptIds: egyptNileStatePrompts.map((prompt) => prompt.id),
};

export const egyptNileStateContent: AuthoredContentModule = {
  sources: egyptNileStateSources,
  claims: egyptNileStateClaims,
  prompts: egyptNileStatePrompts,
  lessons: [egyptNileStateLesson],
};
