import type { Claim, KnowledgeCard, Lesson, MediaAsset, Source, UnderstandingPrompt } from '../../src/domains/contracts';
import type { AuthoredContentModule } from '../assemble';
import { mediaLocator } from '../shared/media-locator';

export const egyptNileStateSources: Source[] = [
  {
    id: 'source.egypt.wengrow-state-formation',
    title: 'The Egyptian Predynastic and State Formation',
    url: 'https://discovery.ucl.ac.uk/id/eprint/1496035/',
    publisher: 'UCL Discovery / Journal of Archaeological Research',
    accessedOn: '2026-08-16',
    licenseOrUse: 'CC BY 4.0 peer-reviewed synthesis cited for research; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.regulski-writing',
    title: 'The Origins and Early Development of Writing in Egypt',
    url: 'https://academic.oup.com/edited-volume/43506/chapter/364131674',
    publisher: 'Oxford Academic',
    accessedOn: '2026-08-16',
    licenseOrUse: 'Specialist handbook chapter cited for research; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.stevenson-palettes',
    title: 'Palettes',
    url: 'https://escholarship.org/content/qt7dh0x2n0/qt7dh0x2n0.pdf',
    publisher: 'UCLA Encyclopedia of Egyptology',
    accessedOn: '2026-08-16',
    licenseOrUse: 'Open-access specialist encyclopedia article cited for research; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.ministry-narmer-palette',
    title: 'Narmer Palette',
    url: 'https://egymonuments.gov.eg/collections/narmer-palette-1/',
    publisher: 'Egyptian Ministry of Tourism and Antiquities',
    accessedOn: '2026-08-16',
    licenseOrUse: 'Official object record cited for facts; ministry image is not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.commons-narmer-palette',
    title: 'Both sides of the Narmer Palette',
    url: 'https://commons.wikimedia.org/wiki/File:Narmer_Palette.jpg',
    publisher: 'Wikimedia Commons',
    accessedOn: '2026-08-16',
    licenseOrUse: 'Public Domain Mark faithful reproduction; candidate runtime evidence image',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.ucl-narmer',
    title: 'Narmer',
    url: 'https://www.ucl.ac.uk/museums-static/digitalegypt/chronology/narmer.html',
    publisher: 'UCL Digital Egypt for Universities',
    accessedOn: '2026-08-16',
    licenseOrUse: 'University museum chronology cited for research; media are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.british-museum-early-egypt',
    title: 'Early Egypt',
    url: 'https://www.britishmuseum.org/collection/galleries/early-egypt',
    publisher: 'British Museum',
    accessedOn: '2026-08-16',
    licenseOrUse: 'Museum synthesis cited for research; gallery media are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.cambridge-nile',
    title: 'The Nile: Mobility and Management',
    url: 'https://doi.org/10.1017/9781108919913',
    publisher: 'Cambridge University Press',
    accessedOn: '2026-08-16',
    licenseOrUse: 'Scholarly environmental synthesis cited for research; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.met-educator',
    title: 'The Art of Ancient Egypt: A Resource for Educators',
    url: 'https://www.metmuseum.org/-/media/files/learn/for-educators/publications-for-educators/the-art-of-ancient-egypt.pdf',
    publisher: 'The Metropolitan Museum of Art',
    accessedOn: '2026-08-16',
    licenseOrUse: 'Museum educator reference cited for research; PDF media are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.hierakonpolis-expedition',
    title: 'Firsts of the First City',
    url: 'https://www.hierakonpolis-online.org/index.php/about-hierakonpolis/firsts-of-the-first-city',
    publisher: 'Hierakonpolis Expedition',
    accessedOn: '2026-08-16',
    licenseOrUse: 'Active excavation-project synthesis cited for research; images are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.unesco-memphis',
    title: 'Memphis and its Necropolis',
    url: 'https://whc.unesco.org/en/list/86/',
    publisher: 'UNESCO World Heritage Centre',
    accessedOn: '2026-08-16',
    licenseOrUse: 'Official heritage and geographic reference; description is CC BY-SA IGO 3.0, maps are reference-only',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.commons-ancient-map',
    title: 'Ancient Egypt main map',
    url: 'https://commons.wikimedia.org/wiki/File:Ancient_Egypt_main_map.png',
    publisher: 'Wikimedia Commons / Jeff Dahl',
    accessedOn: '2026-08-19',
    licenseOrUse: 'CC BY-SA 3.0 raster map used as the geographic composition reference; attribution and share-alike preserved',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.pleiades-abydos',
    title: 'Abydos/Ebot',
    url: 'https://pleiades.stoa.org/places/756512',
    publisher: 'Pleiades, Ancient World Mapping Center / ISAW',
    accessedOn: '2026-08-19',
    licenseOrUse: 'CC BY 3.0 scholarly place record and representative coordinate used for geographic cross-checking',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.ucl-tour-nile',
    title: 'Tour of the Nile',
    url: 'https://www.ucl.ac.uk/3dpetriemuseum/stories/excavation-and-rediscovery/tour-of-the-nile/Tour_of_the_Nile.html',
    publisher: 'UCL Petrie Museum',
    accessedOn: '2026-08-19',
    licenseOrUse: 'University museum reference used to cross-check north-to-south site order; image is not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.met-predynastic-boats',
    title: 'Decorated ware jar depicting two boats',
    url: 'https://www.metmuseum.org/art/collection/search/558187',
    publisher: 'The Metropolitan Museum of Art',
    accessedOn: '2026-08-19',
    licenseOrUse: 'CC0 Open Access image, accession 99.3.2; used as a Predynastic boat and pottery reference for the reconstruction',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.hierakonpolis-tomb-boat',
    title: 'Hierakonpolis Tomb 100 boat',
    url: 'https://commons.wikimedia.org/wiki/File:Hierakonpolis_Tomb_100_Boat.jpg',
    publisher: 'Wikimedia Commons / Frederick William Green and James Edward Quibell',
    accessedOn: '2026-08-19',
    licenseOrUse: 'Public Domain Mark and PD-US-expired; c. 3500–3200 BCE boat image used as a period reference for the reconstruction',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.met-narmer-sealing',
    title: 'Mud jar sealing with King Narmer’s name',
    url: 'https://www.metmuseum.org/art/collection/search/547443',
    publisher: 'The Metropolitan Museum of Art',
    accessedOn: '2026-09-25',
    licenseOrUse: 'Open Access object record, accession 12.187.42, cited for object facts and find place; image is not used',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.the-past-tomb-u-j',
    title: 'The discovery of Tomb U-j',
    url: 'https://the-past.com/shorts/the-picture-desk/the-discovery-of-tomb-u-j/',
    publisher: 'The Past (Current Publishing)',
    accessedOn: '2026-09-25',
    licenseOrUse: 'Archaeology magazine feature cited for find facts; images are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.archaeology-abydos-glyphs',
    title: 'Earliest Egyptian Glyphs',
    url: 'https://archive.archaeology.org/9903/newsbriefs/egypt.html',
    publisher: 'Archaeology (Archaeological Institute of America), March/April 1999',
    accessedOn: '2026-09-25',
    licenseOrUse: 'Magazine news report cited for label size and sign count; text is not reproduced',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.herodotus-godley',
    title: 'Herodotus, Histories 2.99, translated by A. D. Godley',
    url: 'https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0126%3Abook%3D2%3Achapter%3D99',
    publisher: 'Perseus Digital Library / Harvard University Press (1920)',
    accessedOn: '2026-09-25',
    licenseOrUse: 'CC BY-SA 3.0 US digital text of a public-domain translation; cited as later tradition, paraphrased',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.smith-herodotus',
    title: 'Herodotus, in A Dictionary of Greek and Roman Biography and Mythology',
    url: 'https://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.04.0104:entry=herodotus-bio-1',
    publisher: 'Perseus Digital Library / William Smith (1867)',
    accessedOn: '2026-09-25',
    licenseOrUse: 'Public-domain reference work cited only for Herodotus’s fifth-century BCE lifetime',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.waddell-manetho',
    title: 'Manetho, with an English translation by W. G. Waddell',
    url: 'https://archive.org/details/manethowithengli00maneuoft',
    publisher: 'Loeb Classical Library / Harvard University Press (1940), via Internet Archive',
    accessedOn: '2026-09-25',
    licenseOrUse: 'Scholarly translation cited as later tradition (Fr. 6 and introduction), paraphrased',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.mcnamara-narmer-macehead',
    title: 'Ashmolean Object in Focus: The Narmer Mace-Head',
    url: 'https://www.hierakonpolis-online.org/files/hk_nn/nn-31-2019.pdf',
    publisher: 'Liam McNamara, Nekhen News 31 (2019), 10–11, Hierakonpolis Expedition',
    accessedOn: '2026-09-25',
    licenseOrUse: 'Curator’s object study in the excavation project’s journal, cited for facts and interpretations; images are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.ashmolean-origins-gallery',
    title: 'Egypt at its Origins gallery',
    url: 'https://www.ashmolean.org/egypt-and-its-origins-gallery',
    publisher: 'Ashmolean Museum, University of Oxford',
    accessedOn: '2026-09-25',
    licenseOrUse: 'Museum gallery description cited for the object’s location and ceremonial character; images are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.wilson-horned-beasts',
    title: 'Hilary Wilson on… Horned beasts: 2',
    url: 'https://the-past.com/feature/hilary-wilson-on-horned-beasts-2/',
    publisher: 'The Past (Current Publishing)',
    accessedOn: '2026-09-25',
    licenseOrUse: 'Egyptologist’s magazine feature cited to cross-check the mace-head’s numbers; images are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.egypt.commons-narmer-macehead-quibell',
    title: 'Narmer Macehead Quibell 1900',
    url: 'https://commons.wikimedia.org/wiki/File:Narmer_Macehead_Quibell_1900.jpg',
    publisher: 'Wikimedia Commons / J. E. Quibell, Hierakonpolis I (London, 1900)',
    accessedOn: '2026-09-25',
    licenseOrUse: 'Public domain (published 1900; author died 1935); faithful scan of the excavation plate used as runtime evidence',
    reviewStatus: 'reviewed',
  },
];

export const egyptNileStateClaims: Claim[] = [
  {
    id: 'claim.egypt.nile-corridor',
    statement: 'The Nile joined a narrow valley, a broad delta, wetlands, and desert-edge settlements into a long corridor for food, movement, and exchange.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.egypt.cambridge-nile', 'source.egypt.british-museum-early-egypt'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.no-river-determinism',
    statement: 'The Nile made connection possible, but a river did not automatically create one state.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.egypt.wengrow-state-formation', 'source.egypt.cambridge-nile'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.long-state-formation',
    statement: 'Egyptian state formation was a long, uneven process of competition, alliance, display, production, and administration, not one invention day.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.egypt.wengrow-state-formation', 'source.egypt.met-educator'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.unified-around-3100',
    statement: 'By about 3100 BCE, evidence supports rule over a politically unified Egypt, although the exact sequence remains debated.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.egypt.british-museum-early-egypt', 'source.egypt.met-educator', 'source.egypt.wengrow-state-formation'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.narmer-attested',
    statement: 'Narmer is known from contemporary inscriptions at multiple sites as well as the famous palette.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.egypt.ucl-narmer', 'source.egypt.ministry-narmer-palette'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.menes-uncertain',
    statement: 'Whether Narmer was the later remembered founder Menes is uncertain.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.egypt.ucl-narmer'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.palette-observations',
    statement: 'The Narmer Palette shows the ruler’s name, different crowns, ordered attendants, defeated people, animal imagery, and scenes of royal violence.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.egypt.ministry-narmer-palette', 'source.egypt.stevenson-palettes', 'source.egypt.commons-narmer-palette'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.palette-royal-claim',
    statement: 'The palette presents force, order, and elite ceremony as parts of legitimate kingship.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.egypt.stevenson-palettes', 'source.egypt.ministry-narmer-palette'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.palette-cannot-prove-unification',
    statement: 'The Narmer Palette cannot by itself prove that one pictured battle unified all Egypt exactly as shown.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.egypt.stevenson-palettes', 'source.egypt.wengrow-state-formation'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.ceremonial-elite-medium',
    statement: 'Late ceremonial palettes were rare, elaborate media tied to emerging kingship and restricted elite contexts.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.egypt.stevenson-palettes'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.early-writing',
    statement: 'By about 3250 BCE, short Egyptian inscriptions on labels and containers recorded names, places, quantities, or goods.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.egypt.regulski-writing', 'source.egypt.british-museum-early-egypt'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.writing-and-rule',
    statement: 'Early writing helped direct goods and administration while also displaying elite ownership and authority.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.egypt.regulski-writing'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.memphis-region',
    statement: 'The Memphis region became a strategic administrative center near the meeting of valley and delta.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.egypt.unesco-memphis', 'source.egypt.met-educator', 'source.egypt.regulski-writing'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.evidence-bias',
    statement: 'Most surviving early records come from elite cemeteries and ceremonies, so they reveal rulers more clearly than farmers, boat crews, craftspeople, and storehouse workers.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.egypt.regulski-writing', 'source.egypt.wengrow-state-formation'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.palette-discovery',
    statement: 'James Quibell and Frederick Green found the Narmer Palette during excavations at Nekhen (Hierakonpolis) in 1897–1899.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.egypt.hierakonpolis-expedition', 'source.egypt.stevenson-palettes'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.palette-most-reproduced',
    statement: 'The Hierakonpolis Expedition calls the Narmer Palette probably the most reproduced image from ancient Egypt after Tutankhamun’s golden mask.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.egypt.hierakonpolis-expedition'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.main-deposit-not-original',
    statement: 'The buried “Main Deposit” at Hierakonpolis where the Narmer Palette was found was not the place where it was made or used.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.egypt.stevenson-palettes'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.nekhen-brewery',
    statement: 'Around 3600 BCE, Nekhen had breweries that its excavators estimate could make about 300 gallons of beer a day.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.egypt.hierakonpolis-expedition'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.nekhen-animal-burials',
    statement: 'A cemetery at Nekhen holds early animal burials, including baboons, dogs, and cattle, and the only known elephant burial, dated about 3600 BCE.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.egypt.hierakonpolis-expedition'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.everyday-palettes',
    statement: 'Ordinary Predynastic palettes were used to grind minerals, most often green malachite, probably to make eye paint.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.egypt.stevenson-palettes'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.ceremonial-palette-count',
    statement: 'Just over 25 ceremonial palettes are known, whole or in fragments.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.egypt.stevenson-palettes'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.grinding-circle-unused',
    statement: 'Many ceremonial palettes keep a circular area for grinding minerals, but they lack traces of grinding.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.egypt.stevenson-palettes'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.serpopards',
    statement: 'The long-necked creatures on the Narmer Palette, often called serpopards, are held in check by human figures and are regarded as motifs drawn from Near Eastern art.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.egypt.ministry-narmer-palette', 'source.egypt.stevenson-palettes'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.smiting-image-endured',
    statement: 'The image of the king about to strike an enemy became a lasting symbol of Egyptian kingship and was still carved on the last ancient Egyptian temples.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.egypt.ministry-narmer-palette'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.literal-readings',
    statement: 'Early twentieth-century scholars treated ceremonial palettes such as the Narmer Palette as records of actual events; such literal readings are seldom fully accepted today.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.egypt.stevenson-palettes'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.herodotus-menes',
    statement: 'In the 400s BCE, Egyptian priests told the Greek writer Herodotus that the first king, Min, dammed the Nile to make dry land and founded Memphis there.',
    kind: 'later-tradition',
    certainty: 'high',
    sourceIds: ['source.egypt.herodotus-godley', 'source.egypt.smith-herodotus'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.manetho-menes',
    statement: 'Manetho, an Egyptian priest writing in Greek in the 200s BCE, named Menes as the first king; surviving excerpts of his work say Menes was carried off by a hippopotamus.',
    kind: 'later-tradition',
    certainty: 'high',
    sourceIds: ['source.egypt.waddell-manetho'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.narmer-sealing',
    statement: 'A mud jar sealing about 12 centimeters across that carries Narmer’s name was found in a tomb at Tarkhan, near the entrance to the Fayum, far downriver from Nekhen.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.egypt.met-narmer-sealing', 'source.egypt.commons-ancient-map'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.abydos-labels-find',
    statement: 'In 1988, a German Archaeological Institute team led by Günter Dreyer found well over a hundred small inscribed bone and ivory labels in Tomb U-j at Abydos; forty-three carry only numbers.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.egypt.the-past-tomb-u-j', 'source.egypt.archaeology-abydos-glyphs'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.macehead-find',
    statement: 'The Narmer mace-head, a carved limestone mace-head about 20 centimeters tall and weighing 8 kilograms, was found in the Main Deposit at Hierakonpolis in 1897–1899 and is now in the Ashmolean Museum, Oxford.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.egypt.mcnamara-narmer-macehead', 'source.egypt.ashmolean-origins-gallery'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.macehead-ceremonial',
    statement: 'The Narmer mace-head was too heavy to use as a weapon and was probably carried in festivals as a symbol of royal power.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.egypt.mcnamara-narmer-macehead', 'source.egypt.ashmolean-origins-gallery'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.macehead-scene',
    statement: 'The mace-head shows Narmer in the Red Crown enthroned under a canopy on a stepped platform, a figure in a carrying chair, and a count of 400,000 oxen, 1,422,000 goats, and 120,000 captives.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.egypt.mcnamara-narmer-macehead', 'source.egypt.wilson-horned-beasts', 'source.egypt.commons-narmer-macehead-quibell'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.macehead-readings',
    statement: 'Scholars have read the mace-head scene as a royal festival, a public appearance of the king, or a symbolic wedding.',
    kind: 'interpretation',
    certainty: 'contested',
    sourceIds: ['source.egypt.mcnamara-narmer-macehead'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.macehead-numbers-claim',
    statement: 'The mace-head’s numbers are a royal claim carved on a ceremonial object; like the palette scenes, they cannot simply be taken as a literal record.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.egypt.mcnamara-narmer-macehead', 'source.egypt.stevenson-palettes'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.egypt.abydos-label-size',
    statement: 'The Abydos labels measure about 2 by 1.5 centimeters and carry one to four signs each.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.egypt.archaeology-abydos-glyphs'],
    reviewStatus: 'reviewed',
  },
];

export const egyptNileStateMedia: MediaAsset[] = [
  {
    id: 'media.egypt.nile-corridor-map',
    locator: mediaLocator('media.egypt.nile-corridor-map'),
    alt: 'North-up illustrated map of the Nile corridor with the Mediterranean and Nile Delta at top, Memphis near the Delta entrance, Abydos farther south, and Nekhen or Hierakonpolis farthest south; Upper Egypt is south and Lower Egypt north',
    depictionMode: 'map',
    depictionLabel: 'Evidence-based historical map · river branches, wetlands, and settlement extents are approximate',
    rightsLabel: 'Chronos original raster map edit · geographic reference by Jeff Dahl, CC BY-SA 3.0',
    sourceIds: ['source.egypt.commons-ancient-map', 'source.egypt.unesco-memphis', 'source.egypt.pleiades-abydos', 'source.egypt.hierakonpolis-expedition', 'source.egypt.ucl-tour-nile'],
    visualBriefRef: 'docs/research/the-nile-and-an-early-egyptian-state-map.md#generated-artwork-lineage',
    reviewStatus: 'approved',
  },
  {
    id: 'media.egypt.narmer-palette',
    locator: mediaLocator('media.egypt.narmer-palette'),
    alt: 'Both faces of the gray-green Narmer Palette shown side by side, including Narmer in the White Crown raising a mace on one face and Narmer in the Red Crown leading a procession on the other',
    depictionMode: 'evidence',
    depictionLabel: 'Surviving evidence · both faces shown together without cropping',
    rightsLabel: 'Public Domain Mark · faithful reproduction of a public-domain two-dimensional work',
    sourceIds: ['source.egypt.commons-narmer-palette', 'source.egypt.ministry-narmer-palette', 'source.egypt.stevenson-palettes'],
    visualBriefRef: 'docs/research/the-nile-and-an-early-egyptian-state.md#image-lifecycle',
    reviewStatus: 'approved',
  },
  {
    id: 'media.egypt.narmer-macehead',
    locator: mediaLocator('media.egypt.narmer-macehead'),
    alt: 'Black-and-white excavation plate of the Narmer mace-head: two rows of photographs of its worn, carved limestone surface, and below them a line drawing of the whole scene unrolled flat, with the king enthroned under a canopy at the top of steps, standard-bearers, a figure in a covered carrying chair, an ox, a goat and a kneeling captive above rows of number signs, and an enclosure of horned animals',
    depictionMode: 'evidence',
    depictionLabel: 'Surviving evidence · excavation photographs and drawing published in 1900',
    rightsLabel: 'Public domain · J. E. Quibell, Hierakonpolis I (1900), via Wikimedia Commons',
    sourceIds: ['source.egypt.commons-narmer-macehead-quibell', 'source.egypt.mcnamara-narmer-macehead', 'source.egypt.ashmolean-origins-gallery'],
    visualBriefRef: 'docs/research/the-nile-and-an-early-egyptian-state.md#image-lifecycle',
    reviewStatus: 'approved',
  },
  {
    id: 'media.egypt.nile-landing-reconstruction',
    locator: mediaLocator('media.egypt.nile-landing-reconstruction'),
    alt: 'Evidence-led reconstruction of workers unloading jars, baskets, and bundles from a Nile boat while others check closures and cords and carry goods into low mudbrick storehouses',
    depictionMode: 'evidence-based-reconstruction',
    depictionLabel: 'Evidence-led reconstruction · the exact people, landing, and moment are illustrative',
    rightsLabel: 'Chronos original reconstruction · boat references from The Met, CC0, and Green and Quibell, Public Domain',
    sourceIds: ['source.egypt.regulski-writing', 'source.egypt.wengrow-state-formation', 'source.egypt.cambridge-nile', 'source.egypt.hierakonpolis-expedition', 'source.egypt.met-predynastic-boats', 'source.egypt.hierakonpolis-tomb-boat'],
    visualBriefRef: 'docs/research/the-nile-and-an-early-egyptian-state.md#image-lifecycle',
    reviewStatus: 'approved',
  },
];

export const egyptNileStatePrompts: UnderstandingPrompt[] = [
  {
    id: 'prompt.egypt.palette-supported-claim', bestOptionId: 'option.egypt.palette-kingship-claim',
    lessonId: 'lesson.egypt.nile-state',
    kind: 'supported-selection',
    question: 'Which conclusion is best supported by the Narmer Palette itself?',
    explanation: 'The visible crowns, attendants, defeated figures, scale, and ritual order support a bounded claim about how Narmer’s rule was presented. They do not prove one exact conquest story or tell us what every community thought.',
    required: true,
    options: [
      { id: 'option.egypt.palette-kingship-claim', label: 'Narmer’s image connected kingship with force, order, and rule over different regions.' },
      { id: 'option.egypt.palette-one-battle', label: 'One battle shown on the Palette certainly unified every part of Egypt.' },
      { id: 'option.egypt.palette-everyone-agreed', label: 'Every community accepted Narmer’s rule without resistance.' },
      { id: 'option.egypt.palette-daily-tool', label: 'Farmers used this large carved Palette as an everyday grinding board.' },
    ],
  },
  {
    id: 'prompt.egypt.evidence-and-limit',
    lessonId: 'lesson.egypt.nile-state',
    kind: 'concise-explanation',
    question: 'Choose the Nile corridor, the Narmer Palette, or the early labels. How does that evidence help explain state formation, and what can it not prove by itself?',
    explanation: 'A strong answer makes one supported connection—movement, royal ideology, or administration—then names a limit such as exact motives, one conquest sequence, every worker’s experience, or the first moment a state existed.',
    required: true,
    minimumResponseLength: 30,
  },
];

export const egyptNileStateLesson: Lesson = {
  id: 'lesson.egypt.nile-state',
  legacyAliases: ['hieroglyphs', 'narmer'],
  status: 'published',
  title: 'The Nile and an Early Egyptian State',
  masthead: 'c. 3200–2700 BCE',
  place: 'Nile Valley and Delta, northeastern Africa',
  chronology: {
    startYear: -3200,
    endYear: -2700,
    display: 'c. 3200–2700 BCE',
    approximate: true,
  },
  significance: 'The Nile connected communities, but generations of political competition, labor, administration, writing, and royal claims made an early territorial state.',
  heroMediaId: 'media.egypt.nile-landing-reconstruction',
  heroLabel: 'Evidence-led reconstruction',
  heroCaption: 'A reconstructed Nile landing and storehouse workflow based on archaeological evidence — not a photograph of one known place or moment.',
  sectionIdsRequired: [
    'section.egypt.river-corridor',
    'section.egypt.before-one-king',
    'section.egypt.read-palette',
    'section.egypt.palette-limits',
    'section.egypt.administration',
    'section.egypt.world-check',
  ],
  sections: [
    {
      id: 'section.egypt.river-corridor',
      heading: 'The Nile corridor',
      purpose: 'Establish the Nile’s spatial opportunities while rejecting geographic inevitability',
      modules: [
        {
          id: 'module.egypt.opening-river',
          type: 'prose',
          body: 'Between 1897 and 1899, two British archaeologists, James Quibell and Frederick Green, were digging at Nekhen, an ancient town far up the Nile in the south of Egypt. Among the objects they brought out of the ground was a tall slab of gray-green stone, carved on both faces with a king, his crowns, his servants and his enemies. It is the Narmer Palette, more than 5,000 years old. The team that digs at Nekhen today calls it probably the most reproduced image from ancient Egypt after Tutankhamun’s golden mask.\n\nThe Palette is often said to show the moment Egypt became one kingdom. This lesson puts that idea to the test. Start with the river the stone came from.\n\nAway from the Nile, Egypt is desert. Along the river runs a narrow green corridor of fields, villages, workshops and landing places, hundreds of kilometers long, until the river spreads into a broad, wet delta and reaches the Mediterranean. The current flows north. So Upper Egypt, upriver, is the long valley in the south, and Lower Egypt, downriver, is the delta in the north. On a modern map the names look upside down; to anyone traveling by boat, they made perfect sense.\n\nBoats could carry people, jars, grain, stone, timber, cattle and messages along the whole corridor, and the yearly flood renewed the fields, though the river and its channels also shifted. That made connection possible. It did not make a kingdom. People still had to build, often unequally, the relationships and institutions that turned movement into rule.',
          claimIds: ['claim.egypt.palette-discovery', 'claim.egypt.palette-most-reproduced', 'claim.egypt.unified-around-3100', 'claim.egypt.nile-corridor', 'claim.egypt.no-river-determinism'],
          sourceIds: ['source.egypt.hierakonpolis-expedition', 'source.egypt.ministry-narmer-palette', 'source.egypt.cambridge-nile', 'source.egypt.british-museum-early-egypt', 'source.egypt.wengrow-state-formation'],
        },
        {
          id: 'module.egypt.upper-lower',
          type: 'knowledge',
          eyebrow: 'Upper and Lower Egypt',
          title: 'Upper is upriver; Lower is downriver',
          body: 'Three relationships keep the map straight. None of them was a fixed political border.',
          items: [
            { label: 'Upper Egypt', detail: 'The long southern valley, upriver and at higher elevation.' },
            { label: 'Lower Egypt', detail: 'The northern delta, downriver where channels fan toward the Mediterranean.' },
            { label: 'The corridor', detail: 'River travel connected many communities without erasing their local histories or automatically placing them under one ruler.' },
          ],
          claimIds: ['claim.egypt.nile-corridor', 'claim.egypt.no-river-determinism'],
          sourceIds: ['source.egypt.cambridge-nile', 'source.egypt.met-educator'],
        },
        {
          id: 'module.egypt.nile-map',
          type: 'historical-map',
          eyebrow: 'Follow the corridor',
          title: 'Three places along one river',
          body: 'Use the map to hold the north–south relationship in view: Nekhen in the southern valley, Abydos farther north, and the Memphis region near the meeting of valley and delta. These positions help explain movement and administration; they do not draw a timeless political border.',
          mediaId: 'media.egypt.nile-corridor-map',
          periodLabel: 'c. 3200–2700 BCE',
          focusPlace: 'Nile Valley and Delta',
          modernContext: 'Northeastern Africa; ancient channels and wetlands changed',
          accessibleSummary: 'A north-oriented map follows the Nile from Upper Egypt in the south through Nekhen and Abydos to the Memphis region and the Nile Delta in Lower Egypt. The river reaches the Mediterranean Sea in the north. No political borders or conquest arrows are shown.',
          compactLabel: 'Broad river relationships · no political borders',
          coordinateNote: 'Memphis is anchored by UNESCO World Heritage coordinates, Abydos by Pleiades, and Nekhen by a broad site position cross-checked against archaeological reference maps.',
          uncertaintyNote: 'River branches, wetlands, shorelines, and settlement extents changed over time; the map preserves broad relative locations rather than reconstructing one exact ancient year.',
          depictionStatus: 'evidence-based-reconstruction',
          introLayout: 'dense',
          claimIds: ['claim.egypt.nile-corridor', 'claim.egypt.no-river-determinism', 'claim.egypt.memphis-region'],
          sourceIds: ['source.egypt.commons-ancient-map', 'source.egypt.pleiades-abydos', 'source.egypt.ucl-tour-nile', 'source.egypt.unesco-memphis', 'source.egypt.hierakonpolis-expedition'],
        },
      ],
    },
    {
      id: 'section.egypt.before-one-king',
      heading: 'Before one king',
      purpose: 'Replace a neat two-kingdom conquest story with a long process of political experimentation',
      modules: [
        {
          id: 'module.egypt.long-process',
          type: 'prose',
          body: 'The Palette was buried in a town that was already old. Around 3600 BCE, some five hundred years before Narmer, Nekhen had breweries that its excavators estimate could make about 300 gallons of beer a day. One of its cemeteries held the graves of baboons, dogs and cattle, and the only elephant burial yet known. Nekhen mattered long before anyone ruled the whole river.\n\nIt is tempting to picture two finished kingdoms, Upper and Lower Egypt, facing each other across a border until one final battle joined them. Archaeology does not show that. Over centuries, communities and regional centers changed in different ways. Nekhen and Abydos grew important in the south. Their leaders competed through production, trade, ritual, burial, display, alliances and violence. Southern-style objects spread north, while Delta communities kept their own economies, settlements and links beyond the Nile.\n\nBy about 3100 BCE, one ruler could claim authority over a politically unified Egypt. That was not one day’s work. Many earlier changes had reached the point where a single kingship could organize and represent a territory hundreds of kilometers long, and every ruler after that still had to keep it working.',
          claimIds: ['claim.egypt.nekhen-brewery', 'claim.egypt.nekhen-animal-burials', 'claim.egypt.long-state-formation', 'claim.egypt.unified-around-3100'],
          sourceIds: ['source.egypt.hierakonpolis-expedition', 'source.egypt.wengrow-state-formation', 'source.egypt.met-educator', 'source.egypt.british-museum-early-egypt'],
        },
        {
          id: 'module.egypt.state-formation-process',
          type: 'knowledge',
          eyebrow: 'How the state grew',
          title: 'Several processes became one political system',
          body: 'None of these made the state on its own. Together, over generations, they changed what powerful people and institutions could do.',
          items: [
            { label: 'Production and exchange', detail: 'Food, craft goods, stone, animals, and imported materials moved through growing networks.' },
            { label: 'Competition and alliance', detail: 'Regional elites used relationships, ritual, display, and force to expand or defend authority.' },
            { label: 'Administration', detail: 'Labels, sealings, officials, storehouses, and repeated procedures helped institutions direct goods and work.' },
            { label: 'Royal ideology', detail: 'Ceremonies and images presented one ruler as the maker of order and the controller of enemies.' },
          ],
          claimIds: ['claim.egypt.long-state-formation', 'claim.egypt.writing-and-rule', 'claim.egypt.palette-royal-claim'],
          sourceIds: ['source.egypt.wengrow-state-formation', 'source.egypt.regulski-writing', 'source.egypt.stevenson-palettes'],
        },
      ],
    },
    {
      id: 'section.egypt.read-palette',
      heading: 'Read the Narmer Palette',
      purpose: 'Observe both faces of one surviving royal object before interpreting its political message',
      modules: [
        {
          id: 'module.egypt.palette-first-look',
          type: 'prose',
          body: 'Back to the stone from Nekhen. It is about 64 centimeters tall, it dates from around 3100 BCE, and it is now in the Egyptian Museum in Cairo. Its shape copies an everyday tool: the small, flat palettes on which people ground minerals, most often green malachite, probably to make eye paint. This one is far too big and too finely carved for that. Just over 25 ceremonial palettes like it are known, so few that they seem to have belonged to a small ruling group.',
          claimIds: ['claim.egypt.palette-observations', 'claim.egypt.everyday-palettes', 'claim.egypt.ceremonial-palette-count', 'claim.egypt.ceremonial-elite-medium'],
          sourceIds: ['source.egypt.ministry-narmer-palette', 'source.egypt.stevenson-palettes'],
        },
        {
          id: 'module.egypt.palette-evidence',
          type: 'evidence',
          title: 'Both faces, held together',
          artifactLabel: 'Surviving evidence · both faces',
          body: 'Both faces are shown together and uncropped. Before reading anyone’s interpretation, find the crowns, attendants, captives, animals, signs, and changes in scale. The carving and its damage survive; the exact events behind it do not.',
          mediaId: 'media.egypt.narmer-palette',
          claimIds: ['claim.egypt.palette-observations', 'claim.egypt.ceremonial-elite-medium'],
          sourceIds: ['source.egypt.commons-narmer-palette', 'source.egypt.ministry-narmer-palette', 'source.egypt.stevenson-palettes'],
        },
        {
          id: 'module.egypt.palette-observations',
          type: 'prose',
          body: 'Start with what you can see. At the top of both faces, a catfish and a chisel spell the king’s name: Narmer. On one face he wears the tall White Crown of Upper Egypt and raises a mace over a kneeling man. A falcon, captives, an attendant and a few signs fill the rest of the scene.\n\nOn the other face he wears the Red Crown of Lower Egypt and walks in a procession toward rows of defeated enemies. Below, two long-necked beasts, often called serpopards, wind their necks around a round hollow while two men hold them in check. Scholars see creatures like these as borrowed from Near Eastern art, the wider world that included Uruk. The hollow is the grinding circle, where malachite would be ground on an everyday palette. Ceremonial palettes keep that circle, but they show no traces of grinding. At the bottom, a bull breaks into a walled enclosure. On both faces the king is far bigger than almost everyone else.\n\nThat is what the stone shows. What it proves is a harder question.',
          claimIds: ['claim.egypt.palette-observations', 'claim.egypt.narmer-attested', 'claim.egypt.early-writing', 'claim.egypt.serpopards', 'claim.egypt.grinding-circle-unused'],
          sourceIds: ['source.egypt.ministry-narmer-palette', 'source.egypt.stevenson-palettes', 'source.egypt.ucl-narmer', 'source.egypt.regulski-writing'],
        },
        {
          id: 'module.egypt.palette-observe',
          type: 'knowledge',
          eyebrow: 'What you can see',
          title: 'Four details worth holding onto',
          body: 'An observation names what is visible. An interpretation explains why it may matter.',
          items: [
            { label: 'Two crowns', detail: 'Narmer appears with a different regional crown on each face.' },
            { label: 'Unequal scale', detail: 'The ruler is shown larger than attendants, captives, and defeated people.' },
            { label: 'Ordered violence', detail: 'Processions, standards, rows, and registers organize scenes of domination.' },
            { label: 'Early writing', detail: 'Short signs identify the ruler and some people or places; they do not form a long narrative caption.' },
          ],
          claimIds: ['claim.egypt.palette-observations', 'claim.egypt.early-writing'],
          sourceIds: ['source.egypt.ministry-narmer-palette', 'source.egypt.stevenson-palettes', 'source.egypt.regulski-writing'],
        },
      ],
    },
    {
      id: 'section.egypt.palette-limits',
      heading: 'What the Palette can prove',
      purpose: 'Use the Palette for a bounded interpretation and make its limits explicit',
      modules: [
        {
          id: 'module.egypt.palette-interpretation',
          type: 'prose',
          body: 'The Palette is real evidence from Narmer’s time. It is also an argument, made for a king who commands force, ritual, servants and defeated enemies. The two crowns make rule over different parts of Egypt part of that message, and the careful order of the carving turns violence into a claim about rightful kingship. One part of that message lasted a very long time. A king with a raised mace, about to strike a kneeling enemy, became the classic image of Egyptian royal power, still carved on the walls of the last temples ancient Egyptians built.\n\nThe same buried deposit held a second royal argument. Quibell and Green also found a stone mace-head carved for Narmer: about 20 centimeters tall and weighing 8 kilograms, far too heavy to swing in a fight, so it was probably carried in festivals as a symbol of royal power. On it, Narmer sits on a throne under a canopy at the top of a flight of steps, wearing the Red Crown. Along the bottom, number signs count 400,000 oxen, 1,422,000 goats and 120,000 captives.',
          claimIds: ['claim.egypt.palette-royal-claim', 'claim.egypt.smiting-image-endured', 'claim.egypt.main-deposit-not-original', 'claim.egypt.macehead-find', 'claim.egypt.macehead-ceremonial', 'claim.egypt.macehead-scene'],
          sourceIds: ['source.egypt.stevenson-palettes', 'source.egypt.ministry-narmer-palette', 'source.egypt.mcnamara-narmer-macehead', 'source.egypt.ashmolean-origins-gallery', 'source.egypt.wilson-horned-beasts'],
        },
        {
          id: 'module.egypt.macehead-evidence',
          type: 'evidence',
          title: 'The Narmer mace-head, photographed and drawn',
          artifactLabel: 'Surviving evidence · excavation plate, 1900',
          body: 'James Quibell published this plate in 1900: photographs of the worn, rounded stone above, and his drawing of the whole scene unrolled flat below. Find the king on his throne under the canopy, the steps below him, and the figure in a covered carrying chair. Then look along the bottom for the ox, the goat and the kneeling captive, each with rows of number signs.',
          mediaId: 'media.egypt.narmer-macehead',
          scaleNote: 'The mace-head is about 20 centimeters tall and is now in the Ashmolean Museum, Oxford. The drawing is Quibell’s reading of carving that is worn in places.',
          claimIds: ['claim.egypt.macehead-find', 'claim.egypt.macehead-scene'],
          sourceIds: ['source.egypt.commons-narmer-macehead-quibell', 'source.egypt.mcnamara-narmer-macehead', 'source.egypt.ashmolean-origins-gallery'],
        },
        {
          id: 'module.egypt.palette-later-stories',
          type: 'prose',
          body: 'Early in the twentieth century, scholars often read the Palette as a record of real events: one battle in which Narmer, king of the south, conquered the north and united the country. Few specialists fully accept such literal readings today. Royal images could fold repeated conflicts, rituals, ideals and imagined enemies into one scene. The Palette may refer to real events, but it does not tell us which parts are events and which are symbols, or what anyone outside the court thought. The mace-head’s numbers raise the same question. They are the court’s count, carved on a royal object, and they cannot simply be taken as a record. Even its scene is read in different ways: as a royal festival, a public appearance by the king, or a symbolic wedding.\n\nLater Egyptians told a simpler story, and Narmer was not in it. In the 400s BCE, priests told the Greek writer Herodotus that Egypt’s first king, whom he called Min, had dammed the Nile to make dry land and built Memphis on it. In the 200s BCE, the Egyptian priest Manetho listed the founder as Menes and, in the excerpts of his work that survive, recorded that Menes was carried off by a hippopotamus. Narmer’s name, meanwhile, survives on objects from his own lifetime at several sites. Whether Narmer was the king later remembered as Menes is still an open question.',
          claimIds: ['claim.egypt.literal-readings', 'claim.egypt.palette-cannot-prove-unification', 'claim.egypt.macehead-numbers-claim', 'claim.egypt.macehead-readings', 'claim.egypt.herodotus-menes', 'claim.egypt.manetho-menes', 'claim.egypt.narmer-attested', 'claim.egypt.menes-uncertain'],
          sourceIds: ['source.egypt.stevenson-palettes', 'source.egypt.wengrow-state-formation', 'source.egypt.mcnamara-narmer-macehead', 'source.egypt.herodotus-godley', 'source.egypt.smith-herodotus', 'source.egypt.waddell-manetho', 'source.egypt.ucl-narmer'],
        },
        {
          id: 'module.egypt.palette-can-cannot',
          type: 'knowledge',
          eyebrow: 'What we can know',
          title: 'What the Palette can—and cannot—do',
          body: 'A source can be powerful without answering every question.',
          items: [
            { label: 'It can show', detail: 'How Narmer’s court connected kingship with crowns, hierarchy, violence, ceremony, and order.' },
            { label: 'It can support', detail: 'A claim that rule over different regions mattered to early royal identity.' },
            { label: 'It cannot prove alone', detail: 'That one battle created the state exactly as pictured, or that every community accepted one ruler in the same way.' },
            { label: 'It cannot recover', detail: 'The thoughts of captives, farmers, craft workers, boat crews, or most people who appear faintly—or not at all—in elite art.' },
          ],
          claimIds: ['claim.egypt.palette-royal-claim', 'claim.egypt.palette-cannot-prove-unification', 'claim.egypt.evidence-bias'],
          sourceIds: ['source.egypt.stevenson-palettes', 'source.egypt.regulski-writing', 'source.egypt.wengrow-state-formation'],
        },
      ],
    },
    {
      id: 'section.egypt.administration',
      heading: 'How administration worked',
      purpose: 'Connect movement, goods, writing, workers, and repeated procedures to durable administration',
      modules: [
        {
          id: 'module.egypt.labels-and-goods',
          type: 'prose',
          body: 'A carved stone could announce a king. Keeping a kingdom working along the whole river took quieter work, repeated every day. Boats arrived with jars, grain, linen, animals, stone and timber. Someone unloaded them. Someone checked the seals. Someone decided where the goods went, who received rations, and what work was owed.\n\nNarmer’s name turns up in that work too, and not on anything grand: a lump of dried mud about 12 centimeters across that once sealed a jar. It was found in a tomb at Tarkhan, far downriver from Nekhen, where the Palette lay.\n\nWriting had grown up alongside this kind of work. In 1988, German archaeologists digging a large tomb at Abydos found well over a hundred bone and ivory labels from around 3250 BCE, each about the size of a thumbnail (2 by 1.5 centimeters). They hold some of Egypt’s earliest writing, one to four signs apiece. Forty-three carry nothing but numbers. Others may name people, places, goods or institutions, and some were made in batches and cut apart, a sign of organized production rather than one person doodling. Writing did not begin as long stories for a wide reading public. It helped a small group keep track of goods and show who controlled them.\n\nWhere the valley meets the delta, the Memphis region became an important center of government. Later tradition, as you saw, credits the first king with founding the city there, but the real founder and the river’s ancient course are uncertain. The advantage of the place is clearer: from here, traffic between the narrow valley and the branching delta could be watched and organized.',
          claimIds: ['claim.egypt.narmer-sealing', 'claim.egypt.narmer-attested', 'claim.egypt.abydos-labels-find', 'claim.egypt.abydos-label-size', 'claim.egypt.early-writing', 'claim.egypt.writing-and-rule', 'claim.egypt.memphis-region', 'claim.egypt.herodotus-menes'],
          sourceIds: ['source.egypt.met-narmer-sealing', 'source.egypt.commons-ancient-map', 'source.egypt.the-past-tomb-u-j', 'source.egypt.archaeology-abydos-glyphs', 'source.egypt.regulski-writing', 'source.egypt.unesco-memphis', 'source.egypt.met-educator', 'source.egypt.herodotus-godley'],
        },
        {
          id: 'module.egypt.state-in-practice',
          type: 'knowledge',
          eyebrow: 'Who did the work',
          title: 'Power depended on repeated human work',
          body: 'Narmer’s name survives on a famous stone and on a lump of mud. The people who sealed the jars, loaded the boats and rowed them left no names, yet the state lasted because of their work.',
          items: [
            { label: 'Boat crews and carriers', detail: 'Moved food, stone, people, and messages along river routes and between landings.' },
            { label: 'Farmers and herders', detail: 'Produced much of the food and livestock that institutions collected, stored, and redistributed.' },
            { label: 'Craft and storehouse workers', detail: 'Made containers, seals, labels, tools, cloth, and prestige goods; checked and protected supplies.' },
            { label: 'Officials and writers', detail: 'Turned selected people, places, goods, and obligations into records that institutions could reuse.' },
          ],
          claimIds: ['claim.egypt.narmer-sealing', 'claim.egypt.writing-and-rule', 'claim.egypt.evidence-bias', 'claim.egypt.nile-corridor'],
          sourceIds: ['source.egypt.met-narmer-sealing', 'source.egypt.regulski-writing', 'source.egypt.wengrow-state-formation', 'source.egypt.cambridge-nile', 'source.egypt.hierakonpolis-expedition'],
        },
        {
          id: 'module.egypt.nile-landing-field-guide',
          type: 'scene',
          title: 'Follow the goods from boat to storehouse',
          body: 'Evidence-led reconstruction: the exact people, landing, and moment are illustrative. Open the field guide to follow the goods from boat to storehouse, the everyday work the Palette never shows.',
          mediaId: 'media.egypt.nile-landing-reconstruction',
          hotspots: [
            { label: 'River transport', detail: 'Boat crews and carriers moved containers, food, materials, people, and messages along the Nile corridor.' },
            { label: 'Checks, seals, and cords', detail: 'Workers could inspect closures, seals, tags, and containers. The scene shows the physical workflow without claiming exact marks or one documented landing.' },
            { label: 'Storage and redistribution', detail: 'Mudbrick storehouses made collection visible, but keeping goods useful required repeated decisions about access, protection, rations, and destinations.' },
          ],
          claimIds: ['claim.egypt.writing-and-rule', 'claim.egypt.evidence-bias', 'claim.egypt.nile-corridor'],
          sourceIds: ['source.egypt.regulski-writing', 'source.egypt.met-predynastic-boats', 'source.egypt.hierakonpolis-tomb-boat', 'source.egypt.hierakonpolis-expedition'],
        },
      ],
    },
    {
      id: 'section.egypt.world-check',
      heading: 'World Check',
      purpose: 'Require one bounded claim from evidence and one explicit limit',
      modules: [
        {
          id: 'module.egypt.prompt-palette',
          type: 'prompt',
          promptId: 'prompt.egypt.palette-supported-claim',
          claimIds: [],
          sourceIds: [],
        },
        {
          id: 'module.egypt.prompt-limit',
          type: 'prompt',
          promptId: 'prompt.egypt.evidence-and-limit',
          claimIds: [],
          sourceIds: [],
        },
      ],
    },
  ],
  claimIds: egyptNileStateClaims.map((claim) => claim.id),
  sourceIds: egyptNileStateSources.map((source) => source.id),
  mediaIds: egyptNileStateMedia.map((media) => media.id),
  promptIds: egyptNileStatePrompts.map((prompt) => prompt.id),
};

export const egyptNileStateCards: KnowledgeCard[] = [
  {
    id: 'card.artifact.narmer-palette',
    title: 'Narmer Palette',
    category: 'artifact',
    cardClass: 'witness',
    date: {
      startYear: -3100,
      endYear: -3000,
      display: 'c. 3100 BCE',
      approximate: true,
    },
    place: 'Nekhen (Hierakonpolis), Upper Egypt',
    significance: 'A carved royal claim that reveals how early kingship wanted to be seen without recording the whole path to power.',
    revealTitle: 'A royal claim, read with limits',
    revealBody: 'You earned this Artifact card by using both faces of the Palette as evidence while refusing to treat one court image as a complete conquest record.',
    depictionLabel: 'Artifact-focused · surviving evidence',
    facts: [
      'A ceremonial gray-green stone palette about 64 centimeters tall',
      'Found at Nekhen by James Quibell and Frederick Green in 1897–1899; now in the Egyptian Museum in Cairo',
      'Shows Narmer with different regional crowns, attendants, captives, fantastic animals, and royal violence',
      'Can support claims about royal ideology but cannot prove one battle unified all Egypt exactly as shown',
    ],
    lessonIds: ['lesson.egypt.nile-state'],
    sourceIds: ['source.egypt.commons-narmer-palette', 'source.egypt.ministry-narmer-palette', 'source.egypt.stevenson-palettes', 'source.egypt.hierakonpolis-expedition'],
    mediaId: 'media.egypt.narmer-palette',
    unlockLessonId: 'lesson.egypt.nile-state',
  },
];

export const egyptNileStateContent: AuthoredContentModule = {
  sources: egyptNileStateSources,
  claims: egyptNileStateClaims,
  media: egyptNileStateMedia,
  prompts: egyptNileStatePrompts,
  lessons: [egyptNileStateLesson],
  cards: egyptNileStateCards,
};
