import type { Claim, KnowledgeCard, Lesson, MediaAsset, Source, UnderstandingPrompt } from '../../src/domains/contracts';
import type { AuthoredContentModule } from '../assemble';
import { mediaLocator } from '../shared/media-locator';

export const farmingSettlementsSources: Source[] = [
  {
    id: 'source.farming.baird-2018-anatolia',
    title: 'Agricultural origins on the Anatolian plateau',
    url: 'https://doi.org/10.1073/pnas.1800163115',
    publisher: 'Proceedings of the National Academy of Sciences',
    accessedOn: '2026-07-21',
    licenseOrUse: 'Peer-reviewed research citation; figures not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.bogaard-2009-pantries',
    title: 'Private pantries and celebrated surplus: storing and sharing food at Neolithic Çatalhöyük, Central Anatolia',
    url: 'https://doi.org/10.1017/S0003598X00098896',
    publisher: 'Antiquity / Cambridge University Press',
    accessedOn: '2026-07-21',
    licenseOrUse: 'Peer-reviewed research citation; article media not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.unesco-catalhoyuk',
    title: 'Neolithic Site of Çatalhöyük',
    url: 'https://whc.unesco.org/en/list/1405/',
    publisher: 'UNESCO World Heritage Centre',
    accessedOn: '2026-07-21',
    licenseOrUse: 'Institutional World Heritage description under CC-BY-SA IGO 3.0; used for place framing, not redistributed as lesson media',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.unesco-catalhoyuk-maps',
    title: 'Neolithic Site of Çatalhöyük — Maps and geographical data',
    url: 'https://whc.unesco.org/en/list/1405/maps/',
    publisher: 'UNESCO World Heritage Centre',
    accessedOn: '2026-07-21',
    licenseOrUse: 'Official World Heritage geographical table and nomination maps used as coordinate/regional reference; nomination map images not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.natural-earth',
    title: 'Natural Earth',
    url: 'https://www.naturalearthdata.com/',
    publisher: 'Natural Earth',
    accessedOn: '2026-07-21',
    licenseOrUse: 'Public Domain geographic base used for modern coast and landmass orientation only',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.catalhoyuk-architecture',
    title: 'Architecture',
    url: 'http://www.catalhoyuk.com/site/architecture',
    publisher: 'Çatalhöyük Research Project',
    accessedOn: '2026-07-21',
    licenseOrUse: 'Project outreach synthesizing excavation results; project illustrations not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.larsen-2019-bioarch',
    title: 'Bioarchaeology of Neolithic Çatalhöyük reveals fundamental transitions in health, mobility, and lifestyle in early farmers',
    url: 'https://doi.org/10.1073/pnas.1904345116',
    publisher: 'Proceedings of the National Academy of Sciences',
    accessedOn: '2026-07-21',
    licenseOrUse: 'Peer-reviewed research citation; no burial imagery redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.milner-2019-commentary',
    title: 'Early agriculture’s toll on human health',
    url: 'https://doi.org/10.1073/pnas.1908960116',
    publisher: 'Proceedings of the National Academy of Sciences',
    accessedOn: '2026-07-21',
    licenseOrUse: 'Peer-reviewed commentary used as research reference; burial excavation imagery rejected for learner use',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.bogaard-2017-resilience',
    title: 'Agricultural innovation and resilience in a long-lived early farming community: the 1,500-year sequence at Neolithic to early Chalcolithic Çatalhöyük, central Anatolia',
    url: 'https://doi.org/10.1017/S0066154617000072',
    publisher: 'Anatolian Studies / Cambridge University Press',
    accessedOn: '2026-07-21',
    licenseOrUse: 'Peer-reviewed research citation; article media not redistributed',
    reviewStatus: 'reviewed',
  },
];

export const farmingSettlementsClaims: Claim[] = [
  {
    id: 'claim.farming.case-not-global',
    statement: 'This lesson is a Southwest Asian case and does not establish a single worldwide origin of farming.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.baird-2018-anatolia', 'source.farming.unesco-catalhoyuk'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.farming.gradual-uptake',
    statement: 'In Central Anatolia, cultivation could be adopted at low intensity beside foraging for centuries, and nearby communities could differ in whether they cultivated.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.baird-2018-anatolia'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.farming.settlement-density',
    statement: 'Çatalhöyük East was a long-lived, densely packed settlement of conjoined mudbrick houses entered from roofs, without streets between houses.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.farming.unesco-catalhoyuk', 'source.farming.catalhoyuk-architecture', 'source.farming.baird-2018-anatolia'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.farming.catalhoyuk-location',
    statement: 'Çatalhöyük stands on the Konya plain of the Southern Anatolian Plateau in central Anatolia; UNESCO World Heritage coordinates place the site at about 37.667° N, 32.828° E.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.farming.unesco-catalhoyuk', 'source.farming.unesco-catalhoyuk-maps'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.farming.mixed-farming',
    statement: 'By the time of Çatalhöyük East, communities practiced substantial mixed farming of domesticated plants and animals that could sustain a large sedentary community.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.baird-2018-anatolia', 'source.farming.bogaard-2017-resilience', 'source.farming.larsen-2019-bioarch'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.farming.private-storage',
    statement: 'Households stored plant foods in interior bins and side rooms that functioned as private pantries.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.farming.bogaard-2009-pantries', 'source.farming.catalhoyuk-architecture'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.farming.shared-feasting',
    statement: 'Displays of aurochs heads or horns and related evidence point to shared feasting that could ease tensions created by private stores.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.farming.bogaard-2009-pantries'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.farming.tradeoffs',
    statement: 'Denser farming life brought labor demands, crowding-related disease exposure, and other biological stresses that varied across the occupation.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.farming.larsen-2019-bioarch', 'source.farming.milner-2019-commentary'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.farming.no-palace-equality',
    statement: 'Similar house sizes and lack of palaces do not prove perfect equality; private storage and social mechanisms already manage tension.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.farming.bogaard-2009-pantries', 'source.farming.unesco-catalhoyuk'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.farming.not-a-city',
    statement: 'Çatalhöyük’s household-centered dense settlement is not the same social scale as later cities such as Uruk.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.unesco-catalhoyuk', 'source.farming.catalhoyuk-architecture', 'source.farming.bogaard-2009-pantries'],
    reviewStatus: 'editorial-review-required',
  },
];

export const farmingSettlementsMedia: MediaAsset[] = [
  {
    id: 'media.farming.catalhoyuk-rooftops',
    locator: mediaLocator('media.farming.catalhoyuk-rooftops'),
    alt: 'Evidence-based reconstruction looking across adjoining mudbrick rooftops at Çatalhöyük, with roof openings, ladders, household activity, and the dry Konya plain beyond',
    depictionMode: 'evidence-based-reconstruction',
    depictionLabel: 'Evidence-based reconstruction · exact people and moment are illustrative',
    rightsLabel: 'Chronos original reconstruction',
    sourceIds: ['source.farming.unesco-catalhoyuk', 'source.farming.catalhoyuk-architecture'],
    visualBriefRef: 'docs/research/farming-settlements-media.md#rooftop-settlement-hero',
    reviewStatus: 'approved',
  },
  {
    id: 'media.farming.catalhoyuk-house-diagram',
    locator: mediaLocator('media.farming.catalhoyuk-house-diagram'),
    alt: 'Axonometric cutaway of a Çatalhöyük mudbrick house showing the roof opening and ladder, main room, hearth and platforms, side-room storage bins, and an entrance-area animal display',
    depictionMode: 'diagram',
    depictionLabel: 'Evidence-led house diagram · excavated relationships with reconstructed surfaces',
    rightsLabel: 'Chronos original evidence diagram',
    sourceIds: ['source.farming.catalhoyuk-architecture', 'source.farming.bogaard-2009-pantries'],
    visualBriefRef: 'docs/research/farming-settlements-media.md#house-and-storage-evidence-view',
    reviewStatus: 'approved',
  },
  {
    id: 'media.farming.catalhoyuk-locator-map',
    locator: mediaLocator('media.farming.catalhoyuk-locator-map'),
    alt: 'Editorial locator map of Anatolia showing Çatalhöyük inland on the Konya plain of the Anatolian Plateau, between the Mediterranean Sea and the Black Sea',
    depictionMode: 'map',
    depictionLabel: 'Historical locator map · site coordinate verified, modern coasts for orientation',
    rightsLabel: 'Chronos original · Natural Earth base geography, Public Domain',
    sourceIds: [
      'source.farming.unesco-catalhoyuk',
      'source.farming.unesco-catalhoyuk-maps',
      'source.farming.natural-earth',
    ],
    visualBriefRef: 'docs/research/farming-catalhoyuk-locator-map.md#revision-2-visual-correction',
    reviewStatus: 'approved',
  },
  {
    id: 'media.farming.catalhoyuk-card',
    locator: mediaLocator('media.farming.catalhoyuk-card'),
    alt: 'Vertical evidence-based reconstruction of roof-connected mudbrick homes at Çatalhöyük with one roof opening and the Konya plain beyond',
    depictionMode: 'evidence-based-reconstruction',
    depictionLabel: 'Evidence-based reconstruction · settlement view',
    rightsLabel: 'Chronos original reconstruction',
    sourceIds: ['source.farming.unesco-catalhoyuk', 'source.farming.catalhoyuk-architecture'],
    visualBriefRef: 'docs/research/farming-settlements-media.md#catalhoyuk-card-artwork',
    reviewStatus: 'approved',
  },
];

export const farmingSettlementsPrompts: UnderstandingPrompt[] = [
  {
    id: 'prompt.farming.house-pattern',
    lessonId: 'lesson.farming.settlements',
    kind: 'supported-selection',
    question: 'Storage bins and plant remains were concentrated inside side rooms, while entrance areas held animal displays and evidence linked to feasting. Which conclusion is best supported?',
    explanation: 'The layout supports private household storage beside more visible shared activity. It does not prove that every household was equal, that a ruler controlled all food, or that the reconstruction shows one exact event.',
    required: true,
    options: [
      {
        id: 'option.farming.private-and-shared',
        label: 'Households kept some food in private interior stores while some activities brought people together near more visible spaces.',
      },
      {
        id: 'option.farming.perfect-equality',
        label: 'Every household owned exactly the same amount of food and held the same status.',
      },
      {
        id: 'option.farming.central-ruler',
        label: 'A ruler collected every household’s grain in one central palace store.',
      },
      {
        id: 'option.farming.exact-scene',
        label: 'The reconstructed diagram records the exact people and actions of one feast.',
      },
    ],
  },
  {
    id: 'prompt.farming.opportunity-and-cost',
    lessonId: 'lesson.farming.settlements',
    kind: 'concise-explanation',
    question: 'How could staying in one dense settlement create both an advantage and a problem? Use one detail from the houses, stored food, work, or health evidence.',
    explanation: 'A sincere answer might link an advantage — food kept for later, sturdy homes, or nearby neighbors — to a problem such as repetitive work, crowding and illness, tension around private stores, or coordinating wall-to-wall households.',
    required: true,
    minimumResponseLength: 20,
  },
];

export const farmingSettlementsLesson: Lesson = {
  id: 'lesson.farming.settlements',
  legacyAliases: [],
  status: 'published',
  title: 'Farming and Settlements',
  masthead: 'c. 7100–6000 BCE',
  place: 'Çatalhöyük · Central Anatolia',
  chronology: {
    startYear: -7100,
    endYear: -6000,
    display: 'approximately 7100–6000 BCE',
    approximate: true,
  },
  significance: 'A roof-connected settlement shows how stored food changed both the chances — and the pressures — of staying in one place.',
  heroMediaId: 'media.farming.catalhoyuk-rooftops',
  heroLabel: 'Evidence-based reconstruction',
  heroCaption: 'Architecture follows excavated patterns; the people, weather, and exact moment are reconstructed.',
  sectionIdsRequired: [
    'section.farming.enter-from-roof',
    'section.farming.slow-change',
    'section.farming.wall-to-wall',
    'section.farming.read-the-house',
    'section.farming.private-and-shared',
    'section.farming.bargain-of-staying',
    'section.farming.check-and-complete',
  ],
  sections: [
    {
      id: 'section.farming.enter-from-roof',
      heading: 'Enter from the roof',
      purpose: 'Begin inside the practical shape of a wall-to-wall settlement',
      modules: [
        {
          id: 'module.farming.rooftop-opening',
          type: 'prose',
          body: 'Step onto a flat mudbrick roof. Another roof begins where this one ends. To visit a neighbor, you walk across the roofs. To go inside, you climb down through a hole in the ceiling. There is no ordinary street below.\n\nThis reconstructed view starts from a practical fact dug from the architecture: at Çatalhöyük, homes were rebuilt tightly against one another for generations. Food, fuel, work, smoke, waste, and neighbors all had to fit that dense pattern. How did storing food change life for people who stayed in one place?\n\nÇatalhöyük is one case from Central Anatolia — not the birthplace of farming for the whole world. Other communities made different choices in other places and times.',
          claimIds: ['claim.farming.settlement-density', 'claim.farming.case-not-global'],
          sourceIds: ['source.farming.unesco-catalhoyuk', 'source.farming.catalhoyuk-architecture', 'source.farming.baird-2018-anatolia'],
        },
      ],
    },
    {
      id: 'section.farming.slow-change',
      heading: 'No single day changed everything',
      purpose: 'Show cultivation as a gradual and uneven regional process',
      modules: [
        {
          id: 'module.farming.slow-change',
          type: 'prose',
          body: 'Long before Çatalhöyük grew dense, people on the Central Anatolian plateau were trying different ways to get food. At Boncuklu, foragers grew some plants while still gathering wild foods. At nearby Pınarbaşı, archaeologists found little or no sign of farming. Groups in the same broad region did not all follow one timetable.\n\nBy about 7100 BCE, Çatalhöyük shows a much stronger commitment to crops, herded animals, and rebuilding homes in one place. Farming was not a switch everyone flipped. It was a long series of choices, skills, successes — and new dependencies.',
          claimIds: ['claim.farming.gradual-uptake', 'claim.farming.case-not-global'],
          sourceIds: ['source.farming.baird-2018-anatolia'],
        },
      ],
    },
    {
      id: 'section.farming.wall-to-wall',
      heading: 'A neighborhood built wall to wall',
      purpose: 'Place Çatalhöyük and explain the settlement pattern',
      modules: [
        {
          id: 'module.farming.wall-to-wall',
          type: 'knowledge',
          eyebrow: 'Çatalhöyük East',
          title: 'Roofs, rebuilding, and food in one place',
          body: 'On the inland Konya plain, generations built new mudbrick rooms over older ones. Staying turned separate homes into a tightly connected settlement.',
          items: [
            { label: 'Roofs became routes', detail: 'With houses touching wall to wall, people moved across roofs and climbed down into rooms.' },
            { label: 'Homes accumulated', detail: 'Repeated rebuilding in the same area formed a mound and preserved layers for archaeologists to study.' },
            { label: 'Food anchored daily life', detail: 'Crops, herded animals, and gathered foods supported a community that remained large and settled.' },
          ],
          claimIds: ['claim.farming.settlement-density', 'claim.farming.mixed-farming'],
          sourceIds: [
            'source.farming.unesco-catalhoyuk',
            'source.farming.catalhoyuk-architecture',
            'source.farming.baird-2018-anatolia',
            'source.farming.bogaard-2017-resilience',
          ],
        },
        {
          id: 'module.farming.catalhoyuk-locator-map',
          type: 'historical-map',
          eyebrow: 'Place & landscape',
          title: 'Inland on the Konya plain',
          body: 'Çatalhöyük lies on the Anatolian Plateau, inland from both the Mediterranean and Black Seas. This map locates the settlement; it does not mark a single origin point for world farming.',
          mediaId: 'media.farming.catalhoyuk-locator-map',
          periodLabel: 'c. 7100–6000 BCE',
          focusPlace: 'Çatalhöyük',
          modernContext: 'Near Çumra / Konya, Türkiye',
          accessibleSummary: 'Çatalhöyük sits inland on the Konya plain of the Anatolian Plateau, between the Mediterranean Sea to the south and the Black Sea to the north. The map places this Southwest Asian settlement case; it does not show a worldwide origin of farming.',
          compactLabel: 'Site coordinate verified · modern coasts for orientation',
          coordinateNote: 'Çatalhöyük is placed using UNESCO World Heritage coordinates.',
          uncertaintyNote: 'Coastlines and plateau washes orient the learner; they are not a reconstruction of Neolithic shorelines or river channels.',
          depictionStatus: 'illustrative-reconstruction',
          claimIds: ['claim.farming.catalhoyuk-location', 'claim.farming.case-not-global', 'claim.farming.settlement-density'],
          sourceIds: [
            'source.farming.unesco-catalhoyuk',
            'source.farming.unesco-catalhoyuk-maps',
            'source.farming.natural-earth',
          ],
        },
      ],
    },
    {
      id: 'section.farming.read-the-house',
      heading: 'Read the house',
      purpose: 'Observe the spatial pattern before interpreting it',
      modules: [
        {
          id: 'module.farming.house-evidence',
          type: 'scene',
          title: 'Follow the evidence from roof to pantry',
          body: 'This cutaway turns dug house plans into a view you can read. The room layout and bins follow the evidence. Colors, soft objects, and the exact moment are reconstructed.',
          mediaId: 'media.farming.catalhoyuk-house-diagram',
          hotspots: [
            { label: 'Roof opening', detail: 'A ladder linked the roof path to the main room below.' },
            { label: 'Main room', detail: 'Hearths, ovens, and platforms held much of a household’s daily work and rest.' },
            { label: 'Side-room bins', detail: 'Built storage bins and plant remains sat deeper inside the house — evidence for household pantries.' },
            { label: 'Entrance-area display', detail: 'Animal heads and horns near more visible spots, plus feast remains, support shared social activity — not every rule people followed.' },
          ],
          claimIds: ['claim.farming.private-storage', 'claim.farming.shared-feasting', 'claim.farming.settlement-density'],
          sourceIds: ['source.farming.bogaard-2009-pantries', 'source.farming.catalhoyuk-architecture'],
        },
      ],
    },
    {
      id: 'section.farming.private-and-shared',
      heading: 'Private stores and shared occasions',
      purpose: 'Build a bounded interpretation from the observed house pattern',
      modules: [
        {
          id: 'module.farming.private-and-shared',
          type: 'prose',
          body: 'The strongest clue is where things sat. Built bins and plant remains were concentrated inside houses, often in side rooms. That pattern supports the idea that households controlled important food stores. Near entrances and in more visible spaces, animal displays and feast remains point to occasions that involved a wider group.\n\nThe pattern matters because surplus — food kept for later — was never only a pile of calories. Someone grew it, processed it, stored it, protected it, decided when to open it, and sometimes shared it. Private stores could make a household safer. Shared meals and displays could strengthen relationships. They could also show differences and create tension.\n\nThe same evidence has limits. It cannot tell us the exact rules families followed, prove that every household had equal resources, or replay one feast. The bins survive; the conversations around them do not.',
          claimIds: ['claim.farming.private-storage', 'claim.farming.shared-feasting', 'claim.farming.no-palace-equality'],
          sourceIds: ['source.farming.bogaard-2009-pantries', 'source.farming.catalhoyuk-architecture', 'source.farming.unesco-catalhoyuk'],
        },
      ],
    },
    {
      id: 'section.farming.bargain-of-staying',
      heading: 'The bargain of staying',
      purpose: 'Hold security, labor, health, and social coordination together',
      modules: [
        {
          id: 'module.farming.bargain',
          type: 'knowledge',
          eyebrow: 'Tradeoffs',
          title: 'Food security, repeated work, health, and household scale',
          body: 'Staying was neither a simple upgrade nor a mistake. It joined new advantages to new work and risks, and those changed across Çatalhöyük’s long life.',
          items: [
            { label: 'Food for later', detail: 'Farming, herding, gathering, and storage helped households plan beyond the next day or season.' },
            { label: 'Work that repeated', detail: 'Fields, animals, fuel, plastered walls, food processing, and storage all needed steady labor.' },
            { label: 'Bodies close together', detail: 'Crowding, animals, waste, and diets heavy in carbs raised some health pressures — but not the same way for every person or century.' },
            { label: 'Household scale', detail: 'A large settlement could organize through homes and shared habits without becoming a city with palaces or written records.' },
          ],
          claimIds: ['claim.farming.tradeoffs', 'claim.farming.not-a-city', 'claim.farming.mixed-farming'],
          sourceIds: ['source.farming.larsen-2019-bioarch', 'source.farming.milner-2019-commentary', 'source.farming.bogaard-2009-pantries', 'source.farming.unesco-catalhoyuk'],
        },
      ],
    },
    {
      id: 'section.farming.check-and-complete',
      heading: 'World Check',
      purpose: 'Interpret the house pattern and explain an advantage with a problem',
      modules: [
        {
          id: 'module.farming.prompt-house-pattern',
          type: 'prompt',
          promptId: 'prompt.farming.house-pattern',
          claimIds: [],
          sourceIds: [],
        },
        {
          id: 'module.farming.prompt-tradeoff',
          type: 'prompt',
          promptId: 'prompt.farming.opportunity-and-cost',
          claimIds: [],
          sourceIds: [],
        },
      ],
    },
  ],
  claimIds: farmingSettlementsClaims.map((claim) => claim.id),
  sourceIds: farmingSettlementsSources.map((source) => source.id),
  mediaIds: [
    'media.farming.catalhoyuk-rooftops',
    'media.farming.catalhoyuk-house-diagram',
    'media.farming.catalhoyuk-locator-map',
    'media.farming.catalhoyuk-card',
  ],
  promptIds: [
    'prompt.farming.house-pattern',
    'prompt.farming.opportunity-and-cost',
  ],
};

export const farmingSettlementsCards: KnowledgeCard[] = [
  {
    id: 'card.place.catalhoyuk',
    title: 'Çatalhöyük',
    category: 'place',
    cardClass: 'foundation',
    date: {
      startYear: -7100,
      endYear: -6000,
      display: 'c. 7100–6000 BCE',
      approximate: true,
    },
    place: 'Central Anatolia, Konya plain',
    significance: 'A dense, roof-connected farming settlement where house evidence reveals how stored food changed daily life.',
    revealTitle: 'A settlement worth remembering',
    revealBody: 'You discovered Çatalhöyük by reading house and storage evidence to explain both the possibilities and pressures of staying in one place.',
    depictionLabel: 'Evidence-based reconstruction',
    facts: [
      'Long-lived Neolithic settlement on the Konya plain in central Anatolia',
      'Dense mudbrick houses entered from rooftops, without ordinary streets',
      'Household storage bins held plant foods in interior side rooms',
      'Entrance-area displays and feasting evidence point toward shared social activity',
    ],
    lessonIds: ['lesson.farming.settlements'],
    sourceIds: [
      'source.farming.unesco-catalhoyuk',
      'source.farming.bogaard-2009-pantries',
      'source.farming.catalhoyuk-architecture',
    ],
    mediaId: 'media.farming.catalhoyuk-card',
    unlockLessonId: 'lesson.farming.settlements',
  },
];

export const farmingSettlementsContent: AuthoredContentModule = {
  sources: farmingSettlementsSources,
  claims: farmingSettlementsClaims,
  media: farmingSettlementsMedia,
  prompts: farmingSettlementsPrompts,
  lessons: [farmingSettlementsLesson],
  cards: farmingSettlementsCards,
};
