import type { Claim, KnowledgeCard, Lesson, MediaAsset, Source, UnderstandingPrompt } from '../../src/domains/contracts';
import type { AuthoredContentModule } from '../assemble';
import { mediaLocator } from '../shared/media-locator';

export const farmingSettlementsSources: Source[] = [
  {
    id: 'source.farming.baird-2018-anatolia',
    title: 'Agricultural origins on the Anatolian plateau',
    url: 'https://doi.org/10.1073/pnas.1800163115',
    publisher: 'Proceedings of the National Academy of Sciences',
    accessedOn: '2026-07-21',
    licenseOrUse: 'Peer-reviewed research citation; figures not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.bogaard-2009-pantries',
    title: 'Private pantries and celebrated surplus: storing and sharing food at Neolithic Çatalhöyük, Central Anatolia',
    url: 'https://doi.org/10.1017/S0003598X00098896',
    publisher: 'Antiquity / Cambridge University Press',
    accessedOn: '2026-07-21',
    licenseOrUse: 'Peer-reviewed research citation; article media not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.unesco-catalhoyuk',
    title: 'Neolithic Site of Çatalhöyük',
    url: 'https://whc.unesco.org/en/list/1405/',
    publisher: 'UNESCO World Heritage Centre',
    accessedOn: '2026-07-21',
    licenseOrUse: 'Institutional World Heritage description under CC-BY-SA IGO 3.0; used for place framing, not redistributed as lesson media',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.unesco-catalhoyuk-maps',
    title: 'Neolithic Site of Çatalhöyük — Maps and geographical data',
    url: 'https://whc.unesco.org/en/list/1405/maps/',
    publisher: 'UNESCO World Heritage Centre',
    accessedOn: '2026-07-21',
    licenseOrUse: 'Official World Heritage geographical table and nomination maps used as coordinate/regional reference; nomination map images not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.natural-earth',
    title: 'Natural Earth',
    url: 'https://www.naturalearthdata.com/',
    publisher: 'Natural Earth',
    accessedOn: '2026-07-21',
    licenseOrUse: 'Public Domain geographic base used for modern coast and landmass orientation only',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.catalhoyuk-architecture',
    title: 'Architecture',
    url: 'http://www.catalhoyuk.com/site/architecture',
    publisher: 'Çatalhöyük Research Project',
    accessedOn: '2026-07-21',
    licenseOrUse: 'Project outreach synthesizing excavation results; project illustrations not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.larsen-2019-bioarch',
    title: 'Bioarchaeology of Neolithic Çatalhöyük reveals fundamental transitions in health, mobility, and lifestyle in early farmers',
    url: 'https://doi.org/10.1073/pnas.1904345116',
    publisher: 'Proceedings of the National Academy of Sciences',
    accessedOn: '2026-07-21',
    licenseOrUse: 'Peer-reviewed research citation; no burial imagery redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.milner-2019-commentary',
    title: 'Early agriculture’s toll on human health',
    url: 'https://doi.org/10.1073/pnas.1908960116',
    publisher: 'Proceedings of the National Academy of Sciences',
    accessedOn: '2026-07-21',
    licenseOrUse: 'Peer-reviewed commentary used as research reference; burial excavation imagery rejected for learner use',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.bogaard-2017-resilience',
    title: 'Agricultural innovation and resilience in a long-lived early farming community: the 1,500-year sequence at Neolithic to early Chalcolithic Çatalhöyük, central Anatolia',
    url: 'https://doi.org/10.1017/S0066154617000072',
    publisher: 'Anatolian Studies / Cambridge University Press',
    accessedOn: '2026-07-21',
    licenseOrUse: 'Peer-reviewed research citation; article media not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.britannica-aurochs',
    title: 'Aurochs',
    url: 'https://www.britannica.com/animal/aurochs',
    publisher: 'Encyclopaedia Britannica',
    accessedOn: '2026-10-03',
    licenseOrUse: 'Reference citation for a definition and a size; text not redistributed',
    reviewStatus: 'reviewed',
  },
];

export const farmingSettlementsClaims: Claim[] = [
  {
    id: 'claim.farming.case-not-global',
    statement: 'This lesson is a Southwest Asian case and does not establish a single worldwide origin of farming.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.baird-2018-anatolia', 'source.farming.unesco-catalhoyuk'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.farming.gradual-uptake',
    statement: 'In Central Anatolia, cultivation could be adopted at low intensity beside foraging for centuries, and nearby communities could differ in whether they cultivated.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.baird-2018-anatolia'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.farming.settlement-density',
    statement: 'Çatalhöyük East was a long-lived, densely packed settlement of conjoined mudbrick houses entered from roofs, without streets between houses.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.farming.unesco-catalhoyuk', 'source.farming.catalhoyuk-architecture', 'source.farming.baird-2018-anatolia'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.farming.catalhoyuk-location',
    statement: 'Çatalhöyük stands on the Konya plain of the Southern Anatolian Plateau in central Anatolia; UNESCO World Heritage coordinates place the site at about 37.667° N, 32.828° E.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.farming.unesco-catalhoyuk', 'source.farming.unesco-catalhoyuk-maps'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.farming.mixed-farming',
    statement: 'By the time of Çatalhöyük East, communities practiced substantial mixed farming of domesticated plants and animals that could sustain a large sedentary community.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.baird-2018-anatolia', 'source.farming.bogaard-2017-resilience', 'source.farming.larsen-2019-bioarch'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.farming.private-storage',
    statement: 'Households stored plant foods in interior bins and side rooms that functioned as private pantries.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.farming.bogaard-2009-pantries', 'source.farming.catalhoyuk-architecture'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.farming.shared-feasting',
    statement: 'Displays of aurochs heads or horns and related evidence point to shared feasting that could ease tensions created by private stores.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.farming.bogaard-2009-pantries'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.farming.tradeoffs',
    statement: 'Denser farming life brought labor demands, crowding-related disease exposure, and other biological stresses that varied across the occupation.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.farming.larsen-2019-bioarch', 'source.farming.milner-2019-commentary'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.farming.no-palace-equality',
    statement: 'Similar house sizes and lack of palaces do not prove perfect equality; private storage and social mechanisms already manage tension.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.farming.bogaard-2009-pantries', 'source.farming.unesco-catalhoyuk'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.farming.not-a-city',
    statement: 'Çatalhöyük’s household-centered dense settlement is not the same social scale as later cities such as Uruk.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.unesco-catalhoyuk', 'source.farming.catalhoyuk-architecture', 'source.farming.bogaard-2009-pantries'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.farming.roof-ladder-entry',
    statement: 'At Çatalhöyük people moved around on the roofs and entered each house down a wooden ladder through an opening in the ceiling.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.farming.catalhoyuk-architecture', 'source.farming.unesco-catalhoyuk'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.farming.neighbors-via-roof',
    statement: 'The journal summary of Bogaard et al. 2009 pictures neighbors as always in and out of each others’ houses, in this case by way of the roof; the summary presents this as an assumption, not a count.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.farming.bogaard-2009-pantries'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.farming.boncuklu-ancestral',
    statement: 'Baird et al. argue that the community at Boncuklu, which combined some cultivation and sheep and goat herding with foraging for several centuries, was ancestral to the much larger Çatalhöyük East, where from 7100 BCE a modest involvement with food production had become a major commitment to mixed farming; they conclude that adoption had significant long-term social consequences for the adopting community.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.farming.baird-2018-anatolia'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.farming.rebuilt-mounds',
    statement: 'Çatalhöyük houses were continually infilled, often burnt and rebuilt, and the settlement’s layers form two mounds rising up to 20 meters above the Konya plain.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.farming.catalhoyuk-architecture', 'source.farming.unesco-catalhoyuk'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.farming.bin-contents',
    statement: 'Families stored grain, fruit, nuts and condiments in bins deep inside the house, and displayed the heads and horns of aurochs near the entrance.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.farming.bogaard-2009-pantries'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.farming.aurochs',
    statement: 'The aurochs was an extinct wild ox from which cattle are probably descended; it stood about 1.8 meters (6 feet) high at the shoulder.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.farming.britannica-aurochs'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.farming.full-larder',
    statement: 'The journal summary of Bogaard et al. 2009 says the aurochs displays, besides a religious overtone, remembered feasts, “episodes of sharing that mitigated the provocations of a full larder.”',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.farming.bogaard-2009-pantries'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.farming.density-and-workload',
    statement: 'Larsen et al. found elevated exposure to disease and heavier labor demands at Çatalhöyük, tied to dependence on domesticated plant carbohydrates, a growing and denser population fueled by elevated fertility, and increasing stress from workload; Milner cautions that the pattern varied and should not be read as a one-direction decline.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.farming.larsen-2019-bioarch', 'source.farming.milner-2019-commentary'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.farming.long-occupation',
    statement: 'Çatalhöyük East was occupied from about 7100 to 5950 BCE, a little over a thousand years.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.farming.larsen-2019-bioarch', 'source.farming.bogaard-2017-resilience'],
    reviewStatus: 'editorial-review-required',
  },
];

export const farmingSettlementsMedia: MediaAsset[] = [
  {
    id: 'media.farming.catalhoyuk-rooftops',
    locator: mediaLocator('media.farming.catalhoyuk-rooftops'),
    alt: 'Evidence-based reconstruction looking across adjoining mudbrick rooftops at Çatalhöyük, with roof openings, ladders, household activity, and the dry Konya plain beyond',
    depictionMode: 'evidence-based-reconstruction',
    depictionLabel: 'Evidence-based reconstruction · exact people and moment are illustrative',
    rightsLabel: 'Chronos original reconstruction',
    sourceIds: ['source.farming.unesco-catalhoyuk', 'source.farming.catalhoyuk-architecture'],
    visualBriefRef: 'docs/research/farming-settlements-media.md#rooftop-settlement-hero',
    reviewStatus: 'approved',
  },
  {
    id: 'media.farming.catalhoyuk-house-diagram',
    locator: mediaLocator('media.farming.catalhoyuk-house-diagram'),
    alt: 'Axonometric cutaway of a Çatalhöyük mudbrick house showing the roof opening and ladder, main room, hearth and platforms, side-room storage bins, and an entrance-area animal display',
    depictionMode: 'diagram',
    depictionLabel: 'Evidence-led house diagram · excavated relationships with reconstructed surfaces',
    rightsLabel: 'Chronos original evidence diagram',
    sourceIds: ['source.farming.catalhoyuk-architecture', 'source.farming.bogaard-2009-pantries'],
    visualBriefRef: 'docs/research/farming-settlements-media.md#house-and-storage-evidence-view',
    reviewStatus: 'approved',
  },
  {
    id: 'media.farming.catalhoyuk-locator-map',
    locator: mediaLocator('media.farming.catalhoyuk-locator-map'),
    alt: 'Editorial locator map of Anatolia showing Çatalhöyük inland on the Konya plain of the Anatolian Plateau, between the Mediterranean Sea and the Black Sea',
    depictionMode: 'map',
    depictionLabel: 'Historical locator map · site coordinate verified, modern coasts for orientation',
    rightsLabel: 'Chronos original · Natural Earth base geography, Public Domain',
    sourceIds: [
      'source.farming.unesco-catalhoyuk',
      'source.farming.unesco-catalhoyuk-maps',
      'source.farming.natural-earth',
    ],
    visualBriefRef: 'docs/research/farming-catalhoyuk-locator-map.md#revision-2-visual-correction',
    reviewStatus: 'approved',
  },
  {
    id: 'media.farming.catalhoyuk-card',
    locator: mediaLocator('media.farming.catalhoyuk-card'),
    alt: 'Vertical evidence-based reconstruction of roof-connected mudbrick homes at Çatalhöyük with one roof opening and the Konya plain beyond',
    depictionMode: 'evidence-based-reconstruction',
    depictionLabel: 'Evidence-based reconstruction · settlement view',
    rightsLabel: 'Chronos original reconstruction',
    sourceIds: ['source.farming.unesco-catalhoyuk', 'source.farming.catalhoyuk-architecture'],
    visualBriefRef: 'docs/research/farming-settlements-media.md#catalhoyuk-card-artwork',
    reviewStatus: 'approved',
  },
];

export const farmingSettlementsPrompts: UnderstandingPrompt[] = [
  {
    id: 'prompt.farming.what-the-house-shows', bestOptionId: 'option.farming.own-stores-shared-meals',
    lessonId: 'lesson.farming.settlements',
    kind: 'supported-selection',
    question: 'Excavators found bins of grain, fruit and nuts in side rooms deep inside Çatalhöyük houses. Near the entrances they found the heads and horns of aurochs, and remains linked to feasting. Which statement fits these finds best?',
    hint: 'Think about where each find was located, deep inside the house or near the entrance. Who would see each one?',
    explanation: 'The bins deep inside the houses fit food kept by each household. The horns and feast remains near the entrances fit meals shared more widely. This is an interpretation, not a record: the finds do not show a ruler, equal households, or exactly who took part in a feast.',
    required: true,
    options: [
      {
        id: 'option.farming.own-stores-shared-meals',
        label: 'Each household kept its own food, and people also came together to share meals.', feedback: 'Yes. Bins deep inside the houses fit food kept by each household, and horns and feast remains near the entrances fit meals shared more widely.',
      },
      {
        id: 'option.farming.ruler-central-store',
        label: 'A ruler collected grain from the houses and kept it in one large central store.', feedback: 'Reread “Private stores and shared occasions.” Where were the bins found, and does that fit one central store?',
      },
      {
        id: 'option.farming.similar-households',
        label: 'The households had similar amounts of food and a similar place in the community.', feedback: 'Reread “Private stores and shared occasions.” Does the position of the bins tell us how much food each household had, or how people ranked?',
      },
      {
        id: 'option.farming.one-common-supply',
        label: 'People kept no food of their own, because the community shared a common supply.', feedback: 'Look at the first find again. If the community shared one supply, why would there be bins deep inside separate houses?',
      },
    ],
  },
  {
    id: 'prompt.farming.opportunity-and-cost',
    lessonId: 'lesson.farming.settlements',
    kind: 'concise-explanation',
    question: 'How could staying in one dense settlement create both an advantage and a problem? Use one detail from the houses, stored food, work, or health evidence.',
    hint: 'Look back at “The bargain of staying.” Pick one advantage and one problem, and say how they connect.',
    explanation: 'An explanation could link an advantage — food kept for later, sturdy homes, or nearby neighbors — to a problem such as repetitive work, crowding and illness, tension around private stores, or coordinating wall-to-wall households.',
    required: true,
    minimumResponseLength: 20,
  },
];

export const farmingSettlementsLesson: Lesson = {
  id: 'lesson.farming.settlements',
  legacyAliases: [],
  status: 'published',
  title: 'Farming and Settlements',
  masthead: 'c. 7100–6000 BCE',
  place: 'Çatalhöyük · Central Anatolia',
  chronology: {
    startYear: -7100,
    endYear: -6000,
    display: 'approximately 7100–6000 BCE',
    approximate: true,
  },
  significance: 'A roof-connected settlement shows how stored food changed both the chances — and the pressures — of staying in one place.',
  heroMediaId: 'media.farming.catalhoyuk-rooftops',
  heroLabel: 'Evidence-based reconstruction',
  heroCaption: 'Architecture follows excavated patterns; the people, weather, and exact moment are reconstructed.',
  sectionIdsRequired: [
    'section.farming.enter-from-roof',
    'section.farming.slow-change',
    'section.farming.wall-to-wall',
    'section.farming.read-the-house',
    'section.farming.private-and-shared',
    'section.farming.bargain-of-staying',
    'section.farming.check-and-complete',
  ],
  sections: [
    {
      id: 'section.farming.enter-from-roof',
      heading: 'Enter from the roof',
      purpose: 'Begin inside the practical shape of a wall-to-wall settlement',
      modules: [
        {
          id: 'module.farming.rooftop-opening',
          type: 'prose',
          body: 'Çatalhöyük had no streets. From about 7100 BCE, in what is now central Turkey, its mudbrick houses stood wall to wall, so people crossed the roofs to get around and climbed down a wooden ladder through an opening in the ceiling to go inside. A summary of one study of the settlement pictures neighbors “always in and out of each others’ houses,” in this case by way of the roof.\n\nThe opening picture is a reconstruction. The wall-to-wall plan and the roof openings follow what archaeologists dug up; the people, the weather and the moment are imagined. What the houses can tell us is how a community lived with food stored for later, in a place where people stayed for generations.\n\nÇatalhöyük is one case from central Anatolia, not the birthplace of farming for the whole world. Other communities, in other places and times, made different choices.',
          claimIds: ['claim.farming.settlement-density', 'claim.farming.roof-ladder-entry', 'claim.farming.neighbors-via-roof', 'claim.farming.case-not-global'],
          sourceIds: ['source.farming.unesco-catalhoyuk', 'source.farming.catalhoyuk-architecture', 'source.farming.bogaard-2009-pantries', 'source.farming.baird-2018-anatolia'],
        },
      ],
    },
    {
      id: 'section.farming.slow-change',
      heading: 'No single day changed everything',
      purpose: 'Show cultivation as a gradual and uneven regional process',
      modules: [
        {
          id: 'module.farming.slow-change',
          type: 'prose',
          body: 'Long before Çatalhöyük was crowded, foragers at a smaller settlement called Boncuklu tried something new. They began cultivating some plants and keeping a few sheep and goats, but they kept hunting and gathering too. Archaeologists found that this mixed way of getting food lasted for several centuries. It was not a quick step on the way to something bigger.\n\nNot everyone took it. At Pınarbaşı, in the same region, archaeologists found little or no sign of farming. The archaeologist Douglas Baird and his team conclude that some communities chose to disregard cultivation, so neighbors in the same landscape did not follow one timetable.\n\nBaird’s team argues that even Boncuklu’s small beginning had “significant long-term social consequences” for the people there. Their community, they think, was ancestral to the much larger settlement of Çatalhöyük East. By 7100 BCE, a modest involvement with farming had become a major commitment to mixed farming, enough to sustain a very large community that stayed in one place. Nobody flipped a switch. Centuries of small choices turned a side activity into something people depended on.',
          claimIds: ['claim.farming.gradual-uptake', 'claim.farming.boncuklu-ancestral', 'claim.farming.mixed-farming', 'claim.farming.case-not-global'],
          sourceIds: ['source.farming.baird-2018-anatolia', 'source.farming.bogaard-2017-resilience', 'source.farming.larsen-2019-bioarch'],
        },
      ],
    },
    {
      id: 'section.farming.wall-to-wall',
      heading: 'A neighborhood built wall to wall',
      purpose: 'Place Çatalhöyük and explain the settlement pattern',
      modules: [
        {
          id: 'module.farming.wall-to-wall',
          type: 'knowledge',
          eyebrow: 'Çatalhöyük East',
          title: 'Roofs, rebuilding, and food in one place',
          body: 'On the inland Konya plain, generations built new mudbrick rooms over older ones. Staying turned separate homes into a tightly connected settlement.',
          items: [
            { label: 'Roofs became routes', detail: 'With houses touching wall to wall, people crossed the roofs and climbed down ladders into the rooms below.' },
            { label: 'Homes piled up', detail: 'Houses were often burned or filled in and rebuilt on the same ground. The layers grew into mounds rising up to 20 meters above the plain, and archaeologists dig down through them.' },
            { label: 'Food anchored daily life', detail: 'Crops, herded animals, and gathered foods supported a community that remained large and settled.' },
          ],
          claimIds: ['claim.farming.settlement-density', 'claim.farming.roof-ladder-entry', 'claim.farming.rebuilt-mounds', 'claim.farming.mixed-farming'],
          sourceIds: [
            'source.farming.unesco-catalhoyuk',
            'source.farming.catalhoyuk-architecture',
            'source.farming.baird-2018-anatolia',
            'source.farming.bogaard-2017-resilience',
          ],
        },
        {
          id: 'module.farming.catalhoyuk-locator-map',
          type: 'historical-map',
          eyebrow: 'Place & landscape',
          title: 'Inland on the Konya plain',
          body: 'Çatalhöyük lies on the Anatolian Plateau, inland from both the Mediterranean and Black Seas. This map locates the settlement; it does not mark a single origin point for world farming.',
          mediaId: 'media.farming.catalhoyuk-locator-map',
          periodLabel: 'c. 7100–6000 BCE',
          focusPlace: 'Çatalhöyük',
          modernContext: 'Near Çumra / Konya, Türkiye',
          accessibleSummary: 'Çatalhöyük sits inland on the Konya plain of the Anatolian Plateau, between the Mediterranean Sea to the south and the Black Sea to the north. The map places this Southwest Asian settlement case; it does not show a worldwide origin of farming.',
          compactLabel: 'Site coordinate verified · modern coasts for orientation',
          coordinateNote: 'Çatalhöyük is placed using UNESCO World Heritage coordinates.',
          uncertaintyNote: 'Coastlines and plateau washes orient the learner; they are not a reconstruction of Neolithic shorelines or river channels.',
          depictionStatus: 'illustrative-reconstruction',
          claimIds: ['claim.farming.catalhoyuk-location', 'claim.farming.case-not-global', 'claim.farming.settlement-density'],
          sourceIds: [
            'source.farming.unesco-catalhoyuk',
            'source.farming.unesco-catalhoyuk-maps',
            'source.farming.natural-earth',
          ],
        },
      ],
    },
    {
      id: 'section.farming.read-the-house',
      heading: 'Read the house',
      purpose: 'Observe the spatial pattern before interpreting it',
      modules: [
        {
          id: 'module.farming.house-evidence',
          type: 'scene',
          title: 'Follow the evidence from roof to pantry',
          body: 'Start at the roof opening and work inward. This cutaway turns dug house plans into a view you can read. The room layout and bins follow the evidence. Colors, soft objects, and the exact moment are reconstructed.',
          mediaId: 'media.farming.catalhoyuk-house-diagram',
          hotspots: [
            { label: 'Roof opening', detail: 'A wooden ladder linked the roof path to the main room below.' },
            { label: 'Main room', detail: 'Hearths, ovens, and platforms held much of a household’s daily work and rest.' },
            { label: 'Side-room bins', detail: 'Bins for grain, fruit, nuts and condiments stood in a side room, deep inside the house. Together with plant remains, they are the evidence for household pantries.' },
            { label: 'Entrance-area display', detail: 'Heads and horns of aurochs, wild oxen about 1.8 meters tall at the shoulder, were displayed near the entrance. With feast remains, they support shared meals, though not every rule people followed.' },
          ],
          claimIds: ['claim.farming.private-storage', 'claim.farming.bin-contents', 'claim.farming.aurochs', 'claim.farming.shared-feasting', 'claim.farming.roof-ladder-entry', 'claim.farming.settlement-density'],
          sourceIds: ['source.farming.bogaard-2009-pantries', 'source.farming.catalhoyuk-architecture', 'source.farming.britannica-aurochs'],
        },
      ],
    },
    {
      id: 'section.farming.private-and-shared',
      heading: 'Private stores and shared occasions',
      purpose: 'Build a bounded interpretation from the observed house pattern',
      modules: [
        {
          id: 'module.farming.private-and-shared',
          type: 'prose',
          body: 'The strongest clue is where things sat. Bins for grain, fruit, nuts and condiments stood in side rooms deep inside the houses, and plant remains were concentrated there. Near the entrances the excavators found something else: the heads and horns of aurochs, and remains linked to feasting. Surplus, food kept for later, is never only a pile of grain. Someone grew it, processed it, stored it, and decided when to open it.\n\nIn a settlement where neighbors were a rooftop away, a full pantry could cause trouble. A summary of the study calls this “the provocations of a full larder,” and says the horns near the entrance helped. Besides their religious meaning, they remembered feasts, “episodes of sharing” that eased the tension. Private stores could keep a household safe. Shared meals could bind neighbors together, and could also show who had more.\n\nThis is a reading of the evidence, not a record of what happened. Similar house sizes and the lack of palaces do not prove that every household was equal; pantries and feasts are signs that people had to manage their differences. Nobody can say what the family rules were, who was invited to a feast, or what was said beside a bin. The bins survive; the conversations around them do not.',
          claimIds: ['claim.farming.private-storage', 'claim.farming.bin-contents', 'claim.farming.aurochs', 'claim.farming.shared-feasting', 'claim.farming.full-larder', 'claim.farming.neighbors-via-roof', 'claim.farming.no-palace-equality'],
          sourceIds: ['source.farming.bogaard-2009-pantries', 'source.farming.catalhoyuk-architecture', 'source.farming.unesco-catalhoyuk', 'source.farming.britannica-aurochs'],
        },
      ],
    },
    {
      id: 'section.farming.bargain-of-staying',
      heading: 'The bargain of staying',
      purpose: 'Hold security, labor, health, and social coordination together',
      modules: [
        {
          id: 'module.farming.bargain',
          type: 'knowledge',
          eyebrow: 'Tradeoffs',
          title: 'Food security, repeated work, health, and household scale',
          body: 'Staying was neither a simple upgrade nor a mistake. It joined new advantages to new work and risks, and those changed across Çatalhöyük’s long life.',
          items: [
            { label: 'Food for later', detail: 'Farming, herding, gathering, and storage helped households plan beyond the next day or season.' },
            { label: 'Work that repeated', detail: 'Fields, animals, fuel, plastered walls, food processing, and storage all needed steady labor.' },
            { label: 'Bodies close together', detail: 'Crowding, animals, waste, and diets heavy in carbs raised some health pressures — but not the same way for every person or century.' },
            { label: 'Household scale', detail: 'A large settlement could organize through homes and shared habits without becoming a city with palaces or written records.' },
          ],
          claimIds: ['claim.farming.tradeoffs', 'claim.farming.not-a-city', 'claim.farming.mixed-farming'],
          sourceIds: ['source.farming.larsen-2019-bioarch', 'source.farming.milner-2019-commentary', 'source.farming.bogaard-2009-pantries', 'source.farming.unesco-catalhoyuk'],
        },
        {
          id: 'module.farming.bargain-closing',
          type: 'prose',
          body: 'The skeletons add detail. The study that examined them found that as Çatalhöyük grew denser, people were exposed to more disease and had more work to do, and that the population was growing partly because more babies were being born. Other scholars warn against reading this as a simple story of farming making people sicker: the pressures changed over the centuries and did not fall the same way on everyone.\n\nSo the bargain was real. A household with a full larder had food for later, and neighbors a rooftop away. Çatalhöyük had no streets, no palace and no written records, yet people stayed there for a little over a thousand years. How they managed it, house by house, is what the bins and the horns still let us see.',
          claimIds: ['claim.farming.density-and-workload', 'claim.farming.tradeoffs', 'claim.farming.long-occupation', 'claim.farming.not-a-city'],
          sourceIds: ['source.farming.larsen-2019-bioarch', 'source.farming.milner-2019-commentary', 'source.farming.bogaard-2017-resilience', 'source.farming.unesco-catalhoyuk'],
        },
      ],
    },
    {
      id: 'section.farming.check-and-complete',
      heading: 'World Check',
      purpose: 'Interpret the house pattern and explain an advantage with a problem',
      modules: [
        {
          id: 'module.farming.prompt-house-pattern',
          type: 'prompt',
          promptId: 'prompt.farming.what-the-house-shows',
          claimIds: [],
          sourceIds: [],
        },
        {
          id: 'module.farming.prompt-tradeoff',
          type: 'prompt',
          promptId: 'prompt.farming.opportunity-and-cost',
          claimIds: [],
          sourceIds: [],
        },
      ],
    },
  ],
  claimIds: farmingSettlementsClaims.map((claim) => claim.id),
  sourceIds: farmingSettlementsSources.map((source) => source.id),
  mediaIds: [
    'media.farming.catalhoyuk-rooftops',
    'media.farming.catalhoyuk-house-diagram',
    'media.farming.catalhoyuk-locator-map',
    'media.farming.catalhoyuk-card',
  ],
  promptIds: [
    'prompt.farming.what-the-house-shows',
    'prompt.farming.opportunity-and-cost',
  ],
};

export const farmingSettlementsCards: KnowledgeCard[] = [
  {
    id: 'card.place.catalhoyuk',
    title: 'Çatalhöyük',
    category: 'place',
    cardClass: 'foundation',
    date: {
      startYear: -7100,
      endYear: -6000,
      display: 'c. 7100–6000 BCE',
      approximate: true,
    },
    place: 'Central Anatolia, Konya plain',
    significance: 'A dense, roof-connected farming settlement where house evidence reveals how stored food changed daily life.',
    revealTitle: 'A settlement with no streets',
    revealBody: 'A full larder deep inside the house, aurochs horns near the door, neighbors a rooftop away: you found Çatalhöyük by reading where things lay in its houses. It shows how stored food made staying possible, and made it complicated.',
    depictionLabel: 'Evidence-based reconstruction',
    facts: [
      'Long-lived Neolithic settlement on the Konya plain in central Anatolia',
      'Mudbrick houses touched wall to wall with no streets: people crossed the roofs and climbed down a ladder to go in',
      'Bins for grain, fruit, nuts and condiments stood in side rooms deep inside the houses',
      'Aurochs heads and horns near the entrances, with feast remains, point toward shared meals',
      'Houses were rebuilt on the same ground for generations, and the layers form mounds up to 20 meters high',
    ],
    lessonIds: ['lesson.farming.settlements'],
    sourceIds: [
      'source.farming.unesco-catalhoyuk',
      'source.farming.bogaard-2009-pantries',
      'source.farming.catalhoyuk-architecture',
    ],
    mediaId: 'media.farming.catalhoyuk-card',
    unlockLessonId: 'lesson.farming.settlements',
  },
];

export const farmingSettlementsContent: AuthoredContentModule = {
  sources: farmingSettlementsSources,
  claims: farmingSettlementsClaims,
  media: farmingSettlementsMedia,
  prompts: farmingSettlementsPrompts,
  lessons: [farmingSettlementsLesson],
  cards: farmingSettlementsCards,
};
