import type { KnowledgeCard, LessonModule, MediaAsset, Source } from '../../src/domains/contracts';
import { mediaLocator } from '../shared/media-locator';

const brief = 'docs/research/law-kingship-hammurabi-babylon.md#image-lifecycle';
export const hammurabiMediaSources: Source[] = [
  { id: 'source.hammurabi.map-relief', title: 'Natural Earth 1:50m hypsometric tints, shaded relief and water', url: 'https://www.naturalearthdata.com/downloads/50m-raster-data/50m-cross-blend-hypso/', publisher: 'Natural Earth contributors', accessedOn: '2026-10-04', licenseOrUse: 'Public domain. Reuse of the preserved source-faithful geographic crop at bounds 32–52 E, 27–42 N; exact original dataset and crop hashes in map/reference-lineage.json. Modern geography, not ancient shorelines.', reviewStatus: 'reviewed' },
  { id: 'source.hammurabi.map-rivers', title: 'Natural Earth 1:50m river centerlines, v5.1.2', url: 'https://www.naturalearthdata.com/downloads/50m-physical-vectors/50m-rivers-lake-centerlines/', publisher: 'Natural Earth contributors', accessedOn: '2026-10-04', licenseOrUse: 'Public domain generalized modern Tigris/Euphrates/Shatt al Arab geometry. Preserved reviewed segments and hashes in the lifecycle; no ancient channel reconstruction.', reviewStatus: 'reviewed' },
  { id: 'source.hammurabi.map-land', title: 'Natural Earth 1:110m land, v5.1.2', url: 'https://www.naturalearthdata.com/downloads/110m-physical-vectors/110m-land/', publisher: 'Natural Earth contributors', accessedOn: '2026-10-04', licenseOrUse: 'Public domain polygons for the wider-world inset. Projection, view rectangle and data hash recorded; no political borders.', reviewStatus: 'reviewed' },
  { id: 'source.hammurabi.map-babylon', title: 'Babili / Babylon place record', url: 'https://oracc.museum.upenn.edu/geonames/cbd/qpn/x000000440.html', publisher: 'Oracc / Pleiades', accessedOn: '2026-10-04', licenseOrUse: 'Representative site coordinates [44.422236,32.543395], checked against UNESCO nomination center [44.420833,32.541969]. Factual point only; not settlement extent. Local source HTML preserved.', reviewStatus: 'reviewed' },
  { id: 'source.hammurabi.map-larsa', title: 'Larsa / Tell as-Senkereh place record', url: 'https://oracc.museum.upenn.edu/geonames/cbd/qpn/x000001820.html', publisher: 'Oracc / Pleiades', accessedOn: '2026-10-04', licenseOrUse: 'Representative site coordinates [45.853611,31.285833]. Factual point only; French excavation account independently places Larsa in the lower Mesopotamian plain. Local source HTML preserved.', reviewStatus: 'reviewed' },
  { id: 'source.hammurabi.map-unesco', title: 'Babylon nomination: geographical coordinates', url: 'https://whc.unesco.org/document/166322', publisher: 'UNESCO World Heritage Centre / Republic of Iraq', accessedOn: '2026-10-04', licenseOrUse: 'Page 11 geographic center used as an independent factual cross-check, not a copied site plan or depiction of Hammurabi-period architecture.', reviewStatus: 'reviewed' },
  { id: 'source.hammurabi.map-excavation', title: 'Larsa: Les grandes maisons paléo-babyloniennes', url: 'https://archeologie.culture.gouv.fr/larsa/fr/les-grandes-maisons-paleo-babyloniennes', publisher: 'French archaeological mission / Ministry of Culture', accessedOn: '2026-10-04', licenseOrUse: 'Opening location paragraph independently confirms Larsa’s lower Mesopotamian setting between the rivers; no images copied.', reviewStatus: 'reviewed' },
  { id: 'source.hammurabi.stele-photo', title: 'Hammurabi law stele, Louvre SB 8 — full-object photograph', url: 'https://commons.wikimedia.org/wiki/File:Code_of_Hammurabi,_King_of_Babylon,_Basalt,_1792-1750_BC_(28296727785).jpg', publisher: 'Gary Todd / Wikimedia Commons', accessedOn: '2026-10-04', licenseOrUse: 'Gary Todd, 2016-07-13. CC0 1.0, https://creativecommons.org/publicdomain/zero/1.0/. Original Flickr license confirmed by Commons review. Full frame resized to 960×1440 and JPEG compressed; no retouching or reconstruction. Object identity checked against Louvre SB 8.', reviewStatus: 'reviewed' },
];
const mapSources = hammurabiMediaSources.filter(source => source.id !== 'source.hammurabi.stele-photo').map(source => source.id);
export const hammurabiMedia: MediaAsset[] = [
  { id: 'media.hammurabi.locator', locator: mediaLocator('media.hammurabi.locator'), alt: 'A West Asia locator places Babylon northwest of Larsa in present-day Iraq. Modern Tigris and Euphrates courses run through the region between the Mediterranean and Persian Gulf. An inset places the enlarged view beside Africa; its rectangle is the view extent, not territory.', depictionMode: 'map', depictionLabel: 'Illustrated locator · modern geography', rightsLabel: 'Chronos deterministic map · Natural Earth, Public Domain · site points from Oracc/Pleiades', sourceIds: mapSources, visualBriefRef: brief, reviewStatus: 'approved' },
  { id: 'media.hammurabi.law-stele', locator: mediaLocator('media.hammurabi.law-stele'), alt: 'The tall dark law stele stands in a modern Louvre gallery. At its rounded top a standing Hammurabi faces seated Shamash; many rows of cuneiform continue down the stone below the relief.', depictionMode: 'evidence', depictionLabel: 'Surviving law stele · modern museum photograph', rightsLabel: 'Gary Todd · 2016 · CC0 1.0 · full frame resized and compressed', sourceIds: ['source.hammurabi.stele-photo', 'source.hammurabi.louvre-object'], visualBriefRef: brief, reviewStatus: 'approved' },
];
export const hammurabiLocatorVisual: LessonModule = {
  id: 'module.hammurabi.locator', type: 'historical-map', eyebrow: 'Place & landscape', title: 'Babylon and Larsa', body: 'Babylon lay northwest of Larsa in the lower Mesopotamian plain. Their positions help us follow the rivalry between Babylon’s smaller kingdom and Rim-Sin’s power farther south.',
  mediaId: 'media.hammurabi.locator', periodLabel: 'Eighteenth century BCE', focusPlace: 'Babylon and Larsa', modernContext: 'These cities were in West Asia, in present-day Iraq, east of the Mediterranean Sea. The inset places this region beside northern Africa.',
  accessibleSummary: 'Babylon is northwest of Larsa in present-day Iraq. The Mediterranean is west of the cities and the Persian Gulf lies southeast. The Tigris and Euphrates run through the region. An inset shows the location within West Asia next to Africa; its rectangle marks the main map’s view.',
  compactLabel: 'Modern geography · representative site points · no empire boundary',
  coordinateNote: 'Natural Earth relief, rivers and land; Oracc/Pleiades site points, cross-checked with UNESCO for Babylon and the French Larsa excavation account. Dots locate sites, not their territories.',
  uncertaintyNote: 'The rivers and coast shown are modern orientation. Channels and shorelines changed in antiquity; this map does not reconstruct them or the kingdom’s borders.',
  depictionStatus: 'illustrative-reconstruction', claimIds: ['claim.hammurabi.babylon-location', 'claim.hammurabi.site-orientation'], sourceIds: mapSources,
};
export const hammurabiSteleVisual: LessonModule = {
  id: 'module.hammurabi.stele-evidence', type: 'evidence', title: 'The relief and the long inscription', artifactLabel: 'Law stele of Hammurabi · Louvre SB 8', body: 'Look at the two figures near the top, then follow the rows of writing below them. The carved royal scene occupies only part of a monument filled with legal cases.',
  mediaId: 'media.hammurabi.law-stele', layout: 'side-by-side', scaleNote: 'The basalt stele is about 2.25 meters tall. This photograph shows the surviving object in a modern museum gallery; the background is not ancient Babylon.',
  claimIds: ['claim.hammurabi.stele-object', 'claim.hammurabi.royal-justice'], sourceIds: ['source.hammurabi.louvre-object', 'source.hammurabi.stele-photo', 'source.hammurabi.cdli-stele'],
};
export const hammurabiSteleCard: KnowledgeCard = {
  id: 'card.hammurabi.law-stele', title: 'Hammurabi’s Law Stele', category: 'artifact', cardClass: 'witness',
  date: { startYear: -1800, endYear: -1700, display: 'Eighteenth century BCE', approximate: true }, place: 'Babylonia · now in the Louvre',
  significance: 'A stone taller than an adult, filled with cases about work, property and people’s obligations.',
  revealTitle: 'A kingdom’s problems, carved in stone', revealBody: 'Below Hammurabi and Shamash, long rows of cuneiform describe legal cases: a failed harvest, a flooded field, property handed over for safekeeping. This great surviving monument brings the practical work of Babylonian law into view.',
  depictionLabel: 'Surviving law stele · modern museum photograph',
  facts: ['The basalt stone is about 2.25 meters tall.', 'The relief shows Hammurabi standing before Shamash.', 'Many provisions describe a situation and then state a response.', 'The cases address subjects including farming, property, trade and households.'],
  lessonIds: ['lesson.mesopotamia.law-and-kingship'], sourceIds: ['source.hammurabi.louvre-object', 'source.hammurabi.louvre-essay', 'source.hammurabi.avalon-cases', 'source.hammurabi.stele-photo'], mediaId: 'media.hammurabi.law-stele', unlockLessonId: 'lesson.mesopotamia.law-and-kingship', recallPrompt: 'How did one legal case connect a practical problem to a responsibility or remedy?',
};

