import type { Claim, KnowledgeCard, Lesson, MediaAsset, Source, UnderstandingPrompt } from '../../src/domains/contracts';
import type { AuthoredContentModule } from '../assemble';
import { mediaLocator } from '../shared/media-locator';

export const homoSapiensOriginsSources: Source[] = [
  {
    id: 'source.humans.hublin-2017-irhoud',
    title: 'New fossils from Jebel Irhoud, Morocco and the pan-African origin of Homo sapiens',
    url: 'https://doi.org/10.1038/nature22336',
    publisher: 'Nature',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Peer-reviewed excavation report cited as a fact source; article figures not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.richter-2017-irhoud-age',
    title: 'The age of the hominin fossils from Jebel Irhoud, Morocco, and the origins of the Middle Stone Age',
    url: 'https://doi.org/10.1038/nature22335',
    publisher: 'Nature',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Peer-reviewed geochronology cited as a fact source; article figures not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.vidal-2022-omo',
    title: 'Age of the oldest known Homo sapiens from eastern Africa',
    url: 'https://doi.org/10.1038/s41586-021-04275-8',
    publisher: 'Nature',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Open-access peer-reviewed geochronology cited as a fact source',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.scerri-2018-subdivided',
    title: 'Did Our Species Evolve in Subdivided Populations across Africa, and Why Does It Matter?',
    url: 'https://doi.org/10.1016/j.tree.2018.05.005',
    publisher: 'Trends in Ecology & Evolution',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Peer-reviewed multi-disciplinary synthesis cited as a fact source; figures not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.bergstrom-2021-ancestry',
    title: 'Origins of modern human ancestry',
    url: 'https://doi.org/10.1038/s41586-021-03244-5',
    publisher: 'Nature',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Peer-reviewed review cited as a fact source; figures not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.ragsdale-2023-stem',
    title: 'A weakly structured stem for human origins in Africa',
    url: 'https://doi.org/10.1038/s41586-023-06055-y',
    publisher: 'Nature',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Open-access peer-reviewed population-genetic modelling cited as a fact source',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.brooks-2018-olorgesailie',
    title: 'Long-distance stone transport and pigment use in the earliest Middle Stone Age',
    url: 'https://doi.org/10.1126/science.aao2646',
    publisher: 'Science',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Peer-reviewed excavation report cited as a fact source; figures not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.potts-2020-variability',
    title: 'Increased ecological resource variability during a critical transition in hominin evolution',
    url: 'https://doi.org/10.1126/sciadv.abc8975',
    publisher: 'Science Advances',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Open-access peer-reviewed research cited as a fact and coordinate source',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.white-2003-herto',
    title: 'Pleistocene Homo sapiens from Middle Awash, Ethiopia',
    url: 'https://doi.org/10.1038/nature01669',
    publisher: 'Nature',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Peer-reviewed species description cited as a fact and coordinate source; figures not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.grun-1996-florisbad',
    title: 'Direct dating of Florisbad hominid',
    url: 'https://doi.org/10.1038/382500a0',
    publisher: 'Nature',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Peer-reviewed dating study cited as a fact source; figures not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.douglas-2009-florisbad',
    title: 'A new perspective on the geohydrological and surface processes controlling the depositional environment at the Florisbad archaeozoological site',
    url: 'https://scholar.ufs.ac.za/server/api/core/bitstreams/0c41f0d2-54bc-4e4e-9b42-1d02c99f7697/content',
    publisher: 'University of the Free State',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Open-access institutional thesis deposit used for surveyed site coordinates only',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.benncer-2023-irhoud',
    title: 'Jebel Irhoud (Ighoud), Morocco',
    url: 'https://link.springer.com/chapter/10.1007/978-3-031-20290-2_51',
    publisher: 'Springer, Handbook of Pleistocene Archaeology of Africa',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Excavation-team gazetteer entry used for the published site coordinate; chapter text not reproduced',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.roceeh-road',
    title: 'ROAD (ROCEEH Out of Africa Database) — Africa localities',
    url: 'https://www.roceeh.uni-tuebingen.de/api/Africa-localities-lithics-hominins-paleofauna-120ka-1800ka.php',
    publisher: 'Heidelberg Academy of Sciences and Humanities / University of Tübingen',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Curated academic locality database used only to cross-check coordinates, never as sole authority',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.grun-2020-kabwe',
    title: 'Dating the skull from Broken Hill, Zambia, and its position in human evolution',
    url: 'https://doi.org/10.1038/s41586-020-2165-4',
    publisher: 'Nature',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Peer-reviewed dating study cited as a fact source; figures not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.neubauer-2018-brain-shape',
    title: 'The evolution of modern human brain shape',
    url: 'https://doi.org/10.1126/sciadv.aao5961',
    publisher: 'Science Advances',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Open-access peer-reviewed morphometric study cited as a fact source',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.stringer-2016-origin',
    title: 'The origin and evolution of Homo sapiens',
    url: 'https://doi.org/10.1098/rstb.2015.0237',
    publisher: 'Philosophical Transactions of the Royal Society B',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Peer-reviewed synthesis cited as a fact source; figures not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.smithsonian-homo-sapiens',
    title: 'Homo sapiens — Human Origins Program',
    url: 'https://humanorigins.si.edu/evidence/human-fossils/species/homo-sapiens',
    publisher: 'Smithsonian Institution',
    accessedOn: '2026-07-26',
    licenseOrUse: 'National museum public science reference used for framing; museum imagery not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.nhm-modern-humans',
    title: 'Modern humans, Homo sapiens: When, where and how did we evolve?',
    url: 'https://www.nhm.ac.uk/discover/modern-humans-homo-sapiens-when-where-how-did-we-evolve.html',
    publisher: 'Natural History Museum, London',
    accessedOn: '2026-07-26',
    licenseOrUse: 'National museum public science reference used for framing; museum imagery not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.mpi-irhoud-presskit',
    title: 'The first of our kind — Jebel Irhoud press materials',
    url: 'https://www.eva.mpg.de/press/news/2017/2017-06-07-the-first-of-our-kind/',
    publisher: 'Max Planck Institute for Evolutionary Anthropology',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Press images released under CC BY-SA 2.0; reused with credit and share-alike, including as references for an adapted reconstruction',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.geraads-2013-irhoud-paleoenvironment',
    title: "The rodents from the late middle Pleistocene hominid-bearing site of J'bel Irhoud, Morocco, and their chronological and paleoenvironmental implications",
    url: 'https://doi.org/10.1016/j.yqres.2013.08.003',
    publisher: 'Quaternary Research',
    accessedOn: '2026-09-02',
    licenseOrUse: 'Peer-reviewed palaeoenvironmental analysis cited for the open-landscape reconstruction; article figures not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.natural-earth',
    title: 'Natural Earth',
    url: 'https://www.naturalearthdata.com/',
    publisher: 'Natural Earth',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Public Domain geographic base used for modern coast and landmass orientation only',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.wong-2017-sciam',
    title: 'Ancient Fossils from Morocco Mess Up Modern Human Origins',
    url: 'https://www.scientificamerican.com/article/ancient-fossils-from-morocco-mess-up-modern-human-origins/',
    publisher: 'Kate Wong, Scientific American (8 June 2017)',
    accessedOn: '2026-09-24',
    licenseOrUse: 'Science journalism cited for the history of the Jebel Irhoud finds (1961 barite mining, first reading as c. 40,000-year-old African Neanderthals, redating to c. 160,000 years, new fossils from an undisturbed part of the site); no quotation or image reuse',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.smithsonian-omo-i',
    title: 'Omo I',
    url: 'https://humanorigins.si.edu/evidence/human-fossils/fossils/omo-i',
    publisher: 'Smithsonian Institution Human Origins Program',
    accessedOn: '2026-09-24',
    licenseOrUse: 'National museum fossil record cited for the 1967 discovery by a team led by Richard Leakey and the earlier c. 130,000 and c. 195,000-year age estimates; its 195,000 figure is superseded by Vidal et al. 2022; images not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.si-olorgesailie-2018',
    title: 'Scientists Discover Evidence of Early Human Innovation, Pushing Back Evolutionary Timeline',
    url: 'https://www.si.edu/newsdesk/releases/scientists-discover-evidence-early-human-innovation-pushing-back-evolutionary-timeline',
    publisher: 'Smithsonian Institution newsdesk (15 March 2018)',
    accessedOn: '2026-09-24',
    licenseOrUse: 'Excavating institution’s release cited for the long use of handaxes at Olorgesailie, the smaller and more carefully shaped tools that followed, obsidian sources in multiple directions, and processed black and red rock (manganese and ochre); images not redistributed',
    reviewStatus: 'reviewed',
  },
];

export const homoSapiensOriginsClaims: Claim[] = [
  {
    id: 'claim.humans.african-origin',
    statement: 'All people alive today trace their ancestry to populations that lived in Africa; the oldest fossils of our species and the deepest genetic diversity are both found there.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: [
      'source.humans.nhm-modern-humans',
      'source.humans.smithsonian-homo-sapiens',
      'source.humans.bergstrom-2021-ancestry',
      'source.humans.ragsdale-2023-stem',
    ],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.irhoud-age',
    statement: 'Burnt stone tools found with the Jebel Irhoud fossils in Morocco date to about 315,000 years ago (315 ± 34 ka).',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.humans.richter-2017-irhoud-age', 'source.humans.hublin-2017-irhoud'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.irhoud-mosaic',
    statement: 'The Jebel Irhoud fossils combine a face and jaw close to those of people today with a long, low braincase resembling earlier humans.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: [
      'source.humans.hublin-2017-irhoud',
      'source.humans.smithsonian-homo-sapiens',
      'source.humans.nhm-modern-humans',
    ],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.braincase-later',
    statement: 'The rounded braincase typical of people today developed later within the Homo sapiens lineage rather than being present from its start.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: [
      'source.humans.neubauer-2018-brain-shape',
      'source.humans.hublin-2017-irhoud',
      'source.humans.scerri-2018-subdivided',
    ],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.sites-spread',
    statement: 'Fossils assigned to early Homo sapiens come from northern, eastern, and southern Africa: Jebel Irhoud about 315,000 years ago, Florisbad about 259,000, Omo Kibish at least 233,000, and Herto about 160,000.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: [
      'source.humans.hublin-2017-irhoud',
      'source.humans.grun-1996-florisbad',
      'source.humans.vidal-2022-omo',
      'source.humans.white-2003-herto',
      'source.humans.scerri-2018-subdivided',
    ],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.omo-minimum-age',
    statement: 'Volcanic ash lying above the Omo I fossil has been matched to an eruption dated to 233,000 ± 22,000 years ago, so the fossil must be at least that old.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.humans.vidal-2022-omo'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.no-single-birthplace',
    statement: 'No single time and place can currently be identified at which our species\u2019 ancestry was confined to one small region.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: [
      'source.humans.bergstrom-2021-ancestry',
      'source.humans.scerri-2018-subdivided',
      'source.humans.nhm-modern-humans',
    ],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.structured-populations',
    statement: 'The evidence fits our species emerging among populations spread across Africa that were sometimes separated and sometimes in contact, rather than descending from one isolated group.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: [
      'source.humans.scerri-2018-subdivided',
      'source.humans.bergstrom-2021-ancestry',
      'source.humans.ragsdale-2023-stem',
    ],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.not-a-ladder',
    statement: 'Early Homo sapiens fossils do not form a simple line from primitive to modern; different combinations of traits appear at different times and places.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: [
      'source.humans.scerri-2018-subdivided',
      'source.humans.stringer-2016-origin',
      'source.humans.hublin-2017-irhoud',
    ],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.msa-broadly-contemporary',
    statement: 'A shift to Middle Stone Age toolmaking appears in widely separated parts of Africa at broadly similar times around 300,000 years ago.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: [
      'source.humans.scerri-2018-subdivided',
      'source.humans.brooks-2018-olorgesailie',
      'source.humans.richter-2017-irhoud-age',
    ],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.olorgesailie-networks',
    statement: 'At Olorgesailie in southern Kenya, between about 320,000 and 305,000 years ago, people made prepared cores and points, processed iron-rich rock for red pigment, and obtained obsidian from sources 25 to 95 km away.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.humans.brooks-2018-olorgesailie', 'source.humans.potts-2020-variability'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.transport-implies-connection',
    statement: 'Moving stone that far implies wider ranging or exchange between groups than the 5 km or less typical of earlier Acheulean toolmaking.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.humans.brooks-2018-olorgesailie', 'source.humans.potts-2020-variability'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.climate-structure',
    statement: 'Shifting African climate repeatedly expanded and contracted deserts, forests, and grasslands, which could separate populations for long periods and later reconnect them.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.humans.scerri-2018-subdivided', 'source.humans.potts-2020-variability'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.dna-weak-structure',
    statement: 'Modelling the DNA of living African populations fits best with two or more weakly different ancestral populations linked by gene flow over hundreds of thousands of years.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.humans.ragsdale-2023-stem'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.humans-99-9-alike',
    statement: 'The DNA of all people living today is about 99.9% alike.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.humans.smithsonian-homo-sapiens'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.other-hominins',
    statement: 'Other kinds of humans lived in Africa during the same period, including Homo naledi (c. 335,000–236,000 years ago) and the Kabwe individual (c. 299,000 years ago).',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.humans.scerri-2018-subdivided', 'source.humans.grun-2020-kabwe'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.record-sparse',
    statement: 'The African fossil record for this period is thin and unevenly sampled, and large regions including West and Central Africa remain poorly investigated.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: [
      'source.humans.scerri-2018-subdivided',
      'source.humans.bergstrom-2021-ancestry',
      'source.humans.ragsdale-2023-stem',
    ],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.adna-limits',
    statement: 'No DNA has been recovered from African human fossils this old, because warm and humid conditions destroy it, so genetic conclusions about this period come from the DNA of living people and much younger remains.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.humans.scerri-2018-subdivided', 'source.humans.bergstrom-2021-ancestry'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.species-boundary-contested',
    statement: 'Researchers disagree about which fossils should count as Homo sapiens; some place Jebel Irhoud and Florisbad in a different species.',
    kind: 'interpretation',
    certainty: 'contested',
    sourceIds: ['source.humans.scerri-2018-subdivided', 'source.humans.stringer-2016-origin'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.map-points-are-areas',
    statement: 'Map points mark the areas where evidence was found rather than exact spots; Olorgesailie is a basin roughly the size of a small county, and only the Herto fossil has a published GPS fix on its find spot.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: [
      'source.humans.potts-2020-variability',
      'source.humans.white-2003-herto',
      'source.humans.roceeh-road',
      'source.humans.benncer-2023-irhoud',
      'source.humans.douglas-2009-florisbad',
    ],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.irhoud-was-a-cave',
    statement: 'The Jebel Irhoud deposits were inside a cave when people used the site; twentieth-century mining removed the covering rock and much of the sediment, leaving the open face visible today.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.humans.mpi-irhoud-presskit', 'source.humans.hublin-2017-irhoud'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.irhoud-first-reading',
    statement: 'Miners digging for barite at Jebel Irhoud found a human skull in 1961; the fossils were first thought to be African Neanderthals about 40,000 years old, were later redated to roughly 160,000 years, and new fossils were later excavated from a part of the site the miners had not disturbed.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.humans.wong-2017-sciam'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.kabwe-site-lost',
    statement: 'The Kabwe (Broken Hill) cranium was recovered from cave deposits during metal-ore mining in 1921, and the original site has since been completely quarried away.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.humans.grun-2020-kabwe'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.omo-age-history',
    statement: 'The Omo I fossil was found in 1967 by a team led by Richard Leakey; it was first thought to be about 130,000 years old, and redating of its sediments in 2008 gave about 195,000 years.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.humans.smithsonian-omo-i', 'source.humans.vidal-2022-omo'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.omo-ash-match',
    statement: 'The ash layer above Omo I is a more-than-2-m-thick deposit of fine ash too fine-grained to date directly; the chemistry of its glass matches the products of a major explosive eruption of Shala volcano, about 350 km to the northeast, whose deposits near the volcano were dated instead.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.humans.vidal-2022-omo'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.olorgesailie-change',
    statement: 'People at Olorgesailie made large handaxes for hundreds of thousands of years before smaller, more carefully shaped tools appear there about 320,000–305,000 years ago; the obsidian came from sources in several directions, and black and red rocks (manganese and ochre) were processed as colouring material.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.humans.si-olorgesailie-2018', 'source.humans.brooks-2018-olorgesailie'],
    reviewStatus: 'editorial-review-required',
  },
];

export const homoSapiensOriginsMedia: MediaAsset[] = [
  {
    id: 'media.humans.jebel-irhoud-landscape-reconstruction',
    locator: mediaLocator('media.humans.jebel-irhoud-landscape-reconstruction'),
    alt: 'Wide reconstruction of the Jebel Irhoud ridge at dawn, with golden-green open grassland, a shadowed cave in the limestone slope, and six tiny backlit human silhouettes near the cave and overlook',
    depictionMode: 'evidence-based-reconstruction',
    depictionLabel: 'Evidence-based reconstruction · Jebel Irhoud, about 315,000 years ago',
    rightsLabel: 'Chronos reconstruction · based on Shannon McPherron / MPI EVA Leipzig references, CC BY-SA 2.0',
    sourceIds: [
      'source.humans.mpi-irhoud-presskit',
      'source.humans.hublin-2017-irhoud',
      'source.humans.geraads-2013-irhoud-paleoenvironment',
    ],
    visualBriefRef: 'docs/research/homo-sapiens-origins.md#mediahumansjebel-irhoud-landscape-reconstruction--lesson-hero',
    reviewStatus: 'approved',
  },
  {
    id: 'media.humans.jebel-irhoud-excavation',
    locator: mediaLocator('media.humans.jebel-irhoud-excavation'),
    alt: 'Wide photograph of the Jebel Irhoud site in Morocco looking south: a bare limestone hillside cut into an open face, with excavators and equipment small in the centre and dry plains stretching to the horizon',
    depictionMode: 'evidence',
    depictionLabel: 'Excavation photograph · Jebel Irhoud, Morocco',
    rightsLabel: 'Shannon McPherron, MPI EVA Leipzig · CC BY-SA 2.0 · resized',
    sourceIds: ['source.humans.mpi-irhoud-presskit', 'source.humans.hublin-2017-irhoud'],
    visualBriefRef: 'docs/research/homo-sapiens-origins.md#hero-jebel-irhoud-site-photograph',
    reviewStatus: 'approved',
  },
  {
    id: 'media.humans.jebel-irhoud-cranium',
    locator: mediaLocator('media.humans.jebel-irhoud-cranium'),
    alt: 'Two views of a reconstructed skull. On the left, a three-quarter view showing a small flat face tucked beneath a long, low braincase. On the right, the same skull in profile with the space inside the braincase filled by a blue shape that is long and low from front to back rather than round.',
    depictionMode: 'evidence-based-reconstruction',
    depictionLabel: 'Composite reconstruction from micro-CT scans of several original fossils; the blue shape is a virtual cast of the braincase interior',
    rightsLabel: 'Philipp Gunz, MPI EVA Leipzig · CC BY-SA 2.0 · resized',
    sourceIds: [
      'source.humans.mpi-irhoud-presskit',
      'source.humans.hublin-2017-irhoud',
      'source.humans.neubauer-2018-brain-shape',
    ],
    visualBriefRef: 'docs/research/homo-sapiens-origins.md#evidence-encounter-jebel-irhoud-cranium',
    reviewStatus: 'approved',
  },
  {
    id: 'media.humans.jebel-irhoud-tools',
    locator: mediaLocator('media.humans.jebel-irhoud-tools'),
    alt: 'Fourteen stone tools from Jebel Irhoud photographed against black and arranged in rows, most of them pointed and shaped along both edges, in brown, grey, and honey-coloured flint, with a one-centimetre scale bar showing that the largest are roughly the length of a thumb',
    depictionMode: 'evidence',
    depictionLabel: 'Excavated artefacts photographed with a 1 cm scale bar',
    rightsLabel: 'Mohammed Kamal, MPI EVA Leipzig · CC BY-SA 2.0 · converted and resized',
    sourceIds: [
      'source.humans.mpi-irhoud-presskit',
      'source.humans.richter-2017-irhoud-age',
      'source.humans.hublin-2017-irhoud',
    ],
    visualBriefRef: 'docs/research/homo-sapiens-origins.md#middle-stone-age-toolkit-plate',
    reviewStatus: 'approved',
  },
  {
    id: 'media.humans.africa-evidence-map',
    locator: mediaLocator('media.humans.africa-evidence-map'),
    alt: 'Map of Africa with five marked sites: Jebel Irhoud in the far northwest of Morocco, Florisbad in South Africa near the southern end of the continent, and Omo Kibish, Herto, and Olorgesailie clustered in eastern Africa near the equator. Each marker carries the site name and its date. Olorgesailie and Omo Kibish have wider, softer halos than the others.',
    depictionMode: 'map',
    depictionLabel: 'Evidence locations · coordinates verified per site, modern coasts for orientation',
    rightsLabel: 'Chronos original · Natural Earth base geography, Public Domain',
    sourceIds: [
      'source.humans.natural-earth',
      'source.humans.benncer-2023-irhoud',
      'source.humans.white-2003-herto',
      'source.humans.douglas-2009-florisbad',
      'source.humans.potts-2020-variability',
      'source.humans.roceeh-road',
    ],
    visualBriefRef: 'docs/research/homo-sapiens-origins.md#africa-evidence-map',
    reviewStatus: 'approved',
  },
  {
    id: 'media.humans.africa-origins-card',
    locator: mediaLocator('media.humans.africa-origins-card'),
    alt: 'Simplified map of Africa on aged paper with five glowing markers spread from Morocco in the northwest to South Africa in the south and a cluster in eastern Africa, with no text labels',
    depictionMode: 'map',
    depictionLabel: 'Evidence locations · modern coasts for orientation',
    rightsLabel: 'Chronos original · Natural Earth base geography, Public Domain',
    sourceIds: [
      'source.humans.natural-earth',
      'source.humans.benncer-2023-irhoud',
      'source.humans.white-2003-herto',
      'source.humans.douglas-2009-florisbad',
      'source.humans.potts-2020-variability',
    ],
    visualBriefRef: 'docs/research/homo-sapiens-origins.md#knowledge-card-artwork',
    reviewStatus: 'approved',
  },
];

export const homoSapiensOriginsPrompts: UnderstandingPrompt[] = [
  {
    id: 'prompt.humans.best-supported-conclusion', bestOptionId: 'option.humans.connected-populations',
    lessonId: 'lesson.humans.homo-sapiens-origins',
    kind: 'supported-selection',
    hint: 'Compare the spread of the finds. Does the oldest find prove where the first people lived?',
    evidenceModuleIds: ['module.humans.africa-evidence-map'],
    question: 'Fossils of early Homo sapiens have been found in Morocco from about 315,000 years ago, in South Africa from about 259,000 years ago, and in Ethiopia from at least 233,000 years ago. They are thousands of kilometres apart, and they do not all share the same mix of features. Which conclusion does this set of finds best support?',
    explanation: 'The finds are spread across Africa, cover more than 150,000 years and mix features in different ways, which fits groups that were sometimes apart and sometimes in contact. One valley cannot explain finds that far apart. Different mixes of features do not make separate species either, because these groups kept exchanging genes. And “oldest known” is not the same as “first”: Jebel Irhoud is only the oldest evidence found so far, and it turned up by accident in a mine. The next dig could be older and somewhere else. This evidence rules out a simple one-place story without swapping in a different single place.',
    required: true,
    options: [
      {
        id: 'option.humans.connected-populations',
        feedback: 'The spread and different mixes of features fit connected populations across Africa. That does not identify one exact birthplace.',
        label: 'Our species took shape among populations living in many parts of Africa that were sometimes separated and sometimes in contact.',
      },
      {
        id: 'option.humans.one-valley',
        feedback: 'A single eastern valley does not account for this spread of finds. Compare Morocco and South Africa as well as Ethiopia.',
        label: 'Our species began in one valley in eastern Africa and spread out from there.',
      },
      {
        id: 'option.humans.separate-species',
        feedback: 'Different mixes of features alone do not establish separate species. This lesson also considers evidence for contact between populations.',
        label: 'Each region of Africa evolved its own separate human species.',
      },
      {
        id: 'option.humans.morocco-first',
        feedback: 'Oldest found so far does not mean first ever. An older fossil might survive somewhere researchers have not yet found it.',
        label: 'The Morocco fossils are the first members of our species, so our species began in Morocco.',
      },
    ],
  },
  {
    id: 'prompt.humans.evidence-and-limit',
    lessonId: 'lesson.humans.homo-sapiens-origins',
    kind: 'concise-explanation',
    hint: 'Compare the face with the back of the skull. Then consider how much a few fossils from one site can tell us.',
    evidenceModuleIds: ['module.humans.irhoud-cranium'],
    question: 'The Jebel Irhoud fossils have a face much like ours but a long, low braincase. What does that mix suggest about how our species’ features appeared? Name one thing this evidence cannot tell us.',
    explanation: 'The face looks much like ours while the braincase is long and low, which suggests these features appeared at different times rather than all at once. A few fossils from one site cannot tell us exactly where all the changes happened, or describe every population in Africa.',
    required: true,
    minimumResponseLength: 20,
  },
];

export const homoSapiensOriginsLesson: Lesson = {
  id: 'lesson.humans.homo-sapiens-origins',
  legacyAliases: [],
  status: 'published',
  title: 'Our Species Begins in Africa',
  masthead: 'c. 315,000–160,000 years ago',
  place: 'Across Africa',
  chronology: {
    startYear: -313000,
    endYear: -158000,
    display: 'approximately 315,000–160,000 years ago',
    approximate: true,
  },
  significance: 'The oldest fossils of our species were found in Morocco, not East Africa. Bones, stone tools, and DNA together point to beginnings spread across the continent.',
  learningOutcome: 'You explored how fossils, tools, and DNA inform accounts of our origins, and why surviving evidence leaves important questions open.',
  orientationMapModuleId: 'module.humans.africa-evidence-map',
  heroMediaId: 'media.humans.jebel-irhoud-landscape-reconstruction',
  heroLabel: 'Evidence-based reconstruction',
  heroCaption: 'Jebel Irhoud, Morocco, around 315,000 years ago. The open landscape and the site’s lost cave form are reconstructed from environmental and archaeological evidence; the distant people show presence and scale, not known appearance or exact activity.',
  sectionIdsRequired: [
    'section.humans.skull-in-the-wrong-place',
    'section.humans.what-counts-as-us',
    'section.humans.read-the-skull',
    'section.humans.across-a-continent',
    'section.humans.connected-not-sealed-off',
    'section.humans.what-dna-adds',
    'section.humans.check-and-complete',
  ],
  sections: [
    {
      id: 'section.humans.skull-in-the-wrong-place',
      heading: 'A skull in the wrong place',
      purpose: 'Open the puzzle with a concrete find that breaks the expected story',
      modules: [
        {
          id: 'module.humans.skull-in-the-wrong-place',
          type: 'prose',
          body: 'In 1961, miners digging for barite in a limestone hill called Jebel Irhoud, in western Morocco, cut into what had once been a cave and uncovered a human skull. More bones followed. The experts who studied them decided these people were African Neanderthals, about 40,000 years old. Later work pushed the date back to roughly 160,000 years, and still the fossils fit nowhere comfortably.\n\nDecades later, a team from Morocco and Germany returned to dig a part of the site the miners had left undisturbed. Alongside new fossils they found flint tools that had been burned in a fire. Heat wipes a faint signal in flint back to zero, and the signal then builds up again, slowly, for as long as the stone lies buried. Measuring it gave an age of about 315,000 years.\n\nThat number is hard to hold in your head. All of written history — every date you will meet later in this journey — fits inside about the last five thousand years. Jebel Irhoud is more than sixty times further back than that.\n\nThe bones once filed as fairly recent Neanderthals had become the oldest known fossils of Homo sapiens, our own species. And they lay in the far northwest of Africa, more than five thousand kilometres from the eastern valleys where almost everyone had expected the oldest finds to turn up. Before deciding what that means, it helps to be clear about what we are looking for.',
          claimIds: [
            'claim.humans.irhoud-first-reading',
            'claim.humans.irhoud-age',
            'claim.humans.african-origin',
            'claim.humans.irhoud-was-a-cave',
          ],
          sourceIds: [
            'source.humans.wong-2017-sciam',
            'source.humans.richter-2017-irhoud-age',
            'source.humans.hublin-2017-irhoud',
            'source.humans.smithsonian-homo-sapiens',
          ],
        },
      ],
    },
    {
      id: 'section.humans.what-counts-as-us',
      heading: 'What counts as Homo sapiens?',
      purpose: 'Supply the species category, the state of the record, and the fact that we were not alone',
      modules: [
        {
          id: 'module.humans.what-counts-as-us',
          type: 'knowledge',
          eyebrow: 'Key ideas',
          title: 'Species name, sparse fossils, and other humans',
          body: 'Homo sapiens is the name researchers give our species. Deciding which fossils belong under that name is part of the work, not something settled before the digging starts.',
          items: [
            {
              label: 'Everyone alive is one species',
              detail: 'The DNA of people alive today is about 99.9% alike, and every living group traces its ancestry back to Africa.',
            },
            {
              label: 'Fossils are rare survivors',
              detail: 'Bone lasts only in the right conditions, and then someone has to find it. Researchers work from a scatter of survivors, not a record of everyone who lived.',
            },
            {
              label: 'We were not the only humans',
              detail: 'Other kinds of humans lived in Africa at the same time, including Homo naledi in South Africa. At Kabwe in Zambia, once called Broken Hill, miners dug up another kind of human skull in 1921, about 299,000 years old. Its cave has since been quarried away completely.',
            },
            {
              label: 'This is not a ladder',
              detail: 'Early Homo sapiens fossils do not line up neatly from “old” to “modern.” Features turn up in different mixes at different times and places.',
            },
          ],
          claimIds: [
            'claim.humans.humans-99-9-alike',
            'claim.humans.african-origin',
            'claim.humans.other-hominins',
            'claim.humans.kabwe-site-lost',
            'claim.humans.not-a-ladder',
          ],
          sourceIds: [
            'source.humans.smithsonian-homo-sapiens',
            'source.humans.nhm-modern-humans',
            'source.humans.scerri-2018-subdivided',
            'source.humans.grun-2020-kabwe',
          ],
        },
      ],
    },
    {
      id: 'section.humans.read-the-skull',
      heading: 'Read the skull',
      purpose: 'Observe the mosaic anatomy before interpreting it',
      modules: [
        {
          id: 'module.humans.irhoud-cranium',
          type: 'evidence',
          title: 'Look at the face, then look at the back of the head',
          artifactLabel: 'Composite reconstruction · Jebel Irhoud',
          body: 'No single Jebel Irhoud fossil preserves a whole skull, so researchers scanned several pieces and combined them into one reconstruction. In the right-hand view, the blue shape fills the space where the brain once sat. Look at the face first: small, flat and tucked under the brow, a face that would not stand out among people today. Then look behind it. The braincase is long and low, stretched toward the back like those of earlier humans, and nothing like the high, rounded skull of anyone alive now.',
          mediaId: 'media.humans.jebel-irhoud-cranium',
          layout: 'stacked',
          lookHere: [
            { label: 'The face', detail: 'Notice the small, flat face tucked under the brow.', sourceIds: ['source.humans.hublin-2017-irhoud'] },
            { label: 'Behind the face', detail: 'The long, low braincase contrasts with the face. The blue shape shows the space inside it, not a surviving brain.', sourceIds: ['source.humans.mpi-irhoud-presskit'] },
          ],
          claimIds: ['claim.humans.irhoud-mosaic'],
          sourceIds: [
            'source.humans.hublin-2017-irhoud',
            'source.humans.mpi-irhoud-presskit',
            'source.humans.smithsonian-homo-sapiens',
          ],
        },
        {
          id: 'module.humans.mosaic-not-ladder',
          type: 'prose',
          body: 'A face like ours on a braincase unlike ours is what researchers call a mosaic: old and new features in the same person, rather than a whole body changing at once.\n\nWhen researchers compared the inside shape of skulls across hundreds of thousands of years, they concluded that our rounded braincase arrived later, within our species, rather than at its start. That is a reading of a limited set of fossils, not something you can see on one bone, but it fits what Jebel Irhoud shows: our species did not appear finished.\n\nOne site, however old, cannot settle where a species began. For that, you have to look across the rest of the continent.',
          claimIds: ['claim.humans.braincase-later', 'claim.humans.not-a-ladder'],
          sourceIds: [
            'source.humans.neubauer-2018-brain-shape',
            'source.humans.hublin-2017-irhoud',
            'source.humans.nhm-modern-humans',
          ],
        },
      ],
    },
    {
      id: 'section.humans.across-a-continent',
      heading: 'Evidence across a continent',
      purpose: 'Establish the spatial and chronological spread of the evidence',
      modules: [
        {
          id: 'module.humans.africa-evidence-map',
          type: 'historical-map',
          eyebrow: 'Sites',
          title: 'Five finds across Africa',
          body: 'Four of these markers are fossil sites. One, Olorgesailie, is a toolmaking site. Compare the distances between them with the dates on each marker.',
          mediaId: 'media.humans.africa-evidence-map',
          periodLabel: 'c. 320,000–160,000 years ago',
          focusPlace: 'Africa',
          modernContext: 'Morocco, Ethiopia, Kenya, and South Africa today',
          accessibleSummary: 'Five markers are spread across Africa. In the far northwest, Jebel Irhoud in Morocco, about 315,000 years ago. Near the southern end of the continent, Florisbad in South Africa, about 259,000 years ago. Three markers sit closer together in eastern Africa: Omo Kibish in Ethiopia, at least 233,000 years ago; Herto in Ethiopia, about 160,000 years ago; and Olorgesailie in Kenya, a toolmaking site dated to about 320,000 to 305,000 years ago. The finds are separated by thousands of kilometres and by more than 150,000 years, and they do not cluster around any one region. There is no centre to point to.',
          compactLabel: 'Coordinates verified per site · modern coasts for orientation',
          coordinateNote: 'Jebel Irhoud, Herto, and Florisbad are placed from published surveyed or GPS coordinates. Omo Kibish and Olorgesailie are placed from published area descriptions and are drawn with a wider, softer halo to show that lower precision.',
          uncertaintyNote: 'A marker shows where evidence survived and was found, not the only place people lived. Olorgesailie is a whole basin, not a spot. Coastlines are modern and are here for orientation only; they are not a reconstruction of the shorelines, lakes, or deserts of 300,000 years ago.',
          depictionStatus: 'illustrative-reconstruction',
          claimIds: ['claim.humans.sites-spread', 'claim.humans.map-points-are-areas'],
          sourceIds: [
            'source.humans.natural-earth',
            'source.humans.benncer-2023-irhoud',
            'source.humans.white-2003-herto',
            'source.humans.douglas-2009-florisbad',
            'source.humans.potts-2020-variability',
            'source.humans.roceeh-road',
          ],
        },
        {
          id: 'module.humans.no-centre',
          type: 'prose',
          body: 'Line up the dates with the distances on the map, and the old story falls apart. The oldest fossils are in Morocco. The next oldest, at Florisbad in South Africa, lie more than seven thousand kilometres away. And the oldest fossil from the eastern valleys everyone used to point to has only a minimum age, and a story behind it.\n\nThat fossil is Omo I, found in southern Ethiopia in 1967 by a team led by Richard Leakey. It was first thought to be about 130,000 years old; in 2008 its layers were redated to about 195,000. Then researchers turned to the ash lying on top of it, more than two metres of fine volcanic dust. The grains were too fine to date directly, so the team matched the chemistry of its tiny glass shards to a major eruption of Shala volcano, 350 kilometres away, and dated the rock left near the volcano instead: about 233,000 years ago, give or take 22,000. Ash that settled on top must be younger than whatever lies beneath, so the fossil is at least that old. How much older, this evidence cannot say. A minimum age is still real information, a floor rather than a full measurement.\n\nTaken together, the finds do not point to one special place. Spread out, though, is not the same as cut off.',
          claimIds: [
            'claim.humans.sites-spread',
            'claim.humans.omo-age-history',
            'claim.humans.omo-ash-match',
            'claim.humans.omo-minimum-age',
            'claim.humans.no-single-birthplace',
          ],
          sourceIds: [
            'source.humans.smithsonian-omo-i',
            'source.humans.vidal-2022-omo',
            'source.humans.grun-1996-florisbad',
            'source.humans.bergstrom-2021-ancestry',
            'source.humans.scerri-2018-subdivided',
          ],
        },
      ],
    },
    {
      id: 'section.humans.connected-not-sealed-off',
      heading: 'Connected, not sealed off',
      purpose: 'Explain the connections and conditions that make a continent-wide origin possible',
      modules: [
        {
          id: 'module.humans.irhoud-tools',
          type: 'evidence',
          title: 'Middle Stone Age tools from Jebel Irhoud',
          artifactLabel: 'Middle Stone Age tools · Jebel Irhoud',
          body: 'These tools came from the same layers as the Moroccan fossils, and burned pieces like these are what dated the site. Most are pointed and worked along both edges. Others were struck from stone cores that had been shaped first, so the maker could plan the flake before knocking it off, thinking several steps ahead in a material that punishes mistakes.\n\nToolkits built on the same ideas show up in far-apart parts of Africa around 300,000 years ago. “Around” covers tens of thousands of years, and whole regions, especially West and Central Africa, have barely been studied. Even so, the change was not confined to one valley.',
          mediaId: 'media.humans.jebel-irhoud-tools',
          claimIds: ['claim.humans.msa-broadly-contemporary', 'claim.humans.record-sparse'],
          sourceIds: [
            'source.humans.richter-2017-irhoud-age',
            'source.humans.mpi-irhoud-presskit',
            'source.humans.scerri-2018-subdivided',
          ],
        },
        {
          id: 'module.humans.connections',
          type: 'knowledge',
          eyebrow: 'Olorgesailie, southern Kenya',
          title: 'Long-distance stone and pigment',
          body: 'For hundreds of thousands of years, people in one Kenyan basin made big, all-purpose stone handaxes. Then, in layers dated to about 320,000–305,000 years ago, the handaxes are gone. In their place are smaller, more carefully shaped tools, and signs of how far one community’s world now reached. The dig is a joint project of the Smithsonian and the National Museums of Kenya.',
          items: [
            {
              label: 'Obsidian from far off',
              detail: 'Volcanic glass at the site came from sources in several directions, 25 to 95 kilometres away. Earlier toolmakers in the same basin mostly used stone from within about five kilometres.',
            },
            {
              label: 'Colour, deliberately made',
              detail: 'Black and red rocks, manganese and iron-rich ochre, were carried in and processed into colouring material.',
            },
            {
              label: 'What the distance implies',
              detail: 'Stone moving that far suggests trade between groups, or one group ranging much farther than before. The rock cannot tell which. Either way, their world had grown.',
            },
            {
              label: 'Climate kept redrawing the map',
              detail: 'African deserts, grasslands and forests grew and shrank again and again, which could split groups apart for long stretches and later bring them back into contact. Researchers propose this as one cause of the pattern; the dates are still too rough to prove it.',
            },
          ],
          claimIds: [
            'claim.humans.olorgesailie-change',
            'claim.humans.olorgesailie-networks',
            'claim.humans.transport-implies-connection',
            'claim.humans.climate-structure',
          ],
          sourceIds: [
            'source.humans.si-olorgesailie-2018',
            'source.humans.brooks-2018-olorgesailie',
            'source.humans.potts-2020-variability',
            'source.humans.scerri-2018-subdivided',
          ],
        },
      ],
    },
    {
      id: 'section.humans.what-dna-adds',
      heading: 'What DNA adds — and what it cannot',
      purpose: 'Add the genetic evidence and state the honest limits alongside it',
      modules: [
        {
          id: 'module.humans.what-dna-adds',
          type: 'prose',
          body: 'In 2023, a team of geneticists sequenced the genomes of 44 Nama people from southern Africa and set them beside genomes from groups across the continent. Then they tested which ancient family history best explains the patterns people carry today. They had to work from the living, because no DNA has ever been recovered from an African human fossil this old: heat and damp break it down long before 300,000 years pass.\n\nThe best fit was not one ancestral group splitting cleanly into branches. It was two or more groups, only slightly different from one another, exchanging people and genes back and forth for hundreds of thousands of years.\n\nThat is what a model fits, not something anyone watched happen, and the same researchers show how much the choice of model shapes the answer. Still, a third kind of evidence, after bone and stone, points the same way: many groups, spread out, staying in touch.',
          claimIds: [
            'claim.humans.adna-limits',
            'claim.humans.dna-weak-structure',
            'claim.humans.structured-populations',
          ],
          sourceIds: [
            'source.humans.ragsdale-2023-stem',
            'source.humans.bergstrom-2021-ancestry',
            'source.humans.scerri-2018-subdivided',
          ],
        },
        {
          id: 'module.humans.open-questions',
          type: 'knowledge',
          eyebrow: 'Limits',
          title: 'Boundaries, blank spaces, and open models',
          body: 'That our species came from Africa is not in doubt. Nearly every detail inside that answer is still argued over, and the arguments are of different kinds.',
          items: [
            {
              label: 'Where the line goes',
              detail: 'Researchers disagree about which fossils count as Homo sapiens; some put Jebel Irhoud and Florisbad in a different species. The argument is over where to draw a line across a slowly changing family, and there may be no sharp line to find.',
            },
            {
              label: 'Whether a birthplace existed',
              detail: 'No one can currently name one time and place where our ancestry was limited to a small region. That is not the same as proving no such place ever existed.',
            },
            {
              label: 'Who left no descendants',
              detail: 'DNA from living people reaches only ancestral groups that still have descendants. Groups whose lines ended leave no trace in this kind of evidence.',
            },
            {
              label: 'Where nobody has looked',
              detail: 'Bone survives in some places and not others, and digging has been funded and permitted far more in some countries than in others, so a blank spot on the map is not proof that a place was empty. Jebel Irhoud and Kabwe were both found by miners, not by scientists searching for them. The next surprise could come from a part of Africa nobody has looked at yet.',
            },
          ],
          claimIds: [
            'claim.humans.species-boundary-contested',
            'claim.humans.no-single-birthplace',
            'claim.humans.adna-limits',
            'claim.humans.record-sparse',
            'claim.humans.irhoud-first-reading',
            'claim.humans.kabwe-site-lost',
          ],
          sourceIds: [
            'source.humans.scerri-2018-subdivided',
            'source.humans.stringer-2016-origin',
            'source.humans.bergstrom-2021-ancestry',
            'source.humans.ragsdale-2023-stem',
            'source.humans.wong-2017-sciam',
            'source.humans.grun-2020-kabwe',
          ],
        },
      ],
    },
    {
      id: 'section.humans.check-and-complete',
      heading: 'World Check',
      purpose: 'Use the distribution of evidence and explain a limit of it',
      modules: [
        {
          id: 'module.humans.prompt-best-supported-conclusion',
          type: 'prompt',
          promptId: 'prompt.humans.best-supported-conclusion',
          claimIds: [],
          sourceIds: [],
        },
        {
          id: 'module.humans.prompt-evidence-and-limit',
          type: 'prompt',
          promptId: 'prompt.humans.evidence-and-limit',
          claimIds: [],
          sourceIds: [],
        },
      ],
    },
  ],
  claimIds: homoSapiensOriginsClaims.map((claim) => claim.id),
  sourceIds: homoSapiensOriginsSources.map((source) => source.id),
  mediaIds: [
    'media.humans.jebel-irhoud-landscape-reconstruction',
    'media.humans.jebel-irhoud-cranium',
    'media.humans.jebel-irhoud-tools',
    'media.humans.africa-evidence-map',
    'media.humans.africa-origins-card',
  ],
  promptIds: ['prompt.humans.best-supported-conclusion', 'prompt.humans.evidence-and-limit'],
};

export const homoSapiensOriginsCards: KnowledgeCard[] = [
  {
    id: 'card.idea.origins-across-africa',
    title: 'Our Species Began Across Africa',
    category: 'idea',
    cardClass: 'foundation',
    date: {
      startYear: -313000,
      endYear: -158000,
      display: 'c. 315,000–160,000 years ago',
      approximate: true,
    },
    place: 'Across Africa',
    significance: 'Fossils, stone tools, and DNA all point the same way: our species began among many connected groups spread across Africa — with no single birthplace to name.',
    revealTitle: 'No single birthplace',
    revealBody: 'You put fossil, tool, and DNA evidence together, worked out what the spread of finds supports, and named what it still cannot settle.',
    depictionLabel: 'Evidence locations · modern coasts for orientation',
    facts: [
      'Oldest known fossils of our species: Jebel Irhoud, Morocco, about 315,000 years ago',
      'Comparable finds in South Africa and Ethiopia span more than 150,000 years',
      'A modern-looking face appeared before the rounded braincase did',
      'DNA of living people fits several weakly separated groups linked by long contact',
      'No single birthplace has been identified',
    ],
    lessonIds: ['lesson.humans.homo-sapiens-origins'],
    sourceIds: [
      'source.humans.hublin-2017-irhoud',
      'source.humans.scerri-2018-subdivided',
      'source.humans.bergstrom-2021-ancestry',
      'source.humans.ragsdale-2023-stem',
    ],
    mediaId: 'media.humans.africa-origins-card',
    unlockLessonId: 'lesson.humans.homo-sapiens-origins',
    recallPrompt: 'What does a modern-looking face with a long, low braincase suggest? What can one find not settle?',
    connections: [{ lessonId: 'lesson.humans.migrations-and-interbreeding', label: 'Fossils and ancient DNA', reason: 'Compare how a different kind of evidence adds to our account of ancient people.' }],
  },
];

export const homoSapiensOriginsContent: AuthoredContentModule = {
  sources: homoSapiensOriginsSources,
  claims: homoSapiensOriginsClaims,
  media: homoSapiensOriginsMedia,
  prompts: homoSapiensOriginsPrompts,
  lessons: [homoSapiensOriginsLesson],
  cards: homoSapiensOriginsCards,
};
