import type { Claim, KnowledgeCard, Lesson, MediaAsset, Source, UnderstandingPrompt } from '../../src/domains/contracts';
import type { AuthoredContentModule } from '../assemble';
import { mediaLocator } from '../shared/media-locator';

export const homoSapiensOriginsSources: Source[] = [
  {
    id: 'source.humans.hublin-2017-irhoud',
    title: 'New fossils from Jebel Irhoud, Morocco and the pan-African origin of Homo sapiens',
    url: 'https://doi.org/10.1038/nature22336',
    publisher: 'Nature',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Peer-reviewed excavation report cited as a fact source; article figures not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.richter-2017-irhoud-age',
    title: 'The age of the hominin fossils from Jebel Irhoud, Morocco, and the origins of the Middle Stone Age',
    url: 'https://doi.org/10.1038/nature22335',
    publisher: 'Nature',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Peer-reviewed geochronology cited as a fact source; article figures not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.vidal-2022-omo',
    title: 'Age of the oldest known Homo sapiens from eastern Africa',
    url: 'https://doi.org/10.1038/s41586-021-04275-8',
    publisher: 'Nature',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Open-access peer-reviewed geochronology cited as a fact source',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.scerri-2018-subdivided',
    title: 'Did Our Species Evolve in Subdivided Populations across Africa, and Why Does It Matter?',
    url: 'https://doi.org/10.1016/j.tree.2018.05.005',
    publisher: 'Trends in Ecology & Evolution',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Peer-reviewed multi-disciplinary synthesis cited as a fact source; figures not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.bergstrom-2021-ancestry',
    title: 'Origins of modern human ancestry',
    url: 'https://doi.org/10.1038/s41586-021-03244-5',
    publisher: 'Nature',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Peer-reviewed review cited as a fact source; figures not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.ragsdale-2023-stem',
    title: 'A weakly structured stem for human origins in Africa',
    url: 'https://doi.org/10.1038/s41586-023-06055-y',
    publisher: 'Nature',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Open-access peer-reviewed population-genetic modelling cited as a fact source',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.brooks-2018-olorgesailie',
    title: 'Long-distance stone transport and pigment use in the earliest Middle Stone Age',
    url: 'https://doi.org/10.1126/science.aao2646',
    publisher: 'Science',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Peer-reviewed excavation report cited as a fact source; figures not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.potts-2020-variability',
    title: 'Increased ecological resource variability during a critical transition in hominin evolution',
    url: 'https://doi.org/10.1126/sciadv.abc8975',
    publisher: 'Science Advances',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Open-access peer-reviewed research cited as a fact and coordinate source',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.white-2003-herto',
    title: 'Pleistocene Homo sapiens from Middle Awash, Ethiopia',
    url: 'https://doi.org/10.1038/nature01669',
    publisher: 'Nature',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Peer-reviewed species description cited as a fact and coordinate source; figures not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.grun-1996-florisbad',
    title: 'Direct dating of Florisbad hominid',
    url: 'https://doi.org/10.1038/382500a0',
    publisher: 'Nature',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Peer-reviewed dating study cited as a fact source; figures not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.douglas-2009-florisbad',
    title: 'A new perspective on the geohydrological and surface processes controlling the depositional environment at the Florisbad archaeozoological site',
    url: 'https://scholar.ufs.ac.za/server/api/core/bitstreams/0c41f0d2-54bc-4e4e-9b42-1d02c99f7697/content',
    publisher: 'University of the Free State',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Open-access institutional thesis deposit used for surveyed site coordinates only',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.benncer-2023-irhoud',
    title: 'Jebel Irhoud (Ighoud), Morocco',
    url: 'https://link.springer.com/chapter/10.1007/978-3-031-20290-2_51',
    publisher: 'Springer, Handbook of Pleistocene Archaeology of Africa',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Excavation-team gazetteer entry used for the published site coordinate; chapter text not reproduced',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.roceeh-road',
    title: 'ROAD (ROCEEH Out of Africa Database) — Africa localities',
    url: 'https://www.roceeh.uni-tuebingen.de/api/Africa-localities-lithics-hominins-paleofauna-120ka-1800ka.php',
    publisher: 'Heidelberg Academy of Sciences and Humanities / University of Tübingen',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Curated academic locality database used only to cross-check coordinates, never as sole authority',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.grun-2020-kabwe',
    title: 'Dating the skull from Broken Hill, Zambia, and its position in human evolution',
    url: 'https://doi.org/10.1038/s41586-020-2165-4',
    publisher: 'Nature',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Peer-reviewed dating study cited as a fact source; figures not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.neubauer-2018-brain-shape',
    title: 'The evolution of modern human brain shape',
    url: 'https://doi.org/10.1126/sciadv.aao5961',
    publisher: 'Science Advances',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Open-access peer-reviewed morphometric study cited as a fact source',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.stringer-2016-origin',
    title: 'The origin and evolution of Homo sapiens',
    url: 'https://doi.org/10.1098/rstb.2015.0237',
    publisher: 'Philosophical Transactions of the Royal Society B',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Peer-reviewed synthesis cited as a fact source; figures not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.smithsonian-homo-sapiens',
    title: 'Homo sapiens — Human Origins Program',
    url: 'https://humanorigins.si.edu/evidence/human-fossils/species/homo-sapiens',
    publisher: 'Smithsonian Institution',
    accessedOn: '2026-07-26',
    licenseOrUse: 'National museum public science reference used for framing; museum imagery not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.nhm-modern-humans',
    title: 'Modern humans, Homo sapiens: When, where and how did we evolve?',
    url: 'https://www.nhm.ac.uk/discover/modern-humans-homo-sapiens-when-where-how-did-we-evolve.html',
    publisher: 'Natural History Museum, London',
    accessedOn: '2026-07-26',
    licenseOrUse: 'National museum public science reference used for framing; museum imagery not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.mpi-irhoud-presskit',
    title: 'The first of our kind — Jebel Irhoud press materials',
    url: 'https://www.eva.mpg.de/press/news/2017/2017-06-07-the-first-of-our-kind/',
    publisher: 'Max Planck Institute for Evolutionary Anthropology',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Press images released under CC BY-SA 2.0; reused with credit and share-alike, resized only',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.natural-earth',
    title: 'Natural Earth',
    url: 'https://www.naturalearthdata.com/',
    publisher: 'Natural Earth',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Public Domain geographic base used for modern coast and landmass orientation only',
    reviewStatus: 'reviewed',
  },
];

export const homoSapiensOriginsClaims: Claim[] = [
  {
    id: 'claim.humans.african-origin',
    statement: 'All people alive today trace their ancestry to populations that lived in Africa; the oldest fossils of our species and the deepest genetic diversity are both found there.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: [
      'source.humans.nhm-modern-humans',
      'source.humans.smithsonian-homo-sapiens',
      'source.humans.bergstrom-2021-ancestry',
      'source.humans.ragsdale-2023-stem',
    ],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.irhoud-age',
    statement: 'Burnt stone tools found with the Jebel Irhoud fossils in Morocco date to about 315,000 years ago (315 ± 34 ka).',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.humans.richter-2017-irhoud-age', 'source.humans.hublin-2017-irhoud'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.irhoud-mosaic',
    statement: 'The Jebel Irhoud fossils combine a face and jaw close to those of people today with a long, low braincase resembling earlier humans.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: [
      'source.humans.hublin-2017-irhoud',
      'source.humans.smithsonian-homo-sapiens',
      'source.humans.nhm-modern-humans',
    ],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.braincase-later',
    statement: 'The rounded braincase typical of people today developed later within the Homo sapiens lineage rather than being present from its start.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: [
      'source.humans.neubauer-2018-brain-shape',
      'source.humans.hublin-2017-irhoud',
      'source.humans.scerri-2018-subdivided',
    ],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.sites-spread',
    statement: 'Fossils assigned to early Homo sapiens come from northern, eastern, and southern Africa: Jebel Irhoud about 315,000 years ago, Florisbad about 259,000, Omo Kibish at least 233,000, and Herto about 160,000.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: [
      'source.humans.hublin-2017-irhoud',
      'source.humans.grun-1996-florisbad',
      'source.humans.vidal-2022-omo',
      'source.humans.white-2003-herto',
      'source.humans.scerri-2018-subdivided',
    ],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.omo-minimum-age',
    statement: 'Volcanic ash lying above the Omo I fossil has been matched to an eruption dated to 233,000 ± 22,000 years ago, so the fossil must be at least that old.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.humans.vidal-2022-omo'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.no-single-birthplace',
    statement: 'No single time and place can currently be identified at which our species\u2019 ancestry was confined to one small region.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: [
      'source.humans.bergstrom-2021-ancestry',
      'source.humans.scerri-2018-subdivided',
      'source.humans.nhm-modern-humans',
    ],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.structured-populations',
    statement: 'The evidence fits our species emerging among populations spread across Africa that were sometimes separated and sometimes in contact, rather than descending from one isolated group.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: [
      'source.humans.scerri-2018-subdivided',
      'source.humans.bergstrom-2021-ancestry',
      'source.humans.ragsdale-2023-stem',
    ],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.not-a-ladder',
    statement: 'Early Homo sapiens fossils do not form a simple line from primitive to modern; different combinations of traits appear at different times and places.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: [
      'source.humans.scerri-2018-subdivided',
      'source.humans.stringer-2016-origin',
      'source.humans.hublin-2017-irhoud',
    ],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.msa-broadly-contemporary',
    statement: 'A shift to Middle Stone Age toolmaking appears in widely separated parts of Africa at broadly similar times around 300,000 years ago.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: [
      'source.humans.scerri-2018-subdivided',
      'source.humans.brooks-2018-olorgesailie',
      'source.humans.richter-2017-irhoud-age',
    ],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.olorgesailie-networks',
    statement: 'At Olorgesailie in southern Kenya, between about 320,000 and 305,000 years ago, people made prepared cores and points, processed iron-rich rock for red pigment, and obtained obsidian from sources 25 to 95 km away.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.humans.brooks-2018-olorgesailie', 'source.humans.potts-2020-variability'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.transport-implies-connection',
    statement: 'Moving stone that far implies wider ranging or exchange between groups than the 5 km or less typical of earlier Acheulean toolmaking.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.humans.brooks-2018-olorgesailie', 'source.humans.potts-2020-variability'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.climate-structure',
    statement: 'Shifting African climate repeatedly expanded and contracted deserts, forests, and grasslands, which could separate populations for long periods and later reconnect them.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.humans.scerri-2018-subdivided', 'source.humans.potts-2020-variability'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.dna-weak-structure',
    statement: 'Modelling the DNA of living African populations fits best with two or more weakly different ancestral populations linked by gene flow over hundreds of thousands of years.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.humans.ragsdale-2023-stem'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.humans-99-9-alike',
    statement: 'The DNA of all people living today is about 99.9% alike.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.humans.smithsonian-homo-sapiens'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.other-hominins',
    statement: 'Other kinds of humans lived in Africa during the same period, including Homo naledi (c. 335,000–236,000 years ago) and the Kabwe individual (c. 299,000 years ago).',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.humans.scerri-2018-subdivided', 'source.humans.grun-2020-kabwe'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.record-sparse',
    statement: 'The African fossil record for this period is thin and unevenly sampled, and large regions including West and Central Africa remain poorly investigated.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: [
      'source.humans.scerri-2018-subdivided',
      'source.humans.bergstrom-2021-ancestry',
      'source.humans.ragsdale-2023-stem',
    ],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.adna-limits',
    statement: 'No DNA has been recovered from African human fossils this old, because warm and humid conditions destroy it, so genetic conclusions about this period come from the DNA of living people and much younger remains.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.humans.scerri-2018-subdivided', 'source.humans.bergstrom-2021-ancestry'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.species-boundary-contested',
    statement: 'Researchers disagree about which fossils should count as Homo sapiens; some place Jebel Irhoud and Florisbad in a different species.',
    kind: 'interpretation',
    certainty: 'contested',
    sourceIds: ['source.humans.scerri-2018-subdivided', 'source.humans.stringer-2016-origin'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.map-points-are-areas',
    statement: 'Map points mark the areas where evidence was found rather than exact spots; Olorgesailie is a basin roughly the size of a small county, and only the Herto fossil has a published GPS fix on its find spot.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: [
      'source.humans.potts-2020-variability',
      'source.humans.white-2003-herto',
      'source.humans.roceeh-road',
      'source.humans.benncer-2023-irhoud',
      'source.humans.douglas-2009-florisbad',
    ],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.humans.irhoud-was-a-cave',
    statement: 'The Jebel Irhoud deposits were inside a cave when people used the site; twentieth-century mining removed the covering rock and much of the sediment, leaving the open face visible today.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.humans.mpi-irhoud-presskit', 'source.humans.hublin-2017-irhoud'],
    reviewStatus: 'editorial-review-required',
  },
];

export const homoSapiensOriginsMedia: MediaAsset[] = [
  {
    id: 'media.humans.jebel-irhoud-excavation',
    locator: mediaLocator('media.humans.jebel-irhoud-excavation'),
    alt: 'Wide photograph of the Jebel Irhoud site in Morocco looking south: a bare limestone hillside cut into an open face, with excavators and equipment small in the centre and dry plains stretching to the horizon',
    depictionMode: 'evidence',
    depictionLabel: 'Excavation photograph · Jebel Irhoud, Morocco',
    rightsLabel: 'Shannon McPherron, MPI EVA Leipzig · CC BY-SA 2.0 · resized',
    sourceIds: ['source.humans.mpi-irhoud-presskit', 'source.humans.hublin-2017-irhoud'],
    visualBriefRef: 'docs/research/homo-sapiens-origins.md#hero-jebel-irhoud-site-photograph',
    reviewStatus: 'approved',
  },
  {
    id: 'media.humans.jebel-irhoud-cranium',
    locator: mediaLocator('media.humans.jebel-irhoud-cranium'),
    alt: 'Two views of a reconstructed skull. On the left, a three-quarter view showing a small flat face tucked beneath a long, low braincase. On the right, the same skull in profile with the space inside the braincase filled by a blue shape that is long and low from front to back rather than round.',
    depictionMode: 'evidence-based-reconstruction',
    depictionLabel: 'Composite reconstruction from micro-CT scans of several original fossils; the blue shape is a virtual cast of the braincase interior',
    rightsLabel: 'Philipp Gunz, MPI EVA Leipzig · CC BY-SA 2.0 · resized',
    sourceIds: [
      'source.humans.mpi-irhoud-presskit',
      'source.humans.hublin-2017-irhoud',
      'source.humans.neubauer-2018-brain-shape',
    ],
    visualBriefRef: 'docs/research/homo-sapiens-origins.md#evidence-encounter-jebel-irhoud-cranium',
    reviewStatus: 'approved',
  },
  {
    id: 'media.humans.jebel-irhoud-tools',
    locator: mediaLocator('media.humans.jebel-irhoud-tools'),
    alt: 'Fourteen stone tools from Jebel Irhoud photographed against black and arranged in rows, most of them pointed and shaped along both edges, in brown, grey, and honey-coloured flint, with a one-centimetre scale bar showing that the largest are roughly the length of a thumb',
    depictionMode: 'evidence',
    depictionLabel: 'Excavated artefacts photographed with a 1 cm scale bar',
    rightsLabel: 'Mohammed Kamal, MPI EVA Leipzig · CC BY-SA 2.0 · converted and resized',
    sourceIds: [
      'source.humans.mpi-irhoud-presskit',
      'source.humans.richter-2017-irhoud-age',
      'source.humans.hublin-2017-irhoud',
    ],
    visualBriefRef: 'docs/research/homo-sapiens-origins.md#middle-stone-age-toolkit-plate',
    reviewStatus: 'approved',
  },
  {
    id: 'media.humans.africa-evidence-map',
    locator: mediaLocator('media.humans.africa-evidence-map'),
    alt: 'Map of Africa with five marked sites: Jebel Irhoud in the far northwest of Morocco, Florisbad in South Africa near the southern end of the continent, and Omo Kibish, Herto, and Olorgesailie clustered in eastern Africa near the equator. Each marker carries the site name and its date. Olorgesailie and Omo Kibish have wider, softer halos than the others.',
    depictionMode: 'map',
    depictionLabel: 'Evidence locations · coordinates verified per site, modern coasts for orientation',
    rightsLabel: 'Chronos original · Natural Earth base geography, Public Domain',
    sourceIds: [
      'source.humans.natural-earth',
      'source.humans.benncer-2023-irhoud',
      'source.humans.white-2003-herto',
      'source.humans.douglas-2009-florisbad',
      'source.humans.potts-2020-variability',
      'source.humans.roceeh-road',
    ],
    visualBriefRef: 'docs/research/homo-sapiens-origins.md#africa-evidence-map',
    reviewStatus: 'approved',
  },
  {
    id: 'media.humans.africa-origins-card',
    locator: mediaLocator('media.humans.africa-origins-card'),
    alt: 'Simplified map of Africa on aged paper with five glowing markers spread from Morocco in the northwest to South Africa in the south and a cluster in eastern Africa, with no text labels',
    depictionMode: 'map',
    depictionLabel: 'Evidence locations · modern coasts for orientation',
    rightsLabel: 'Chronos original · Natural Earth base geography, Public Domain',
    sourceIds: [
      'source.humans.natural-earth',
      'source.humans.benncer-2023-irhoud',
      'source.humans.white-2003-herto',
      'source.humans.douglas-2009-florisbad',
      'source.humans.potts-2020-variability',
    ],
    visualBriefRef: 'docs/research/homo-sapiens-origins.md#knowledge-card-artwork',
    reviewStatus: 'approved',
  },
];

export const homoSapiensOriginsPrompts: UnderstandingPrompt[] = [
  {
    id: 'prompt.humans.best-supported-conclusion',
    lessonId: 'lesson.humans.homo-sapiens-origins',
    kind: 'supported-selection',
    question: 'Fossils of early Homo sapiens have been found in Morocco from about 315,000 years ago, in South Africa from about 259,000 years ago, and in Ethiopia from at least 233,000 years ago. They are thousands of kilometres apart, and they do not all share the same mix of features. Which conclusion does this set of finds best support?',
    explanation: 'The finds are spread across Africa, cover more than 150,000 years, and mix features in different ways. That fits groups that were sometimes apart and sometimes in contact. One valley cannot explain finds that far apart. Different mixes of features are not separate species either, because these groups kept exchanging genes. And “oldest known” is not the same as “first”: Jebel Irhoud is the oldest evidence found so far — the next dig could be older and somewhere else. This evidence rules out a simple one-place story. It does not replace it with a different single place.',
    required: true,
    options: [
      {
        id: 'option.humans.connected-populations',
        label: 'Our species took shape among populations living in many parts of Africa that were sometimes separated and sometimes in contact.',
      },
      {
        id: 'option.humans.one-valley',
        label: 'Our species began in one valley in eastern Africa and spread out from there.',
      },
      {
        id: 'option.humans.separate-species',
        label: 'Each region of Africa evolved its own separate human species.',
      },
      {
        id: 'option.humans.morocco-first',
        label: 'The Morocco fossils are the first members of our species, so our species began in Morocco.',
      },
    ],
  },
  {
    id: 'prompt.humans.evidence-and-limit',
    lessonId: 'lesson.humans.homo-sapiens-origins',
    kind: 'concise-explanation',
    question: 'The Jebel Irhoud fossils have a face much like ours but a long, low braincase. What does that mix suggest about how our species’ features appeared? Name one thing this evidence cannot tell us.',
    explanation: 'A sincere answer links the mix to features arriving separately, not all at once — with a modern-looking face before the rounded braincase. Any real limit counts for the second part: only a few people from one site; the record is thin; whole regions have barely been dug; no DNA survives from African fossils this old; researchers still disagree about which fossils count as our species. The length rule measures effort, not polish. Write what you actually think.',
    required: true,
    minimumResponseLength: 20,
  },
];

export const homoSapiensOriginsLesson: Lesson = {
  id: 'lesson.humans.homo-sapiens-origins',
  legacyAliases: [],
  status: 'published',
  title: 'Our Species Begins in Africa',
  masthead: 'c. 315,000–160,000 years ago',
  place: 'Across Africa',
  chronology: {
    startYear: -313000,
    endYear: -158000,
    display: 'approximately 315,000–160,000 years ago',
    approximate: true,
  },
  significance: 'The oldest fossils of our species were found in Morocco, not East Africa. Bones, stone tools, and DNA together point to beginnings spread across the continent.',
  heroMediaId: 'media.humans.jebel-irhoud-excavation',
  heroLabel: 'Excavation photograph',
  heroCaption: 'Jebel Irhoud, Morocco, looking south. People once used this place as a cave. Mining in the 1960s removed the roof and much of the soil, leaving the open face where fossils were later dug out.',
  sectionIdsRequired: [
    'section.humans.skull-in-the-wrong-place',
    'section.humans.what-counts-as-us',
    'section.humans.read-the-skull',
    'section.humans.across-a-continent',
    'section.humans.connected-not-sealed-off',
    'section.humans.what-dna-adds',
    'section.humans.check-and-complete',
  ],
  sections: [
    {
      id: 'section.humans.skull-in-the-wrong-place',
      heading: 'A skull in the wrong place',
      purpose: 'Open the puzzle with a concrete find that breaks the expected story',
      modules: [
        {
          id: 'module.humans.skull-in-the-wrong-place',
          type: 'prose',
          body: 'In 1961, miners cutting into a hillside called Jebel Irhoud in western Morocco found a human skull. Nobody knew what to make of it. It did not look like anyone expected. For decades, people thought the site was much younger than it is.\n\nLater, a team from Morocco and Germany went back to dig what the mining had left. Among the bones they found flint tools that had been burned in a fire long ago. Burned stone can keep a faint record of how long it has been buried. Reading that record gave an age of about 315,000 years.\n\nThat number is hard to hold in your head. All of written history — every date you will meet later in this journey — fits inside about the last five thousand years. Jebel Irhoud is more than sixty times further back than that.\n\nThese became the oldest known fossils of Homo sapiens — our own species. And they were in the far northwest of Africa, more than five thousand kilometres from the eastern valleys where almost everyone had expected the oldest finds. Before we can say what that means, we need to be clear about what we are looking for.',
          claimIds: ['claim.humans.irhoud-age', 'claim.humans.african-origin', 'claim.humans.irhoud-was-a-cave'],
          sourceIds: [
            'source.humans.richter-2017-irhoud-age',
            'source.humans.hublin-2017-irhoud',
            'source.humans.smithsonian-homo-sapiens',
          ],
        },
      ],
    },
    {
      id: 'section.humans.what-counts-as-us',
      heading: 'What counts as Homo sapiens?',
      purpose: 'Supply the species category, the state of the record, and the fact that we were not alone',
      modules: [
        {
          id: 'module.humans.what-counts-as-us',
          type: 'knowledge',
          eyebrow: 'Key ideas',
          title: 'Species name, sparse fossils, and other humans',
          body: 'Homo sapiens is the name researchers give our species. Which fossils belong in that name is part of the work — not something settled before digging begins.',
          items: [
            {
              label: 'Everyone alive is one species',
              detail: 'The DNA of people alive today is about 99.9% alike. Every living group can trace ancestry back to Africa.',
            },
            {
              label: 'A fossil is not a photograph',
              detail: 'Bone survives only in certain conditions. Researchers have a scatter of survivors — not a record of everyone who lived.',
            },
            {
              label: 'We were not the only humans',
              detail: 'Other kinds of humans also lived in Africa then, including Homo naledi in South Africa and a person from Kabwe in Zambia. Their remains are roughly this old too.',
            },
            {
              label: 'This is not a ladder',
              detail: 'Early Homo sapiens fossils do not line up neatly from “old” to “modern.” Different features show up in different mixes at different times and places.',
            },
          ],
          claimIds: [
            'claim.humans.humans-99-9-alike',
            'claim.humans.african-origin',
            'claim.humans.other-hominins',
            'claim.humans.not-a-ladder',
          ],
          sourceIds: [
            'source.humans.smithsonian-homo-sapiens',
            'source.humans.nhm-modern-humans',
            'source.humans.scerri-2018-subdivided',
            'source.humans.grun-2020-kabwe',
          ],
        },
      ],
    },
    {
      id: 'section.humans.read-the-skull',
      heading: 'Read the skull',
      purpose: 'Observe the mosaic anatomy before interpreting it',
      modules: [
        {
          id: 'module.humans.irhoud-cranium',
          type: 'evidence',
          title: 'Look at the face, then look at the back of the head',
          artifactLabel: 'Composite reconstruction · Jebel Irhoud',
          body: 'No single Jebel Irhoud fossil keeps a whole skull. Researchers scanned several pieces and combined them into one reconstruction. On the right, the blue shape shows the space the brain filled. Look at the face first: small, flat, tucked under the brow — a face that would not stand out among people today. Then look behind it. The braincase is long and low, pushed out toward the back, like earlier humans. It is nothing like the high, round skull of a person alive now.',
          mediaId: 'media.humans.jebel-irhoud-cranium',
          claimIds: ['claim.humans.irhoud-mosaic'],
          sourceIds: [
            'source.humans.hublin-2017-irhoud',
            'source.humans.mpi-irhoud-presskit',
            'source.humans.smithsonian-homo-sapiens',
          ],
        },
        {
          id: 'module.humans.mosaic-not-ladder',
          type: 'prose',
          body: 'A face like ours on a braincase unlike ours is called a mosaic: old and new features in the same person, not a whole body changing at once.\n\nResearchers who measured many skulls concluded that the rounded braincase we have now came later, inside our species, rather than arriving at the start. That is a reading of a limited set of fossils — not something you can see straight off one bone. But it fits what Jebel Irhoud shows: our species did not appear finished.\n\nOne site cannot settle where a species began. So the next question is what the rest of the continent looks like.',
          claimIds: ['claim.humans.braincase-later', 'claim.humans.not-a-ladder'],
          sourceIds: [
            'source.humans.neubauer-2018-brain-shape',
            'source.humans.hublin-2017-irhoud',
            'source.humans.nhm-modern-humans',
          ],
        },
      ],
    },
    {
      id: 'section.humans.across-a-continent',
      heading: 'Evidence across a continent',
      purpose: 'Establish the spatial and chronological spread of the evidence',
      modules: [
        {
          id: 'module.humans.africa-evidence-map',
          type: 'historical-map',
          eyebrow: 'Sites',
          title: 'Five finds across Africa',
          body: 'Four of these markers are fossil sites. One, Olorgesailie, is a toolmaking site. Compare the distances between them with the dates on each marker.',
          mediaId: 'media.humans.africa-evidence-map',
          periodLabel: 'c. 320,000–160,000 years ago',
          focusPlace: 'Africa',
          modernContext: 'Morocco, Ethiopia, Kenya, and South Africa today',
          accessibleSummary: 'Five markers are spread across Africa. In the far northwest, Jebel Irhoud in Morocco, about 315,000 years ago. Near the southern end of the continent, Florisbad in South Africa, about 259,000 years ago. Three markers sit closer together in eastern Africa: Omo Kibish in Ethiopia, at least 233,000 years ago; Herto in Ethiopia, about 160,000 years ago; and Olorgesailie in Kenya, a toolmaking site dated to about 320,000 to 305,000 years ago. The finds are separated by thousands of kilometres and by more than 150,000 years, and they do not cluster around any one region. There is no centre to point to.',
          compactLabel: 'Coordinates verified per site · modern coasts for orientation',
          coordinateNote: 'Jebel Irhoud, Herto, and Florisbad are placed from published surveyed or GPS coordinates. Omo Kibish and Olorgesailie are placed from published area descriptions and are drawn with a wider, softer halo to show that lower precision.',
          uncertaintyNote: 'A marker shows where evidence survived and was found, not the only place people lived. Olorgesailie is a whole basin, not a spot. Coastlines are modern and are here for orientation only; they are not a reconstruction of the shorelines, lakes, or deserts of 300,000 years ago.',
          depictionStatus: 'illustrative-reconstruction',
          claimIds: ['claim.humans.sites-spread', 'claim.humans.map-points-are-areas'],
          sourceIds: [
            'source.humans.natural-earth',
            'source.humans.benncer-2023-irhoud',
            'source.humans.white-2003-herto',
            'source.humans.douglas-2009-florisbad',
            'source.humans.potts-2020-variability',
            'source.humans.roceeh-road',
          ],
        },
        {
          id: 'module.humans.no-centre',
          type: 'prose',
          body: 'Line up the dates with the distances, and no simple story survives. The oldest fossils are in Morocco. The next oldest are at Florisbad in South Africa — more than seven thousand kilometres away. The eastern African fossils, in the region everyone used to point to, are younger than both.\n\nThe Omo Kibish fossil shows how careful dating has to be. It lies under a layer of volcanic ash. That ash matches an eruption dated to about 233,000 years ago (give or take 22,000). Because the ash fell on top, the fossil below must be older. How much older? This evidence cannot say. A minimum age is real information — a floor, not a full measurement.\n\nTaken together, the finds do not point to one special place. Researchers cannot currently name one time and place where our ancestry was trapped in a small region. That careful wording matters: it says nobody can identify such a place now — not that no such place ever existed.\n\nSpread out, though, is not the same as cut off.',
          claimIds: [
            'claim.humans.sites-spread',
            'claim.humans.omo-minimum-age',
            'claim.humans.no-single-birthplace',
          ],
          sourceIds: [
            'source.humans.vidal-2022-omo',
            'source.humans.grun-1996-florisbad',
            'source.humans.bergstrom-2021-ancestry',
            'source.humans.scerri-2018-subdivided',
          ],
        },
      ],
    },
    {
      id: 'section.humans.connected-not-sealed-off',
      heading: 'Connected, not sealed off',
      purpose: 'Explain the connections and conditions that make a continent-wide origin possible',
      modules: [
        {
          id: 'module.humans.irhoud-tools',
          type: 'evidence',
          title: 'Middle Stone Age tools from Jebel Irhoud',
          artifactLabel: 'Middle Stone Age tools · Jebel Irhoud',
          body: 'These tools came from the same layers as the Moroccan fossils. The burned ones helped date the site. Most are pointed and worked on both edges. Others were struck from stone cores that had been shaped first, so the maker could plan the flake before knocking it off — several steps ahead in a material that punishes mistakes.\n\nToolkits built on the same ideas show up in far-apart parts of Africa around 300,000 years ago. “Around” still covers tens of thousands of years. Whole regions, especially West and Central Africa, have barely been studied. Even so, this shift is not limited to one valley.',
          mediaId: 'media.humans.jebel-irhoud-tools',
          claimIds: ['claim.humans.msa-broadly-contemporary', 'claim.humans.record-sparse'],
          sourceIds: [
            'source.humans.richter-2017-irhoud-age',
            'source.humans.mpi-irhoud-presskit',
            'source.humans.scerri-2018-subdivided',
          ],
        },
        {
          id: 'module.humans.connections',
          type: 'knowledge',
          eyebrow: 'Olorgesailie, southern Kenya',
          title: 'Long-distance stone and pigment',
          body: 'Layers in one Kenyan basin, dated to about 320,000–305,000 years ago, show how far one community’s world reached. The dig is a joint project of the Smithsonian and the National Museums of Kenya.',
          items: [
            {
              label: 'Obsidian from far off',
              detail: 'Volcanic glass at the site came from sources 25 to 95 kilometres away. Earlier toolmakers in the same basin mostly used stone from within about five kilometres.',
            },
            {
              label: 'Pigment, deliberately made',
              detail: 'Lumps of iron-rich rock were carried in and processed to make red colouring.',
            },
            {
              label: 'What the distance implies',
              detail: 'Stone moving that far suggests trade between groups, or one group travelling much farther. The rock cannot tell which. Either way, the world had grown.',
            },
            {
              label: 'Climate kept redrawing the map',
              detail: 'African deserts, grasslands, and forests grew and shrank again and again. That could split groups apart for long stretches, then bring them back into contact. Researchers suggest this as one cause; the dating is still too rough to prove it drove the pattern.',
            },
          ],
          claimIds: [
            'claim.humans.olorgesailie-networks',
            'claim.humans.transport-implies-connection',
            'claim.humans.climate-structure',
          ],
          sourceIds: [
            'source.humans.brooks-2018-olorgesailie',
            'source.humans.potts-2020-variability',
            'source.humans.scerri-2018-subdivided',
          ],
        },
      ],
    },
    {
      id: 'section.humans.what-dna-adds',
      heading: 'What DNA adds — and what it cannot',
      purpose: 'Add the genetic evidence and state the honest limits alongside it',
      modules: [
        {
          id: 'module.humans.what-dna-adds',
          type: 'prose',
          body: 'No DNA has ever been recovered from an African human fossil this old. Heat and damp break genetic material down, and 300,000 years is far beyond what usually survives in Africa. So the genetic evidence for this period does not come from the fossils. It comes from the DNA of people living now, read backwards.\n\nIn 2023, a team modelled genomes from groups across Africa, including 44 newly sequenced Nama genomes from the south. The best fit was not one ancestral group splitting cleanly into branches. It was two or more groups, only a little different from each other, exchanging people and genes across hundreds of thousands of years.\n\nRead that carefully. It describes what a model fits — not what anyone watched happen. The same researchers show that the choice of model does a lot of the work. What makes it worth knowing is that a third kind of evidence, after bone and stone, points the same way: many groups, spread out, staying in touch.',
          claimIds: [
            'claim.humans.adna-limits',
            'claim.humans.dna-weak-structure',
            'claim.humans.structured-populations',
          ],
          sourceIds: [
            'source.humans.ragsdale-2023-stem',
            'source.humans.bergstrom-2021-ancestry',
            'source.humans.scerri-2018-subdivided',
          ],
        },
        {
          id: 'module.humans.open-questions',
          type: 'knowledge',
          eyebrow: 'Limits',
          title: 'Boundaries, blank spaces, and open models',
          body: 'That our species came from Africa is not in doubt. Almost every detail inside that answer is still being argued — and the arguments are of different kinds.',
          items: [
            {
              label: 'Where the line goes',
              detail: 'Researchers disagree about which fossils count as Homo sapiens. Some put Jebel Irhoud and Florisbad in a different species. The fight is about where to draw a line on a slowly changing family tree — and there may be no sharp line to find.',
            },
            {
              label: 'Where nobody has looked',
              detail: 'The record is thin and uneven. Bone survives in some places and not others. Digging has been funded and allowed far more in some countries than in others. A blank spot on the map is not proof that place was empty.',
            },
            {
              label: 'Whether a birthplace existed',
              detail: 'No one can currently name one time and place where our ancestry was limited to a small region. That is not the same as proving no such place ever existed.',
            },
            {
              label: 'Who left no descendants',
              detail: 'DNA from living people can only reach ancestral groups that still have living descendants. Groups whose lines ended leave no trace in this method.',
            },
          ],
          claimIds: [
            'claim.humans.species-boundary-contested',
            'claim.humans.record-sparse',
            'claim.humans.no-single-birthplace',
            'claim.humans.adna-limits',
          ],
          sourceIds: [
            'source.humans.scerri-2018-subdivided',
            'source.humans.stringer-2016-origin',
            'source.humans.bergstrom-2021-ancestry',
            'source.humans.ragsdale-2023-stem',
          ],
        },
      ],
    },
    {
      id: 'section.humans.check-and-complete',
      heading: 'World Check',
      purpose: 'Use the distribution of evidence and explain a limit of it',
      modules: [
        {
          id: 'module.humans.prompt-best-supported-conclusion',
          type: 'prompt',
          promptId: 'prompt.humans.best-supported-conclusion',
          claimIds: [],
          sourceIds: [],
        },
        {
          id: 'module.humans.prompt-evidence-and-limit',
          type: 'prompt',
          promptId: 'prompt.humans.evidence-and-limit',
          claimIds: [],
          sourceIds: [],
        },
      ],
    },
  ],
  claimIds: homoSapiensOriginsClaims.map((claim) => claim.id),
  sourceIds: homoSapiensOriginsSources.map((source) => source.id),
  mediaIds: [
    'media.humans.jebel-irhoud-excavation',
    'media.humans.jebel-irhoud-cranium',
    'media.humans.jebel-irhoud-tools',
    'media.humans.africa-evidence-map',
    'media.humans.africa-origins-card',
  ],
  promptIds: ['prompt.humans.best-supported-conclusion', 'prompt.humans.evidence-and-limit'],
};

export const homoSapiensOriginsCards: KnowledgeCard[] = [
  {
    id: 'card.idea.origins-across-africa',
    title: 'Our Species Began Across Africa',
    category: 'idea',
    cardClass: 'foundation',
    date: {
      startYear: -313000,
      endYear: -158000,
      display: 'c. 315,000–160,000 years ago',
      approximate: true,
    },
    place: 'Across Africa',
    significance: 'Fossils, stone tools, and DNA all point the same way: our species began among many connected groups spread across Africa — with no single birthplace to name.',
    revealTitle: 'No single birthplace',
    revealBody: 'You put fossil, tool, and DNA evidence together, worked out what the spread of finds supports, and named what it still cannot settle.',
    depictionLabel: 'Evidence locations · modern coasts for orientation',
    facts: [
      'Oldest known fossils of our species: Jebel Irhoud, Morocco, about 315,000 years ago',
      'Comparable finds in South Africa and Ethiopia span more than 150,000 years',
      'A modern-looking face appeared before the rounded braincase did',
      'DNA of living people fits several weakly separated groups linked by long contact',
      'No single birthplace has been identified',
    ],
    lessonIds: ['lesson.humans.homo-sapiens-origins'],
    sourceIds: [
      'source.humans.hublin-2017-irhoud',
      'source.humans.scerri-2018-subdivided',
      'source.humans.bergstrom-2021-ancestry',
      'source.humans.ragsdale-2023-stem',
    ],
    mediaId: 'media.humans.africa-origins-card',
    unlockLessonId: 'lesson.humans.homo-sapiens-origins',
  },
];

export const homoSapiensOriginsContent: AuthoredContentModule = {
  sources: homoSapiensOriginsSources,
  claims: homoSapiensOriginsClaims,
  media: homoSapiensOriginsMedia,
  prompts: homoSapiensOriginsPrompts,
  lessons: [homoSapiensOriginsLesson],
  cards: homoSapiensOriginsCards,
};
