import type { KnowledgeCard, LessonModule, MediaAsset, Source } from '../../src/domains/contracts';
import { mediaLocator } from '../shared/media-locator';

export const indusMediaSources: Source[] = [
  { id: 'source.indus.locator-relief', title: 'Natural Earth: Cross-blended Hypsometric Tints with Shaded Relief and Water', url: 'https://www.naturalearthdata.com/downloads/50m-raster-data/50m-cross-blend-hypso/', publisher: 'Natural Earth contributors', accessedOn: '2026-09-13', licenseOrUse: 'Public domain. Georeferenced HYP_50M_SR_W raster cropped for South Asia and an Africa–Asia locator inset; exact crop, file version discrepancy, hash, geographic edit target, and full illustration prompts preserved in the map brief. Modern terrain and coastline for orientation, not a Bronze Age landscape reconstruction.', reviewStatus: 'reviewed' },
  { id: 'source.indus.locator-river', title: 'Natural Earth: 1:50m rivers and lake centerlines', url: 'https://www.naturalearthdata.com/downloads/50m-physical-vectors/50m-rivers-lake-centerlines/', publisher: 'Natural Earth contributors', accessedOn: '2026-09-13', licenseOrUse: 'Public-domain vector geography; Indus features from the v5.1.2 repository tag. Generalized modern river course only. Extracted source geometry and checksum retained; no ancient channels inferred.', reviewStatus: 'reviewed' },
  { id: 'source.indus.locator-relief-crosscheck', title: 'South Asia relief map blank', url: 'https://commons.wikimedia.org/wiki/File:South_Asia_relief_map_blank.png', publisher: 'BoH, adapted from maps-for-free.com', accessedOn: '2026-09-13', licenseOrUse: 'CC0. Independent reference for the Indian peninsula, Sri Lanka, northern mountain belt, and flanking seas. Preserved in research as a cross-check; it is not the geographic edit target.', reviewStatus: 'reviewed' },
  { id: 'source.indus.reservoir-photo', title: 'Water reservoir at Dholavira site', url: 'https://commons.wikimedia.org/wiki/File:Water_reservoir_at_Dholavira_site.jpg', publisher: 'Bhajish Bharathan / Wikimedia Commons', accessedOn: '2026-09-12', licenseOrUse: 'Photograph, May 27, 2017. CC BY-SA 4.0: https://creativecommons.org/licenses/by-sa/4.0/ . Original evidence view resized and compressed without cropping or retouching. A separately labeled AI-assisted reservoir reconstruction adapts this photo and is also CC BY-SA 4.0.', reviewStatus: 'reviewed' },
  { id: 'source.indus.weights-photo', title: 'Cubical weights from Mohenjo-daro, Ashmolean Museum', url: 'https://commons.wikimedia.org/wiki/File:Cubical_weights_Mohenjodaro_Ashmolean.jpg', publisher: 'Zunkir / Wikimedia Commons', accessedOn: '2026-09-12', licenseOrUse: 'Photograph, August 23, 2022. CC BY-SA 4.0: https://creativecommons.org/licenses/by-sa/4.0/ . Resized and compressed without retouching. Source identifies three chert weights from Mohenjo-daro; no mass is inferred from apparent size.', reviewStatus: 'reviewed' },
  { id: 'source.indus.locator-natural-earth', title: 'Natural Earth 1:50m land, pinned v5.1.2 distribution', url: 'https://www.naturalearthdata.com/downloads/50m-physical-vectors/50m-land/', publisher: 'Natural Earth contributors', accessedOn: '2026-09-12', licenseOrUse: 'Public-domain geographic data: https://www.naturalearthdata.com/about/terms-of-use/ . Modern coastline only; preserved crop, checksum and deterministic rendering in the map research note.', reviewStatus: 'reviewed' },
  { id: 'source.indus.locator-getty-harappa', title: 'Harappa archaeological site, TGN 8039784', url: 'https://www.getty.edu/vow/TGNFullDisplay?english=Y&find=&nation=&place=&subjectid=8039784', publisher: 'Getty Thesaurus of Geographic Names', accessedOn: '2026-09-12', licenseOrUse: 'Site-coordinate facts used; no copyrighted map or image reproduced. Cross-checked against an independent field-study location.', reviewStatus: 'reviewed' },
  { id: 'source.indus.locator-harappa-field-study', title: 'Diversity Analysis of Insects of the Thorn Forest Community at Harappa Archaeological Site, Pakistan', url: 'https://www.zsp.com.pk/pdf46/1091-1099%20%2827%29%20PJZ-1694-14%2014-7-14.pdf', publisher: 'Nazir, Sharif, Arshad and Khan, Pakistan Journal of Zoology 46(4), 2014', accessedOn: '2026-09-12', licenseOrUse: 'Page 1092, study-area coordinates only. Independent geographic cross-check; no ecological claim used as historical evidence and no figure reproduced.', reviewStatus: 'reviewed' },
];

const mapSources = ['source.indus.locator-natural-earth', 'source.indus.locator-relief', 'source.indus.locator-river', 'source.indus.locator-relief-crosscheck', 'source.indus.locator-getty-harappa', 'source.indus.locator-harappa-field-study', 'source.indus.moenjodaro', 'source.indus.dholavira'];
const brief = 'docs/research/indus-cities-and-signs.md#image-lifecycle';
export const indusMedia: MediaAsset[] = [
  { id: 'media.indus.cities-locator-map', locator: mediaLocator('media.indus.cities-locator-map'), alt: 'Illustrated map of South Asia: India’s peninsula extends into the Indian Ocean, with Pakistan to its northwest and the Himalayas to the north. Harappa and Mohenjo-daro are in Pakistan; Dholavira is in northwestern India. An Africa–Asia inset outlines the main map’s region east of Africa.', depictionMode: 'map', depictionLabel: 'Illustrated locator · modern geography', rightsLabel: 'Chronos illustrated edit · Natural Earth geography, Public Domain', sourceIds: mapSources, visualBriefRef: 'docs/research/indus-locator-map.md', reviewStatus: 'approved' },
  { id: 'media.indus.street-reconstruction', locator: mediaLocator('media.indus.street-reconstruction'), alt: 'Reconstruction of a brick neighborhood: water from a household bathing floor enters a street drain, while a worker clears sediment from an exposed opening. People carry jars along the lane.', depictionMode: 'evidence-based-reconstruction', depictionLabel: 'Reconstruction · documented connections in an imagined neighborhood', rightsLabel: 'Chronos original · AI-assisted archaeological reconstruction', sourceIds: ['source.indus.street-drains', 'source.indus.moenjodaro'], visualBriefRef: brief, reviewStatus: 'approved' },
  { id: 'media.indus.reservoir-reconstruction', locator: mediaLocator('media.indus.reservoir-reconstruction'), alt: 'Reconstruction based on the photographed Dholavira basin, with stored water below the stone walls and a few people carrying jars along the dry edge.', depictionMode: 'evidence-based-reconstruction', depictionLabel: 'Reconstruction · water level and people are illustrative', rightsLabel: 'Chronos AI-assisted adaptation of Bhajish Bharathan’s photograph · CC BY-SA 4.0', sourceIds: ['source.indus.reservoir-photo', 'source.indus.dholavira'], visualBriefRef: brief, reviewStatus: 'approved' },
  { id: 'media.indus.reservoir', locator: mediaLocator('media.indus.reservoir'), alt: 'An excavated reservoir at Dholavira, with a broad empty basin, stone-lined edges and the remains of buildings above it.', depictionMode: 'evidence', depictionLabel: 'Site photograph · excavated reservoir', rightsLabel: 'Bhajish Bharathan · CC BY-SA 4.0 · resized and compressed', sourceIds: ['source.indus.reservoir-photo', 'source.indus.dholavira'], visualBriefRef: brief, reviewStatus: 'approved' },
  { id: 'media.indus.weights', locator: mediaLocator('media.indus.weights'), alt: 'Three roughly cubical stone weights from Mohenjo-daro, displayed from larger to smaller in the Ashmolean Museum.', depictionMode: 'evidence', depictionLabel: 'Surviving objects · modern museum display', rightsLabel: 'Zunkir · CC BY-SA 4.0 · resized and compressed', sourceIds: ['source.indus.weights-photo', 'source.indus.measuring'], visualBriefRef: brief, reviewStatus: 'approved' },
  { id: 'media.indus.seal', locator: mediaLocator('media.indus.seal'), alt: 'The Met catalog image for seal 49.40.2 shows a horned animal facing an object and a row of signs above it.', depictionMode: 'evidence', depictionLabel: 'Museum image of the seal design · Met 49.40.2', rightsLabel: 'The Metropolitan Museum of Art · Dodge Fund, 1949 · Public Domain', sourceIds: ['source.indus.met-seal'], visualBriefRef: brief, reviewStatus: 'approved' },
];

export const indusVisualModules: Record<string, LessonModule> = {
  map: { id: 'module.indus.cities-locator-map', type: 'historical-map', eyebrow: 'Place & landscape', title: 'The Indus cities in South Asia', body: 'The three cities lie toward the northwest of South Asia. Harappa is northeast of Mohenjo-daro; Dholavira is farther south and east, near the Arabian Sea. They are three examples from a much larger settlement network.', mediaId: 'media.indus.cities-locator-map', periodLabel: 'c. 2600–1900 BCE', focusPlace: 'Harappa, Mohenjo-daro and Dholavira', modernContext: 'These cities were in South Asia, in present-day Pakistan and northwestern India. The inset places this region east of Africa, on the northern side of the Indian Ocean.', accessibleSummary: 'India’s peninsula projects into the Indian Ocean, between the Arabian Sea to the west and the Bay of Bengal to the east. The Himalayas run along the north. Harappa and Mohenjo-daro are in present-day Pakistan; Dholavira is in northwestern India. Harappa is northeast of Mohenjo-daro; Dholavira is southeast. The inset locates the main map in southern Asia, east of Africa. Its rectangle shows the map extent, not an ancient territory.', compactLabel: 'Illustrated locator · modern geography', coordinateNote: 'Source: Natural Earth relief and modern river geography; city coordinates checked against UNESCO, Getty and the Harappa field study. The inset rectangle matches the main map’s extent.', uncertaintyNote: 'This is a locator using modern geography. Ancient river channels and shorelines changed; terrain colors do not reconstruct Bronze Age vegetation. The inset box marks the area enlarged, not a civilization’s boundary.', depictionStatus: 'illustrative-reconstruction', claimIds: ['claim.indus.regional-cities', 'claim.indus.south-asia-location'], sourceIds: mapSources },
  drainage: { id: 'module.indus.drainage-scene', type: 'scene', title: 'Follow water beyond one home', body: 'Return to the opening reconstruction to trace the connection and the work it needed.', mediaId: 'media.indus.street-reconstruction', hotspots: [
    { label: 'A household connection', detail: 'At the left, water leaves a bathing floor and joins the street channel. Excavated drains support this relationship; this house and its exposed corner are an illustrative composite.' },
    { label: 'A shared channel', detail: 'Follow the drain along the lane. Many real street drains were covered. The illustration exposes part of this one so you can see the connection below the walking surface.' },
    { label: 'Work that continued', detail: 'The worker clearing sediment makes maintenance visible. Cleaned traps are documented; the person, tool and moment are imagined.' },
  ], claimIds: ['claim.indus.household-drainage'], sourceIds: ['source.indus.street-drains', 'source.indus.moenjodaro'] },
  reservoir: { id: 'module.indus.reservoir-evidence', type: 'evidence', title: 'Holding water for later', artifactLabel: 'Dholavira · reconstruction and excavated reservoir', body: 'Picture the broad basin holding seasonal water. Then compare it with the excavated structure: its stone-lined edges survive, but the ancient water level does not. The illustration helps us picture storage without telling us who organized it.', mediaId: 'media.indus.reservoir-reconstruction', layout: 'stacked', scaleNote: 'The basin’s visible form follows the photograph. Water level, people, restored surfaces and light are illustrative; neither image is a measured plan.', comparison: { mediaId: 'media.indus.reservoir', label: 'The surviving reservoir', detail: 'Bhajish Bharathan’s 2017 photograph shows the empty excavated basin used as the reconstruction reference.', sourceIds: ['source.indus.reservoir-photo', 'source.indus.dholavira'] }, claimIds: ['claim.indus.water-storage'], sourceIds: ['source.indus.reservoir-photo', 'source.indus.dholavira'] },
  weights: { id: 'module.indus.weights-evidence', type: 'evidence', title: 'Objects behind a shared standard', artifactLabel: 'Mohenjo-daro weights · Ashmolean Museum', body: 'Look at the three shaped stone objects. Their different sizes are visible; their masses are not. The shared standard comes from researchers measuring weights across sites, not from judging one photograph.', mediaId: 'media.indus.weights', layout: 'stacked', scaleNote: 'This is a modern museum arrangement without a measurement scale. It does not show an excavated grouping or prove particular weight ratios.', claimIds: ['claim.indus.shared-weights'], sourceIds: ['source.indus.weights-photo', 'source.indus.measuring'] },
  seal: { id: 'module.indus.seal-evidence', type: 'evidence', title: 'A design we can inspect', artifactLabel: 'Indus stamp seal · Met 49.40.2', body: 'Find the animal, the object in front of it and the short row of signs. Their presence is visible. Naming the pictured object or translating the signs requires further evidence.', mediaId: 'media.indus.seal', scaleNote: 'The original seal is about 3.8 centimetres across. This catalog image presents its design; it is not a measured view of its surface or depth.', lookHere: [{ label: 'Short inscription', detail: 'The signs sit above the animal. Recognizing a repeated form is different from knowing what it means.', sourceIds: ['source.indus.met-seal', 'source.indus.rao-response'] }], claimIds: ['claim.indus.seal-object', 'claim.indus.undeciphered-signs'], sourceIds: ['source.indus.met-seal', 'source.indus.rao-response'] },
};

export const indusSealCard: KnowledgeCard = {
  id: 'card.indus.stamp-seal', title: 'Indus Stamp Seal', category: 'artifact', cardClass: 'witness',
  date: { startYear: -2600, endYear: -1900, display: 'c. 2600–1900 BCE', approximate: true }, place: 'Indus region',
  significance: 'A buffalo in miniature, carved into a stone stamp small enough to hold in your palm.',
  revealTitle: 'Carved to leave a mark', revealBody: 'Press a seal into soft clay, lift it away, and a raised copy of the design remains. Around four thousand years ago, someone chose this animal and these tiny signs to make a mark they could stamp again and again.',
  depictionLabel: 'Museum image of the seal design · Met 49.40.2',
  facts: ['The seal is made from steatite, a soft stone, which was heated after carving.', 'It is about 3.8 centimetres across.', 'The buffalo’s sweeping horns sit just below a row of tiny signs.'],
  lessonIds: ['lesson.indus.cities-and-signs'], sourceIds: ['source.indus.met-seal', 'source.indus.rao-response'], mediaId: 'media.indus.seal', unlockLessonId: 'lesson.indus.cities-and-signs', recallPrompt: 'How could someone use this carved stone to repeat the same design?',
};
