import type { Claim, Lesson, Source, UnderstandingPrompt } from '../../src/domains/contracts';
import type { AuthoredContentModule } from '../assemble';
import { indusMedia, indusMediaSources, indusSealCard, indusVisualModules } from './indus-media';

export const indusSources: Source[] = [
  { id: 'source.indus.dholavira', title: 'Dholavira: a Harappan City', url: 'https://whc.unesco.org/en/list/1645/', publisher: 'UNESCO World Heritage Centre / India', accessedOn: '2026-09-11', licenseOrUse: 'Research citation; description and Outstanding Universal Value closely reviewed. Photographs require separate clearance.', reviewStatus: 'reviewed' },
  { id: 'source.indus.moenjodaro', title: 'Archaeological Ruins at Moenjodaro', url: 'https://whc.unesco.org/en/list/138/', publisher: 'UNESCO World Heritage Centre / Pakistan', accessedOn: '2026-09-11', licenseOrUse: 'Research citation; Brief synthesis on site location and street drainage reviewed. Summary brick wording and inherited building names are not adopted.', reviewStatus: 'reviewed' },
  { id: 'source.indus.street-drains', title: 'Mohenjo-daro Street with Drains', url: 'https://www.harappa.com/blog/mohenjo-daro-street-drains', publisher: 'Harappa.com, citing Wheeler and Possehl', accessedOn: '2026-09-11', licenseOrUse: 'Research citation; paragraphs on household outflows, covered drains and cleaning closely reviewed. No image reproduction.', reviewStatus: 'reviewed' },
  { id: 'source.indus.measuring', title: 'Measuring the Harappan world', url: 'https://www.harappa.com/sites/default/files/pdf/Kenoyer%202010%20Measuring%20the%20Harappan%20World.pdf', publisher: 'J. Mark Kenoyer, in The Archaeology of Measurement (2010)', accessedOn: '2026-09-11', licenseOrUse: 'Research citation; pp. 115–117, table 9.3 and figure 9.10 closely reviewed. No figure reproduction.', reviewStatus: 'reviewed' },
  { id: 'source.indus.harp-weights', title: 'Weights, Harappa', url: 'https://www.harappa.com/slide/weights-harappa', publisher: 'Harappa Archaeological Research Project / Jonathan Mark Kenoyer', accessedOn: '2026-09-11', licenseOrUse: 'Research citation of excavation caption; photograph not licensed for publication here.', reviewStatus: 'reviewed' },
  { id: 'source.indus.harp-seals', title: 'Seals & tablets', url: 'https://www.harappa.com/indus/30.html', publisher: 'Harappa Archaeological Research Project / Jonathan Mark Kenoyer', accessedOn: '2026-09-11', licenseOrUse: 'Research citation of the Mound E house assemblage; no photograph reproduction.', reviewStatus: 'reviewed' },
  { id: 'source.indus.met-seal', title: 'Stamp seal: buffalo with incense burner (?) — object 49.40.2', url: 'https://www.metmuseum.org/art/collection/search/324063', publisher: 'The Metropolitan Museum of Art', accessedOn: '2026-09-11', licenseOrUse: 'Object description and details closely reviewed. Public-domain catalog image acquired and reviewed September 12; resized/compressed only, with no retouching. The view is labeled as the seal design because the catalog does not distinguish seal from impression.', reviewStatus: 'reviewed' },
  { id: 'source.indus.rao-response', title: 'Entropy, the Indus Script, and Language: A Reply to Richard Sproat', url: 'https://homes.cs.washington.edu/~rao/IndusCompLing.html', publisher: 'Rao and colleagues, Computational Linguistics 36(4), 2010; author manuscript', accessedOn: '2026-09-11', licenseOrUse: 'Research citation; sections 2–4 on statistical evidence, competing sign-system explanations and limits closely reviewed. No computational replication claimed.', reviewStatus: 'reviewed' },
  { id: 'source.indus.green-governance', title: 'Of Revenue Without Rulers: Public Goods in the Egalitarian Cities of the Indus Civilization', url: 'https://www.frontiersin.org/journals/political-science/articles/10.3389/fpos.2022.823071/full', publisher: 'Adam S. Green, Frontiers in Political Science (2022)', accessedOn: '2026-09-11', licenseOrUse: 'Research citation; governance evidence section closely reviewed. Egalitarian government remains the author’s interpretation; third-party figures are not reproduced.', reviewStatus: 'reviewed' },
  { id: 'source.indus.harp-settlement', title: 'Changing Settlement at Harappa', url: 'https://www.harappa.com/slide/changing-settlement-harappa', publisher: 'Harappa Archaeological Research Project, Harappa 2000–2001', accessedOn: '2026-09-11', licenseOrUse: 'Excavation-project period and settlement-plan caption closely reviewed; no plan reproduction.', reviewStatus: 'reviewed' },
  { id: 'source.indus.kenoyer-tradition', title: 'Cultures and Societies of the Indus Tradition', url: 'https://www.harappa.com/sites/default/files/pdf/CulturesSocietiesIndusTrad.pdf', publisher: 'J. Mark Kenoyer (2006)', accessedOn: '2026-09-11', licenseOrUse: 'Research citation; Table 1 and Localization Era discussion, PDF pp. 6 and 9, closely reviewed. Older linguistic/religious identifications are not adopted.', reviewStatus: 'reviewed' },
  { id: 'source.indus.iln-marshall', title: 'First images of the announcement in the Illustrated London News (September 20, 1924)', url: 'https://www.harappa.com/blog/first-images-announcement-illustrated-london-news', publisher: 'Harappa.com, quoting John Marshall in The Illustrated London News', accessedOn: '2026-10-02', licenseOrUse: 'Research citation; short quotations of the 1924 text as quoted on the page (date, 400-mile distance, dating sentence and the later note that the first age estimate was off by one or two thousand years). No image reproduction.', reviewStatus: 'reviewed' },
  { id: 'source.indus.sayce-letter', title: 'Prof. A. H. Sayce, letter on the Indus discoveries, The Illustrated London News (September 27, 1924)', url: 'https://www.harappa.com/slide/prof-ah-sayce-remarkable-discoveries-india', publisher: 'Harappa.com archive of the 1924 letter', accessedOn: '2026-10-02', licenseOrUse: 'Research citation; short quotations from the letter (“practically identical”, “might have come from the same hand”) and its dates for the Susa tablets. Sayce’s comparison is reported as his 1924 argument, not as a modern finding. No image reproduction.', reviewStatus: 'reviewed' },
  { id: 'source.indus.dholavira-bisht', title: 'Excavations at Dholavira 1989–2005', url: 'https://ancientportsantiques.com/wp-content/uploads/Documents/PLACES/IndOc-Gulf/Dholavira-Bisht2015.pdf', publisher: 'R. S. Bisht, Archaeological Survey of India (2015); copy hosted by ancientportsantiques.com', accessedOn: '2026-10-02', licenseOrUse: 'Research citation; signboard passages on pp. 112 and 228–231 closely reviewed (ten large gypsum-inlaid signs, find spot, 3.5 m passage width, wooden board since decayed, meaning unknown). No figure reproduction.', reviewStatus: 'reviewed' },
  ...indusMediaSources,
];

export const indusClaims: Claim[] = [
  { id: 'claim.indus.urban-period', statement: 'The Mature Harappan urban period is conventionally dated to about 2600–1900 BCE; individual settlements have longer histories.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.indus.kenoyer-tradition', 'source.indus.harp-settlement', 'source.indus.dholavira'], reviewStatus: 'reviewed' },
  { id: 'claim.indus.regional-cities', statement: 'Indus settlements occupied different environments across parts of present-day Pakistan and India, including Mohenjo-daro and Dholavira.', kind: 'observation', certainty: 'high', sourceIds: ['source.indus.moenjodaro', 'source.indus.dholavira'], reviewStatus: 'reviewed' },
  { id: 'claim.indus.south-asia-location', statement: 'The lesson’s three cities are in South Asia, in present-day Pakistan and northwestern India. The Indian peninsula projects into the Indian Ocean, east of Africa; the Himalayas lie along its north.', kind: 'observation', certainty: 'high', sourceIds: ['source.indus.locator-relief', 'source.indus.locator-relief-crosscheck', 'source.indus.locator-getty-harappa', 'source.indus.moenjodaro', 'source.indus.dholavira'], reviewStatus: 'reviewed' },
  { id: 'claim.indus.household-drainage', statement: 'At Mohenjo-daro, bathing-floor drains fed street drains; covers and settling traps formed part of a maintained drainage system.', kind: 'observation', certainty: 'high', sourceIds: ['source.indus.street-drains', 'source.indus.moenjodaro'], reviewStatus: 'reviewed' },
  { id: 'claim.indus.water-storage', statement: 'Dholavira used reservoirs and seasonal streams in a dry setting, with substantial stone construction.', kind: 'observation', certainty: 'high', sourceIds: ['source.indus.dholavira'], reviewStatus: 'reviewed' },
  { id: 'claim.indus.shared-weights', statement: 'Measured stone weights from Harappa and other Indus sites follow shared standards, with variation rather than perfect identity.', kind: 'observation', certainty: 'high', sourceIds: ['source.indus.measuring', 'source.indus.harp-weights'], reviewStatus: 'reviewed' },
  { id: 'claim.indus.weight-functions', statement: 'Weights could support controlled exchange; their association with gateways and craft areas also supports taxation as an interpretation, not a recovered transaction.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.indus.measuring', 'source.indus.harp-weights'], reviewStatus: 'reviewed' },
  { id: 'claim.indus.crafts-and-connections', statement: 'Dholavira preserves craft-working evidence and evidence of exchange within the Indus region and with Oman and Mesopotamia.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.indus.dholavira'], reviewStatus: 'reviewed' },
  { id: 'claim.indus.seal-object', statement: 'Met object 49.40.2 is a small steatite stamp seal with an animal, a short inscription and another depicted object whose identification is uncertain.', kind: 'observation', certainty: 'high', sourceIds: ['source.indus.met-seal'], reviewStatus: 'reviewed' },
  { id: 'claim.indus.seal-context', statement: 'Seals could make clay impressions, and a house by Harappa’s Mound E gateway contained several kinds of inscribed objects; the users’ identities are inferred.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.indus.harp-seals', 'source.indus.met-seal', 'source.indus.green-governance'], reviewStatus: 'reviewed' },
  { id: 'claim.indus.undeciphered-signs', statement: 'Indus inscriptions have no securely established reading; statistical regularities alone neither translate them nor settle whether they encode speech.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.indus.rao-response', 'source.indus.met-seal'], reviewStatus: 'reviewed' },
  { id: 'claim.indus.coordination-and-rule', statement: 'Shared standards and large communal works support organized cooperation; they do not by themselves identify rulers, political institutions or equal access.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.indus.green-governance', 'source.indus.dholavira'], reviewStatus: 'reviewed' },
  { id: 'claim.indus.urban-transformation', statement: 'After about 1900 BCE, settlement at Harappa contracted; wider changes in urban organization coexisted with continuing farming and craft traditions.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.indus.harp-settlement', 'source.indus.kenoyer-tradition'], reviewStatus: 'reviewed' },
  { id: 'claim.indus.trap-sand-heaps', statement: 'Excavators describe “little heaps of greenish-gray sand” beside the settling pools and traps of Indus street drains and read them as evidence that the traps were cleaned out periodically.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.indus.street-drains'], reviewStatus: 'reviewed' },
  { id: 'claim.indus.drain-construction', statement: 'Mohenjo-daro street drains were made of baked brick with specially shaped corner bricks and mud mortar; most were covered with flat baked bricks, wider ones with limestone blocks, and a layer of mud.', kind: 'observation', certainty: 'high', sourceIds: ['source.indus.street-drains', 'source.indus.moenjodaro'], reviewStatus: 'reviewed' },
  { id: 'claim.indus.drain-reuse', statement: 'Possehl observes that Mohenjo-daro drains were reused over time by raising their walls with more bricks, and describes one drain at the end of First Street that was 2 meters deep in places.', kind: 'observation', certainty: 'high', sourceIds: ['source.indus.street-drains'], reviewStatus: 'reviewed' },
  { id: 'claim.indus.dholavira-setting', statement: 'Dholavira stood on the arid island of Khadir in Gujarat; two seasonal streams supplied the walled city, a series of reservoirs lay east and south of the citadel, and stone masonry with mud-brick cores was a main building method.', kind: 'observation', certainty: 'high', sourceIds: ['source.indus.dholavira'], reviewStatus: 'reviewed' },
  { id: 'claim.indus.weight-numbers', statement: 'The smallest Indus weights are under one gram (about 0.86 g); the first seven weights double in the ratio 1:2:4:8:16:32:64; the most common weight is the 16th ratio, about 13.7 g.', kind: 'observation', certainty: 'high', sourceIds: ['source.indus.measuring', 'source.indus.harp-weights'], reviewStatus: 'reviewed' },
  { id: 'claim.indus.weights-taxation-argument', statement: 'Kenoyer notes that most scholars assume Indus weights served everyday market exchange, argues that the small number of weights relative to city size makes this probably invalid, and judges taxation or tithing much more probable, citing the highest concentration of weights at gateways and craft areas.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.indus.measuring'], reviewStatus: 'reviewed' },
  { id: 'claim.indus.dholavira-materials', statement: 'Dholavira preserves bead-processing workshops and objects made of copper, shell, stone, terracotta, gold and ivory.', kind: 'observation', certainty: 'high', sourceIds: ['source.indus.dholavira'], reviewStatus: 'reviewed' },
  { id: 'claim.indus.discovery-1924', statement: 'On September 20, 1924, John Marshall announced in the Illustrated London News the discovery of ruined cities at Harappa and Mohenjo-daro, about 400 miles apart, writing that knowledge of Indian antiquities went back hardly further than the third century BCE; the cities’ true age proved to be one or two thousand years off the first estimate.', kind: 'observation', certainty: 'high', sourceIds: ['source.indus.iln-marshall'], reviewStatus: 'reviewed' },
  { id: 'claim.indus.sayce-comparison', statement: 'In a letter published September 27, 1924, A. H. Sayce judged the Harappa and Mohenjo-daro seals “practically identical” with Proto-Elamite tablets from Susa dated about 2600–2300 BCE, and argued that this showed contact between Susa and northwestern India in the third millennium BCE.', kind: 'observation', certainty: 'high', sourceIds: ['source.indus.sayce-letter'], reviewStatus: 'reviewed' },
  { id: 'claim.indus.dholavira-signboard-find', statement: 'At Dholavira, ten unusually large signs, cut as gypsum inlays, were found lying in the western chamber of the north gate.', kind: 'observation', certainty: 'high', sourceIds: ['source.indus.dholavira-bisht'], reviewStatus: 'reviewed' },
  { id: 'claim.indus.dholavira-signboard-display', statement: 'The excavators infer that the gypsum signs were inlaid on a wooden board, since decayed, matching the 3.5-meter width of the north gate’s central passage and fixed above its doorway to be visible from afar; the inscription’s meaning is unknown.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.indus.dholavira-bisht'], reviewStatus: 'reviewed' },
  { id: 'claim.indus.dholavira-layout', statement: 'Dholavira’s walled city had a fortified citadel, a fortified Middle Town and a Lower Town; UNESCO’s description reads this layout as reflecting a stratified social order.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.indus.dholavira'], reviewStatus: 'reviewed' },
  { id: 'claim.indus.green-argument', statement: 'Adam Green argues that Indus shared standards and communal works fit organized cooperation among groups rather than rule by a political elite.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.indus.green-governance'], reviewStatus: 'reviewed' },
  { id: 'claim.indus.harappa-sequence', statement: 'Harappa’s earliest settlement dates to about 3300 BCE; by the end of the Harappan period, 2600–1900 BCE, most of the excavated plan was in use; after about 1900 BCE settlement retracted to Mound AB, Harappa Town and the northwest corner of Mound E, and continued to about 1300 BCE.', kind: 'observation', certainty: 'high', sourceIds: ['source.indus.harp-settlement'], reviewStatus: 'reviewed' },
];

export const indusPrompts: UnderstandingPrompt[] = [
  {
    id: 'prompt.indus.what-weights-show', bestOptionId: 'option.indus.same-units', lessonId: 'lesson.indus.cities-and-signs', kind: 'supported-selection', required: true, evidenceModuleIds: ['module.indus.weights-evidence'],
    question: 'Excavators have measured weights from Harappa and other Indus sites. The first seven units double each time, and real stones vary a little. Which statement goes only as far as that evidence can take it?',
    hint: 'Sort the statements by what the weights can show directly and what would need other evidence.',
    explanation: 'The weights show that people at different sites used the same units in a doubling series, so an agreement about quantity reached beyond any single city. That could help people coordinate exchange or collections. The weights alone do not name the people who set or enforced the standard, say how goods were divided among households, or give any meaning to the signs on seals.',
    options: [
      { id: 'option.indus.same-units', label: 'People at different sites weighed goods by the same units, so an agreement about quantity reached beyond any single city.', feedback: 'Yes. Weights from different sites fit the same series of units, even though individual stones vary a little.' },
      { id: 'option.indus.ruler-ordered-weights', label: 'One ruler ordered every weight made and controlled all trade from a single capital.', feedback: 'Reread “Who organized the cities?” What do researchers say shared standards and public works can and cannot show about who held authority?' },
      { id: 'option.indus.households-equal', label: 'Every household owned the same amount of goods, because everyone weighed with the same stones.', feedback: 'Think about what a weight records. Does anything in the lesson show how goods were divided between households?' },
      { id: 'option.indus.signs-read', label: 'Researchers can read the signs on Indus seals, because the weights and the signs belong to one system.', feedback: 'Reread “Seals and undeciphered signs.” What would a convincing reading have to explain, and do weights supply it?' },
    ],
  },
  {
    id: 'prompt.indus.water-needs-many-hands', lessonId: 'lesson.indus.cities-and-signs', kind: 'concise-explanation', required: true, evidenceModuleIds: ['module.indus.reservoir-evidence'], minimumResponseLength: 20,
    question: 'Choose one: the drains of Mohenjo-daro or the reservoirs of Dholavira. (1) Why could one family not have built it and kept it working alone? (2) Name one thing we still don’t know about who was in charge of the work.',
    hint: 'Think about what happens after the drain or reservoir is built. For part 2, remember what the lesson says about rulers and neighborhood groups.',
    explanation: 'A strong answer covers both parts. (1) It picks one system and shows that it reached beyond a single household or needed ongoing work. Mohenjo-daro: a household drain joined a street drain; the settling traps had to be emptied again and again, and excavators read the heaps of greenish-gray sand beside such traps as the leftovers; old drains were reused by raising their walls with more bricks. Dholavira: gathering seasonal water in reservoirs took planned construction and upkeep. (2) It names something still unknown, such as whether a ruler, a neighborhood group or another institution directed the work.',
  },
];

const sections: Lesson['sections'] = [
  {
    id: 'section.indus.cities-and-landscapes', heading: 'Cities across the Indus region', purpose: 'Locate the urban tradition and introduce coordination as a concrete historical problem.',
    modules: [
      indusVisualModules.map,
      { id: 'module.indus.cities-and-landscapes', type: 'prose', claimIds: ['claim.indus.urban-period', 'claim.indus.regional-cities', 'claim.indus.trap-sand-heaps'], sourceIds: ['source.indus.kenoyer-tradition', 'source.indus.moenjodaro', 'source.indus.dholavira', 'source.indus.street-drains'], body: 'Mohenjo-daro’s street drains had settling traps built in: pockets where sediment sinks while the water runs on. Beside such traps, excavators describe “little heaps of greenish-gray sand,” which they read as the leftovers of cleaning them out. Someone dug those traps clear, roughly four thousand years ago, and nothing tells us who. The Indus cities left drains, weights and seals in abundance, and writing no one can yet read.\n\nEarlier in this journey you saw cities held together by food, work and records. Here the records cannot be read, so the evidence is the work itself.\n\nAbout 2600–1900 BCE, large settlements flourished across parts of what are now Pakistan and India. Archaeologists call this the Mature Harappan period, after the site of Harappa. The dates describe a phase of city life, not every settlement’s lifetime.\n\nMohenjo-daro stood on the Indus plain in present-day Pakistan. Farther southeast, Dholavira sat on an arid island in Gujarat, now in India. They shared one regional tradition, yet their surroundings called for different solutions.' },
    ],
  },
  {
    id: 'section.indus.water-systems', heading: 'Water for city life', purpose: 'Explain connected drainage and seasonal storage as different forms of organized work.',
    modules: [
      { id: 'module.indus.drains', type: 'prose', claimIds: ['claim.indus.household-drainage', 'claim.indus.drain-construction', 'claim.indus.drain-reuse', 'claim.indus.trap-sand-heaps'], sourceIds: ['source.indus.street-drains', 'source.indus.moenjodaro'], body: 'Follow the water at Mohenjo-daro. In some houses it left a bathing floor, ran into a drain and joined a channel along the street. The street drains were baked brick, with shaped bricks for the corners and mud mortar in the joints. Most lay hidden under flat bricks, limestone blocks and a layer of mud.\n\nThen came the upkeep. One drain at the end of First Street ran two meters deep in places, and over time people reused such drains by raising their walls with more bricks. The traps had to be emptied again and again, which is what the sand heaps record. A drain inside one home fed a system that reached beyond it, and keeping water moving took repeated work, not only skill in building.' },
      indusVisualModules.drainage,
      { id: 'module.indus.reservoirs', type: 'prose', claimIds: ['claim.indus.water-storage', 'claim.indus.dholavira-setting'], sourceIds: ['source.indus.dholavira'], body: 'Dholavira faced the opposite problem. The city stood on the arid island of Khadir in Gujarat, and the two streams that served it flowed only in certain seasons. Its builders answered with a series of reservoirs to the east and south of the fortified citadel, and with walls of stone masonry over mud-brick cores.\n\nHolding seasonal water made it available long after it arrived. That meant planning where to put the basins, steering water into them and keeping the structures sound. The two cities show why a shared urban tradition did not mean one design copied everywhere.' },
      indusVisualModules.reservoir,
    ],
  },
  {
    id: 'section.indus.weights-and-work', heading: 'Shared measures and skilled work', purpose: 'Connect measured objects and craft production to coordination without assuming a particular transaction.',
    modules: [
      { id: 'module.indus.weights', type: 'prose', claimIds: ['claim.indus.shared-weights', 'claim.indus.weight-functions', 'claim.indus.weight-numbers', 'claim.indus.weights-taxation-argument'], sourceIds: ['source.indus.measuring', 'source.indus.harp-weights'], body: 'Small stone cubes tell another story. At Harappa, excavators found weights cut in graduated sizes. The smallest weighs under a gram. The first seven in the series double each time (1, 2, 4, 8, 16, 32, 64), and the most common weight, about 13.7 grams, is sixteen times the smallest. Other Indus sites follow the same pattern, though real stones vary a little.\n\nA balance lets people who share a standard agree on a quantity, even when they come from different places. What were the weights for? Most scholars have assumed everyday market trade. The archaeologist J. Mark Kenoyer replies that there are too few weights for cities that size, and that they cluster most thickly near gateways and in craft areas, where arriving goods could have been weighed and taxed. He thinks taxation or tithing much more probable. That is an interpretation, not a recorded transaction.' },
      indusVisualModules.weights,
      { id: 'module.indus.crafts', type: 'prose', claimIds: ['claim.indus.crafts-and-connections', 'claim.indus.dholavira-materials'], sourceIds: ['source.indus.dholavira'], body: 'At Dholavira, excavators found bead-working areas and objects made from copper, shell, stone, terracotta, gold and ivory. The site also preserves evidence of exchange with other Indus settlements, with Oman and with Mesopotamia. Making such objects took people who could obtain materials, work them and pass them on.\n\nWeights give us quantities. For marks and signs, we turn to seals.' },
    ],
  },
  {
    id: 'section.indus.seals-and-signs', heading: 'Seals and undeciphered signs', purpose: 'Distinguish an object’s observable features, excavated context and possible message.',
    modules: [
      { id: 'module.indus.seal-record', type: 'prose', claimIds: ['claim.indus.seal-object', 'claim.indus.seal-context', 'claim.indus.discovery-1924', 'claim.indus.sayce-comparison'], sourceIds: ['source.indus.met-seal', 'source.indus.harp-seals', 'source.indus.iln-marshall', 'source.indus.sayce-letter'], body: 'On September 20, 1924, the archaeologist John Marshall announced in the Illustrated London News that mounds at Harappa and Mohenjo-daro, about four hundred miles apart, covered the ruins of ancient cities. Until then, he wrote, knowledge of Indian antiquities went back “hardly further than the third century before Christ.” A week later the Assyriologist A. H. Sayce, a scholar of ancient Mesopotamia, wrote to the same paper. The seals from the new sites, he said, were “practically identical” with tablets from the ancient city of Susa dated 2600–2300 BCE, so alike that they “might have come from the same hand.” On Sayce’s argument, seals placed the new cities in the centuries of early Mesopotamia, one or two thousand years older than first thought.\n\nA stamp seal is an engraved stone that leaves an impression when pressed into soft clay. One Indus seal, now in the Metropolitan Museum of Art, is carved from steatite, a soft stone, and then heated. Its design combines a horned animal, which the museum identifies as a buffalo, a short row of signs and an object in front of the animal that the museum tentatively calls an incense burner. The question mark in its title is the museum admitting what it cannot be sure of: even naming a carved shape takes interpretation.\n\nAt Harappa, in a house on the main street to the southern gateway of Mound E, archaeologists found several kinds of seals and inscribed tablets together. The excavators suggest that some people, “possibly merchants,” used many kinds of inscribed objects. “Possibly” matters: the objects do not introduce their owners by any name we can read.' },
      indusVisualModules.seal,
      { id: 'module.indus.sign-limits', type: 'prose', claimIds: ['claim.indus.undeciphered-signs', 'claim.indus.dholavira-signboard-find', 'claim.indus.dholavira-signboard-display'], sourceIds: ['source.indus.rao-response', 'source.indus.met-seal', 'source.indus.dholavira-bisht'], body: 'Not every Indus sign is small. At Dholavira, excavators found ten unusually large signs lying in the western chamber of the north gate. Cut from gypsum, they had been inlaid in a wooden board that has since decayed; its size matched the 3.5-meter width of the gate’s central passage. The excavators think it was fixed above the doorway, where the white gypsum would be visible from afar. If so, everyone who came through that gate walked beneath it. Today no one can say what it said.\n\nTo decipher a script is to work out how its signs stand for a language. No reading of the Indus signs is securely established, and researchers disagree about how much spoken language they recorded, or whether they were a different kind of sign system. Repeated signs and patterns in their order show that the marks were organized, but a pattern alone does not tell us what a sign means. A convincing reading would have to explain inscriptions beyond the examples used to devise it and fit the objects’ contexts. Until then, a claimed king’s name or religious message is a claim to test.' },
    ],
  },
  {
    id: 'section.indus.organizing-cities', heading: 'Who organized the cities?', purpose: 'State what coordinated work supports while keeping political authority and unequal access open.',
    modules: [
      { id: 'module.indus.organizing-cities', type: 'prose', claimIds: ['claim.indus.coordination-and-rule', 'claim.indus.dholavira-layout', 'claim.indus.green-argument'], sourceIds: ['source.indus.green-governance', 'source.indus.dholavira'], body: 'Drains, reservoirs and shared weights did not maintain themselves. People organized labor, passed on skills and followed agreements that reached beyond a single household. Someone cleared the traps; someone raised the walls of old drains. Who directed them, we cannot read.\n\nResearchers read the same evidence differently. Adam Green argues that shared standards and communal works fit cities run by cooperation among groups rather than by rulers. Others see hierarchy, meaning unequal positions in society, in differences between neighborhoods and in Dholavira’s fortified citadel, Middle Town and Lower Town, a layout UNESCO’s description reads as a stratified social order. Large public works alone cannot decide between these views.\n\nA king is easy to imagine, and the evidence does not supply one. Equality is just as easy to imagine, and the evidence does not supply that either. Who held authority, and who shared in the benefits, is still open.' },
    ],
  },
  {
    id: 'section.indus.changing-settlements', heading: 'Changes after 1900 BCE', purpose: 'Distinguish the end of an urban phase from the disappearance of a population or all its knowledge.',
    modules: [
      { id: 'module.indus.changing-settlements', type: 'prose', claimIds: ['claim.indus.urban-transformation', 'claim.indus.harappa-sequence'], sourceIds: ['source.indus.harp-settlement', 'source.indus.kenoyer-tradition'], body: 'Harappa shows what change looked like. People first settled there around 3300 BCE, centuries before the cities’ great age, and by 2600–1900 BCE most of the excavated plan was in use. After about 1900 BCE, settlement pulled back to Mound AB, Harappa Town and one corner of Mound E, and continued to about 1300 BCE. A city had shrunk; the site was not empty.\n\nAcross the wider region, farming and skills such as pottery and bead-making went on even as the earlier organization of cities and exchange changed. The change unfolded over time, not in a single day when a people vanished.\n\nLook back at the sand beside the drain. The writing is still silent, but the traces are not: sand heaps, stone weights in a doubling series, a buffalo carved on a stamp seal, ten white signs lying in a gateway. They show people keeping water moving, measuring quantities and pressing signs into clay. What those signs say, and who directed the work, nobody yet knows.' },
    ],
  },
  {
    id: 'section.indus.understanding', heading: 'Explain the evidence', purpose: 'Check a shared-measure inference and ask for an explanation of collective water work and its limits.',
    modules: [
      { id: 'module.indus.shared-standards-check', type: 'prompt', promptId: 'prompt.indus.what-weights-show', claimIds: ['claim.indus.shared-weights', 'claim.indus.weight-numbers', 'claim.indus.coordination-and-rule'], sourceIds: ['source.indus.measuring', 'source.indus.green-governance'] },
      { id: 'module.indus.water-work-check', type: 'prompt', promptId: 'prompt.indus.water-needs-many-hands', claimIds: ['claim.indus.household-drainage', 'claim.indus.trap-sand-heaps', 'claim.indus.drain-reuse', 'claim.indus.water-storage', 'claim.indus.coordination-and-rule'], sourceIds: ['source.indus.street-drains', 'source.indus.dholavira', 'source.indus.green-governance'] },
    ],
  },
];

export const indusLesson: Lesson = {
  id: 'lesson.indus.cities-and-signs', legacyAliases: ['indus_cities', 'indus_script'], status: 'published',
  title: 'Indus Cities and Undeciphered Signs', masthead: 'c. 2600–1900 BCE', place: 'Indus region · present-day Pakistan and India',
  chronology: { startYear: -2600, endYear: -1900, display: 'c. 2600–1900 BCE', approximate: true },
  significance: 'Water systems, shared weights and seals reveal how Indus communities organized city life—even though their inscriptions remain unread.',
  learningOutcome: 'You explored how water systems and shared measures connected Indus communities, and why organized work does not by itself identify who ruled.',
  orientationMapModuleId: 'module.indus.cities-locator-map',
  heroMediaId: 'media.indus.street-reconstruction',
  heroLabel: 'A neighborhood at Mohenjo-daro',
  heroCaption: 'Reconstruction based on documented household and street drains. The people, buildings and moment are imagined; part of the channel is exposed to show how it connects.',
  sectionIdsRequired: sections.map((section) => section.id), sections,
  claimIds: indusClaims.map((claim) => claim.id), sourceIds: indusSources.map((source) => source.id), mediaIds: indusMedia.map((media) => media.id), promptIds: indusPrompts.map((prompt) => prompt.id),
};

export const indusContent: AuthoredContentModule = { sources: indusSources, claims: indusClaims, lessons: [indusLesson], prompts: indusPrompts, media: indusMedia, cards: [indusSealCard] };
