import type { Claim, Lesson, Source, UnderstandingPrompt } from '../../src/domains/contracts';
import type { AuthoredContentModule } from '../assemble';
import { kermaMedia, kermaMediaSources, kermaVisualModules } from './kerma-media';

export const kermaSources: Source[] = [
  ...kermaMediaSources,
  { id: 'source.kerma.mission-history', title: 'History: the kingdom of Kerma', url: 'https://kerma.ch/en/history/', publisher: 'Swiss Archaeological Mission in Sudan', accessedOn: '2026-09-14', licenseOrUse: 'Research citation; chronology, economic prosperity and expansion passages reviewed. Images require separate clearance.', reviewStatus: 'reviewed' },
  { id: 'source.kerma.mission-research', title: 'Research at Kerma', url: 'https://kerma.ch/en/research/', publisher: 'Swiss Archaeological Mission in Sudan', accessedOn: '2026-09-14', licenseOrUse: 'Research citation; renewed urban excavations and local-capital interpretation reviewed. No image redistribution.', reviewStatus: 'reviewed' },
  { id: 'source.kerma.city-project', title: 'Kerma–Doukki Gel', url: 'https://archeologie.culture.gouv.fr/monde/fr/kerma-doukki-gel', publisher: 'French Ministry of Culture / Sudanese–Swiss–French archaeological mission', accessedOn: '2026-09-14', licenseOrUse: 'Research citation; La ville de Kerma and Les recherches en cours reviewed. Building functions are archaeological interpretations. No image redistribution.', reviewStatus: 'reviewed' },
  { id: 'source.kerma.isotopes-2008', title: 'Stable isotopes and diet at Ancient Kerma, Upper Nubia (Sudan)', url: 'https://kerma.ch/documents/Publications_PDF/Chaix_Thompson_2007_Isotopeskerma.pdf', publisher: 'A. H. Thompson, L. Chaix and M. P. Richards, Journal of Archaeological Science 35 (2008), 376–387', accessedOn: '2026-09-14', licenseOrUse: 'Research citation; pp. 377–378 site, indigenous roots and food remains; pp. 384–385 sampling limits reviewed. No universal diet inferred.', reviewStatus: 'reviewed' },
  { id: 'source.kerma.metallurgy', title: 'Copper at Ancient Kerma: A Diachronic Investigation of Alloys and Raw Materials', url: 'https://www.sciencedirect.com/science/article/pii/S2667136022000036', publisher: 'F. W. Rademakers et al., Advances in Archaeomaterials 3 (2022), 1–18', accessedOn: '2026-09-14', licenseOrUse: 'Research citation; Table 1 and sections 3.1–3.2 local alloying/recycling; sections 4–5 supply alternatives reviewed. No unique ore route inferred.', reviewStatus: 'reviewed' },
  { id: 'source.kerma.mass-burials', title: 'Dying to Serve: the Mass Burials at Kerma', url: 'https://www.cambridge.org/core/services/aop-cambridge-core/content/view/C64CF190D99C036B35E4D02729DF52DD/S0003598X00098938a.pdf/dying_to_serve_the_mass_burials_at_kerma.pdf', publisher: 'M. A. Judd and J. D. Irish, Antiquity 83 (2009), 709–722', accessedOn: '2026-09-14', licenseOrUse: 'Research citation; pp. 710–712 and 719–720 burial investment, city and authority reviewed. Causes of death and consent are not learner claims; no human-remains images.', reviewStatus: 'reviewed' },
  { id: 'source.kerma.sennuwy', title: 'Lady Sennuwy: object and conservation record, MFA 14.720', url: 'https://www.mfa.org/collections/conservation/feature_ladysennuwy', publisher: 'Museum of Fine Arts, Boston', accessedOn: '2026-09-14', licenseOrUse: 'Research citation; Egyptian object identity and Kerma K III find context reviewed. Transport alternatives remain unresolved. No image redistribution.', reviewStatus: 'reviewed' },
  { id: 'source.kerma.reisner-context', title: 'Excavations at Kerma, Parts I–III, p. 138', url: 'https://doi.org/10.11588/diglit.49516#0198', publisher: 'George A. Reisner, Harvard African Studies 5 (1923)', accessedOn: '2026-09-14', licenseOrUse: 'Research citation; statue find context reviewed. Earlier Egyptian-colony interpretation is not adopted.', reviewStatus: 'reviewed' },
];

export const kermaClaims: Claim[] = [
  { id: 'claim.kerma.deffufa', statement: 'The Western Deffufa is a substantial surviving mud-brick monument in the ancient city of Kerma, interpreted as a temple. The site has received conservation and restoration; its present appearance is not the complete original building.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.kerma.map-site', 'source.kerma.deffufa-photo'], reviewStatus: 'reviewed' },
  { id: 'claim.kerma.met-beaker', statement: 'Met 20.2.45 is a handmade Classic Kerma pottery beaker dated ca. 1802–1640 BCE, 10.8 cm tall, found at Abydos Tomb 525 in Egypt. Its flaring form has a dark upper body and interior, red lower body and irregular pale band. Its maker and exact workshop are unidentified.', kind: 'observation', certainty: 'high', sourceIds: ['source.kerma.met-beaker'], reviewStatus: 'reviewed' },
  { id: 'claim.kerma.locator-geography', statement: 'Modern geographic data locate Kerma in northeastern Africa beside the Nile in Sudan, south of Egypt. The UNESCO tentative-list point represents the site; the Africa inset outlines the main map view rather than political territory. Modern river courses and terrain are orientation, not a reconstruction of ancient channels or vegetation.', kind: 'observation', certainty: 'high', sourceIds: ['source.kerma.map-site', 'source.kerma.map-relief', 'source.kerma.map-river', 'source.kerma.isotopes-2008'], reviewStatus: 'reviewed' },
  { id: 'claim.kerma.location', statement: 'Kerma is in present-day Sudan, in northeastern Africa, south of Egypt along the Nile.', kind: 'observation', certainty: 'high', sourceIds: ['source.kerma.mission-history', 'source.kerma.isotopes-2008'], reviewStatus: 'reviewed' },
  { id: 'claim.kerma.period', statement: 'About 2500–1500 BCE is a rounded teaching frame for the Kerma kingdom; archaeological phases have more detailed boundaries.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.kerma.mission-history'], reviewStatus: 'reviewed' },
  { id: 'claim.kerma.local-city', statement: 'Excavated housing, streets, defenses, workshops and buildings interpreted as royal or administrative support Kerma as a local urban capital, not an Egyptian colonial foundation.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.kerma.city-project', 'source.kerma.mission-research', 'source.kerma.isotopes-2008'], reviewStatus: 'reviewed' },
  { id: 'claim.kerma.food', statement: 'Cattle remains, cereals including barley and wheat, and excavated bakeries attest food production at Kerma.', kind: 'observation', certainty: 'high', sourceIds: ['source.kerma.isotopes-2008'], reviewStatus: 'reviewed' },
  { id: 'claim.kerma.work-and-support', statement: 'Food production and storage supported people doing other work; substantial city defenses and monuments required organized labor and supplies.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.kerma.city-project', 'source.kerma.isotopes-2008', 'source.kerma.mass-burials'], reviewStatus: 'reviewed' },
  { id: 'claim.kerma.metalworking', statement: 'Metal objects and production waste support skilled local work including deliberate copper alloying and recycling.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.kerma.metallurgy', 'source.kerma.city-project'], reviewStatus: 'reviewed' },
  { id: 'claim.kerma.unequal-power', statement: 'Royal and administrative buildings and much larger richly supplied burials support concentrated authority and unequal access to labor and wealth.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.kerma.mass-burials', 'source.kerma.city-project'], reviewStatus: 'reviewed' },
  { id: 'claim.kerma.connections', statement: 'Kerma participated in exchange with other regions and had changing relations, including rivalry, with Egypt.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.kerma.mission-history', 'source.kerma.metallurgy', 'source.kerma.mass-burials'], reviewStatus: 'reviewed' },
  { id: 'claim.kerma.sennuwy', statement: 'Egyptian statue MFA 14.720 was found in Kerma tomb K III; its presence shows movement but cannot alone prove Egyptian rule.', kind: 'observation', certainty: 'high', sourceIds: ['source.kerma.sennuwy', 'source.kerma.reisner-context'], reviewStatus: 'reviewed' },
  { id: 'claim.kerma.conquest', statement: 'Egyptian conquest around the end of the lesson period ended Kerma’s political independence and brought destruction to the city; this is not evidence that all its inhabitants disappeared.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.kerma.mission-history'], reviewStatus: 'reviewed' },
  { id: 'claim.kerma.sennuwy-find', statement: 'MFA 14.720, Lady Sennuwy, is a granodiorite statue weighing nearly 2,400 pounds, excavated in 1914 by the Harvard University–Boston Museum of Fine Arts Expedition in the burial complex of a local ruler in the land of Kush, today’s northern Sudan.', kind: 'observation', certainty: 'high', sourceIds: ['source.kerma.sennuwy', 'source.kerma.reisner-context'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.kerma.kush-name', statement: 'Egyptian hieroglyphic texts refer to the kingdom of Kerma as the Kingdom of Kush.', kind: 'observation', certainty: 'high', sourceIds: ['source.kerma.map-site'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.kerma.pre-kerma-granaries', statement: 'The Pre-Kerma settlement (c. 3200–2500 BCE) comprised about 40 huts, four to seven meters across, around a storage area that included almost 500 cereal granaries.', kind: 'observation', certainty: 'high', sourceIds: ['source.kerma.mission-history'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.kerma.defenses-and-hall', statement: 'Kerma city had deep ditches and an elaborate system of fortifications and a large round audience hall, rebuilt several times in the same place, which probably had a conical roof supported by three or four rows of wooden columns.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.kerma.city-project', 'source.kerma.map-site'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.kerma.deffufa-size', statement: 'The Western Deffufa, a large mud-brick temple, currently stands 18 meters high; deffufa is a Nubian word for a large mud-brick, man-made structure.', kind: 'observation', certainty: 'high', sourceIds: ['source.kerma.map-site'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.kerma.beaker-making', statement: 'Classic Kerma beakers were covered with red ocher and polished before firing, then inverted in combustible material to create the reducing atmosphere that gives the distinctive black tops.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.kerma.met-beaker'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.kerma.beaker-find', statement: 'Classic Kerma beakers were found stacked in tombs in groups of as many as seven; Met 20.2.45 was found in Abydos Tomb 525 in the 1908 Garstang excavations, and such tombs generally contain both Kerma ceramics and Egyptian goods.', kind: 'observation', certainty: 'high', sourceIds: ['source.kerma.met-beaker'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.kerma.beaker-traders', statement: 'The owners of tombs at Abydos that contain Kerma ceramics and Egyptian goods may have been traders, originally from Kerma, who had taken up residence in Egypt.', kind: 'interpretation', certainty: 'low', sourceIds: ['source.kerma.met-beaker'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.kerma.bronze-furnace', statement: 'A large cross-shaped furnace at the foot of the Western Deffufa was a unique installation, in the excavators’ words, for making bronze plaques; the city also produced faience and ceramics.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.kerma.city-project'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.kerma.trade-goods', statement: 'Trade in gold, precious stones, ivory, animal hide, ebony and cattle contributed to Kerma’s wealth, and the city stood at a crossroads of major trade routes linking Africa and the Mediterranean.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.kerma.mission-history', 'source.kerma.city-project'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.kerma.cattle-mound', statement: 'One tomb, perhaps of a king of the Middle Kerma period (2050–1750 BCE), lay under a mound that reached 25 meters across, with more than 4,000 cattle skulls arranged in a crescent on its south side; later rulers were buried under mounds up to 90 meters across.', kind: 'observation', certainty: 'high', sourceIds: ['source.kerma.map-site'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.kerma.hyksos-alliance', statement: 'The Swiss mission cites an alliance proposed by a Hyksos king of Egypt’s Fifteenth Dynasty, around 1580 BCE, as corroborating Kerma’s importance on the political scene.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.kerma.mission-history'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.kerma.conquest-displacement', statement: 'The Egyptian conquest of the Kingdom of Kush was carried out by Thutmose I (1496–1483 BCE); the Nubians had to leave their homes, often burnt during the conquest, and several settled at Soleb, Sesebi, Tabo, Kawa or at the foot of Gebel Barkal.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.kerma.mission-history'], reviewStatus: 'editorial-review-required' },
];

export const kermaPrompts: UnderstandingPrompt[] = [
  {
    id: 'prompt.kerma.what-two-finds-show', bestOptionId: 'option.kerma.own-makers-and-contact', lessonId: 'lesson.nubia.kerma-and-nile-world', kind: 'supported-selection', required: true,
    question: 'Archaeologists found waste left from making metal objects in the city of Kerma. In a Kerma ruler’s tomb they found a statue made in Egypt. Which statement fits both finds best?',
    hint: 'Ask what each find shows: where something was made, and where it was found.',
    explanation: 'The waste shows that metal was worked at Kerma. The statue shows that an object made in Egypt reached Kerma, though how it got there is unknown. Together the finds fit a kingdom with its own skilled workers and connections beyond it. They do not show who ruled Kerma.',
    options: [
      { id: 'option.kerma.own-makers-and-contact', label: 'Kerma had its own metalworkers, and an object made in Egypt also reached Kerma.', feedback: 'Yes. Waste left from making metal shows that metalworking happened at Kerma, and a statue made in Egypt shows an object traveling to Kerma.' },
      { id: 'option.kerma.egypt-governed', label: 'Egypt governed Kerma, because an Egyptian statue was buried in a Kerma tomb.', feedback: 'Reread “A changing relationship with Egypt.” Does finding an object in a place tell us who governed that place?' },
      { id: 'option.kerma.metal-from-egypt', label: 'Kerma depended on Egypt for its metal objects, since an Egyptian statue reached it.', feedback: 'Reread “Kerma’s skilled makers.” Where was the metalworking waste found, and what does that say about where metal was worked?' },
    ],
  },
  {
    id: 'prompt.kerma.what-work-made-possible', lessonId: 'lesson.nubia.kerma-and-nile-world', kind: 'concise-explanation', required: true, minimumResponseLength: 20,
    question: 'Choose one group: farmers, herders, craftspeople or builders. What did their work let the kingdom of Kerma do?',
    hint: 'Pick one group, then look back at “Feeding and building the city” or “Kerma’s skilled makers.” Start with what that group did, then say what the kingdom could do because of it.',
    explanation: 'For example: farmers grew barley and wheat that could feed the people who built walls and the Western Deffufa, so the kingdom could carry out large building work. Herders raised cattle, part of Kerma’s wealth; craftspeople made goods such as metal plaques and pottery that supplied the city and its rulers; builders made the defenses and monuments that rulers used. A strong answer names a group, says what its work was, and links it to something the kingdom could do. It may also note that the kingdom’s wealth and authority were shared unequally.',
  },
];

const sections: Lesson['sections'] = [
  {
    id: 'section.kerma.nile-neighbors', heading: 'Kerma on the Nile', purpose: 'Locate the city and kingdom and ask what supported its power.',
    modules: [
      kermaVisualModules.map,
      { id: 'module.kerma.nile-neighbors', type: 'prose', claimIds: ['claim.kerma.location', 'claim.kerma.period', 'claim.kerma.local-city', 'claim.kerma.sennuwy', 'claim.kerma.sennuwy-find', 'claim.kerma.kush-name'], sourceIds: ['source.kerma.mission-history', 'source.kerma.isotopes-2008', 'source.kerma.city-project', 'source.kerma.sennuwy', 'source.kerma.reisner-context', 'source.kerma.map-site'], body: 'In 1914, an expedition from Harvard University and the Museum of Fine Arts, Boston was digging in the burial complex of a local ruler in what is now Sudan when it found a statue of a woman. It was carved from granodiorite and weighed nearly 2,400 pounds, about 1,100 kilograms. The woman was Egyptian. She had been placed in a ruler’s tomb in a land that was not Egypt.\n\nThat place was Kerma, on the Nile south of Egypt. For about a thousand years, from roughly 2500 to 1500 BCE, it was the capital of a kingdom: the center of government for a territory and its communities under a ruler. Egyptian texts called that kingdom Kush. Egypt and Sudan are modern country names that help us find it.\n\nNobody knows how the statue got there. The kingdom that received it is easier to see, in the food, the building and the skilled work that held Kerma together, and that is what this lesson follows. Its history overlapped the Egyptian and Indus societies you have met; none waited for the others to finish. The Nile that connected Egyptian communities also ran through Kerma, where people built a kingdom with its own rulers.' },
    ],
  },
  {
    id: 'section.kerma.food-and-building', heading: 'Feeding and building the city', purpose: 'Explain food supply as a condition for specialized work and substantial construction.',
    modules: [
      { id: 'module.kerma.feeding-city', type: 'prose', claimIds: ['claim.kerma.food', 'claim.kerma.pre-kerma-granaries', 'claim.kerma.work-and-support'], sourceIds: ['source.kerma.isotopes-2008', 'source.kerma.city-project', 'source.kerma.mission-history'], body: 'Kerma’s food story starts before the kingdom does. In the settlement that came first, about 40 huts stood around a storage area holding almost 500 grain stores, the Swiss archaeological mission reports. By the time Kerma was a capital, archaeologists had found cattle remains, barley and wheat, and bakeries. Each find is a daily chore made visible: someone had to herd the animals, grow and store the grain, and bake it, day after day.\n\nFood also supported people doing other jobs. Someone building a wall or working metal still had to eat, and growing, storing and supplying food made it possible to support work beyond farming. This helps explain how a large city could function. It does not tell us how any one household supplied or received its food.' },
      { id: 'module.kerma.building-city', type: 'prose', claimIds: ['claim.kerma.local-city', 'claim.kerma.defenses-and-hall', 'claim.kerma.work-and-support'], sourceIds: ['source.kerma.city-project', 'source.kerma.map-site', 'source.kerma.mass-burials'], body: 'Excavations reveal streets and houses, workshops, deep ditches and a system of strong defenses. Researchers also identify buildings used by rulers and officials, including a large round hall that was rebuilt several times in the same place. They think it had a cone-shaped roof held up by rows of wooden columns. Making these places took materials, labor and planning, and keeping a crew working meant bringing their efforts and supplies together.\n\nFood alone did not create a kingdom. People had to organize the work, keep their skills alive and decide how resources would be used. Kerma’s surviving city shows some of what that organization achieved.' },
      kermaVisualModules.deffufa,
    ],
  },
  {
    id: 'section.kerma.skilled-makers', heading: 'Kerma’s skilled makers', purpose: 'Connect local production evidence with skilled people and useful or valued objects.',
    modules: [
      { id: 'module.kerma.beaker', type: 'prose', claimIds: ['claim.kerma.met-beaker', 'claim.kerma.beaker-making', 'claim.kerma.beaker-find', 'claim.kerma.beaker-traders'], sourceIds: ['source.kerma.met-beaker'], body: 'Craftspeople are people skilled at making things, and this beaker is one of their finest surviving works. Pottery is clay hardened by fire. Kerma’s potters covered their beakers with red ocher and polished them, then fired them upside down in a bed of combustible material. That fire had little air, and it blackened the tops. The result is a vessel with a black rim, a red body and an irregular pale band between them.\n\nIt is about 11 centimeters tall and was made around 1800–1640 BCE. It was found in 1908 in Tomb 525 at Abydos, in Egypt, not in Kerma. The Metropolitan Museum, which holds it as number 20.2.45, notes that Kerma beakers turn up stacked in graves, sometimes seven at a time, and that tombs like this one hold Egyptian goods too. Their owners may have been traders from Kerma who had made their home in Egypt. Nobody knows who made this beaker, or how it came to lie in that grave.' },
      kermaVisualModules.beaker,
      { id: 'module.kerma.metalworking', type: 'prose', claimIds: ['claim.kerma.metalworking', 'claim.kerma.bronze-furnace'], sourceIds: ['source.kerma.metallurgy', 'source.kerma.city-project'], body: 'Kerma’s metalworkers left their own traces. At the foot of the Western Deffufa, archaeologists uncovered a large furnace built in the shape of a cross, which the excavators call a unique installation for making bronze plaques. Bronze is an alloy, a mixture of metals. Analyses of Kerma’s copper objects show that workers mixed copper with other metals on purpose and melted old pieces down to use again. Waste from this work turns up in the city, so it is a trace of work done at Kerma rather than a finished object that might have arrived from elsewhere. Their skill helped supply the city and its rulers.' },
    ],
  },
  {
    id: 'section.kerma.rulers-and-resources', heading: 'Rulers and resources', purpose: 'Explain how organized work and wealth were concentrated unequally.',
    modules: [
      { id: 'module.kerma.rulers', type: 'prose', claimIds: ['claim.kerma.unequal-power', 'claim.kerma.cattle-mound', 'claim.kerma.work-and-support'], sourceIds: ['source.kerma.mass-burials', 'source.kerma.city-project', 'source.kerma.map-site'], body: 'The kingdom depended on many people’s work, but people did not share its wealth and authority equally. Buildings that archaeologists read as royal residences and places of administration point to rulers and officials. The cemetery points the same way. One tomb, perhaps a king’s from the Middle Kerma period, lay under a mound 25 meters across, and more than 4,000 cattle skulls had been set in a crescent along its south side. Later rulers were buried under mounds up to 90 meters across. Smaller burials held far fewer goods.\n\nEach of those skulls came from an animal someone had raised, and each mound needed living people to gather materials and build it. Rulers could call on work and wealth far beyond what went into an ordinary grave.\n\nThe cemetery shows what rulers could command. It tells us much less about what the people who did the work wanted.' },
    ],
  },
  {
    id: 'section.kerma.egypt-and-change', heading: 'A changing relationship with Egypt', purpose: 'Distinguish local power, external connections and later conquest.',
    modules: [
      { id: 'module.kerma.egyptian-object', type: 'prose', claimIds: ['claim.kerma.connections', 'claim.kerma.trade-goods', 'claim.kerma.beaker-find', 'claim.kerma.hyksos-alliance', 'claim.kerma.sennuwy'], sourceIds: ['source.kerma.mission-history', 'source.kerma.city-project', 'source.kerma.metallurgy', 'source.kerma.met-beaker', 'source.kerma.sennuwy', 'source.kerma.reisner-context'], body: 'Kerma was never cut off. People there traded in gold, precious stones, ivory, hides, ebony and cattle, and the city stood where trade routes between Africa and the Mediterranean world met. Things moved in both directions: a Kerma beaker lay in a grave at Abydos in Egypt, and an Egyptian statue lay in a tomb at Kerma.\n\nLady Sennuwy’s statue was made in Egypt, and it was found in a large tomb at Kerma. Museum records tell us what she is and where she was found, but not how she got there. Finding an object in a place does not show who governed it. Put her beside the workshops and the beaker: Kerma made things, and Kerma received things.\n\nThe relationship between the two kingdoms changed over the centuries, and it was not always friendly. Around 1580 BCE, a king of Egypt’s Fifteenth Dynasty proposed an alliance with Kerma. The Swiss archaeological mission reads this as evidence of how much the kingdom mattered on the political stage. Exchange and rivalry could exist side by side.' },
      kermaVisualModules.sennuwy,
      { id: 'module.kerma.political-change', type: 'prose', claimIds: ['claim.kerma.conquest', 'claim.kerma.conquest-displacement', 'claim.kerma.hyksos-alliance', 'claim.kerma.work-and-support', 'claim.kerma.unequal-power'], sourceIds: ['source.kerma.mission-history', 'source.kerma.city-project', 'source.kerma.mass-burials'], body: 'Around 1500 BCE, Egypt’s king Thutmose I conquered the kingdom of Kush, and Kerma fell. The Swiss mission writes that the people of Kerma had to leave their homes, many of them burnt during the conquest. Several groups settled at places such as Soleb, Sesebi, Tabo and Kawa, or at the foot of Gebel Barkal. The kingdom had lost its independence, but its people had not vanished.\n\nNobody knows how Lady Sennuwy reached a Kerma ruler’s tomb. The kingdom that received her was a capital built by farmers, herders, craftspeople and builders, strong enough that a king of Egypt’s Fifteenth Dynasty sought its alliance around 1580 BCE and another Egyptian king conquered it within a century.' },
    ],
  },
  {
    id: 'section.kerma.understanding', heading: 'Explain Kerma’s power', purpose: 'Use material evidence and explain a connection between work and a kingdom’s capacities.',
    modules: [
      { id: 'module.kerma.contact-check', type: 'prompt', promptId: 'prompt.kerma.what-two-finds-show', claimIds: ['claim.kerma.metalworking', 'claim.kerma.sennuwy'], sourceIds: ['source.kerma.metallurgy', 'source.kerma.sennuwy'] },
      { id: 'module.kerma.power-check', type: 'prompt', promptId: 'prompt.kerma.what-work-made-possible', claimIds: ['claim.kerma.work-and-support', 'claim.kerma.unequal-power'], sourceIds: ['source.kerma.city-project', 'source.kerma.mass-burials'] },
    ],
  },
];

export const kermaLesson: Lesson = {
  id: 'lesson.nubia.kerma-and-nile-world', legacyAliases: ['kerma'], status: 'published',
  title: 'Kerma and the Middle Nile', masthead: 'c. 2500–1500 BCE', place: 'Middle Nile · present-day Sudan',
  chronology: { startYear: -2500, endYear: -1500, display: 'c. 2500–1500 BCE', approximate: true },
  significance: 'Food, skilled work and organized labor helped sustain Kerma, a kingdom with its own rulers and changing connections with Egypt.',
  learningOutcome: 'You explored how people’s work supported Kerma’s power, and why connections with Egypt did not always mean Egyptian rule.',
  orientationMapModuleId: 'module.kerma.nile-locator',
  sectionIdsRequired: sections.map((section) => section.id), sections,
  claimIds: kermaClaims.map((claim) => claim.id), sourceIds: kermaSources.map((source) => source.id), mediaIds: kermaMedia.map((media) => media.id), promptIds: kermaPrompts.map((prompt) => prompt.id),
};

export const kermaContent: AuthoredContentModule = { sources: kermaSources, claims: kermaClaims, media: kermaMedia, lessons: [kermaLesson], prompts: kermaPrompts };
