import type { Claim, Lesson, MediaAsset, Source, UnderstandingPrompt } from '../../src/domains/contracts';
import type { LessonPrototypeReview } from '../../src/infrastructure/content/prototypeReview';
import type { AuthoredContentModule } from '../assemble';
import { mediaLocator } from '../shared/media-locator';

export const manyBeginningsOfFarmingSources: Source[] = [
  {
    id: 'source.farming.larson-2014-pnas',
    title: 'Current perspectives and the future of domestication studies',
    url: 'https://doi.org/10.1073/pnas.1323964111',
    publisher: 'Proceedings of the National Academy of Sciences',
    accessedOn: '2026-07-27',
    licenseOrUse: 'Open-access scholarly synthesis cited for research; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.fuller-2014-convergent',
    title: 'Convergent evolution and parallelism in plant domestication revealed by an expanding archaeological record',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4035951/',
    publisher: 'Proceedings of the National Academy of Sciences',
    accessedOn: '2026-07-27',
    licenseOrUse: 'Open-access scholarly synthesis cited for research; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.fuller-willcox-2011',
    title: 'Cultivation and domestication had multiple origins: arguments against the core area hypothesis for the origins of agriculture in the Near East',
    url: 'https://doi.org/10.1080/00438243.2011.624747',
    publisher: 'World Archaeology',
    accessedOn: '2026-07-27',
    licenseOrUse: 'Peer-reviewed scholarship cited as a fact and interpretation source; article media are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.denham-2003-kuk',
    title: 'Origins of agriculture at Kuk Swamp in the highlands of New Guinea',
    url: 'https://doi.org/10.1126/science.1085255',
    publisher: 'Science',
    accessedOn: '2026-07-27',
    licenseOrUse: 'Peer-reviewed excavation synthesis cited as a fact source; article media are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.fullagar-2006-kuk-starch',
    title: 'Early and mid Holocene tool-use and processing of taro and yam at Kuk Swamp, Papua New Guinea',
    url: 'https://doi.org/10.1016/j.jas.2005.07.020',
    publisher: 'Journal of Archaeological Science',
    accessedOn: '2026-07-27',
    licenseOrUse: 'Peer-reviewed residue and use-wear study cited as a fact source; article media are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.deng-2015-baligang',
    title: 'From Early Domesticated Rice of the Middle Yangtze Basin to Millet, Rice and Wheat Agriculture',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4604147/',
    publisher: 'PLOS ONE',
    accessedOn: '2026-07-27',
    licenseOrUse: 'CC BY scholarly article cited as a fact source',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.winchell-2018-sorghum',
    title: 'On the origins and dissemination of domesticated sorghum and pearl millet across Africa and into India',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6394749/',
    publisher: 'African Archaeological Review',
    accessedOn: '2026-07-27',
    licenseOrUse: 'Open-access scholarly synthesis cited as a fact source; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.barron-2020-pearl-millet',
    title: 'The transition from wild to domesticated pearl millet in the Tilemsi Valley of Mali',
    url: 'https://doi.org/10.1007/s10437-021-09428-8',
    publisher: 'African Archaeological Review',
    accessedOn: '2026-07-27',
    licenseOrUse: 'Peer-reviewed archaeobotanical research cited as a fact source; article media are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.piperno-2009-maize',
    title: 'Starch grain and phytolith evidence for early ninth millennium B.P. maize from the Central Balsas River Valley, Mexico',
    url: 'https://doi.org/10.1073/pnas.0812525106',
    publisher: 'Proceedings of the National Academy of Sciences',
    accessedOn: '2026-07-27',
    licenseOrUse: 'Peer-reviewed microfossil study cited as a fact source; article media are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.ranere-2009-balsas',
    title: 'The cultural and chronological context of early Holocene maize and squash domestication in the Central Balsas River Valley, Mexico',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC2664064/',
    publisher: 'Proceedings of the National Academy of Sciences',
    accessedOn: '2026-07-27',
    licenseOrUse: 'Open-access excavation context cited as a fact source; article media are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.fuks-marom-2021-wheat',
    title: 'Sheep and wheat domestication in southwest Asia: a meta-trajectory of intensification and loss',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8214439/',
    publisher: 'Animal Frontiers',
    accessedOn: '2026-08-11',
    licenseOrUse: 'CC BY 4.0 scientific comparison used as the factual and visual reference for the Chronos wheat-ear diagram',
    reviewStatus: 'reviewed',
  },
];

export const manyBeginningsOfFarmingClaims: Claim[] = [
  {
    id: 'claim.farming.multi.independent-centers',
    statement: 'People developed food production independently in several regions using local plants and practices.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.larson-2014-pnas', 'source.farming.fuller-2014-convergent'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.not-one-revolution',
    statement: 'Farming did not begin as one worldwide invention in Southwest Asia that every other region simply copied.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.fuller-willcox-2011', 'source.farming.larson-2014-pnas'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.domestication-process',
    statement: 'Cultivation can begin before plants show the inherited physical changes archaeologists use to identify domestication.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.larson-2014-pnas', 'source.farming.fuller-2014-convergent'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.cereal-protracted',
    statement: 'In several major Old World cereals, domestication traits developed over many generations rather than in one sudden switch.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.fuller-2014-convergent'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.sw-asia',
    statement: 'Southwest Asia was one early region where communities gradually cultivated and domesticated local cereals and pulses.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.fuller-willcox-2011', 'source.farming.baird-2018-anatolia'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.china',
    statement: 'Early food production in China included distinct northern millet and Yangtze rice traditions.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.deng-2015-baligang', 'source.farming.fuller-2014-convergent'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.new-guinea',
    statement: 'New Guinea communities independently developed cultivation and wetland agriculture involving plants including bananas, taro, and yams.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.denham-2003-kuk', 'source.farming.fullagar-2006-kuk-starch'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.africa',
    statement: 'African communities followed independent cereal-domestication pathways including pearl millet in the western Sahel and sorghum in the eastern Sahel.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.winchell-2018-sorghum', 'source.farming.barron-2020-pearl-millet'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.americas',
    statement: 'People in the Americas independently domesticated local plants, including maize in the Central Balsas region of Mexico by about 8,700 years ago.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.piperno-2009-maize', 'source.farming.ranere-2009-balsas'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.not-always-villages',
    statement: 'Cultivation could be part of mobile or seasonally mobile lifeways, so dense permanent villages were not a universal first step.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.ranere-2009-balsas', 'source.farming.fuller-2014-convergent'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.no-automatic-cities',
    statement: 'Food production created new possibilities but did not automatically produce cities, states, writing, or kings.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.larson-2014-pnas', 'source.farming.fuller-2014-convergent'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.evidence-bias',
    statement: 'Tropical tubers and wetland traces preserve differently from dryland cereal grains, so different regions leave different archaeological records.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.denham-2003-kuk', 'source.farming.fullagar-2006-kuk-starch', 'source.farming.fuller-2014-convergent'],
    reviewStatus: 'reviewed',
  },
];

export const manyBeginningsOfFarmingMedia: MediaAsset[] = [
  {
    id: 'media.farming.multiple-origins-map',
    locator: mediaLocator('media.farming.multiple-origins-map'),
    alt: 'World map with soft highlighted zones in Southwest Asia, northern and central China, the New Guinea highlands, the African Sahel, Mesoamerica, and northern South America; no arrows connect the regions',
    depictionMode: 'map',
    depictionLabel: 'Evidence-led world map · broad regions are approximate, modern coasts provide orientation',
    rightsLabel: 'Chronos original map edit · Natural Earth base geography, Public Domain',
    sourceIds: [
      'source.farming.natural-earth',
      'source.farming.fuller-2014-convergent',
      'source.farming.denham-2003-kuk',
      'source.farming.deng-2015-baligang',
      'source.farming.winchell-2018-sorghum',
      'source.farming.piperno-2009-maize',
    ],
    visualBriefRef: 'docs/research/many-beginnings-of-farming-map.md#generated-artwork-lineage',
    reviewStatus: 'approved',
  },
  {
    id: 'media.farming.wild-domesticated-wheat',
    locator: mediaLocator('media.farming.wild-domesticated-wheat'),
    alt: 'Illustrated sequence comparing wheat dispersal: a farmer gathers and threshes a compact domesticated ear with a rough break scar, while a looser wild ear disarticulates into falling spikelets with smooth scars',
    depictionMode: 'diagram',
    depictionLabel: 'Evidence-led botanical diagram · one cereal mechanism, not every domestication pathway',
    rightsLabel: 'Chronos original diagram · scientific reference adapted from Fuks and Marom 2021, CC BY 4.0',
    sourceIds: ['source.farming.fuks-marom-2021-wheat', 'source.farming.fuller-2014-convergent'],
    visualBriefRef: 'docs/research/many-beginnings-of-farming.md#image-lifecycle',
    reviewStatus: 'approved',
  },
];

export const manyBeginningsOfFarmingPrompts: UnderstandingPrompt[] = [
  {
    id: 'prompt.farming.multi.what-evidence-supports',
    lessonId: 'lesson.farming.multiple-origins',
    kind: 'supported-selection',
    question: 'Looking across Southwest Asia, China, New Guinea, Africa, and the Americas, which conclusion is best supported?',
    explanation: 'Different communities worked with different local plants on different timelines. That pattern supports several independent beginnings, not one invention copied everywhere.',
    required: true,
    options: [
      { id: 'option.farming.multi.several-beginnings', label: 'Farming began independently in several regions with different crops.' },
      { id: 'option.farming.multi.one-beginning', label: 'Farming was invented once in Southwest Asia and then copied everywhere.' },
      { id: 'option.farming.multi.villages-first', label: 'Dense permanent villages always appeared before cultivation.' },
      { id: 'option.farming.multi.one-continent', label: 'Useful evidence for early farming survives on only one continent.' },
    ],
  },
  {
    id: 'prompt.farming.multi.explain-independent',
    lessonId: 'lesson.farming.multiple-origins',
    kind: 'concise-explanation',
    question: 'Choose one region. How do its crops or clues support an independent beginning of farming, and what can those clues not prove by themselves?',
    explanation: 'A strong explanation connects a local crop or clue to the wider pattern, then names a limit - such as the exact first person, exact start day, motives, or whether farming made life better.',
    required: true,
    minimumResponseLength: 30,
  },
];

export const manyBeginningsOfFarmingLesson: Lesson = {
  id: 'lesson.farming.multiple-origins',
  legacyAliases: ['neolithic_revolution'],
  status: 'draft',
  title: 'Many Beginnings of Farming',
  masthead: 'c. 10,000-3000 BCE',
  place: 'Several regions across the world',
  chronology: {
    startYear: -10000,
    endYear: -3000,
    display: 'c. 10,000-3000 BCE',
    approximate: true,
  },
  significance: 'Farming began more than once, as communities in different regions gradually changed local plants - and were changed by the work of growing them.',
  sectionIdsRequired: [
    'section.farming.multi.not-once',
    'section.farming.multi.what-domestication',
    'section.farming.multi.five-beginnings',
    'section.farming.multi.different-evidence',
    'section.farming.multi.not-one-lifestyle',
    'section.farming.multi.world-check',
  ],
  sections: [
    {
      id: 'section.farming.multi.not-once',
      heading: 'Farming did not begin once',
      purpose: 'Break the single-revolution myth and establish the lesson question',
      modules: [
        {
          id: 'module.farming.multi.opening',
          type: 'prose',
          body: 'Imagine drawing one dot on a world map and calling it the birthplace of farming. For a long time, many history books placed that dot in Southwest Asia, in the region often called the Fertile Crescent. The story was simple: people there invented farming, then everyone else copied it.\n\nThe evidence tells a more interesting story. After about 10,000 BCE, communities in several far-apart regions began changing how they gathered, tended, planted, and harvested food. They worked with wheat and barley, millet and rice, bananas and taro, pearl millet and sorghum, maize and squash. These plants did not all come from one place, and the communities were not following one plan.\n\nSouthwest Asia was an important early beginning. It was not the world\'s only beginning. The question is not "Who invented farming first?" It is how different people, in different landscapes, created several food-producing lifeways.',
          claimIds: ['claim.farming.multi.independent-centers', 'claim.farming.multi.not-one-revolution'],
          sourceIds: ['source.farming.larson-2014-pnas', 'source.farming.fuller-2014-convergent', 'source.farming.fuller-willcox-2011'],
        },
        {
          id: 'module.farming.multi.words-for-change',
          type: 'knowledge',
          eyebrow: 'Three useful words',
          title: 'Foraging, cultivation, and domestication',
          body: 'The change was not one leap. These words help us follow the steps without pretending every region followed the same path.',
          items: [
            { label: 'Foraging', detail: 'Finding, gathering, hunting, and managing foods that grow or live without being planted as crops.' },
            { label: 'Cultivation', detail: 'Deliberately tending and planting useful plants. Cultivation can happen before the plants themselves look domesticated.' },
            { label: 'Domestication', detail: 'Inherited changes in plants that build up as people repeatedly select, protect, move, and reproduce them.' },
          ],
          claimIds: ['claim.farming.multi.domestication-process'],
          sourceIds: ['source.farming.larson-2014-pnas', 'source.farming.fuller-2014-convergent'],
        },
      ],
    },
    {
      id: 'section.farming.multi.what-domestication',
      heading: 'Plants changed with people',
      purpose: 'Make gradual domestication concrete through one cereal mechanism',
      modules: [
        {
          id: 'module.farming.multi.cereal-example',
          type: 'prose',
          body: 'Wild cereal plants need to spread their own seeds. When a seed head ripens, it breaks apart - or shatters - and drops grain onto the ground. That is good for the plant. It is inconvenient for a person trying to gather a basketful.\n\nNow imagine harvest after harvest. People are most likely to collect seed heads that are still holding together. If they plant some of those grains, plants that hold onto their seeds get another chance to reproduce near people. Nobody has to know about genes or announce a breeding program. Repeated choices can slowly make the stay-attached trait more common.\n\nArchaeologists find that important cereal traits often took many generations to become common. Cultivation could be underway long before a crop crossed a neat line into "domesticated." That is why farming is better understood as a process than as an invention day.',
          claimIds: ['claim.farming.multi.domestication-process', 'claim.farming.multi.cereal-protracted'],
          sourceIds: ['source.farming.fuller-2014-convergent', 'source.farming.larson-2014-pnas'],
        },
        {
          id: 'module.farming.multi.wheat-comparison',
          type: 'evidence',
          title: 'Which ear is easier to gather?',
          artifactLabel: 'Plant evidence model',
          body: 'The ear on the right breaks apart when ripe, spreading wild spikelets. The ear on the left holds together until people thresh it. If gatherers repeatedly planted grain from ears that stayed intact, that useful inherited trait could become more common over many generations. This wheat example makes one mechanism visible; other crops and regions followed different pathways.',
          mediaId: 'media.farming.wild-domesticated-wheat',
          claimIds: ['claim.farming.multi.domestication-process', 'claim.farming.multi.cereal-protracted'],
          sourceIds: ['source.farming.fuks-marom-2021-wheat', 'source.farming.fuller-2014-convergent'],
        },
        {
          id: 'module.farming.multi.process-not-plan',
          type: 'knowledge',
          eyebrow: 'A two-way change',
          title: 'People changed plants, and plants changed people',
          body: 'Domestication was not a one-way command. New plant traits and new human routines developed together.',
          items: [
            { label: 'People selected', detail: 'Where, when, and how people gathered and replanted changed which plants reproduced.' },
            { label: 'Plants responded over generations', detail: 'Useful inherited traits became more common, although the pace differed from crop to crop.' },
            { label: 'Work changed too', detail: 'Preparing ground, planting, weeding, watering, harvesting, processing, and storing tied communities to new seasonal tasks.' },
          ],
          claimIds: ['claim.farming.multi.domestication-process', 'claim.farming.multi.cereal-protracted'],
          sourceIds: ['source.farming.larson-2014-pnas', 'source.farming.fuller-2014-convergent'],
        },
      ],
    },
    {
      id: 'section.farming.multi.five-beginnings',
      heading: 'Several regions, different pathways',
      purpose: 'Build a global mental map from illustrative regions and their local crops without implying a complete count',
      modules: [
        {
          id: 'module.farming.multi.regional-pattern',
          type: 'knowledge',
          eyebrow: 'Approximate early zones',
          title: 'Different regions, different crops',
          body: 'These are broad regions, not five exact invention spots. Dates continue to be refined, and more independent beginnings existed than this lesson can show.',
          items: [
            { label: 'Southwest Asia', detail: 'Communities gradually cultivated and domesticated local cereals such as wheat and barley, together with pulses such as lentils.' },
            { label: 'China', detail: 'Northern millet traditions and Yangtze rice traditions developed along different pathways before crops later mixed between regions.' },
            { label: 'New Guinea', detail: 'Highland communities cultivated plants including bananas, taro, and yams and later shaped wetland fields at Kuk.' },
            { label: 'Africa', detail: 'People domesticated local cereals along more than one pathway, including pearl millet in the western Sahel and sorghum farther east.' },
            { label: 'Americas', detail: 'Communities domesticated local plants in several areas; maize and squash in Mesoamerica are one early, well-studied example.' },
          ],
          claimIds: [
            'claim.farming.multi.sw-asia',
            'claim.farming.multi.china',
            'claim.farming.multi.new-guinea',
            'claim.farming.multi.africa',
            'claim.farming.multi.americas',
          ],
          sourceIds: [
            'source.farming.fuller-willcox-2011',
            'source.farming.baird-2018-anatolia',
            'source.farming.deng-2015-baligang',
            'source.farming.denham-2003-kuk',
            'source.farming.winchell-2018-sorghum',
            'source.farming.barron-2020-pearl-millet',
            'source.farming.piperno-2009-maize',
            'source.farming.ranere-2009-balsas',
          ],
        },
        {
          id: 'module.farming.multi.map-alternative',
          type: 'historical-map',
          eyebrow: 'Approximate early zones',
          title: 'No single birthplace',
          body: 'The highlighted areas show several broad regions where evidence supports independent food-production pathways. Compare their distance and their local crops. There are no arrows because this is not a story of one invention spreading everywhere.',
          mediaId: 'media.farming.multiple-origins-map',
          periodLabel: 'c. 10,000–3000 BCE',
          focusPlace: 'Several regions across the world',
          modernContext: 'Modern coastlines are used only for orientation',
          accessibleSummary: 'A full world map highlights broad, separate areas in Southwest Asia, northern and central China, the New Guinea highlands, the African Sahel, Mesoamerica, and northern South America. No arrows or routes connect them. The wide separation and different local crops support several beginnings of food production, while the soft edges show that these are approximate evidence zones rather than exact invention spots.',
          compactLabel: 'Broad evidence zones · no borders, routes, or pinpoint firsts',
          coordinateNote: 'The lesson makes no claim about a single exact coordinate in any region. Modern Natural Earth coastlines anchor the relative geography; the highlighted zones summarize the broad locations supported by the cited regional studies.',
          uncertaintyNote: 'A glow shows where evidence survives and has been studied, not every community that experimented with plants. Edges, dates, and even the number of independent pathways remain open to revision. China and the Americas each include more than one local pathway within the lesson’s regional grouping.',
          depictionStatus: 'illustrative-reconstruction',
          claimIds: [
            'claim.farming.multi.independent-centers',
            'claim.farming.multi.not-one-revolution',
            'claim.farming.multi.sw-asia',
            'claim.farming.multi.china',
            'claim.farming.multi.new-guinea',
            'claim.farming.multi.africa',
            'claim.farming.multi.americas',
          ],
          sourceIds: [
            'source.farming.natural-earth',
            'source.farming.fuller-2014-convergent',
            'source.farming.denham-2003-kuk',
            'source.farming.deng-2015-baligang',
            'source.farming.winchell-2018-sorghum',
            'source.farming.piperno-2009-maize',
          ],
        },
      ],
    },
    {
      id: 'section.farming.multi.different-evidence',
      heading: 'Different plants leave different clues',
      purpose: 'Compare evidence types and make preservation bias part of the reasoning',
      modules: [
        {
          id: 'module.farming.multi.evidence-comparison',
          type: 'knowledge',
          eyebrow: 'What survives',
          title: 'The evidence does not look the same everywhere',
          body: 'Archaeologists combine several clues. Each can answer some questions and leave others open.',
          items: [
            { label: 'Seeds and grain parts', detail: 'Burned grains can preserve size and shape. Cereal joints can show whether ripe seed heads shattered easily or stayed attached.' },
            { label: 'Starch grains and phytoliths', detail: 'Microscopic traces on tools, in soil, or inside plant remains can identify foods even when soft roots, tubers, and fruits have vanished.' },
            { label: 'Fields and water control', detail: 'Ditches, mounds, and changed wetland soils can show repeated work on a landscape even when the full crop list is uncertain.' },
            { label: 'Tools and use-wear', detail: 'Scratches, polish, and residues can show that people processed plants, but one tool rarely proves who first domesticated them.' },
          ],
          claimIds: ['claim.farming.multi.evidence-bias', 'claim.farming.multi.domestication-process'],
          sourceIds: ['source.farming.denham-2003-kuk', 'source.farming.fullagar-2006-kuk-starch', 'source.farming.fuller-2014-convergent'],
        },
        {
          id: 'module.farming.multi.kuk-close-read',
          type: 'prose',
          body: 'Kuk Swamp in the New Guinea highlands makes the problem clear. Researchers found old channels, mounds, tools, and microscopic plant traces. Together, they support a long history of tending useful plants and, later, more intensive wetland agriculture involving bananas and root crops.\n\nBut the clues have limits. A starch grain can show that someone processed taro or yam; it may not show whether that exact plant was wild or domesticated. A ditch can show people reshaped water and soil; it cannot name the worker or explain every reason for the work.\n\nDry cereal grains often survive charring. Tropical bananas, taro, and yams usually decay. If historians looked only for the evidence common in Southwest Asia, New Guinea might appear to have no farming story. Different evidence does not mean weaker history. It means the questions and methods must fit the plants and landscape.',
          claimIds: ['claim.farming.multi.new-guinea', 'claim.farming.multi.evidence-bias'],
          sourceIds: ['source.farming.denham-2003-kuk', 'source.farming.fullagar-2006-kuk-starch'],
        },
      ],
    },
    {
      id: 'section.farming.multi.not-one-lifestyle',
      heading: 'Farming was not one lifestyle',
      purpose: 'Prevent village-first and automatic-progress stories before the settlement case',
      modules: [
        {
          id: 'module.farming.multi.many-lifeways',
          type: 'prose',
          body: 'A field does not tell us that its growers lived beside it all year. In the Central Balsas region of Mexico, people who used maize and squash could still move seasonally. Elsewhere, some communities spent more time in one place before domesticated crops became central. Cultivation, village life, and domestication could arrive in different orders.\n\nFarming also brought choices and costs, not an automatic upgrade. A dependable crop could feed more people or store well. It could also demand long hours at certain seasons, narrow diets, spread crop disease, or make a failed harvest more dangerous. Evidence rarely preserves everyone\'s share of that work. Women\'s and children\'s labor was probably important, but the surviving seeds and ditches do not identify individual workers.\n\nWarmer Holocene conditions formed part of the background, but they cannot explain why different communities chose different plants at different times. There was no single cause and no guaranteed destination.',
          claimIds: ['claim.farming.multi.not-always-villages', 'claim.farming.multi.independent-centers'],
          sourceIds: ['source.farming.ranere-2009-balsas', 'source.farming.fuller-2014-convergent', 'source.farming.larson-2014-pnas'],
        },
        {
          id: 'module.farming.multi.not-automatic-progress',
          type: 'knowledge',
          eyebrow: 'What farming did - and did not - do',
          title: 'New possibilities, no automatic future',
          body: 'Food production changed what communities could do. It did not push every society along one staircase toward the present.',
          items: [
            { label: 'It could support storage', detail: 'Some crops could be dried and kept, helping communities bridge seasons and plan ahead.' },
            { label: 'It could increase commitments', detail: 'Fields, waterworks, harvests, and stored food tied people to schedules, places, and shared decisions.' },
            { label: 'It did not guarantee cities', detail: 'Cities, states, kings, and writing appeared only in some places, much later, through additional changes and choices.' },
          ],
          claimIds: ['claim.farming.multi.no-automatic-cities', 'claim.farming.multi.not-always-villages'],
          sourceIds: ['source.farming.larson-2014-pnas', 'source.farming.fuller-2014-convergent', 'source.farming.ranere-2009-balsas'],
        },
      ],
    },
    {
      id: 'section.farming.multi.world-check',
      heading: 'World Check',
      purpose: 'Require learners to use a regional example and name an evidence limit',
      modules: [
        {
          id: 'module.farming.multi.prompt-supported',
          type: 'prompt',
          promptId: 'prompt.farming.multi.what-evidence-supports',
          claimIds: [],
          sourceIds: [],
        },
        {
          id: 'module.farming.multi.prompt-explain',
          type: 'prompt',
          promptId: 'prompt.farming.multi.explain-independent',
          claimIds: [],
          sourceIds: [],
        },
      ],
    },
  ],
  claimIds: manyBeginningsOfFarmingClaims.map((claim) => claim.id),
  sourceIds: [
    ...manyBeginningsOfFarmingSources.map((source) => source.id),
    'source.farming.baird-2018-anatolia',
    'source.farming.natural-earth',
  ],
  mediaIds: ['media.farming.multiple-origins-map', 'media.farming.wild-domesticated-wheat'],
  promptIds: manyBeginningsOfFarmingPrompts.map((prompt) => prompt.id),
};

export const manyBeginningsOfFarmingPrototypeReview: LessonPrototypeReview = {
  lessonId: 'lesson.farming.multiple-origins',
  researchNotePath: 'docs/research/many-beginnings-of-farming.md',
  validationTier: 'reference',
  mediaIntentions: [
    {
      sectionId: 'section.farming.multi.what-domestication',
      kind: 'diagram',
      purpose: 'Compare a wild cereal ear that drops ripe grains with a domesticated ear that holds them for harvest.',
      status: 'ready',
      mediaId: 'media.farming.wild-domesticated-wheat',
    },
    {
      sectionId: 'section.farming.multi.five-beginnings',
      kind: 'map',
      purpose: 'Locate illustrative early food-production regions without borders, pinpoint firsts, diffusion arrows, or a claim that the set is complete.',
      status: 'ready',
      mediaId: 'media.farming.multiple-origins-map',
    },
    {
      sectionId: 'section.farming.multi.different-evidence',
      kind: 'other',
      purpose: 'Ask which clues survive from cereal farming versus tropical root-crop and wetland cultivation, and what each evidence set leaves uncertain.',
      status: 'not-needed',
    },
  ],
  productReview: {
    state: 'approved',
    reviewedBy: 'Carlin Aylsworth',
    reviewedOn: '2026-08-11',
    notes: 'Approved the learner-prototype checkpoint in the Codex task: "love the prototype".',
  },
  learnerReview: {
    required: true,
    state: 'not-scheduled',
    notes: 'Required because this lesson establishes the reference process; an adult proxy review does not replace an ages 11-14 walkthrough.',
  },
};

export const manyBeginningsOfFarmingContent: AuthoredContentModule = {
  sources: manyBeginningsOfFarmingSources,
  claims: manyBeginningsOfFarmingClaims,
  media: manyBeginningsOfFarmingMedia,
  prompts: manyBeginningsOfFarmingPrompts,
  lessons: [manyBeginningsOfFarmingLesson],
  prototypeReviews: [manyBeginningsOfFarmingPrototypeReview],
};
