import type { Claim, Lesson, MediaAsset, Source, UnderstandingPrompt } from '../../src/domains/contracts';
import type { AuthoredContentModule } from '../assemble';
import { mediaLocator } from '../shared/media-locator';

export const manyBeginningsOfFarmingSources: Source[] = [
  {
    id: 'source.farming.larson-2014-pnas',
    title: 'Current perspectives and the future of domestication studies',
    url: 'https://doi.org/10.1073/pnas.1323964111',
    publisher: 'Proceedings of the National Academy of Sciences',
    accessedOn: '2026-07-27',
    licenseOrUse: 'Open-access scholarly synthesis cited for research; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.fuller-2014-convergent',
    title: 'Convergent evolution and parallelism in plant domestication revealed by an expanding archaeological record',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4035951/',
    publisher: 'Proceedings of the National Academy of Sciences',
    accessedOn: '2026-07-27',
    licenseOrUse: 'Open-access scholarly synthesis cited for research; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.fuller-willcox-2011',
    title: 'Cultivation and domestication had multiple origins: arguments against the core area hypothesis for the origins of agriculture in the Near East',
    url: 'https://doi.org/10.1080/00438243.2011.624747',
    publisher: 'World Archaeology',
    accessedOn: '2026-07-27',
    licenseOrUse: 'Peer-reviewed scholarship cited as a fact and interpretation source; article media are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.denham-2003-kuk',
    title: 'Origins of agriculture at Kuk Swamp in the highlands of New Guinea',
    url: 'https://doi.org/10.1126/science.1085255',
    publisher: 'Science',
    accessedOn: '2026-07-27',
    licenseOrUse: 'Peer-reviewed excavation synthesis cited as a fact source; article media are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.fullagar-2006-kuk-starch',
    title: 'Early and mid Holocene tool-use and processing of taro and yam at Kuk Swamp, Papua New Guinea',
    url: 'https://doi.org/10.1016/j.jas.2005.07.020',
    publisher: 'Journal of Archaeological Science',
    accessedOn: '2026-07-27',
    licenseOrUse: 'Peer-reviewed residue and use-wear study cited as a fact source; article media are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.deng-2015-baligang',
    title: 'From Early Domesticated Rice of the Middle Yangtze Basin to Millet, Rice and Wheat Agriculture',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4604147/',
    publisher: 'PLOS ONE',
    accessedOn: '2026-07-27',
    licenseOrUse: 'CC BY scholarly article cited as a fact source',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.winchell-2018-sorghum',
    title: 'On the origins and dissemination of domesticated sorghum and pearl millet across Africa and into India',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6394749/',
    publisher: 'African Archaeological Review',
    accessedOn: '2026-07-27',
    licenseOrUse: 'Open-access scholarly synthesis cited as a fact source; figures are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.barron-2020-pearl-millet',
    title: 'The transition from wild to domesticated pearl millet in the Tilemsi Valley of Mali',
    url: 'https://doi.org/10.1007/s10437-021-09428-8',
    publisher: 'African Archaeological Review',
    accessedOn: '2026-07-27',
    licenseOrUse: 'Peer-reviewed archaeobotanical research cited as a fact source; article media are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.piperno-2009-maize',
    title: 'Starch grain and phytolith evidence for early ninth millennium B.P. maize from the Central Balsas River Valley, Mexico',
    url: 'https://doi.org/10.1073/pnas.0812525106',
    publisher: 'Proceedings of the National Academy of Sciences',
    accessedOn: '2026-07-27',
    licenseOrUse: 'Peer-reviewed microfossil study cited as a fact source; article media are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.ranere-2009-balsas',
    title: 'The cultural and chronological context of early Holocene maize and squash domestication in the Central Balsas River Valley, Mexico',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC2664064/',
    publisher: 'Proceedings of the National Academy of Sciences',
    accessedOn: '2026-07-27',
    licenseOrUse: 'Open-access excavation context cited as a fact source; article media are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.fuks-marom-2021-wheat',
    title: 'Sheep and wheat domestication in southwest Asia: a meta-trajectory of intensification and loss',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8214439/',
    publisher: 'Animal Frontiers',
    accessedOn: '2026-08-11',
    licenseOrUse: 'CC BY 4.0 scientific comparison used as the factual and visual reference for the Chronos wheat-ear diagram',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.golson-2017-kuk-intro',
    title: 'An introduction to the investigations at Kuk Swamp',
    url: 'https://press-files.anu.edu.au/downloads/press/n2540/html/ch01.xhtml',
    publisher: 'Jack Golson, in Ten Thousand Years of Cultivation at Kuk Swamp in the Highlands of Papua New Guinea (Terra Australis 46), ANU Press (2017)',
    accessedOn: '2026-09-24',
    licenseOrUse: 'Excavator’s own open-access account cited for the 1969 drainage of Kuk Swamp for a Tea Research Station, the ancient ditch profiles exposed in the walls of the new drains, and Golson’s August 1970 visit; paraphrase only, no images',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.unesco-kuk',
    title: 'Kuk Early Agricultural Site',
    url: 'https://whc.unesco.org/en/list/887/',
    publisher: 'UNESCO World Heritage Centre',
    accessedOn: '2026-09-24',
    licenseOrUse: 'World Heritage listing description cited for the site’s altitude (1,500 m), cultivation mounds followed by wetland drainage ditches dug with wooden tools, and banana, taro and yam cultivation; paraphrase only, no images',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.nsf-2009-balsas-maize',
    title: 'Wild grass became maize crop more than 8,700 years ago',
    url: 'https://www.eurekalert.org/news-releases/717396',
    publisher: 'U.S. National Science Foundation news release via EurekAlert! (23 March 2009)',
    accessedOn: '2026-09-24',
    licenseOrUse: 'Funder’s summary of Piperno et al. and Ranere et al. 2009 cited for Balsas teosinte as a large wild grass and maize’s ancestor, and for maize and squash remains with stone grinding tools at the shelter; paraphrase only',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.smithsonian-2009-balsas',
    title: 'New Research Reveals the Earliest Evidence for Corn in the New World',
    url: 'https://www.si.edu/newsdesk/releases/new-research-reveals-earliest-evidence-corn-new-world',
    publisher: 'Smithsonian Institution news release (23 March 2009)',
    accessedOn: '2026-09-24',
    licenseOrUse: 'Research institution’s summary cited for the Xihuatoxtla rock shelter, starch and phytolith evidence of maize and squash by 8,700 years ago, and small cultivating groups shifting settlements seasonally; paraphrase only',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.farming.uw-2015-teosinte',
    title: 'UW study shows how a kernel got naked and corn became king',
    url: 'https://news.wisc.edu/uw-study-shows-how-a-kernel-got-naked-and-corn-became-king/',
    publisher: 'University of Wisconsin–Madison News (27 July 2015)',
    accessedOn: '2026-09-24',
    licenseOrUse: 'University news report on John Doebley’s research cited for teosinte ears holding 10 to 12 kernels in hard, inedible casings versus maize ears with hundreds of exposed kernels; paraphrase only, no images',
    reviewStatus: 'reviewed',
  },
];

export const manyBeginningsOfFarmingClaims: Claim[] = [
  {
    id: 'claim.farming.multi.independent-centers',
    statement: 'People developed food production independently in several regions using local plants and practices.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.larson-2014-pnas', 'source.farming.fuller-2014-convergent'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.not-one-revolution',
    statement: 'Farming did not begin as one worldwide invention in Southwest Asia that every other region simply copied.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.fuller-willcox-2011', 'source.farming.larson-2014-pnas'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.domestication-process',
    statement: 'Cultivation can begin before plants show the inherited physical changes archaeologists use to identify domestication.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.larson-2014-pnas', 'source.farming.fuller-2014-convergent'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.cereal-protracted',
    statement: 'In several major Old World cereals, domestication traits developed over many generations rather than in one sudden switch.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.fuller-2014-convergent'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.sw-asia',
    statement: 'Southwest Asia was one early region where communities gradually cultivated and domesticated local cereals and pulses.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.fuller-willcox-2011', 'source.farming.baird-2018-anatolia'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.china',
    statement: 'Early food production in China included distinct northern millet and Yangtze rice traditions.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.deng-2015-baligang', 'source.farming.fuller-2014-convergent'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.new-guinea',
    statement: 'New Guinea communities independently developed cultivation and wetland agriculture involving plants including bananas, taro, and yams.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.denham-2003-kuk', 'source.farming.fullagar-2006-kuk-starch'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.africa',
    statement: 'African communities followed independent cereal-domestication pathways including pearl millet in the western Sahel and sorghum in the eastern Sahel.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.winchell-2018-sorghum', 'source.farming.barron-2020-pearl-millet'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.americas',
    statement: 'People in the Americas independently domesticated local plants, including maize in the Central Balsas region of Mexico by about 8,700 years ago.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.piperno-2009-maize', 'source.farming.ranere-2009-balsas'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.not-always-villages',
    statement: 'Cultivation could be part of mobile or seasonally mobile lifeways, so dense permanent villages were not a universal first step.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.ranere-2009-balsas', 'source.farming.fuller-2014-convergent'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.no-automatic-cities',
    statement: 'Food production created new possibilities but did not automatically produce cities, states, writing, or kings.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.larson-2014-pnas', 'source.farming.fuller-2014-convergent'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.evidence-bias',
    statement: 'Tropical tubers and wetland traces preserve differently from dryland cereal grains, so different regions leave different archaeological records.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.farming.denham-2003-kuk', 'source.farming.fullagar-2006-kuk-starch', 'source.farming.fuller-2014-convergent'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.kuk-drains-find',
    statement: 'In 1969, drains dug to prepare part of Kuk Swamp for a tea research station exposed the profiles of many ancient ditches in their walls; the archaeologist Jack Golson inspected them in 1970.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.farming.golson-2017-kuk-intro'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.kuk-mounds-ditches',
    statement: 'Kuk lies about 1,500 meters above sea level; agriculture there arose independently by at least about 7,000 years ago, beginning with cultivation mounds and later draining the wetland with ditches dug with wooden tools.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.farming.unesco-kuk', 'source.farming.denham-2003-kuk'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.kuk-starch-10000',
    statement: 'Starch residues and use-wear on stone tools show people at Kuk processing taro and yams about 10,000 years ago.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.farming.fullagar-2006-kuk-starch'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.teosinte-ancestor',
    statement: 'Maize was domesticated from Balsas teosinte, a wild grass of southwestern Mexico whose small ears hold about 10 to 12 kernels in hard, inedible casings, while maize ears hold hundreds of exposed kernels.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.farming.nsf-2009-balsas-maize', 'source.farming.uw-2015-teosinte'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.balsas-xihuatoxtla',
    statement: 'Starch grains and phytoliths of maize and squash from Xihuatoxtla rock shelter in the Central Balsas valley, found with stone grinding tools, date to at least about 8,700 years ago.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.farming.smithsonian-2009-balsas', 'source.farming.nsf-2009-balsas-maize', 'source.farming.piperno-2009-maize'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.balsas-seasonal',
    statement: 'Early cultivators in the Central Balsas region appear to have lived in small groups that shifted their settlements seasonally and used a variety of ways of getting food.',
    kind: 'interpretation',
    certainty: 'moderate',
    sourceIds: ['source.farming.smithsonian-2009-balsas', 'source.farming.ranere-2009-balsas'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.farming.multi.millet-pottery-imprints',
    statement: 'In northern Mali, pearl millet chaff used as temper survives as imprints in pottery; older sherds show wild forms, and sherds dated to about 3000-2000 BCE show domesticated spikelets.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.farming.barron-2020-pearl-millet'],
    reviewStatus: 'reviewed',
  },
];

export const manyBeginningsOfFarmingMedia: MediaAsset[] = [
  {
    id: 'media.farming.multiple-origins-map',
    locator: mediaLocator('media.farming.multiple-origins-map'),
    alt: 'World map with soft highlighted zones in Southwest Asia, northern and central China, the New Guinea highlands, the African Sahel, Mesoamerica, and northern South America; no arrows connect the regions',
    depictionMode: 'map',
    depictionLabel: 'Evidence-led world map · broad regions are approximate, modern coasts provide orientation',
    rightsLabel: 'Chronos original map edit · Natural Earth base geography, Public Domain',
    sourceIds: [
      'source.farming.natural-earth',
      'source.farming.fuller-2014-convergent',
      'source.farming.denham-2003-kuk',
      'source.farming.deng-2015-baligang',
      'source.farming.winchell-2018-sorghum',
      'source.farming.piperno-2009-maize',
    ],
    visualBriefRef: 'docs/research/many-beginnings-of-farming-map.md#generated-artwork-lineage',
    reviewStatus: 'approved',
  },
  {
    id: 'media.farming.wild-domesticated-wheat',
    locator: mediaLocator('media.farming.wild-domesticated-wheat'),
    alt: 'Illustrated sequence comparing wheat dispersal: a farmer gathers and threshes a compact domesticated ear with a rough break scar, while a looser wild ear disarticulates into falling spikelets with smooth scars',
    depictionMode: 'diagram',
    depictionLabel: 'Evidence-led botanical diagram · one cereal mechanism, not every domestication pathway',
    rightsLabel: 'Chronos original diagram · scientific reference adapted from Fuks and Marom 2021, CC BY 4.0',
    sourceIds: ['source.farming.fuks-marom-2021-wheat', 'source.farming.fuller-2014-convergent'],
    visualBriefRef: 'docs/research/many-beginnings-of-farming.md#image-lifecycle',
    reviewStatus: 'approved',
  },
];

export const manyBeginningsOfFarmingPrompts: UnderstandingPrompt[] = [
  {
    id: 'prompt.farming.multi.what-evidence-supports',
    lessonId: 'lesson.farming.multiple-origins',
    kind: 'supported-selection',
    question: 'Looking across Southwest Asia, China, New Guinea, Africa, and the Americas, which conclusion is best supported?',
    explanation: 'Different communities worked with different local plants on different timelines. That pattern supports several independent beginnings, not one invention copied everywhere.',
    required: true,
    options: [
      { id: 'option.farming.multi.several-beginnings', label: 'Farming began independently in several regions with different crops.' },
      { id: 'option.farming.multi.one-beginning', label: 'Farming was invented once in Southwest Asia and then copied everywhere.' },
      { id: 'option.farming.multi.villages-first', label: 'Dense permanent villages always appeared before cultivation.' },
      { id: 'option.farming.multi.one-continent', label: 'Useful evidence for early farming survives on only one continent.' },
    ],
  },
  {
    id: 'prompt.farming.multi.explain-independent',
    lessonId: 'lesson.farming.multiple-origins',
    kind: 'concise-explanation',
    question: 'Choose one region. How do its crops or clues support an independent beginning of farming, and what can those clues not prove by themselves?',
    explanation: 'A strong explanation connects a local crop or clue to the wider pattern, then names a limit - such as the exact first person, exact start day, motives, or whether farming made life better.',
    required: true,
    minimumResponseLength: 30,
  },
];

export const manyBeginningsOfFarmingLesson: Lesson = {
  id: 'lesson.farming.multiple-origins',
  legacyAliases: ['neolithic_revolution'],
  status: 'published',
  title: 'Many Beginnings of Farming',
  masthead: 'c. 10,000-3000 BCE',
  place: 'Several regions across the world',
  chronology: {
    startYear: -10000,
    endYear: -3000,
    display: 'c. 10,000-3000 BCE',
    approximate: true,
  },
  significance: 'Farming began more than once, as communities in different regions gradually changed local plants - and were changed by the work of growing them.',
  sectionIdsRequired: [
    'section.farming.multi.not-once',
    'section.farming.multi.what-domestication',
    'section.farming.multi.five-beginnings',
    'section.farming.multi.different-evidence',
    'section.farming.multi.not-one-lifestyle',
    'section.farming.multi.world-check',
  ],
  sections: [
    {
      id: 'section.farming.multi.not-once',
      heading: 'Farming did not begin once',
      purpose: 'Break the single-revolution myth and establish the lesson question',
      modules: [
        {
          id: 'module.farming.multi.opening',
          type: 'prose',
          body: 'In 1969, drainage channels began cutting across Kuk Swamp, 1,500 meters up in the highlands of New Guinea. The swamp was being drained for a new tea research station. But the fresh walls of the drains showed something nobody had planned for: the outlines of many much older ditches, buried in the layers of the swamp. The archaeologist Jack Golson came to look in 1970. Years of digging showed that people had been tending plants at Kuk for thousands of years, and that by at least 7,000 years ago they were farming there.\n\nKuk did not fit the story many history books told. That story put farming\'s birthplace at a single dot on the map, in Southwest Asia, in the region often called the Fertile Crescent: people there invented farming, and everyone else copied it. The gardeners of Kuk grew bananas, taro, and yams, not wheat, and they worked it out for themselves.\n\nKuk was one of several beginnings. After about 10,000 BCE, communities in far-apart regions began changing how they gathered, tended, planted, and harvested food: wheat and barley in Southwest Asia, millet and rice in China, pearl millet and sorghum in Africa, maize and squash in the Americas. Southwest Asia was an important early beginning, but not the only one. So the real question is not who invented farming first. It is how different people, in different landscapes, each came to grow their food.',
          claimIds: [
            'claim.farming.multi.independent-centers',
            'claim.farming.multi.not-one-revolution',
            'claim.farming.multi.kuk-drains-find',
            'claim.farming.multi.kuk-mounds-ditches',
            'claim.farming.multi.new-guinea',
          ],
          sourceIds: [
            'source.farming.larson-2014-pnas',
            'source.farming.fuller-2014-convergent',
            'source.farming.fuller-willcox-2011',
            'source.farming.golson-2017-kuk-intro',
            'source.farming.unesco-kuk',
            'source.farming.denham-2003-kuk',
            'source.farming.fullagar-2006-kuk-starch',
          ],
        },
        {
          id: 'module.farming.multi.words-for-change',
          type: 'knowledge',
          eyebrow: 'Three useful words',
          title: 'Foraging, cultivation, and domestication',
          body: 'Every one of these beginnings was slow. Three words help follow the change without pretending every region took the same path.',
          items: [
            { label: 'Foraging', detail: 'Finding, gathering, hunting, and managing foods that grow or live without being planted as crops.' },
            { label: 'Cultivation', detail: 'Deliberately tending and planting useful plants. Cultivation can happen before the plants themselves look domesticated.' },
            { label: 'Domestication', detail: 'Inherited changes in plants that build up as people repeatedly select, protect, move, and reproduce them.' },
          ],
          claimIds: ['claim.farming.multi.domestication-process'],
          sourceIds: ['source.farming.larson-2014-pnas', 'source.farming.fuller-2014-convergent'],
        },
      ],
    },
    {
      id: 'section.farming.multi.what-domestication',
      heading: 'Plants changed with people',
      purpose: 'Make gradual domestication concrete through one cereal mechanism',
      modules: [
        {
          id: 'module.farming.multi.cereal-example',
          type: 'prose',
          body: 'Wild wheat is built to scatter. As an ear ripens, the stem that holds its grains together turns brittle and breaks, and the grains drop to the ground a piece at a time. That is good for the plant. It is bad news for anyone hoping to gather a basketful.\n\nSo the grain people carried home came mostly from ears that were still holding together. When they planted some of it, the plants that clung to their seeds got another chance to grow. Nobody needed to know about genes or plan a breeding program. Harvest after harvest, those ordinary choices made the stay-attached trait more common, so slowly that in major cereals it took many generations to spread. Cultivation could be under way long before a crop crossed any neat line into "domesticated."\n\nGiven enough time, a plant could change almost beyond recognition. Maize comes from teosinte, a wild grass of Mexico\'s Balsas River valley. A teosinte ear is small and holds only 10 to 12 kernels, each sealed in a hard, inedible case. An ear of maize holds hundreds of kernels, bare and ready to eat.',
          claimIds: ['claim.farming.multi.domestication-process', 'claim.farming.multi.cereal-protracted', 'claim.farming.multi.teosinte-ancestor'],
          sourceIds: [
            'source.farming.fuller-2014-convergent',
            'source.farming.larson-2014-pnas',
            'source.farming.fuks-marom-2021-wheat',
            'source.farming.nsf-2009-balsas-maize',
            'source.farming.uw-2015-teosinte',
          ],
        },
        {
          id: 'module.farming.multi.wheat-comparison',
          type: 'evidence',
          title: 'Which ear is easier to gather?',
          artifactLabel: 'Plant evidence model',
          body: 'Compare the two ears. The wild ear on the right falls apart when ripe, and each piece breaks off cleanly, leaving a smooth scar. The domesticated ear on the left stays whole until people thresh it, and its pieces tear off with a rough scar. Archaeologists look for those same scars on ancient cereal remains. This is one mechanism in one crop; other crops and regions followed different pathways.',
          mediaId: 'media.farming.wild-domesticated-wheat',
          claimIds: ['claim.farming.multi.domestication-process', 'claim.farming.multi.cereal-protracted'],
          sourceIds: ['source.farming.fuks-marom-2021-wheat', 'source.farming.fuller-2014-convergent'],
        },
        {
          id: 'module.farming.multi.process-not-plan',
          type: 'knowledge',
          eyebrow: 'A two-way change',
          title: 'People changed plants, and plants changed people',
          body: 'Domestication was not a one-way command. New plant traits and new human routines developed together.',
          items: [
            { label: 'People selected', detail: 'Where, when, and how people gathered and replanted changed which plants reproduced.' },
            { label: 'Plants responded over generations', detail: 'Useful inherited traits became more common, although the pace differed from crop to crop.' },
            { label: 'Work changed too', detail: 'Preparing ground, planting, weeding, watering, harvesting, processing, and storing tied communities to new seasonal tasks.' },
          ],
          claimIds: ['claim.farming.multi.domestication-process', 'claim.farming.multi.cereal-protracted'],
          sourceIds: ['source.farming.larson-2014-pnas', 'source.farming.fuller-2014-convergent'],
        },
      ],
    },
    {
      id: 'section.farming.multi.five-beginnings',
      heading: 'Several regions, different pathways',
      purpose: 'Build a global mental map from illustrative regions and their local crops without implying a complete count',
      modules: [
        {
          id: 'module.farming.multi.regional-pattern',
          type: 'knowledge',
          eyebrow: 'Approximate early zones',
          title: 'Different regions, different crops',
          body: 'These are broad regions, not five exact invention spots. Dates continue to be refined, and more independent beginnings existed than this lesson can show.',
          items: [
            { label: 'Southwest Asia', detail: 'Communities gradually cultivated and domesticated local cereals such as wheat and barley, together with pulses such as lentils.' },
            { label: 'China', detail: 'Northern millet traditions and Yangtze rice traditions developed along different pathways before crops later mixed between regions.' },
            { label: 'New Guinea', detail: 'At Kuk, people grew bananas, taro, and yams, first in planting mounds and later in wetland gardens drained by ditches dug with wooden tools.' },
            { label: 'Africa', detail: 'People domesticated local cereals along more than one pathway: pearl millet in the western Sahel, sorghum farther east. In Mali, pearl millet chaff that potters mixed into clay left imprints: wild forms in older pots, domesticated ones by about 3000-2000 BCE.' },
            { label: 'Americas', detail: 'Communities domesticated local plants in several areas. At Xihuatoxtla rock shelter in Mexico\'s Balsas valley, microscopic traces of maize and squash found with stone grinding tools date to about 8,700 years ago.' },
          ],
          claimIds: [
            'claim.farming.multi.sw-asia',
            'claim.farming.multi.china',
            'claim.farming.multi.new-guinea',
            'claim.farming.multi.africa',
            'claim.farming.multi.americas',
            'claim.farming.multi.kuk-mounds-ditches',
            'claim.farming.multi.millet-pottery-imprints',
            'claim.farming.multi.balsas-xihuatoxtla',
          ],
          sourceIds: [
            'source.farming.fuller-willcox-2011',
            'source.farming.baird-2018-anatolia',
            'source.farming.deng-2015-baligang',
            'source.farming.denham-2003-kuk',
            'source.farming.winchell-2018-sorghum',
            'source.farming.barron-2020-pearl-millet',
            'source.farming.piperno-2009-maize',
            'source.farming.ranere-2009-balsas',
            'source.farming.unesco-kuk',
            'source.farming.smithsonian-2009-balsas',
            'source.farming.nsf-2009-balsas-maize',
          ],
        },
        {
          id: 'module.farming.multi.map-alternative',
          type: 'historical-map',
          introLayout: 'dense',
          eyebrow: 'Approximate early zones',
          title: 'No single birthplace',
          body: 'The highlighted areas show several broad regions where evidence supports independent food-production pathways. Compare their distance and their local crops. There are no arrows because this is not a story of one invention spreading everywhere.',
          mediaId: 'media.farming.multiple-origins-map',
          periodLabel: 'c. 10,000–3000 BCE',
          focusPlace: 'Several regions across the world',
          modernContext: 'Modern coastlines are used only for orientation',
          accessibleSummary: 'A full world map highlights broad, separate areas in Southwest Asia, northern and central China, the New Guinea highlands, the African Sahel, Mesoamerica, and northern South America. No arrows or routes connect them. The wide separation and different local crops support several beginnings of food production, while the soft edges show that these are approximate evidence zones rather than exact invention spots.',
          compactLabel: 'Broad evidence zones · no borders, routes, or pinpoint firsts',
          coordinateNote: 'The lesson makes no claim about a single exact coordinate in any region. Modern Natural Earth coastlines anchor the relative geography; the highlighted zones summarize the broad locations supported by the cited regional studies.',
          uncertaintyNote: 'A glow shows where evidence survives and has been studied, not every community that experimented with plants. Edges, dates, and even the number of independent pathways remain open to revision. China and the Americas each include more than one local pathway within the lesson’s regional grouping.',
          depictionStatus: 'illustrative-reconstruction',
          claimIds: [
            'claim.farming.multi.independent-centers',
            'claim.farming.multi.not-one-revolution',
            'claim.farming.multi.sw-asia',
            'claim.farming.multi.china',
            'claim.farming.multi.new-guinea',
            'claim.farming.multi.africa',
            'claim.farming.multi.americas',
          ],
          sourceIds: [
            'source.farming.natural-earth',
            'source.farming.fuller-2014-convergent',
            'source.farming.denham-2003-kuk',
            'source.farming.deng-2015-baligang',
            'source.farming.winchell-2018-sorghum',
            'source.farming.piperno-2009-maize',
          ],
        },
      ],
    },
    {
      id: 'section.farming.multi.different-evidence',
      heading: 'Different plants leave different clues',
      purpose: 'Compare evidence types and make preservation bias part of the reasoning',
      modules: [
        {
          id: 'module.farming.multi.evidence-comparison',
          type: 'knowledge',
          eyebrow: 'What survives',
          title: 'The evidence does not look the same everywhere',
          body: 'Archaeologists combine several clues. Each can answer some questions and leave others open.',
          items: [
            { label: 'Seeds and grain parts', detail: 'Burned grains can preserve size and shape. Cereal joints can show whether ripe seed heads shattered easily or stayed attached.' },
            { label: 'Starch grains and phytoliths', detail: 'Microscopic traces on tools, in soil, or inside plant remains can identify foods even when soft roots, tubers, and fruits have vanished.' },
            { label: 'Fields and water control', detail: 'Ditches, mounds, and changed wetland soils can show repeated work on a landscape even when the full crop list is uncertain.' },
            { label: 'Tools and use-wear', detail: 'Scratches, polish, and residues can show that people processed plants, but one tool rarely proves who first domesticated them.' },
          ],
          claimIds: ['claim.farming.multi.evidence-bias', 'claim.farming.multi.domestication-process'],
          sourceIds: ['source.farming.denham-2003-kuk', 'source.farming.fullagar-2006-kuk-starch', 'source.farming.fuller-2014-convergent'],
        },
        {
          id: 'module.farming.multi.kuk-close-read',
          type: 'prose',
          body: 'Back at Kuk, the drains of 1969 had opened a puzzle. The old ditches and mounds showed that people had reshaped the swamp again and again. But what were they growing? Bananas, taro, and yams have no hard seeds to char and survive; they rot. So researchers turned to the microscope. Starch grains and wear on stone tools show that people at Kuk were processing taro and yams about 10,000 years ago. Plant traces from later layers point to bananas grown in larger numbers.\n\nEach clue has limits. A starch grain can show that someone processed taro, but not always whether that plant was wild or cultivated. A ditch shows that people moved water and soil; it cannot name the diggers or explain every reason for their work.\n\nIf historians looked only for the charred grain that survives so well in drier lands, Kuk would seem to have no farming story at all. Different evidence does not mean weaker history. It means the questions have to fit the plants and the landscape.',
          claimIds: [
            'claim.farming.multi.new-guinea',
            'claim.farming.multi.evidence-bias',
            'claim.farming.multi.kuk-starch-10000',
            'claim.farming.multi.kuk-drains-find',
          ],
          sourceIds: ['source.farming.denham-2003-kuk', 'source.farming.fullagar-2006-kuk-starch', 'source.farming.golson-2017-kuk-intro'],
        },
      ],
    },
    {
      id: 'section.farming.multi.not-one-lifestyle',
      heading: 'Farming was not one lifestyle',
      purpose: 'Prevent village-first and automatic-progress stories before the settlement case',
      modules: [
        {
          id: 'module.farming.multi.many-lifeways',
          type: 'prose',
          body: 'A field does not prove that its growers lived beside it all year. The people who left maize at Xihuatoxtla seem to have lived in small groups that moved their settlements with the seasons. Elsewhere, some communities settled in one place before domesticated crops became central. Cultivation, village life, and domestication could arrive in different orders.\n\nFarming also brought costs, not an automatic upgrade. A dependable crop could feed more people or store well. It could also demand long hours in certain seasons, narrow diets, spread crop disease, or make a failed harvest more dangerous. Warmer conditions after the last Ice Age formed part of the background, but they cannot explain why different communities chose different plants at different times.\n\nAt Kuk, as everywhere else in this lesson, the gardeners\' names are gone. Women\'s and children\'s work was probably important, but seeds and ditches do not identify individual workers. What survives is the work itself: ditches dug with wooden tools, found again thousands of years later by the drains of a tea research station.',
          claimIds: [
            'claim.farming.multi.not-always-villages',
            'claim.farming.multi.independent-centers',
            'claim.farming.multi.balsas-seasonal',
            'claim.farming.multi.kuk-mounds-ditches',
            'claim.farming.multi.kuk-drains-find',
          ],
          sourceIds: [
            'source.farming.ranere-2009-balsas',
            'source.farming.fuller-2014-convergent',
            'source.farming.larson-2014-pnas',
            'source.farming.smithsonian-2009-balsas',
            'source.farming.unesco-kuk',
            'source.farming.golson-2017-kuk-intro',
          ],
        },
        {
          id: 'module.farming.multi.not-automatic-progress',
          type: 'knowledge',
          eyebrow: 'What farming did - and did not - do',
          title: 'New possibilities, no automatic future',
          body: 'Food production changed what communities could do. It did not push every society along one staircase toward the present.',
          items: [
            { label: 'It could support storage', detail: 'Some crops could be dried and kept, helping communities bridge seasons and plan ahead.' },
            { label: 'It could increase commitments', detail: 'Fields, waterworks, harvests, and stored food tied people to schedules, places, and shared decisions.' },
            { label: 'It did not guarantee cities', detail: 'Cities, states, kings, and writing appeared only in some places, much later, through additional changes and choices.' },
          ],
          claimIds: ['claim.farming.multi.no-automatic-cities', 'claim.farming.multi.not-always-villages'],
          sourceIds: ['source.farming.larson-2014-pnas', 'source.farming.fuller-2014-convergent', 'source.farming.ranere-2009-balsas'],
        },
      ],
    },
    {
      id: 'section.farming.multi.world-check',
      heading: 'World Check',
      purpose: 'Require learners to use a regional example and name an evidence limit',
      modules: [
        {
          id: 'module.farming.multi.prompt-supported',
          type: 'prompt',
          promptId: 'prompt.farming.multi.what-evidence-supports',
          claimIds: [],
          sourceIds: [],
        },
        {
          id: 'module.farming.multi.prompt-explain',
          type: 'prompt',
          promptId: 'prompt.farming.multi.explain-independent',
          claimIds: [],
          sourceIds: [],
        },
      ],
    },
  ],
  claimIds: manyBeginningsOfFarmingClaims.map((claim) => claim.id),
  sourceIds: [
    ...manyBeginningsOfFarmingSources.map((source) => source.id),
    'source.farming.baird-2018-anatolia',
    'source.farming.natural-earth',
  ],
  mediaIds: ['media.farming.multiple-origins-map', 'media.farming.wild-domesticated-wheat'],
  promptIds: manyBeginningsOfFarmingPrompts.map((prompt) => prompt.id),
};

export const manyBeginningsOfFarmingContent: AuthoredContentModule = {
  sources: manyBeginningsOfFarmingSources,
  claims: manyBeginningsOfFarmingClaims,
  media: manyBeginningsOfFarmingMedia,
  prompts: manyBeginningsOfFarmingPrompts,
  lessons: [manyBeginningsOfFarmingLesson],
};
