import type { Claim, KnowledgeCard, Lesson, MediaAsset, Source, UnderstandingPrompt } from '../../src/domains/contracts';
import type { AuthoredContentModule } from '../assemble';
import { mediaLocator } from '../shared/media-locator';

export const migrationsAncientDnaSources: Source[] = [
  {
    id: 'source.humans.hallett-2025-niche',
    title: 'Major expansion in the human niche preceded out of Africa dispersal',
    url: 'https://www.nature.com/articles/s41586-025-09154-0',
    publisher: 'Nature',
    accessedOn: '2026-07-26',
    licenseOrUse: 'CC BY 4.0 primary research cited for repeated dispersals and changing ecological range',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.sumer-2024-admixture',
    title: 'Earliest modern human genomes constrain timing of Neanderthal admixture',
    url: 'https://www.nature.com/articles/s41586-024-08420-x',
    publisher: 'Nature',
    accessedOn: '2026-07-26',
    licenseOrUse: 'CC BY 4.0 primary genome study; third-party specimen photographs are not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.green-2010-neanderthal',
    title: 'A draft sequence of the Neandertal genome',
    url: 'https://pubmed.ncbi.nlm.nih.gov/20448178/',
    publisher: 'Science',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Peer-reviewed foundational genome study cited as a fact source; media not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.fu-2015-oase',
    title: 'An early modern human from Romania with a recent Neanderthal ancestor',
    url: 'https://www.nature.com/articles/nature14558',
    publisher: 'Nature',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Peer-reviewed primary genome study cited as a fact source; rights-reserved photographs not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.reich-2010-denisova',
    title: 'Genetic history of an archaic hominin group from Denisova Cave in Siberia',
    url: 'https://www.nature.com/articles/nature09710',
    publisher: 'Nature',
    accessedOn: '2026-07-26',
    licenseOrUse: 'CC BY-NC-SA primary study used for facts only; no media redistribution',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.denisova-project',
    title: 'Denisova genome project',
    url: 'https://www.eva.mpg.de/genetics/genome-projects/denisova/',
    publisher: 'Max Planck Institute for Evolutionary Anthropology',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Institutional project record cited for the small fossil sample and genome work; images not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.zhang-2025-harbin-mtdna',
    title: 'Denisovan mitochondrial DNA from dental calculus of the >146,000-year-old Harbin cranium',
    url: 'https://www.sciencedirect.com/science/article/pii/S0092867425006270',
    publisher: 'Cell',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Peer-reviewed primary molecular study cited as a fact source; media not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.welker-2025-harbin-proteome',
    title: 'The proteome of the late Middle Pleistocene Harbin individual',
    url: 'https://doi.org/10.1126/science.adu9677',
    publisher: 'Science',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Peer-reviewed primary protein study cited as a fact source; media not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.jacobs-2019-denisovan',
    title: 'Multiple Deeply Divergent Denisovan Ancestries in Papuans',
    url: 'https://api.repository.cam.ac.uk/server/api/core/bitstreams/d7ffe16b-0df0-4bb3-9aa4-c4cde7ac6cd2/content',
    publisher: 'Cell',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Peer-reviewed primary genome study cited as a fact source; media not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.chen-2020-backmigration',
    title: 'Identifying and Interpreting Apparent Neanderthal Ancestry in African Individuals',
    url: 'https://www.sciencedirect.com/science/article/pii/S0092867420300593',
    publisher: 'Cell',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Peer-reviewed genome study cited to qualify simple Africa/non-Africa ancestry claims',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.orlando-2021-adna',
    title: 'Ancient DNA analysis',
    url: 'https://www.nature.com/articles/s43586-020-00011-0',
    publisher: 'Nature Reviews Methods Primers',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Peer-reviewed methods review cited for preservation, contamination, sampling, and inference limits',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.eurekalert-adna-clean-room',
    title: 'aDNA Clean Room',
    url: 'https://www.eurekalert.org/multimedia/895013',
    publisher: 'Max Planck Institute of Geoanthropology / EurekAlert',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Licensed reference photograph by Vanessa Villalba; use permitted with appropriate credit; source photograph not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.alpaslan-roodenberg-2021-ethics',
    title: 'Ethics of DNA research on human remains: five globally applicable guidelines',
    url: 'https://www.nature.com/articles/s41586-021-04008-x',
    publisher: 'Nature',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Open-access ethics guidance cited for destructive sampling and stakeholder responsibilities',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.mylopotamitaki-2024-ranis',
    title: 'Homo sapiens reached the higher latitudes of Europe by 45,000 years ago',
    url: 'https://www.nature.com/articles/s41586-023-06923-7',
    publisher: 'Nature',
    accessedOn: '2026-07-26',
    licenseOrUse: 'CC BY 4.0 primary study cited for Ranis evidence and coordinates; third-party photographs not redistributed',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.trinkaus-2007-oase-coordinates',
    title: 'Peștera cu Oase 2 and the cranial morphology of early modern Europeans',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC1783092/',
    publisher: 'Proceedings of the National Academy of Sciences',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Open primary research cited for the cave coordinate and chronology',
    reviewStatus: 'reviewed',
  },
  {
    id: 'source.humans.morley-2019-denisova-coordinate',
    title: 'Hominin and animal activities in the microstratigraphic record from Denisova Cave',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6763451/',
    publisher: 'Scientific Reports',
    accessedOn: '2026-07-26',
    licenseOrUse: 'Open primary research cited for the Denisova Cave coordinate and preservation context',
    reviewStatus: 'reviewed',
  },
];

export const migrationsAncientDnaClaims: Claim[] = [
  {
    id: 'claim.humans.dispersals-repeated',
    statement: 'Homo sapiens groups moved beyond Africa more than once, and some early branches contributed little ancestry to later sampled populations.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.humans.hallett-2025-niche', 'source.humans.sumer-2024-admixture'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.humans.major-expansion-fifty-ka',
    statement: 'Most ancestry of living people outside Africa traces to an expansion that began roughly 50,000 years ago.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.humans.hallett-2025-niche', 'source.humans.sumer-2024-admixture'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.humans.other-populations-eurasia',
    statement: 'Neanderthal and Denisovan populations already lived in parts of Eurasia when dispersing Homo sapiens groups arrived.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.humans.green-2010-neanderthal', 'source.humans.reich-2010-denisova'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.humans.shared-neanderthal-encounter',
    statement: 'A Neanderthal interbreeding event shared by sequenced non-African populations occurred about 45,000–49,000 years ago.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.humans.sumer-2024-admixture', 'source.humans.green-2010-neanderthal'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.humans.long-segments-recent',
    statement: 'Long inherited DNA segments point to a more recent ancestor because recombination breaks segments into smaller pieces over generations.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.humans.fu-2015-oase', 'source.humans.sumer-2024-admixture'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.humans.oase-recent-ancestor',
    statement: 'Oase 1 had a Neanderthal ancestor about four to six generations earlier.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.humans.fu-2015-oase'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.humans.additional-encounters',
    statement: 'Some early Homo sapiens people show evidence of additional, more recent Neanderthal ancestors.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.humans.fu-2015-oase', 'source.humans.sumer-2024-admixture'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.humans.ancestry-not-purity',
    statement: 'Later population movements, including movements back into Africa, make a simple pure Africa/non-Africa ancestry divide inaccurate.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.humans.green-2010-neanderthal', 'source.humans.chen-2020-backmigration'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.humans.denisovans-known-genetically',
    statement: 'Denisovans were first recognized as a distinct ancient human population through DNA from a very small fossil sample.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.humans.reich-2010-denisova', 'source.humans.denisova-project'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.humans.denisovan-contacts-multiple',
    statement: 'Genomes support more than one encounter with genetically distinct Denisovan-related populations.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.humans.jacobs-2019-denisovan'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.humans.adna-preservation-biased',
    statement: 'Ancient DNA survives unevenly, so the places with readable genomes are a biased sample of where people lived.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.humans.orlando-2021-adna', 'source.humans.morley-2019-denisova-coordinate'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.humans.adna-inference-limited',
    statement: 'Ancient DNA can estimate biological relatedness and mixture but cannot recover language, self-identity, motives, or a complete travel route.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.humans.orlando-2021-adna', 'source.humans.alpaslan-roodenberg-2021-ethics'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.humans.adna-ethical',
    statement: 'Sampling human remains can be destructive and requires legal, scientific, and stakeholder accountability.',
    kind: 'observation',
    certainty: 'high',
    sourceIds: ['source.humans.orlando-2021-adna', 'source.humans.alpaslan-roodenberg-2021-ethics'],
    reviewStatus: 'reviewed',
  },
  {
    id: 'claim.humans.map-is-sample',
    statement: 'Mapped ancient-genome sites show where a few remains survived and were studied, not every route or place where people lived.',
    kind: 'interpretation',
    certainty: 'high',
    sourceIds: ['source.humans.sumer-2024-admixture', 'source.humans.orlando-2021-adna'],
    reviewStatus: 'reviewed',
  },
];

export const migrationsAncientDnaMedia: MediaAsset[] = [
  {
    id: 'media.humans.migrations-hero-map',
    locator: mediaLocator('media.humans.migrations-hero-map'),
    alt: 'Wide illustrated map from Europe to East Asia with six ancient-genome evidence sites. Ranis, Zlatý kůň, Oase, and Bacho Kiro cluster in Europe; Ust’-Ishim lies far to the east in Siberia; Tianyuan lies farther east near northern China. Each site has a date between about 50,000 and 37,000 years before present.',
    depictionMode: 'map',
    depictionLabel: 'Evidence-site map · locations and dates adapted from Sümer et al. 2024',
    rightsLabel: 'Chronos raster image edit · map data from Sümer et al., CC BY 4.0 · specimen photographs excluded',
    sourceIds: ['source.humans.sumer-2024-admixture'],
    visualBriefRef: 'docs/research/migrations-and-ancient-dna-map.md',
    reviewStatus: 'approved',
  },
  {
    id: 'media.humans.adna-clean-room',
    locator: mediaLocator('media.humans.adna-clean-room'),
    alt: 'Graphical illustration of an ancient-DNA clean room. A researcher in a white hooded clean suit, protective glasses, and gloves works behind a clear clean-bench sash. A stand of pipettes, green and pink tube racks, small containers, and laboratory equipment surround the work area.',
    depictionMode: 'evidence-based-reconstruction',
    depictionLabel: 'Graphical image edit · ancient-DNA clean-room procedure',
    rightsLabel: 'Chronos raster image edit · reference photograph Vanessa Villalba / MPI · used with appropriate credit',
    sourceIds: ['source.humans.eurekalert-adna-clean-room', 'source.humans.orlando-2021-adna'],
    visualBriefRef: 'docs/research/migrations-and-ancient-dna-media.md#ancient-dna-clean-room-raster-image-edit',
    reviewStatus: 'approved',
  },
  {
    id: 'media.humans.inherited-segments-diagram',
    locator: mediaLocator('media.humans.inherited-segments-diagram'),
    alt: 'Two textured chromosome-like bands compare inherited ancestry. The upper band contains one long rust-colored segment within a blue-teal genome, while the lower band contains several shorter separated rust-colored segments.',
    depictionMode: 'diagram',
    depictionLabel: 'Explanatory diagram · segment lengths simplified',
    rightsLabel: 'Chronos image edit · reference: Moran et al. 2021, CC BY 4.0',
    sourceIds: ['source.humans.fu-2015-oase', 'source.humans.sumer-2024-admixture'],
    visualBriefRef: 'docs/research/migrations-and-ancient-dna.md#inherited-segments-evidence-diagram',
    reviewStatus: 'approved',
  },
  {
    id: 'media.humans.neanderthals-card',
    locator: mediaLocator('media.humans.neanderthals-card'),
    alt: 'Evidence-based reconstruction portrait of a calm Neanderthal adult with a broad middle face, large nose, strong brow ridge, long low head, and robust neck against a dark stone background.',
    depictionMode: 'evidence-based-reconstruction',
    depictionLabel: 'Evidence-based reconstruction · not a known individual',
    rightsLabel: 'Chronos-original generated artwork · 2026',
    sourceIds: ['source.humans.green-2010-neanderthal', 'source.humans.sumer-2024-admixture'],
    visualBriefRef: 'docs/research/migrations-and-ancient-dna.md#knowledge-card-plan',
    reviewStatus: 'approved',
  },
];

export const migrationsAncientDnaPrompts: UnderstandingPrompt[] = [
  {
    id: 'prompt.humans.long-segments-inference',
    lessonId: 'lesson.humans.migrations-and-interbreeding',
    kind: 'supported-selection',
    question: 'Oase 1 carried unusually long stretches of Neanderthal DNA. Which conclusion is best supported?',
    explanation: 'Long pieces have had fewer generations to be broken apart. They support a recent Neanderthal ancestor. They cannot tell us Oase 1’s language, identity, or the history of every group.',
    required: true,
    options: [
      { id: 'option.humans.recent-neanderthal-ancestor', label: 'One of Oase 1’s recent ancestors was Neanderthal.' },
      { id: 'option.humans.oase-was-neanderthal', label: 'Oase 1 was a Neanderthal rather than Homo sapiens.' },
      { id: 'option.humans.dna-reveals-language', label: 'The DNA tells us which language Oase 1 spoke.' },
      { id: 'option.humans.all-encounters-same', label: 'Every Homo sapiens group had the same encounter at the same time.' },
    ],
  },
  {
    id: 'prompt.humans.adna-evidence-and-limit',
    lessonId: 'lesson.humans.migrations-and-interbreeding',
    kind: 'concise-explanation',
    question: 'Use one example to explain what ancient DNA reveals about an encounter. Then name one thing DNA cannot tell us by itself.',
    explanation: 'A strong answer can use Oase 1, the shared Neanderthal encounter, or Denisovan-related ancestry. Limits include exact routes, language, culture, motives, identity, and people whose DNA has not survived.',
    required: true,
    minimumResponseLength: 30,
  },
];

export const migrationsAncientDnaLesson: Lesson = {
  id: 'lesson.humans.migrations-and-interbreeding',
  legacyAliases: [],
  status: 'published',
  title: 'Migrations, Encounters, and Ancient DNA',
  masthead: 'Leaving was not one journey',
  place: 'Africa and Eurasia',
  chronology: {
    startYear: -70000,
    endYear: -40000,
    display: 'c. 70,000–40,000 years ago',
    approximate: true,
  },
  significance: 'People moved beyond Africa in more than one wave. When some groups met Neanderthals and Denisovans, those meetings became part of human ancestry.',
  heroMediaId: 'media.humans.migrations-hero-map',
  heroLabel: 'Ancient-genome evidence sites',
  heroCaption: 'These six sites mark where remains survived and produced genome-wide data. They are evidence samples, not a route or a complete map of where people lived.',
  sectionIdsRequired: [
    'section.humans.movement-not-march',
    'section.humans.other-humans-eurasia',
    'section.humans.dna-keeps-traces',
    'section.humans.shared-and-local-encounters',
    'section.humans.denisovan-clues',
    'section.humans.dna-limits',
  ],
  sections: [
    {
      id: 'section.humans.movement-not-march',
      heading: 'Leaving was not one journey',
      purpose: 'Replace the single-migration story with a branching history',
      modules: [
        {
          id: 'module.humans.movement-opening',
          type: 'prose',
          body: `The last lesson followed our species’ deep roots across Africa. Now follow some of those connected groups beyond the continent.

This was not one crowd leaving on one day. Homo sapiens groups moved at different times. Some early branches seem to have ended or mixed into other groups. A later expansion, beginning roughly 50,000 years ago, left most of the ancestry carried by people outside Africa today.

Movement did not lead into an empty world.`,
          claimIds: ['claim.humans.dispersals-repeated', 'claim.humans.major-expansion-fifty-ka'],
          sourceIds: ['source.humans.hallett-2025-niche', 'source.humans.sumer-2024-admixture'],
        },
        {
          id: 'module.humans.branches-not-ladder',
          type: 'knowledge',
          eyebrow: 'A branching story',
          title: 'Several movements, many outcomes',
          body: 'The evidence works better as a family tree with crossing branches than as a line of people marching toward the present.',
          items: [
            { label: 'Earlier movements', detail: 'Some Homo sapiens groups reached places beyond Africa earlier, but they left little known ancestry in later sampled people.' },
            { label: 'A major expansion', detail: 'Many living people outside Africa trace most of their ancestry to groups that expanded about 50,000 years ago.' },
            { label: 'No finish line', detail: 'A branch that left fewer descendants was not less human or less successful in its own time.' },
          ],
          claimIds: ['claim.humans.dispersals-repeated', 'claim.humans.major-expansion-fifty-ka'],
          sourceIds: ['source.humans.hallett-2025-niche', 'source.humans.sumer-2024-admixture'],
        },
      ],
    },
    {
      id: 'section.humans.other-humans-eurasia',
      heading: 'A world with other humans',
      purpose: 'Locate the populations and show that the map is a sample, not a route',
      modules: [
        {
          id: 'module.humans.other-populations',
          type: 'prose',
          body: `Neanderthals already lived across much of western Eurasia. Farther east, groups researchers call Denisovans also lived in Asia. They were related human populations, not lower steps on a ladder.

The known evidence does not map every territory or path Homo sapiens took. It comes from a few places where remains survived and scientists recovered useful DNA. Cool caves and cold ground preserve DNA better than hot, wet places. That makes the known sample uneven.`,
          claimIds: ['claim.humans.other-populations-eurasia', 'claim.humans.adna-preservation-biased', 'claim.humans.map-is-sample'],
          sourceIds: ['source.humans.green-2010-neanderthal', 'source.humans.reich-2010-denisova', 'source.humans.orlando-2021-adna'],
        },
      ],
    },
    {
      id: 'section.humans.dna-keeps-traces',
      heading: 'An encounter written in long pieces',
      purpose: 'Use segment length to make one ancient encounter concrete',
      modules: [
        {
          id: 'module.humans.inherited-segments',
          type: 'evidence',
          title: 'Long pieces point to a recent ancestor',
          artifactLabel: 'Explanatory diagram · inherited DNA',
          body: `The top row shows one long inherited segment. The lower row shows how inherited material can be split into shorter pieces after many generations.

Oase 1 lived in what is now Romania about 40,000 years ago. Their genome held unusually long Neanderthal segments. The best explanation is a Neanderthal ancestor only four to six generations earlier. DNA cannot tell us what those people called each other or how they understood their family.`,
          mediaId: 'media.humans.inherited-segments-diagram',
          claimIds: ['claim.humans.long-segments-recent', 'claim.humans.oase-recent-ancestor', 'claim.humans.adna-inference-limited'],
          sourceIds: ['source.humans.fu-2015-oase', 'source.humans.sumer-2024-admixture'],
        },
        {
          id: 'module.humans.oase-lineage',
          type: 'prose',
          body: `Oase 1’s lineage seems to have contributed little ancestry to later Europeans. That does not make the person unimportant. Their DNA still records a meeting that would otherwise be almost invisible.

One person also cannot stand for every group. Other genomes tell a wider story.`,
          claimIds: ['claim.humans.oase-recent-ancestor', 'claim.humans.additional-encounters'],
          sourceIds: ['source.humans.fu-2015-oase', 'source.humans.sumer-2024-admixture'],
        },
        {
          id: 'module.humans.prompt-long-segments',
          type: 'prompt',
          promptId: 'prompt.humans.long-segments-inference',
          claimIds: [],
          sourceIds: [],
        },
      ],
    },
    {
      id: 'section.humans.shared-and-local-encounters',
      heading: 'One shared encounter—and others',
      purpose: 'Distinguish a shared ancestry event from additional meetings',
      modules: [
        {
          id: 'module.humans.shared-and-local',
          type: 'knowledge',
          eyebrow: 'What many genomes share',
          title: 'The meetings did not all happen at once',
          body: 'Researchers compare both how much Neanderthal DNA remains and how long its pieces are.',
          items: [
            { label: 'A shared event', detail: 'Genomes point to one period of interbreeding about 45,000–49,000 years ago in the ancestry shared by sampled people outside Africa.' },
            { label: 'Other encounters', detail: 'Oase 1 and several people from Bacho Kiro had additional Neanderthal ancestors much closer to their own lifetimes.' },
            { label: 'No pure groups', detail: 'People kept moving and mixing. Later movement back into Africa also carried some Neanderthal-related ancestry with it.' },
          ],
          claimIds: ['claim.humans.shared-neanderthal-encounter', 'claim.humans.additional-encounters', 'claim.humans.ancestry-not-purity'],
          sourceIds: ['source.humans.sumer-2024-admixture', 'source.humans.fu-2015-oase', 'source.humans.chen-2020-backmigration'],
        },
        {
          id: 'module.humans.ancestry-is-not-identity',
          type: 'prose',
          body: `A small ancestry percentage is not a purity score. It does not make someone “part Neanderthal” in culture or identity. It describes parts of a genome, compared with a small set of ancient reference genomes.

Ancestry is evidence about biological relationships. It is not a ranking of people.`,
          claimIds: ['claim.humans.ancestry-not-purity', 'claim.humans.adna-inference-limited'],
          sourceIds: ['source.humans.green-2010-neanderthal', 'source.humans.chen-2020-backmigration', 'source.humans.alpaslan-roodenberg-2021-ethics'],
        },
      ],
    },
    {
      id: 'section.humans.denisovan-clues',
      heading: 'A people first recognized through DNA',
      purpose: 'Use Denisovan evidence to widen the encounter story while preserving uncertainty',
      modules: [
        {
          id: 'module.humans.denisovan-discovery',
          type: 'prose',
          body: `In 2008, researchers found a tiny finger-bone fragment in Denisova Cave in Siberia. Its DNA did not match Homo sapiens or Neanderthals. It revealed another related human population, now called Denisovans after the cave.

The name is modern. We do not know what these people called themselves. For years, Denisovans were known mostly from teeth, small bone fragments, and DNA. In 2025, proteins and mitochondrial DNA linked the nearly complete Harbin cranium to a Denisovan population, giving researchers their first strong view of one Denisovan skull. Even so, one skull cannot show what all Denisovans looked like, and details such as skin and hair remain uncertain.`,
          claimIds: ['claim.humans.denisovans-known-genetically', 'claim.humans.adna-inference-limited'],
          sourceIds: [
            'source.humans.reich-2010-denisova',
            'source.humans.denisova-project',
            'source.humans.zhang-2025-harbin-mtdna',
            'source.humans.welker-2025-harbin-proteome',
          ],
        },
        {
          id: 'module.humans.denisovan-branches',
          type: 'knowledge',
          eyebrow: 'Clues far beyond one cave',
          title: 'More than one Denisovan-related population',
          body: 'The cave gave researchers a name and a reference genome. Other genomes show that the story stretched much farther across Asia.',
          items: [
            { label: 'Several contacts', detail: 'Genetic studies find signs of more than one encounter with Denisovan-related populations.' },
            { label: 'Different branches', detail: 'Some Denisovan-related ancestry in living Papuan people comes from groups that were already quite different from one another.' },
            { label: 'No territory to color in', detail: 'DNA can show relationships. It cannot draw one exact Denisovan homeland across the map.' },
          ],
          claimIds: ['claim.humans.denisovan-contacts-multiple', 'claim.humans.adna-inference-limited'],
          sourceIds: ['source.humans.jacobs-2019-denisovan', 'source.humans.reich-2010-denisova'],
        },
      ],
    },
    {
      id: 'section.humans.dna-limits',
      heading: 'Powerful evidence, narrow answers',
      purpose: 'End with preservation, ethics, and the limits of genetic inference',
      modules: [
        {
          id: 'module.humans.dna-limits',
          type: 'prose',
          body: `Ancient DNA can reveal biological relatives and show that populations had children together. It can sometimes estimate when an encounter happened.

But most ancient people left no readable DNA. Heat, water, time, and microbes destroy it. Sampling can also damage human remains. Researchers must work with care, follow local laws, and involve people and communities connected to the remains.

DNA cannot tell us a person’s language, feelings, name, or identity. It cannot map every journey. Used carefully, it adds one strong line of evidence beside fossils and archaeology—not a complete story by itself.

Some groups kept moving east. Reaching Sahul would require another kind of movement: crossing open water.`,
          claimIds: ['claim.humans.adna-preservation-biased', 'claim.humans.adna-inference-limited', 'claim.humans.adna-ethical'],
          sourceIds: ['source.humans.orlando-2021-adna', 'source.humans.alpaslan-roodenberg-2021-ethics'],
        },
        {
          id: 'module.humans.adna-clean-room',
          type: 'evidence',
          title: 'Protecting a fragile signal',
          artifactLabel: 'Research process · ancient-DNA clean room',
          body: 'Modern DNA from a researcher can overwhelm the small amount that survives in an ancient sample. Clean suits, gloves, filtered workspaces, sterilized tools, and careful pipetting help reduce contamination. The illustration preserves the equipment and working arrangement in the source photograph; it does not identify the sample being handled.',
          mediaId: 'media.humans.adna-clean-room',
          claimIds: ['claim.humans.adna-preservation-biased', 'claim.humans.adna-inference-limited'],
          sourceIds: ['source.humans.eurekalert-adna-clean-room', 'source.humans.orlando-2021-adna'],
        },
        {
          id: 'module.humans.prompt-adna-limit',
          type: 'prompt',
          promptId: 'prompt.humans.adna-evidence-and-limit',
          claimIds: [],
          sourceIds: [],
        },
      ],
    },
  ],
  claimIds: migrationsAncientDnaClaims.map((claim) => claim.id),
  sourceIds: migrationsAncientDnaSources.map((source) => source.id),
  mediaIds: [
    'media.humans.migrations-hero-map',
    'media.humans.adna-clean-room',
    'media.humans.inherited-segments-diagram',
    'media.humans.neanderthals-card',
  ],
  promptIds: ['prompt.humans.long-segments-inference', 'prompt.humans.adna-evidence-and-limit'],
};

export const migrationsAncientDnaCards: KnowledgeCard[] = [
  {
    id: 'card.people.neanderthals',
    title: 'Neanderthals',
    category: 'people',
    cardClass: 'witness',
    date: { startYear: -400000, endYear: -40000, display: 'c. 400,000–40,000 years ago', approximate: true },
    place: 'Western Eurasia and Central Asia',
    significance: 'Neanderthals were a related human population whose encounters with Homo sapiens still survive in many genomes.',
    revealTitle: 'An encounter that left descendants',
    revealBody: 'You used inherited DNA segments to connect one close family history with a much wider pattern of meetings between human populations.',
    depictionLabel: 'Evidence-based reconstruction · not a known individual',
    facts: [
      'Neanderthals lived across much of western Eurasia',
      'They were related humans, not a lower step on a ladder',
      'One shared encounter dates to about 45,000–49,000 years ago',
      'Oase 1 had a Neanderthal ancestor about four to six generations earlier',
    ],
    lessonIds: ['lesson.humans.migrations-and-interbreeding'],
    sourceIds: ['source.humans.green-2010-neanderthal', 'source.humans.fu-2015-oase', 'source.humans.sumer-2024-admixture'],
    mediaId: 'media.humans.neanderthals-card',
    unlockLessonId: 'lesson.humans.migrations-and-interbreeding',
  },
];

export const migrationsAncientDnaContent: AuthoredContentModule = {
  sources: migrationsAncientDnaSources,
  claims: migrationsAncientDnaClaims,
  media: migrationsAncientDnaMedia,
  prompts: migrationsAncientDnaPrompts,
  lessons: [migrationsAncientDnaLesson],
  cards: migrationsAncientDnaCards,
};
