import type { Claim, Lesson, Source, UnderstandingPrompt } from '../../src/domains/contracts';
import type { AuthoredContentModule } from '../assemble';

export const pyramidsPowerStateLaborSources: Source[] = [
  {
    id: 'source.pyramids.ifao-merer',
    title: 'Les Papyrus de la Mer Rouge I: Le Journal de Merer',
    url: 'https://www.ifao.egnet.net/uploads/publications/divers/MIFAO136_ann_01.pdf',
    publisher: 'Institut français d’archéologie orientale',
    accessedOn: '2026-08-31',
    licenseOrUse: 'Official excavation publication cited for research; publication photography is not redistributed',
    reviewStatus: 'review-required',
  },
  {
    id: 'source.pyramids.aera-lost-city',
    title: 'The Lost City of the Pyramid Builders',
    url: 'https://aeraweb.org/projects/lost-city/',
    publisher: 'Ancient Egypt Research Associates',
    accessedOn: '2026-08-31',
    licenseOrUse: 'Excavation-project synthesis cited for research; project images are not redistributed',
    reviewStatus: 'review-required',
  },
  {
    id: 'source.pyramids.aera-gangs',
    title: 'Of Gangs and Graffiti: How Ancient Egyptians Organized Their Labor Force',
    url: 'https://www.aeraweb.org/wp-content/uploads/2009/09/aeragram7_1_2004.pdf',
    publisher: 'Ancient Egypt Research Associates / AERAGRAM',
    accessedOn: '2026-08-31',
    licenseOrUse: 'Excavation-project article cited for research; figures require separate rights review',
    reviewStatus: 'review-required',
  },
  {
    id: 'source.pyramids.aera-food',
    title: 'Feeding Pyramid Workers',
    url: 'https://aeraweb.org/feeding-pyramid-workers/',
    publisher: 'Ancient Egypt Research Associates',
    accessedOn: '2026-08-31',
    licenseOrUse: 'Archaeological and experimental synthesis cited for research; images are not redistributed',
    reviewStatus: 'review-required',
  },
  {
    id: 'source.pyramids.egypt-workers-town',
    title: 'Workers’ Town and Cemetery',
    url: 'https://egymonuments.gov.eg/en/monuments/workers-town-and-cemetery',
    publisher: 'Egyptian Ministry of Tourism and Antiquities',
    accessedOn: '2026-08-31',
    licenseOrUse: 'Official site record cited for research; ministry media are not redistributed',
    reviewStatus: 'review-required',
  },
  {
    id: 'source.pyramids.egypt-great-pyramid',
    title: 'The Great Pyramid',
    url: 'https://egymonuments.gov.eg/en/monuments/the-great-pyramid/',
    publisher: 'Egyptian Ministry of Tourism and Antiquities',
    accessedOn: '2026-08-31',
    licenseOrUse: 'Official monument record cited for research; ministry media are not redistributed',
    reviewStatus: 'review-required',
  },
  {
    id: 'source.pyramids.egypt-djoser',
    title: 'The Step Pyramid Complex of Djoser',
    url: 'https://egymonuments.gov.eg/en/monuments/the-step-pyramid-complex-of-djoser',
    publisher: 'Egyptian Ministry of Tourism and Antiquities',
    accessedOn: '2026-08-31',
    licenseOrUse: 'Official monument record cited for research; ministry media are not redistributed',
    reviewStatus: 'review-required',
  },
  {
    id: 'source.pyramids.harvard-giza',
    title: 'Digital Giza: Introduction to Giza',
    url: 'https://giza.fas.harvard.edu/gizaintro/',
    publisher: 'Harvard University',
    accessedOn: '2026-08-31',
    licenseOrUse: 'University archaeological archive cited for research; individual media require item-level rights review',
    reviewStatus: 'review-required',
  },
  {
    id: 'source.pyramids.cambridge-location',
    title: 'Location of the Old Kingdom Pyramids in Egypt',
    url: 'https://doi.org/10.1017/S0959774305000090',
    publisher: 'Cambridge Archaeological Journal',
    accessedOn: '2026-08-31',
    licenseOrUse: 'Peer-reviewed specialist study cited for research; figures are not redistributed',
    reviewStatus: 'review-required',
  },
  {
    id: 'source.pyramids.ucl-construction',
    title: 'How a pyramid was built',
    url: 'https://www.ucl.ac.uk/museums-static/digitalegypt/pyramids/how.html',
    publisher: 'UCL Digital Egypt for Universities',
    accessedOn: '2026-08-31',
    licenseOrUse: 'University Egyptology reference cited for research; figures are not redistributed',
    reviewStatus: 'review-required',
  },
  {
    id: 'source.pyramids.uee-slavery',
    title: 'Slavery and Servitude',
    url: 'https://escholarship.org/content/qt8mx2073f/qt8mx2073f.pdf',
    publisher: 'UCLA Encyclopedia of Egyptology',
    accessedOn: '2026-08-31',
    licenseOrUse: 'Open-access specialist reference cited for research; figures are not redistributed',
    reviewStatus: 'review-required',
  },
  {
    id: 'source.pyramids.warden-taxation',
    title: 'Centralized Taxation during the Old Kingdom',
    url: 'https://gizamedia.rc.fas.harvard.edu/documents/warden_hes_1_2015.pdf',
    publisher: 'Harvard Egyptological Studies',
    accessedOn: '2026-08-31',
    licenseOrUse: 'Specialist chapter cited for research; figures are not redistributed',
    reviewStatus: 'review-required',
  },
  {
    id: 'source.pyramids.met-old-kingdom',
    title: 'When the Pyramids Were Built: Egyptian Art of the Old Kingdom',
    url: 'https://www.metmuseum.org/met-publications/when-the-pyramids-were-built-egyptian-art-of-the-old-kingdom',
    publisher: 'The Metropolitan Museum of Art',
    accessedOn: '2026-08-31',
    licenseOrUse: 'Museum scholarly publication cited for research; object images require item-level rights review',
    reviewStatus: 'review-required',
  },
];

export const pyramidsPowerStateLaborClaims: Claim[] = [
  {
    id: 'claim.pyramids.development',
    statement: 'Monumental royal tombs developed through generations of experiment, from mastabas and Djoser’s stepped complex to later smooth-sided pyramids and Giza.',
    kind: 'interpretation', certainty: 'high',
    sourceIds: ['source.pyramids.egypt-djoser', 'source.pyramids.met-old-kingdom'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.pyramids.royal-complex',
    statement: 'A pyramid belonged to a larger royal funerary complex of temples, causeways, burials, and ritual spaces.',
    kind: 'observation', certainty: 'high',
    sourceIds: ['source.pyramids.egypt-great-pyramid', 'source.pyramids.harvard-giza', 'source.pyramids.egypt-djoser'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.pyramids.great-scale',
    statement: 'Khufu’s Great Pyramid originally stood about 146.5 meters high; most core stone was local limestone, while fine Tura limestone was shipped for casing.',
    kind: 'observation', certainty: 'high',
    sourceIds: ['source.pyramids.egypt-great-pyramid', 'source.pyramids.harvard-giza', 'source.pyramids.ifao-merer'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.pyramids.merer-log',
    statement: 'Merer’s surviving log records an inspector and crew moving fine limestone from Tura to Khufu’s pyramid project by water near the end of the king’s reign.',
    kind: 'observation', certainty: 'high',
    sourceIds: ['source.pyramids.ifao-merer', 'source.pyramids.aera-lost-city'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.pyramids.records-limited',
    statement: 'Merer’s log supports claims about scheduling, supervision, transport, and provisioning but does not preserve the exact ramp system, every worker’s status, or the whole construction plan.',
    kind: 'interpretation', certainty: 'high',
    sourceIds: ['source.pyramids.ifao-merer', 'source.pyramids.ucl-construction'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.pyramids.worker-settlement',
    statement: 'Heit el-Ghurab preserves a purpose-built settlement with galleries, houses, workshops, storage, food production, and administration tied to the Giza pyramid projects.',
    kind: 'observation', certainty: 'high',
    sourceIds: ['source.pyramids.aera-lost-city', 'source.pyramids.egypt-workers-town'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.pyramids.provisioning',
    statement: 'Bread molds, storage spaces, animal bones, and other remains show that feeding and equipping the workforce was itself a large organized job.',
    kind: 'interpretation', certainty: 'high',
    sourceIds: ['source.pyramids.aera-food', 'source.pyramids.aera-lost-city', 'source.pyramids.egypt-workers-town'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.pyramids.crew-organization',
    statement: 'Builders’ marks and administrative records show crews divided into named, supervised units that could be combined for large tasks.',
    kind: 'interpretation', certainty: 'moderate',
    sourceIds: ['source.pyramids.aera-gangs', 'source.pyramids.ifao-merer'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.pyramids.labor-status',
    statement: 'The workforce likely combined skilled specialists, administrators, sailors, support workers, and people performing forms of obligatory or rotational service; the exact mix cannot be recovered person by person.',
    kind: 'interpretation', certainty: 'moderate',
    sourceIds: ['source.pyramids.uee-slavery', 'source.pyramids.warden-taxation', 'source.pyramids.aera-lost-city', 'source.pyramids.aera-gangs'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.pyramids.no-simple-slave-story',
    statement: 'Giza evidence does not support a single faceless chattel-slave gang as the explanation for pyramid building, but provisions and honored burials do not prove that all workers could freely refuse state service.',
    kind: 'interpretation', certainty: 'high',
    sourceIds: ['source.pyramids.uee-slavery', 'source.pyramids.egypt-workers-town', 'source.pyramids.aera-food', 'source.pyramids.warden-taxation'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.pyramids.hard-labor',
    statement: 'Skeletal injuries and the scale of quarrying, hauling, construction, cooking, and tool production show that pyramid work could be physically demanding and dangerous.',
    kind: 'interpretation', certainty: 'moderate',
    sourceIds: ['source.pyramids.egypt-workers-town', 'source.pyramids.aera-food'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.pyramids.construction-uncertain',
    statement: 'Archaeology supports quarrying, sledges, waterways, inclined surfaces, levers, measurement, and skilled stonework, while the exact arrangement used at each stage remains uncertain.',
    kind: 'interpretation', certainty: 'moderate',
    sourceIds: ['source.pyramids.ucl-construction', 'source.pyramids.egypt-great-pyramid', 'source.pyramids.ifao-merer', 'source.pyramids.aera-gangs'],
    reviewStatus: 'editorial-review-required',
  },
  {
    id: 'claim.pyramids.power-visible',
    statement: 'Pyramid building made royal power visible by concentrating resources and labor around a king’s funerary future, while the surviving record favors rulers and institutions over ordinary lives.',
    kind: 'interpretation', certainty: 'high',
    sourceIds: ['source.pyramids.harvard-giza', 'source.pyramids.cambridge-location', 'source.pyramids.warden-taxation', 'source.pyramids.aera-lost-city'],
    reviewStatus: 'editorial-review-required',
  },
];

export const pyramidsPowerStateLaborPrompts: UnderstandingPrompt[] = [
  {
    id: 'prompt.pyramids.merer-and-settlement',
    lessonId: 'lesson.egypt.pyramids-and-state-labor',
    kind: 'supported-selection',
    question: 'Which conclusion is best supported when Merer’s log and the workers’ settlement are considered together?',
    explanation: 'Merer’s log records supervised stone transport. The settlement preserves places for storage, food production, workshops, housing, and administration. Comparing their different evidence reveals a connected building system.',
    required: true,
    options: [
      { id: 'option.pyramids.coordinated-system', label: 'The project connected scheduled transport with places that supplied, housed, and managed workers.' },
      { id: 'option.pyramids.swapped-evidence', label: 'Merer’s log is strongest for worker housing, while the settlement records the crew’s daily boat routes.' },
      { id: 'option.pyramids.swapped-materials', label: 'The settlement traces stone from Tura, while Merer’s log identifies what workers ate at Giza.' },
      { id: 'option.pyramids.royal-symbolism', label: 'Both sources mainly explain what the pyramid symbolized in royal funerary belief.' },
    ],
  },
  {
    id: 'prompt.pyramids.evidence-and-limit',
    lessonId: 'lesson.egypt.pyramids-and-state-labor',
    kind: 'concise-explanation',
    question: 'Choose Merer’s log or the workers’ settlement. How does it show the state turning a plan into repeated work, and what can it not prove by itself?',
    explanation: 'A strong answer connects the evidence to transport, provisioning, or administration, then names a limit such as the entire workforce, individual freedom, or the full construction method.',
    required: true,
    minimumResponseLength: 30,
  },
];

export const pyramidsPowerStateLaborLesson: Lesson = {
  id: 'lesson.egypt.pyramids-and-state-labor',
  legacyAliases: ['imhotep', 'pyramids'],
  status: 'draft',
  title: 'Pyramids, Power, and State Labor',
  masthead: 'c. 2700–2500 BCE',
  place: 'Saqqara and Giza, near ancient Memphis, Egypt',
  chronology: { startYear: -2700, endYear: -2500, display: 'c. 2700–2500 BCE', approximate: true },
  significance: 'Pyramids made royal power visible because building them required a state to coordinate knowledge, transport, supplies, and many kinds of labor.',
  sectionIdsRequired: [
    'section.pyramids.development',
    'section.pyramids.royal-complex',
    'section.pyramids.merer-logbook',
    'section.pyramids.workforce',
    'section.pyramids.provisioning',
    'section.pyramids.construction',
    'section.pyramids.world-check',
  ],
  sections: [
    {
      id: 'section.pyramids.development',
      heading: 'From mastabas to pyramids',
      purpose: 'Establish pyramids as the result of cumulative experiments rather than a sudden invention',
      modules: [
        {
          id: 'module.pyramids.opening',
          type: 'prose',
          body: 'Imagine arriving at Giza when Khufu’s pyramid was new. Its fine outer casing would have made the sides appear smoother and brighter than the exposed core we see today. At about 146.5 meters high, it concentrated an astonishing amount of stone in one place. But the first question is not “How could anyone do this?” It is “What had to be organized before they could?”\n\nEgyptian builders did not leap from small tombs to the Great Pyramid in one inspired moment. Across generations, royal burial places changed from low rectangular mastabas into stacked stone forms, then into smooth-sided pyramids. Djoser’s complex at Saqqara, built more than a century before Khufu’s, turned familiar shapes into a stepped stone monument surrounded by courts and ritual buildings. Later projects tested new angles, internal spaces, quarries, and ways of moving stone. Some plans changed while they were being built.\n\nImhotep is named in later tradition as Djoser’s architect and was celebrated long after his lifetime. That does not make the pyramid one person’s invention. Surveyors, stoneworkers, haulers, toolmakers, scribes, boat crews, food producers, and generations of earlier builders all contributed knowledge.',
          claimIds: ['claim.pyramids.development', 'claim.pyramids.great-scale'],
          sourceIds: ['source.pyramids.egypt-djoser', 'source.pyramids.met-old-kingdom', 'source.pyramids.egypt-great-pyramid'],
        },
        {
          id: 'module.pyramids.experiment-sequence',
          type: 'knowledge',
          eyebrow: 'A building tradition develops',
          title: 'Three changes to notice',
          body: 'The sequence matters more than memorizing every ruler or pyramid.',
          items: [
            { label: 'Mastabas', detail: 'Low rectangular tomb structures already joined burial, status, offerings, and specialized building work.' },
            { label: 'Djoser’s complex', detail: 'A stepped stone pyramid stood inside a much larger designed landscape of courts, walls, and ritual buildings.' },
            { label: 'Later pyramids', detail: 'Builders refined smooth sides, internal spaces, quarrying, transport, and setting out over several royal projects.' },
          ],
          claimIds: ['claim.pyramids.development', 'claim.pyramids.royal-complex'],
          sourceIds: ['source.pyramids.egypt-djoser', 'source.pyramids.met-old-kingdom'],
        },
      ],
    },
    {
      id: 'section.pyramids.royal-complex',
      heading: 'A royal monument and its complex',
      purpose: 'Connect the monument to kingship, ritual, resources, and the wider landscape',
      modules: [
        {
          id: 'module.pyramids.not-alone',
          type: 'prose',
          body: 'A pyramid did not stand alone. Khufu’s monument was part of a complex with a valley temple near the floodplain, a causeway climbing toward the plateau, a temple beside the pyramid, smaller pyramids, boat pits, and cemeteries. These places linked the dead king’s body, offerings, rituals, family, officials, and the landscape of the Nile.\n\nThe monument made a claim that was hard to ignore. A ruler could command valued land, stone, tools, food, transport, skilled knowledge, and human time—and direct them toward his afterlife and continuing royal cult. That visible concentration of resources was political. It did not mean that every official obeyed perfectly or that the state controlled every village in the same way. It did mean that royal institutions could coordinate repeated work on an extraordinary scale.\n\nMost surviving inscriptions and monuments were created for rulers and elites. They tell us much more about how kings wanted power to look than about what an individual farmer, baker, sailor, or hauler thought of the project.',
          claimIds: ['claim.pyramids.royal-complex', 'claim.pyramids.power-visible', 'claim.pyramids.great-scale'],
          sourceIds: ['source.pyramids.harvard-giza', 'source.pyramids.egypt-great-pyramid', 'source.pyramids.cambridge-location', 'source.pyramids.warden-taxation'],
        },
        {
          id: 'module.pyramids.capacity',
          type: 'knowledge',
          eyebrow: 'State capacity in practice',
          title: 'The pyramid depended on connected systems',
          body: 'Historians call this state capacity: a government’s ability to turn decisions into repeated action. Stone was only one part of the project.',
          items: [
            { label: 'Knowledge', detail: 'Surveying, measurement, stoneworking, toolmaking, and planning had to be taught and repeated.' },
            { label: 'Movement', detail: 'Quarries, boats, canals, roads, sledges, and hauling teams connected materials to the plateau.' },
            { label: 'Supplies', detail: 'Food, water, clothing, wood, copper tools, rope, and replacement parts had to arrive again and again.' },
            { label: 'Administration', detail: 'Officials and scribes scheduled teams, recorded deliveries, assigned work, and redistributed provisions.' },
          ],
          claimIds: ['claim.pyramids.power-visible', 'claim.pyramids.great-scale'],
          sourceIds: ['source.pyramids.harvard-giza', 'source.pyramids.cambridge-location', 'source.pyramids.warden-taxation'],
        },
      ],
    },
    {
      id: 'section.pyramids.merer-logbook',
      heading: 'Merer’s logbook',
      purpose: 'Read a primary administrative record for what it reveals and what it leaves unknown',
      modules: [
        {
          id: 'module.pyramids.merer',
          type: 'prose',
          body: 'Around the end of Khufu’s reign, an inspector named Merer kept a daily log on papyrus. Fragments of that log survived at Wadi el-Jarf, a harbor on the Red Sea. The entries are brief and repetitive: the crew spends days at places, moves through waterways, receives provisions, and transports fine limestone from quarries at Tura toward Akhet-Khufu—“Khufu’s Horizon,” the ancient name of the Great Pyramid.\n\nThe log changes the question. It does not describe people mysteriously lifting stones into the sky. It shows an official tracking a crew through a working transport network. Fine casing stone traveled by boat through Nile channels and harbor facilities. Time, destinations, supervision, and supplies mattered enough to record.\n\nThis is unusually direct evidence, but it has a narrow window. Merer records one crew late in the project and one stream of material. His log is not a diary of feelings, a list of every worker, or a manual for raising the pyramid’s core.',
          claimIds: ['claim.pyramids.merer-log', 'claim.pyramids.records-limited', 'claim.pyramids.great-scale'],
          sourceIds: ['source.pyramids.ifao-merer', 'source.pyramids.egypt-great-pyramid', 'source.pyramids.aera-lost-city'],
        },
        {
          id: 'module.pyramids.merer-can-cannot',
          type: 'knowledge',
          eyebrow: 'Read the record carefully',
          title: 'What Merer can—and cannot—tell us',
          body: 'A primary source can be direct without being complete.',
          items: [
            { label: 'It records', detail: 'A supervised crew, repeated journeys, named places, workdays, provisions, and fine limestone moving toward Khufu’s project.' },
            { label: 'It supports', detail: 'A claim that transport and scheduling connected distant quarries to the construction site.' },
            { label: 'It cannot prove', detail: 'The exact ramp arrangement, the size and status of the entire workforce, or how every stone reached its final position.' },
            { label: 'It rarely preserves', detail: 'The voices, choices, fears, family obligations, and disagreements of individual crew members.' },
          ],
          claimIds: ['claim.pyramids.merer-log', 'claim.pyramids.records-limited'],
          sourceIds: ['source.pyramids.ifao-merer', 'source.pyramids.ucl-construction'],
        },
        { id: 'module.pyramids.prompt-system', type: 'prompt', promptId: 'prompt.pyramids.merer-and-settlement', claimIds: [], sourceIds: [] },
      ],
    },
    {
      id: 'section.pyramids.workforce',
      heading: 'Who did the work',
      purpose: 'Replace a simple slave-or-free binary with an evidence-bounded account of a layered workforce',
      modules: [
        {
          id: 'module.pyramids.workers',
          type: 'prose',
          body: 'Popular stories often reduce the workforce to one image: endless rows of enslaved people driven by whips. The evidence from Giza does not support that as a complete explanation. Crew names and builders’ marks show organized work units. A purpose-built settlement preserves galleries, larger houses, workshops, storage, bakeries, administrative spaces, and nearby cemeteries. Some workers had specialized skills. Some people received substantial provisions. Some injured bodies show healing.\n\nBut replacing “all slaves” with “all happy volunteers” creates a new mistake. Ancient Egyptian labor categories do not fit neatly into a modern free-or-enslaved switch. Skilled permanent workers, administrators, sailors, farmers, cooks, craft workers, and people required to take temporary turns of state service may all have taken part. Captives and people bound to households or institutions also existed in Egyptian society. Food and burial show that workers were supported and recognized; they do not tell us whether each person could refuse.\n\nThe exact mix probably changed by task, season, reign, and place. The strongest conclusion is a workforce with many roles organized by royal institutions—not one faceless category.',
          claimIds: ['claim.pyramids.crew-organization', 'claim.pyramids.labor-status', 'claim.pyramids.no-simple-slave-story', 'claim.pyramids.hard-labor'],
          sourceIds: ['source.pyramids.aera-gangs', 'source.pyramids.uee-slavery', 'source.pyramids.warden-taxation', 'source.pyramids.egypt-workers-town', 'source.pyramids.aera-lost-city'],
        },
        {
          id: 'module.pyramids.worker-range',
          type: 'knowledge',
          eyebrow: 'Many kinds of labor',
          title: 'Look beyond the hauling team',
          body: 'The workers who placed stone depended on people whose work happened elsewhere.',
          items: [
            { label: 'Specialists', detail: 'Surveyors, masons, toolmakers, carpenters, and experienced crew leaders carried knowledge across the project.' },
            { label: 'Transport crews', detail: 'Sailors, haulers, quarry workers, and canal crews connected material sources to the building site.' },
            { label: 'Support workers', detail: 'Farmers, herders, bakers, brewers, cooks, potters, rope makers, and carriers kept people and tools working.' },
            { label: 'Administrators', detail: 'Scribes and officials recorded time, teams, deliveries, rations, and institutional decisions.' },
          ],
          claimIds: ['claim.pyramids.labor-status', 'claim.pyramids.provisioning', 'claim.pyramids.crew-organization'],
          sourceIds: ['source.pyramids.aera-lost-city', 'source.pyramids.aera-food', 'source.pyramids.ifao-merer', 'source.pyramids.aera-gangs'],
        },
      ],
    },
    {
      id: 'section.pyramids.provisioning',
      heading: 'Feeding and organizing the workforce',
      purpose: 'Make support labor and redistribution visible as part of monument building',
      modules: [
        {
          id: 'module.pyramids.feeding',
          type: 'prose',
          body: 'A large work crew cannot keep hauling if food stops arriving. At Heit el-Ghurab, southeast of the Giza pyramids, archaeologists have found bread molds, animal bones, storage spaces, workshops, offices, and different kinds of housing. These remains turn “feeding the workers” into a chain of jobs. Herds had to be raised and moved. Grain had to be collected, stored, ground, mixed, baked, and distributed. Tools and containers had to be made and replaced.\n\nThe strongest surviving phase of this settlement belongs mainly to the later Giza projects of Khafre and Menkaure, not entirely to Khufu’s reign. That date boundary matters. The settlement helps reveal how the Giza building system operated, but we should not silently move every wall and bone backward into Merer’s exact year.\n\nProvisioning is evidence of organization and unequal access. Different areas received different animal products, suggesting rank or role mattered. Yet a rich meal in the archaeological record cannot tell us whether a particular worker was content, coerced, exhausted, proud, or all four at different moments.',
          claimIds: ['claim.pyramids.worker-settlement', 'claim.pyramids.provisioning', 'claim.pyramids.labor-status'],
          sourceIds: ['source.pyramids.aera-lost-city', 'source.pyramids.aera-food', 'source.pyramids.egypt-workers-town'],
        },
        {
          id: 'module.pyramids.supply-chain',
          type: 'knowledge',
          eyebrow: 'A daily system',
          title: 'One loaf had a long history',
          body: 'Every ration connected the plateau to work beyond the monument.',
          items: [
            { label: 'Production', detail: 'Farming and herding used land, water, seed, animals, tools, and household labor.' },
            { label: 'Collection', detail: 'Institutions gathered goods through obligations, taxation, estates, or other arrangements that changed over time.' },
            { label: 'Processing', detail: 'Millers, bakers, brewers, butchers, cooks, and potters turned raw supplies into usable provisions.' },
            { label: 'Distribution', detail: 'Storage and records helped direct different goods toward crews, workshops, officials, and households.' },
          ],
          claimIds: ['claim.pyramids.provisioning', 'claim.pyramids.power-visible'],
          sourceIds: ['source.pyramids.aera-food', 'source.pyramids.warden-taxation', 'source.pyramids.aera-lost-city'],
        },
      ],
    },
    {
      id: 'section.pyramids.construction',
      heading: 'How construction worked',
      purpose: 'State the supported construction system without pretending one complete method survives',
      modules: [
        {
          id: 'module.pyramids.methods',
          type: 'prose',
          body: 'Food and records kept people working; builders still had to move and place stone. The exact construction sequence is debated, but uncertainty is not the same as mystery. Archaeology supports a connected toolkit: local quarrying, harder stone tools and copper tools for particular jobs, sledges, ropes, prepared roads, boats and waterways, ramps or other inclined surfaces, levers, careful measurement, and highly skilled finishing. Different stages and parts of the complex could use different arrangements.\n\nNo surviving Old Kingdom text gives us a complete building manual. Later diagrams, experiments, traces around other pyramids, and engineering models can test possibilities, but they do not recover one certain ramp wrapped around Khufu’s monument from bottom to top. A proposal must explain the physical evidence; it cannot become fact because it makes an exciting animation.\n\nThe strongest answer is therefore a system, not a secret. Generations of accumulated knowledge met organized labor and reliable supply. The unresolved details are real historical questions. They are not evidence for aliens, vanished machines, or people in the past being incapable of difficult engineering.',
          claimIds: ['claim.pyramids.construction-uncertain', 'claim.pyramids.development', 'claim.pyramids.records-limited'],
          sourceIds: ['source.pyramids.ucl-construction', 'source.pyramids.egypt-great-pyramid', 'source.pyramids.ifao-merer', 'source.pyramids.aera-gangs'],
        },
        {
          id: 'module.pyramids.known-unknown',
          type: 'knowledge',
          eyebrow: 'Evidence and reconstruction',
          title: 'Known parts, uncertain arrangement',
          body: 'Separate the supported components from the full sequence scholars reconstruct.',
          items: [
            { label: 'Supported components', detail: 'Quarries, tools, sledges, ropes, waterways, prepared surfaces, measurement, and skilled crews all have evidence behind them.' },
            { label: 'Supported principle', detail: 'People could divide a huge project into repeated tasks and combine crews and materials over many years.' },
            { label: 'Still reconstructed', detail: 'The exact shape, placement, and changing use of ramps or lifting arrangements at every height.' },
            { label: 'Not supported', detail: 'A gap in the manual does not require a lost civilization or nonhuman builders.' },
          ],
          claimIds: ['claim.pyramids.construction-uncertain', 'claim.pyramids.power-visible'],
          sourceIds: ['source.pyramids.ucl-construction', 'source.pyramids.egypt-great-pyramid', 'source.pyramids.harvard-giza'],
        },
      ],
    },
    {
      id: 'section.pyramids.world-check',
      heading: 'World Check',
      purpose: 'Require a supported state-capacity claim and an explicit evidence limit',
      modules: [
        { id: 'module.pyramids.prompt-limit', type: 'prompt', promptId: 'prompt.pyramids.evidence-and-limit', claimIds: [], sourceIds: [] },
      ],
    },
  ],
  claimIds: pyramidsPowerStateLaborClaims.map((claim) => claim.id),
  sourceIds: pyramidsPowerStateLaborSources.map((source) => source.id),
  mediaIds: [],
  promptIds: pyramidsPowerStateLaborPrompts.map((prompt) => prompt.id),
};

export const pyramidsPowerStateLaborContent: AuthoredContentModule = {
  sources: pyramidsPowerStateLaborSources,
  claims: pyramidsPowerStateLaborClaims,
  prompts: pyramidsPowerStateLaborPrompts,
  lessons: [pyramidsPowerStateLaborLesson],
};
