import type { Claim, Lesson, MediaAsset, Source, UnderstandingPrompt } from '../../src/domains/contracts';
import type { AuthoredContentModule } from '../assemble';
import { mediaLocator } from '../shared/media-locator';

export const pyramidsPowerStateLaborSources: Source[] = [
  { id: 'source.pyramids.ifao-merer', title: 'Les Papyrus de la Mer Rouge I: Le Journal de Merer', url: 'https://www.ifao.egnet.net/uploads/publications/divers/MIFAO136_ann_01.pdf', publisher: 'Institut français d’archéologie orientale', accessedOn: '2026-09-02', licenseOrUse: 'Official excavation publication cited for research; publication photography is not redistributed', reviewStatus: 'review-required' },
  { id: 'source.pyramids.harvard-giza', title: 'Digital Giza: Introduction to Giza', url: 'https://giza.fas.harvard.edu/gizaintro/', publisher: 'Harvard University', accessedOn: '2026-09-02', licenseOrUse: 'University archaeological archive cited for research; individual media require item-level rights review', reviewStatus: 'review-required' },
  { id: 'source.pyramids.aera-settlement', title: 'The Lost City of the Pyramid Builders', url: 'https://aeraweb.org/projects/lost-city/', publisher: 'Ancient Egypt Research Associates', accessedOn: '2026-09-02', licenseOrUse: 'Excavation-project synthesis cited for research; project images are not redistributed', reviewStatus: 'review-required' },
  { id: 'source.pyramids.mortar-radiocarbon', title: 'Radiocarbon Dates of Old and Middle Kingdom Monuments in Egypt', url: 'https://doi.org/10.1017/S0033822200038558', publisher: 'Radiocarbon', accessedOn: '2026-09-02', licenseOrUse: 'Peer-reviewed chronology study cited for research; figures are not redistributed', reviewStatus: 'review-required' },
  { id: 'source.pyramids.high-chronology', title: 'A New Radiocarbon-Based Chronology for the Egyptian Old Kingdom', url: 'https://doi.org/10.1371/journal.pone.0314612', publisher: 'PLOS ONE', accessedOn: '2026-09-02', licenseOrUse: 'CC BY peer-reviewed chronology study cited for research; figures require separate media review', reviewStatus: 'review-required' },
  { id: 'source.pyramids.dixon-cedar', title: 'The Great Pyramid’s Dixon Relics', url: 'https://doi.org/10.11588/cipeg.2020.4.86467', publisher: 'CIPEG Journal', accessedOn: '2026-09-02', licenseOrUse: 'Peer-reviewed object and radiocarbon study cited for research; images are not redistributed', reviewStatus: 'review-required' },
  { id: 'source.pyramids.scanpyramids-corridor', title: 'Precise characterization of a corridor-shaped structure in Khufu’s Pyramid by observation of cosmic-ray muons', url: 'https://doi.org/10.1038/s41467-023-36351-0', publisher: 'Nature Communications', accessedOn: '2026-09-02', licenseOrUse: 'Peer-reviewed open-access measurement study cited for research; figures require separate media review', reviewStatus: 'review-required' },
  { id: 'source.pyramids.osirion-frankfort', title: 'The Cenotaph of Seti I at Abydos', url: 'https://archive.org/details/MEEF39.1', publisher: 'Egypt Exploration Society', accessedOn: '2026-09-02', licenseOrUse: 'Primary excavation report cited for research; plates require separate rights review', reviewStatus: 'review-required' },
  { id: 'source.pyramids.osirion-luminescence', title: 'Surface luminescence dating of some Egyptian monuments', url: 'https://doi.org/10.1016/j.culher.2014.05.007', publisher: 'Journal of Cultural Heritage', accessedOn: '2026-09-02', licenseOrUse: 'Peer-reviewed dating study cited for research; figures are not redistributed', reviewStatus: 'review-required' },
  { id: 'source.pyramids.hawara-petrie', title: 'Hawara, Biahmu, and Arsinoe', url: 'https://doi.org/10.11588/diglit.1034', publisher: 'William Flinders Petrie / Field & Tuer', accessedOn: '2026-09-02', licenseOrUse: 'Public-domain primary excavation report cited for research; any runtime crop requires media review', reviewStatus: 'review-required' },
  { id: 'source.pyramids.hawara-vlf', title: 'Archaeogeophysical investigation of the Labyrinth mortuary temple complex at Hawara', url: 'https://doi.org/10.3997/1873-0604.2010004', publisher: 'Near Surface Geophysics', accessedOn: '2026-09-02', licenseOrUse: 'Peer-reviewed geophysical study cited for research; figures are not redistributed', reviewStatus: 'review-required' },
  { id: 'source.pyramids.hawara-ert', title: 'Geophysical Survey at Hawara Archaeological Site', url: 'https://archaeologicalrescue.org/wp-content/uploads/2026/02/Hawara-report-2024.pdf', publisher: 'Egyptian archaeological and geophysical research team', accessedOn: '2026-09-02', licenseOrUse: 'Public technical report cited for research; figures require separate rights review', reviewStatus: 'review-required' },
  { id: 'source.pyramids.hawara-pliny', title: 'Natural History, Book 36.84–89', url: 'https://www.attalus.org/translate/pliny_hn36a.html', publisher: 'Attalus / Pliny the Elder', accessedOn: '2026-09-02', licenseOrUse: 'Ancient literary testimony cited and paraphrased for research; no runtime image is used', reviewStatus: 'review-required' },
  { id: 'source.pyramids.hawara-excavation', title: 'Fayoum antiquities mission begins work at the Labyrinth site', url: 'https://www.cairo24.com/2420190', publisher: 'Cairo 24', accessedOn: '2026-09-02', licenseOrUse: 'Named-official fieldwork report cited for current-status context; media are not redistributed', reviewStatus: 'review-required' },
  { id: 'source.pyramids.vessels-metrology', title: 'Metrological analysis of Predynastic Egyptian stone vessels', url: 'https://doi.org/10.1038/s40494-025-02196-7', publisher: 'Heritage Science', accessedOn: '2026-09-02', licenseOrUse: 'Peer-reviewed open-access metrology study cited for research; figures require separate media review', reviewStatus: 'review-required' },
  { id: 'source.pyramids.vessels-abu-rawash', title: 'Technical choices and processes of stone vessel manufacture under the reign of king Den', url: 'https://www.persee.fr/doc/arnil_1161-0492_2021_num_31_1_1361', publisher: 'Archéo-Nil', accessedOn: '2026-09-02', licenseOrUse: 'Peer-reviewed archaeological study cited for research; figures are not redistributed', reviewStatus: 'review-required' },
  { id: 'source.pyramids.vessels-private-scans', title: 'Vase Scan Resources', url: 'https://unchartedx.com/site/vase-scan-resources/', publisher: 'UnchartedX', accessedOn: '2026-09-02', licenseOrUse: 'Claim-owner files and reports cited as a public evidence trail; no assets are redistributed', reviewStatus: 'review-required' },
  { id: 'source.pyramids.turin-king-list', title: 'Turin King List, Papyrus Cat. 1874', url: 'https://collezionepapiri.museoegizio.it/section/Papyrus-Collection/History-and-content/History-and-content/', publisher: 'Museo Egizio', accessedOn: '2026-09-02', licenseOrUse: 'Official museum context cited for research; object imagery is not redistributed', reviewStatus: 'review-required' },
  { id: 'source.pyramids.commons-giza-plan', title: 'Plan intérieur de la grande Pyramide', url: 'https://commons.wikimedia.org/wiki/File:Plan_int%C3%A9rieur_de_la_grande_Pyramide.jpg', publisher: 'Wikimedia Commons / E. Giraud', accessedOn: '2026-09-03', licenseOrUse: 'Public Domain Mark 1.0 raster used as the spatial reference for a Chronos evidence diagram', reviewStatus: 'reviewed' },
  { id: 'source.pyramids.commons-osirion-photo', title: '26869 — the Osireion at Abydos', url: 'https://commons.wikimedia.org/wiki/File:26869-_the_Osireion_at_Abydos.jpg', publisher: 'Wikimedia Commons / Panegyrics of Granovetter', accessedOn: '2026-09-03', licenseOrUse: 'CC BY-SA 2.0 photograph adapted with attribution and share-alike for a Chronos evidence diagram', reviewStatus: 'reviewed' },
  { id: 'source.pyramids.commons-hawara-plan', title: 'Hawara-plan-complexe', url: 'https://commons.wikimedia.org/wiki/File:Hawara-plan-complexe.jpg', publisher: 'Wikimedia Commons / Franck Monnier', accessedOn: '2026-09-03', licenseOrUse: 'CC BY 2.5 plan adapted with attribution for a Chronos evidence-stream diagram', reviewStatus: 'reviewed' },
  { id: 'source.pyramids.commons-vessels-photo', title: 'Ancient Egypt Predynastic Stone Vessels', url: 'https://commons.wikimedia.org/wiki/File:Ancient_Egypt_Predynastic_Stone_Vessels_(27732541153).jpg', publisher: 'Wikimedia Commons / Gary Todd', accessedOn: '2026-09-03', licenseOrUse: 'CC0 1.0 Louvre display photograph used as the object-form reference for a Chronos evidence diagram', reviewStatus: 'reviewed' },
];

export const pyramidsPowerStateLaborClaims: Claim[] = [
  { id: 'claim.pyramids.separate-questions', statement: 'A monument’s surrounding context, construction phase, material date, named ruler, later use, and inferred purpose are related but distinct historical questions.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.pyramids.ifao-merer', 'source.pyramids.mortar-radiocarbon', 'source.pyramids.osirion-frankfort', 'source.pyramids.hawara-petrie'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.giza-old-kingdom-context', statement: 'Administrative texts, radiocarbon series, royal complexes, transport infrastructure, and settlement evidence strongly connect intensive work at Giza with the Old Kingdom and Khufu’s reign.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.pyramids.ifao-merer', 'source.pyramids.harvard-giza', 'source.pyramids.aera-settlement', 'source.pyramids.mortar-radiocarbon'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.giza-context-limit', statement: 'Khufu-era activity at the Giza complex does not by itself directly date every internal masonry phase or prove the original purpose of every chamber.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.pyramids.ifao-merer', 'source.pyramids.harvard-giza', 'source.pyramids.scanpyramids-corridor'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.labor-stream', statement: 'Giza’s settlement and records show organized transport, provisioning, administration, and skilled work, but they do not recover every worker’s status or settle every construction phase.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.pyramids.ifao-merer', 'source.pyramids.aera-settlement'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.high-chronology', statement: 'A 2025 radiocarbon model supports an Old Kingdom chronology older by decades, and in some schemes about a century, than common lower chronologies rather than a shift of millennia.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.pyramids.high-chronology'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.material-is-not-event', statement: 'The age of wood or charcoal does not automatically equal the date when it was placed in a monument or when surrounding stone was built.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.pyramids.dixon-cedar', 'source.pyramids.mortar-radiocarbon'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.plan-incomplete', statement: 'Muon measurements established a previously unknown corridor in the Great Pyramid, while its role remains uncertain.', kind: 'observation', certainty: 'high', sourceIds: ['source.pyramids.scanpyramids-corridor'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.osirion-seti-assembly', statement: 'Excavation recorded Seti I-stamped construction bricks and a Seti-marked granite cramp beneath intact roofing, directly tying named components of the Osirion to Seti I’s building program.', kind: 'observation', certainty: 'high', sourceIds: ['source.pyramids.osirion-frankfort'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.osirion-date-conflict', statement: 'Two published Osirion surface-luminescence results are broad and discordant: one overlaps Seti I’s era while one produced an older, roughly Middle Kingdom-range estimate.', kind: 'observation', certainty: 'moderate', sourceIds: ['source.pyramids.osirion-luminescence'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.osirion-unresolved', statement: 'The Osirion evidence leaves an earlier component or surface history possible, but the two measurements cannot by themselves date the whole monument or identify its builders.', kind: 'interpretation', certainty: 'contested', sourceIds: ['source.pyramids.osirion-luminescence', 'source.pyramids.osirion-frankfort'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.hawara-middle-kingdom-link', statement: 'Excavated architectural material links the Hawara complex to Amenemhat III and Sobekneferu, establishing Middle Kingdom royal work and use at the site without directly dating every surviving foundation.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.pyramids.hawara-petrie'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.hawara-anomalies', statement: 'Ground geophysical surveys south of Hawara’s pyramid detected organized anomalies that may include architectural remains, but scans alone cannot identify or date them.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.pyramids.hawara-vlf', 'source.pyramids.hawara-ert'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.hawara-traditions', statement: 'Ancient writers preserved conflicting accounts of Hawara’s builder and purpose, and Pliny recorded a tradition placing its construction thousands of years earlier than the Middle Kingdom attribution.', kind: 'later-tradition', certainty: 'high', sourceIds: ['source.pyramids.hawara-pliny'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.hawara-excavation-test', statement: 'An Egyptian antiquities mission was reported excavating the Labyrinth area in 2026, creating a direct opportunity to test whether older construction phases survive.', kind: 'observation', certainty: 'moderate', sourceIds: ['source.pyramids.hawara-excavation'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.vessels-early-skill', statement: 'Provenanced Predynastic and Early Dynastic stone vessels show controlled rotation, abrasive working, and specialized high-skill production before the great Giza pyramids.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.pyramids.vessels-metrology', 'source.pyramids.vessels-abu-rawash'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.vessels-private-limit', statement: 'Some privately held vessel meshes show remarkable geometry, but geometry alone cannot establish an object’s archaeological age, maker, or manufacturing process.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.pyramids.vessels-private-scans', 'source.pyramids.vessels-metrology'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.deep-time-memory', statement: 'Egyptian records preserved divine and primeval successions before historical kings, showing that dynastic Egyptians imagined a deeper past without directly dating a particular monument.', kind: 'later-tradition', certainty: 'high', sourceIds: ['source.pyramids.turin-king-list'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.earlier-regime-hypothesis', statement: 'An earlier Nile cultural or technical regime of materially different character and ability is a legitimate hypothesis when tested structure by structure, but no single public evidence chain currently identifies it as the builder of all four cases.', kind: 'interpretation', certainty: 'contested', sourceIds: ['source.pyramids.mortar-radiocarbon', 'source.pyramids.osirion-luminescence', 'source.pyramids.hawara-petrie', 'source.pyramids.vessels-metrology'], reviewStatus: 'editorial-review-required' },
];

export const pyramidsPowerStateLaborMedia: MediaAsset[] = [
  {
    id: 'media.pyramids.giza-evidence-chain',
    locator: mediaLocator('media.pyramids.giza-evidence-chain'),
    alt: 'Evidence diagram centered on an archival Great Pyramid section, with separate panels for a papyrus log and limestone boat, the surrounding work landscape, charcoal and mortar dating, and an understated corridor detected by muon paths',
    depictionMode: 'diagram',
    depictionLabel: 'Evidence relationship diagram · archival section is not a modern survey',
    rightsLabel: 'Chronos original raster edit · E. Giraud reference, Public Domain Mark 1.0',
    sourceIds: ['source.pyramids.commons-giza-plan', 'source.pyramids.ifao-merer', 'source.pyramids.aera-settlement', 'source.pyramids.mortar-radiocarbon', 'source.pyramids.scanpyramids-corridor'],
    visualBriefRef: 'docs/research/pyramids-power-and-state-labor.md#image-lifecycle',
    reviewStatus: 'approved',
  },
  {
    id: 'media.pyramids.osirion-evidence-pair',
    locator: mediaLocator('media.pyramids.osirion-evidence-pair'),
    alt: 'Evidence diagram showing the surviving sunken Osirion, a protected dovetail-shaped stone connector beneath covering blocks, and granite and sandstone samples linked to broad earlier and later ranges on one shared scale',
    depictionMode: 'diagram',
    depictionLabel: 'Evidence relationship diagram · sample ranges do not date the whole monument',
    rightsLabel: 'Adapted from Panegyrics of Granovetter, CC BY-SA 2.0; changes made · diagram CC BY-SA 2.0',
    sourceIds: ['source.pyramids.commons-osirion-photo', 'source.pyramids.osirion-frankfort', 'source.pyramids.osirion-luminescence'],
    visualBriefRef: 'docs/research/pyramids-power-and-state-labor.md#image-lifecycle',
    reviewStatus: 'approved',
  },
  {
    id: 'media.pyramids.hawara-evidence-streams',
    locator: mediaLocator('media.pyramids.hawara-evidence-streams'),
    alt: 'Hawara plan surrounded by four distinct evidence panels: an ancient manuscript, royal-name architectural material, fuzzy geophysical anomalies beneath a survey grid, and an archaeological trench exposing crossing walls',
    depictionMode: 'diagram',
    depictionLabel: 'Evidence-stream diagram · central plan reconstructs excavated remains; geophysical anomalies are not confirmed rooms',
    rightsLabel: 'Chronos original raster edit · plan reference by Franck Monnier after Petrie, CC BY 2.5',
    sourceIds: ['source.pyramids.commons-hawara-plan', 'source.pyramids.hawara-petrie', 'source.pyramids.hawara-vlf', 'source.pyramids.hawara-ert', 'source.pyramids.hawara-pliny', 'source.pyramids.hawara-excavation'],
    visualBriefRef: 'docs/research/pyramids-power-and-state-labor.md#image-lifecycle',
    reviewStatus: 'approved',
  },
  {
    id: 'media.pyramids.vessel-evidence-test',
    locator: mediaLocator('media.pyramids.vessel-evidence-test'),
    alt: 'Three-part comparison separating a plain Predynastic-style hard-stone vessel in museum context, a generic cutaway wireframe showing inner and outer surfaces, and abrasive sand, water, simple tools, and a drilled test piece',
    depictionMode: 'diagram',
    depictionLabel: 'Evidence relationship diagram · represented object, generic mesh, and process clues are not one object history',
    rightsLabel: 'Chronos original raster edit · Gary Todd vessel-display reference, CC0 1.0',
    sourceIds: ['source.pyramids.commons-vessels-photo', 'source.pyramids.vessels-metrology', 'source.pyramids.vessels-abu-rawash', 'source.pyramids.vessels-private-scans'],
    visualBriefRef: 'docs/research/pyramids-power-and-state-labor.md#image-lifecycle',
    reviewStatus: 'approved',
  },
];

export const pyramidsPowerStateLaborPrompts: UnderstandingPrompt[] = [
  {
    id: 'prompt.pyramids.context-and-phase', lessonId: 'lesson.egypt.pyramids-and-state-labor', kind: 'supported-selection',
    question: 'Which conclusion best fits the whole pattern of evidence at Giza?',
    explanation: 'Merer’s crew, the royal complex, radiocarbon results, and the settlement all place major work at Giza in the Old Kingdom. Even together, they do not give every hidden space the same date or reveal what every chamber was first meant to do.',
    required: true,
    options: [
      { id: 'option.pyramids.strong-context-open-phases', label: 'Khufu-era work at Giza is strongly supported, while some internal phases and purposes remain open questions.' },
      { id: 'option.pyramids.settlement-dates-core', label: 'The workers’ settlement dates the Great Pyramid’s main core because both belong to Giza’s larger building system.' },
      { id: 'option.pyramids.cedar-dates-core', label: 'The older cedar is the strongest date for a pre-Khufu core because it was recovered from inside a sealed shaft.' },
      { id: 'option.pyramids.corridor-outweighs-context', label: 'The unknown corridor weakens the Old Kingdom attribution more than the dated log and complex context strengthen it.' },
    ],
  },
  {
    id: 'prompt.pyramids.build-evidence-chain', lessonId: 'lesson.egypt.pyramids-and-state-labor', kind: 'concise-explanation',
    question: 'Imagine you could join the next investigation at the Osirion, Hawara, or a stone vessel. What clue would you begin with, what might it mean, and what would you look for next?',
    explanation: 'Begin with something you can point to—a measurement, inscription, scan, object, or ancient account. Then name what it might mean and the excavation context, repeated test, or manufacturing experiment that could make the idea stronger or weaker.',
    required: true,
    minimumResponseLength: 40,
  },
];

export const pyramidsPowerStateLaborLesson: Lesson = {
  id: 'lesson.egypt.pyramids-and-state-labor',
  legacyAliases: ['imhotep', 'pyramids'],
  status: 'draft',
  title: 'Pyramids, Builders, and Evidence',
  masthead: 'Giza c. 2700–2500 BCE; comparisons from Predynastic Egypt to the present',
  place: 'Giza, Abydos, Hawara, and museum collections in Egypt',
  chronology: { startYear: -2700, endYear: -2500, display: 'Giza c. 2700–2500 BCE', approximate: true },
  significance: 'Egypt’s monuments still hold real surprises. Following their clues without forcing them into one story reveals both the power of the Old Kingdom and the possibility of deeper, less familiar histories along the Nile.',
  sectionIdsRequired: ['section.pyramids.questions', 'section.pyramids.giza', 'section.pyramids.dating', 'section.pyramids.osirion', 'section.pyramids.hawara', 'section.pyramids.vessels', 'section.pyramids.world-check'],
  sections: [
    {
      id: 'section.pyramids.questions', heading: 'At the Great Pyramid', purpose: 'Give learners a concrete method for separating evidence claims before comparing Egyptian cases',
      modules: [
        { id: 'module.pyramids.opening', type: 'prose', body: 'Stand at the foot of the Great Pyramid and the stone seems to answer before anyone asks a question: surely a monument this large must come with a certain story. Yet size does not make the story simple. Royal names, work crews, old wood, hidden spaces, repairs, and later rituals can all belong to the same place without belonging to the same moment.\n\nKhufu’s name is part of Giza’s evidence. But what kind of connection does a name establish—builder, patron, owner, restorer, or later claimant? What does a date belong to—the stone, a piece of wood, the placing of a block, or a later visit? And does later use reveal original purpose?\n\nAt Giza, several clues converge strongly on major Old Kingdom work. At the Osirion, Hawara, and among Egypt’s finely worked stone vessels, the pattern is less settled. Each place gets its own hearing. The aim is not to defend one grand answer, but to discover how much stranger and more interesting the evidence becomes when we let different clues tell different parts of the story.', claimIds: ['claim.pyramids.separate-questions', 'claim.pyramids.earlier-regime-hypothesis'], sourceIds: ['source.pyramids.ifao-merer', 'source.pyramids.osirion-frankfort', 'source.pyramids.hawara-petrie', 'source.pyramids.vessels-metrology'] },
        { id: 'module.pyramids.six-questions', type: 'knowledge', eyebrow: 'Reading a monument', title: 'Follow the evidence toward purpose', body: 'Five checks keep the clues distinct. Together, they lead to the larger question: what purpose does the whole pattern actually support?', items: [
          { label: 'What survives?', detail: 'Start with the wall, object, writing, scan result, tool mark, or material that can be inspected.' },
          { label: 'What is its context?', detail: 'Ask where it was found, what surrounds it, and whether that relationship is undisturbed.' },
          { label: 'What event is dated?', detail: 'The age of wood, a stone surface, mortar, or a written reign may date different events.' },
          { label: 'Who is connected?', detail: 'A name may identify a builder, patron, owner, restorer, user, or later claimant.' },
          { label: 'What changed?', detail: 'A monument may be built, enlarged, repaired, or repurposed. A later use does not automatically reveal its first purpose.' },
        ], claimIds: ['claim.pyramids.separate-questions'], sourceIds: ['source.pyramids.dixon-cedar', 'source.pyramids.osirion-luminescence', 'source.pyramids.hawara-petrie'] },
      ],
    },
    {
      id: 'section.pyramids.giza', heading: 'Giza in Khufu’s time', purpose: 'Present the strongest converging Old Kingdom evidence while preserving its phase and purpose limits',
      modules: [
        { id: 'module.pyramids.giza-evidence', type: 'prose', body: 'About 4,500 years ago, an inspector named Merer kept a day-by-day log. His crew loaded fine limestone at Tura, travelled by water, and delivered it to Akhet-Khufu—“Khufu’s Horizon”—late in Khufu’s reign. The entries are brief, but they bring part of the project alive: boats moving through canals, named teams reporting to officials, and stone arriving on schedule.\n\nMove outward from the pyramid and the scene widens. Temples, causeways, boat pits, cemeteries, offices, workshops, bakeries, animal bones, and workers’ housing preserve a whole landscape of building and ritual. Mortar samples broadly cluster in the third millennium BCE, though some are older than expected. This is why the Old Kingdom case at Giza is strong: many independent clues meet in the same place and period.\n\nThe people behind that work were not one faceless slave gang. They included skilled crews, administrators, boatmen, cooks, and others supported by a vast system of food and supplies. Some may have served willingly, some by obligation, and some under conditions we can no longer recover. The best-preserved settlement also belongs mainly to the later projects of Khafre and Menkaure. It illuminates Giza’s building world without becoming an answer to every question inside Khufu’s pyramid.', claimIds: ['claim.pyramids.giza-old-kingdom-context', 'claim.pyramids.labor-stream'], sourceIds: ['source.pyramids.ifao-merer', 'source.pyramids.harvard-giza', 'source.pyramids.aera-settlement', 'source.pyramids.mortar-radiocarbon'] },
        { id: 'module.pyramids.giza-visual', type: 'evidence', title: 'Four clues around one monument', artifactLabel: 'Evidence relationship diagram', body: 'The log records transport. The settlement and causeways supply context. Charcoal or mortar dates a material. Muons reveal a space. Together they form a strong case for major Old Kingdom work at Giza, but none automatically gives every internal phase the same date or explains the monument’s first purpose.', mediaId: 'media.pyramids.giza-evidence-chain', claimIds: ['claim.pyramids.giza-old-kingdom-context', 'claim.pyramids.giza-context-limit', 'claim.pyramids.material-is-not-event', 'claim.pyramids.plan-incomplete'], sourceIds: ['source.pyramids.ifao-merer', 'source.pyramids.aera-settlement', 'source.pyramids.mortar-radiocarbon', 'source.pyramids.scanpyramids-corridor'] },
        { id: 'module.pyramids.giza-limit', type: 'knowledge', eyebrow: 'The Giza case', title: 'A strong history with unfinished edges', body: 'The wider building world is vivid. Some interior moments remain much harder to see.', items: [
          { label: 'Khufu’s project', detail: 'His administration moved fine limestone to the named Giza project, and Old Kingdom activity surrounded the pyramids.' },
          { label: 'The wider program', detail: 'The complex fits a major royal building and cult program supported by many kinds of organized work.' },
          { label: 'Inside the monument', detail: 'The surrounding evidence does not make every hidden space, core block, or internal phase the same date.' },
          { label: 'Workers’ lives', detail: 'Their food, housing, jobs, and organization survive more clearly than every person’s freedom, obligation, or experience.' },
        ], claimIds: ['claim.pyramids.giza-old-kingdom-context', 'claim.pyramids.giza-context-limit', 'claim.pyramids.labor-stream'], sourceIds: ['source.pyramids.ifao-merer', 'source.pyramids.harvard-giza', 'source.pyramids.scanpyramids-corridor'] },
      ],
    },
    {
      id: 'section.pyramids.dating', heading: 'Dating a stone monument', purpose: 'Show why material age, archaeological context, historical chronology, and architectural phase can disagree',
      modules: [
        { id: 'module.pyramids.dating-evidence', type: 'prose', body: 'Stone carries no growth rings and no stamped year. To date a stone monument, researchers look for something that once lived or something whose surface was exposed to light—and then ask how it became part of the building.\n\nConsider a small cedar fragment found in a sealed shaft inside the Great Pyramid. Its radiocarbon range, 3341–3094 BCE, is older than Khufu. That is intriguing, but the test dates the tree’s growth. The wood might have come from the long-lived heart of an old tree, rested in storage, or been reused before entering the shaft. Charcoal trapped in mortar creates the same puzzle: it is close to construction, yet the wood burned to make it may already have had a long history.\n\nA 2025 study brought 160 measurements together, giving extra weight to short-lived plants. Its result nudges the Old Kingdom earlier than familiar textbook dates—by decades and, in some chronologies, roughly a century. That changes the calendar without moving the pyramids into another age. At the same time, cosmic-ray muons revealed a corridor no modern explorer knew existed. The corridor is real. What it did, when it was made, and what else may remain hidden are new questions rather than instant answers.', claimIds: ['claim.pyramids.material-is-not-event', 'claim.pyramids.high-chronology', 'claim.pyramids.plan-incomplete'], sourceIds: ['source.pyramids.dixon-cedar', 'source.pyramids.high-chronology', 'source.pyramids.scanpyramids-corridor'] },
        { id: 'module.pyramids.prompt-context', type: 'prompt', promptId: 'prompt.pyramids.context-and-phase', claimIds: [], sourceIds: [] },
      ],
    },
    {
      id: 'section.pyramids.osirion', heading: 'The Osirion at Abydos', purpose: 'Let learners compare a named structural component with discordant surface-luminescence dates',
      modules: [
        { id: 'module.pyramids.osirion-evidence', type: 'prose', body: 'Behind the richly decorated temple of Seti I at Abydos lies a building with a different presence. The Osirion sits low in the ground, often holding water, with enormous undecorated blocks arranged around a central island. Early excavators felt they were looking at architecture from a much earlier Egypt.\n\nThen excavation complicated that impression. Bricks stamped for Seti I appeared in the construction sequence. Beneath intact roofing, excavators found a granite cramp—a stone connector joining blocks—marked with Seti’s royal name. This was not simply a boast added to a finished wall: it tied at least one hidden part of the structure directly to his building program.\n\nA later scientific test complicated the story again. In 2015, researchers estimated when two stone surfaces had last seen enough light before being covered. The sandstone result centered around 1300 BCE, but with a very wide range extending centuries on either side. The granite result pointed much earlier, to around 1980 BCE.\n\nTwo samples cannot give an entire monument a birthday. The older granite could belong to an earlier component, reused stone, an unusual exposure history, a surface whose dating signal was not fully reset, or a limit of the measurement. But it should not be wished away. For now, the Osirion holds both a substantial Seti I construction story and a serious reason to test for something older.', claimIds: ['claim.pyramids.osirion-seti-assembly', 'claim.pyramids.osirion-date-conflict', 'claim.pyramids.osirion-unresolved'], sourceIds: ['source.pyramids.osirion-frankfort', 'source.pyramids.osirion-luminescence'] },
        { id: 'module.pyramids.osirion-visual', type: 'evidence', title: 'One protected join, two broad ranges', artifactLabel: 'Evidence relationship diagram', body: 'The connector belongs to a protected structural assembly tied to Seti I. The blue-gray granite range sits earlier on the shared scale; the amber sandstone range sits later. Both estimates are broad, and two surfaces cannot supply one construction date for the whole Osirion.', mediaId: 'media.pyramids.osirion-evidence-pair', claimIds: ['claim.pyramids.osirion-seti-assembly', 'claim.pyramids.osirion-date-conflict', 'claim.pyramids.osirion-unresolved'], sourceIds: ['source.pyramids.osirion-frankfort', 'source.pyramids.osirion-luminescence'] },
        { id: 'module.pyramids.osirion-compare', type: 'knowledge', eyebrow: 'The open question', title: 'Two clues, two moments in the building', body: 'The Seti connection is physical and protected. The older surface result is scientific and unresolved.', items: [
          { label: 'Seti-marked cramp', detail: 'Directly connects one protected structural assembly to Seti I’s program.' },
          { label: 'Older granite result', detail: 'Dates the sampled surface under a model; it may indicate an older component or a different exposure history.' },
          { label: 'Missing link', detail: 'Replicated dates tied to known wall junctions could distinguish reused stone from an earlier construction phase.' },
        ], claimIds: ['claim.pyramids.osirion-seti-assembly', 'claim.pyramids.osirion-date-conflict', 'claim.pyramids.osirion-unresolved'], sourceIds: ['source.pyramids.osirion-frankfort', 'source.pyramids.osirion-luminescence'] },
      ],
    },
    {
      id: 'section.pyramids.hawara', heading: 'The Labyrinth at Hawara', purpose: 'Compare ancient testimony, excavated royal material, geophysics, and active excavation without flattening their conflicts',
      modules: [
        { id: 'module.pyramids.hawara-evidence', type: 'prose', body: 'Ancient visitors struggled to describe the building at Hawara. Herodotus called it greater than the pyramids, claimed to have walked through its upper rooms, and linked it to twelve kings. Other writers disagreed about its builders and purpose. Pliny preserved the most startling tradition: that the Labyrinth had been built 3,600 years before his time. Surviving versions disagree over the exact number, but not that the tradition imagined a far deeper past.\n\nMuch of the building had vanished by the time Petrie excavated Hawara. In the robbed foundation bed he found architectural pieces naming the Middle Kingdom rulers Amenemhat III and Sobekneferu. Those names anchor royal work and use in their era. They do not, by themselves, make every foundation beneath the site the same age.\n\nThe ground has since begun to speak in another way. Surveys in 2010 and 2024 detected organized shapes beneath the soil south of the pyramid—possible walls or rooms that excavation can finally reach. In 2026, an Egyptian official reported that an antiquities and university team had begun that work. Hawara is no longer only an argument over old texts and scans. Trenches can now reveal which walls meet, which cut through others, and whether a deeper phase survives.', claimIds: ['claim.pyramids.hawara-middle-kingdom-link', 'claim.pyramids.hawara-anomalies', 'claim.pyramids.hawara-traditions', 'claim.pyramids.hawara-excavation-test'], sourceIds: ['source.pyramids.hawara-petrie', 'source.pyramids.hawara-vlf', 'source.pyramids.hawara-ert', 'source.pyramids.hawara-pliny', 'source.pyramids.hawara-excavation'] },
        { id: 'module.pyramids.hawara-visual', type: 'evidence', title: 'Four ways the ground can answer', artifactLabel: 'Evidence-stream diagram', body: 'The central plan reconstructs excavated remains rather than a complete surviving building. Ancient testimony preserves remembered scale and disagreement. Royal-name material anchors Middle Kingdom work. Survey colors mark subsurface anomalies, not confirmed rooms. Excavation can reveal which walls meet or cut through others—and recover material that can actually be dated.', mediaId: 'media.pyramids.hawara-evidence-streams', claimIds: ['claim.pyramids.hawara-middle-kingdom-link', 'claim.pyramids.hawara-anomalies', 'claim.pyramids.hawara-traditions', 'claim.pyramids.hawara-excavation-test'], sourceIds: ['source.pyramids.hawara-petrie', 'source.pyramids.hawara-vlf', 'source.pyramids.hawara-ert', 'source.pyramids.hawara-pliny', 'source.pyramids.hawara-excavation'] },
        { id: 'module.pyramids.hawara-streams', type: 'knowledge', eyebrow: 'Hawara today', title: 'Four voices in an unfinished history', body: 'No single voice tells the whole story, but together they show where to look next.', items: [
          { label: 'The ancient visitors', detail: 'Preserve awe, memory, and argument—including conflicting builders and a startling deep date.' },
          { label: 'The royal names', detail: 'Connect Amenemhat III and Sobekneferu to work and use at the complex.' },
          { label: 'The buried shapes', detail: 'Reveal organized features beneath the soil, without yet telling us who built them or when.' },
          { label: 'The new trenches', detail: 'Can uncover wall relationships, sealed deposits, reused blocks, and material suitable for dating.' },
        ], claimIds: ['claim.pyramids.hawara-middle-kingdom-link', 'claim.pyramids.hawara-anomalies', 'claim.pyramids.hawara-traditions', 'claim.pyramids.hawara-excavation-test'], sourceIds: ['source.pyramids.hawara-petrie', 'source.pyramids.hawara-vlf', 'source.pyramids.hawara-ert', 'source.pyramids.hawara-pliny', 'source.pyramids.hawara-excavation'] },
      ],
    },
    {
      id: 'section.pyramids.vessels', heading: 'The skill inside a stone vessel', purpose: 'Use metrology and provenance to establish early Nile skill without making geometry answer chronology or authorship by itself',
      modules: [
        { id: 'module.pyramids.vessels-evidence', type: 'prose', body: 'Imagine lifting a thin-walled bowl carved from granite. The stone is harder than a steel knife, yet its curve feels deliberate and its inner and outer surfaces stay remarkably centered. Nile craftspeople were making objects like this before the Great Pyramid rose. Excavated Predynastic and Early Dynastic vessels preserve drilling, polishing, careful symmetry, and controlled turning.\n\nA 2025 study measured 19 catalogued vessels in the Petrie Museum and compared them with modern handmade and machine-made objects. In overall quality, the ancient group overlapped the handmade examples. But its ability to keep the inside and outside centered stood out. The researchers proposed patient abrasive work: turn the vessel while grinding tools and a sand-and-water mixture slowly remove the stone.\n\nOther scans raise harder questions. Some privately held vessels show fitted curves and geometry that look even more extraordinary. Those measurements deserve to be examined rather than mocked. Yet a beautiful digital mesh cannot supply the physical object’s missing excavation history, and precision alone cannot name a tool or maker. Comparable scans, open processing files, microscopic traces, secure find histories, and successful experiments could carry the argument much further.\n\nWhat is already secure is impressive enough. A highly capable stoneworking tradition flourished along the Nile before the famous pyramids, and some vessels became heirlooms deposited generations later. Its tools, training, and organization may have differed greatly from later practice. Whether those craftspeople also belonged to an older phase of a particular monument remains a question to answer at that monument.', claimIds: ['claim.pyramids.vessels-early-skill', 'claim.pyramids.vessels-private-limit', 'claim.pyramids.earlier-regime-hypothesis'], sourceIds: ['source.pyramids.vessels-metrology', 'source.pyramids.vessels-abu-rawash', 'source.pyramids.vessels-private-scans'] },
        { id: 'module.pyramids.vessels-visual', type: 'evidence', title: 'Object, measurement, and method', artifactLabel: 'Evidence relationship diagram', body: 'The referenced museum collection preserves real early vessel forms; dates for individual objects come from their documented find and collection records, not from the represented jar alone. The generic mesh makes centered inner and outer surfaces visible. Abrasives, simple tools, wear, and successful experiments test possible methods. These are three linked questions—not one object biography.', mediaId: 'media.pyramids.vessel-evidence-test', claimIds: ['claim.pyramids.vessels-early-skill', 'claim.pyramids.vessels-private-limit'], sourceIds: ['source.pyramids.vessels-metrology', 'source.pyramids.vessels-abu-rawash', 'source.pyramids.vessels-private-scans'] },
        { id: 'module.pyramids.deep-time', type: 'knowledge', eyebrow: 'Earlier Nile histories', title: 'The Turin King List begins before the dynasties', body: 'The list begins with divine and primeval rulers before historical kings. Such records matter, but they are not construction labels.', items: [
          { label: 'They can show', detail: 'Egyptians did not imagine their own history beginning with the rulers whose monuments survive best.' },
          { label: 'They can preserve', detail: 'Names, successions, sacred memory, and ideas about peoples or powers before the familiar dynasties.' },
          { label: 'They cannot date alone', detail: 'A wall, vessel, or pyramid without a defensible link between the text and that object.' },
        ], claimIds: ['claim.pyramids.deep-time-memory', 'claim.pyramids.earlier-regime-hypothesis'], sourceIds: ['source.pyramids.turin-king-list', 'source.pyramids.vessels-metrology'] },
      ],
    },
    {
      id: 'section.pyramids.world-check', heading: 'Build a case from one clue', purpose: 'Require learners to build a short observation-to-interpretation-to-test chain from one comparison case',
      modules: [
        { id: 'module.pyramids.prompt-chain', type: 'prompt', promptId: 'prompt.pyramids.build-evidence-chain', claimIds: [], sourceIds: [] },
        { id: 'module.pyramids.conclusion', type: 'prose', body: 'After four stops, Egypt looks less like a solved diagram and more like a landscape with histories laid over one another. Khufu’s administration and crews emerge clearly at Giza. Skilled stoneworkers appear much earlier. At Abydos, Seti I’s builders left their mark inside an Osirion that may also contain an older story. At Hawara, ancient memories, Middle Kingdom names, buried architecture, and new excavation are meeting for the first time.\n\nThat does not make every explanation equally likely. It makes an earlier Nile cultural or technical regime of materially different character and ability a legitimate possibility—one that must earn its place structure by structure. A sealed deposit beneath a wall, a dated surface at a known joint, an excavated earlier foundation, or a successful tool experiment on a securely documented vessel could transform possibility into a much stronger history.\n\nThe exciting position is not certainty at all costs. It is knowing exactly where the evidence is strong, where it strains, and where the next discovery could genuinely change the story.', claimIds: ['claim.pyramids.separate-questions', 'claim.pyramids.giza-old-kingdom-context', 'claim.pyramids.osirion-unresolved', 'claim.pyramids.hawara-excavation-test', 'claim.pyramids.vessels-early-skill', 'claim.pyramids.earlier-regime-hypothesis'], sourceIds: ['source.pyramids.ifao-merer', 'source.pyramids.osirion-frankfort', 'source.pyramids.osirion-luminescence', 'source.pyramids.hawara-petrie', 'source.pyramids.hawara-excavation', 'source.pyramids.vessels-metrology'] },
      ],
    },
  ],
  claimIds: pyramidsPowerStateLaborClaims.map((claim) => claim.id),
  sourceIds: pyramidsPowerStateLaborSources.map((source) => source.id),
  mediaIds: pyramidsPowerStateLaborMedia.map((media) => media.id),
  promptIds: pyramidsPowerStateLaborPrompts.map((prompt) => prompt.id),
};

export const pyramidsPowerStateLaborContent: AuthoredContentModule = {
  sources: pyramidsPowerStateLaborSources,
  claims: pyramidsPowerStateLaborClaims,
  media: pyramidsPowerStateLaborMedia,
  prompts: pyramidsPowerStateLaborPrompts,
  lessons: [pyramidsPowerStateLaborLesson],
};
