import type { Claim, Lesson, Source, UnderstandingPrompt } from '../../src/domains/contracts';
import type { AuthoredContentModule } from '../assemble';

export const pyramidsPowerStateLaborSources: Source[] = [
  { id: 'source.pyramids.ifao-merer', title: 'Les Papyrus de la Mer Rouge I: Le Journal de Merer', url: 'https://www.ifao.egnet.net/uploads/publications/divers/MIFAO136_ann_01.pdf', publisher: 'Institut français d’archéologie orientale', accessedOn: '2026-09-02', licenseOrUse: 'Official excavation publication cited for research; publication photography is not redistributed', reviewStatus: 'review-required' },
  { id: 'source.pyramids.harvard-giza', title: 'Digital Giza: Introduction to Giza', url: 'https://giza.fas.harvard.edu/gizaintro/', publisher: 'Harvard University', accessedOn: '2026-09-02', licenseOrUse: 'University archaeological archive cited for research; individual media require item-level rights review', reviewStatus: 'review-required' },
  { id: 'source.pyramids.aera-settlement', title: 'The Lost City of the Pyramid Builders', url: 'https://aeraweb.org/projects/lost-city/', publisher: 'Ancient Egypt Research Associates', accessedOn: '2026-09-02', licenseOrUse: 'Excavation-project synthesis cited for research; project images are not redistributed', reviewStatus: 'review-required' },
  { id: 'source.pyramids.mortar-radiocarbon', title: 'Radiocarbon Dates of Old and Middle Kingdom Monuments in Egypt', url: 'https://doi.org/10.1017/S0033822200038558', publisher: 'Radiocarbon', accessedOn: '2026-09-02', licenseOrUse: 'Peer-reviewed chronology study cited for research; figures are not redistributed', reviewStatus: 'review-required' },
  { id: 'source.pyramids.high-chronology', title: 'A New Radiocarbon-Based Chronology for the Egyptian Old Kingdom', url: 'https://doi.org/10.1371/journal.pone.0314612', publisher: 'PLOS ONE', accessedOn: '2026-09-02', licenseOrUse: 'CC BY peer-reviewed chronology study cited for research; figures require separate media review', reviewStatus: 'review-required' },
  { id: 'source.pyramids.dixon-cedar', title: 'The Great Pyramid’s Dixon Relics', url: 'https://doi.org/10.11588/cipeg.2020.4.86467', publisher: 'CIPEG Journal', accessedOn: '2026-09-02', licenseOrUse: 'Peer-reviewed object and radiocarbon study cited for research; images are not redistributed', reviewStatus: 'review-required' },
  { id: 'source.pyramids.scanpyramids-corridor', title: 'Precise characterization of a corridor-shaped structure in Khufu’s Pyramid by observation of cosmic-ray muons', url: 'https://doi.org/10.1038/s41467-023-36351-0', publisher: 'Nature Communications', accessedOn: '2026-09-02', licenseOrUse: 'Peer-reviewed open-access measurement study cited for research; figures require separate media review', reviewStatus: 'review-required' },
  { id: 'source.pyramids.osirion-frankfort', title: 'The Cenotaph of Seti I at Abydos', url: 'https://archive.org/details/MEEF39.1', publisher: 'Egypt Exploration Society', accessedOn: '2026-09-02', licenseOrUse: 'Primary excavation report cited for research; plates require separate rights review', reviewStatus: 'review-required' },
  { id: 'source.pyramids.osirion-luminescence', title: 'Surface luminescence dating of some Egyptian monuments', url: 'https://doi.org/10.1016/j.culher.2014.05.007', publisher: 'Journal of Cultural Heritage', accessedOn: '2026-09-02', licenseOrUse: 'Peer-reviewed dating study cited for research; figures are not redistributed', reviewStatus: 'review-required' },
  { id: 'source.pyramids.hawara-petrie', title: 'Hawara, Biahmu, and Arsinoe', url: 'https://doi.org/10.11588/diglit.1034', publisher: 'William Flinders Petrie / Field & Tuer', accessedOn: '2026-09-02', licenseOrUse: 'Public-domain primary excavation report cited for research; any runtime crop requires media review', reviewStatus: 'review-required' },
  { id: 'source.pyramids.hawara-vlf', title: 'Archaeogeophysical investigation of the Labyrinth mortuary temple complex at Hawara', url: 'https://doi.org/10.3997/1873-0604.2010004', publisher: 'Near Surface Geophysics', accessedOn: '2026-09-02', licenseOrUse: 'Peer-reviewed geophysical study cited for research; figures are not redistributed', reviewStatus: 'review-required' },
  { id: 'source.pyramids.hawara-ert', title: 'Geophysical Survey at Hawara Archaeological Site', url: 'https://archaeologicalrescue.org/wp-content/uploads/2026/02/Hawara-report-2024.pdf', publisher: 'Egyptian archaeological and geophysical research team', accessedOn: '2026-09-02', licenseOrUse: 'Public technical report cited for research; figures require separate rights review', reviewStatus: 'review-required' },
  { id: 'source.pyramids.hawara-pliny', title: 'Natural History, Book 36.84–89', url: 'https://www.attalus.org/translate/pliny_hn36a.html', publisher: 'Attalus / Pliny the Elder', accessedOn: '2026-09-02', licenseOrUse: 'Ancient literary testimony cited and paraphrased for research; no runtime image is used', reviewStatus: 'review-required' },
  { id: 'source.pyramids.hawara-excavation', title: 'Fayoum antiquities mission begins work at the Labyrinth site', url: 'https://www.cairo24.com/2420190', publisher: 'Cairo 24', accessedOn: '2026-09-02', licenseOrUse: 'Named-official fieldwork report cited for current-status context; media are not redistributed', reviewStatus: 'review-required' },
  { id: 'source.pyramids.vessels-metrology', title: 'Metrological analysis of Predynastic Egyptian stone vessels', url: 'https://doi.org/10.1038/s40494-025-02196-7', publisher: 'Heritage Science', accessedOn: '2026-09-02', licenseOrUse: 'Peer-reviewed open-access metrology study cited for research; figures require separate media review', reviewStatus: 'review-required' },
  { id: 'source.pyramids.vessels-abu-rawash', title: 'Technical choices and processes of stone vessel manufacture under the reign of king Den', url: 'https://www.persee.fr/doc/arnil_1161-0492_2021_num_31_1_1361', publisher: 'Archéo-Nil', accessedOn: '2026-09-02', licenseOrUse: 'Peer-reviewed archaeological study cited for research; figures are not redistributed', reviewStatus: 'review-required' },
  { id: 'source.pyramids.vessels-private-scans', title: 'Vase Scan Resources', url: 'https://unchartedx.com/site/vase-scan-resources/', publisher: 'UnchartedX', accessedOn: '2026-09-02', licenseOrUse: 'Claim-owner files and reports cited as a public evidence trail; no assets are redistributed', reviewStatus: 'review-required' },
  { id: 'source.pyramids.turin-king-list', title: 'Turin King List, Papyrus Cat. 1874', url: 'https://collezionepapiri.museoegizio.it/section/Papyrus-Collection/History-and-content/History-and-content/', publisher: 'Museo Egizio', accessedOn: '2026-09-02', licenseOrUse: 'Official museum context cited for research; object imagery is not redistributed', reviewStatus: 'review-required' },
];

export const pyramidsPowerStateLaborClaims: Claim[] = [
  { id: 'claim.pyramids.separate-questions', statement: 'A monument’s surrounding context, construction phase, material date, named ruler, later use, and inferred purpose are related but distinct historical questions.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.pyramids.ifao-merer', 'source.pyramids.mortar-radiocarbon', 'source.pyramids.osirion-frankfort', 'source.pyramids.hawara-petrie'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.giza-old-kingdom-context', statement: 'Administrative texts, radiocarbon series, royal complexes, transport infrastructure, and settlement evidence strongly connect intensive work at Giza with the Old Kingdom and Khufu’s reign.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.pyramids.ifao-merer', 'source.pyramids.harvard-giza', 'source.pyramids.aera-settlement', 'source.pyramids.mortar-radiocarbon'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.giza-context-limit', statement: 'Khufu-era activity at the Giza complex does not by itself directly date every internal masonry phase or prove the original purpose of every chamber.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.pyramids.ifao-merer', 'source.pyramids.harvard-giza', 'source.pyramids.scanpyramids-corridor'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.labor-stream', statement: 'Giza’s settlement and records show organized transport, provisioning, administration, and skilled work, but they do not recover every worker’s status or settle every construction phase.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.pyramids.ifao-merer', 'source.pyramids.aera-settlement'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.high-chronology', statement: 'A 2025 radiocarbon model supports an Old Kingdom chronology older by decades, and in some schemes about a century, than common lower chronologies rather than a shift of millennia.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.pyramids.high-chronology'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.material-is-not-event', statement: 'The age of wood or charcoal does not automatically equal the date when it was placed in a monument or when surrounding stone was built.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.pyramids.dixon-cedar', 'source.pyramids.mortar-radiocarbon'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.plan-incomplete', statement: 'Muon measurements established a previously unknown corridor in the Great Pyramid, while its role remains uncertain.', kind: 'observation', certainty: 'high', sourceIds: ['source.pyramids.scanpyramids-corridor'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.osirion-seti-assembly', statement: 'Excavation recorded Seti I-stamped construction bricks and a Seti-marked granite cramp beneath intact roofing, directly tying named components of the Osirion to Seti I’s building program.', kind: 'observation', certainty: 'high', sourceIds: ['source.pyramids.osirion-frankfort'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.osirion-date-conflict', statement: 'Two published Osirion surface-luminescence results are broad and discordant: one overlaps Seti I’s era while one produced an older, roughly Middle Kingdom-range estimate.', kind: 'observation', certainty: 'moderate', sourceIds: ['source.pyramids.osirion-luminescence'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.osirion-unresolved', statement: 'The Osirion evidence leaves an earlier component or surface history possible, but the two measurements cannot by themselves date the whole monument or identify its builders.', kind: 'interpretation', certainty: 'contested', sourceIds: ['source.pyramids.osirion-luminescence', 'source.pyramids.osirion-frankfort'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.hawara-middle-kingdom-link', statement: 'Excavated architectural material links the Hawara complex to Amenemhat III and Sobekneferu, establishing Middle Kingdom royal work and use at the site without directly dating every surviving foundation.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.pyramids.hawara-petrie'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.hawara-anomalies', statement: 'Ground geophysical surveys south of Hawara’s pyramid detected organized anomalies that may include architectural remains, but scans alone cannot identify or date them.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.pyramids.hawara-vlf', 'source.pyramids.hawara-ert'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.hawara-traditions', statement: 'Ancient writers preserved conflicting accounts of Hawara’s builder and purpose, and Pliny recorded a tradition placing its construction thousands of years earlier than the Middle Kingdom attribution.', kind: 'later-tradition', certainty: 'high', sourceIds: ['source.pyramids.hawara-pliny'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.hawara-excavation-test', statement: 'An Egyptian antiquities mission was reported excavating the Labyrinth area in 2026, creating a direct opportunity to test whether older construction phases survive.', kind: 'observation', certainty: 'moderate', sourceIds: ['source.pyramids.hawara-excavation'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.vessels-early-skill', statement: 'Provenanced Predynastic and Early Dynastic stone vessels show controlled rotation, abrasive working, and specialized high-skill production before the great Giza pyramids.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.pyramids.vessels-metrology', 'source.pyramids.vessels-abu-rawash'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.vessels-private-limit', statement: 'Some privately held vessel meshes show remarkable geometry, but geometry alone cannot establish an object’s archaeological age, maker, or manufacturing process.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.pyramids.vessels-private-scans', 'source.pyramids.vessels-metrology'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.deep-time-memory', statement: 'Egyptian records preserved divine and primeval successions before historical kings, showing that dynastic Egyptians imagined a deeper past without directly dating a particular monument.', kind: 'later-tradition', certainty: 'high', sourceIds: ['source.pyramids.turin-king-list'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.pyramids.earlier-regime-hypothesis', statement: 'An earlier Nile cultural or technical regime of materially different character and ability is a legitimate hypothesis when tested structure by structure, but no single public evidence chain currently identifies it as the builder of all four cases.', kind: 'interpretation', certainty: 'contested', sourceIds: ['source.pyramids.mortar-radiocarbon', 'source.pyramids.osirion-luminescence', 'source.pyramids.hawara-petrie', 'source.pyramids.vessels-metrology'], reviewStatus: 'editorial-review-required' },
];

export const pyramidsPowerStateLaborPrompts: UnderstandingPrompt[] = [
  {
    id: 'prompt.pyramids.context-and-phase', lessonId: 'lesson.egypt.pyramids-and-state-labor', kind: 'supported-selection',
    question: 'Which conclusion best respects both the strength and the limit of the Giza evidence?',
    explanation: 'Merer’s log, radiocarbon, settlement remains, and the royal complex strongly connect Old Kingdom institutions with major work at Giza. They do not automatically date every hidden or internal phase or identify the purpose of every space.',
    required: true,
    options: [
      { id: 'option.pyramids.strong-context-open-phases', label: 'Old Kingdom work at Giza is strongly supported, while the date and purpose of every phase are not equally direct.' },
      { id: 'option.pyramids.settlement-dates-core', label: 'The workers’ settlement dates the Great Pyramid’s main core because both belong to Giza’s larger building system.' },
      { id: 'option.pyramids.cedar-dates-core', label: 'The older cedar is the strongest date for a pre-Khufu core because it was recovered from inside a sealed shaft.' },
      { id: 'option.pyramids.corridor-outweighs-context', label: 'The unknown corridor weakens the Old Kingdom attribution more than the dated log and complex context strengthen it.' },
    ],
  },
  {
    id: 'prompt.pyramids.build-evidence-chain', lessonId: 'lesson.egypt.pyramids-and-state-labor', kind: 'concise-explanation',
    question: 'Choose the Osirion, Hawara, or a stone vessel. What is directly observed, what might it suggest, and what evidence would help test that interpretation?',
    explanation: 'A strong response keeps the links separate: a measurement, inscription, scan, object, or ancient account is the observation; an earlier phase, maker, or method is an interpretation; excavation context, replication, or a dated construction relationship can test it.',
    required: true,
    minimumResponseLength: 40,
  },
];

export const pyramidsPowerStateLaborLesson: Lesson = {
  id: 'lesson.egypt.pyramids-and-state-labor',
  legacyAliases: ['imhotep', 'pyramids'],
  status: 'draft',
  title: 'Pyramids, Builders, and Evidence',
  masthead: 'Giza c. 2700–2500 BCE; comparisons from Predynastic Egypt to the present',
  place: 'Giza, Abydos, Hawara, and museum collections in Egypt',
  chronology: { startYear: -2700, endYear: -2500, display: 'Giza c. 2700–2500 BCE', approximate: true },
  significance: 'Egypt’s great monuments and stone vessels teach a crucial habit: evidence for a ruler, a use, a date, and a building phase must be connected rather than treated as the same claim.',
  sectionIdsRequired: ['section.pyramids.questions', 'section.pyramids.giza', 'section.pyramids.dating', 'section.pyramids.osirion', 'section.pyramids.hawara', 'section.pyramids.vessels', 'section.pyramids.world-check'],
  sections: [
    {
      id: 'section.pyramids.questions', heading: 'Six questions about one monument', purpose: 'Give learners a concrete method for separating evidence claims before comparing Egyptian cases',
      modules: [
        { id: 'module.pyramids.opening', type: 'prose', body: 'A royal name is found near an enormous stone monument. Does the name identify the builder? The owner? Someone who repaired it? Someone who used it centuries later? Those answers can overlap, but they are not automatically the same.\n\nThis lesson begins at the Great Pyramid of Giza, where several kinds of evidence strongly connect major work with the Old Kingdom and the reign of Khufu. It then compares the Osirion at Abydos, the Labyrinth site at Hawara, and finely worked stone vessels. These are not pieces of one monument story. Each is a separate test of the same six questions. The goal is not to protect one answer. It is to ask exactly what each piece of evidence can carry.', claimIds: ['claim.pyramids.separate-questions', 'claim.pyramids.earlier-regime-hypothesis'], sourceIds: ['source.pyramids.ifao-merer', 'source.pyramids.osirion-frankfort', 'source.pyramids.hawara-petrie', 'source.pyramids.vessels-metrology'] },
        { id: 'module.pyramids.six-questions', type: 'knowledge', eyebrow: 'What we can know', title: 'Keep each link visible', body: 'These five links lead to a sixth question: what purpose does the evidence actually support?', items: [
          { label: 'What survives?', detail: 'Start with the wall, object, writing, scan result, tool mark, or material that can be inspected.' },
          { label: 'What is its context?', detail: 'Ask where it was found, what surrounds it, and whether that relationship is undisturbed.' },
          { label: 'What event is dated?', detail: 'The age of wood, a stone surface, mortar, or a written reign may date different events.' },
          { label: 'Who is connected?', detail: 'A name may identify a builder, patron, owner, restorer, user, or later claimant.' },
          { label: 'What changed?', detail: 'A monument may be built, enlarged, repaired, or repurposed. A later use does not automatically reveal its first purpose.' },
        ], claimIds: ['claim.pyramids.separate-questions'], sourceIds: ['source.pyramids.dixon-cedar', 'source.pyramids.osirion-luminescence', 'source.pyramids.hawara-petrie'] },
      ],
    },
    {
      id: 'section.pyramids.giza', heading: 'What connects Giza to the Old Kingdom', purpose: 'Present the strongest converging Old Kingdom evidence while preserving its phase and purpose limits',
      modules: [
        { id: 'module.pyramids.giza-evidence', type: 'prose', body: 'The strongest case for Old Kingdom work at Giza does not depend on one cartouche. Merer’s logbook records a supervised crew transporting fine limestone by water to Akhet-Khufu—“Khufu’s Horizon”—late in Khufu’s reign. Royal temples, causeways, boat pits, cemeteries, and administration surround the pyramids. Radiocarbon results from monument mortar cluster broadly in the third millennium BCE, though some samples are older than expected. A nearby settlement preserves housing, storage, food production, workshops, and offices connected with Giza’s building programs.\n\nTogether, these sources show rulers and institutions organizing transport, skilled work, food, records, and ritual activity on a huge scale. They make a simple picture of one undifferentiated slave gang inadequate. They do not tell us whether every worker could refuse service, and the best-preserved settlement phase belongs mainly to the later Khafre and Menkaure projects. Labor evidence is therefore a powerful part of Giza’s history—not a shortcut that answers every question about the Great Pyramid.', claimIds: ['claim.pyramids.giza-old-kingdom-context', 'claim.pyramids.labor-stream'], sourceIds: ['source.pyramids.ifao-merer', 'source.pyramids.harvard-giza', 'source.pyramids.aera-settlement', 'source.pyramids.mortar-radiocarbon'] },
        { id: 'module.pyramids.giza-limit', type: 'knowledge', eyebrow: 'What we can know', title: 'Strong context is not a date for every stone', body: 'The evidence converges at the complex level, while some interior questions remain open.', items: [
          { label: 'It can show', detail: 'Khufu-era institutions moved fine limestone to the named Giza project, and Old Kingdom activity surrounded the pyramids.' },
          { label: 'It can support', detail: 'A major Old Kingdom royal building and cult program using many kinds of organized work.' },
          { label: 'It cannot prove alone', detail: 'That every hidden space, core block, or internal phase was made at the same moment.' },
          { label: 'It cannot recover', detail: 'The original purpose of every room or the experience and status of every person who worked there.' },
        ], claimIds: ['claim.pyramids.giza-old-kingdom-context', 'claim.pyramids.giza-context-limit', 'claim.pyramids.labor-stream'], sourceIds: ['source.pyramids.ifao-merer', 'source.pyramids.harvard-giza', 'source.pyramids.scanpyramids-corridor'] },
      ],
    },
    {
      id: 'section.pyramids.dating', heading: 'What a date actually dates', purpose: 'Show why material age, archaeological context, historical chronology, and architectural phase can disagree',
      modules: [
        { id: 'module.pyramids.dating-evidence', type: 'prose', body: 'Stone is difficult to date directly. Researchers often date material connected to it and then test the connection. Charcoal in mortar is tied to construction, but the burned wood might already have been old. A cedar fragment from a sealed shaft inside the Great Pyramid was radiocarbon dated to 3341–3094 BCE—older than Khufu—but that dates the tree’s growth, not automatically the shaft or pyramid. The wood may have been stored, reused, or cut from the long-lived inner part of a tree.\n\nA 2025 model using 160 radiocarbon measurements, including more short-lived plants, supports an Old Kingdom chronology older than some familiar textbook dates by decades and, in some schemes, roughly a century. That is a real revision. It is not a shift of thousands of years. Meanwhile, muon measurements found a previously unknown corridor in the Great Pyramid. The corridor is real; its purpose and date are still separate questions. New evidence can strengthen one part of a history while opening another.', claimIds: ['claim.pyramids.material-is-not-event', 'claim.pyramids.high-chronology', 'claim.pyramids.plan-incomplete'], sourceIds: ['source.pyramids.dixon-cedar', 'source.pyramids.high-chronology', 'source.pyramids.scanpyramids-corridor'] },
        { id: 'module.pyramids.prompt-context', type: 'prompt', promptId: 'prompt.pyramids.context-and-phase', claimIds: [], sourceIds: [] },
      ],
    },
    {
      id: 'section.pyramids.osirion', heading: 'The Osirion’s construction evidence', purpose: 'Let learners compare a named structural component with discordant surface-luminescence dates',
      modules: [
        { id: 'module.pyramids.osirion-evidence', type: 'prose', body: 'At Abydos, the Osirion looks and feels different from the decorated temple of Seti I beside it. Its enormous stone blocks and low, water-filled setting led early excavators to compare it with much earlier architecture. Excavation later found stronger construction relationships: bricks stamped for Seti I, walls tied into the temple-building sequence, and a granite cramp carrying Seti’s royal name beneath intact roofing. That last detail links at least one load-bearing assembly to Seti’s program rather than to a name carved on an exposed finished wall.\n\nA 2015 surface-luminescence study produced a genuine conflict. One sandstone estimate, about 1300 ± 570 BCE, broadly overlaps Seti’s era. One granite estimate was substantially earlier, around 1980 BCE.\n\nThe method estimates when a sampled stone face last received enough light before being covered. With only two samples of different materials, wide disagreement, and no independent repeat study, the results do not date the entire monument. The earlier estimate should not be erased. It could reflect an older component, a different exposure history, a surface that did not receive enough light to reset its clock, or measurement limits. The responsible conclusion is unresolved at the phase level: a substantial Seti I building program is directly supported, while an older component remains possible and testable.', claimIds: ['claim.pyramids.osirion-seti-assembly', 'claim.pyramids.osirion-date-conflict', 'claim.pyramids.osirion-unresolved'], sourceIds: ['source.pyramids.osirion-frankfort', 'source.pyramids.osirion-luminescence'] },
        { id: 'module.pyramids.osirion-compare', type: 'knowledge', eyebrow: 'Compare the evidence', title: 'Two strong clues answer different questions', body: 'Neither clue should be discarded, and neither can stand in for the whole building history.', items: [
          { label: 'Seti-marked cramp', detail: 'Directly connects one protected structural assembly to Seti I’s program.' },
          { label: 'Older granite result', detail: 'Dates the sampled surface under a model; it may indicate an older component or a different exposure history.' },
          { label: 'Missing link', detail: 'Replicated dates tied to known wall junctions could distinguish reused stone from an earlier construction phase.' },
        ], claimIds: ['claim.pyramids.osirion-seti-assembly', 'claim.pyramids.osirion-date-conflict', 'claim.pyramids.osirion-unresolved'], sourceIds: ['source.pyramids.osirion-frankfort', 'source.pyramids.osirion-luminescence'] },
      ],
    },
    {
      id: 'section.pyramids.hawara', heading: 'The Labyrinth at Hawara', purpose: 'Compare ancient testimony, excavated royal material, geophysics, and active excavation without flattening their conflicts',
      modules: [
        { id: 'module.pyramids.hawara-evidence', type: 'prose', body: 'At Hawara, ancient visitors described an immense building that later Europeans called the Labyrinth. They did not preserve one agreed story. Herodotus attributed it to twelve kings and said he saw the upper rooms. Manetho placed its builder in Dynasty XII. Other Greek and Roman writers recorded competing builders and uses. Pliny even preserved a tradition that placed construction 3,600 years before his own time; older printed versions read 4,600. That deep date is real evidence of an ancient tradition, even though its number is textually unstable and Pliny does not supply the chain behind it.\n\nArchaeology adds a different stream. Petrie recovered a robbed building bed and architectural material naming the Middle Kingdom rulers Amenemhat III and Sobekneferu. That strongly supports royal work and use in their era, but a loose inscribed block cannot date every foundation below it. Ground surveys in 2010 and 2024 detected organized anomalies south of the pyramid that may include surviving architecture. They cannot identify or date a wall without excavation.\n\nIn 2026, an Egyptian antiquities official reported that an SCA and Fayoum University team had begun excavating the Labyrinth area. That work can test whether older phases exist; until its contexts and dates are published, the result remains open.', claimIds: ['claim.pyramids.hawara-middle-kingdom-link', 'claim.pyramids.hawara-anomalies', 'claim.pyramids.hawara-traditions', 'claim.pyramids.hawara-excavation-test'], sourceIds: ['source.pyramids.hawara-petrie', 'source.pyramids.hawara-vlf', 'source.pyramids.hawara-ert', 'source.pyramids.hawara-pliny', 'source.pyramids.hawara-excavation'] },
        { id: 'module.pyramids.hawara-streams', type: 'knowledge', eyebrow: 'What we can know', title: 'Four evidence streams, four different jobs', body: 'The case becomes clearer when each source keeps its own job.', items: [
          { label: 'Ancient accounts', detail: 'Show what visitors, priests, and writers remembered or argued; their builder stories and dates conflict.' },
          { label: 'Inscribed material', detail: 'Shows Amenemhat III and Sobekneferu were connected to work and use at the complex.' },
          { label: 'Geophysical surveys', detail: 'Show where subsurface differences may exist; they do not provide a construction date.' },
          { label: 'Excavation', detail: 'Can expose wall relationships, sealed deposits, reused blocks, and material suitable for direct tests.' },
        ], claimIds: ['claim.pyramids.hawara-middle-kingdom-link', 'claim.pyramids.hawara-anomalies', 'claim.pyramids.hawara-traditions', 'claim.pyramids.hawara-excavation-test'], sourceIds: ['source.pyramids.hawara-petrie', 'source.pyramids.hawara-vlf', 'source.pyramids.hawara-ert', 'source.pyramids.hawara-pliny', 'source.pyramids.hawara-excavation'] },
      ],
    },
    {
      id: 'section.pyramids.vessels', heading: 'Stone vessels and early technical skill', purpose: 'Use metrology and provenance to establish early Nile skill without making geometry answer chronology or authorship by itself',
      modules: [
        { id: 'module.pyramids.vessels-evidence', type: 'prose', body: 'Long before the Great Pyramid, Nile craftspeople made vessels from hard stones such as granite, basalt, and porphyry. Objects from excavated Predynastic and Early Dynastic contexts establish thin walls, careful symmetry, drilling, polishing, and controlled rotation. Separately, a 2025 study measured 19 catalogued Petrie Museum vessels against modern machine-made and handmade groups. The ancient group’s overall quality overlapped the handmade comparison, while its inner and outer surfaces showed a distinctive ability to stay centered. The study inferred skilled abrasive rotation: the stone was turned while grinding tools and a sand-and-water mixture shaped it.\n\nSome privately held vessels have downloadable scans with even more surprising fitted geometry. Those measurements deserve inspection, not ridicule. But the scan of a shape cannot establish the physical object’s documented find history, nor can precision by itself name the tool or maker. The next useful tests are a secure chain from excavation to collection, comparable scanning, open processing records, microscopic tool marks, and successful manufacturing experiments.\n\nThe secure evidence already changes the story. A highly capable Nile stoneworking tradition existed before the famous dynastic monuments, and some vessels were old enough to be reused as heirlooms in later deposits. That earlier technical culture—the way knowledge, tools, and work were organized—may have differed greatly from later periods. Whether it also built an older phase of a particular monument must still be shown at that monument.', claimIds: ['claim.pyramids.vessels-early-skill', 'claim.pyramids.vessels-private-limit', 'claim.pyramids.earlier-regime-hypothesis'], sourceIds: ['source.pyramids.vessels-metrology', 'source.pyramids.vessels-abu-rawash', 'source.pyramids.vessels-private-scans'] },
        { id: 'module.pyramids.deep-time', type: 'knowledge', eyebrow: 'Earlier Nile histories', title: 'The Turin King List begins before the dynasties', body: 'The list begins with divine and primeval rulers before historical kings. Such records matter, but they are not construction labels.', items: [
          { label: 'They can show', detail: 'Egyptians did not imagine their own history beginning with the rulers whose monuments survive best.' },
          { label: 'They can preserve', detail: 'Names, successions, sacred memory, and ideas about peoples or powers before the familiar dynasties.' },
          { label: 'They cannot date alone', detail: 'A wall, vessel, or pyramid without a defensible link between the text and that object.' },
        ], claimIds: ['claim.pyramids.deep-time-memory', 'claim.pyramids.earlier-regime-hypothesis'], sourceIds: ['source.pyramids.turin-king-list', 'source.pyramids.vessels-metrology'] },
      ],
    },
    {
      id: 'section.pyramids.world-check', heading: 'World Check', purpose: 'Require learners to build a short observation-to-interpretation-to-test chain from one comparison case',
      modules: [
        { id: 'module.pyramids.prompt-chain', type: 'prompt', promptId: 'prompt.pyramids.build-evidence-chain', claimIds: [], sourceIds: [] },
        { id: 'module.pyramids.conclusion', type: 'prose', body: 'The evidence does not force a choice between “every structure was built exactly as later dynasties claimed” and “one lost civilization built everything.” It supports a harder and more interesting history. Old Kingdom institutions clearly carried out major work at Giza. Earlier Nile craftspeople already possessed remarkable technical skill. The Osirion combines a directly named Seti I structural element with one substantially earlier surface-luminescence estimate whose uncertainty and construction meaning remain unresolved. Hawara combines Middle Kingdom royal material with conflicting ancient histories, real subsurface anomalies, and a new excavation capable of testing deeper phases.\n\nAn earlier Nile cultural or technical regime of materially different character and ability is therefore a legitimate hypothesis—but one to test structure by structure. The best next evidence would join the links: a dated surface tied to a known wall junction, a sealed earlier deposit beneath primary masonry, an excavated construction interface, or a replicated tool process on a securely provenanced object. Critical thinking means neither closing the question early nor pretending every possibility has equal support.', claimIds: ['claim.pyramids.separate-questions', 'claim.pyramids.giza-old-kingdom-context', 'claim.pyramids.osirion-unresolved', 'claim.pyramids.hawara-excavation-test', 'claim.pyramids.vessels-early-skill', 'claim.pyramids.earlier-regime-hypothesis'], sourceIds: ['source.pyramids.ifao-merer', 'source.pyramids.osirion-frankfort', 'source.pyramids.osirion-luminescence', 'source.pyramids.hawara-petrie', 'source.pyramids.hawara-excavation', 'source.pyramids.vessels-metrology'] },
      ],
    },
  ],
  claimIds: pyramidsPowerStateLaborClaims.map((claim) => claim.id),
  sourceIds: pyramidsPowerStateLaborSources.map((source) => source.id),
  mediaIds: [],
  promptIds: pyramidsPowerStateLaborPrompts.map((prompt) => prompt.id),
};

export const pyramidsPowerStateLaborContent: AuthoredContentModule = {
  sources: pyramidsPowerStateLaborSources,
  claims: pyramidsPowerStateLaborClaims,
  prompts: pyramidsPowerStateLaborPrompts,
  lessons: [pyramidsPowerStateLaborLesson],
};
