import type { Claim, KnowledgeCard, Lesson, MediaAsset, Source, UnderstandingPrompt } from '../../src/domains/contracts';
import type { AuthoredContentModule } from '../assemble';
import { mediaLocator } from '../shared/media-locator';

export const urukSources: Source[] = [
  { id: 'source.met.uruk', title: 'Uruk: First City of the Ancient World', url: 'https://www.metmuseum.org/toah/hd/uruk/hd_uruk.htm', publisher: 'The Metropolitan Museum of Art', accessedOn: '2026-07-13', licenseOrUse: 'Institutional educational reference; runtime reuse not asserted', reviewStatus: 'review-required' },
  { id: 'source.britannica.uruk', title: 'Erech (Uruk)', url: 'https://www.britannica.com/place/Erech', publisher: 'Encyclopaedia Britannica', accessedOn: '2026-09-24', licenseOrUse: 'Editorial reference; runtime reuse not asserted', reviewStatus: 'review-required' },
  { id: 'source.unesco.ahwar', title: 'The Ahwar of Southern Iraq', url: 'https://whc.unesco.org/en/list/1481/', publisher: 'UNESCO World Heritage Centre', accessedOn: '2026-07-14', licenseOrUse: 'Property description available under CC-BY-SA IGO 3.0', reviewStatus: 'reviewed' },
  { id: 'source.unesco.ahwar-maps', title: 'The Ahwar of Southern Iraq: Maps and Geographical Data', url: 'https://whc.unesco.org/en/list/1481/maps/', publisher: 'UNESCO World Heritage Centre', accessedOn: '2026-07-14', licenseOrUse: 'Official World Heritage coordinates and public State Party nomination-map reference', reviewStatus: 'reviewed' },
  { id: 'source.ur.southern-mesopotamia', title: 'Southern Mesopotamia, Figure 28.1', url: 'https://people.bu.edu/chamley/HSFref/Ur2012CompanionArchANE.pdf', publisher: 'Jason Ur, in A Companion to the Archaeology of the Ancient Near East (Blackwell)', accessedOn: '2026-07-14', licenseOrUse: 'Copyrighted scholarly publication; used as a non-distributed geographic reference only', reviewStatus: 'reviewed' },
  { id: 'source.uruk.perruchini-2023-brb-residues', title: 'Revealing invisible stews: new results of organic residue analyses of Beveled Rim Bowls from the Late Chalcolithic site of Shakhi Kora, Kurdistan Region of Iraq', url: 'https://doi.org/10.1016/j.jasrep.2022.103730', publisher: 'Perruchini et al., Journal of Archaeological Science: Reports 48 (2023), 103730', accessedOn: '2026-09-24', licenseOrUse: 'Open access, CC BY 4.0; cited as a fact source; no text or images reproduced', reviewStatus: 'reviewed' },
  { id: 'source.met.beveled-rim-bowl', title: 'Beveled rim bowl, 62.70.25', url: 'https://www.metmuseum.org/art/collection/search/325431', publisher: 'The Metropolitan Museum of Art', accessedOn: '2026-09-24', licenseOrUse: 'Object record cited for date, findspot and dimensions; Open Access image not used', reviewStatus: 'reviewed' },
  { id: 'source.uruk.fassbinder-2019-magnetometry', title: 'Venice in the desert: Archaeological geophysics on the world’s oldest metropolis Uruk-Warka, the city of King Gilgamesh (Iraq)', url: 'https://www.academia.edu/40253397/Venice_in_the_desert_Archaeological_geophysics_on_the_world_s_oldest_metropolis_Uruk_Warka_the_city_of_King_Gilgamesh_Iraq_', publisher: 'Fassbinder, Ostner, Scheiblecker, Parsi and van Ess, in J. Bonsall (ed.), New Global Perspectives on Archaeological Prospection (Archaeopress, 2019), pp. 197–200', accessedOn: '2026-09-24', licenseOrUse: 'Copyrighted scholarly chapter; cited as a fact source only', reviewStatus: 'reviewed' },
  { id: 'source.uruk.michalowski-2003-lu-a', title: 'An Early Dynastic Tablet of ED Lu A from Tell Brak (Nagar)', url: 'https://cdli.earth/articles/cdlj/2003-3', publisher: 'Piotr Michalowski, Cuneiform Digital Library Journal 2003:3', accessedOn: '2026-09-24', licenseOrUse: 'Open scholarly article; cited as a fact source only', reviewStatus: 'reviewed' },
  { id: 'source.uruk.kovacs-gilgamesh', title: 'The Epic of Gilgamesh, Tablet I, translated by Maureen Gallery Kovacs', url: 'https://people.uncw.edu/deagona/myth/Gilgamesh%201-4.pdf', publisher: 'Stanford University Press, 1989 (electronic edition by Wolf Carnahan, 1998)', accessedOn: '2026-09-24', licenseOrUse: 'Copyrighted translation; one short line quoted, the rest paraphrased', reviewStatus: 'reviewed' },
  { id: 'source.archatlas.uruk-ur', title: 'Uruk and Ur', url: 'https://www.archatlas.org/atlas/visualisations/sitesfromsatellites/urukur/', publisher: 'ArchAtlas / Andrew Sherratt', accessedOn: '2026-07-14', licenseOrUse: 'Cited scholarly web reference; NASA imagery credited by the publisher', reviewStatus: 'reviewed' }
];

export const urukClaims: Claim[] = [
  { id: 'claim.uruk.administration', statement: 'Proto-cuneiform tablets and seals provide evidence for organized accounting and administration at Uruk.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.met.uruk'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.uruk.city-life', statement: 'City-scale life created opportunities for specialization while also requiring coordinated labor and creating unequal burdens.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.met.uruk', 'source.britannica.uruk'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.uruk.wetland-landscape', statement: 'Uruk, Ur, and Eridu developed on the shifting alluvial and wetland landscape of southern Mesopotamia; exact ancient river channels, marsh limits, and shoreline positions remain approximate.', kind: 'reconstruction', certainty: 'moderate', sourceIds: ['source.unesco.ahwar', 'source.ur.southern-mesopotamia', 'source.archatlas.uruk-ur'], reviewStatus: 'editorial-review-required' },
  { id: 'claim.uruk.largest-settlement', statement: 'By around 3200 BCE Uruk was the largest settlement in southern Mesopotamia, and possibly in the world.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.met.uruk'], reviewStatus: 'reviewed' },
  { id: 'claim.uruk.population-estimate', statement: 'A geophysics team estimates that the inner city of Uruk, about 555 hectares, held about 40,000 people by about 3000 BCE.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.uruk.fassbinder-2019-magnetometry'], reviewStatus: 'reviewed' },
  { id: 'claim.uruk.bowl-mass-find', statement: 'A single sounding (test trench) at Uruk produced a mass find of 1,520 beveled-rim bowls, published by Hans Nissen in 1970.', kind: 'observation', certainty: 'high', sourceIds: ['source.uruk.perruchini-2023-brb-residues'], reviewStatus: 'reviewed' },
  { id: 'claim.uruk.bowl-making', statement: 'Beveled-rim bowls were roughly made by hand or in a mould from clay tempered with chaff, lightly fired, uneven in form, and are found in their thousands at fourth-millennium BCE sites from southern Iraq and the Gulf to eastern Turkey and Iran.', kind: 'observation', certainty: 'high', sourceIds: ['source.uruk.perruchini-2023-brb-residues'], reviewStatus: 'reviewed' },
  { id: 'claim.uruk.bowl-size', statement: 'A beveled-rim bowl in the Metropolitan Museum of Art (62.70.25), excavated at Nippur and dated about 3300–3100 BCE, measures about 19 cm across and 8.2 cm high.', kind: 'observation', certainty: 'high', sourceIds: ['source.met.beveled-rim-bowl'], reviewStatus: 'reviewed' },
  { id: 'claim.uruk.ration-hypothesis', statement: 'Nissen proposed after the Uruk mass find that beveled-rim bowls were ration containers, so that institutions paid out food to workers in standard bowlfuls; assumed standard volumes have been challenged and the idea is not settled.', kind: 'interpretation', certainty: 'contested', sourceIds: ['source.uruk.perruchini-2023-brb-residues'], reviewStatus: 'reviewed' },
  { id: 'claim.uruk.ration-signs', statement: 'The archaic sign GU7, a human head with a beveled-rim bowl, means “to eat” and is read as “ration” in archaic texts; the sign NINDA is identified as picturing the bowl.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.uruk.perruchini-2023-brb-residues'], reviewStatus: 'reviewed' },
  { id: 'claim.uruk.bowl-debate', statement: 'The use of beveled-rim bowls is still debated: leavened-bread hypotheses have been most popular in recent decades, other proposals include salt, dairy processing and ritual use, and residue analysis at Shakhi Kora in northern Iraq found meat and possibly dairy foods, supporting multi-purpose explanations.', kind: 'interpretation', certainty: 'contested', sourceIds: ['source.uruk.perruchini-2023-brb-residues'], reviewStatus: 'reviewed' },
  { id: 'claim.uruk.rations-recorded', statement: 'Early pictographic signs on clay tablets at Uruk recorded the management of goods and the allocation of workers’ rations.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.met.uruk'], reviewStatus: 'reviewed' },
  { id: 'claim.uruk.professions-list', statement: 'The Standard Professions List (Lu A), a list of titles and occupations, is attested already in the Uruk IV period and was still copied in Old Babylonian times.', kind: 'observation', certainty: 'high', sourceIds: ['source.uruk.michalowski-2003-lu-a'], reviewStatus: 'reviewed' },
  { id: 'claim.uruk.precincts', statement: 'Uruk’s center held the Eanna and Anu precincts; the Anu ziggurat platform was crowned by the building called the White Temple.', kind: 'observation', certainty: 'high', sourceIds: ['source.britannica.uruk'], reviewStatus: 'reviewed' },
  { id: 'claim.uruk.cone-mosaics', statement: 'Monumental mud-brick buildings at Uruk were decorated with mosaics of painted clay cones embedded in the walls.', kind: 'observation', certainty: 'high', sourceIds: ['source.met.uruk'], reviewStatus: 'reviewed' },
  { id: 'claim.uruk.excavations', statement: 'Uruk has been excavated from 1928 onward by the German Oriental Society and the German Archaeological Institute.', kind: 'observation', certainty: 'high', sourceIds: ['source.britannica.uruk'], reviewStatus: 'reviewed' },
  { id: 'claim.uruk.canals-magnetometry', statement: 'Magnetometer surveys at Uruk (2001–2002 and 2016–2019, about 70 hectares) revealed a network of waterways, ship canals, harbors, water gates and landing places inside the city; their dates within the city’s long history are not fixed by the survey.', kind: 'observation', certainty: 'high', sourceIds: ['source.uruk.fassbinder-2019-magnetometry'], reviewStatus: 'reviewed' },
  { id: 'claim.uruk.wall-later', statement: 'In the Early Dynastic period (about 2900–2350 BCE) Uruk was surrounded by a massive wall, about 9 km long, which tradition credited to King Gilgamesh, who probably ruled around 2700 BCE.', kind: 'interpretation', certainty: 'high', sourceIds: ['source.met.uruk', 'source.britannica.uruk', 'source.uruk.fassbinder-2019-magnetometry'], reviewStatus: 'reviewed' },
  { id: 'claim.uruk.gilgamesh-wall-story', statement: 'The Epic of Gilgamesh opens by telling the listener to go up on the wall of Uruk, walk around it and inspect its brickwork, asking whether it is not made of kiln-fired brick.', kind: 'later-tradition', certainty: 'high', sourceIds: ['source.uruk.kovacs-gilgamesh'], reviewStatus: 'reviewed' },
  { id: 'claim.uruk.wall-fired-brick', statement: 'Magnetometer data suggest that parts of the inner and outer faces of Uruk’s city wall were built of fired brick, a detail not known before the survey.', kind: 'interpretation', certainty: 'moderate', sourceIds: ['source.uruk.fassbinder-2019-magnetometry'], reviewStatus: 'reviewed' }
];

export const urukMedia: MediaAsset[] = [
  { id: 'media.uruk.reconstruction', locator: mediaLocator('media.uruk.reconstruction'), alt: 'Aerial evidence-based reconstruction of ancient Uruk with a monumental precinct at its center', depictionMode: 'evidence-based-reconstruction', depictionLabel: 'Evidence-based reconstruction', rightsLabel: 'Chronos original reconstruction', sourceIds: ['source.met.uruk'], visualBriefRef: 'docs/architecture/uruk-vertical-slice.md#evidence-and-reconstruction-treatment', reviewStatus: 'provenance-review-required' },
  { id: 'media.uruk.site', locator: mediaLocator('media.uruk.site'), alt: 'Archaeological remains at the site of Uruk in the modern landscape', depictionMode: 'evidence', depictionLabel: 'Archaeological site photograph · surviving evidence', rightsLabel: 'Chronos educational use', sourceIds: ['source.met.uruk'], visualBriefRef: 'docs/architecture/uruk-vertical-slice.md#evidence-and-reconstruction-treatment', reviewStatus: 'provenance-review-required' },
  { id: 'media.uruk.clay-envelope', locator: mediaLocator('media.uruk.clay-envelope'), alt: 'Clay accounting envelope and tablet with impressed marks', depictionMode: 'evidence', depictionLabel: 'Artifact-focused · surviving evidence', rightsLabel: 'Chronos educational use', sourceIds: ['source.met.uruk'], visualBriefRef: 'docs/architecture/uruk-vertical-slice.md#evidence-and-reconstruction-treatment', reviewStatus: 'provenance-review-required' },
  { id: 'media.uruk.southern-mesopotamia-map', locator: mediaLocator('media.uruk.southern-mesopotamia-map'), alt: 'Illustrated map of the southern Mesopotamian plain showing the relative positions of Uruk, Ur, and Eridu, the Tigris and Euphrates river system, the Zagros highlands, and an approximate ancient Gulf and wetland margin', depictionMode: 'map', depictionLabel: 'Illustrative historical map · approximate ancient waterways and wetland margin', rightsLabel: 'Chronos original · Natural Earth base geography, Public Domain', sourceIds: ['source.unesco.ahwar-maps', 'source.ur.southern-mesopotamia', 'source.archatlas.uruk-ur'], visualBriefRef: 'docs/research/uruk-southern-mesopotamia-map.md', reviewStatus: 'provenance-review-required' }
];

export const urukPrompts: UnderstandingPrompt[] = [
  { id: 'prompt.uruk.administration-evidence', lessonId: 'lesson.uruk.first-city', kind: 'supported-selection', hint: 'Look at the marks in clay. What could a lasting record help people organize?', evidenceModuleIds: ['module.uruk.tablet-evidence'], question: 'Which evidence best supports organized administration at Uruk?', explanation: 'Tablets and seals are surviving evidence of record-keeping. A reconstruction painting is an interpretation, not direct evidence.', required: true, options: [{ id: 'option.uruk.reconstruction', label: 'A reconstruction painting of the city' }, { id: 'option.uruk.tablets', label: 'Administrative tablets and cylinder seals' }, { id: 'option.uruk.later-story', label: 'A later story about Uruk’s walls' }] },
  { id: 'prompt.uruk.opportunity-and-cost', lessonId: 'lesson.uruk.first-city', kind: 'concise-explanation', question: 'Name one opportunity and one cost or challenge of life in Uruk, using lesson evidence.', explanation: 'Extra food could support specialized work. But large projects needed coordinated labor, and benefits and burdens could be shared unequally.', required: true, minimumResponseLength: 20 }
];

export const urukLesson: Lesson = {

    id: 'lesson.uruk.first-city', legacyAliases: ['uruk'], title: 'Uruk: Life in an Early City', masthead: 'c. 3200 BCE', chronology: { startYear: -3500, endYear: -3000, display: 'approximately 3500–3000 BCE', approximate: true }, significance: 'When Uruk grew into a major city around 3200 BCE, coordinating work and resources at city scale changed daily life.',
    learningOutcome: 'You explored how food, work, and records connected city life, and how surviving evidence differs from reconstruction.', orientationMapModuleId: 'module.uruk.southern-mesopotamia-map', status: 'published', place: 'Southern Mesopotamia', heroMediaId: 'media.uruk.reconstruction', heroLabel: 'Evidence-based reconstruction', heroCaption: 'A reconstructed view of early Uruk based on archaeological evidence — not a photograph of the past.',

    sectionIdsRequired: ['section.uruk.masthead', 'section.uruk.opening-city-question', 'section.uruk.water-food-and-labor', 'section.uruk.the-built-city', 'section.uruk.tablets-and-administration', 'section.uruk.evidence-and-reconstruction', 'section.uruk.check-and-complete'],

    sections: [

      { id: 'section.uruk.masthead', heading: 'Uruk around 3200 BCE', purpose: 'Begin with place and scale', modules: [{ id: 'module.uruk.city-glance', type: 'prose', body: 'Around 3200 BCE, on the flat river plain of what is now southern Iraq, Uruk was the largest settlement in southern Mesopotamia, and perhaps in the world. By about 3000 BCE, one estimate puts some 40,000 people inside it. Food, work, worship, and record-keeping had to be organized at a scale no farming village had faced.', claimIds: ['claim.uruk.largest-settlement', 'claim.uruk.population-estimate', 'claim.uruk.city-life'], sourceIds: ['source.met.uruk', 'source.uruk.fassbinder-2019-magnetometry'] }, {

        id: 'module.uruk.southern-mesopotamia-map', type: 'historical-map', eyebrow: 'Place & landscape', title: 'A city shaped by water',

        body: 'Uruk stood near the Euphrates on a plain built from river silt, with marshes and the Gulf to the southeast. Over generations, rivers, channels, wetlands, and dry ground all shifted. Fields, food, and travel depended on water that would not stay put.',

        mediaId: 'media.uruk.southern-mesopotamia-map', periodLabel: 'c. 3200 BCE', focusPlace: 'Uruk', modernContext: 'Near modern Warka, Iraq',

        accessibleSummary: 'Uruk lies northwest of Ur and Eridu on the southern Mesopotamian plain. The Euphrates system runs along the western side, the Tigris system lies farther east toward the Zagros highlands, and a shifting wetland and Gulf zone lies to the southeast.',

        compactLabel: 'Illustrative map · ancient waterways approximate',

        coordinateNote: 'Uruk, Ur, and Eridu are placed using official UNESCO World Heritage coordinates.',

        uncertaintyNote: 'City locations follow UNESCO World Heritage coordinates. Ancient river channels, marshes, and the Gulf shoreline shifted over time and are shown approximately.',

        depictionStatus: 'illustrative-reconstruction', claimIds: ['claim.uruk.wetland-landscape'], sourceIds: ['source.unesco.ahwar', 'source.unesco.ahwar-maps', 'source.ur.southern-mesopotamia', 'source.archatlas.uruk-ur'],

      }] },

      { id: 'section.uruk.opening-city-question', heading: 'What makes a city?', purpose: 'Opening city question', modules: [{ id: 'module.uruk.city-question', type: 'prose', body: 'In a single test trench at Uruk, archaeologists found 1,520 bowls of the same kind.\n\nThey were not fine pottery. Each one was thick and rough, made of clay mixed with chaff, shaped by hand or pressed in a mould, and fired lightly, so no two came out quite alike. One now in the Metropolitan Museum of Art is about 19 centimeters across and 8 deep, small enough to hold in two hands. Bowls like these turn up by the thousands at sites from southern Iraq and the Gulf to the highlands of eastern Turkey and Iran. Archaeologists call them beveled-rim bowls, after their slanting lip.\n\nWhy would one place need so many cheap bowls? Archaeologists have argued about the answer for more than fifty years, and the argument leads straight into the bigger question of this lesson: what changes when thousands of people live and work together?', claimIds: ['claim.uruk.bowl-mass-find', 'claim.uruk.bowl-making', 'claim.uruk.bowl-size', 'claim.uruk.bowl-debate'], sourceIds: ['source.uruk.perruchini-2023-brb-residues', 'source.met.beveled-rim-bowl'] }, { id: 'module.uruk.scene', type: 'scene', title: 'Explore the scene', body: 'This view is a reconstruction. It places what excavators have found into one possible scene. Open each marker to see what that part is based on.', mediaId: 'media.uruk.reconstruction', hotspots: [{ label: 'Monumental precinct', detail: 'Great mudbrick temples stood in sacred precincts at the center. Some of their walls were decorated with mosaics of painted clay cones.' }, { label: 'Dense neighborhoods', detail: 'Mudbrick homes packed many households close together.' }, { label: 'Water routes', detail: 'Canals linked fields, food, and movement.' }], claimIds: ['claim.uruk.city-life', 'claim.uruk.cone-mosaics'], sourceIds: ['source.met.uruk'] }] },

      { id: 'section.uruk.water-food-and-labor', heading: 'Water, food, and labor', purpose: 'How the city kept moving', modules: [{ id: 'module.uruk.city-systems', type: 'knowledge', eyebrow: 'City systems', title: 'Irrigation, surplus, and coordinated work', body: 'One answer to the bowl puzzle came from the archaeologist Hans Nissen after that 1,520-bowl find: the bowls held rations. In this reading, institutions at Uruk collected grain and paid it back out to workers, a bowlful at a time. It is a strong idea, not a settled fact. But the city’s own records show the pattern it depends on: scribes tracked goods and workers’ rations on clay.\n\nCompare Çatalhöyük, the farming settlement in the last lesson, where families kept food in bins inside their own houses. At Uruk, grain also moved through large institutions. That could free people for other work, and it could give whoever controlled the stores power over everyone who depended on them.', items: [{ label: 'Water', detail: 'Canals carried river water toward fields and settlements.' }, { label: 'Food', detail: 'Grain handed out as rations could feed people who did not farm. Scribes at Uruk wrote a list of titles and jobs that was still being copied more than a thousand years later.' }, { label: 'Labor', detail: 'Canals, temples, and harvests all needed planning, many hands, and someone deciding whose hands.' }], claimIds: ['claim.uruk.ration-hypothesis', 'claim.uruk.rations-recorded', 'claim.farming.private-storage', 'claim.uruk.professions-list', 'claim.uruk.city-life'], sourceIds: ['source.uruk.perruchini-2023-brb-residues', 'source.met.uruk', 'source.farming.bogaard-2009-pantries', 'source.farming.catalhoyuk-architecture', 'source.uruk.michalowski-2003-lu-a', 'source.britannica.uruk'] }] },

      { id: 'section.uruk.the-built-city', heading: 'The built city', purpose: 'Read architecture as a clue', modules: [{ id: 'module.uruk.built-city', type: 'knowledge', eyebrow: 'Architecture', title: 'Monumental, everyday, and uncertain', body: 'At Uruk’s center stood two great sacred precincts, Eanna and Anu. In the Anu precinct, a high platform was crowned by the building archaeologists call the White Temple. Some mudbrick walls were covered in mosaics of painted clay cones, pushed in one by one. Every brick and cone was made, carried, and set by someone who had to be fed.', items: [{ label: 'Monumental', detail: 'Temples on raised platforms needed huge amounts of brick, planning, and labor.' }, { label: 'Everyday', detail: 'Homes and lanes held ordinary lives that left fewer traces.' }, { label: 'Uncertain', detail: 'A plan of walls cannot tell us exactly how every space felt or worked.' }], claimIds: ['claim.uruk.precincts', 'claim.uruk.cone-mosaics', 'claim.uruk.city-life'], sourceIds: ['source.britannica.uruk', 'source.met.uruk'] }] },

      { id: 'section.uruk.tablets-and-administration', heading: 'Tablets and administration', purpose: 'Museum evidence', modules: [{ id: 'module.uruk.tablet-evidence', type: 'evidence', title: 'Records pressed into clay', artifactLabel: 'Clay accounting record', body: 'Uruk’s scribes drew and pressed signs into damp clay to keep track of goods and workers’ rations, and rolled carved seals across it. One of their signs shows a human head with a beveled-rim bowl at its mouth. It means “to eat,” and in these early accounts scholars read it as “ration.” Another sign is thought to picture the bowl on its own. If those readings are right, the plain bowl from the trench found its way into the city’s writing.\n\nUruk links earlier farming communities to a world where records and ideas could travel beyond one person’s memory.', mediaId: 'media.uruk.clay-envelope', layout: 'side-by-side', lookHere: [{ label: 'Marks pressed into clay', detail: 'The marks survive. Reading what a particular mark meant still needs expert interpretation.', sourceIds: ['source.met.uruk'] }], claimIds: ['claim.uruk.administration', 'claim.uruk.rations-recorded', 'claim.uruk.ration-signs'], sourceIds: ['source.met.uruk', 'source.uruk.perruchini-2023-brb-residues'] }] },

      { id: 'section.uruk.evidence-and-reconstruction', heading: 'Evidence and reconstruction', purpose: 'Separate what survives from what is inferred', modules: [{ id: 'module.uruk.site-evidence', type: 'evidence', title: 'The city beneath the landscape', artifactLabel: 'Archaeological context', body: 'This is Uruk today: worn mounds of mudbrick rising from a flat plain. German teams have excavated here since 1928. Since 2001, survey teams have also walked the site with magnetometers, instruments that pick up faint magnetic traces of buried walls and filled-in channels without digging. Their maps show canals, harbors, and water gates threading through the city.\n\nLater Mesopotamians remembered Uruk through a king. Gilgamesh probably ruled around 2700 BCE, when a massive wall about 9 kilometers long surrounded the city, and tradition said he had ordered it built. The Epic of Gilgamesh opens by telling its listener: “Go up on the wall of Uruk and walk around.” Inspect the brickwork, the poem says: is it not made of kiln-fired brick? The magnetometer maps suggest that parts of the wall’s faces were indeed fired brick, a detail no one had known before.\n\nBut the wall came centuries after the city in this lesson, and a poem cannot tell us how Uruk worked in 3200 BCE. For that, the evidence is the site, the tablets, and those plain bowls. What the bowls held is still argued over: rations, bread, or something else. At one site in northern Iraq, chemists found traces of meat and perhaps dairy inside them. The city at the top of this lesson is a reconstruction that puts the evidence into one possible view. It is not a photograph of the past.', mediaId: 'media.uruk.site', claimIds: ['claim.uruk.excavations', 'claim.uruk.canals-magnetometry', 'claim.uruk.wall-later', 'claim.uruk.gilgamesh-wall-story', 'claim.uruk.wall-fired-brick', 'claim.uruk.bowl-debate', 'claim.uruk.administration'], sourceIds: ['source.britannica.uruk', 'source.uruk.fassbinder-2019-magnetometry', 'source.met.uruk', 'source.uruk.kovacs-gilgamesh', 'source.uruk.perruchini-2023-brb-residues'] }] },

      { id: 'section.uruk.check-and-complete', heading: 'World Check', purpose: 'Use evidence to explain', modules: [{ id: 'module.uruk.prompt-admin', type: 'prompt', promptId: 'prompt.uruk.administration-evidence', claimIds: [], sourceIds: [] }, { id: 'module.uruk.prompt-cost', type: 'prompt', promptId: 'prompt.uruk.opportunity-and-cost', claimIds: [], sourceIds: [] }] },

    ],

    claimIds: ['claim.uruk.administration', 'claim.uruk.city-life', 'claim.uruk.wetland-landscape', 'claim.uruk.largest-settlement', 'claim.uruk.population-estimate', 'claim.uruk.bowl-mass-find', 'claim.uruk.bowl-making', 'claim.uruk.bowl-size', 'claim.uruk.ration-hypothesis', 'claim.uruk.ration-signs', 'claim.uruk.bowl-debate', 'claim.uruk.rations-recorded', 'claim.uruk.professions-list', 'claim.uruk.precincts', 'claim.uruk.cone-mosaics', 'claim.uruk.excavations', 'claim.uruk.canals-magnetometry', 'claim.uruk.wall-later', 'claim.uruk.gilgamesh-wall-story', 'claim.uruk.wall-fired-brick', 'claim.farming.private-storage'], sourceIds: ['source.met.uruk', 'source.britannica.uruk', 'source.unesco.ahwar', 'source.unesco.ahwar-maps', 'source.ur.southern-mesopotamia', 'source.archatlas.uruk-ur', 'source.uruk.perruchini-2023-brb-residues', 'source.met.beveled-rim-bowl', 'source.uruk.fassbinder-2019-magnetometry', 'source.uruk.michalowski-2003-lu-a', 'source.uruk.kovacs-gilgamesh', 'source.farming.bogaard-2009-pantries', 'source.farming.catalhoyuk-architecture'], mediaIds: ['media.uruk.reconstruction', 'media.uruk.site', 'media.uruk.clay-envelope', 'media.uruk.southern-mesopotamia-map'], promptIds: ['prompt.uruk.administration-evidence', 'prompt.uruk.opportunity-and-cost'],

  };

export const urukCards: KnowledgeCard[] = [
  { id: 'card.place.uruk', title: 'Uruk', category: 'place', cardClass: 'foundation', date: { startYear: -3500, endYear: -3000, display: 'c. 3200 BCE', approximate: true }, place: 'Southern Mesopotamia', significance: 'A major early city where evidence reveals new scales of building, work, and administration.', revealTitle: 'A place worth remembering', revealBody: 'You earned Uruk by using evidence to explain how early city life changed human coordination.', depictionLabel: 'Evidence-based reconstruction', facts: ['Major city by about 3200 BCE', 'Located in southern Mesopotamia', 'Administrative tablets preserve accounting evidence'], lessonIds: ['lesson.uruk.first-city'], sourceIds: ['source.met.uruk', 'source.britannica.uruk'], mediaId: 'media.uruk.reconstruction', recallPrompt: 'How did food, specialized work, and records depend on each other in a city?', connections: [{ lessonId: 'lesson.writing.early-systems', label: 'From marks to writing', reason: 'Return to city record-keeping as you explore what marks could communicate.' }], unlockLessonId: 'lesson.uruk.first-city' }
];

export const urukContent: AuthoredContentModule = {
  sources: urukSources,
  claims: urukClaims,
  media: urukMedia,
  prompts: urukPrompts,
  lessons: [urukLesson],
  cards: urukCards,
};
