import { createHash } from 'node:crypto';

/**
 * A prompt ID stands for one question. Learners' answers are stored under it,
 * so once a prompt is published its identity must not change under the same
 * ID. The fingerprint is a hash of the fields that make up that identity:
 * lesson, kind, question text, options (ids and labels), best option,
 * required flag and minimum answer length.
 *
 * Explanation, option feedback and hint text are left out: they may be
 * revised under the same ID. Option order is left out too: reordering the
 * choices does not change the question or what counts as an answer.
 */
export const PROMPT_FINGERPRINTS_PATH = 'content/published-prompt-fingerprints.json';
export const PROMPT_FINGERPRINTS_COMMAND = 'npm run content:fingerprints';

type PromptLike = {
  id: string;
  lessonId: string;
  kind: string;
  question: string;
  required: boolean;
  bestOptionId?: string;
  minimumResponseLength?: number;
  options?: Array<{ id: string; label: string }>;
};
type LessonLike = { id: string; status: string; promptIds: string[] };

export type PromptFingerprintRecord = { lessonId: string; fingerprint: string; retired?: true };
export type PromptFingerprintFile = { about: string; prompts: Record<string, PromptFingerprintRecord> };

const ABOUT = `Generated by \`${PROMPT_FINGERPRINTS_COMMAND}\`. One entry per prompt ever published. A published prompt's identity (lesson, kind, question, options, best option, required flag, minimum answer length) must never change under the same ID: give the changed question a new ID instead. Retired entries stay so a retired ID is never reused for a different question. See docs/architecture/prompt-changes.md.`;

export function promptIdentity(prompt: PromptLike) {
  return {
    lessonId: prompt.lessonId,
    kind: prompt.kind,
    question: prompt.question,
    required: prompt.required,
    bestOptionId: prompt.bestOptionId ?? null,
    minimumResponseLength: prompt.minimumResponseLength ?? null,
    options: (prompt.options ?? []).map((option) => ({ id: option.id, label: option.label })).sort((a, b) => a.id.localeCompare(b.id)),
  };
}

export const fingerprintPrompt = (prompt: unknown) =>
  createHash('sha256').update(JSON.stringify(promptIdentity(prompt as PromptLike))).digest('hex');

/** Prompts in published lessons, keyed by ID. */
// Bundles arrive untyped (like validateContent's input), so non-strict builds and tests can pass them as they are.
export function publishedPrompts(prompts: readonly unknown[], lessons: readonly unknown[]) {
  const promptById = new Map((prompts as PromptLike[]).map((prompt) => [prompt.id, prompt]));
  const published = new Map<string, PromptLike>();
  for (const lesson of lessons as LessonLike[]) {
    if (lesson.status !== 'published') continue;
    for (const id of lesson.promptIds) {
      const prompt = promptById.get(id);
      if (prompt) published.set(id, prompt);
    }
  }
  return published;
}

const changedMessage = (id: string) =>
  `prompt ${id} changed its question, options, best answer, required flag or minimum length, but kept its ID. Learners' answers are stored under this ID, so give the changed prompt a new ID (and update the lesson's promptIds and prompt module), then run ${PROMPT_FINGERPRINTS_COMMAND}. Explanation, feedback and hint text may change under the same ID.`;

/** Errors when a published prompt's identity changed under the same ID, or the file is out of date. */
export function checkPromptFingerprints(prompts: readonly unknown[], lessons: readonly unknown[], recorded: PromptFingerprintFile | undefined): string[] {
  if (!recorded) return [`${PROMPT_FINGERPRINTS_PATH} is missing. Run ${PROMPT_FINGERPRINTS_COMMAND}.`];
  const errors: string[] = [];
  const published = publishedPrompts(prompts, lessons);
  for (const [id, prompt] of published) {
    const entry = recorded.prompts[id];
    if (!entry) { errors.push(`published prompt ${id} has no fingerprint. Run ${PROMPT_FINGERPRINTS_COMMAND}.`); continue; }
    if (entry.fingerprint !== fingerprintPrompt(prompt)) { errors.push(changedMessage(id)); continue; }
    if (entry.retired) errors.push(`prompt ${id} is published again. Run ${PROMPT_FINGERPRINTS_COMMAND}.`);
  }
  for (const [id, entry] of Object.entries(recorded.prompts)) {
    if (!entry.retired && !published.has(id)) errors.push(`prompt ${id} is no longer published. Run ${PROMPT_FINGERPRINTS_COMMAND} to mark it retired.`);
  }
  return errors;
}

/**
 * Records new published prompts and marks removed ones retired. It never
 * rewrites an existing fingerprint, so it cannot hide a changed question: that
 * is reported as an error instead.
 */
export function regeneratePromptFingerprints(prompts: readonly unknown[], lessons: readonly unknown[], recorded: PromptFingerprintFile | undefined): { file: PromptFingerprintFile; errors: string[] } {
  const previous = recorded?.prompts ?? {};
  const published = publishedPrompts(prompts, lessons);
  const errors: string[] = [];
  const next: Record<string, PromptFingerprintRecord> = {};
  for (const [id, entry] of Object.entries(previous)) {
    const prompt = published.get(id);
    if (!prompt) { next[id] = { lessonId: entry.lessonId, fingerprint: entry.fingerprint, retired: true }; continue; }
    if (entry.fingerprint !== fingerprintPrompt(prompt)) errors.push(changedMessage(id));
    next[id] = { lessonId: entry.lessonId, fingerprint: entry.fingerprint };
  }
  for (const [id, prompt] of published) {
    if (!previous[id]) next[id] = { lessonId: prompt.lessonId, fingerprint: fingerprintPrompt(prompt) };
  }
  const sorted = Object.fromEntries(Object.keys(next).sort().map((id) => [id, next[id]]));
  return { file: { about: ABOUT, prompts: sorted }, errors };
}
