import { ClaimSchema, JourneySchema, KnowledgeCardSchema, LessonSchema, MediaAssetSchema, SourceSchema, UnderstandingPromptSchema } from '../../domains/contracts';
export type ContentBundle={sources:unknown[];claims:unknown[];media:unknown[];prompts:unknown[];lessons:unknown[];journeys:unknown[];cards:unknown[]};
export function validateContent(input:ContentBundle){
 const errors:string[]=[]; const parse=<T>(items:unknown[],schema:any,label:string):T[]=>items.flatMap((item,i)=>{const r=schema.safeParse(item);if(!r.success){errors.push(`${label}[${i}]: ${r.error.issues.map((x:any)=>x.message).join(', ')}`);return []}return [r.data]});
 const sources=parse<any>(input.sources,SourceSchema,'source'),claims=parse<any>(input.claims,ClaimSchema,'claim'),media=parse<any>(input.media,MediaAssetSchema,'media'),prompts=parse<any>(input.prompts,UnderstandingPromptSchema,'prompt'),lessons=parse<any>(input.lessons,LessonSchema,'lesson'),journeys=parse<any>(input.journeys,JourneySchema,'journey'),cards=parse<any>(input.cards,KnowledgeCardSchema,'card');
 const all=[...sources,...claims,...media,...prompts,...lessons,...journeys,...cards]; const ids=new Set<string>(); for(const x of all){if(ids.has(x.id))errors.push(`duplicate ID: ${x.id}`);ids.add(x.id)}
 const sourceIds=new Set(sources.map(x=>x.id)),lessonIds=new Set(lessons.map(x=>x.id)),claimIds=new Set(claims.map(x=>x.id)),mediaIds=new Set(media.map(x=>x.id)),promptIds=new Set(prompts.map(x=>x.id));
 const refs=(owner:string,values:string[],known:Set<string>,kind:string)=>values.forEach(id=>{if(!known.has(id))errors.push(`${owner}: broken ${kind} reference ${id}`)});
 for(const l of lessons){const sectionIds=new Set<string>(); for(const s of l.sections){if(sectionIds.has(s.id))errors.push(`${l.id}: duplicate section ID ${s.id}`);sectionIds.add(s.id);for(const m of s.modules){refs(m.id,m.sourceIds,sourceIds,'source');refs(m.id,m.claimIds,claimIds,'claim');if(m.type==='evidence'&&!mediaIds.has(m.mediaId))errors.push(`${m.id}: broken media reference ${m.mediaId}`);if(m.type==='prompt'&&!promptIds.has(m.promptId))errors.push(`${m.id}: broken prompt reference ${m.promptId}`)}} refs(l.id,l.sectionIdsRequired,sectionIds,'required section');refs(l.id,l.sourceIds,sourceIds,'source');refs(l.id,l.claimIds,claimIds,'claim');refs(l.id,l.mediaIds,mediaIds,'media');refs(l.id,l.promptIds,promptIds,'prompt')}
 for(const c of claims)refs(c.id,c.sourceIds,sourceIds,'source'); for(const m of media){refs(m.id,m.sourceIds,sourceIds,'source');if(!m.depictionLabel)errors.push(`${m.id}: missing depiction label`)}
 for(const p of prompts)if(!p.explanation.trim())errors.push(`${p.id}: missing prompt explanation`);
 for(const j of journeys){const positions=new Set<number>();for(const chapter of j.chapters)for(const e of chapter.entries){if(positions.has(e.position))errors.push(`${j.id}: duplicate journey entry position ${e.position}`);positions.add(e.position);if(!lessonIds.has(e.lessonId))errors.push(`${e.id}: unreachable required journey entry ${e.lessonId}`)}}
 for(const c of cards){refs(c.id,c.lessonIds,lessonIds,'lesson');refs(c.id,c.sourceIds,sourceIds,'source');if(!lessonIds.has(c.unlockLessonId))errors.push(`${c.id}: invalid card unlock reference ${c.unlockLessonId}`);if(!mediaIds.has(c.mediaId))errors.push(`${c.id}: broken media reference ${c.mediaId}`)}
 return {success:errors.length===0,errors};
}
