import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowRight, Check, ChevronDown, X } from 'lucide-react';
import { chronosContent } from '../../content/chronos';
import type { ChronosContentBundle } from '../../content/assemble';
import { createPublishedJourneyCatalog, type CatalogJourney } from '../domains/journeys/catalog';
import { continueJourney, deriveJourneyProgress, setActiveLesson, type LearnerJourneyState } from '../domains/journeys/state';
import { createJourneyStateGateway, type JourneyStateGateway } from '../infrastructure/journeys/gateway';
import { createProgressGateway, type JourneyProgressSummary, type LearnProgressGateway } from '../learn/progress';

export function JourneySwitcher({ currentJourneyId, currentLessonId, content = chronosContent, journeyGatewayFactory = createJourneyStateGateway, progressGatewayFactory = createProgressGateway, navigate = (destination: string) => window.location.assign(destination) }: {
  currentJourneyId: string; currentLessonId: string; content?: ChronosContentBundle;
  journeyGatewayFactory?: () => Promise<JourneyStateGateway>; progressGatewayFactory?: () => Promise<LearnProgressGateway>; navigate?: (destination: string) => void;
}) {
  const dialogRef = useRef<HTMLDialogElement>(null); const gatewayRef = useRef<JourneyStateGateway>();
  const [state, setState] = useState<LearnerJourneyState>(); const [summaries, setSummaries] = useState<Record<string, JourneyProgressSummary>>({}); const [error, setError] = useState(''); const [attempt, setAttempt] = useState(0);
  const catalog = useMemo(() => createPublishedJourneyCatalog(content.journeys, content.lessons), [content]); const items = [catalog.worldHistory, ...Object.values(catalog.groups).flat()].filter((item): item is CatalogJourney => Boolean(item));
  const current = items.find((item) => item.id === currentJourneyId);
  useEffect(() => { let active = true; Promise.all([journeyGatewayFactory(), progressGatewayFactory()]).then(async ([journeyGateway, progressGateway]) => { gatewayRef.current = journeyGateway; const [snapshot, progress] = await Promise.all([journeyGateway.load(), progressGateway.loadJourneySummaries(content.lessons.filter((lesson) => lesson.status === 'published').map((lesson) => lesson.id))]); let next = snapshot.state; const journey = content.journeys.find((item) => item.id === currentJourneyId && item.status === 'published'); if (journey) { next = setActiveLesson(next, currentJourneyId, currentLessonId); await journeyGateway.save(next); } if (active) { setState(next); setSummaries(progress); setError(''); } }).catch(() => { if (active) setError('Journey choices could not be loaded.'); }); return () => { active = false; }; }, [attempt, content, currentJourneyId, currentLessonId, journeyGatewayFactory, progressGatewayFactory]);
  const switchTo = async (item: CatalogJourney) => { if (!state || !gatewayRef.current) return; const journey = content.journeys.find((entry) => entry.id === item.id)!; const next = continueJourney(state, journey, content.lessons); try { const saved = await gatewayRef.current.save(next); setState(saved.state); navigate(`/learn/${saved.state.journeys[item.id].activeLessonId}`); } catch { setError('Switching failed. Your lesson progress is unchanged.'); } };
  const sections = state ? [
    { title: 'Active journey', items: items.filter((item) => item.id === state.activeJourneyId) },
    { title: 'Other open journeys', items: items.filter((item) => item.id !== state.activeJourneyId && state.journeys[item.id]?.status === 'open') },
    { title: 'Saved for later', items: items.filter((item) => state.journeys[item.id]?.status === 'saved') },
  ] : [];
  return <div className="journey-switcher"><button className="journey-switcher-trigger" onClick={() => dialogRef.current?.showModal()} aria-haspopup="dialog"><span><small>{current?.kind === 'world-history' ? 'Learning' : 'Current journey'}</small><strong>{current?.title ?? 'World History'}</strong></span><ChevronDown /></button><dialog ref={dialogRef} className="journey-switcher-dialog" onClick={(event) => { if (event.target === dialogRef.current) dialogRef.current.close(); }}><header><div><p>Switch journey</p><h2>Your open paths</h2></div><button onClick={() => dialogRef.current?.close()} aria-label="Close journey switcher"><X /></button></header>{error && <p className="switcher-error" role="alert">{error} <button onClick={() => setAttempt((value) => value + 1)}>Retry</button></p>}{!state && !error && <p className="switcher-loading">Loading journeys…</p>}{state && <div className="switcher-sections">{sections.map((section) => <section key={section.title}><h3>{section.title}</h3>{section.items.length ? section.items.map((item) => { const journey = content.journeys.find((entry) => entry.id === item.id)!; const progress = deriveJourneyProgress(journey, content.lessons, summaries); const isActive = item.id === state.activeJourneyId; return <article key={item.id}><div><small>{item.kind === 'world-history' ? 'World History' : item.kind.replace('-', ' ')}</small><strong>{item.title}</strong><span>{progress.completed} of {progress.total} reviewed lessons</span></div>{isActive ? <Check aria-label="Active" /> : <button onClick={() => switchTo(item)}>Switch <ArrowRight /></button>}</article>; }) : <p>No other published journeys in this group.</p>}</section>)}</div>}<a className="switcher-library-link" href="/library">Explore the Library</a></dialog></div>;
}
