create schema if not exists chronos_private;
revoke all on schema chronos_private from public, anon, authenticated;

create table public.learners (id uuid primary key references auth.users(id) on delete cascade, created_at timestamptz not null default now());
create table public.content_lessons (id text primary key, snapshot_version text not null, published_at timestamptz, unique(id,snapshot_version));
create table public.journeys (id text primary key, snapshot_version text not null);
create table public.journey_entries (id text primary key, journey_id text not null references public.journeys(id), lesson_id text not null references public.content_lessons(id), position integer not null check(position>=0), required boolean not null default true, unique(journey_id,position));
create table public.knowledge_cards (id text primary key, snapshot_version text not null);
create table public.card_unlocks (lesson_id text primary key references public.content_lessons(id), card_id text not null references public.knowledge_cards(id));
create table public.legacy_id_aliases (legacy_id text primary key, canonical_id text not null, entity_kind text not null check(entity_kind in('lesson','card')), semantic_equivalence_approved boolean not null default false, review_note text not null);
create table public.lesson_progress (learner_id uuid not null references public.learners(id) on delete cascade, lesson_id text not null references public.content_lessons(id), status text not null default 'in_progress' check(status in('in_progress','completed')), started_at timestamptz not null default now(), completed_at timestamptz, primary key(learner_id,lesson_id), check((status='completed')=(completed_at is not null)));
create table public.section_resume_state (learner_id uuid not null, lesson_id text not null, section_id text not null, updated_at timestamptz not null default now(), primary key(learner_id,lesson_id), foreign key(learner_id,lesson_id) references public.lesson_progress(learner_id,lesson_id) on delete cascade);
create table public.understanding_prompt_attempts (id bigint generated always as identity primary key, learner_id uuid not null, lesson_id text not null, prompt_id text not null, response jsonb not null, attempted_at timestamptz not null default now(), foreign key(learner_id,lesson_id) references public.lesson_progress(learner_id,lesson_id) on delete cascade);
create index prompt_attempts_completion_idx on public.understanding_prompt_attempts(learner_id,lesson_id,prompt_id);
create table public.completion_commands (learner_id uuid not null references public.learners(id) on delete cascade, idempotency_key text not null, lesson_id text not null references public.content_lessons(id), result jsonb, created_at timestamptz not null default now(), primary key(learner_id,idempotency_key));
create table public.card_ownership (learner_id uuid not null references public.learners(id) on delete cascade, card_id text not null references public.knowledge_cards(id), acquired_at timestamptz not null default now(), source_lesson_id text not null references public.content_lessons(id), primary key(learner_id,card_id));

insert into public.content_lessons(id,snapshot_version,published_at) values ('lesson.farming.settlements','uruk-slice-v1',null),('lesson.uruk.first-city','uruk-slice-v1',now()),('lesson.writing.early-systems','uruk-slice-v1',null);
insert into public.journeys values('journey.world-history','uruk-slice-v1');
insert into public.journey_entries(id,journey_id,lesson_id,position) values ('entry.world-history.farming','journey.world-history','lesson.farming.settlements',0),('entry.world-history.uruk','journey.world-history','lesson.uruk.first-city',1),('entry.world-history.writing','journey.world-history','lesson.writing.early-systems',2);
insert into public.knowledge_cards values('card.place.uruk','uruk-slice-v1'); insert into public.card_unlocks values('lesson.uruk.first-city','card.place.uruk');
insert into public.legacy_id_aliases values('uruk','lesson.uruk.first-city','lesson',true,'ASH-53 approved semantic equivalence for explicit legacy completion only');

alter table public.learners enable row level security; alter table public.lesson_progress enable row level security; alter table public.section_resume_state enable row level security; alter table public.understanding_prompt_attempts enable row level security; alter table public.completion_commands enable row level security; alter table public.card_ownership enable row level security;
alter table public.content_lessons enable row level security; alter table public.journeys enable row level security; alter table public.journey_entries enable row level security; alter table public.knowledge_cards enable row level security; alter table public.card_unlocks enable row level security; alter table public.legacy_id_aliases enable row level security;

create policy learners_select on public.learners for select to authenticated using ((select auth.uid())=id); create policy learners_insert on public.learners for insert to authenticated with check ((select auth.uid())=id); create policy learners_update on public.learners for update to authenticated using ((select auth.uid())=id) with check ((select auth.uid())=id);
create policy progress_select on public.lesson_progress for select to authenticated using ((select auth.uid())=learner_id); create policy progress_insert on public.lesson_progress for insert to authenticated with check ((select auth.uid())=learner_id); create policy progress_update on public.lesson_progress for update to authenticated using ((select auth.uid())=learner_id) with check ((select auth.uid())=learner_id);
create policy resume_select on public.section_resume_state for select to authenticated using ((select auth.uid())=learner_id); create policy resume_insert on public.section_resume_state for insert to authenticated with check ((select auth.uid())=learner_id); create policy resume_update on public.section_resume_state for update to authenticated using ((select auth.uid())=learner_id) with check ((select auth.uid())=learner_id);
create policy attempts_select on public.understanding_prompt_attempts for select to authenticated using ((select auth.uid())=learner_id); create policy attempts_insert on public.understanding_prompt_attempts for insert to authenticated with check ((select auth.uid())=learner_id); create policy attempts_update on public.understanding_prompt_attempts for update to authenticated using ((select auth.uid())=learner_id) with check ((select auth.uid())=learner_id);
create policy commands_select on public.completion_commands for select to authenticated using ((select auth.uid())=learner_id); create policy commands_insert on public.completion_commands for insert to authenticated with check ((select auth.uid())=learner_id); create policy commands_update on public.completion_commands for update to authenticated using ((select auth.uid())=learner_id) with check ((select auth.uid())=learner_id);
create policy ownership_select on public.card_ownership for select to authenticated using ((select auth.uid())=learner_id); create policy ownership_insert on public.card_ownership for insert to authenticated with check ((select auth.uid())=learner_id); create policy ownership_update on public.card_ownership for update to authenticated using ((select auth.uid())=learner_id) with check ((select auth.uid())=learner_id);
create policy published_lessons_select on public.content_lessons for select to authenticated using(published_at is not null); create policy journeys_select on public.journeys for select to authenticated using(true); create policy entries_select on public.journey_entries for select to authenticated using(true); create policy cards_select on public.knowledge_cards for select to authenticated using(true); create policy unlocks_select on public.card_unlocks for select to authenticated using(true); create policy aliases_select on public.legacy_id_aliases for select to authenticated using(semantic_equivalence_approved);

grant select,insert,update on public.learners,public.lesson_progress,public.section_resume_state,public.understanding_prompt_attempts,public.completion_commands,public.card_ownership to authenticated; grant usage,select on sequence public.understanding_prompt_attempts_id_seq to authenticated; grant select on public.content_lessons,public.journeys,public.journey_entries,public.knowledge_cards,public.card_unlocks,public.legacy_id_aliases to authenticated;

create or replace function public.complete_lesson_and_acquire_card(p_lesson_id text,p_idempotency_key text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_learner uuid:=(select auth.uid()); v_required text[]:=array['prompt.uruk.administration-evidence','prompt.uruk.opportunity-and-cost']; v_card text; v_completion_count integer:=0; v_card_count integer:=0; v_result jsonb;
begin
 if v_learner is null then raise exception 'authentication required' using errcode='28000'; end if;
 if p_idempotency_key is null or length(trim(p_idempotency_key))<8 then raise exception 'invalid idempotency key' using errcode='22023'; end if;
 insert into public.learners(id) values(v_learner) on conflict do nothing;
 insert into public.completion_commands(learner_id,idempotency_key,lesson_id) values(v_learner,p_idempotency_key,p_lesson_id) on conflict do nothing;
 select result into v_result from public.completion_commands where learner_id=v_learner and idempotency_key=p_idempotency_key for update; if v_result is not null then return v_result; end if;
 if not exists(select 1 from public.completion_commands where learner_id=v_learner and idempotency_key=p_idempotency_key and lesson_id=p_lesson_id) then raise exception 'idempotency key reused for another lesson' using errcode='22023'; end if;
 if not exists(select 1 from public.lesson_progress where learner_id=v_learner and lesson_id=p_lesson_id) then raise exception 'learner progress not found' using errcode='42501'; end if;
 if p_lesson_id='lesson.uruk.first-city' and exists(select 1 from unnest(v_required) r where not exists(select 1 from public.understanding_prompt_attempts a where a.learner_id=v_learner and a.lesson_id=p_lesson_id and a.prompt_id=r)) then raise exception 'required prompt attempts missing' using errcode='23514'; end if;
 update public.lesson_progress set status='completed',completed_at=coalesce(completed_at,now()) where learner_id=v_learner and lesson_id=p_lesson_id and status<>'completed'; get diagnostics v_completion_count=row_count;
 select card_id into v_card from public.card_unlocks where lesson_id=p_lesson_id;
 if v_card is not null then insert into public.card_ownership(learner_id,card_id,source_lesson_id) values(v_learner,v_card,p_lesson_id) on conflict do nothing; get diagnostics v_card_count=row_count; end if;
 v_result:=jsonb_build_object('completion',case when v_completion_count=1 then 'newly-completed' else 'already-completed' end,'cardOwnership',case when v_card is null then 'not-configured' when v_card_count=1 then 'newly-acquired' else 'already-owned' end,'cardId',v_card);
 update public.completion_commands set result=v_result where learner_id=v_learner and idempotency_key=p_idempotency_key; return v_result;
end $$;
revoke all on function public.complete_lesson_and_acquire_card(text,text) from public,anon,service_role; grant execute on function public.complete_lesson_and_acquire_card(text,text) to authenticated;
